### ISSUE TITLE
Add support for changing local cache directory from `TURBO_CACHE_DIR` env var

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turbo#1004]
This is useful for CI/CD (so you do not need to pass `--cache-dir` to each command

- [ ] Add this check and logic similarly to other env var handlers in `run.go` here: https://github.com/vercel/turborepo/blob/main/cli/internal/run/run.go#L507. It should gracefully handle relative path (just like we do for `--cache-dir`
- [ ] Update `--cache-dir` reference docs to note that this can setting can also be configured via the `TURBO_CACHE_DIR` env var.  https://github.com/vercel/turborepo/blob/main/docs/pages/docs/reference/command-line-reference.mdx#--cache-dir

**Comment by belgattitude** [comment]
Link towards doc has changed, so here's from the official doc: https://turbo.build/repo/docs/reference/command-line-reference#--cache-dir

To some extend I would even extend the use-cases by exposing a cacheDir in the turbo.json config. Saving in nm folder for example is creating confusion in case it's cached (cache growing indefinitly) or switching branches. 

Note that nx allows to set it through config (was also a feature request)

https://nx.dev/concepts/how-caching-works#customizing-the-cache-location

```json
{
  "tasksRunnerOptions": {
    "default": {
      "options": {
        "cacheableOperations": ["build", "test"],
        "cacheDirectory": "/tmp/mycache"
      }
    }
  }
}
```

**Comment by anthonyshew** [comment]
Done!: https://turbo.build/repo/docs/reference/system-variables
