### ISSUE TITLE
Turborepo SvelteKit Template (without TS, with JSDoc)

### ISSUE THREAD

**Issue by git-no** [vercel/turbo#1015]
### Describe the feature you'd like to request

A Template for Sveltekit to install, as it is available for Turborepo with NextJS.
Turborepo SvelteKit Template (without TS, with JSDoc).

### Describe the solution you'd like

A Template for Sveltekit to install (including lint), as it is available for Turborepo with NextJS.
Maybe with Tailwind, but it is not required.
### Describe alternatives you've considered

-

**Comment by tknickman** [comment]
We do have one here!

https://github.com/vercel/turbo/tree/main/examples/with-svelte
