### ISSUE TITLE
Allow `run` to accept flags before tasks

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turbo#1094]
### Describe the feature you'd like to request

A pattern I've seen in some monorepos is to have shorthand filters, but necessarily specific tasks for each package or app in the root package.json. 

```
{
  "scripts": {
      "web": "pnpm --filter=web",
      "api": "pnpm --filter=api"
   }
}
```

Then teams can quickly run arbitrary package-specific tasks from the root without having to `cd` or write out long filters like so:

```sh
$ pnpm web dev  
# => runs pnpm --filter=web "dev"

$ pnpm api build  
# => runs pnpm --filter=api "build"
```

When you try to do this with `turbo` at the moment you get the following error: 

<img width="566" alt="CleanShot 2022-04-21 at 09 52 11@2x" src="https://user-images.githubusercontent.com/4060187/164473969-4ad72336-b120-4b07-90d7-56bddadaeedf.png">

### Describe the solution you'd like

`turbo run` should be able to accept flags before tasks to enable the above behavior. This should be possible even with our [hacky custom arg parsing:](https://github.com/vercel/turborepo/blob/main/cli/internal/run/run.go#L466) 

```
{
  "scripts": {
      "web": "turbo run --filter=web",
      "api": "turbo run --filter=api"
   }
}
```

```
$ pnpm web dev
# => runs turbo run --filter=web "dev"

$ pnpm api build  
# => runs turbo run --filter=api "build"
```

### Describe alternatives you've considered

N/A

**Comment by anthonyshew** [comment]
This looks like a stale to me, if I'm understanding hte problem statement correctly. If you're stumbling on this issue and think you have this problem, please open up a new issue.
