### ISSUE TITLE
globalDependencies doesn't revaluate on unset environment variable

### ISSUE THREAD

**Issue by zanona** [vercel/turbo#1099]
### What version of Turborepo are you using?

1.2.5

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

Whenever adding a `globalDependencies` relying on `$NODE_ENV`, the cache is only revaluated if `$NODE_ENV` is set to a non-empty value. If empty or unset, it will be ignored and turbo will run as if the last value had been provided.

### Expected Behavior

I would like that whenever `$NODE_ENV` was previously provided as `production` and then a second time, not provided at all, the cache would be revaluated. Since `production  != undefined`

### To Reproduce

turbo.json

```json
{
  "$schema": "https://turborepo.org/schema.json",
  "globalDependencies": ["$NODE_ENV"],
  "pipeline": {
    "lint": {
      "outputs": []
    }
  }
}
```
package.json
```json
{
  "name": "@scope/a",
  "scripts": {
    "lint": "echo NODE_ENV:$NODE_ENV",
  }
}
```

running with `NODE_ENV=production` (first time)
```
$ NODE_ENV=production npx turbo run lint --scope=@scope/a
• Packages in scope: @scope/a
• Running lint in 1 packages
@scope/a:lint: cache miss, executing 03b196778cd445c2
@scope/a:lint:
@scope/a:lint: > lint
@scope/a:lint: > echo NODE_ENV:$NODE_ENV
@scope/a:lint:
@scope/a:lint: NODE_ENV:production

 Tasks:    1 successful, 1 total
 Cached:    0 cached, 1 total
   Time:    319ms

```

running a second time without declaring `NODE_ENV` (should revaluate cache)
```
$ npx turbo run lint --scope=@scope/a
• Packages in scope: @scope/a
• Running lint in 1 packages
@scope/a:lint: cache hit, replaying output 03b196778cd445c2
@scope/a:lint:
@scope/a:lint: > lint
@scope/a:lint: > echo NODE_ENV:$NODE_ENV
@scope/a:lint:
@scope/a:lint: NODE_ENV:production <<<<<<<<<<<<<<<<<<<<<

 Tasks:    1 successful, 1 total
Cached:    1 cached, 1 total
  Time:    107ms >>> FULL TURBO

```

**Comment by mehulkar** [comment]
This should definitely work, I've added a test case in https://github.com/vercel/turbo/pull/6238 to make sure
