### ISSUE TITLE
Invalid cache output if changing files while running build

### ISSUE THREAD

**Issue by mcrowder65** [vercel/turbo#1146]
### What version of Turborepo are you using?

1.2.5

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When running `turbo run command`, if you switch the contents of the files after the cache check happened, but before the command finishes executing, turbo will cache the updates contents but the hashes don't actually match!

### Expected Behavior

Maybe turbo should run a hash at the end of a command to ensure the content didn't change while the command was running?

### To Reproduce

```
git clone https://github.com/mcrowder65/turborepo-example
yarn
yarn build
```
As soon as yarn build starts, update `apps/rs/src/App.js` to have `console.log("bug")`

After yarn build is done and everything is cached, run `serve -s apps/rs/build`, and you'll see `bug` being logged in the console.

Now go and delete that `console.log("bug")`, run `yarn build` again, and note it's cached. and run `serve -s apps/rs/build` again, and you'll see `bug` in the console.

**Comment by gsoltis** [comment]
Hmm, is there a specific use case where you need to update the contents during execution in the way that you describe? It seems like it would be a race condition.

If it only happens by accident, I'm somewhat inclined to say "don't do that", but if there's a particular scenario that this enables, it might be worth designing a way to handle it.

**Comment by muhaimin-anchorzero** [comment]
We have hit an issue similar to this. The most likely answer seems to be a race.

We build with `tsc`. `src` directory is declared as a cache input and `tsc` builds it and outputs the result to `dist`.
There have been multiple instances where the cached output was produced from code other than what was hashed.

In particular we have seen stale outputs and even missing outputs. `src/index.ts` is present at the time `turbo` hashed it, but `dist/index.js` is missing (and turbo re-runs do not rebuild).

Additionally verified this by investigating `node_modules/.cache/turbo`. After hitting this issue subsequent `turbo build` does not rebuild until we invalidate the cache by updating an input or forcing a build with `turbo run --force build`.

I understand that this isn't specifically a turbo issue and may be a `tsc --watch` process or some other thing that is causing this. It may be the case that others are experiencing this issue but do not know that it is this issue.

The suggestion to hash again before committing to the cache would not be an adequate fix as the source contents may be "incorrect" at just the perfect time when it is used but be restored to "correct" prior to the time the 2nd hash is computed.

I'm not sure how it could be fixed other than by making a copy of the sources into a dedicated build dir, running build, then copying the result out.

**Comment by anthonyshew** [comment]
Generally speaking, what's being described in this issue falls outside of the mental model of what Turborepo is reasonably capable of. We want to keep the mental model simple: Pre-determined inputs -> pre-determined outputs.

I'm going to close this out because:
- It's been open for quite awhile and hasn't garnered much interest.
- As stated above, this doesn't seem like something we are going to want to support. Or, at the very least, won't get prioritized.

P.S. There may be some overlap here with a "Watch Mode" that we're thinking about. I don't expect it will cover this use case - but mentioning it here nonetheless.
