### ISSUE TITLE
Template packages

### ISSUE THREAD

**Issue by spigelli** [vercel/turbo#1185]
### Describe the feature you'd like to request

Nx has the concept of generators, but they are very involved and doesn't really match with what hygen offers for file-wise generation which a lot of people might be used to. It'd be great if turbo repo had its own solution for this.

### Describe the solution you'd like

The ability to configure a package as a template and a `turbo creat-workspace-from-workspace-template <path-to-template-workspace> <path-to-new-workspace>`
> Different command name hopefully

Bonuses and subsequent features:
- Generation configuration and dynamic paths/handlebars
  - A template with a file in the workspace's tree with name `[componnentName].tsx` could match some component args you input
  - Component args could be passed to the file template instance with handlebars templating
- Plugins for templates
- Merge template changes into template workspace instances 

### Describe alternatives you've considered

Copy paste workspace

**Comment by nathanhammond** [comment]
We absolutely are looking into something like this. As we're an abstraction over package managers more than an abstraction over application code we are likely to choose a different boundary to draw the line about what type of generators we support but one path beyond that is creating a system by which others are able to ... plug in the gaps. 😅

**Comment by spigelli** [comment]
Yeah this would probably go in as auxiliary tooling. Basically just needs to be something like [this haskell project generator](https://hackage.haskell.org/package/rob), don't think it'd be so great to have people learn how to use yeoman or hygen syntax, something super simple to implement. But something where file/folder templating matches how next's dynamic filenames look and how these [remix-esque nested layouts](https://twitter.com/leeerob/status/1521659624516030466?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1521659624516030466%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.redditmedia.com%2Fmediaembed%2Fuhxfnd%3Fresponsive%3Dtrueis_nightmode%3Dfalse) are going to function in the upcoming next router update would be super cool. Cause if I'm right a majority of turborepo users are managing next/component library projects?

**Comment by tknickman** [comment]
Hey @spigelli we haven't forgotten about this! We're actively looking into an option here, and I'm consolidating feedback for the feature. As part of this, I'm going to close this issue to consolidate the conversation to single spot.

Closing in favor of https://github.com/vercel/turbo/issues/4511
