### ISSUE TITLE
allow specifying options before task in `turbo run`

### ISSUE THREAD

**Issue by unional** [vercel/turbo#1207]
### Describe the feature you'd like to request

Able to do `turbo run --filter=<selector> <task>`

This way, we can define "alias" script at the top level `package.json` like this:

```json
{
  "scripts": {
    "pkg-a": "turbo run --filter=pkg-a"
  }
}
```

and able to use it like this (using `yarn` as an example):

```sh
yarn pkg-a build
```

Currently, we have to use the underlying package manager to do that:

```json
{
  "scripts": {
    "pkg-a": "yarn workspace pkg-a"
  }
}
```

### Describe the solution you'd like

In general, allow the options to go in front of the arguments.

### Describe alternatives you've considered

If that is not desirable (due to optional param for the options),
then maybe have a separate command like `yarn workspace` would be an alternative

**Comment by gsoltis** [comment]
@unional we are moving towards [cobra](https://github.com/spf13/cobra) for our commandline parsing, which I think will be the right way to address this.

**Comment by mehulkar** [comment]
This looks like it works now, I tried it with a simple repo with

```
turbo run -F app-a build
```
