### ISSUE TITLE
Running `eslint --fix` with turbo restores unlinted file from cache 

### ISSUE THREAD

**Issue by florian-richter** [vercel/turbo#1220]
### What version of Turborepo are you using?

1.2.8

### What package manager are you using / does the bug impact?

npm, Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

We use a `lint:fix` script in our package.json which run `eslint *.ts --fix`.
It usually runs correctly, but our team found an edge case where turbo reports a cache hit and the unlinted file is restored.

### Expected Behavior

I would expect that the file is cached in the fixed state and if the cache hits, the fix is reapplied.

### Steps:
1. Create project with `npx create-turbo@latest` (select default answers for everything)
2. Edit files mentioned below
3. `npm run lint:fix` => no cache hit, file fixed
```
> turborepo-basic-shared@0.0.0 lint:fix
> turbo run lint:fix

• Packages in scope: docs, eslint-config-custom, tsconfig, ui, web
• Running lint:fix in 5 packages
ui:lint:fix: cache miss, executing 26612e11fce8e58e
ui:lint:fix: 
ui:lint:fix: > ui@0.0.0 lint:fix
ui:lint:fix: > eslint *.ts* --fix
ui:lint:fix: 

 Tasks:    1 successful, 1 total
Cached:    0 cached, 1 total
  Time:    1.283s 
```
4. Change `index.tsx` back to the unlinted state
5. `npm run lint:fix` => cache hit, file not fixed (= contains double semi)
```
> turborepo-basic-shared@0.0.0 lint:fix
> turbo run lint:fix

• Packages in scope: docs, eslint-config-custom, tsconfig, ui, web
• Running lint:fix in 5 packages
ui:lint:fix: cache hit, replaying output 26612e11fce8e58e
ui:lint:fix: 
ui:lint:fix: > ui@0.0.0 lint:fix
ui:lint:fix: > eslint *.ts* --fix
ui:lint:fix: 

 Tasks:    1 successful, 1 total
Cached:    1 cached, 1 total
  Time:    61ms >>> FULL TURBO
```

### The edited files:
/package.json
```json
{
  "name": "turborepo-basic-shared",
  "version": "0.0.0",
  "private": true,
  "workspaces": [
    "apps/*",
    "packages/*"
  ],
  "scripts": {
    "lint:fix": "turbo run lint:fix"
  },
  "devDependencies": {
    "prettier": "latest",
    "turbo": "latest"
  },
  "engines": {
    "npm": ">=7.0.0",
    "node": ">=14.0.0"
  },
  "packageManager": "npm@8.9.0"
}

```

/turbo.json
```json
{
  "pipeline": {
    "lint:fix": {
      "outputs": ["**/*.ts", "**/*.tsx", "**/*.js"]
    }
  }
}

```

.eslintrc.js
```js
module.exports = {
  root: true,
  // This tells ESLint to load the config from the package `eslint-config-custom`
  extends: ["custom", "eslint:recommended"],
  settings: {
    next: {
      rootDir: ["apps/*/"],
    },
  },
};
```

/packages/ui/package.json
```json
{
  "name": "ui",
  "version": "0.0.0",
  "main": "./index.tsx",
  "types": "./index.tsx",
  "license": "MIT",
  "scripts": {
    "lint:fix": "eslint *.ts* --fix"
  },
  "devDependencies": {
    "@types/react": "^17.0.37",
    "@types/react-dom": "^17.0.11",
    "eslint": "^7.32.0",
    "eslint-config-custom": "*",
    "react": "^17.0.2",
    "tsconfig": "*",
    "typescript": "^4.5.2"
  }
}
```

/packages/ui/index.tsx
```tsx
export * from "./Button";

true;;
```

<sub>[TURBO-1507](https://linear.app/vercel/issue/TURBO-1507/running-eslint-fix-with-turbo-restores-unlinted-file-from-cache)</sub>

**Comment by mattpocock** [comment]
It looks like the `outputs` here are mis-specified. `outputs` are used for when a command _produces output files_. Since linting doesn't produce output files (only console output) I think you might be better served by specifying these as an empty array.

**Comment by florian-richter** [comment]
It uses `eslint --fix` which modifies the source files. As this takes considerable time (assuming many rules and many files), it would be nice if this was cached correctly.

**Comment by sppatel** [comment]
Instead of outputs being all your entire source - which seems excessive - could you enable content caching for aslant itself and JUST have eslint.cache be the input (or possible the output) - I think this could help invalidate it correctly.

**Comment by dobesv** [comment]
Did you ever figure this out?  Generally tools like this don't like it when the input and output are the same file, but I guess if it works, it works!

**Comment by anthonyshew** [comment]
This is a misconfiguration issue rather than a Turborepo bug. Will close!
