### ISSUE TITLE
--ignore flag is not working for build commands in package scripts

### ISSUE THREAD

**Issue by gyfchong** [vercel/turbo#1227]
### What version of Turborepo are you using?

1.2.9

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

I have setup an `apps` folder and a `packages` folder and I want to only run build on the `packages` folder when I use `yarn build`

Using this command, the flag is ignored and my apps folder is still built.
```
"build": "turbo run build --ignore=\"apps/**/*\" ",
```

However running this test command, seems to ignore correctly:
```
"test": "turbo run test --ignore=\"apps/**/*\" ",
```

### Expected Behavior

When using the --ignore flag on `turbo run build`, the given directory/file is ignored.

### To Reproduce

1. Setup a repo with 2 folders, `apps` and `packages`
3. Setup turborepo
4. Add `"build": "turbo run build --ignore=\"apps/**/*\" ",` to your package json
5. Run command
6. Observe that the apps folder is not ignored.

<sub>[TURBO-1505](https://linear.app/vercel/issue/TURBO-1505/ignore-flag-is-not-working-for-build-commands-in-package-scripts)</sub>

**Comment by danawoodman** [comment]
Same here, literally copy-pasted from [the docs](https://turbo.build/repo/docs/reference/command-line-reference#--ignore) `turbo run build --ignore="apps/**/*"` but build is running in the `apps/` folder

```json
{
  "scripts": {
    "build:packages": "turbo run build --ignore=\"apps/**/*\"",
  }
}
```

Seems ignore is broken?

**Comment by NexZhu** [comment]
Same here `--ignore` flag not working even directly run from the terminal. MacOS

**Comment by danawoodman** [comment]
Any maintainers wanna chime in?

**Comment by mehulkar** [comment]
Hey all, thanks for the report, I'll take it to the team!

**Comment by arlyon** [comment]
Hello, the `--ignore` flag is designed to be used in tandem with `--filter`. I have added a change in https://github.com/vercel/turbo/pull/6780 which enforces this along with some integration tests.
