### ISSUE TITLE
--global-deps is ignored

### ISSUE THREAD

**Issue by cinan** [vercel/turbo#1230]
### What version of Turborepo are you using?

1.2.8

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

Turbo ignores [--global-deps](https://turborepo.org/docs/reference/command-line-reference#--global-deps) value. Tested in vanilla `npx create-turbo` repo.

### Expected Behavior

Turbo shouldn't ignore the switch.

### To Reproduce

```
npx create-turbo@latest
yarn lint # cache miss; ok
echo "// ignore" >> packages/eslint-config-acme/index.js # to break cache
yarn lint --global-deps="packages/eslint-config-acme/*.js" # cache hit, should be miss
```

I tried to define `globalDependencies` in `turbo.json` instead of `--global-deps` switch and in that way turbo missed cache correctly.

**Comment by ThomZz** [comment]
Turbo version : 1.2.8
Windows 10

The behavior when specifying the "globalDependencies" property in turbo.json seem indeed broken .. Anything that I put in there seems ignored.. 

With the "--global-deps" flag, it seems to work only partially, as only files that are directly at the root of my workspace (ex: --globalDeps="file.json") are considered. Any file that are at least one level deep in a directory (ex: --globalDeps="directory/file.json") are ignored.

**Comment by gsoltis** [comment]
This does indeed look like a bug. 

I think adding the global deps in `turbo.json` will work as a workaround, but this flag should also work. Thanks for the report!

**Comment by nathanhammond** [comment]
After a conversation we may be deprecating this functionality as:
- it does not work presently, implying that nobody is relying on it.
- `turbo.json` is a better place for this information in every scenario we are able to identify.

Can you help us understand the use-case where specifying via command line would be better than via `turbo.json`?

**Comment by cinan** [comment]
In general, when running `test/dev/build/...` scripts I don't care about eslint configuration. But when running `lint` (and only then), I want to depend on extra eslint configuration file. Currently after eslint configuration I mustn't forget to use `--force` when running `lint` script.

My root `package.json` would look like:

```
"scripts": {
    "build": "turbo run build",
    "dev": "turbo run dev",
    "lint": "turbo run lint --global-deps=...",
}
```

**Comment by nathanhammond** [comment]
> want to depend on extra eslint configuration file

Is that lint configuration file in your repository? You can specify that file to be included as a dependency when `lint`ing using something that looks like `"inputs": ["../../.eslintrc.js"]`. Also, if you use our recommended linting setup, this is also not typically a requirement. An example of that setup can be found here:

https://github.com/vercel/turborepo/blob/main/examples/basic/.eslintrc.js

**Comment by cinan** [comment]
I wasn't aware of the `inputs` option. It seems I don't need anymore `--global-deps`. Thanks!
