### ISSUE TITLE
Forward stdin

### ISSUE THREAD

**Issue by marvinroger** [vercel/turbo#1235]
### Describe the feature you'd like to request

Hi!

I have a pretty standard setup, where I have a `dev` script running `nodemon`. `nodemon` allows to type a special `rs` command to stdin, triggering a restart of the process, which is very useful.

It works fine when ran directly, but it does not work through turbo, as turbo does not forward stdin to the underlying process.

### Describe the solution you'd like

Maybe a task definition in `turbo.json` could have a `forwardStdin` option, which would, when enabled, forward stdin!
I think `forwardStdin: true` should be mutually exclusive with `cache: true`, because stdin could impact the result of the task.

<sub>[TURBO-588](https://linear.app/vercel/issue/TURBO-588/pipe-stdin-to-non-concurrent-tasks)</sub>

**Comment by MohamedLamineAllal** [comment]
`pnpm run publish`  is a workflow that i want to have. And i have otp code that i have to provide making it interactive. Doesn't work through turbo.

**Comment by gsoltis** [comment]
`forwardStdin` is an interesting idea. I think it would have scheduling implications as well, only one task at a time would be able to grab it

**Comment by MyNameReallySux** [comment]
Any input on the priority/interest in this from the Vercel team? Any major engineering blockers?

It seems like this would be possible without too much complexity as long as `--concurrency=1` and  `--cache=false`. This is something I would attempt to fix, but not too awesome at Rust 😞. If someone can give me a quick pointer as to where this code would need to be implemented in the repo, I may attempt to fix in the future when I get some time.

**Comment by gsoltis** [comment]
I think if we're going to do this, we would need to have the restrictions you mention (`--concurrency=1` and `--cache=false` or set to false in `turbo.json`) which amounts to: 1 task at a time, and don't write to the cache. I think we can eventually relax these restrictions, but doing so has implementation and scheduling concerns. Namely, what to do with two potentially-concurrent tasks that both want `stdin`. But we don't have to tackle that to get something out.

So that brings us to the syntax. I *think* the proposal for adding `forwardStdin: true` to the task in `turbo.json` would work, since it's a property of the task being run.

**Comment by dgarciamuria** [comment]
Today I run into an use case in which maybe having `cache: true` as optional would be helpful. In our workflow we leverage git-secret to store encrypted secrets and sometimes you get asked for the passphrase to decrypt them, but the password it self wont change the output of the command, it either runs or fails. Does it make sense?

**Comment by macseem** [comment]
Yeah, this would be super helpful, 
as cases like running react native app with dependencies makes you not being able to use "metro" commands

**Comment by appleseed-iii** [comment]
another use case is for a turbo command which runs `prisma db push`, which sometimes has interactive output like `To apply this change we need to reset the database, do you want to continue? All data will be lost. › (y/N)`

**Comment by thedevdavid** [comment]
another use case is Prisma migrations. After running `prisma migrate dev` with Turbo, I saw the successful migrations log and then nothing happened, the CLI was just hanging. Then a couple of mins later I realized that it was probably waiting for input but it couldn't go through Turbo and yep I was right.

After ctrl+c exiting the command, I was able to see the last line `Enter a name for the new migration:`

**Comment by clickclickonsal** [comment]
Another use case is with [expo](https://docs.expo.dev/) when running `expo start`. 🙇🏼

**Comment by mctrafik** [comment]
Not being able to run generators, builders, surveys etc feels like a deal-breaker. I'm investigating monorepo tools and for comparison, other tools do not suffer this obvious limitation!

**Comment by sang-au** [comment]
I am using turbo repos with expo and I can not enter r in the command line to refresh the bundle while development, please fix it

**Comment by federicobadini** [comment]
As mentioned in a [linked shopify cli issue](https://github.com/Shopify/cli/issues/1341) also the `shopify dev` command seems to have issues with turbo

**Comment by MickL** [comment]
[Drizzle](https://orm.drizzle.team/) is also unusable without this :/

**Comment by EduardoSimon** [comment]
I'm having the same issue when running jest in --watch mode.

**Comment by flogy** [comment]
Would be interested in this feature too, to forward commands to Metro in React Native projects.

**Comment by garrettparris** [comment]
graph protocol / graph nodes unusable without this

**Comment by MickL** [comment]
Hey guys, two weeks ago Turborepo released a [new Teminal UI](https://turbo.build/blog/turbo-1-13-0#new-terminal-ui). This seems to be the solution or not?

Unfortunately there was no reporting back in
 this issue @chris-olszewski @mehulkar - But maybe I am wrong and it is not the solution?

I tried it and it seems to work, but the console output is cut off so I cant see what I am doing:
<img width="986" alt="Bildschirmfoto 2024-04-03 um 21 48 12" src="https://github.com/vercel/turbo/assets/5103210/b712b549-08b2-4deb-b32d-ced6d2832c7e">

Also it bothers me that when I only have on task running (which is common e.g. for Drizzle) it still shows this task UI and I need to jump into the task with enter key. Instead Turbo could notice I am executing just one task and just show me the output of this task with nothing around it.

**Comment by anthonyshew** [comment]
To update here, @MickL is correct that our current plan is to enable this with the new terminal UI.

If you'd like to try out the new UI and have feedback, please add it to the RFC: https://github.com/vercel/turbo/discussions/7802

**Comment by anthonyshew** [comment]
We've now shipped this functionality as a part of 2.0: https://turbo.build/blog/turbo-2-0#watch-mode

**Comment by nullndr** [comment]
I can't understand why this issue has been closed since the OP issue is still present in the latest version (`2.0.4`).

The shopify cli can't be used, even when the task is selected.

**Comment by jetaggart** [comment]
Watch mode is not the same as forwarding stdin, for example I cannot use the react native debugger from CLI without forwarding stdin

**Comment by anthonyshew** [comment]
Apologies, I linked the wrong heading: https://turbo.build/blog/turbo-2-0#interactive-tasks

Edited my post two above this one.

**Comment by jetaggart** [comment]
Amazing, thank you! Definitely had me confused for a second!

**Comment by mcnaveen** [comment]
Hi @anthonyshew It's not still enabling the interactive CLI.
For example. In this project (https://vercel.com/templates/next.js/turborepo-react-native)
Nothing is passed to StdIn. 

cc: @leerob

**Comment by anthonyshew** [comment]
@mcnaveen Can you create a separate Issue? Thanks.

**Comment by eluchsinger** [comment]
Still having the same issue. I followed prisma's guide for Turborepo, but the migration gets stuck when it should be asking for a name. When I cancel the process, the output suddenly appears: `Enter a name for the new migration:`
