### ISSUE TITLE
Ungraceful termination leaves turbo meta files around

### ISSUE THREAD

**Issue by sppatel** [vercel/turbo#1268]
### What version of Turborepo are you using?

1.2.9

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When running a task and then terminating that task via Ctrl-C - depending on the input complexity of that task - termination can leave repository in a bad state with temp files around.

```
drwxr-xr-x    - sachin.patel 19 May 12:24 0c44f2e517f3b41f/
.rwxrwxr-x   44 sachin.patel 19 May 12:24 0c44f2e517f3b41f-meta.json*
drwxr-xr-x    - sachin.patel 19 May 12:24 0ca02e8cfde14602/
.rwxrwxr-x   44 sachin.patel 19 May 12:24 0ca02e8cfde14602-meta.json*
drwxr-xr-x    - sachin.patel 19 May 12:24 0e6e43c97fbf832d/
.rwxrwxr-x   44 sachin.patel 19 May 12:24 0e6e43c97fbf832d-meta.json*
drwxr-xr-x    - sachin.patel 19 May 12:24 0fe27e653c076444/
.rwxrwxr-x   44 sachin.patel 19 May 12:24 0fe27e653c076444-meta.json*
drwxr-xr-x    - sachin.patel 19 May 12:24 0205d9fe6f0d6c23/
.rwxrwxr-x   44 sachin.patel 19 May 12:24 0205d9fe6f0d6c23-meta.json*
drwxr-xr-x    - sachin.patel 19 May 12:24 021458ea25e1e1cb/
.rwxrwxr-x   44 sachin.patel 19 May 12:24 021458ea25e1e1cb-meta.json*
drwxr-xr-x    - sachin.patel 19 May 12:24 03aa2cc194b2abfa/
.rwxrwxr-x   44 sachin.patel 19 May 12:24 03aa2cc194b2abfa-meta.json*
drwxr-xr-x    - sachin.patel 19 May 12:24 04093098fc837bc0/
.rwxrwxr-x   44 sachin.patel 19 May 12:24 04093098fc837bc0-meta.json*
drwxr-xr-x    - sachin.patel 19 May 12:24 04764d4fe1e86dea/
.rwxrwxr-x   44 sachin.patel 19 May 12:24 04764d4fe1e86dea-meta.json*
drwxr-xr-x    - sachin.patel 19 May 12:24 06ac4cf9c017ddf8/
.rwxrwxr-x   43 sachin.patel 19 May 12:24 06ac4cf9c017ddf8-meta.json*
drwxr-xr-x    - sachin.patel 19 May 12:24 06d464e9998db120/
.rwxrwxr-x   44 sachin.patel 19 May 12:24 06d464e9998db120-meta.json*
drwxr-xr-x    - sachin.patel 19 May 12:24 07f0d46fd16d7874/
.rwxrwxr-x   44 sachin.patel 19 May 12:24 07f0d46fd16d7874-meta.json*
drwxr-xr-x    - sachin.patel 19 May 12:24 09fc28c94b0d1ba1/
.rwxrwxr-x   44 sachin.patel 19 May 12:24 09fc28c94b0d1ba1-meta.json*
drwxr-xr-x    - sachin.patel 19 May 12:24 0903eebd4e79df9a/
.rwxrwxr-x   44 sachin.patel 19 May 12:24 0903eebd4e79df9a-meta.json*
drwxr-xr-x    - sachin.patel 19 May 12:24 094540b882a45b28/
.rwxrwxr-x   45 sachin.patel 19 May 12:24 094540b882a45b28-meta.json*
drwxr-xr-x    - sachin.patel 19 May 12:24 1d5f655502bceea4/
.rwxrwxr-x   44 sachin.patel 19 May 12:24 1d5f655502bceea4-meta.json*
drwxr-xr-x    - sachin.patel 19 May 12:24 1dfd23a9c6016c61/
.rwxrwxr-x   45 sachin.patel 19 May 12:24 1dfd23a9c6016c61-meta.json*
```

Also leads to errors such as this in the console..

```
Hashing error: cannot find package-file hash for @fooo/package-#*.ts!**/*.jsx!**/*.tsx!*.js!*.jsx!*.ts!**/*.js!*.tsx!../../config/eslint/!../../tools/eslint-plugin-i18next-parser/dist/!.eslintrc.js!i18next-parser.config.js!tsconfig.eslint.js
```

There is not an easy way to clean this up.

### Expected Behavior

Terminating turbo via Ctrl-C or killing the pid - should not leave turbo related temp files around.  Or better, don't write these to the repo root (and a temp folder instead)

### To Reproduce

Create a task with a large number of packages and fine grained inputs (including files at root using path traversal).  Midway though the execution - Ctrl-C a few times to try to get the process terminated.

Check your repository dir and the directory will be flooded with turbo related files as shown.

**Comment by sppatel** [comment]
This actually happens where you have a path traversal input.

**Comment by gsoltis** [comment]
Agreed, `turbo` should not be leaving these around.

**Comment by marekbrainhub** [comment]
Is there a timeline for a fix for this issue?

**Comment by jonaslindstr** [comment]
> There is not an easy way to clean this up.

With GNU find I have managed to clean up some of the mess with `find -maxdepth 1 -regextype egrep -regex './[0-9a-f]{16}($|-meta.json)' -exec rm -rf {} +`. Combined with `git clean -fn` this works ok.

> Agreed, `turbo` should not be leaving these around.

I agree with OP that it would be good if they were not created in the first place. Can a git-ignored directory be used, like `.turbo`?

I haven't been able to consistently reproduce the error, but it started appearing after a refactoring commit which updated all workspaces plus `turbo.json`. Rebasing an existing workspace on top of that commit triggered the error.

**Comment by gsoltis** [comment]
Is this still happening with version `1.5.5` (latest as of now)?

These files should be exclusively written in the cache directory. If they are still ending up elsewhere, are you by any chance customizing the cache directory? It is normally `node_modules/.cache/turbo`

**Comment by gsoltis** [comment]
I'm still having trouble reproducing this issue, so I'd like to confirm some details:
 - This happens only when hitting `Ctrl+C` during a long-running task
 - There's something (`outputs`?) in `turbo.json` that does path traversal up to files at the root
 - The cache folder is left as the default (`node_modules/.cache/turbo`)
 - The working directory flag is not being used (`--cwd`)
 
 Could someone who's experiencing this problem share either a minimal repro or the relevant piece of `turbo.json`?

**Comment by anthonyshew** [comment]
Hey, folks! I'm going to close this one as a stale due to inactivity and a lack of reproduction link.

If you're still running into this issue, please open up a fresh issue with a repro!
