### ISSUE TITLE
Generate task summary/result file at the end of execution

### ISSUE THREAD

**Issue by sppatel** [vercel/turbo#1279]
### Describe the feature you'd like to request

Having a summary in json or textual format that indicates for a given task which ones where executed successfully via a cache hit vs a fresh execution.  While the execution log does tell us this its not parsable at the end of the run.  There may be follow operations in a CI build (such as publish) that need to happen only on packages that were actually re-built (and not replayed from a cache hit).  Today there isn't a way after a turbo run to easily identify which ones where re-played and which ones where executed.  

### Describe the solution you'd like

A turbo-[task]-summary.json produced after an execution that provides detailed summary info for a given task - specicially which packages where replayed and which ones were executed.  The summary could also include other meta data such as success/failure info, elapsed time, etc.

This summary can then be parsed by non turbo tasks to determine follow up actions that need to occur.  In my case, publishing only the packages that were re-built.

### Describe alternatives you've considered

Alternatviely is to `tee` the log to a file and then grep and parse lines with "cache miss".

**Comment by dobesv** [comment]
If this output in a format that CI tools could ingest (e.g. junit xml files) that might be neat as well, you could report that back to CircleCI or whatever and they could show the summary.

**Comment by cbm-egoubely** [comment]
@sppatel I think this is handled now (cf. [`--summarize`](https://turbo.build/repo/docs/reference/command-line-reference#--summarize) Turbo CLI option).

**Comment by mehulkar** [comment]
Just found this issue 🤦🏾 , thanks for the comment @cbm-egoubely , closing down
