### ISSUE TITLE
Missed file changes or false cache hits when no VCS is used

### ISSUE THREAD

**Issue by antonk52** [vercel/turbo#1280]
### What version of Turborepo are you using?

1.2.9

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

In a project with no or unsupported VCS turborepo misses source code changes

1. Build a package and its dependencies to populate cache(example `turbo run build --filter=pkg-2...`)
2. Run the command again to see FULL TURBO(no need to do build again)
3. Change a source file of a dependency package that should invalidate cache for all builds
4. Run build command for a package and its dependencies again
5. File change is ignored and FULL TURBO is seen(false cache hit for the package and its dependencies)

### Expected Behavior

The cache should have been invalidated and turbo should have rerun build commands to build from source.

### To Reproduce

I have created a repository with a minimal example where I can consistently reproduce the issue
https://github.com/antonk52/turbo-caching-issue

**Comment by jknoxville** [comment]
I tried to look into this last year but couldn't figure out where the logic is for deciding whether a package needs to be rebuilt. In theory it should be quite simple to add a file-based fallback in the case of no (or unsupported VCS) that just looks at last modified times etc. Would anyone be able to point me to this? I'd like to have a crack at fixing it but don't know where to start.

**Comment by anthonyshew** [comment]
Hey, folks! I'm going to close this as stale since it's pretty old and hasn't seen much interest!

If there's a major appetite for a feature like this and I'm not seeing it, please do open an RFC in Discussions!
