### ISSUE TITLE
Loose loginUrl config on "link" command

### ISSUE THREAD

**Issue by ThibautMarechal** [vercel/turbo#1281]
### What version of Turborepo are you using?

1.2.11

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

When running the `link` command, if we have the 'loginUrl' configured in the `.turbo/config.json` file, it will be removed.

## Example: 
*Initial content*
``` 
// .turbo/config.json
{
  "apiUrl":"http://localhost:8080/turbo/api", 
  "loginUrl": "http://localhost:8080/turbo/login"
}
```
*After runnning the command `turbo link` and succeffuly linked the repository with a remote cache server*
```
// .turbo/config.json
{
  "teamId":"team_e0ec3412-a694-452a-8a1d-8e53e2ec19c0",
  "apiUrl":"http://localhost:8080/turbo/api"
}
```

### Expected Behavior

It should keep the `loginUrl` configuration.

### To Reproduce

No need of a custom remote cache server to reproduce it. It can be done by setting the default value ("https://vercel.com") and running the `link` command

**Comment by jaredpalmer** [comment]
Confirmed

**Comment by ThibautMarechal** [comment]
Seems to be fixed with the latest release. I'm closing the issue
