### ISSUE TITLE
Don't bust cache on new workspace packages

### ISSUE THREAD

**Issue by TxHawks** [vercel/turbo#1304]
### Describe the feature you'd like to request

With pnpm (and possibly other package managers too), every time a new workspace package is added, the lock file changes and the cache is busted for all tasks on all packages.

Many design systems manage every component as an individual package, both for versioning and for a better, more granular cache. In such repositories, adding a workspace package is a very common event, that needlessly makes the cache a lot less useful and defeats the purpose of a granular cache.

This is also not needed for correctness, since the cache of relevant tasks in dependent packages  will be busted automatically either through changes/additions to `package.json` or the `dependsOn` field in `turbo.json`.

### Describe the solution you'd like

If the only changes detected in the lock file are related to workspace packages, the cache should not be invalidated.

### Describe alternatives you've considered

I can't think of any alternative other than keeping things as they currently are with a very inefficient cache in such scenarios

**Comment by dobesv** [comment]
Based on the documentation I believe it will parse lockfiles, at least `yarn.lock`, and only consider dependencies relevant to each workspace.  However, I'm not sure if that applies to npm package-lock files or really how it works for yarn, as the docs are not very clear on this point.

**Comment by TxHawks** [comment]
I'm not sure about Yarn - but to the best of my knowledge, yarn doesn't add workspace dependencies to the lockfile anyway - but with pnpm, any change to the lockfile seems to bust the cache completely

**Comment by dobesv** [comment]
Take a look at https://turborepo.org/docs/core-concepts/caching#hashing at the end there's a note that for yarn it parses the lockfile, but apparently not for npm and pnpm for whatever reason.

Yarn uses the same lockfile for all the workspaces in a project, and it gets modified by any change to dependencies (presumably as with npm and pnpm).

**Comment by dobesv** [comment]
I guess if you take a look at why npm/pnpm are not currently supported you could try to fix it and submit a PR.

**Comment by niudai** [comment]
My Related Discussion: https://github.com/vercel/turborepo/discussions/1501

**Comment by Dwlad90** [comment]
Any update on parsing of the pnpm lock file? We have many and frequently changing packages, which basically eliminates turborepo's value proposition for us. We really don't want to give up pnpm or Turborepo, but as things stand, we will have to

**Comment by gsoltis** [comment]
Supporting `pnpm` and other lockfiles is a current area of active development. First to get `prune` working with `pnpm`, but the same lockfile parsing should be reusable to get more granular dependency tree hashing per-package

**Comment by TxHawks** [comment]
Thank you. This is great

**Comment by Moriz-code** [comment]
@gsoltis Is there any expected timeframe on this?

**Comment by nathanhammond** [comment]
@Moriz-code no ETA until we start the effort; we always have to weigh any task against our other priorities.

**Comment by Dwlad90** [comment]
Has this been fixed in `1.6.1`. Caching now seem largely unaffected by changes to internal packages

**Comment by attila** [comment]
It definitely is an issue with `1.6.3` on npm, while I don't recall this on versions prior to 1.6.x. Any change to package-lock.json triggers all jobs on all workspaces 😮

**Comment by gsoltis** [comment]
`turbo` now hashes only the dependencies used by each workspace, so this should be working now. Are you still seeing cache invalidations? If so, what package manager are you using?

**Comment by Dwlad90** [comment]
> `turbo` now hashes only the dependencies used by each workspace, so this should be working now. Are you still seeing cache invalidations? If so, what package manager are you using?

I installed a new package from NPM in one of the workspaces and the problem still exists. When running a command through `turbo` an on any package see `workspace:build: cache miss, executing HASH`

We use pnpm.

The environment:
node: v18.12.1
pnpm: v7.27.0
Turbo: v1.7.4

**Comment by gsoltis** [comment]
@Dwlad90 just to confirm, the hash changes for _every_ package, not just the ones that depend on the package you added a dependency to?

**Comment by chris-olszewski** [comment]
Hi @Dwlad90, I noticed that your in the diff of the lockfile the existing entries for `through`, `for-each`, `event-target-polyfill`, and `eslint-module-utils` were all changed. Can you quick use `pnpm why -r` to see which of your workspaces depend on these packages? If your monorepo root depends on any of these than invalidating the entire cache is expected.

I'm closing and locking this as turbo now supports this behavior for all of the major package managers. If anyone encounters an erroneous cache miss after a package was added please open a new one that includes a reproduction or at the very least the output of `git diff $LOCKFILE`.
