### ISSUE TITLE
Provide a granular way to depend on OS / Architecture

### ISSUE THREAD

**Issue by gsoltis** [vercel/turbo#1315]
### Describe the feature you'd like to request

Some tasks, particularly tests and builds for non-frontend, non-backend binaries, behave differently on different OSes and architectures. `turbo` should be able to be easily configured to not cache results across platforms / architectures

### Describe the solution you'd like

Most likely something in `turbo.json` to apply either monorepo-wide or per-task.

### Describe alternatives you've considered

Environment variables can be used, but require every person or process who interacts with `turbo` to have them set appropriately.

<sub>[TURBO-2047](https://linear.app/vercel/issue/TURBO-2047/provide-a-granular-way-to-depend-on-os-architecture)</sub>

**Comment by mehulkar** [comment]
Related: #4124

**Comment by anthonyshew** [comment]
Documented in #7072
