### ISSUE TITLE
Negative filter not respected for transitive dependencies

### ISSUE THREAD

**Issue by maschwenk** [vercel/turbo#1319]
### What version of Turborepo are you using?

1.2.14

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Turbo's `filter` does not seem to respect the same semantics as `pnpm`'s. For instance, with a DAG like:

```
package_a 
   |
    -----> package_i_dont_want_to_build
```

This command works and brings no packages into scope
```
turbo --filter=package_i_dont_want_to_build --filter='!package_i_dont_want_to_build`
```

This command
```
turbo --filter=package_a --filter='!package_i_dont_want_to_build`
```
builds `package_a` and `package_i_dont_want_to_build`.

### Expected Behavior

A negative filter should be absolute and `--filter='!package_i_dont_want_to_build'` should mean that that package is never built, regardless of the DAG. For reference, this _does_ work when using `pnpm`'s filters.

### To Reproduce

Described in the bug

**Comment by kraenhansen** [comment]
@gsoltis I can elaborate on the use-case, I'm facing: We have `package-a` which depends on `package-b` on our local machines we want `package-b` to build when building `package-a` but on CI, we want to issue a slightly different command to build `package-b` (we want to prebuilt our binary without debug symbols). So we want to issue the build command separately and simply skip building `package-b` to avoid it overriding the output.

**Comment by maschwenk** [comment]
@kraenhansen yeah `only` I believe is just for ignoring dependencies of pipeline commands, so if you had `test` depending on `build` you could skip running build when you call test for a one off.

@gsoltis The use case I'm looking at is developing a dev server. Right now we boot up a file watcher that spawns a dev server. We enumerate the dependencies of the `app` with `pnpm`, and then watch those file paths for changes. When there's a change to those paths, we tell `pnpm` to build the packages that have changed. `pnpm` is strict and if you pass a package with a filter, it'll just build that package, and not care about its dependencies unless you actually add the `...` e.g. `--filter=blah...`. Because almost all `turbo` workspaces will have:

```
 "build": {
    "dependsOn": ["^build"]
  }
```
that means there's really no way to prevent it from doing those dependent builds, even if they are cached. I guess because we're caching the dependent rebuilds shouldn't matter, because turbo should realize that if I'm asking it to rebuild a package, it shouldn't rebuild its children unless they've changed, it just seems like it'd be nice to not have to even evaluate the cache in those scenarios. Maybe we should just change our config to:

```
 "build": {
    "dependsOn": ["build"]
  }
```

and then when we really want to build dependents we can explicitly call that. Would love to jump in a call/zoom to go over this dev server use case, wondering if you have better options. We do some nonstandard stuff in our dev server like hot reloads and lazy-require patching that wouldn't jive well with just replacing it with a nodemon setup like I've seen in the docs. Just curious if there are better paved paths here for that use case.

**Comment by maschwenk** [comment]
Ok looks like one way I'm able to achieve what I want is:

```json
"pipeline": {
    "build": {},
    "buildAllWithDependents": {
      "dependsOn": ["^build"]
    }
},
```

and then I can choose when I want to have the flowdown builds happening vs not. Unsure of the implications of this, but I think should work for my usecase. Still curious if there are better recommendations for the dev-server use case. 

_____________________

One other use case we had was where we an E2E project depending on an app (our only app-level dependency) and this would mean if we called `turbo build --filter=e2e` it would build our app code, which we didn't want because we wanted it to run in a dev server mode, but that's sorta a secondary and more niche use-case. We've since decided to ban dependencies on apps.

**Comment by maschwenk** [comment]
@kraenhansen noting that the above doesn't actually work, because calling `turbo build` as defined above will mean that the packages won't build their dependencies, but they also won't build in topological order. If you truly want to run things ignoring topological order, you can achieve this all a bit simpler by just using the `parallel` flag. Still trying to think through better options here.

**Comment by nathanhammond** [comment]
We would typically recommend building a separate dependency graph, possibly using synthetic tasks to accomplish this. Filtering at the command line is not an easily-shareable configuration mechanism, and it's way better to maintain within a declarative `turbo.json`.
