### ISSUE TITLE
Full cache build still very slow

### ISSUE THREAD

**Issue by MichealXie** [vercel/turbo#1340]
### What version of Turborepo are you using?

1.2.16

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When I run `turbo run build --filter=./packages/*`, it can successfully cache and replaying, but the speed is very slow compare to
![148454607-f65de1fb-2d46-4594-ad95-2234815338f3](https://user-images.githubusercontent.com/27472703/172160125-1ff0f3c1-5b1e-4109-a6ea-7ba7b3901708.png)
 
The image says build 102 job with 370ms, but my build speed (without remote cache) is
![Pasted image 20220606202728](https://user-images.githubusercontent.com/27472703/172160664-287e4032-51fd-4058-a421-32bc8d1083f7.png)
 
and the build command are all like: 
```json

    "build": "npm-run-all -p build:es build:cjs",
    "build:cjs": "tsc -p tsconfig.build.json -m commonjs --outDir dist/lib --declaration false",
    "build:es": "tsc -p tsconfig.build.json -m esNext --outDir dist/esm --declarationDir dist/types",
```

### Expected Behavior

As fast as you advertise, 25 packages build time within 1 second.

### To Reproduce

I don't know it's a bug or design in this way, and all my code are company's code so sorry that I can't show it.

**Comment by gsoltis** [comment]
For slow builds is it possible for you get a profile of your execution? `turbo run build --filter=./packages/* --profile=my-build.prof`? That will help us see where `turbo` is spending time.

Another avenue of investigation is regarding size of your outputs. Do you have an estimate for the file size of the artifacts you're producing in a build? This is probably the `dist/` folders.

**Comment by MichealXie** [comment]
@gsoltis The 25 package's dist folder size add together is around 100mb.

I try run with or without `turbo run build --filter=./packages/* --profile=my-build.prof` and `turbo run build --filter=./packages/*`, both of it take about 20 seconds with `FULL TURBO`.

Here is the prof result:
![Pasted image 20220609153652](https://user-images.githubusercontent.com/27472703/172791528-07affb4c-9c1f-4ab0-b253-a779d25f404b.png)

If you need anything else please give me a comment, I really want to boost my build speed in my local env.

**Comment by nathanhammond** [comment]
@MichealXie We actually need that profile file itself so that we can investigate it. Can you attach it? Or you can send it to me privately: nathan.hammond@vercel.com

**Comment by crubier** [comment]
Hi, I have a pretty nasty case of this here on `turbo@1.4.6`: 

Uncached build:

<img width="433" alt="Screen Shot 2022-09-09 at 11 30 09 AM" src="https://user-images.githubusercontent.com/2954572/189331072-5da7ce67-3662-4624-9936-f111e057a07f.png">

Full turbo build:

<img width="502" alt="Screen Shot 2022-09-09 at 11 33 30 AM" src="https://user-images.githubusercontent.com/2954572/189331157-b0132a5d-041a-44cf-ab47-7ffc59501a6e.png">

I am going to email the profile to nathan.hammond@vercel.com now.

**Comment by vincent-lecrubier-skydio** [comment]
Hi, I have a pretty nasty case of this here on `turbo@1.4.6`: 

Uncached build:

<img width="433" alt="Screen Shot 2022-09-09 at 11 30 09 AM" src="https://user-images.githubusercontent.com/2954572/189331072-5da7ce67-3662-4624-9936-f111e057a07f.png">

Full turbo build:

<img width="502" alt="Screen Shot 2022-09-09 at 11 33 30 AM" src="https://user-images.githubusercontent.com/2954572/189331157-b0132a5d-041a-44cf-ab47-7ffc59501a6e.png">

I am going to email the profile to nathan.hammond@vercel.com now.

**Comment by tknickman** [comment]
Interesting, thanks for sending the trace over - we'll take a look. 

For anyone else who finds this in the future - please send traces to [turbo-core@vercel.com](mailto:turbo-core@vercel.com) so we don't _only_ drown @nathanhammond with these and we can hopefully get you a resolution faster 😄

**Comment by nathanhammond** [comment]
￼@tknickman that email address doesn't accept external messages. 😅￼

**Comment by tknickman** [comment]
In that case. Keep drowning @nathanhammond! 😂

**Comment by nathanhammond** [comment]
Given that the second run was about the same amount of time, I have a suspicion that the caches are failing to restore.￼ Matching by key, but during a failure to restore we may then incorrectly report the cache hit.

**Comment by nathanhammond** [comment]
(I haven't reviewed profiles yet, will forward.)

**Comment by vincent-lecrubier-skydio** [comment]
Ok so on my side, I have clearly identified that the one nextjs workspace is causing trouble: removing it takes the fully cached time down to 16s.

I don't think my config is doing anything exceptional, and my nextjs project is also pretty basic. Not clear why it is causing trouble. 🤔 

<img width="415" alt="Screen Shot 2022-09-09 at 3 17 25 PM" src="https://user-images.githubusercontent.com/94416008/189371273-d81d744d-46b3-4454-bef7-c0c499218d0d.png">

**Comment by nathanhammond** [comment]
Still just looking at the total durations, the difference between your runs and when you pop out that one task makes me feel pretty good about my hypothesis.￼

**Comment by vincent-lecrubier-skydio** [comment]
Cool! Let me know if you think there is a workaround / solution I need to take action on, or if you plan on a fix on your side

**Comment by vincent-lecrubier-skydio** [comment]
Thanks to @nathanhammond I was able to find the source of my problem: 

I was adding my `.next` folder as `output` of my `build` step 😱 . This folder includes caches, and these caches were 8GB, hence the long time to restore cache.

So in my case the fix is to take my `turbo.json` config file in essence from this:

```json
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "build": {
      "outputs": [".next/**", "build/**", "out/**", "gen/**", "dist/**"],
    }
  }
}
```

to this:

```json
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "build": {
      "outputs": ["build/**", "out/**", "gen/**", "dist/**"],
    }
  }
}
```

This took down my full turbo time back to 4 seconds 👍 

<img width="438" alt="Screen Shot 2022-09-12 at 12 59 29 PM" src="https://user-images.githubusercontent.com/94416008/189647955-3da3908a-a8cb-4523-96de-380d392f2199.png">

**Comment by mehulkar** [comment]
Looks like this is resolved with better config, thanks for reporting the update @vincent-lecrubier-skydio!

**Comment by nikelborm** [comment]
Hi!

I don't know if it's the expected behavior, but I have a graph of 8 tasks where every task is cached and I properly specified inputs and outputs for every package. When everything has cache hit, I expected that the command will run almost instantly, but no. It takes 8 seconds for 8 very tiny packages. Building them from scratch takes 8 seconds. I can send you the whole workspace with all caches if you want, and also I can send you profiling information

**Comment by nikelborm** [comment]
Profiling information:

[all_cache_hit.json](https://github.com/user-attachments/files/21941800/all_cache_hit.json)

**Comment by nikelborm** [comment]
The strange thing is that they all take almost exactly 2 seconds as if something holds each task and then time-outs in the background

(screenshot rendered in [perfetto](https://ui.perfetto.dev/) from the file above)

<img width="3012" height="697" alt="Image" src="https://github.com/user-attachments/assets/aa728513-50a0-4dfe-a5af-91282bd6df05" />

**Comment by nikelborm** [comment]
I think the issue might be related to the fact I have btrfs
