### ISSUE TITLE
Output verbosity flags may be broken

### ISSUE THREAD

**Issue by sppatel** [vercel/turbo#1348]
### What version of Turborepo are you using?

1.2.16

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Documentation refers to https://turborepo.org/docs/reference/command-line-reference#-v--vv--vvv to set output verbosity.  This used to work, however it is now broken.

```
❯ turbo run build -v
2022-06-08T09:41:43.313-0400 [ERROR] run: : error="unknown shorthand flag: 'v' in -v"
 ERROR  unknown shorthand flag: 'v' in -v
 ```
```
❯ turbo run build -vv
2022-06-08T09:41:59.546-0400 [ERROR] run: : error="unknown shorthand flag: 'v' in -vv"
 ERROR  unknown shorthand flag: 'v' in -vv
```

```
❯ turbo run build -vvv
2022-06-08T09:42:18.831-0400 [ERROR] run: : error="unknown shorthand flag: 'v' in -vvv"
 ERROR  unknown shorthand flag: 'v' in -vvv
```

### Expected Behavior

Should be able to set the verbosity for INFO, DEBUG, TRACE.

### To Reproduce

Run any turbo command and try to use verbose output flags.

**Comment by sppatel** [comment]
If I run turbo with `yarn` the flags are accepted but only see DEBUG output (no INFO, TRACE)

**Comment by gsoltis** [comment]
This is fixed for `run` in `main` [here](https://github.com/vercel/turborepo/blob/main/cli/internal/run/run.go#L464), and is slated for a broader fix with the final move of the top-level command to [`cobra`](https://github.com/spf13/cobra)

**Comment by mehulkar** [comment]
This should be working in latest versions, and is covered by a few integration tests also. Let us know if you're still seeing it!
