### ISSUE TITLE
Skip files from output

### ISSUE THREAD

**Issue by lodmfjord** [vercel/turbo#1366]
### Describe the feature you'd like to request

To disable some folders/files in output. 

For example, one package I have (NextJS app) can sometimes have a big *cache* folder in *.next*. I would love to skip the cache folder while still caching .next.

### Describe the solution you'd like

Either something like:

"skip": [".next/cache"]

Or by using some RegEx voodoo in outputs. 

### Describe alternatives you've considered

Disabling cache in NextJS. 
https://github.com/vercel/next.js/issues/37608

**Comment by mehulkar** [comment]
You should be able to specify with `!` now. I think that should cover your case!

```json
{
  "outputs": [".next", "!.next/cache"]
}
```
