### ISSUE TITLE
Report which packages/tasks have failed at the end of a task without having to scroll terminal output.

### ISSUE THREAD

**Issue by sppatel** [vercel/turbo#1368]
### Describe the feature you'd like to request

This is similar to nature to [1279](https://github.com/vercel/turborepo/issues/1279) but we have a repo that has hundreds of packages .  In addition we have received feedback that on CI (atleast) devs do not like the default behavior of exiting exiting early because they do not get a complete picture of what other failures exist.   While they could run the command locally, some operations such as Jest on 100's of packages would eat up local compute or take a really long time to finish running tests across all affected packages (which in some cases could be all of them).

The ask for us was to switch to --continue.  However this introduces a usability concern in that you have to scroll up the terminal output to find all the failures which is not ideal.  For something like Jest this isn't too big of an issue because we generate html reports that can be looked at for a complete summary but for other operations such as webpack, lint, etc. this is not the case.

At minimum - need a way at the end to report on which packages failed a task.

### Describe the solution you'd like

At the end of the run, please report the failed tasks and which specific packages failed for that task.  Also include this in the json summary as requested in [1279](https://github.com/vercel/turborepo/issues/1279)

### Describe alternatives you've considered

None.

**Comment by gsoltis** [comment]
I like this idea, as well as the json output.

**Comment by Irvenae** [comment]
Just ran into this and have been scrolling for a couple of minutes through my logs now. Very annoying!
Is there a plan to resolve this?

**Comment by cbm-egoubely** [comment]
@sppatel  I think this is handled now (cf [`--summarize`](https://turbo.build/repo/docs/reference/command-line-reference#--summarize) CLI options).

**Comment by robaca** [comment]
We have a [Nushell](https://nushell.sh) script to log the last lines of each failed task:

```nushell
#!/usr/bin/env nu

def showLog [task] {
    $"-----------------------------------------------------------------------------
# ($task.taskId):
-----------------------------------------------------------------------------
(tail -n 50 $task.logFile)
"
}

(ls .turbo/runs/
    | sort-by modified -r
    | first
    | open $in.name
    | get tasks
    | where { |task| $task.execution.exitCode != 0 }
    | each { |task| showLog $task }
    | to text)
```

**Comment by mehulkar** [comment]
This was done in https://github.com/vercel/turbo/pull/4965! We output failed task at the bottom of a run now.
