### ISSUE TITLE
Add ability to call run [command] from subdirectory and have turbo build necessary targets up to desired target and then run the target

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turbo#144]
### Describe the feature you'd like to request

- `cd app && turbo dev` should build whatever is necessary

### Describe the solution you'd like

- We may need to have a way to mark the "root" folder
- This also sets us up for `esy-like` environment variables and install commands, which we likely should be doing anyway.

### Describe alternatives you've considered

- Running everything from the root is painful. Turbo should fix this.

**Comment by lfades** [comment]
To keep it zero config could it be possible to read the `package.json` of parent folders looking for the `turbo` key? I'm not sure of what would be the downsides in this case but it should be fast enough if it doesn't have to read far up the tree

**Comment by anthonyshew** [comment]
Install `turbo` globally. :)
