### ISSUE TITLE
Aggregated Output Support

### ISSUE THREAD

**Issue by zaripych** [vercel/turbo#1469]
### Describe the feature you'd like to request

When analysing output for a turbo-run that ran against multiple packages the output sometimes becomes hard to comprehend.

Example:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/396623/176992689-667fce7d-d1a4-4ab8-ade6-2d893b42e714.png">

### Describe the solution you'd like

`pnpm` provides an option to [print an aggregated output](https://pnpm.io/cli/run#--aggregate-output). Just doing something similar makes total sense, given `turbo` already stores all the log output in files ...

### Describe alternatives you've considered

Nothing comes to my mind. Except running `turbo` twice ... but only works if cache was hit and tasks ran successfully.

**Comment by zaripych** [comment]
Hmmm. A bunch of subjective extra thoughts:

With aggregated output it now also makes sense to stop using `package:task` prefix in front of every line. Which should save so much space. 

Alternatively, `package:task` could be shortened to a short id. Ie
```sh
[AAA]  Test Suites: 2 passed, 2 total
```

The color of every package could be different. It also seems like a good idea to reduce brightness of the prefix - as it does have lower value potentially compared to what goes after it.

**Comment by NullVoxPopuli** [comment]
second this -- `pnpm`'s windowed-logging approach is really nice. It only shows more output when tasks fail, which I think is appropriate.

**Comment by mehulkar** [comment]
You can use [`--log-order=grouped`](https://turbo.build/repo/docs/reference/command-line-reference/run#--log-order) now!
