### ISSUE TITLE
When parsing some client configs, Turbo is not aware of `--` (ignore-option)

### ISSUE THREAD

**Issue by erickponce** [vercel/turbo#1476]
### What version of Turborepo are you using?

1.3.1

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

Hello there!

When parsing some client configs, Turbo is not aware of `--` (ignore-option)...
this means that a script with a same name arg like `--token` are overriding Turbo's own env var token.
Another issue is that the http client are not reporting an invalid token error on this scenario.

It's protected on another method `selectCwd` on the same file:
https://github.com/vercel/turborepo/blob/d83130a8b30b01ae2ce1627f4188e791598ea8b3/cli/internal/config/config.go#L245

so the fix is basically replicate that if into method `ParseAndValidate` arg loop:
https://github.com/vercel/turborepo/blob/d83130a8b30b01ae2ce1627f4188e791598ea8b3/cli/internal/config/config.go#L140

### Expected Behavior

Turbo should ignore any args after `--` (ignore-option).

### To Reproduce

Call Turbo with a script args `-- --token=000000` and 000000 will become Turbo's token.

**Comment by nathanhammond** [comment]
Is this addressed by #1612?

**Comment by nathanhammond** [comment]
I believe that we addressed this with our migration to cobra.
