### ISSUE TITLE
Invalid package dependency graph: cyclic dependency detected.

### ISSUE THREAD

**Issue by long-woo** [vercel/turbo#1480]
### What version of Turborepo are you using?

1.3.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

> Invalid package dependency graph: cyclic dependency detected:
lib-a,lib-b,lib-c

### Expected Behavior

Successfully start the service.

### To Reproduce

Add `lib-a`, `lib-b` and `lib-c` to `monorepo` of `pnpm`, `lib-a` depends on `lib-b`, `lib-b` depends on `lib-c`, `lib-c` depends on `lib-a`, which are all `peerdependencies` dependent methods. When I run 'pnpm dev (`turbo run dev`)', the following error occurs:

> Invalid package dependency graph: cyclic dependency detected:
lib-a,lib-b,lib-c

**Comment by nathanhammond** [comment]
Hey, sorry for not getting back to you! We do not at this time intend to support cyclic dependencies amongst in-workspace packages.
