### ISSUE TITLE
Abstract internal makefile/go/postinstall into its own package

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turbo#153]
### Describe the feature you'd like to request

Abstract internal tooling (half-ripped from esbuild) into formalize package for publishing JS-wrapped Go packages to NPM.

### Describe the solution you'd like

- Break out makefile into shell scripts and js script (mostly are around publishing the 10 different golang packages)

### Describe alternatives you've considered

- Wait until we do presets to tackle this

**Comment by anthonyshew** [comment]
Finishing the Rust port so closing out Go-related stuff.
