### ISSUE TITLE
Design system example does not proceed when prompt appears in npm `dev` script

### ISSUE THREAD

**Issue by marr** [vercel/turbo#1547]
### What version of Turborepo are you using?

1.3.1

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Following the install instructions for the design system example, I am not able to complete the dev script. There is a prompt in the script, since I already have port 6006 running which reads:
> ? Port 6006 is not available. Would you like to run Storybook on port 6007 instead? › (Y/n)

Pressing Enter does not complete the prompt, and the script waits. The storybook server is never started.

### Expected Behavior

The prompt allows for interactivity
or
The "yes" option is selected automatically.

The first option may better for safety/security.

### To Reproduce

1. Have something listening on port 6006. You can run `nc -l 6006` on a mac/linux machine in a separate terminal window to do this.
2. Run the dev script after installing the design-system package. [Install instructions](https://github.com/vercel/turborepo/tree/main/examples/design-system)
3. See message from description prompting Y/n.
4. No way to proceed after this.

**Comment by marr** [comment]
Related https://github.com/vercel/turborepo/issues/1235

**Comment by anthonyshew** [comment]
Closing as stale! Our recent example updates have this covered.
