### ISSUE TITLE
Gatsby logs not captured properly

### ISSUE THREAD

**Issue by alvarlagerlof** [vercel/turbo#1572]
### What version of Turborepo are you using?

1.3.4

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

When running build, all logs from Gatsby ([quick start project](https://www.gatsbyjs.com/docs/quick-start/)) are not placed in the appropriate subrepo tag.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/14835120/180645644-04e53257-f680-4060-a091-9dc9316b31c2.png">
<img width="471" alt="image" src="https://user-images.githubusercontent.com/14835120/180645655-1b021cda-96aa-4be5-85b9-bbcf51f25f61.png">

### Expected Behavior

All logs should have their subrepo name next to the.

### To Reproduce

https://github.com/alvarlagerlof/turborepo-bug

**Comment by alvarlagerlof** [comment]
I suspected something like that. Is there any reasonable thing that could be done to capture logs from the workers?

**Comment by anthonyshew** [comment]
This should hopefully be fixed now in the new Turborepo 2.0 TUI. Please open a fresh issue if this is still a problem.
