### ISSUE TITLE
Allow wildcard for package-specific overrides in turbo.json

### ISSUE THREAD

**Issue by TxHawks** [vercel/turbo#1694]
### Describe the feature you'd like to request

I'd like to be able to define a group of packages using a wildcard when defining package-specific overrides in `turbo.json`.

### Describe the solution you'd like

I'd like to be able to use a wildcard when defining package-specific overrides, so say use a Hungarian notation-like naming scheme for my packages, I'd be able to do:

```jsonc
"app-*#build": {
  "dependsOn": [ "somePackage#deploy" ]
}
```

### Describe alternatives you've considered

None

**Comment by mehulkar** [comment]
Closing in favor of the older issue https://github.com/vercel/turbo/issues/1053
