### ISSUE TITLE
Storybook props table does no appear on provided `design-system` example

### ISSUE THREAD

**Issue by vimtor** [vercel/turbo#1704]
### What version of Turborepo are you using?

1.4.3

### What package manager are you using / does the bug impact?

npm, Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Storybook props table does not load on the provided [examples/design-system](https://github.com/vercel/turborepo/tree/main/examples/design-system).

<img width="1410" alt="CleanShot 2022-08-16 at 18 07 10@2x" src="https://user-images.githubusercontent.com/36263538/184927372-dcfb2710-5d68-42c6-a07c-f920ca17183a.png">

### Expected Behavior

The props table should appear.

### To Reproduce

1. Clone and run the [examples/design-system](https://github.com/vercel/turborepo/tree/main/examples/design-system) folder
2. `npm run dev`
3. Navigate to the `Docs`

**Comment by vimtor** [comment]
I've found that running the following works:

```
turbo run dev --filter=docs
```

**Comment by Ne-Ne** [comment]
@vimtor did you have an example Button component or was is the default repo version?

**Comment by vimtor** [comment]
> @vimtor did you have an example Button component or was is the default repo version?

It was the default repo version

**Comment by Ne-Ne** [comment]
Interesting even when I update all storybook deps I get nothing, no error just got this "as-is".

However, if you move this storybook away from `docs` and load storybook into the UI library it works fine.

<img width="1051" alt="Screenshot 2022-08-19 at 12 07 25" src="https://user-images.githubusercontent.com/2177851/185654718-4d87f497-9539-4532-9b91-f525a9941b14.png">

**Comment by erickreutz** [comment]
Also running into this issue.

**Comment by la55u** [comment]
@erickreutz I use the webpack5 builder and have the same issue.

**Comment by erickreutz** [comment]
Digging into this further this morning. I found two issues preventing the args table from working.  I suspected that `react-docgen-typescript` wasn't picking up the `.ts` outside of the `docs` repo. Adding `"../../packages/**/*.{ts,tsx}"` as an include to the `reactDocgenTypescriptOptions` in `main.js` fixed this issue. The second issue is that `Button` defines a single prop of `children`. Looking at the docs for `react-docgen-typescript` the option `skipChildrenPropWithoutDoc` defaults to true. In order for `children` to show up, I needed to set that to false.

**Comment by la55u** [comment]
> 
> 
> ```js
>   typescript: {
>     reactDocgen: "react-docgen-typescript",
>     reactDocgenTypescriptOptions: {
>       shouldExtractLiteralValuesFromEnum: true,
>       skipChildrenPropWithoutDoc: false,
>       propFilter: (prop) =>
>         prop.parent ? !/node_modules/.test(prop.parent.fileName) : true,
>       include: ["../../packages/**/*.{ts,tsx}"],
>     },
>   },
> ```

Thank you, it kind of works (showing the name and control of the props) but the description of the props and and the description of the component itself is still missing.:/

**Comment by mrtnbroder** [comment]
So for anyone interested, I've figured out a solution that is worked as intended. Hope it helps 👍 

I'm using pnpm v7, my stories are within a directory called "stories", co-located where my component are living.

`main.ts`
```ts
const config = {
  "stories": [
    "../node_modules/@acme/core/src/**/stories/*.stories.@(ts|tsx|mdx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
  ],
  "framework": {
    "name": "@storybook/react-vite",
    "options": {}
  },
  "core": {
    "disableTelemetry": true,
  },
  "typescript": {
    reactDocgenTypescriptOptions: {
      include: ["../core/**/*.{ts,tsx}"]
    },
    "skipBabel": true,
    "check": false,
  },
  "docs": {
    "autodocs": true // "tag"
  }
};

export default config;
```

`package.json`

```json
{
  "name": "docs",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "storybook": "storybook dev -p 6006",
    "build": "storybook build",
    "clean": "rm -rf .turbo && rm -rf node_modules",
    "build-storybook": "storybook build"
  },
  "dependencies": {
    "@acme/core": "workspace:*",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@storybook/addon-essentials": "^7.0.0-beta.44",
    "@storybook/addon-interactions": "^7.0.0-beta.44",
    "@storybook/addon-links": "^7.0.0-beta.44",
    "@storybook/blocks": "^7.0.0-beta.44",
    "@storybook/react": "^7.0.0-beta.44",
    "@storybook/react-vite": "^7.0.0-beta.44",
    "@storybook/testing-library": "^0.0.14-next.1",
    "@types/react": "^18.0.27",
    "@types/react-dom": "^18.0.10",
    "storybook": "^7.0.0-beta.44",
    "typescript": "^4.9.3"
  }
}
```
