### ISSUE TITLE
Support wildcards in package specific tasks in turbo.json

### ISSUE THREAD

**Issue by sppatel** [vercel/turbo#1771]
### Describe the feature you'd like to request

As described here https://turborepo.org/docs/core-concepts/pipelines#implicit-dependencies-and-specific-package-tasks turbo supports package specific tasks.  However the limitation is that this isn't currently very scalable.  If you have one or two overrides, not a big issue, but if you have many packages that follow a naming convention and require specific dependsOn - then its not feasible to maintain each entry in turbo.json.

```
"build": {
  "dependsOn": []
},
"special-1#build": {
  "dependsOn": ["^foo"]
}
"special-2#build": {
  "dependsOn": ["^foo"]
}
"special-3#build": {
  "dependsOn": ["^foo"]
}
```

### Describe the solution you'd like

Support wildcards such that I can create unique "sets" of packages specific tasks.  The example above would then be specified as..

```
"build": {
  "dependsOn": []
 },
"special-*#build": {
  "dependsOn": ["^foo"]
}
```

As an extension to this - packages in a mono repo can be organized in multiple workspaces.  So being able to create a workspace specific task override would be beneficial as well.  Similar to // for representing root, I would imaging a special indentifier representing the workspace (vs an individual package)

```
"build": {
  "dependsOn": []
 },
"$workspace-a#build": {
  "dependsOn": ["^foo"]
}
```

### Describe alternatives you've considered

No current alternatives.

**Comment by tknickman** [comment]
Thanks - we have a similar PR open from the community - https://github.com/vercel/turborepo/pull/1088

**Comment by mehulkar** [comment]
Closing in favor of the older issue: https://github.com/vercel/turbo/issues/1053
