### ISSUE TITLE
Add update checker to `turbo`

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turbo#178]
### Describe the feature you'd like to request

Add update check + message so people can be notified when new releases come out

### Describe the solution you'd like

Should mostly grab the implementation from:
- `updater` in PlanetScale CLI https://github.com/planetscale/cli/tree/main/internal/update
- `updater` in GitHub CLI https://github.com/cli/cli/tree/trunk/internal/update

### Describe alternatives you've considered

Rolling it ourselves seems like a bad idea, although, it could be nice to link to a CMS service to add context to releases perhaps. But for starters, we need this.

**Comment by AyoubBenAl1** [comment]
I'd like to work on this.
Can you assign it to me

**Comment by jaredpalmer** [comment]
Go for it. If you're not already on it, join our https://turborepo.org/discord

**Comment by m9p909** [comment]
I saw a PR that never got approved. I'm going to fix up the PR and submit it again, lmk if I should stop.

**Comment by m9p909** [comment]
nvm this is delayed. https://github.com/vercel/turbo/pull/397#issuecomment-1079271761

**Comment by mehulkar** [comment]
We have this now
