### ISSUE TITLE
Turbo doesn't stop process when VS Code quits

### ISSUE THREAD

**Issue by mellson** [vercel/turbo#1802]
### What version of Turborepo are you using?

1.4.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When I use Turbo to run Nextjs inside VS Code the node process sticks around after I quit. This doesn't happen if I run without Turbo. Is there a way to make Turbo stop running when the calling terminal is exited?

### Expected Behavior

I would expect all my processes started in the terminal inside VS Code to quit when I quit VS Code

### To Reproduce

I've created [an example repo here](https://github.com/mellson/turbo-hanging-process-example) based on the Turbo basic starter repo. Use this repo or follow steps similar to these:

Start Nextjs using Turbo inside VS Code; after it's started, quit VS Code using CMD+Q. Nextjs will still be running.
If you quit the process using CTRL+C inside the VS Code terminal, everything stops as it should.

**Comment by tecoad** [comment]
I have the same issue. How did you manage @mellson ?

**Comment by mellson** [comment]
> I have the same issue. How did you manage @mellson ?

Sadly, I haven't found a failsafe way. I try to remember to stop the running process before exiting VS Code.

**Comment by anthonyshew** [comment]
Seeing that the original issue is mentioning a version from 8 minors ago. Additionally, this issue is pretty old and doesn't have much activity so I'm going to close it up.

If you're still seeing this problem, please open up a fresh issue with our bug issue template!
