### ISSUE TITLE
with-tailwindcss example double include of globals breaks styling

### ISSUE THREAD

**Issue by kriswuollett** [vercel/turbo#1809]
### What version of Turborepo are you using?

1.4.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

The [shared `ui` component includes tailwindcss globals](https://github.com/vercel/turborepo/blob/75bc262a7255bfa3bc3c89fbcc154d765e901e5a/examples/with-tailwind/packages/ui/src/styles.css#L1) overrides the [sample app's globals.css](https://github.com/vercel/turborepo/blob/75bc262a7255bfa3bc3c89fbcc154d765e901e5a/examples/with-tailwind/apps/web/src/styles/globals.css#L1), when [both are included in the app](https://github.com/vercel/turborepo/blob/75bc262a7255bfa3bc3c89fbcc154d765e901e5a/examples/with-tailwind/apps/web/src/pages/_app.tsx#L1-L3). This can cause issues like masking a `button`'s background color (also breaks the search bar layout in the [Card layout with sidebar example](https://tailwindui.com/components/application-ui/page-examples/home-screens#component-d7cea65e442e0c2c85f158472dd2a846)). Note the missing teal "Send money" button that should be next to "Add money" on the right hand side, and the order of css imports is user agent, global, global, styles:

![image](https://user-images.githubusercontent.com/1834192/187536460-49d77d98-12ca-4893-b4ad-4b36a34f39e1.png)

### Expected Behavior

The examples should show proper reuse of tailwind/css in a shared UI package.

I'm not sure what the best solution is, but perhaps in the short term it includes:

* not including tailwindcss configuration in `ui` and assuming those globals are included
* scanning the shared component library as described in [Tailwind's third-party library / monorepo guide](https://tailwindcss.com/docs/content-configuration#working-with-third-party-libraries)

Longer term perhaps:

* `app` should demonstrate extending the theme from `ui`, e.g., more theme colors

### To Reproduce

Not sure at the moment, because merely adding something like the following to the examples index.tsx below the current button seems to work due to the differing import order:

```html
        <div className="mx-auto mt-5 max-w-xl sm:flex sm:justify-center md:mt-8">
          <button className="text-white bg-gray-600">HI</button>
        </div>
```

Note order of CSS imports is: user agent, globals, styles, globals.

![image](https://user-images.githubusercontent.com/1834192/187538270-38026369-8875-41db-9d91-a8c0978c8376.png)

**Comment by linkb15** [comment]
[Tailwind Prefix Config](https://tailwindcss.com/docs/configuration#prefix)

How about prefix the classname so it does not conflicting using the tailwind configuration prefix option?

**Comment by tknickman** [comment]
@kriswuollett we ended up using the prefix option for the ui lib in our tailwind example to avoid this issue. The example is up to date now and should fix this!

**Comment by kdb13** [comment]
> [@kriswuollett](https://github.com/kriswuollett) we ended up using the prefix option for the ui lib in our tailwind example to avoid this issue. The example is up to date now and should fix this!

Won't prefixing cause having duplicate classes in the final CSS bundle for the NextJS app?

Suppose, we are using the `px-4` class in the `ui` package as well as the `web` NextJS app, then when the app is built, it'll include two classes:
* `px-4` from the NextJS
* `ui-px-4` from the UI package

**Comment by Stupidism** [comment]
Here's my workaround. Just give up reusing the prebuilt style from `packages/ui`

```diff
// apps/my-app/app/globals.css
+ @import "../../../packages/ui/src/styles/globals.css";
+ @source "../../../packages/ui";

// apps/my-app/app/layout.tsx
import './globals.css';
- import '@repo/ui/styles.css';

// For comparison, text-success is only used in app
+  <div className="text-success">test</div>
// text-destructive is used in both app and packages/ui
+ <div className="text-destructive">test</div>
```

Before

![Image](https://github.com/user-attachments/assets/a54c5433-6e46-4e47-806a-264408c904eb)

After

![Image](https://github.com/user-attachments/assets/3361d81e-9bff-4f16-be97-6feb73362923)
