### ISSUE TITLE
npm prune support

### ISSUE THREAD

**Issue by punkpeye** [vercel/turbo#1830]
### Describe the feature you'd like to request

Opened since there appears to be no open issue to track the missing feature.

### Describe the solution you'd like

`yarn` v1 equivalent support for `--prune`

### Describe alternatives you've considered

Migrating to `yarn` v1

**Comment by 7flash** [comment]
```
yarn turbo prune
```

**Comment by punkpeye** [comment]
This issue is about supporting NPM, not about switching to yarn.

**Comment by weyert** [comment]
Looks like they started working on the `prune` feature for `pnpm`. Can imagine next would be `npm` :)

**Comment by punkpeye** [comment]
Isn't it super odd to prioritize everything but the standard package manager? Makes me question how the project is run. Unless there are limitations of npm that make it unfeasible for whatever reason.

**Comment by 7flash** [comment]
```
pnpm dlx turbo prune
```

**Comment by chris-olszewski** [comment]
@punkpeye There has been *far* more interest in getting prune working for Yarn v2+ and `pnpm` and thus we've prioritized them. Npm support will get added once those others have been implemented

**Comment by punkpeye** [comment]
Bummer I guess I could try to switch to yarn pr pnpm, just seems odd that the primary package manager is not supported.

**Comment by cyborch** [comment]
@chris-olszewski I'm voting for this to be resolved to, how do we signal interest in getting this resolved?

**Comment by punkpeye** [comment]
I guess 👍 on the original issue.

**Comment by chris-olszewski** [comment]
This is nearing the top of my todo list. Aiming to have this implemented and released sometime the week of Oct 10.

**Comment by weyert** [comment]
>  This is nearing the top of my todo list. Aiming to have this implemented and released sometime the week of Oct 10.

Awesome :)

**Comment by nathanhammond** [comment]
`prune` works for `npm`! 🎉
