### ISSUE TITLE
[BUG] turbo link didn't use --api options to create config.json

### ISSUE THREAD

**Issue by promer94** [vercel/turbo#1914]
### What version of Turborepo are you using?

1.4.6

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

```bash
npx turbo link --  --api=xxx
```
always create a `config.json` with default apiurl 
```json
{
  "apiurl": "https://vercel.com/api",
  "loginurl": "https://vercel.com",
  "teamid": "team_xxx"
}
```

### Expected Behavior

```bash
npx turbo link --  --api=https://turbocache.vercel.app/api
```
shoud create a `config.json` with specified apiurl 
```json
{
  "apiurl": "https://turbocache.vercel.app/api",
  "teamid": "team_xxxx"
}
```

### To Reproduce

* init a turborepo
```bash
npx create-turbo
```

* login
```bash
npx turbo login -- --url=https://turbocache.vercel.app --api=https://turbocache.vercel.app/api
```

* link
```bash
npx turbo link -- --url=https://turbocache.vercel.app --api=https://turbocache.vercel.app/api
```

* check `.turbo/config.json`

<sub>[TURBO-1884](https://linear.app/vercel/issue/TURBO-1884/[bug]-turbo-link-didnt-use-api-options-to-create-configjson)</sub>

**Comment by promer94** [comment]
It seems like that apiurl is only used by `remoteConfig` https://github.com/vercel/turborepo/blob/0ac4e22c46ee5dc41284cb0a2bc2cca0d85b6368/cli/internal/config/config.go#L142 

I think It should be assigned to `repoConfig` with `teamId` together
https://github.com/vercel/turborepo/blob/0ac4e22c46ee5dc41284cb0a2bc2cca0d85b6368/cli/internal/config/config_file.go#L24-L34

**Comment by gsoltis** [comment]
I'll take a look at this. Normally, commandline flags are used to override values in config files, but for something like `turbo. login` with an overridden login url, it probably doesn't make sense to save the token without the url. 

As a workaround, you should be able to edit the config file and have it work.

**Comment by anthonyshew** [comment]
Closing due to staleness!

**Comment by bitttttten** [comment]
Oh no I literally just stumbled upon this issue @anthonyshew 😅 

I'm getting a slightly different error now:

```sh
npx turbo@latest link --  --api=https://turbocache.vercel.app/api
 ERROR  unexpected argument '--api=https://turbocache.vercel.app/api' found

Usage: turbo link [OPTIONS]

For more information, try '--help'.
```

I'll create a new ticket instead.
