### ISSUE TITLE
`with-react-native-web` example doesn't work

### ISSUE THREAD

**Issue by jferrettiboke** [vercel/turbo#1919]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

The [`with-react-native-web` example](https://github.com/vercel/turborepo/tree/main/examples/with-react-native-web) doesn't work.

### Expected Behavior

The example should work in order for developers to learn and explore how things are wired up.

Furthermore, the example is using the exact same React v17.x version in both Next.js and Expo apps. In a real-world scenario, React versions between Next.js and Expo rarely match between them. Developers could struggle a lot just because of this.

Please, provide an up-to-date [`with-react-native-web` example](https://github.com/vercel/turborepo/tree/main/examples/with-react-native-web), keep Next.js and Expo running with the latest compatible dependency versions, and highlight and make developers aware of the solution to fix React incompatibility issues when there is more than one React version (which is pretty common when using Next.js and Expo in a monorepo setup).

### To Reproduce

1. `npx degit vercel/turborepo/examples/with-react-native-web with-react-native-web`
2. `cd with-react-native-web`
3. `yarn install`
4. `git init . && git add . && git commit -m "Init"`
5. `yarn dev`

**Comment by rvieceli** [comment]
@jferrettiboke have you tried [Managing dependencies](https://turborepo.org/docs/guides/workspaces#managing-dependencies)?

**Comment by mehulkar** [comment]
Tried this out locally and saw a few issues (not sure which one is the actual problem)

- `apps/native`'s `dev` script asks to instal `expo-cli` globally. Not sure if it's waiting for user input to proceed or not (maybe a `-y` flag or some autoinstall script would help? or documentation should include a `yarn global add expo-cli`)
- Some TS errors from `react-native`. The version is pinned, so I'm not sure how this could have broken on its own, but it's complaining about `TouchableOpacity` component. Maybe we should simplify our example not to depend on _actual_components of ReactNative, since our examples are to show how _Turbo_ works, not React native.

I'm not familiar with RN or Expo, so I didn't go further than this at the moment

**Comment by AyoCodess** [comment]
this temaplate does not work for me either https://github.com/vercel/turbo/discussions/2543

**Comment by mehulkar** [comment]
Fixed at least one issue in https://github.com/vercel/turbo/pull/2523, but I didn't try running the dev server. Will try to give it a go today and see if it's an easy fix.

**Comment by tknickman** [comment]
The TS issue with `TouchableOpacity` I believe required the specific version of react types - we've had to fix it once here already: https://github.com/vercel/turbo/pull/2181/files

**Comment by cbaucom** [comment]
I also just tried to get up and running with this example and the native app seems to break when trying to use the `ui` `Button` component. When you comment out the button, the UI on the app seems to load fine.

**Comment by cbaucom** [comment]
I put a [PR](https://github.com/vercel/turbo/pull/2759) up to solve the path issue the native app is having with trying to use things from `packages`.

**Comment by tubbo** [comment]
When I cloned this repo, I also had to `yarn workspace native add -D expo-cli` so the dev server ran. I guess my Expo Go app was not up-to-date because I was originally having trouble loading the UI, but after seeing it on web I tried restarting the Expo Go app and getting into my project, and it ran again. `¯\_(ツ)_/¯`

**Comment by butadpj** [comment]
I can't even install the packages from the root directory. I'm getting this error when I run `npm install` 

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: native@1.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from native@1.0.0
npm ERR!   apps/native
npm ERR!     native@1.0.0
npm ERR!     node_modules/native
npm ERR!       workspace apps/native from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.68.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.68.2" from native@1.0.0
npm ERR!   apps/native
npm ERR!     native@1.0.0
npm ERR!     node_modules/native
npm ERR!       workspace apps/native from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/butadpj/.npm/_logs/2023-08-11T16_48_29_332Z-eresolve-report.txt
```

**Comment by eggdev** [comment]
@butadpj I was getting a similar error. I updated the versions of React Native in my local repo to whatever the latest were for today. Seemed to install and spin up fine, but not sure if some other dependencies need to be updated yet

**Comment by amerllica** [comment]
Another issue is with the `expo-router`, I can't implement it properly within the `native` project. I read the docs of the `expo-router` significantly. If I add `index.js` file in the root of the `native` project and write `import 'expo-router/entry
` inside it, I would get this error:

```
Web Bundling failed 787ms
error: index.js: The "id" argument must be of type string. Received undefined
```

If I remove the `index.js` file and add the entry file inside the `package.json` file by using the `main` key, (Like the docs said) I would get this error:

```
Error: Unable to resolve module ./node_modules/expo-router/entry from /Users/amerllica/WebstormProjects/mini-market-app/apps/_e_customer/.: 

None of these files exist:
  * node_modules/expo-router/entry(.web.ts|.ts|.web.tsx|.tsx|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs)
  * node_modules/expo-router/entry/index(.web.ts|.ts|.web.tsx|.tsx|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs)
    at ModuleResolver.resolveDependency (/Users/amerllica/WebstormProjects/mini-market-app/apps/_e_customer/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (/Users/amerllica/WebstormProjects/mini-market-app/apps/_e_customer/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at /Users/amerllica/WebstormProjects/mini-market-app/apps/_e_customer/node_modules/metro/src/lib/transformHelpers.js:169:21
    at Server._resolveRelativePath (/Users/amerllica/WebstormProjects/mini-market-app/apps/_e_customer/node_modules/metro/src/Server.js:1045:12)
    at async Server.requestProcessor [as _processBundleRequest] (/Users/amerllica/WebstormProjects/mini-market-app/apps/_e_customer/node_modules/metro/src/Server.js:449:37)
    at async Server._processRequest (/Users/amerllica/WebstormProjects/mini-market-app/apps/_e_customer/node_modules/metro/src/Server.js:383:7)
```

**Peculiar:** The `native` project alongside `expo-router` works properly individually outside of the mono repo.

I don't know how to report this issue. Or if I report this would Jared Palmer care about it?

**Comment by butadpj** [comment]
Hi @amerllica 
> If I remove the `index.js` file and add the entry file inside the `package.json` file by using the `main` key, (Like the docs said) I would get this error:
> 

Having `index.js` file in the root of my react native project and inside of it is `import 'expo-router/entry` works perfectly on my end. You just have to make sure that your dependencies are up to update. Try running `expo install —check` && `expo install —fix`

**Comment by amerllica** [comment]
@butadpj Thanks for your answer, my native project is fully updated even its Expo SDK is 49+ but by adding `expo-router` version 2, it will be like the above explanation.

Would you mind tell me the Expo SDK and expo router versions?

Or in a advance request, would you mind create a GitHub project to show me the working repo (a bare minimum with expo router)?

**Comment by butadpj** [comment]
@amerllica, I forgot to mention, you also have to add these
- `"main": "index.js",` in your package.json. 
- `EXPO_USE_METRO_WORKSPACE_ROOT=1` in your .env file

I also hope your `metro.config.js` file looks like this. Note that you also have to install `find-yarn-workspace-root` for this
```javascript
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require("expo/metro-config");
const findWorkspaceRoot = require("find-yarn-workspace-root");
const path = require("path");

// Find the project and workspace directories
const projectRoot = __dirname;
// This can be replaced with `find-yarn-workspace-root`
const workspaceRoot = findWorkspaceRoot(projectRoot);

const config = getDefaultConfig(projectRoot);

// 1. Watch all files within the monorepo
config.watchFolders = [workspaceRoot];
// 2. Let Metro know where to resolve packages and in what order
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, "node_modules"),
  path.resolve(workspaceRoot, "node_modules"),
];

// 3. Force Metro to resolve (sub)dependencies only from the `nodeModulesPaths`
config.resolver.disableHierarchicalLookup = true;

module.exports = config;
```

Let me know if it still doesn't work so I can proceed on creating the bare minimum project. 

As per your question, yes I also have SDK 49 and expo-router 2.

**Comment by amerllica** [comment]
@butadpj, Really thanks for your bits of help, Exactly like you said, I made a `.env` file and wrote the `EXPO_USE_METRO_WORKSPACE_ROOT=1` init. Also, I added the package.json `main` key completely correct. and then what I got:

```
Web Bundling failed 726ms
error: ../../node_modules/expo-router/entry.js: The "id" argument must be of type string. Received undefined
```

I got one step better. No the native project inside the `apps` folder finds the root `node_modules` and the `expo-router/entry`. But it returns to the `The "id" argument must be of type string. Received undefined`.

It's really frustrating.

**Comment by butadpj** [comment]
hey @amerllica, since you're still getting the same error. [Here's the minimal example of turborepo with expo router](https://github.com/butadpj/turborepo-with-expo-router). I've documented all the steps taken to setup `expo-router`. Hope you find it helpful!

**Comment by amerllica** [comment]
Really thanks @butadpj 
I did everything exactly the same as the expo docs, and I will be comparing yours and mine to find out what's the issue.

BTW, Your minimal example works well on Android and iOS but for the web, it says:

```
Please install @expo/webpack-config@^19.0.0 by running:

npx expo install @expo/webpack-config@^19.0.0

If you're not using web, please ensure you remove the "web" string from the platforms array in the
project Expo config.
```

And doesn't run the web build. I must not install `@expo/webpack-config@^19.0.0` because the SDK 49+ doesn't need webpack at all and it can use metro instead.

**Comment by butadpj** [comment]
Oh for the web part, sorry i didnt mention, I actually skipped this part in the docs
<img width="772" alt="Screen Shot 2023-09-17 at 11 16 32 PM" src="https://github.com/vercel/turbo/assets/72847313/2d47d397-d5cc-440b-b0f5-57351f226de7">

**Comment by amerllica** [comment]
Thanks @butadpj, Now all platforms work properly. your configuration needs the `"bundler": "metro",` in the `app.json` file below the `"web"` key. The rest of things were settled up already.

I want to post a question on the StackOverflow and it would be a good log for the community.

**Comment by anthonyshew** [comment]
Closing as stale! We've done a bunch of example updates recently.

If you're still running into problems, please open a new issue!
