### ISSUE TITLE
buildable package conditional exports  and bundle size inconsistencies

### ISSUE THREAD

**Issue by hubertkuoch** [vercel/turbo#1938]
### What version of Turborepo are you using?

1.4.6

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

1. Next.js app does not seem to recognize conditional exports `mjs/cjs` extensions from buildable package
2. Inconsistent bundle size when an app imports third party package vs when the app uses the same third party package via an internal buildable package

### Expected Behavior

1. Next.js app should be able to resolve conditional exports with `mjs/cjs` extensions from buildable package
2. Bundle size when an app imports third party package vs when the app uses the same third party package via an internal buildable package should be close

### To Reproduce

A full reproduction is available here: [repo]

The root [README.md] contains the few commands to copy/paste if needed

[repo]: https://github.com/hubertkuoch/next-monorepo
[README.md]: https://github.com/hubertkuoch/next-monorepo/blob/main/README.md

**Comment by hubertkuoch** [comment]
To je more precise re. bundle size, not sure why next includes readable-stream package when using a lib built upon @emotion/cache

**Comment by anthonyshew** [comment]
Closing due to staleness. Will mention though that this wouldn't be something that is in Turborepo's domain! (at least not today)
