### ISSUE TITLE
lint turbo/no-undeclared-env-vars not recognizing changes to turbo.json

### ISSUE THREAD

**Issue by thomasvalera** [vercel/turbo#1964]
### What version of Turborepo are you using?

1.4.6

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

When I add an unlisted environment variable in the code, `npm run lint` doesn't detect it automatically and doesn't throw an error.
Also when unlisting a previous env variable from `turbo.json` while still using it in code, `npm run lint` doesn't detect it and won't throw an error.

The only way to show the proper output is to manually delete the cache inside the project's `.next/cache/eslint` between each lint which seems wrong to do.

### Expected Behavior

Running `npm run lint` should always show an error if an unlisted env variable is being used or has been unlisted from `turbo.json` and never show an error if it has been added to `turbo.json`. It should also not be necessary to manually delete the eslint cache between each lint.

### To Reproduce

1. Create a new starter project with `npx create-turbo@latest`
2. Inside `apps/web/pages/index.tsx` add a new env variable at the start of the function, save.
```
export default function Web() {
  const hello = process.env.HELLO;
  return (
    <div>
      <h1>Web</h1>
      <Button />
    </div>
  );
}
```
3. Run `npm run lint`. This will show an error:
```
web:lint: 4:17  Error: $HELLO is not listed as a dependency in turbo.json  turbo/no-undeclared-env-vars
```
4. Add "$HELLO" to `turbo.json`'s `build` pipeline, save.
```
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": ["^build", "$HELLO"],
      "outputs": ["dist/**", ".next/**"]
    },
    "lint": {
      "outputs": []
    },
    "dev": {
      "cache": false
    }
  }
}
```
5. Run `npm run lint` again, this will still show the error:
```
web:lint: 4:17  Error: $HELLO is not listed as a dependency in turbo.json  turbo/no-undeclared-env-vars
```
6. Delete `apps/web/.next/cache/eslint` folder
7. Run `npm run lint` again. This time all tasks are successful and no error is shown.

In reverse:
8. Remove "$HELLO" from `turbo.json`, save.
9. Run `npm run lint`. And no error is shown where it should show an error.
10. Remove the eslint cache
11. Run `npm run lint` again, and this time the error is shown.

EDIT: I read that turbo.json is always an input and invalidates the caches, but that seems not to be the case then.

**Comment by jonahallibone** [comment]
+1 Having the issue here

**Comment by nathanhammond** [comment]
There are actually two layers of cache in play here.￼ The ESLint cache is not invalidating depending upon the values inside of turbo.json￼.

**Comment by nathanhammond** [comment]
After taking a look, https://github.com/eslint/eslint/blob/8cc0bbe440dc5e6af6ef02f00d0514a40ca07c24/lib/cli-engine/lint-result-cache.js#L96-L114 is how ESLint invalidates its cache. If any plugins require input _beyond_ this (which ours does) the ESLint cache will always be stale after first run if the external input changes.

/cc @tknickman

**Comment by nathanhammond** [comment]
What works:
- change `turbo.json`, save the target file, run lint.

What doesn't work:
- change `turbo.json`, run lint.

**Comment by thomasvalera** [comment]
Thanks for the explanation @nathanhammond, that makes a lot of sense.
I had indeed seen that saving a random file in the target project or in the cache file itself invalidated it and made it work as expected.

While I'm sure it's not trivial, it would be nice to have this edge case handled by turborepo.

In the meanwhile I will see if running a simple script inside `npm run lint` to delete the cache is sufficient.

**Comment by nathanhammond** [comment]
If we were going to make this work "right" we would need to open an RFC for ESLint

As a straw proposal this could be enabling any plugin to define a `computeCacheKey` function. Those are invoked in defined plugin order, receiving as input the output of the previous call.

The cache is stored and retrieved addressed by that cache key.

**Comment by geminiyellow** [comment]
same here, i just want to run next-auth example, but lint error.

**Comment by tknickman** [comment]
This should now be resolved, we include a cacheKey that should invalidate when making changes to your turbo.json:

https://github.com/vercel/turbo/blob/main/packages/eslint-plugin-turbo/lib/configs/recommended.ts#L5

**Comment by mirhamasala** [comment]
@tknickman - I did just run into what seems to be the same issue, so not entirely sure it's resolved?

**Comment by marcoseiza** [comment]
@mirhamasala +1 same here

**Comment by cedric-kany** [comment]
same for me, fixed with deleting eslint folder in .next/cache

**Comment by vinodsantharam** [comment]
> same for me, fixed with deleting eslint folder in .next/cache

+1 💯
