### ISSUE TITLE
capture cache hash fingerprint and whether it would be hit or miss

### ISSUE THREAD

**Issue by ilovett** [vercel/turbo#2073]
### Describe the feature you'd like to request

Would like to capture the generated hash output for a specific package *(excludes all dependency hashes)* if there is a cache hit, how could I do this?

For example, if I build a docker image, I would like to tag it based on the generate cache fingerprint one time... If I could capture the generated cache fingerprint, I can check to see if the image already exists on my remote repo and completely skip building the docker image if it's already been built.   Would I run into any pitfalls with this idea?

### Describe the solution you'd like

I could somehow capture the expected fingerprint hash **will be** for a specific / single package

```bash
export HASH=$(turbo cache hash build --filter=single-package)

echo $HASH
"5aefefec20c8a847"
```

Not sure how the "top level" scope would be chosen, but I would only want to capture one specific hash for a specific / single package

Also might be nice to know if it **will be** a cache hit or miss?

```bash
export HIT_OR_MISS=$(turbo cache hit build --filter=single-package)

echo $HIT_OR_MISS
"hit"
```

### Describe alternatives you've considered

Ahh,... I suppose grepping the output on a `--dry-run` but that seems not very tidy, might be nice to have a function for this

**Comment by gsoltis** [comment]
Would piping `--dry-run=json` to `jq` suffice?

**Comment by ilovett** [comment]
@gsoltis I suppose if I can assume that the last item in `tasks` like `jq .'tasks[-1].hash'` -- this might get me the hash?  But how can I tell from the output if it was a cache hit or miss?

**Comment by gsoltis** [comment]
`cacheState` is a new addition, yes.

You should be able to match on the task name to get the one you want more reliably than relying on the last task. Depending on what you ask `turbo` to do, there may not be a deterministic "last task"

**Comment by ilovett** [comment]
@gsoltis I suppose I would have to jq for *both properties* `cacheState.remote` and `cacheState.local` ?

Could we not have one property that specifies whether it was not cached, local cached, or remote cached?

```
"cached": false | "local" | "remote"
```

In the above example, `false` would be `miss` -- `local` and `remote` are truthy and therefore `hit`

But furthermore, they also specify *where* they were cached

**Comment by nathanhammond** [comment]
We can't tell you which cache you'd be using when executing dry run. It will depend on the flags and configuration you pass into a separate execution. As a consequence of that enumerating the states of each cache is the best design.

The API shape of this feature has shipped, isn't going to be changed, and can be used to support your goal (even if you have to write a more-complicated `jq` query). I'm going to close this as "complete" as we have no plans to alter this design.
