### ISSUE TITLE
Caching not working for Nuxt v3

### ISSUE THREAD

**Issue by smakhtin** [vercel/turbo#2078]
### What version of Turborepo are you using?

1.5.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

In Vercel logs when Nuxt v3 is built first time it builds to:
```
.vercel/output
```

When cache hit cache is replayed to:

```
 .output/
```

Because the caching and replaying structures are different Vercel can't find dist folder after build:
```
Error: No Output Directory named "dist" found after the Build completed.
```

### Expected Behavior

Build and replay folder structure should be similar. `Dist` folder should be found after cached build.

### To Reproduce

Nuxt V3 project on Vercel with Turborepo and remote cache.

**Comment by smakhtin** [comment]
@tknickman sure, here is `turbo.json`:

```json
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": ["^build", "$GQL_HOST"],
      "outputs": [
        "dist/**",
        ".output/**",
        "artifacts/**",
        "cache/**",
        "typechain-types/**",
        "pages/.vitepress/dist/**",
        ".nuxt/**",
        ".vercel/**"
      ]
    },
    "lint": {
      "dependsOn": ["$PRIVATE_KEY", "$OWNER_ADDRESS", "$LATEST_ADDRESS"],
      "outputs": []
    },
    "dev": {
      "cache": false
    },
    "test": {
      "dependsOn": ["^build"],
      "outputs": []
    },
    "codegen": {
      "outputs": ["generated/**"]
    }
  },
  "globalDependencies": [".env"]
}
```

**Comment by anthonyshew** [comment]
Going to close this one due to inactivity! If you think there's still a problem, please open a fresh issue.
