### ISSUE TITLE
The "^" is magic and needs an example

### ISSUE THREAD

**Issue by mehulkar** [vercel/turbo#2110]
### Discussed in https://github.com/vercel/turborepo/discussions/2084

<div type='discussions-op-text'>

<sup>Originally posted by **AddictArts** September 26, 2022</sup>
I am reading and re-reading multiple times "The `^` symbol explicitly declares that the task has a dependency on a task in a workspace it depends on."

Without an example or better explanation I am unclear exactly the behavior. The declaration  `"dependsOn": ["^build"]` has no other build pipelines named build to depend on. Also in other workspaces the build commands in scripts can't declare dependencies they don't have `turbo.json's` to map dependencies.

The issue an poor clarity is that `dependsOn` is used to mention other pipelines, but with `^` it seems to be changing the semantics and imply some sort of workspace dependency pipeline that is implicit. It might be better to have a different key?

I think what it is saying is that if a workspace package depends on another local workspace package it will build that first? At least an example would make it explicitly clear. I'd prefer not to make assumptions on what will happen.

Note: To make matters worse, at least  for me, recent youtube "How many apps can you buld in one Turborepo?" the author never adds this magic `^` or the `dependsOn` in the build pipeline. I thin the reason is none of the apps depend on each other. Turbo is fairly explicit and clear, easy to reason about expect the magic `^`.
</div>

**Comment by connorjs** [comment]
I agree that a dedicated “`turbo.json` API doc page” would help. I often have to navigate directly to <https://turbo.build/repo/docs/core-concepts/monorepos/running-tasks#defining-a-pipeline>. (Searching “Pipeline” brings me to a section in the `0.4.0` blog post: <https://turbo.build/blog/turbo-0-4-0#pipelines>.)

As for this specific question, which caught my eye, we can probably elaborate on the existing code comment which describes `^`.

```text
// A workspace's `build` task depends on that workspace's
// topological dependencies' and devDependencies'
// `build` tasks  being completed first. The `^` symbol
// indicates an upstream dependency.
"dependsOn": ["^build"],
```

So, `^` means “the packages’s dependencies” where dependencies mean `dependency` and `devDependency` fields of `package.json`.

**Comment by mehulkar** [comment]
We have a better page for this now: https://turbo.build/repo/docs/core-concepts/monorepos/task-dependencies with examples.
