### ISSUE TITLE
Fails to parse pnpm-lock.yaml when `use-inline-specifiers-lockfile-format=true`

### ISSUE THREAD

**Issue by fubhy** [vercel/turbo#2131]
### What version of Turborepo are you using?

1.5.5

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Pnpm recently added an (experimental) feature that improves the pnpm-lock.yaml syntax. This is particularly useful to produce more digestable git diffs in lock file changes. However, since it affects the structure of the lock file, turborepo is not able to parse it anymore. 

### Expected Behavior

Turborepo supports `use-inline-specifiers-lockfile-format=true`

### To Reproduce

Configure `use-inline-specifiers-lockfile-format=true` in `.npmrc`, delete the existing `pnpm-lock.yaml` and run `pnpm install` again. Now, run any `pnpm turbo` command to see the error.

**Comment by chris-olszewski** [comment]
Supporting this lockfile format would be good, but since it's experimental and doesn't have any functional change it'll be hard to prioritize.

**Comment by chris-olszewski** [comment]
Support for this was added along with pnpm 8 since this was changed to the default for pnpm 8: https://github.com/pnpm/pnpm/pull/5810
