### ISSUE TITLE
Add `--grouped` flag to group log output 

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turbo#219]
### Describe the feature you'd like to request

> Output of steps are intermingled and can be a little hard to read

<img width="618" alt="CleanShot 2021-12-12 at 18 03 32@2x" src="https://user-images.githubusercontent.com/4060187/145733177-98d75d05-49d9-4fdd-9362-a9c808493a78.png">

https://twitter.com/yangshunz/status/1470019087669489665

### Describe the solution you'd like

- [ ] Add a `--grouped` flag that will not stream, but buffer and print all logs of a task once in a single group after a task is completed. This should be the default log behavior in non-interactive terminal processes. Our [`logstreamer`](https://github.com/vercel/turborepo/tree/main/cli/internal/logstreamer) abstraction already has an option for this, but need to make sure that prints to stdout/stderr are not intermingled. Ideally, writes should print First In, First Out, so a (new) queue/channel might be needed inside of [`run_state.go`](https://github.com/vercel/turborepo/blob/main/cli/internal/run/run_state.go#L85).
- [ ] Update documentation

### Describe alternatives you've considered

- `--buffered` flag name

**Comment by marklawlor** [comment]
Could this be enabled selectively?

For example, I may wish to only group the `build` tasks but stream the `dev` ones? That way if `dev` depends on `build`, it will initially group the `build` logs but then switch to streaming for the `dev` tasks.

**Comment by meehawk** [comment]
@jaredpalmer is this taken up? If not I'd love to take this up. Any guidance would be awesome

**Comment by szk2s** [comment]
Would love this. Our CI log is almost useless.

**Comment by georeith** [comment]
+1 could really use this for test output

**Comment by ruettenm** [comment]
We have the same problem in a bigger project (turbo.json n around 300 lines and 25 package.json in the mono repo). It's always a bit hard to find something in the log :-)

This feature would be really helpful for us ❤️

**Comment by robaca** [comment]
It also would be cool, if in that case, an additional parameter would toggle turbo to output GitHub Workflow Group statements for every task, maybe even with a nice `title`.

```
::group::{task name}
::endgroup::
```

(see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines)

**Comment by mehulkar** [comment]
Couple naming options that have been floated internally:

- `--log-stream: natural | grouped`
- `--log-order: stream | grouped`

The `--log-*` prefix feels like a good fit after `--log-prefis` lands.

(cc @rafaeltab if you're interested in picking this up, let me know and I can help you get it merged. You can pick either of the names and we can change it once we get consensus here / internally)

@robaca, we're interested in handling the Github log grouping you mentioned after prefixing and grouping options land  independently. The idea would be to compose both to make it Just Work in Github.

**Comment by DivvSaxena** [comment]
How can i contribute to this issue I am just a begineer?

**Comment by rafaeltab** [comment]
@DivvSaxena Hey! I am working on this issue, and while not at a massive pace I am getting close to finishing it. 
I assume you got here because of the 'good first issue' tag, which is way underused.

If you still want to contribute to Turborepo, possibly through a different issue keep reading.

If you join the discord, perhaps someone can point you to a different issue you could pick up. If you mention me there, I'll try to get you in contact with someone who could point you in the right direction.

If you don't have discord or are unable to join the discord server for some other reason please let me know, and I'll try to get someone looking at this.

**Comment by mehulkar** [comment]
This was merged in #3916, thanks @rafaeltab!
