### ISSUE TITLE
Documentation for turborepo integration with stencilJS

### ISSUE THREAD

**Issue by MogLuiz** [vercel/turbo#2194]
### Describe the feature you'd like to request

Documentation of turborepo integration with stencilJS.
StencilJS is a webcomponent compiler that is widely used for design-system creation. It is present in companies such as Apple, Amazon, Porsche, Microsoft etc...

StencilJS documentation -> https://stenciljs.com/

### Describe the solution you'd like

A document that includes solutions for the integration of tools.

### Describe alternatives you've considered

I think the documentation with practical examples would be very interesting for the community.

**Comment by mehulkar** [comment]
Hey @MogLuiz did you try this out already? Turbo doesn't particularly care about what packages are available in each workspace, so there shouldn't be anything Turbo related to set this up. If you run into any specific issues, or if you're looking for any guidance, feel free to re-open! We'd also be open to contributions to the `examples/` folder if you want to make a pull request!
