### ISSUE TITLE
eslint-plugin-turbo: `no-undeclared-env-vars` does not work when access to environment variables with `indexed` syntax instead of `dot`

### ISSUE THREAD

**Issue by smorimoto** [vercel/turbo#2196]
### What version of Turborepo are you using?

1.5.6

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

As the title says, the `no-undeclared-env-vars` of `eslint-plugin-turbo` does not work correctly when access to environment variables with `indexed` syntax instead of `dot`.
It's a bug that happens in the environment that has a rule called [`noPropertyAccessFromIndexSignature`](https://www.typescriptlang.org/tsconfig#noPropertyAccessFromIndexSignature) of TypeScript enabled.

### Expected Behavior

Anyway the rule should be able to catch it...

### To Reproduce

```typescript
// catchable
process.env.TURBOREPO
// uncatchable
process.env["TURBOREPO"]
```

**Comment by smorimoto** [comment]
@nicolas-webdev This is a bug I found in the repository which is under the enterprise contract. Not in a rush, but the real (theoretically) catchable problem is just one half.

**Comment by gnohj** [comment]
@smorimoto if you look in the code it shows that it was intentionally left out, so not sure its a bug but more of a feature request

**Comment by tknickman** [comment]
@smorimoto this should now be resolved!

**Comment by smorimoto** [comment]
Oh wow! That’s amazing!

**Comment by smorimoto** [comment]
@tknickman I've tried to check that with the latest canary release, but I can't see anything being fixed. Could you give me a specific commit in which you all fixed?

**Comment by smorimoto** [comment]
@tknickman ping

**Comment by smorimoto** [comment]
ping

**Comment by mehulkar** [comment]
Re-opening this so it's back in our queue (Tom's currently on leave)

**Comment by gsoltis** [comment]
@smorimoto Sorry for the delay! I believe #5052 is the relevant PR. Have you tried with a recent release? 

If you have a specific construct that is not behaving as expected, I think the best approach is to see if we can come up with a failing test case [here](https://github.com/vercel/turbo/blob/main/packages/eslint-plugin-turbo/__tests__/lib/no-undeclared-env-vars.test.ts#L10). I'm happy to help put that together if you've got an example that we can use.

**Comment by gsoltis** [comment]
@smorimoto I've also put together #6254 to explicitly check string literal indexing, although before they should've been ignored and not flagged. You can see new test cases to that effect [here](https://github.com/vercel/turbo/pull/6254/files#diff-83a7e65178b057711489f2f900751fb70940e0be006116e8bb70a880e667e608R14)

**Comment by smorimoto** [comment]
Nice!

**Comment by gsoltis** [comment]
Latest canary has the new code.
