### ISSUE TITLE
create-turbo showHistory and showVersion might not be needed

### ISSUE THREAD

**Issue by dragos199993** [vercel/turbo#2249]
### What version of Turborepo are you using?

1.5.7-canary.0

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

This is not really a bug report, but rather a very, very small clean up. Noticed that on:
turborepo/packages/create-turbo/src/index.ts

line 71/72, showHistory and showVersion are used based on the selected flag. From what I tested, those flags are the default one and this 2 if statements can be removed. Tested both with the shortened -h and -v and it works without this 2 lines.

### Expected Behavior

Same behavior, but without 2 if statements (yes, I know it's nitpick) 😆 

### To Reproduce

go to turborepo/packages/create-turbo/src/index.ts and check line 71/72

**Comment by dragos199993** [comment]
If this change is wanted, I can open a PR with this small change as well. Thanks!

**Comment by mehulkar** [comment]
For other readers, referencing these lines:

https://github.com/vercel/turborepo/blob/dae9e9a40d24b517dbc1e5928dd86b68f91c41e7/packages/create-turbo/src/index.ts#L72-L73

@dragos199993 I think you're right! https://github.com/sindresorhus/meow#meowoptions will use the `helpText` by default and `--version` also works by default. A PR would be great!
