### ISSUE TITLE
Client Timeout should be configureable

### ISSUE THREAD

**Issue by tm1000** [vercel/turbo#2280]
### Describe the feature you'd like to request

See: https://github.com/vercel/turborepo/discussions/1993

There is a timeout hardcoded here: https://github.com/vercel/turborepo/blob/d79261f1b6da79ee5cbeb3f0988003a303eb15e3/cli/internal/client/client.go#L77

This causes timeouts for assets that take more than 20s to upload (like over my slow home connection to a remote)

Note: This used to be a timeout of 60 seconds but was changed to 20 in this PR: https://github.com/vercel/turborepo/pull/545

### Describe the solution you'd like

The timeout should be configurable

### Describe alternatives you've considered

I've tried different implementations but ultimately its because my home internet connection is not fast enough to upload the asset in under 20 seconds

**Comment by mehulkar** [comment]
That seems reasonable. Would you expect this to be a user configurable number (given your use case) or something in the turbo.json config? It could go into the `remoteCache` config or be a CLI arg. (which I notice now isn't documented in our [Configuration options](https://turborepo.org/docs/reference/configuration))

**Comment by tm1000** [comment]
HI @mehulkar thanks for the comments!

- In the turbo.json is fine (didnt know about the `remoteCache` config myself). Really whatever is easier for you to program
- It only applies to upload/download not the entire command turbo is running.

**Comment by mehulkar** [comment]
Reasonable ask. If you're up for making a PR, go for it!

**Comment by tm1000** [comment]
@mehulkar This is actually a duplicate of #2096

**Comment by mehulkar** [comment]
Thanks for hunting that down! Closing this in favor of the older #2096. (If you could update your "fixes" in the PR too, that would be great 😄 )
