### ISSUE TITLE
`with-docker` example fails to build due to `/app/yarn.lock: no such file or directory`

### ISSUE THREAD

**Issue by kriswuollett** [vercel/turbo#2284]
### What version of Turborepo are you using?

`latest` as of 2022-10-20

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

The `with-docker` example fails to build. Tested on macOS 12.6, Docker version 20.10.20, Docker Compose version v2.12.0. 

The `builder` target fails:

```
#24 [with-docker-api builder 7/7] RUN turbo prune --scope=api --docker
#24 0.301  ERROR  could not construct graph: 1 error occurred:
#24 0.301       * reading yarn.lock: open /app/yarn.lock: no such file or directory
#24 0.301 
#24 0.301 
#24 ERROR: executor failed running [/bin/sh -c turbo prune --scope=api --docker]: exit code: 1
```

[log.txt](https://github.com/vercel/turborepo/files/9831128/log.txt)

### Expected Behavior

Example builds following directions at:
https://github.com/vercel/turborepo/blob/d79261f1b6da79ee5cbeb3f0988003a303eb15e3/examples/with-docker/README.md?plain=1#L39-L42

### To Reproduce

Check out this commit:

```
commit d79261f1b6da79ee5cbeb3f0988003a303eb15e3 (HEAD -> main, origin/main, origin/HEAD)
Author: Nathan Hammond <nathan.hammond@vercel.com>
Date:   Thu Oct 20 05:42:11 2022 +0800

    Specify branch in release process.
```

Go to the `examples/with-docker` folder. Run the following command:

```shell
COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -f docker-compose.yml build --parallel --no-cache=true --progress=plain
```

**Comment by tknickman** [comment]
Did you run `yarn install` first?

**Comment by chris-olszewski** [comment]
The initial error comes from not running `yarn install` in `with-docker` since prune requires a `yarn.lock`. I'll quick put up a PR to add this to the instructions.
