### ISSUE TITLE
eslint-plugin-turbo doesn't match for non-dollar prefixed env vars?

### ISSUE THREAD

**Issue by nathanhammond** [vercel/turbo#2288]
`BASEURL` is somehow not detected in the attached repo; I suspect that $-prefixed matching when we moved to `globalEnv` is breaking this.

https://github.com/JSGehlen/dummyturbo

**Comment by anthonyshew** [comment]
This looks pretty old. I'm sure we've had many iterations since 3 years ago.

If you're running into this as a problem, please open up a new issue.
