### ISSUE TITLE
Inconsistent "cache hit" (regression) on v1.6.0+

### ISSUE THREAD

**Issue by Joroze** [vercel/turbo#2307]
### What version of Turborepo are you using?

1.6.1

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Figured I'd just report this bug that is occurring again sooner than later. 

https://github.com/vercel/turborepo/issues/2004#issuecomment-1287375565

**TLDR**: Sporadic cache misses that I've noticed when using Vite with the React Plugin on NPM.

_package.json_
```
...
"vite": "3.1.8",
"@vitejs/plugin-react": "2.1.0",
```
NPM v8.11.0 (Node v16)
OS/Chip - M2 macOS Monterey v12.6

### Expected Behavior

Caching should be 'ol reliable

### To Reproduce

Two ways to reproduce:
- Try `npm run build` against this kitchen sink example https://github.com/vercel/turborepo/tree/main/examples/kitchen-sink, and you'll notice caching is inconsistent 
-- (_admin workspace specifically because it's already using vite + react plugin_)
- Try `npm run build` against this vite example but add the react plugin to it beforehand https://github.com/vercel/turborepo/tree/main/examples/with-vite, and you'll notice caching is inconsistent

**Comment by ambiguous48** [comment]
Just thinking out loud here, but Vite generates a temporary file called `vite.config.js.timestamp-1663771012345.mjs` when building. Not sure if it is generated on every build, but I came to know of its existence after it failed to be deleted a handful of times. This file is often _not_ .gitignored because it is generated in the main project directory (adjacent to `vite.config.js`)

I wonder if/how this is handled by turbo, and if it could be interfering with the caching fingerprint.

Some discussion on the generated vite file here: https://github.com/vitejs/vite/issues/9470

**Comment by nathanhammond** [comment]
@Joroze can you try adding the  Vite file from the previous comment into your `.gitignore` file via a glob?

**Comment by Joroze** [comment]
> @Joroze can you try adding the Vite file from the previous comment into your `.gitignore` file via a glob?

@ambiguous48 @nathanhammond

I don't believe this is the culprit. I don't even see that file getting generated. I feel like I can replicate this more easily with the `admin` project in the _kitchen sink_ example.

**Comment by ambiguous48** [comment]
> I don't even see that file getting generated.

The file is deleted immediately after it's creation. You wouldn't see it unless you're looking for it.

If you actually want to see it, run this command, then in another terminal run `vite build`

```sh
for i in {1..240}; do ls -lA | grep "vite"; sleep 0.25; done
```

I'm not at all saying this is the actual cause of the issue, just replying as to why you're not seeing the file.

**Comment by Joroze** [comment]
> > I don't even see that file getting generated.
> 
> The file is deleted immediately after it's creation. You wouldn't see it unless you're looking for it.
> 
> If you actually want to see it, run this command, then in another terminal run `vite build`
> 
> ```shell
> for i in {1..240}; do ls -lA | grep "vite"; sleep 0.25; done
> ```
> 
> I'm not at all saying this is the actual cause of the issue, just replying as to why you're not seeing the file.

Thanks! Good to know. Anyways, I already tried including something like `vite.*` and `vite.config.js.*` in my root `.gitignore` and still occurs. Unless I did this wrong?

**Comment by weyert** [comment]
Are you sure the files get generated in the root? Maybe it needs to be `**/vite*`

**Comment by Joroze** [comment]
> Are you sure the files get generated in the root? Maybe it needs to be `**/vite*`

Nope, that also does not work.

**Comment by AlexAegis** [comment]
Can confirm, rolled back to 1.5.* and caching started working
