### ISSUE TITLE
Prune command with custom output folder that doesn't override .git

### ISSUE THREAD

**Issue by toto1384** [vercel/turbo#2311]
### Describe the feature you'd like to request

I want to specify which output folder of the prune command

and then the contents of that folder be updated with the new code without breaking the git integration inside

### Describe the solution you'd like

For example `turbo prune --scope=web --out="/prune/web"`
then do
`turbo prune --scope=docs --out="/prune/docs"`

### Describe alternatives you've considered

Having one output folder.
Creating a separate repository for each project build folder (in my case is `.next` folder) and uploading it to GitHub, then finding a way to start it on the VPS without the source code

# Why do I want this?
In the future, I want to open my agency where I will have one monorepo for all the projects and a lot of utils and components repos with all the functionality. all shared with the projects from my clients

So knowing that I can't possibly post my client number 1 code on client number 2 VPS, needing to split the code every time I need to upload it to the VPS

Also, I would love any alternative ideas and improvements I can make to this process

**Comment by weyert** [comment]
Do you mean you have a mono repo for agency wide but want to share the client's code in a dedicated repository?

**Comment by toto1384** [comment]
Yes

**Comment by weyert** [comment]
You might want to script something that syncs the code of the monorepo with your client's repository.  Guess, you could prune the code in CI and then commit it to the client's repository? I am curious if something like [1] or [2] could help with your problem

To me, personally, this sounds like an edge case

[1] https://github.com/SimonBaeumer/sync-monorepo
[2] https://github.com/symplify/monorepo-split-github-action

**Comment by toto1384** [comment]
Thanks for the answer @weyert. Even though the solutions feel more like a 'hack' than a 'fix', I'll use [1] if I can't find anything better. Though I still hope for a proper solution for this

**Comment by chris-olszewski** [comment]
If I'm understanding the request completely, I think it should reside in a new command. I imagine to properly support this we would want to have some form of visibility in order to provide some guarantee that code for client 1 doesn't accidentally depend on client 2.

I'm not expecting this to be worked on by the core team anytime soon, but I'd be available to give some guidance on a PR.

**Comment by anthonyshew** [comment]
Closing as this is well outside of Turborepo's current scope.
