### ISSUE TITLE
add flag to skip dependency circles blocking

### ISSUE THREAD

**Issue by juliusmarminge** [vercel/turbo#2314]
### Describe the feature you'd like to request

A flag to allow Turbo to proceed even if it finds dependency circles.

In tRPC, we test all our 4 packages in the server package, thus the server package has a devDependency to all the other packages. This causes Turbo to freak out since it doesn't like the circular dependency.

The thing is, the scripts themselves aren't causing circularity (since they are devDeps they aren't required for the build), so I would like to let Turbo to proceed even if it finds a cycle in the dependency graph.

Made a PR (https://github.com/trpc/trpc/pull/3070) to migrate tRPC to use Turbo but either:
- tests are failing when I remove the dependencies (fails to resolve path)
- turbo won't run if the dependencies are there

<img width="598" alt="CleanShot 2022-10-25 at 09 25 24@2x" src="https://user-images.githubusercontent.com/51714798/197709931-ef6853af-dbbf-44ea-8ec6-322906cba0f5.png">

### Describe the solution you'd like

allow passing a flag into turbo, maybe something like this:

```bash
turbo build --allowCycles
```

### Describe alternatives you've considered

Don't use devDeps in the cycles perhaps, since they are devDeps? Or have some way to tell turbo that the packages aren't required for the build

### Additional

We can refactor our repo so that the server package doesn't have the others as devDependencies, but [Alex likes](https://github.com/trpc/trpc/pull/3070#issuecomment-1289589167) the co-located tests.

**Comment by Ayc0** [comment]
@juliusmarminge do you know how it is implemented in turborepo?
