### ISSUE TITLE
Automatic TypeScript Configuration

### ISSUE THREAD

**Issue by ryanhaticus** [vercel/turbo#2327]
### Which project is this feature idea for?

Turbopack

### Describe the feature you'd like to request

I'd love to see automatic TypeScript configuration when using Turbopack in NextJS 13. This is already a feature in NextJS 12 with Webpack, and I'd love to see these detections continue to create a great developer experience.

### Describe the solution you'd like

"It looks like you're trying to use TypeScript but do not have the required package(s) installed." but when using Turbopack!

### Describe alternatives you've considered

Starting with Webpack in the development environment, then switching to Turbopack.

**Comment by timneutkens** [comment]
This is handled in Next.js now!
