### ISSUE TITLE
Turbo homepage is unbearably laggy without hardware acceleration

### ISSUE THREAD

**Issue by willwill96** [vercel/turbo#2346]
### Which project is this feature idea for?

Turbopack

### Describe the feature you'd like to request

Without hardware acceleration enabled on your browser, turbo.build is unbearably laggy. I've tried on the latest version of Brave and Chrome browsers and on both my personal and work computer. I can barely even scroll down on the page. I was having the same issue with the vercel conf signup page. 

With hardware acceleration enabled, everything works smoothly.

I'm honestly not sure why it's so slow, but I suspect it has something to do with the grid animation, mainly because the page otherwise seems simple.

I hope I don't sound too critical, I'm a huge fan of the work vercel has been doing and enabling. 

But right now,  it's a bit frustrating to need to use a separate browser without hardware acceleration enabled to view a docs page.

### Describe the solution you'd like

Performance without hardware acceleration improved

### Describe alternatives you've considered

Using specific browsers and settings for vercel docs

**Comment by anthonyshew** [comment]
This does look like a legitimate issue with rendering the many gradients and animations involved on the home page. However, I'm seeing just 4 reactions on here after over a year and I'd have to assume that having hardware acceleration turned off is a distant edge case.
