### ISSUE TITLE
[WEB-966] [Turbopack] Libraries depending on node-gyp-build fail parsing

### ISSUE THREAD

**Issue by Escapado** [vercel/turbo#2349]
### What version of Turbopack are you using?

latest alpha

### What package manager are you using / does the bug impact?

pnpm, Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

When using a package which depends on node-gyp-build (such as the supabase-js client), turbopack can't compile the app.

It fails with the following output:
```
error - [resolve] [project-with-next]/node_modules/node-gyp-build/index.js  Error resolving commonjs request
  unable to resolve dynamic
  
  | It was not possible to find the requested file.
  | Parsed request as written in source code: dynamic
  | Path where resolving has started: [project-with-next]/node_modules/node-gyp-build/index.js
  | Type of request: commonjs request
```

when I run `next dev --turbo --show-all` I additionally get this info:
 
```
error - [resolve] node_modules/node-gyp-build/index.js
  Error resolving commonjs request
  unable to resolve dynamic

[parse]
  node_modules/node-gyp-build/index.js
    node_modules/node-gyp-build/index.js:22:9  lint TP1002 require(???*0*) is very dynamic
        18   
        19   module.exports = load
        20   
        21   function load (dir) {
        22 >   return runtimeRequire(load.path(dir))
        23   }
        24   
        25   load.path = function (dir) {
        26     dir = path.resolve(dir || '.')
    
    - *0* ???*1*(???*2*)
      ⚠️  call of unknown function
    - *1* (...) => (??? | ???)["path"]
      ⚠️  property on function
    - *2* arguments[0]
      ⚠️  cross function analyzing is not yet supported

```

### Expected Behavior

Importing packages which depend on node-gyp-build should work.

### To Reproduce

Checkout the repo below. It's an exceedingly minimal Next 13 project.
`next dev` works as intended.
`next dev --turbo` will produce the aforementioned error.

### Reproduction Repo

https://github.com/Escapado/next-turbo-bug

<sub>[WEB-966](https://linear.app/vercel/issue/WEB-966/[turbopack]-libraries-depending-on-node-gyp-build-fail-parsing)</sub>

<sub>[WEB-1137](https://linear.app/vercel/issue/WEB-1137/[web-966]-[turbopack]-libraries-depending-on-node-gyp-build-fail)</sub>

**Comment by pauliusuza** [comment]
This is a serious blocker

**Comment by st1ng7ay** [comment]
Any idea how solve this error ?

**Comment by nathaneidelson** [comment]
Any update on this...?

**Comment by boredjoker** [comment]
still not work in next 13.5

**Comment by baufometic** [comment]
Seeing this in Next@13.5.2

**Comment by mblode** [comment]
Still happening on Next 14

**Comment by AlexDrags** [comment]
Yes, Next 14 have this problem

**Comment by buzzthedev** [comment]
Yep, still happening on Next 14.0.2

**Comment by ameyer117** [comment]
Kind of hilariously bad that `@vercel/postgres@0.5.1` (Vercel's own package) breaks Turbopack when using Next@14.0.2 with this error. Y'all really need to do some testing before releasing.

**Comment by sannajammeh** [comment]
Massive blocker here. Unable to use `supabase` inside components due to this weird error.

**Comment by AaronHernandezPerez** [comment]
Still happening in Next 14.0.3

**Comment by Warmachine13** [comment]
same problem next 14.0.3

**Comment by joacub** [comment]
Same

**Comment by captainsloths** [comment]
Can confirm this is still an issue with the latest supabase library + nextJS 14.0.3.

**Comment by BennyKok** [comment]
Even with `@vercel/postgres@0.5.1` also

![CleanShot 2023-12-05 at 16 37 53](https://github.com/vercel/turbo/assets/18395202/b71d325c-e5c3-426a-a95a-d6da067c5a41)

Would be great there's a work around for this.

**Comment by edxeth** [comment]
Just tested, Next.js 14.0.4 fixes this.
Sadly, I'm stuck on Next.js 14.0.3 because Mongoose library does not work with Next.js 14.0.4, therefore I cannot use Turbopack.
What a headache man...

**Comment by mblode** [comment]
This is finally fixed with Next 14.0.4! 🥳

**Comment by porkopek** [comment]
Yeah, fixed!

**Comment by kdy1** [comment]
Closing as fixed. Thank you for trying!
