### ISSUE TITLE
[turbopack] Running the demo often reports "Error during SSR Rendering "

### ISSUE THREAD

**Issue by flyyuan** [vercel/turbo#2352]
### What version of Turborepo are you using?

1.6.0

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

<img width="868" alt="image" src="https://user-images.githubusercontent.com/19996552/197924483-caab50e7-80d2-4032-bec4-9345e58f8ac7.png">

### Expected Behavior

Normally no error

### To Reproduce

1. Create a Next.js 13 project with Turbopack
`sh
npx create-next-app --example with-turbopack
`

2. Start the Next.js development server (with Turbopack)
`sh
next dev --turbo
`

**Comment by jridgewell** [comment]
We just fixed a bug that caused the same errors in https://github.com/vercel/turbo/commit/c222daa84088203af01d79e5e87b5d81a7868138. What version of node are you using?

**Comment by Jungzl** [comment]
> We just fixed a bug that caused the same errors in [c222daa](https://github.com/vercel/turbo/commit/c222daa84088203af01d79e5e87b5d81a7868138). What version of node are you using?

v16.18.0

**Comment by gujiwuqing** [comment]
> We just fixed a bug that caused the same errors in [c222daa](https://github.com/vercel/turbo/commit/c222daa84088203af01d79e5e87b5d81a7868138). What version of node are you using?

I had the same problem。node version is v14.19.1

**Comment by gujiwuqing** [comment]
> We just fixed a bug that caused the same errors in [c222daa](https://github.com/vercel/turbo/commit/c222daa84088203af01d79e5e87b5d81a7868138). What version of node are you using?
I changed the version number to 16.10.0 to run successfully, which I guess is the 16x starting version

**Comment by flyyuan** [comment]
> We just fixed a bug that caused the same errors in [c222daa](https://github.com/vercel/turbo/commit/c222daa84088203af01d79e5e87b5d81a7868138). What version of node are you using?

v16.15.1

**Comment by sidverma32** [comment]
@jridgewell @alexkirsz  is that fixed? because still getting this issue in starter code! please update the latest status

**Comment by jridgewell** [comment]
We're have it fixed soon, but it'll require updating Next with the next canary release (maybe tomorrow?)

**Comment by dejurin** [comment]
<img width="1041" alt="Screenshot 2022-10-29 at 01 09 29" src="https://user-images.githubusercontent.com/4470015/198740835-61ec4aa8-7852-4b17-aeb8-795a26089544.png">

When I was import NextSeo.

```
import { NextSeo } from 'next-seo';

const Page = () => (
  <>
    <NextSeo
      title="Simple Usage Example"
      description="A short description goes here."
    />
    <p>Simple Usage</p>
  </>
);

export default Page;
```

 ```
 "dependencies": {
    "next": "latest",
    "next-seo": "5.11.1",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "@types/node": "18.0.3",
    "@types/react": "18.0.15",
    "@types/react-dom": "18.0.6",
    "autoprefixer": "^10.4.7",
    "eslint": "8.19.0",
    "eslint-config-next": "latest",
    "prettier": "^2.7.1",
    "typescript": "4.7.4"
  }
```

```
node v18.10.0
npm@8.19.2
macOS 12.6 / chip M1 
```

**Comment by Sandeep06Dev** [comment]
Getting the same issue with  NodeJs v14.17.3

**Comment by padmaia** [comment]
Is anyone experiencing this with recent versions?

**Comment by timneutkens** [comment]
Going to close this as most of the Next.js test suite passes consistently now.
