### ISSUE TITLE
[Turbopack] Ignore tsconfig inside node_modules

### ISSUE THREAD

**Issue by jridgewell** [vercel/turbo#2380]
### What version of Turbopack are you using?

alpha

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Turbopack is applying the `tsconfig.json` configurations found inside `node_modules` dependencies, breaking [with-atlaskit](https://github.com/vercel/next.js/tree/2551978fa40b68882daa349019f13f8f783571f5/examples/with-atlaskit).

Moved from https://github.com/vercel/the-three-body/issues/117

### Expected Behavior

`tsconfig.json` should be ignored inside `node_modules` dependencies.

### To Reproduce

Run atlaskit's example with turbopack

### Reproduction Repo

https://github.com/vercel/next.js/tree/2551978fa40b68882daa349019f13f8f783571f5/examples/with-atlaskit

**Comment by kwonoj** [comment]
Close as we think it is fixed.
