### ISSUE TITLE
[Turbopack] Tabs are not responding properly , not smooth behaviour

### ISSUE THREAD

**Issue by sidverma32** [vercel/turbo#2409]
### What version of Turbopack are you using?

next 13.0.0

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Turbopack seems not responding when clicking on Tabs (majorly get stuck in last Tab click) . Have added a recording of my issue that when i clicking on "tailwind"  it is not showing the preview. Neither in network call. 

Once i reload the page or click somewhere else and then clicking on "tailwind" tab it's working.

Also, i noticed that the time taken to load the module on terminal goes sometimes quite high though the module is already loaded/cached. Not sure why so!!

https://user-images.githubusercontent.com/10995431/198272962-634f7628-3c8b-4c8a-b429-43f0bf8dfc18.mov

### Expected Behavior

The tabs should be working properly when clicking "N" number times and switching between tabs. Also the module should not load on every tab switch if it's already loaded once.

### To Reproduce

- follow the starter code given in doc.
- npm run dev
- navigate to http://localhost:3000/styling
- and play around with the Tabs 
- the last tab will not be responding properly.

**Comment by padmaia** [comment]
Tailwind support was added in 13.1
