### ISSUE TITLE
[Turbopack] [500] error: no storage space

### ISSUE THREAD

**Issue by MTyson** [vercel/turbo#2469]
### What version of Turbopack are you using?

How to check?

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

Vanilla next with turbopack install:
npx create-next-app --example with-turbopack

followed by devmode:
npm run dev
or
yarn dev

App starts, hitting root dir at post 3000 gives 500 error:
no storage space

server console shows:
[500] error: no storage space (151ms)
[500] error: no storage space (0.387ms)

This is Debian:
lsb_release -a 

Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

### Expected Behavior

Display the ui in dev mode

### To Reproduce

as described

**Comment by koutoftimer** [comment]
@MTyson works for me. Well, there are issue, but not when I'm opening root directory.

```
$ node --version
v18.11.0
$ npm --version
8.19.2
```

**Comment by the-mgi** [comment]
i am having the same issue, with differences in the environment.
i am using yarn, and this is my OS
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

**Comment by padmaia** [comment]
Is anyone still seeing this with recent versions?

**Comment by padmaia** [comment]
Closing this as I haven't heard of anyone experiencing this recently. Let us know if we need to reopen.
