### ISSUE TITLE
[Turbopack] WebSocket connection to 'ws://localhost:3000/_next/webpack-hmr' failed

### ISSUE THREAD

**Issue by blopez2010** [vercel/turbo#2496]
### What version of Turbopack are you using?

default for next 13

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Adding the `--turbo` on the `package.json/scripts/dev` value throws the error in the browser console.

### Expected Behavior

shouldn't throw any error in the browser console.

### To Reproduce

1. Create a monorepo with Turborepo.
2. Locale the `package.json` within the web app.
3. Add `--turbo` at the end of `"dev": "next dev --turbo"`
4. Add a new folder named `app`
5. Create a `page.tsx` (working with Javascript throws the same error)
6. Add a `layout.tsx` file.
7. run `pnpm dev` on the terminal.
8. Open the Browser and go to `http://localhost:3000`.
9. Open the devtools, the error should be printed like: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15872584/198854978-17e6cbb2-2861-494f-bb32-278284eaf514.png">
10. Removing the `--turbo` in the `dev` script, the browser console error goes away.

### Reproduction Repo

https://github.com/blopez2010/my-turborepo

**Comment by jridgewell** [comment]
Turbopack's dev server is not compatible with the builds produced by webpack. You may have a cached JS file or something that is continuing to make requests.

https://github.com/vercel/turbo/blob/56039940cdfac07b68e030da1396214962e99ceb/crates/turbopack-dev-server/src/lib.rs#L200-L209

**Comment by blopez2010** [comment]
Hey @jridgewell I did it and it didn't worked.

I use Blisk for development and after closing the app and reopen it again, the same error is shown. Now in the termine I'm noticing a message I haven't seen before (after restarting my laptop)

```web:dev: for everyone.
web:dev: 
web:dev: Learn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack
web:dev: Please direct feedback to: https://nextjs.link/turbopack-feedback
web:dev: 
web:dev: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
web:dev: event - initial compilation 51ms
web:dev: event - updated in 2439ms
web:dev: [404] /_next/webpack-hmr (WebSocket)
web:dev: A non-turbopack next.js client is trying to connect.
web:dev: Make sure to reload/close any browser window which has been opened without --turbo.
web:dev: event - updated in 1560ms
web:dev: error - [resolve] ... [1 paths] are hidden, run with --show-all to show them
web:dev: warning - [parse] ... [1 paths] are hidden, run with --show-all to show them
web:dev: [404] /favicon.ico (3049ms)
web:dev: event - updated in 3049ms
web:dev: event - updated in 191ms
web:dev: event - updated in 0.185ms
web:dev: event - updated in 437ms
web:dev: event - updated in 0.033ms
web:dev: [404] /_next/webpack-hmr (WebSocket)
web:dev: A non-turbopack next.js client is trying to connect.
web:dev: Make sure to reload/close any browser window which has been opened without --turbo.
web:dev: [404] /favicon.ico (0.349ms)
web:dev: event - updated in 228ms
web:dev: event - updated in 8.95ms
web:dev: [404] /favicon.ico (0.452ms)
web:dev: event - updated in 394ms
web:dev: [404] /_next/webpack-hmr (WebSocket)
web:dev: A non-turbopack next.js client is trying to connect.
web:dev: Make sure to reload/close any browser window which has been opened without --turbo.
web:dev: event - updated in 174ms
web:dev: event - updated in 25ms```

Am I missing something? 

One thing to add; when I created the monorepo, the nextjs version in the package.json was the v12 and I manually upgrade to the v13 (removing the `node_modules` and `npm i`)

**Comment by kwonoj** [comment]
This seems due to new appdir adds dev overlay installs hmr socket

(https://github.com/vercel/next.js/blob/9bf811eea0028dcc4f74070e8a98c5d11da97d41/packages/next/client/components/react-dev-overlay/internal/helpers/use-websocket.ts#L25)

We'll probably need to update dev overlay to aware --turbo to suppress connection / or disable overlay itself.

**Comment by mmiszy** [comment]
It's curious this bug doesn't occur outside of a monorepo setup.
I can reproduce it in an almost-empty turborepo setup:

1. `npx create-turbo@latest turbopack-bug`
2. Update `next` to `canary`
3. Enable `experimental.appDir: true` in `apps/web/next.config.js`
4. Delete `apps/web/pages`
5. Add `apps/web/app/page.tsx` with `export default function() { return <div>Hello</div>; }`
6. Run `next dev --turbo`
7. Observe the bug:

<img width="758" alt="Screenshot 2022-10-30 at 10 55 00" src="https://user-images.githubusercontent.com/1338731/198872758-cd2bd853-3184-4ccd-a566-a23b4d391501.png">
<img width="369" alt="Screenshot 2022-10-30 at 10 55 14" src="https://user-images.githubusercontent.com/1338731/198872763-7f954b49-92cd-4d2b-bbe1-8506b37e39fb.png">
<img width="743" alt="Screenshot 2022-10-30 at 10 55 40" src="https://user-images.githubusercontent.com/1338731/198872785-905eccc7-f4ed-4084-a68c-48f70ab2baee.png">

**Comment by barthicus** [comment]
Can confirm @mmiszy 's words. I wanted to play with the new Next.js `appDir` and `next dev --turbo` mode but it failed on basic setup with monorepo. It works fine only in the old `next dev` mode.
Fresh install, no cache. I use `pnpm` btw.

**Comment by useafterfree** [comment]
I got this yesterday when working with multiple next projects. I solved it by issuing a 'killall node' and then restarting.

**Comment by EtZeta** [comment]
If you delete "turbo.json" in the monorepo, webpack hmr don't load.

**Comment by hunghvu** [comment]
> It's curious this bug doesn't occur outside of a monorepo setup. I can reproduce it in an almost-empty turborepo:
> 
>     1. `npx create-turbo@latest turbopack-bug`
> 
>     2. Update `next` to `canary`
> 
>     3. Enable `experimental.appDir: true` in `apps/web/next.config.js`
> 
>     4. Delete `apps/web/pages`
> 
>     5. Add `apps/web/app/page.tsx` with `export default function() { return <div>Hello</div>; }`
> 
>     6. Run `next dev --turbo`
> 
>     7. Observe the bug:
> 
> 
> <img alt="Screenshot 2022-10-30 at 10 55 00" width="758" src="https://user-images.githubusercontent.com/1338731/198872758-cd2bd853-3184-4ccd-a566-a23b4d391501.png">
> 
> <img alt="Screenshot 2022-10-30 at 10 55 14" width="369" src="https://user-images.githubusercontent.com/1338731/198872763-7f954b49-92cd-4d2b-bbe1-8506b37e39fb.png">
> 
> <img alt="Screenshot 2022-10-30 at 10 55 40" width="743" src="https://user-images.githubusercontent.com/1338731/198872785-905eccc7-f4ed-4084-a68c-48f70ab2baee.png">

Can confirm. HMR is not working while this error happens, meaning I need to F5 the page to reflect the changes. This happens even on a clean installation with `turborepo` (no cache, nothing)..

```
web:dev: [404] /_next/webpack-hmr (WebSocket)
web:dev: A non-turbopack next.js client is trying to connect.
web:dev: Make sure to reload/close any browser window which has been opened without --turbo.
```

**Comment by timmeade** [comment]
I have hit this hard also.

**Comment by desire** [comment]
+1

**Comment by naeri-kailash** [comment]
+1

**Comment by ljq0226** [comment]
+1

**Comment by mjth** [comment]
+1

**Comment by Anishali2** [comment]
I solved this issue opening localhost in a single tab of the browser and closed all the tabs containing localhost in there URL
Also try starting the server again using with --turbo flag
