### ISSUE TITLE
HMR update client hook

### ISSUE THREAD

**Issue by dherault** [vercel/turbo#2529]
### Which project is this feature idea for?

Turbopack

### Describe the feature you'd like to request

Hi,

I wonder if a client-side hook for HMR updates is or will be available for Turbopack-enabled clients running in dev mode.

### Describe the solution you'd like

A websocket hook.

Something akin to (Vite.js):
```js
hot.on('vite:beforeUpdate', () => {
    // Do something
})
```

### Describe alternatives you've considered

None so far.

**Comment by jridgewell** [comment]
We already support a limited set of [Webpack's HMR API](https://webpack.js.org/api/hot-module-replacement). I'm certain we'll add more support as we progress through the alpha.
