### ISSUE TITLE
[turborepo] some weird behavior of 'dependsOn'

### ISSUE THREAD

**Issue by Sleaf** [vercel/turbo#2534]
### What version of Turborepo are you using?

1.6.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I have 2 projects named A,B in my monorepo

- B depends on A( "dependencies": { "A": "workspace:*"}  in package.json of B)
- A has no outputs, B has outputs.
- B have 'build' script, A has no script. 

**case 1:**
```json5
# turbo.json
"pipeline": {
    "build": {
      "outputs": [
        "dist/**"
      ]
    }
}
```
after `turbo run build`, I change A , cache of B still hit

**case 2:**
```json5
# turbo.json
"pipeline": {
    "build": {
      "outputs": [
        "dist/**"
      ],
      "dependsOn": ["^build"]
    }
}
```
after `turbo run build`, I change A, cache of B missed.

The behavior of **case 2** is what I expected, but the config confuses me. A has no 'build' script, but ` "dependsOn": []` or miss the field will skip checking these depends what should be checked.

[offical docs](https://turbo.build/repo/docs/reference/configuration#dependson) doesn't talk about the logic of 'dependsOn',  I'm not sure if this is an bug.

### Expected Behavior

Caches of parent projects will not hit after changing depends  whether 'dependsOn' was set or not.

### To Reproduce

follow descriptions

**Comment by chris-olszewski** [comment]
This is expected behavior:

> Prefixing an item in dependsOn with a ^ tells turbo that this pipeline task depends on the workspace's topological dependencies

The topological dependencies that the docs talk about is the package dependency graph which is where B's dependency on A resides.

I believe the [Running Tasks](https://turbo.build/repo/docs/core-concepts/monorepos/running-tasks#no-dependencies) page does a good job of walking through writing a pipeline. Any suggestions to make it clearer are welcome!
