### ISSUE TITLE
[turborepo] GitHub releases are missing

### ISSUE THREAD

**Issue by kachkaev** [vercel/turbo#2536]
### What version of Turborepo are you using?

1.6.1 or 1.6.2

### What package manager are you using / does the bug impact?

N/A

### What operating system are you using?

N/A

### Describe the Bug

https://github.com/vercel/turbo/releases shows 1.5.5, 1.5.6, 1.6.0, but not 1.6.1 or 1.6.2. Because of that Renovate PRs like https://github.com/blockprotocol/blockprotocol/pull/732 cannot release notes that are quick to digest. It’s hard to know what has changed.

### Expected Behavior

New release tags are created as before, Renovate PRs contain clickable release notes like in https://github.com/blockprotocol/blockprotocol/pull/730

### To Reproduce

See https://github.com/blockprotocol/blockprotocol/pull/732

**Comment by chris-olszewski** [comment]
Thanks for the report. Just created the releases.

**Comment by kachkaev** [comment]
This has been fixed:
- https://github.com/vercel/turbo/releases/tag/v1.6.1
- https://github.com/vercel/turbo/releases/tag/v1.6.2
- https://github.com/vercel/turbo/releases/tag/v1.6.3

Thanks!
