### ISSUE TITLE
[Turbopack] @Next/Font is not working properly with turbopack

### ISSUE THREAD

**Issue by imran-prog** [vercel/turbo#2545]
### What version of Turbopack are you using?

default from next 13

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

@next/font isn't working with the turbo pack properly. The turbo pack is throwing an error that @next/font/google failed to run or is incorrectly configured while I am importing it in my layout file in the app directory. Alongside the error, it is suggesting that I run the server without a turbo pack. I am trying to import the inter-font as per the documentation. The main reason for this issue is that turbo pack `--turbo` is running perfectly in all other scenarios if don't use this library.

### Expected Behavior

The font should load properly as it does without the turbo pack bundler compilation.

### To Reproduce

1. Install Next Js 13 using npx `npx create-next-app app-name`
2. Create a new directory with the `app` name
3. Add the `layout.jsx` file in the app directory
4. Then, create the `page.jsx` file in app directory and create a basic react component
5. Install @next/font library using node package manager `npm install @next/font`
6. Import @next/font library in layout.jsx using `import { Inter } from "@next/font/google"`
7. Initialize the font by creating the variable `const inter = Inter()`
8. Finally change the HTML tag with this link `<html lang="en" className={inter.className}>`
9. Run the server using `npx next dev --turbo`
10. Open `localhost:3000` in your browser.
11. This error should be visible on the page

<img src="https://i.ibb.co/vv18Shg/image.png" alt="image" border="0">

**Comment by SkelatorIndy** [comment]
I'm encountering the same issue with the same client-side error, however if I check the server logs, it displays the error
```
warning - [resolve]
  Unsupported module
  The package @next/font is not yet supported
```

It seems like this error could be intentional based on that message, but I'm not sure if it may just be left over from previous development.
I did also only notice this error happening after upgrading to next v13.0.1, so it seems possible that that release could have broken it.

**Comment by jbertan** [comment]
Same problem here, back to npm run dev without --turbo :(

**Comment by nathanhammond** [comment]
Hey y'all, we're aware of this limitation. If you look very closely you'll see that we throw an error message about this support. We look forward to bringing support for this very soon!

https://github.com/vercel/turbo/blob/4c5cab2755444fd60aa91aaba798473e58de117b/crates/turbopack/src/lib.rs#L66-L67

#2545 and #2494 are both reporting the same thing. At this point it's not _exactly_ a bug, more a known limitation, and internally we're tracking toward implementing it. @wbinnssmith is the person currently investigating it.

In the mean time this is a possible workaround to enable using fonts with Turbopack:
https://nextjs.org/docs/messages/no-page-custom-font#possible-ways-to-fix-it

**Comment by dawidseipold** [comment]
Same error here.

**Comment by hwwn** [comment]
same issue here when I switch to Next 13

**Comment by nvuhung** [comment]
I have same issue, any update for this?

**Comment by hwwn** [comment]
> I have same issue, any update for this?

I just delete the @next/font use something else to replace it

**Comment by nvuhung** [comment]
> > I have same issue, any update for this?
> 
> I just delete the @next/font use something else to replace it

Yes, I have changed to load font by that way https://nextjs.org/docs/messages/no-page-custom-font#possible-ways-to-fix-it and it works. But I cannot use the Optimize Font with turborepo.

**Comment by smyja** [comment]
still facing this issue

**Comment by brother-json** [comment]
I have this issue now and the issue is 'closed'. Hmm.

**Comment by christian-anunciado** [comment]
Still facing the same issue after updating to 14.0, local font not working

**Comment by timneutkens** [comment]
FYI all tests for `next/font` are now passing so this should work fine with Turbopack when using Next.js 15 (currently release candidate)

**Comment by imran-prog** [comment]
@timneutkens I just tested with Next 15 RC version and yes the font's are working fine with Turbo!!!🎉

**Comment by vishal-kumar3** [comment]
@imran-prog Getting this error in Next 15 RC turbo, How to fix this??
![image](https://github.com/user-attachments/assets/c59f41b4-dad8-47d5-8d74-a9a2c6680bb9)
![image](https://github.com/user-attachments/assets/2ece9fb6-1e62-43dd-95f7-fbd5a21499ca)

**Comment by imran-prog** [comment]
@vishal-kumar3 I think there might have been some issue during the installation process or configuration. I tried reproducing the issue with the same code you shared but for me the fonts are working fine, no matter which one i try. Can you share how did you reproduced this issue, that might help understand the issue on your end.

**Comment by vishal-kumar3** [comment]
@imran-prog just used bunx create-next-app@rc with react compiler then added this font.
This error is occurring only in linux, started same project in windows and it was working fine. Don't know whats wrong.

**Comment by atemengue** [comment]
@vishal-kumar3 I have sthe ame problem. please can you share your solution ?

**Comment by quyettranvu** [comment]
Experienced the same issue even on Windows, I think that is is because of font installation process, and if the issue persists, I may have to find alternatives. Hopefully, the issue of fonts with Turbopack can be resolved

**Comment by dickermoshe** [comment]
This issue should be reopened

**Comment by vishal-kumar3** [comment]
@atemengue @quyettranvu @dickermoshe 
Use next.js 15 or latest version, it has been fixed.
RC release might have had this problem. Since RC release is not needed anymore and we have latest stable release, opt for them.

**Comment by dickermoshe** [comment]
I'm using Next `15.2.3` on windows, this is still happening

**Comment by vishal-kumar3** [comment]
> I'm using Next `15.2.3` on windows, this is still happening

This can be due to extensions you might be using. Try in some fresh browser or remove all the extensions. If this error persists then i even don't know how to fix this and why it occurs.
