### ISSUE TITLE
with-tailwind example duplicated css

### ISSUE THREAD

**Issue by nathanhammond** [vercel/turbo#2554]
### Discussed in https://github.com/vercel/turbo/discussions/2308

<div type='discussions-op-text'>

<sup>Originally posted by **oscarsala** October 24, 2022</sup>
[this example](https://github.com/vercel/turborepo/tree/main/examples/with-tailwind) causes tailwind to be imported twice duplicating classes, and base selectors styles causing a lot of issues with specificity, has anyone been able to integrate it better?</div>

**Comment by kriswuollett** [comment]
Reported in #1809

**Comment by tknickman** [comment]
Fixed in https://github.com/vercel/turbo/pull/3557
