### ISSUE TITLE
[turborepo] hashing is including .gitignored files when inputs are specified

### ISSUE THREAD

**Issue by sppatel** [vercel/turbo#2560]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When a task has no inputs specified - changes to the package excluding .gitignored files are correctly taken into account.

However, if inputs are specified - and those inputs overlap with anything in .gitignored - the .gitignored files which match the input are taken into account which I believe is not desirable.

For example.. consider this task..

```
    "build": {
      "inputs": ["**/*.txt"],
    },
  ```

with a package that has..

```
.
├── .gitignore
├── ignored.txt
└── src
    └── include.txt
```

In this situation - if i modify ignored.txt - there will not be a cache hit and the .gitignored file is taken into consideration.

In most cases - you won't hit an issue because your .gitignored files likely aren't going to change since its most likley cached output BUT there are scenarios where this file does change every build (e.g a file that generates a start/finish timestamp for example).  In this situation a rebuild will always result in a new fingerprint.

### Expected Behavior

Inputs should always exclude .gitignored files.  The workaround of adding an exclusion .eg `:!/ignored.txt' does not work.

### To Reproduce

An easy way to reproduce is for your build script to just output a random number to the .gitignored file.  Subsequent rebuilds will never cache hit because the .gitignored file is impacting the hash.

**Comment by anthonyshew** [comment]
This intentional behavior. However, we've now added a microsyntax utility to make it easier to do exactly what you need!: https://turbo.build/blog/turbo-1-12-0#improved-inputs-ergonomics
