### ISSUE TITLE
[turborepo] TSConfig paths not resolved while using TurboRepo with PNPM

### ISSUE THREAD

**Issue by fortezhuo** [vercel/turbo#2575]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

TSConfig paths not resolved while using TurboRepo with PNPM. On VSCode, everything seem works, but while running next dev, an error "Module not found" occured. 

The error only occurs while using PNPM, and while using Yarn, everything works.

```
web:dev: error - ../../packages/ui/Button.tsx:2:0
web:dev: Module not found: Can't resolve 'ui/Text'
web:dev:   1 | import * as React from "react";
web:dev: > 2 | import { Text } from "ui/Text";
web:dev:   3 | export const Button = () => {
web:dev:   4 |   return (
web:dev:   5 |     <>
```

### Expected Behavior

Turborepo with PNPM should not ignore tsconfig path

### To Reproduce

1. clone this repo 
2. run ```pnpm dev```
3. open ```localhost:3000```

Note :
- The repo that generated using ```pnpm dlx create-turbo@latest```
- I only add / modify these files

packages/tsconfig/base.json
```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Default",
  "compilerOptions": {
    "composite": false,
    "declaration": true,
    "declarationMap": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "inlineSources": false,
    "isolatedModules": true,
    "moduleResolution": "node",
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "preserveWatchOutput": true,
    "skipLibCheck": true,
    "strict": true,
    "paths": {
      "ui/*": ["../ui/*"]
    }
  },
  "exclude": ["node_modules"]
}
```

packages/ui

Text.tsx
```
export function Text(props: any) {
  return <span {...props} />;
}
```

Button.tsx
```
import * as React from "react";
import { Text } from "ui/Text";
export const Button = () => {
  return (
    <>
      <button>Boop</button>
      <Text>Hello World</Text>
    </>
  );
};
```

index.tsx
```
export {};
```

packages/web/pages/index.tsx
```
import { Button } from "ui/Button";

export default function Web() {
  return (
    <div>
      <h1>Web</h1>
      <Button />
    </div>
  );
}
```

### Reproduction Repo

https://github.com/fortezhuo/turbo_pnpm

**Comment by nathanhammond** [comment]
This is not a Turborepo issue; you've [changed the resolution algorithm](https://www.typescriptlang.org/tsconfig#paths) by specifying `paths`. `ui` _already existed as a package_ if you've run `pnpm install` by virtue of how workspaces function.

We provide some guidance on using TypeScript here:
- https://turbo.build/repo/docs/handbook/sharing-code/internal-packages
- https://turbo.build/blog/you-might-not-need-typescript-project-references

**Comment by fortezhuo** [comment]
Actually I have found this pattern on solito monorepo (but they use yarn instead) https://github.com/nandorojo/solito/tree/master/example-monorepos/with-tailwind

And no error occurs while using yarn. And please elaborate what should I add to make this work using pnpm ?

**Comment by digoburigo** [comment]
Even don't changing the paths the error stil occurs, pnpm uses a separeted file for workspaces
`pnpm-workspace.yaml`
```
packages:
  - apps/docs
  - apps/web
  - packages/eslint-config-custom
  - packages/tailwind-config
  - packages/tsconfig
  - packages/ui
```
Doing this the only package that don't work is the `tsconfig` one.

In `package.json`
```
"workspaces": [
    "apps/*",
    "packages/*"
  ],
```
This works properly

**Comment by jcamden** [comment]
I believe the issue here might be that pnpm expects workspace package version to be formatted `"workspace/*"` whereas the examples start out with just `"*"`.
