### ISSUE TITLE
Turn off typescript by default

### ISSUE THREAD

**Issue by idleman** [vercel/turbo#2593]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

TypeScript enabled by default is 100% unnecessary. It exists multiple languages that compiles to JavaScript and they all have various advantages and disadvantages. I don't see why TypeScript should be any different. You don't need it to build scalable applications. In most project, it just add unnecessary complexity.

### Describe the solution you'd like

In the init process, ask whatever the user want to enable TypeScript or not.

### Describe alternatives you've considered

Not using the library alternatively, copy the whole code base and turn off TypeScript by default. Or just remove it manually each time.

**Comment by nathanhammond** [comment]
@idleman I understand that you're not a fan of TS in all scenarios. We want to encourage people adopting Turborepo to consider TypeScript as a good default decision. We believe that's a good place to begin a new project in 2022.

We have no plans to change our approach here and will continue to encourage TypeScript adoption.
