### ISSUE TITLE
[turborepo] prune --docker principle breaks with workspace internal packages dependencies

### ISSUE THREAD

**Issue by toniopelo** [vercel/turbo#2603]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Linux

### Describe the Bug

Let's say we have the following file structure in a monorepo with yarn workspaces
```
shared/
  pkg1/
    ...
    package.json
services/
  service1/
    ...
    package.json

package.json
yarn.lock
```

If `services/service1` require `shared/pkg1`, when using a dockerfile like:
```Dockerfile
FROM node:18-alpine as source
# ...
WORKDIR /source
COPY . .
RUN yarn turbo prune --scope=service1 --docker

FROM node:18-alpine as runner
COPY --from=source /source/out/yarn.lock .
COPY --from=source /source/out/json .
RUN yarn
COPY --from=source /source/out/full .
# ...
```
It breaks because yarn will try resolve internal package `shared/pkg1` as stated in `services/service1/package.json` and in `yarn.lock`.
This really defeat the purpose of this feature and especially the `--docker` flag because to leverage the docker layer caching in order to avoid re-running `RUN yarn`, we need to only copy the json folder first, but then `RUN yarn` will fail because internal package are not present.
This is a pretty common use case in a monorepo.

### Expected Behavior

Being able to run yarn properly without loosing ability to leverage docker layer caching

### To Reproduce

Data to reproduce are already in the `Describe the bug` section

**Comment by toniopelo** [comment]
Weel, it turns out that it was only caused by the fact that an incorrect version of yarn was running inside my docker container and didn't recognize my workspace configuration correctly. Copying `.yarn` and `.yarnrc.yml` over to the json folder fixed it.
Sorry for the noise, and I'm gonna take a nap for my brain to recover now.. :brain:

**Comment by nathanhammond** [comment]
Glad you got it figured out!
