### ISSUE TITLE
[turborepo] final resolution of dependency can change and turbo won't detect it

### ISSUE THREAD

**Issue by yarinsa** [vercel/turbo#2606]
### What version of Turborepo are you using?

1.5.6

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

We are running `--dry-run=json` in the CI in order to determine which packages changed and if to build & publish packages. 
We added a new package where we set "react-router-dom": "*", in the package.json. 
That caused change in the final package resolution, which broke to main app. 

**The problem:** no change was detected in the main app, therefore it wasn't built and tested. 

* Willing to help with code contribution to detect such a change. 

### Expected Behavior

Turborepo will identify changes in package dependencies final resolution to determine task execution 

### To Reproduce

Create monorepo with 2 packages: 

1. "app" - add "react-router-dom" : "6.3.0" as dep
2. "components" - add  "react-router-dom" : "*" as dep

Final resolution should be 6.4.3 which is the most up-to date version according to today

**Comment by nathanhammond** [comment]
(#2211)
