### ISSUE TITLE
[Turborepo] Provide a command to determine affected workspaces

### ISSUE THREAD

**Issue by notaphplover** [vercel/turbo#2648]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

As developer I want a graph API to know which worspaces would be affected under certain conditions in order to distribute the execution of a certain tasks.

Sometimes it's interesting to manually distribute task executions among different services. As an example, given my monorepo and a git commit, I want to know which tasks would be executed to run unit tests considering changes since that specific commit.

If I was working in a local environment, this could be easilly accomplished using the turborepo CLI. What happens if I want to distribute this work among several workers processing my CI pipeline? If the `foo` and `bar` workspaces are the only ones which contains `test:unit` tasks, it makes sense to me to request to launch two workers and request turborepo to launch, for each worker, the `test:unit` task for a single workspace. Without knowing beforehand which projects are affected, I cannot easily accomplish this.

### Describe the solution you'd like

Thinking in a general purpose solution, I think it would be great to add an `affected:workspaces` (I don't really care about the specific name) command line to the CLI.

It would be similart than the `run` cli command, without options which makes no sense in this case. Instead of running all the affected tasks, it would return a stringified JSON object (maybe additional output options would be a good choice) with all the workspaces affected.

Example:
```
turbo affected:workspaces --filter=my-pkg --filter=my-app --filter=[HEAD^1]
```

would return `["my-pkg"]` if and only if `my-pkg` is the name of the only workspace which contains tasks which would normally be executed by the same run command (`turbo run --filter=my-pkg --filter=my-app --since=[HEAD^1]`)

### Describe alternatives you've considered

I considered several workarounds but I didn't like any of those.
- Launching a worker for each workspace and trying to run the `test:unit` task for that workspace is not a good choice, I'm consuming resources in order to do nothing in most of the projects.

I also considered other possible solutions
- Requesting run to add a flag to actually not run tasks seems sort of a nonsense in my mind since the run command is supposed to be used to tun tasks, not running tasks would be, at least, counter intuitive.
- Requesting a task graph (the same output which is already returned by `turbo run --graph`) is also a really interesting possibility, if we want to go this way I just strongly suggest to fix the [bug which adds all possible pipeline task nodes](https://turbo.build/repo/docs/reference/command-line-reference#--graph) since that would totally mess the workspaces detection

**Comment by weyert** [comment]
Can’t you use —dryrun=json for this?

**Comment by notaphplover** [comment]
> Can’t you use —dryrun=json for this?

Yes, I can't believe a missed that option. Thank you so much and sorry for the noise
