### ISSUE TITLE
[WEB-963] [turbopack] tsconfig extends field doesn't resolve

### ISSUE THREAD

**Issue by vexCoder** [vercel/turbo#2682]
### What version of Turbopack are you using?

1.6.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

Turbopack fails on a nextjs app when there is an `extends` field in the `tsconfig.json`. Error says `extends field doesn't resolve correctly`

### Expected Behavior

Be able to extend local tsconfig files.

### To Reproduce

create a package that exports tsconfig files. import it on a next 13 app and in the tsconfig extend it. run `next dev --turbo`

<sub>[WEB-963](https://linear.app/vercel/issue/WEB-963/[turbopack]-tsconfig-extends-field-doesnt-resolve)</sub>

**Comment by ertolv** [comment]
I have got the same error. It occurred when I added analytics package from Vercel,
```
error - [typescript] [project-with-next]/node_modules/@vercel/analytics/tsconfig.json  An issue occurred while parsing a tsconfig.json file.
  extends doesn't resolve correctly
```

**Comment by yannbf** [comment]
Had the same issue, from a 3rd party library even though my tsconfig has `skipLibCheck: true`:

```
error - [typescript] [project-with-next]/node_modules/.pnpm/popmotion@11.0.5/node_modules/popmotion/tsconfig.json  An issue occurred while parsing a tsconfig.json file.
  extends doesn't resolve correctly
```

**Comment by B4rsekerDev** [comment]
Also had the same issue: https://github.com/vercel/turbo/issues/2973

**Comment by jakeleventhal** [comment]
Same here
