### ISSUE TITLE
[turborepo] `baseUrl` set in `tsconfig/nextjs.json` doesn't work in apps that extend it

### ISSUE THREAD

**Issue by albertothedev** [vercel/turbo#2685]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

I am moving a few Next.js projects to Turborepo and in those projects I am using absolute imports like this:

```typescript
// project-root/tsconfig.json
{
  // ...
  "compilerOptions": {
    // ...
    baseUrl: "."
  }
}
```

In Turborepo, when I set `baseUrl` in `packages/tsconfig/nextjs.json` like above and extend it in the projects in the `apps` directory like this:

```typescript
{
  "extends": "tsconfig/nextjs.json",
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

The absolute imports don't work. They only work when I set it in the `tsconfig.json` of each project:

```typescript
{
  "extends": "tsconfig/nextjs.json",
  "compilerOptions": { "baseUrl": "." },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

### Expected Behavior

For each project inside the `apps` directory to be able to use absolute imports when extending the `tsconfig/nextjs.json` package.

### To Reproduce

Set `baseUrl` in `packages/tsconfig/nextjs.json` and try to use absolute imports in a project that extends it.

**Comment by aminwangaa** [comment]
is the problem same? docs:build: error TS6053: File 'tsconfig/nextjs.json' not found. 
why the file is not found

**Comment by albertothedev** [comment]
> is the problem same? docs:build: error TS6053: File 'tsconfig/nextjs.json' not found. why the file is not found

Sorry, I don't understand what you mean.

**Comment by irg1008** [comment]
This and baseurl simple doesn't work in packages. Only relative imports. Build fails if using absolute imports

**Comment by nfiacco** [comment]
Running into the same issue— seems like `baseUrl` isn't included when extending the base tsconfig.

**Comment by anthonyshew** [comment]
This is an issue with the way TypeScript works rather than Next.js. Will close because of that.
