### ISSUE TITLE
[turborepo] ESLint rule `no-undeclared-env-vars` not satisfied by using `env` or `globalEnv` in `turbo.json`

### ISSUE THREAD

**Issue by rodrigoehlers** [vercel/turbo#2690]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

The ESLint rule `no-undeclared-env-vars` doesn't detect values set in the `env` keys instead of defining them with `$` in a `dependsOn` keys. The rule [docs](https://github.com/vercel/turbo/blob/main/packages/eslint-plugin-turbo/docs/rules/no-undeclared-env-vars.md) (opened by clicking on the lint error url in VS Code) don't show any usage of environment vars in the `env` key. However, the [turbo docs](https://turbo.build/repo/docs/reference/configuration) show the usage of the `env` key and even explicitly mention usage of the `$` sign in the `dependsOn` key as being deprecated. Quote:

> Using `$` to declare environment variables in the `dependsOn` config is deprecated. Use the `env` key instead.

### Expected Behavior

Using the `env` key to declare environment variables in `turbo.json` should satisfy the ESLint rule.

### To Reproduce

Use an environment variable in your app to trigger the ESLint rule. Add the environment variable as a dependency using the `env` or `globalEnv` key in `turbo.json`. Sadly using it won't satisfy the rule, showing the error.

**Comment by rodrigoehlers** [comment]
After saving the target file again, it seems to have picked the change up. Sorry!

**Comment by maxijonson** [comment]
Wow thank you @rodrigoehlers ! I've been pulling my hair for about an hour now and was on the verge of just disabling the rule for deploys 😅I had to save the file again for the error to disappear.

This does sound like some kind of bug though. I shouldn't need to re-save an already correct file for turbo to pick it up. How is it even looking at the wrong "version" of the file? Even VS Code was telling me all is ok. (had to restart the ESLint server after editing `turbo.json` though).
