### ISSUE TITLE
Docker dev enviroment

### ISSUE THREAD

**Issue by KristjanVall** [vercel/turbo#2721]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Hello how can i active docker dev environment like live reload and volume.

I have tried different things, but not achieved it.

### Describe the solution you'd like

dockerfile example
docker-compose example

### Describe alternatives you've considered

dockerfile example
docker-compose example

**Comment by anthonyshew** [comment]
This is a question rather than an issue. It's also quite stale. If you're still interested in asking this question, please ask in Discussions!
