### ISSUE TITLE
[turborepo] with-docker example's Dockerfiles violating best practices

### ISSUE THREAD

**Issue by NexZhu** [vercel/turbo#2722]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

I think the current with-docker example's Dockerfiles is not good for utilizing Docker build cache.

```dockerfile
# Set working directory
COPY . .
RUN turbo prune --scope=web --docker
```

This will copy all files in the monorepo project, which takes more time than neccessary, also if any other package change, even if that package is not a dependency of the current package, it will invalidate the build cache, causing all statements after `COPY . .` to run again.

### Describe the solution you'd like

I think `RUN turbo prune --scope=web --docker` should run outside of the Docker container, and only `COPY` the `.out` directory which will invalidate Docker build cache only if any related file actually changes.

### Describe alternatives you've considered

.

**Comment by soulchild** [comment]
@NexZhu Care to elaborate why you closed this issue? I think I'm running into exactly the same problem. Docker builds are taking ages with TurboRepo because basically the whole Docker caching mechanism is circumvented.

**Comment by NexZhu** [comment]
@soulchild Because I didn't look at the Dockerfile carefully before I opened the issue, after taking a look again, I think the `builder` stage itself runs very fast, and if the content of the `out` directory doesn't change (if soms unrelated packages change, it won't effect the `out` directory content), the `COPY --from=builder /app/out/xxx` commands' cache won't be invalidated, so overall it shouldn't slow down the build.

But if you found it taking ages, maybe I was wrong this time, and there are actually optimizations needed to be done to the Dockerfile, but I don't know where. I've reopend the issue so people can look into it more closely.

**Comment by soulchild** [comment]
@NexZhu You're right: For whatever reasons, repeated build runs now use the Docker cache correctly (from the `installer` stage onwards). Maybe I had something else tripping up the build process…

**Comment by hubertoschusch** [comment]
This doesnt work, the copy . . Causes everything to be run again once source code changes...
