### ISSUE TITLE
[turborepo] `FORCE_COLOR=1` does not work on wasm-pack packages

### ISSUE THREAD

**Issue by marcofugaro** [vercel/turbo#2727]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v1, Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

When calling `FORCE_COLOR=1 turbo run build`, the color on the output is not present for [wasm-pack](https://github.com/rustwasm/wasm-pack) packages. While it work correctly for other build tools like Vite.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/7217420/202218023-c769cb51-8cae-4df6-a7fd-010eed92fd54.png">

### Expected Behavior

<img width="660" alt="image" src="https://user-images.githubusercontent.com/7217420/202218134-6ca63bb4-1bfb-4cac-b68b-d70b3a2cca30.png">

### To Reproduce

- Create a wasm-pack project (run `wasm-pack new myproject`, see [docs](https://rustwasm.github.io/docs/wasm-pack/commands/new.html)).
- Add it to turborepo
- Add the `FORCE_COLOR=1` flag to the build command
- Run the build command

**Comment by NullVoxPopuli** [comment]
I see this issue as well with eslint, prettier, tsc, etc

**Comment by anthonyshew** [comment]
As of 1.12, logs support colors by default! https://turbo.build/blog/turbo-1-12-0#colors-in-task-logs
