### ISSUE TITLE
[turborepo] When a constant in `packages/utils` is used in `apps/www`, the key of the constant is automatically converted to number

### ISSUE THREAD

**Issue by kibaek-kimm** [vercel/turbo#2734]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Service has been implemented through Turborepo.
There are constants in `packages/utils` and there are util functions that use these constants.
And the key of constants is composed of a string meaning a specific code as shown below codes.

```
{
  "001": "value",
  "017": "value",
  ...
}
```

Constants in `packages/utils` are referenced by `apps/www`.
It works fine in dev. However, the problem is that when build project, key is converted to a number.

```
{
   1: "value",
   17: "value",
  ...
}
```

### Expected Behavior

The key of the constant must not be converted to number.

### To Reproduce

Set the key values of the object to "001", "017" and run build.

I tried implementing the repro code using `npx create-turbo@latest` boilerplate, but it worked fine.
Confusing

**Comment by tknickman** [comment]
This is likely an issue with your build process and not an issue with turbo. I'm going to close this for now, but if you can share a reproduction case we'd be happy to reopen and take a deeper look.

**Comment by kibaek-kimm** [comment]
it fix this bug by setting `swcMinify: false`.  But i think this is not root cause.
