### ISSUE TITLE
[turbopack] 

### ISSUE THREAD

**Issue by mnengwa** [vercel/turbo#2772]
### What version of Turbopack are you using?

alpha

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

Hi, I had set up my aliases which work fine when using the default bundler (Webpack) in Next 13. However, it all breaks when I use the turbo flag to start the dev server.

![image](https://user-images.githubusercontent.com/25894745/202859685-ea8176c2-245c-4a02-8437-734de13cfb9e.png)

![image](https://user-images.githubusercontent.com/25894745/202859648-7e8b54fc-73cc-4437-895d-cf9a8b8e9c0a.png)

### Expected Behavior

When using the `npm run dev --turbo` on a Next 13 project, it should recognize the path aliases as defined in the `jsconfig.json` file.

### To Reproduce

1. Install Next 13 and enable turbo by changing `npm run dev` to `npm run dev --turbo`
2. Create a directory named `lib` and inside it create two more `assets` and `components`
3. Create a `jsconfig.js` file with the following content
```
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@/assets/*": [
                "lib/assets/*"
            ],
            "@/components/*": [
                "lib/components/*"
            ]
        }
    }
}
```
5. Start the dev server with `npm run dev`
6. Try the path alias in an import

**Comment by Xariwey** [comment]
it only happens when using --turbo

```
"scripts": {
  "dev": "next dev --turbo",  🔴
  "dev": "next dev",  🟢
}
```

```
🔴 yarn dev --turbo
```
```
🟢 yarn turbo dev
```

**Comment by Fnll** [comment]
`jsconfig.json` right now has not been supported. I think it's a feature request as #2357 mentioned.

**Comment by hlodver** [comment]
Same issue for be using the following config:
`{
  "compilerOptions": {
    "baseUrl": "src"
  }
}`

**Comment by padmaia** [comment]
`jsconfig.json` support added in Next.js 13.2
