### ISSUE TITLE
[turborepo] eslint-plugin-turbo does not support turbo.json with comments

### ISSUE THREAD

**Issue by Alxandr** [vercel/turbo#2796]
### What version of Turborepo are you using?

1.5.5

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

If I have comments in my turbo.json (copied from the docs website here: https://turbo.build/repo/docs/core-concepts/monorepos/running-tasks#defining-a-pipeline) - `eslint-plugin-turbo` crashes on doing JSON.parse on the config.

### Expected Behavior

It should handle comments in the json as turbo itself does.

### To Reproduce

Have a `turbo.json` with comments, and run eslint in the repo with `eslint-plugin-turbo` enabled.

**Comment by jooshua-inglis** [comment]
Hey @Alxandr. I've merged a PR to fix the issue.
Just need to wait until the next release until its avaliable.

**Comment by tknickman** [comment]
Should be available now!
