### ISSUE TITLE
[turborepo] `turbo prune` creates broken `pnpm-lock.yaml`

### ISSUE THREAD

**Issue by dlehmhus** [vercel/turbo#2798]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

`turbo prune --scope="<app-name>" --docker` creates broken/incomplete `pnpm-lock.yaml` file, which leads to `ERR_PNPM_ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY` and `ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE` errors .

### Expected Behavior

Pruned `pnpm-lock.yaml` lock file should still contain every needed dependency and pruned output should also include packages that a referenced from the project root (but are not inside the `--scope`) 

### To Reproduce

```sh
git clone https://github.com/dlehmhus/pnpm-prune-root-issue-example
cd pnpm-prune-root-issue-example/
docker build -f apps/web/Dockerfile -t "pnpm-prune-example" .
```
or, to inspect the output:
```sh
pnpm exec turbo prune --scope="web" --docker
```
if you take a look at the generated `pnpm-lock.yaml` you can see two issues:

1. `apps/web` references `13.0.4_biqbaboplfbrettd7655fr4n2y`, but that dependency doesn't exists in the pruned `pnpm-lock.yaml`
2. `.` (projet root) links to `link:packages/package-for-ci` but that doesn't exist in `out/json`

### Reproduction Repo

https://github.com/dlehmhus/pnpm-prune-root-issue-example

**Comment by Kuirak** [comment]
I think I got an almost identical issue but with a git dependency which is missing the entry in `packages:` 

### Reproduction Repo
https://github.com/peerigon/turbo-pnpm-prune-git-dependency-issue

**Comment by chris-olszewski** [comment]
Hi @Kuirak, could you open up a new issue? I suspect that the `git` dependency issue will be a different fix. Thanks for the repro it really helps!

**Comment by Kuirak** [comment]
> Hi @Kuirak, could you open up a new issue? I suspect that the `git` dependency issue will be a different fix. Thanks for the repro it really helps!

Done, can be found here: https://github.com/vercel/turbo/issues/2870

**Comment by joemckenney** [comment]
I'm running into this issue as well.  Some additional context that may be helpful.

I'm on the same version of turbo, but a different version of pnpm (7.22.0).  I hit this issue on upgrade to pnpm@7.24.3.

I couldn't understand what pnpm changed that would cause this based on their changelog which is how I arrived here.

Concretely, a dependency of the workspace root, which *does* end up in the lockfile is not included as a package in the pruned output.
