### ISSUE TITLE
[turbopack] esm interrupt error when transform to lower browserslist_query

### ISSUE THREAD

**Issue by ahabhgk** [vercel/turbo#2825]
### What version of Turbopack are you using?

1.6.3

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

import a cjs module in esm module with a lower browserslist_query, will throw `Uncaught ReferenceError: module is not defined`.

### Expected Behavior

should not have the ReferenceError.

### To Reproduce

Change the browserslist_query:
<img width="905" alt="Screen Shot 2022-11-24 at 14 08 48" src="https://user-images.githubusercontent.com/42857895/203706988-9e5182cd-701f-4edc-9615-06ced8919ecd.png">

```js
// index.js
import lib from './lib.js';
console.log(lib());
```

```js
// lib.js
module.exports = async function() {
  return 1;
}
```

**Comment by ahabhgk** [comment]
It seems caused by SWC inject_helpers, [`lib.js` should be a cjs module but after `inject_helpers` it was transformed to a esm module](https://play.swc.rs/?version=1.3.19&code=H4sIAAAAAAAAA8vNTynNSdVLrSjILyopVrBVSCyuzEtWSCvNSy7JzM9TSMvTSCwq0lSo5lJQKEotKS3KUzDkquUCAOxwi%2Bc3AAAA&config=H4sIAAAAAAAAA0WOSw7DMAhE78La23aRE3TTQyAXp678ExApUeS7F7eWwmoE82Y44SMelhMashAPJUdR3GEB8hnFc2wKzmy2CpiEugPalbhgelBqxAKL8kYOFHklHaTcDEm1Ck3IQY4lhmMU%2BJobk8h1wrImuuKVsUionIebCb3%2BRTDqbbLbGFVf26BO0KPRr%2FUO%2FSqa4VGe0zie7F94Qh4%2B8QAAAA%3D%3D), and this will [not happen in babel](https://babeljs.io/repl#?browsers=chrome%2050&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=LYewJgrgNgpgdDAHgBxAJwC4GcAEBeHAQywE8A7AYxwDMJKMBLEMmsgCkLTQEocBvAFA4caGBghoWARgEBfAUA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3%2Ctypescript&prettier=false&targets=Node-14&version=7.20.4&externalPlugins=%40babel%2Fplugin-transform-runtime%407.19.6&assumptions=%7B%7D)

**Comment by kdy1** [comment]
swc now creates `var helper = require()` for `Program::Scripts`.
https://play.swc.rs/?version=1.3.46&code=H4sIAAAAAAAAA8vNTynNSdVLrSjILyopVrBVSCyuzEtWSCvNSy7JzM9TSMvTSCwq0lSo5lJQKEotKS3KUzDkquUCAOxwi%2Bc3AAAA&config=H4sIAAAAAAAAA22OSw7CMAxE95yiypotG07AhkNYwSmp8pPtSq2q3p0k%2FRAkNnH8ZjSe5dJ1amCt7t2Sv3lJQIx07pnwHASmTBRqD6zJJlHXQx24SAYcY0XrpiicBCmAe6BLSJw9QiPuogD1KDWSb3uWcjEyHlk78zZYM7dtdPSJkPnXWKwQeod%2FuwhBYBPJt0GEoKUBFZkc%2FS5w3ek2y1vDvoXO48ryM77G5vT6Ae4%2F33lWAQAA
