### ISSUE TITLE
[turbopack] css background can't load url 'https://xxx.png'

### ISSUE THREAD

**Issue by Huanqiang** [vercel/turbo#2832]
### What version of Turbopack are you using?

next 13.0.0

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Turbopack failed to compile

error - [resolve] [project-with-next]/app  Error resolving server relative import: not implemented yet
  unable to resolve server relative "//s.stu.126.net/res/images/ui/ui_new_yktnav_sprite.png"
  
  | An error happened during resolving.
  | Error message: server relative imports are not implemented yet
  | Parsed request as written in source code: server relative "//s.stu.126.net/res/images/ui/ui_new_yktnav_sprite.png"
  | Path where resolving has started: [project-with-next]/app
  | Type of request: server relative import: not implemented yet

### Expected Behavior

compile success

### To Reproduce

.title {
  color: yellow;
  background: 9999px 9999px no-repeat;
  background-position: 0 -28px;
  background-image: url(//s.stu.126.net/res/images/ui/ui_new_yktnav_sprite.png);
}

**Comment by biem97** [comment]
Create a dir named `types` on your root `ui` repo.
add this file `index.d.ts` with 
```
declare module "*.jpg" {
  const path: string;
  export default path;
}

declare module "*.png" {
  const path: string;
  export default path;
}
```
![image](https://user-images.githubusercontent.com/35174855/204072537-a6065c07-390f-4e88-9897-5e770a7703d1.png)
![image](https://user-images.githubusercontent.com/35174855/204072524-ee1c1fca-00b3-4136-ba95-fc39e438f94a.png)


You're welcome :)

**Comment by B4rsekerDev** [comment]
Had the same issue and solved by moving my wrapper component into separate client-side component, so it doesnt load on the server. There I define the background image

RootLayout:
```
  <html lang="cs" className="h-full bg-zinc-900 text-zinc-300 background">
      <head />
      <body className="h-full">
        <BackgroundComponent>
              {children}
        </BackgroundComponent>
      </body>
    </html>
```

BackgroundComponent:
```
 <main className="h-full bg-[url('../public/background.png')] bg-no-repeat bg-center bg-cover">
      <div className="bg-black h-screen w-screen bg-opacity-60 backdrop-blur-sm">
        {children}
      </div>
    </main>
```

**Comment by jridgewell** [comment]
I believe this specific issue is fixed by https://github.com/vercel/turbo/pull/4582
