### ISSUE TITLE
[turborepo] Example with vite is not working

### ISSUE THREAD

**Issue by nosyn** [vercel/turbo#2836]
`### What version of Turborepo are you using?

v1.6.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Example with vite is not working

### Expected Behavior

Example with vite should work.

There's a typo in the `vite.json` file inside `tsconfig` package. I can't create a PR so here's suggest change:
![image](https://user-images.githubusercontent.com/35174855/204069239-bf00f1b4-b05a-442f-82ef-624b8281594f.png)

### To Reproduce

```
npx degit vercel/turbo/examples/with-vite with-vite
cd with-vite
pnpm install
pnpm dev
```
![image](https://user-images.githubusercontent.com/35174855/204069135-e01b30a6-3c8f-4b76-92de-b62daaf2d37e.png)

**Comment by anthonyshew** [comment]
We've updated our examples recently! Please open a new issue if you're still running into problems.
