### ISSUE TITLE
Support `ignoreError` | `noBail` in pipeline

### ISSUE THREAD

**Issue by unional** [vercel/turbo#2842]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Add the ability to run scripts that can fail. Ignore the failure and continue.

This is useful for things like nuking the `node_modules` so that the user can run `install` in a clean slate.

Solutions like `rimraf node_modules || true` does not work cross platform/shell.

### Describe the solution you'd like

Able to specify a flag in `turbo.json` to ignore error.

The property name can be `ignoreError` or `noBail` (as in `pnpm` `--no-bail`):

```json
{
  "pipeline": {
    "nuke": {
       "ignoreError": true
    }
  }
}
```

### Describe alternatives you've considered

For `pnpm`, I'm able to create a solution without `turbo`:

```json
{
  "scripts": {
    "nuke": "pnpm --no-bail --filter=* nuke && pnpm --no-bail nuke:local",
    "nuke:local": "rimraf node_modules"
  }
}
```

But can't find any solution for `npm` and `yarn`.

`cash-true` needs global install, and `exitzero` doesn't work.

**Comment by mehulkar** [comment]
We have the [`--continue`](https://turbo.build/repo/docs/reference/command-line-reference/run#--continue) flag, but it cannot be applied to specific tasks. Does that work for you @unional or do you need a more specific control  here>

**Comment by unional** [comment]
Thanks, I think that probably works. Will close this ticket and try it out more.
