### ISSUE TITLE
improve lock deps detection 

### ISSUE THREAD

**Issue by yarinsa** [vercel/turbo#2843]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Better yarn.lock changes detection 

I've opened this issue in the past, since it broke our production
https://github.com/vercel/turbo/issues/2606

In the world of micro_packages almost every pull request includes lock change which triggers release of all the packages. 

### Describe the solution you'd like

The behavior that would be the most correct will be to detect changes is:
1. if a resolution of dependency changed
2. and this dependency affects this package
3. then detect change

### Describe alternatives you've considered

I can try to think of more complex of change detection logic using "turbo-prune" and comparing. But sounds like a lot of overhead to do it from outside.

**Comment by chris-olszewski** [comment]
Hi @yarinsa, I'm closing this in favor of #2162. If you feel that issue doesn't address your ask please feel free to reopen.
