### ISSUE TITLE
[turbopack] "From fixture location" test fails with git error 128

### ISSUE THREAD

**Issue by milahu** [vercel/turbo#2846]
### What version of Turbopack are you using?

1.6.3

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

low priority: has workaround

im trying to build turbo in nix https://github.com/NixOS/nixpkgs/pull/200788

[Test_getTraversePath](https://github.com/vercel/turbo/blob/main/cli/internal/hashing/package_deps_hash_test.go#L184-L218) throws

```
    package_deps_hash_test.go:210: getTraversePath() error = exit status 128, wantErr false
--- FAIL: Test_getTraversePath (0.01s)
    --- FAIL: Test_getTraversePath/From_fixture_location (0.01s)
    --- PASS: Test_getTraversePath/Traverse_out_of_git_repo (0.00s)
FAIL
FAIL    github.com/vercel/turbo/cli/internal/hashing    0.242s
FAIL
```

git error 128 is "undefined error" aka "read the error message in stderr"
but the test does not print stderr

when i run the test in bash

```sh
    (
      set -x
      cd /build/source
      git rev-parse --show-cdup || rc=$?
      echo rc = $rc
    )
```

i get

```
fatal: not a git repository (or any of the parent directories): .git
rc = 128
```

problems

- test assumes that source is a git repo
- stderr from git is not visible. i tried `err.Stderr` but that throws "err.Stderr undefined (type error has no field or method Stderr)". im not fluent in go, but this should be trivial
- tests TestDeleteRepoRoot and TestShutdown assume that $HOME is writable. test should create tempdir and use that as $HOME

[getTraversePath](https://github.com/vercel/turbo/blob/0fe2584912a8908907a7216a8628871d396f3e4f/cli/internal/hashing/package_deps_hash.go?rgh-link-date=2022-11-27T19%3A16%3A38Z#L331) should return error + stderr

```go
func getTraversePath(rootPath turbopath.AbsoluteSystemPath) (turbopath.RelativeUnixPath, error) {
	cmd := exec.Command("git", "rev-parse", "--show-cdup")
	cmd.Dir = rootPath.ToString()

	traversePath, err := cmd.Output()
	if err != nil {
		return "", err
	}
```

> low priority: has workaround

workaround

```
(
  cd /build/source
  git init
)
HOME=/tmp
```

### Expected Behavior

pass test

### To Reproduce

nix-build . -A turbo

**Comment by anthonyshew** [comment]
It looks like this specific issue is in the Go code. We're completing our migration to Rust currently so will close this as this code will be deprecated soon.
