### ISSUE TITLE
[turborepo] `turbo prune` is not including `.npmrc` when using `pnpm`

### ISSUE THREAD

**Issue by Kuirak** [vercel/turbo#2871]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When running `turbo prune --scope="<app-name>" --docker` and using a `.npmrc` file to configure `pnpm install` to use settings like `enable-pre-post-scripts=true` or `shamefully-hoist=true` the `.npmrc` file is missing in the `out` directory

### Expected Behavior

If exists a `.npmrc` should be copied to `out`

### To Reproduce

1. Use `pnpm` as package manager 
2. Create an `.npmrc` file with some config. e.g:
```sh
enable-pre-post-scripts=true
shamefully-hoist=true
```
3. Run `turbo prune --scope="<app-name>" --docker`
4. Inspect `out` folder, no `.npmrc` exists

**Comment by thomson2k** [comment]
@Kuirak 
It looks like yoo not properly copying the .npmrc file to the out directory. This can happen if the .npmrc file is not located in the root of your project directory. By default, the turbo prune command only copies files and directories located in the root of the project, so if your .npmrc file is located elsewhere, it will not be copied.

To fix this issue, you can either move your .npmrc file to the root of your project directory, or you can use the --include option to specify the path to the .npmrc file that you want to include in the out directory. For example:

`turbo prune --scope="<app-name>" --docker --include="path/to/.npmrc"`

This will ensure that the .npmrc file is included in the out directory when running the turbo prune command. Note that you may need to adjust the path to the .npmrc file depending on where it is located in your project.

**Comment by Kuirak** [comment]
@thomson2k 
I think the `turbo prune --docker` command should copy the `.npmrc` of the project by default, because some `pnpm` settings like [`shamefully-hoist`](https://pnpm.io/npmrc#shamefully-hoist) change how dependencies  are installed and this is why I think this should be part of the `prune` command and not a manual step.

> To fix this issue, you can either move your .npmrc file to the root of your project directory,

Actually the `.npmrc` is at the projects root.

**Comment by chris-olszewski** [comment]
Hi @Kuirak, we're open to a PR from the community to add copying this file for npm and pnpm. At the moment, I don't think it'll be a high priority for the team considering how straight forward the workaround is.

**Comment by Kuirak** [comment]
Hi @chris-olszewski with workaround do you mean the one @thomson2k posted? 
I cannot find the `--include` in the docs and the CLI fails with it.

Since the `.npmrc` can alter how`pnpm` works I think it is a pretty important part to 100% support `pnpm`.

I am no `go` developer but I can try doing a PR. Can you point out where I can start?
