### ISSUE TITLE
Execution of Build order in development mode

### ISSUE THREAD

**Issue by devGitAbhishek** [vercel/turbo#2891]
### What version of Turborepo are you using?

1.5.6

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

- Consider the following repo setup:

**apps**
    UI [ depends on packages A,B,C,D,E ] _(This has been made with create react app)_
**packages** _(all packages have webpack config file)_
     A [ depends on E ]
     B [ depends on E ]
     C [ depends on E ]
     D [ depends on E & F ]
     E
     F

- Actual run order in development mode: yarn dev ( turbo run dev --continue )

1. package E
2. package F
3. package A,B,C,D

- For the turbo.json file we have included the following things in pipeline: 

 "dev": {
      "outputs": [".dist/**"]
    } 
In the above if we include depends on ["^dev"], then only package build is done which is E and after that it stops, there is no other script that gets executed.

- Note: 

1. yarn dev executes all dev jobs for app and packages.
2. For app: dev: **_react-scripts start_**
3. For all packages: **_webpack --watch_**

### Expected Behavior

- Required run order for dev:

package E
package F
package A,B,C,D
app UI

- When we execute production build where following is included in pipeline it work fine.
  "build": {
      "dependsOn": ["^build"],
      "outputs": [".dist/**"],
      "cache": true
    }

### To Reproduce

1. Make setup of turborepo, with all packages having webpack and babel setup.
2. Under apps have a app of CRA.
3. In package.json of app and packages define a dev command under script which actually does job of starting up app and building packages.
4. Run yarn dev from root of project

**Comment by milovangudelj** [comment]
As the docs state you can't have task `A` depend on a long running task `B` such as a dev script executed in watch mode (e.g. with `--watch` flag). That's because task `A` will wait until task `B`, on which it depends, has finished and since dev tasks don't exit `A` will never run.

> Label a task as `persistent` if it is a long-running process, such as a dev server or `--watch` mode. Turbo will prevent other tasks from depending on persistent tasks. Without setting this config, if any other task depends on `dev`, it will never run, because `dev` never exits. With this option, `turbo` can warn you about an invalid configuration.

So this is not a bug but rather a missing feature. Btw, a watch mode is being considered as you can read in this issue (#986). See the last couple of comments made in Nov by Nathan Hammond.

**Comment by devGitAbhishek** [comment]
> As the docs state you can't have task `A` depend on a long running task `B` such as a dev script executed in watch mode (e.g. with `--watch` flag). That's because task `A` will wait until task `B`, on which it depends, has finished and since dev tasks don't exit `A` will never run.
> 
> > Label a task as `persistent` if it is a long-running process, such as a dev server or `--watch` mode. Turbo will prevent other tasks from depending on persistent tasks. Without setting this config, if any other task depends on `dev`, it will never run, because `dev` never exits. With this option, `turbo` can warn you about an invalid configuration.
> 
> So this is not a bug but rather a missing feature. Btw, a watch mode is being considered as you can read in this issue (#986). See the last couple of comments made in Nov by Nathan Hammond.

thanks
