### ISSUE TITLE
[turbopack] middleware is ignored in Next.js

### ISSUE THREAD

**Issue by useafterfree** [vercel/turbo#2905]
### What version of Turbopack are you using?

alpha

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

middleware.ts and middleware.js in the root of the project are not ran

### Expected Behavior

Middleware should be executed on api routes.

## create turbopack app
`npx create-next-app --example with-turbopack`
## create a middleware file (middleware.js) with the following contents:
```
console.log({ middleWare: true})

import { NextResponse } from "next/server";

export default (req) => {
  return NextResponse.next();
};

// Stop Middleware running on static files
export const config = { matcher: '/((?!.*\\.).*)' }
```
## start next
`npm run dev`
## observe turbopack does not load the file
`{ middleWare: true }` does not exist in the output
## observe omitting turbopack loads the file
`npx next dev`
`{ middleWare: true }` exists in the output

**Comment by zigang93** [comment]
is this related to turborepo? you should open issue at nextjs

**Comment by useafterfree** [comment]
Closing since it duplicates: https://github.com/vercel/next.js/issues/42921
