### ISSUE TITLE
Syntax for using output as input

### ISSUE THREAD

**Issue by Andarist** [vercel/turbo#2907]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

When creating pipelines it's easy to think in terms of inputs and outputs - very often they **relate** to each other, and one task's output becomes another task's input.

There is no syntax to specify this - we can list the same file patterns in both scripts at appropriate positions but it's:
- manual
- error-prone
- doesn't convey the intention

### Describe the solution you'd like

It would be lovely to have some special syntax for `inputs`, to automatically use outputs of another task as an input.

### Describe alternatives you've considered

The alternative is to carefully manage inputs/outputs when making changes.

We can also solely rely on `dependsOn` and if only this `dependsOn: ['build'], inputs: []` would mean that this dependant script could not be executed then it would be OK-ish. But this actually means that a task should be re-run on any change in the particular directory. I could try to use `dependsOn: ['build'], inputs: ['this_wont_match_anything']` but that is quite hacky.

**Comment by nathanhammond** [comment]
In _most_ cases we're hoping that you don't have to get super-clever with `inputs` and `outputs`. If you're having to do that I'd _love_ to see a concrete example of your use case to see if there's a way to accomplish your goals in our current intentionally-limited DSL that isn't super painful. (Can ping me privately on Twitter or https://turbo.build/discord if sharing in public isn't viable.)

In general, our "conceptually pure but of course doesn't survive contact with the real world" approach is:
- `inputs` are intended for scoping down the files in-package in terms of hash inclusion. They can be _abused_ to support impure monorepos and traverse out of a package.
- `outputs` in an _ideal_ world would only ever be a single directory, and it _wouldn't exist_ prior to running the task.

If those two invariants are met we can avoid doing a _ton_ of work on your behalf.

**Comment by nathanhammond** [comment]
(Also, we're really trying to avoid addition of additional microsyntax so the final shape of any solution to the problem you're trying to solve for might look a lot different than this proposal.)

**Comment by Andarist** [comment]
Basically, I'd like for `test` to depend on `build`'s output while ignoring any other changes in that package. Changes to `src/**`, `package.json` etc should only affect `build`, that in turn should rerun `test`. I can share the same inputs here and depend on the `build` but that isn't exactly what I want - those overlap when you think about what `build` is doing etc but at the conceptual level I only care about `build`'s output (and `test`'s own input: `test/**`). Cache invalidation for `build` is its job, not `test`'s. Note that I want to keep `test` in the same package as `build`.

> (Also, we're really trying to avoid addition of additional microsyntax so the final shape of any solution to the problem you're trying to solve for might look a lot different than this proposal.)

Not a problem, I respect that you might not want to extend the existing DSL too much here - each new syntax has its cost. 

Note though that how you described `inputs` is exactly what I'd want here: I want to include some output as part of the hash. That's why this particular proposal made sense to me (over, let's say, including a new config key or stuff like that)

I also share the same understanding of `outputs`. It's just that, ideally, those generated outputs could be directly used as inputs.

**Comment by Andarist** [comment]
I think that your detailed (❤️) answer satisfies all of my use cases right now!

> This makes it possible to do things like: turbo run build --dry=json | jq .[].packageName.cacheState at the beginning of your CI run and—if it comes back as a hit—you could maybe skip installing something like graphviz in CI.

This is neat! Thanks for the tip. A tip like this could get included somewhere in the docs 😃
