### ISSUE TITLE
[turbopack] Undefined on extending React.Component

### ISSUE THREAD

**Issue by hydroper** [vercel/turbo#2926]
### What version of Turbopack are you using?

React version: 18.2.0, Next: 13.0.6

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

`React.Component` is undefined in the `extends` clause.

### Expected Behavior

No runtime error:

> TypeError: Class extends value undefined is not a constructor or null
>  - at  (/app/GameContainer.tsx:5:18)
>  - at Module.[project-with-next]/app/GameContainer.tsx (ecmascript, rsc) (.next\server\app\chunks\rsc\app_layout.tsx.js:165:3)
>  - at  (.next\server\app\chunks\ssr\_6c0b57.js:67894:21)
>  - ...

### To Reproduce

Scaffold a new Turbopack app with NextJS and cleanup the project. Run `npm run dev` and access the web page.

### Reproduction Repo

https://github.com/matheusdiasdesouzads/phantasystar3turbopack

**Comment by raulsanchez1024** [comment]
I saw something similar and I removed all the `node_modules` using `npx npkill` and ran the following

`$ pnpm i`

`$ pnpm build`

`$ pnpm dev`

**Comment by hongdeyuan** [comment]
I also have the same problem...

resolve：
`'use client';`  work for me;
