### ISSUE TITLE
[turborepo] can't force a single workspace to run task that has dependsOn

### ISSUE THREAD

**Issue by scamden** [vercel/turbo#2939]
### What version of Turborepo are you using?

1.6.2

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

if i have a task `compile` specified as 
```
    "compile": {
      "dependsOn": ["^compile"],
      "outputs": ["build/**"]
    },
```

i can't exclude the dependencies of the task no matter what i try. 

my best attempt was 
`turbo compile --filter="\!app^..." --filter="app" --force`

### Expected Behavior

explicitly excluding deps should override the behavior of dependsOn and not run the task for dependencies

### To Reproduce

make a monorepo with workspace `app` which depends on workspace `anyother` and with task `compile` specified as 
```
    "compile": {
      "dependsOn": ["^compile"],
      "outputs": ["build/**"]
    },
```
run
`turbo compile --filter="\!app^..." --filter="app" --force`

cc: @spikebrehm @adamrneary

**Comment by tknickman** [comment]
@scamden `--only` is designed to do what you're looking for here (ignore `dependsOn`). Checkout the [docs](https://turbo.build/repo/docs/reference/command-line-reference#--only) here.

**Comment by scamden** [comment]
@tknickman thanks for the reply. unfortunately this doesn't seem to work for tasks dependent on the same task. running: `turbo run --only compile --filter app` still runs dependent compiles for me on turbo v1.6.3

And actually I don't think I want to ignore dependsOn entirely. For example, if i have a build task that has `dependsOn : ['^compile', 'lint']` i would want a way to run all the tasks within the workspace but not the dependents. so still run build and lint, but not upstream compile if that makes sense. I think we need something like --only-filtered-workspaces so it runs everything in the dependsOn but only for the workspaces we've filtered to if that makes sense.

**Comment by gajus** [comment]
@tknickman Is there a workaround for this?

**Comment by chris-olszewski** [comment]
@gajus @spikebrehm @scamden 

Hi all, could you help me understand the reasoning for wanting to run a single task in a single package and ignore all dependencies? We could add an additional flag just for this behavior, but we want to make sure we are understanding the problem you're encountering/what you're trying to achieve before we add another flag.

**Comment by anthonyshew** [comment]
The behavior of `--only` has changed to include what's being requested in this issue per https://github.com/vercel/turbo/pull/8163.
