### ISSUE TITLE
Extended task graph creation

### ISSUE THREAD

**Issue by DerYeger** [vercel/turbo#2943]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

The generated task graphs can become quite hard to read, once enough packages and tasks are defined.
As a workaround, I created [@yeger/turbo-graph](https://github.com/DerYeger/yeger/tree/main/packages/turbo-graph), which provides an interactive visualization for Turborepo task graphs.

However, its implementation is rather hacky, because Turborepo can currently only output the graphs in JSON format as files.
I suggest extending the CLI, or maybe even adding a programmatic JS API, for creating task graphs in all supported formats without the need for files.

Further, it would be nice to include all tasks by passing a flag, instead of including them in the command.

### Describe the solution you'd like

Programmatic API (or extended CLI) for creating task graphs in all supported formats without the need for intermediate files.

Add a flag/option to create graphs containing all tasks without specifying them.

E.g. `turbo --graph --graph-format=json --full-graph` or

```js
import { createGraph } from 'turbo/graph'

const myGraph = createGraph({
  format: 'json',
  tasks: 'all', // 'all' or string[] with task names
})
```

### Describe alternatives you've considered

Currently, I'm parsing the dot graph output manually.
While I don't need most features of the JSON format (as I'm using my own d3-based graph library), the `pos` field of graph nodes would be of great use for laying out the graphs.

For detecting available tasks, I'm parsing the `turbo.json` file's pipeline.

**Comment by tknickman** [comment]
Hey @DerYeger, awesome project - we were playing around with it yesterday. Have you have tried using `--dry=json`? This should give you all the information you need to construct the graph, and will output to stdout in json format (skipping the file write)

**Comment by DerYeger** [comment]
Thank you!

`--dry=json` looks great and contains even more data for me to display.
I'll give it a try and close this issue if it works out (which I strongly assume it will).

**Comment by DerYeger** [comment]
I gave it a try and ended up with way too busy graphs, because `--dry=json` includes transitive dependencies as well.

Once I find the time, I'll evaluate whether filtering transitive dependencies is any cleaner or simpler at all at the current parsing approach.

But in any case, the additional information is great, and I'm looking forward to displaying it as well.

**Comment by DerYeger** [comment]
v1.0.0 of `@yeger/turbo-graph` now uses the `--dry=json` command to construct it's model!
