### ISSUE TITLE
[turborepo] Cannot install on Alpine Linux

### ISSUE THREAD

**Issue by natesilva** [vercel/turbo#2959]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

`turbo` fails to install on Alpine Linux -- the version of Linux that is commonly used in Docker images.

When installing using `npm install turbo --save-dev` as described on the [getting started page](https://turbo.build/repo/docs/getting-started/add-to-project), or when installing using `npm install -g turbo`, the error is:

 `Error: spawnSync /root/node_modules/turbo/bin/turbo ENOENT`.

As a workaround I was able to install using `npm i -g turbo-linux-arm64` (on my Mac using Docker) or `npm i -g turbo-linux-64` (on my CI system). I don’t want to hardcode a particular platform, though.

Another workaround is to use a different Linux distro. But `turbo` should work on Alpine since it’s one of the most common Linux distros for Docker.

### Expected Behavior

You should be able to install `turbo` on Alpine Linux without specifying the platform name.

### To Reproduce

```shell
docker run --rm -it node:18-alpine /bin/sh

/ # npm i -g turbo

npm notice 
npm notice New major version of npm available! 8.19.2 -> 9.2.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.2.0
npm notice Run npm install -g npm@9.2.0 to update!
npm notice 
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/turbo
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! node:internal/errors:484
npm ERR!     ErrorCaptureStackTrace(err);
npm ERR!     ^
npm ERR! 
npm ERR! <ref *1> Error: spawnSync /usr/local/lib/node_modules/turbo/bin/turbo ENOENT
npm ERR!     at Object.spawnSync (node:internal/child_process:1110:20)
npm ERR!     at spawnSync (node:child_process:857:24)
npm ERR!     at Object.execFileSync (node:child_process:900:15)
npm ERR!     at validateBinaryVersion (/usr/local/lib/node_modules/turbo/install.js:25:6)
npm ERR!     at /usr/local/lib/node_modules/turbo/install.js:308:5 {
npm ERR!   errno: -2,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'spawnSync /usr/local/lib/node_modules/turbo/bin/turbo',
npm ERR!   path: '/usr/local/lib/node_modules/turbo/bin/turbo',
npm ERR!   spawnargs: [ '--version' ],
npm ERR!   error: [Circular *1],
npm ERR!   status: null,
npm ERR!   signal: null,
npm ERR!   output: null,
npm ERR!   pid: 37,
npm ERR!   stdout: null,
npm ERR!   stderr: null
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.12.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-08T17_39_09_754Z-debug-0.log
```

**Comment by natesilva** [comment]
I found the workaround to this which was to `apk add --no-cache libc6-compat` before trying to install `turbo`.

**Comment by iiian** [comment]
@natesilva this worked for me as well.

**Comment by fran-cadenas-fu** [comment]
This workaround it's not working for me. Im currently working on Google Cloud Build and the problem persists with the same error as @natesilva described.

**Comment by iiian** [comment]
> This workaround it's not working for me. Im currently working on Google Cloud Build and the problem persists with the same error as @natesilva described.

`apk add build-base libc6-compat gcompat` help at all?

**Comment by fran-cadenas-fu** [comment]
> > This workaround it's not working for me. Im currently working on Google Cloud Build and the problem persists with the same error as @natesilva described.
> 
> `apk add build-base libc6-compat gcompat` help at all?

Yes tried and got the same error:
```
npm ERR! code 1
npm ERR! path /workspace/node_modules/turbo
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! node:internal/errors:478
npm ERR!     ErrorCaptureStackTrace(err);
npm ERR!     ^
npm ERR! 
npm ERR! <ref *1> Error: spawnSync /workspace/node_modules/turbo/bin/turbo ENOENT
npm ERR!     at Object.spawnSync (node:internal/child_process:1119:20)
npm ERR!     at spawnSync (node:child_process:847:24)
npm ERR!     at Object.execFileSync (node:child_process:890:15)
npm ERR!     at validateBinaryVersion (/workspace/node_modules/turbo/install.js:25:6)
npm ERR!     at /workspace/node_modules/turbo/install.js:308:5 {
npm ERR!   errno: -2,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'spawnSync /workspace/node_modules/turbo/bin/turbo',
npm ERR!   path: '/workspace/node_modules/turbo/bin/turbo',
npm ERR!   spawnargs: [ '--version' ],
npm ERR!   error: [Circular *1],
npm ERR!   status: null,
npm ERR!   signal: null,
npm ERR!   output: null,
npm ERR!   pid: 87,
npm ERR!   stdout: null,
npm ERR!   stderr: null
npm ERR! }
```

**Comment by iiian** [comment]
So, currently the working approach is:

```
docker run --rm -it node:18-alpine /bin/sh
/# apk add --no-cache libc6-compat
/# npm i -g turbo
🏆 
```

However, I see in your output that your path is `/workspace/node_modules/turbo`, so there's a `WORKDIR /workspace` in there somewhere, and is there possibly more?

1. Have you tried to confirm precisely that the above works, as a bare-minimum confirmation of functionality?
2. If so, perhaps a docker image cache clear could help, `docker rmi node:18-alpine`? My node:18-alpine is `sha:a136ed7b0`.
3. If not, perhaps you can share a minimal copy of your `Dockerfile` that isn't passing?

Sorry, this might be stuff you've already considered, just trying to help rubber-duck this thing.

**Comment by fran-cadenas-fu** [comment]
@iiian I'm currently working with Google Cloud Build and buildpacks. My build file is the following:

```
steps:
  - id: "Prepare OS I"
    name: node:18-alpine
    entrypoint: apk
    args: ["update"]
  - id: "Prepare OS II"
    name: node:18-alpine
    entrypoint: apk
    args: ["add", "--no-cache", "git", "build-base", "libc6-compat", "gcompat"]
  - id: "Install turbo"
    name: node:18-alpine
    entrypoint: npm
    args: ["install", "-g", "turbo"]
  - id: "Install dependencies"
    name: node:18-alpine
    entrypoint: npm
    args: ["install"]
```

**Comment by iiian** [comment]
Ah, okay, I'm unfamiliar with GCB. So does this mean your `/workspace/node_modules` directory is supposed to be your global npm install dir in GCB? Is it possible to `npm root -g` instead of `npm install -g turbo`?

**Comment by iiian** [comment]
Is it possible to switch to `yarn`? https://cloud.google.com/build/docs/building/build-nodejs

> Cloud Build enables you to use any publicly available container image to execute your tasks. The public [node image from Docker Hub](https://hub.docker.com/_/node/) comes preinstalled with npm and **yarn** tools. You can configure Cloud Build to build your Node.js project with these tools.

`yarn add global turbo` might give different results

**Comment by fran-cadenas-fu** [comment]
Thanks @iiian, switching to yarn it's not an option in my case...

It's just as you said then, I'm getting a `/usr/local/lib/node_modules` as the `root -g` output. But the error is pointing to that location:
```
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/turbo
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! node:internal/errors:484
npm ERR!     ErrorCaptureStackTrace(err);
npm ERR!     ^
npm ERR! 
npm ERR! <ref *1> Error: spawnSync /usr/local/lib/node_modules/turbo/bin/turbo ENOENT
npm ERR!     at Object.spawnSync (node:internal/child_process:1110:20)
npm ERR!     at spawnSync (node:child_process:857:24)
npm ERR!     at Object.execFileSync (node:child_process:900:15)
npm ERR!     at validateBinaryVersion (/usr/local/lib/node_modules/turbo/install.js:25:6)
npm ERR!     at /usr/local/lib/node_modules/turbo/install.js:308:5 {
npm ERR!   errno: -2,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'spawnSync /usr/local/lib/node_modules/turbo/bin/turbo',
npm ERR!   path: '/usr/local/lib/node_modules/turbo/bin/turbo',
npm ERR!   spawnargs: [ '--version' ],
npm ERR!   error: [Circular *1],
npm ERR!   status: null,
npm ERR!   signal: null,
npm ERR!   output: null,
npm ERR!   pid: 24,
npm ERR!   stdout: null,
npm ERR!   stderr: null
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.12.1
```

**Comment by iiian** [comment]
@fran-cadenas-fu 

Okay then we might be zeroing in. In https://github.com/vercel/turbo/issues/2959#issuecomment-1366481250 you mentioned that `npm i -g` was trying to add `turbo` to `/workspace/node_modules`. Can you explain the discrepancy that we are seeing now, that could be a part of it. 

Are you able to `npm i -g` anything else? If not, it may not be a `turbo` issue. If you can, I'd just create another ticket similar to this one, and reference it for context.

**Comment by fran-cadenas-fu** [comment]
> @fran-cadenas-fu
> 
> Okay then we might be zeroing in. In [#2959 (comment)](https://github.com/vercel/turbo/issues/2959#issuecomment-1366481250) you mentioned that `npm i -g` was trying to add `turbo` to `/workspace/node_modules`. Can you explain the discrepancy that we are seeing now, that could be a part of it.
> 
> Are you able to `npm i -g` anything else? If not, it may not be a `turbo` issue. If you can, I'd just create another ticket similar to this one, and reference it for context.

The error shown in the previous message is the one that is given by `npm install -g turbo`. The original `/workspace` directory is probably an error from another try. The one that matches the last try is pointing `/usr/local/lib/node_modules/`
