### ISSUE TITLE
[turborepo] npx create-turbo@latest installation error - fs.cpSync is not a function

### ISSUE THREAD

**Issue by 5hee75** [vercel/turbo#2972]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm - error occurs with any package manager

### What operating system are you using?

Mac

### Describe the Bug

Encounter an installation error using the `npx create-turbo@latest` script after selecting the package manager.  Error states that `fs.cpSync` is not a function.
```
╰─$ npx create-turbo@latest
npx: installed 182 in 16.442s

>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.

? Where would you like to create your turborepo? test-turbo-t3
? Which package manager do you want to use? pnpm

Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: import_fs.default.cpSync is not a function
    at run (/Users/jsheets/.npm/_npx/23061/lib/node_modules/create-turbo/dist/index.js:328:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Expected Behavior

Script should bootstrap a new turborepo repository with the desired package manager.

### To Reproduce

Execute `npx create-turbo@latest` and follow prompts.  Error occurs after selecting package manager.

**Comment by chris-olszewski** [comment]
This looks like https://github.com/vercel/turbo/issues/2305, which was addressed in https://github.com/vercel/turbo/pull/2638. Can you give the result of `node --version` and `npx create-turbo@latest --version`

**Comment by tknickman** [comment]
This hasn't been published in latest yet, but it should be available on `create-turbo@canary`
