### ISSUE TITLE
[turborepo] can't specify a cache input to another workspace package

### ISSUE THREAD

**Issue by scamden** [vercel/turbo#2999]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

if I try this for a path into another dep it doesn't bust cache for changes to `eslint-preset.js`
```
  "lint": {
      "outputs": [],
      "inputs": ["**/*", "../rig/eslint-preset.js"]
    },
 ```

where rig is one of the workspaces and is included as a dep everywhere via `"rig": "workspace:*",`

fwiw i also tried "node_modules/@watershed/rig/eslint-preset.js" which i would prefer.
    
(sidenote but turbo also doesn't throw any kind of error if I specify a totally non-existent file there)

### Expected Behavior

i would have expected the cache to bust automatically because a dependency source controlled file changed, but barring that i would expect this explicit path to bust as it does in https://github.com/vercel/turbo/issues/1913

### To Reproduce

bug description shows the setup

cc: @spikebrehm @adamrneary

**Comment by Sergei8888** [comment]
The same for me

**Comment by evsasse** [comment]
Seeing the same problem on 1.8.8 + pnpm

**Comment by anthonyshew** [comment]
The cache is actually being missed for a different reason: Setting `inputs` opts you out of Turborepo's default input behavior. This means that you're including, for instance, gitignored files into your hash. The out-of-package globs being referenced are likely working correctly.

Worthy of note: We've added a microsyntax to help you include the defaults in Turborepo 1.12. Check out `$TURBO_DEFAULT$`! here: https://turbo.build/blog/turbo-1-12-0#improved-inputs-ergonomics

**Comment by psychobolt** [comment]
@anthonyshew Not working for me in v2. Did something change? 

Simply run `git diff HEAD~1`, `yarn turbo run build --filter="[HEAD~1]"`. Ref: [Sandbox](https://codesandbox.io/p/devbox/test-turbo-inputs-lwndsy)

**Comment by psychobolt** [comment]
Doesn't still seem to work for root level workspaces. See issue: https://github.com/vercel/turbo/issues/8762
