### ISSUE TITLE
Display whether cache hit is from local or remote

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turbo#302]
### Describe the feature you'd like to request

As a user, I want to know if my cache hit came from my local filesystem or from the remote cache.

### Describe the solution you'd like

Right now our cache abstraction for `fetch` returns a boolean for hit/miss. We should change that to an object or enum which adds source information. 

```go
type FetchResult struct {
  // Fetch was successful
  Status: bool,
  // Source: local, remote
  Source: string,
}
```

### Describe alternatives you've considered

Could alter the shape of the struct to simplify things.

**Comment by JoeyEamigh** [comment]
Additionally, it would be great to have an option in the pipeline that only allows certain things to be retrieved from the local cache. This would be beneficial in something like a `bootstrap` step that creates a symlink. This could be cached locally but not remotely.

**Comment by tknickman** [comment]
This is now done
