### ISSUE TITLE
[turborepo]  ERROR  run failed: error preparing engine: Missing task definition, configure "build" or "___ROOT___#build" in turbo.json

### ISSUE THREAD

**Issue by weyert** [vercel/turbo#3050]
### What version of Turborepo are you using?

1.7.0-canary.3

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

I tried to upgrade `turbo` from version `1.6.3` to `1.7.0-canary.3` and since the upgrade it's throwing the following error:

```bash
Running local turbo binary in /Users/weyert/Development/Projects/experiment/node_modules/turbo/bin/turbo

 ERROR  run failed: error preparing engine: Missing task definition, configure "build" or "___ROOT___#build" in turbo.json
```

while with `1.6.3` it runs as expected:

```bash
 Tasks:    1 successful, 2 total
Cached:    0 cached, 2 total
  Time:    12.478s 
```

### Expected Behavior

I would expect that the command `turbo run build` would succeed running

### To Reproduce

Not available yet

**Comment by weyert** [comment]
@nathanhammond#7947 looks like it happens when I have this in the root's `package.json`:
```
  "workspaces": {
    "packages": [
      "packages/*",
      "projects/*",
      "examples/*"
    ]
  },
```


In 1.6.3 it gives an error, which I missed, but in 1.7.0 it acts weird:
1.6.3:
```
 WARNING  Issues occurred when constructing package graph. Turbo will function, but some features may not be available:  1 error occurred:
        * json: cannot unmarshal object into Go struct field NpmPackage.packages.workspaces of type []string
```

in 1.7.0:
```
 ERROR  run failed: error preparing engine: Missing task definition, configure "build" or "___ROOT___#build" in turbo.json
```

everything starts work when I change the above to:
```
  "workspaces": [
      "packages/*",
      "projects/*",
      "examples/*"
  ],
```

**Comment by tknickman** [comment]
@weyert parsing error should be fixed in the latest canary and will go out with our next release

**Comment by weyert** [comment]
Great thank you!

**Comment by tanzeelrana** [comment]
![Screenshot 2023-07-05 at 08 36 22](https://github.com/vercel/turbo/assets/2520028/2686e33c-7e6b-4047-beb6-0481e3b8e668)

in my case i had the `package-lock.json` file generated due to a bad command i ran earlier. when i removed the lock file and ran turbo command, it worked :)

**Comment by tinytelly** [comment]
for me it was doing this:

1. remove the package-lock.json
2. remove the yarn.lock
3. npm install (puts back a package-lock.json)
4. turbo build
5. works now :-)

**Comment by mathix420** [comment]
I had similar issues because I forgot to change the `packageManager` field in `package.json` after switching from bunjs to pnpm. Everything was working fine locally but kept crashing on Github CI with this error:

```
. postinstall: ::endgroup::
. postinstall:   x internal errors encountered: unable to find package manager binary: cannot
. postinstall:   | find binary path
. postinstall: Failed
```

Hoping this can help others!
