### ISSUE TITLE
[turbo-malloc] In alloc_zeroed, add the allocated size to the counter only if the memory allocation succeeded

### ISSUE THREAD

**Issue by Boscop** [vercel/turbo#3070]
### What version of Turbopack are you using?

0.1.0

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Linux

### Describe the Bug

I was just reading through the code on github and noticed in `turbo-malloc` that the condition here should be negated, i.e. `if !ret.is_null() {` (like it does for `alloc` and `realloc`), so that it will add the allocated size to the counter only if the memory allocation succeeded:

https://github.com/vercel/turbo/blob/131c370a8cd65ffabdacfbac92b8f4b1249dc77a/crates/turbo-malloc/src/lib.rs#L39-L45

Also in the other impl below that:

https://github.com/vercel/turbo/blob/131c370a8cd65ffabdacfbac92b8f4b1249dc77a/crates/turbo-malloc/src/lib.rs#L79-L85

### Expected Behavior

-

### To Reproduce

-

<sub>[PACK-2502](https://linear.app/vercel/issue/PACK-2502/[turbo-malloc]-in-alloc-zeroed-add-the-allocated-size-to-the-counter)</sub>

**Comment by sokra** [comment]
Good find. Do you want to send a PR?

**Comment by arlyon** [comment]
Hey, looks like this issue has been addressed. Closing! :)
