### ISSUE TITLE
[turborepo] examples/with-svelte does not call `svelte-kit sync` and caches build without .svelte-kit/tsconfig.json

### ISSUE THREAD

**Issue by iva2k** [vercel/turbo#3085]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

Following instructions for examples/with-svelte, and getting to `pnpm run build`. 
Log message shows: does not call `svelte-kit sync` and caches build without .svelte-kit/tsconfig.json

```text
docs:build: > docs@0.0.0 build C:\dev\turborepo\with-svelte\apps\docs
docs:build: > vite build
docs:build: 
docs:build: ▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]
docs:build: 
docs:build:     tsconfig.json:2:13:
docs:build:       2 │   "extends": "./.svelte-kit/tsconfig.json",
docs:build:         ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
docs:build: 
docs:build: 
docs:build: vite v4.0.0 building for production...

...
web:build: > web@0.0.0 build C:\dev\turborepo\with-svelte\apps\web
web:build: > vite build
web:build: 
web:build: ▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]
web:build: 
web:build:     tsconfig.json:2:13:
web:build:       2 │   "extends": "./.svelte-kit/tsconfig.json",
web:build:         ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
web:build: 
web:build: 
web:build: vite v4.0.0 building for production...
...
```

### Expected Behavior

Turbo build script should invoke `svelte-kit sync` to let the framework create its ./.svelte-kit/* files, and `pnpm run build` should not complain about missing ./.svelte-kit/* files.

### To Reproduce

```bash
npx degit vercel/turbo/examples/with-svelte with-svelte
cd with-svelte
pnpm install
pnpm run build
```

**Comment by anthonyshew** [comment]
Been awhile since this issue was opened and we've made lots of updates to our examples! If you're still seeing this problem, please do open up a fresh issue!

**Comment by iva2k** [comment]
Thanks for the awesome package and resolving this issue!

I ran the test with one version back v1.12.1  (which BTW the example installs) - the issue was not yet fixed. 

I manually updated to the current v1.12.2 and the issue has been fixed. Great!

For the record - this issue does not seem to be with the `with-svelte` example, but with the `turbo` package. Nothing in the example was wrong or can be done to fix this error, and there are no git commits into `with-svelte` between v1.12.1 and v1.12.2.

To fully close this - @anthonyshew - A request to cleanup - please, bump `turbo` version spec to 1.12.2 in the example's `package.json`. Or do you want a PR (for such a tiny one-liner)? Then this error will be gone for good.

**Comment by pbk0** [comment]
This error is back while using turbo 2.4.2

**Comment by anthonyshew** [comment]
Would love a PR for this if someone could!
