### ISSUE TITLE
[turborepo] It's impossible to override broken remote cache. --force doesn't override it remotely

### ISSUE THREAD

**Issue by alexhanga** [vercel/turbo#3127]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

Sometimes Turbo pushes incomplete (invalid) files into remote cache, and all developers needs to execute build with force in order to fix this cache problems locally. It would be good to have ability to override remote cache in this scenario.

I don't have any steps to reproduce to receive broken cache, we are still investigating, but it's a problem that we cannot override broken builds.

In our build process we use `tsc` and turbo has "outputs" for emitted code. But sometimes turbo push incomplete files (like first 300 lines). We think that it can be related to fs watch limits, but it's hard to check.

### Expected Behavior

Running build with `--force` and/or `--override` (suggested flag) should push new cache into remote and it should override it.

### To Reproduce

Make a script that will log current time, execute it with turbo, re-execute it with `--force`, remove local cache and execute once again without `--force`. Observe that you received previous cache.

**Comment by Myroslav-mint** [comment]
This is annoying problem especially when a team grows

**Comment by tknickman** [comment]
using [--force](https://turbo.build/repo/docs/reference/command-line-reference#--force) with [--remote-only](https://turbo.build/repo/docs/reference/command-line-reference#--remote-only) should do what you're looking for here.

**Comment by tknickman** [comment]
I'm very interested in this as well:

> In our build process we use tsc and turbo has "outputs" for emitted code. But sometimes turbo push incomplete files (like first 300 lines). We think that it can be related to fs watch limits, but it's hard to check.

We haven't had any reports of this, so I would be very curious to see what's going on here. if you could get a reproduction for this that would be awesome!

**Comment by anthonyshew** [comment]
Tom provided the right answer here so closing!
