### ISSUE TITLE
[turborepo] Deploying sveltekit to vercel

### ISSUE THREAD

**Issue by dheerajsarwaiya** [vercel/turbo#3131]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

1. I have created a monorepo with a sveltekit apps/webapp and another sveltekit common package in packages/ui. 
2. In turbo json I have following settings for output
` "outputs": ["dist/**", ".next/**", ".svelte-kit/**", ".vercel/**"]`

3. I am using adapter-auto and sveltejs/kit 
```
"@sveltejs/adapter-auto": "next",
"@sveltejs/kit": "next",
```
4. I set the output directory in vercel as ./svelte-kit
5. But when I am trying to deploy. Deploy is happening but getting  "This Serverless Function has crashed." error.
6. In the logs it says that it is unable to find @sveltejs/kit.. but both of my packages(apps/webapp and pacakges/ui) have this package. 
![Screenshot from 2022-12-22 23-56-26](https://user-images.githubusercontent.com/18539875/209298109-19582622-eb0e-47bf-8eb4-9efe0fb94eb0.png)

Not sure what is the issue. I tried to change the adapter to vercel as well .. same error

### Expected Behavior

no error

### To Reproduce

Create a monorepo with 2 sveltekit workspace
1. apps/web
2. pacakges/ui 

web calls packages/ui for UI components. Now try to deploy it on vercel.

**Comment by tknickman** [comment]
Hey @dheerajsarwaiya, check out the Vercel Sveltekit with Turborepo template! https://vercel.com/templates/svelte/turborepo-sveltekit-starter

**Comment by dheerajsarwaiya** [comment]
whats the problem? I did checkout the template. I compared svelte.config.js, package.json, and turbo.json. Everything is same. One difference is that it is using svelte in packages/ui vs I am using sveltekit there as well .. is that the problem? 

Do we always have to create monorepo from this or can we create something by our own and make the necessary changes?

thanks.

**Comment by csellis** [comment]
@dheerajsarwaiya did you ever solve this?
