### ISSUE TITLE
Explain why cache miss occurs when the hash is the same

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [vercel/turbo#3142]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Sometimes the Turborepo cache misses even though the printed hash is the same as a previous run. For example, in https://github.com/trpc/trpc/pull/3491:

* [First run](https://github.com/trpc/trpc/actions/runs/3783659335/jobs/6432382405): `@trpc/next:lint: cache miss, executing ce4fd5cd0fed4c45`
* [Second run](https://github.com/trpc/trpc/actions/runs/3783659335/jobs/6432436158): `@trpc/next:lint: cache miss, executing ce4fd5cd0fed4c45`

Even with [`-vvv`](https://turbo.build/repo/docs/reference/command-line-reference#-v--vv--vvv), there's not much logged. https://github.com/trpc/trpc/actions/runs/3785821470/jobs/6436171107

Something in the Turborepo setup is probably incorrect. But it's very hard to debug this without a message saying _why_ the cache missed.

### Describe the solution you'd like

For the case of the same reported hash, vaguely...

```plaintext
Caches matched on hash, but missed because of environment variable SOME_ENV_VAR_THASH.
```

```plaintext
Caches matched on hash, but missed because cache file path/to/file.log was (empty|missing).
```

### Describe alternatives you've considered

...I can't think of anything better than more logging, sorry. 😞

**Comment by juliusmarminge** [comment]
We also get a lot of cache misses on initial build even if they hit on the vercel deployment.

Probably a misconfigurarion but as Josh said hard to debug.

**Comment by anthonyshew** [comment]
We ended up finding out that this was due to bad environment variable secrets.

I'm not sure how helpful we can be in this specific circumstance - but perhaps it would have been nice for `-vvv` to have told us about the parameters for a cache hit that we were good on and the ones that we weren't.

**Comment by dbrxnds** [comment]
Hi @anthonyshew, do you mind sharing what you mean by "bad environment variable secrets"? What was going wrong? Currently running into this same exact issue, although only with remote cache.

**Comment by juliusmarminge** [comment]
> Hi @anthonyshew, do you mind sharing what you mean by "bad environment variable secrets"? What was going wrong? Currently running into this same exact issue, although only with remote cache.

We had our `TURBO_TEAM` token set to the teamId and not just the name (trpc)

**Comment by flex-jonghyen** [comment]
Because this issue is requesting feature about more reason about them, this issue is not solved.
`-vvv` does not explain enough about why cache is invalid or hash is changed.

**Comment by AdvancedCat** [comment]
I occured the same issue about cache missed while I didn't change any files. 
I hope `-vvv` can display more detail that why cache missed, files changed? or environment variable changed?

**Comment by templela** [comment]
Plus one for having a description of the input to the hash in verbose output
