### ISSUE TITLE
[turbopack] Invalid selector - Parsing CSS source code failed

### ISSUE THREAD

**Issue by mmailaender** [vercel/turbo#3145]
### What version of Turbopack are you using?

Next 13.1

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

Starting the dev server with Turbo fails.

![image](https://user-images.githubusercontent.com/87228994/209788766-541c4a57-ed54-4b86-82dc-da21b2901a49.png)

![image](https://user-images.githubusercontent.com/87228994/209788787-93f43a56-dd28-4532-892c-d40d9bcf7af5.png)

Running with Webpack works fine `next dev`

### Expected Behavior

Turbopack should be able to parse the CSS

### To Reproduce

Running `next dev --turbo` with Reshaped 1.9 installed

**Comment by kdy1** [comment]
Can you provide a repro or the actual CSS input?

**Comment by mmailaender** [comment]
Created a test repo: https://github.com/mmailaender/Turbopack 
[Direct link Gitpod](https://gitpod.io/#https://github.com/mmailaender/Turbopack)


But now I'm getting a different error if I'm using turbopack:

![image](https://user-images.githubusercontent.com/87228994/226712584-d3c55aa8-af6b-4698-8f74-e10c23cfffe6.png)
![image](https://user-images.githubusercontent.com/87228994/226712660-c94eab5e-14a8-4ec6-9ee4-18a6e3f9fab0.png)

**Comment by kdy1** [comment]
I think it's a different issue. Can you file another one?

**Comment by mmailaender** [comment]
@kdy1 created a new one: https://github.com/vercel/turbo/issues/4296
