### ISSUE TITLE
[turborepo] npm install doesn't install dependencies in workspaces

### ISSUE THREAD

**Issue by grug** [vercel/turbo#3146]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

When cloning a turbo repository that has packages with package.json files inside of them, I run `npm install` in the root of the repository and I would expect the dependencies within my packages to install. However, they do not.

### Expected Behavior

I would expect dependencies to install in my packages and for node_modules directories to appear in them [as per the docs](https://turbo.build/repo/docs/handbook/package-installation#installing-packages)

### To Reproduce

1. Create fresh turbo repo
2. Add a new workspace/package with its own dependencies to the repo
3. Run `npm install` in the root of the repository
4. Observe that dependencies do not install in the package

**Comment by grug** [comment]
I closed it off because I was being very silly! Complete user error 😂

**Comment by AlexandraKlein** [comment]
> I closed it off because I was being very silly! Complete user error 😂

What was your user error? If I `npm install` at the root of the monorepo, I don't get an install in the subdirectories.

**Comment by vicasas** [comment]
The same happens to me!. In `packages` I created a new directory called `apm` where I have some dependencies, moving to the root of the repository and running `npm install` does not create the `node_modules` folder, the same thing happens if this is done inside the `apm folder `.
