### ISSUE TITLE
[turborepo] postinstall on packages does not run when running yarn install

### ISSUE THREAD

**Issue by robertwt7** [vercel/turbo#3147]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

Running `yarn` on root does not run `postinstall` on each package / app

### Expected Behavior

it should run the `postinstall` 

### To Reproduce

run `yarn` on root or `yarn install`

**Comment by chris-olszewski** [comment]
Hi @robertwt7, I'm unsure where `turbo` is coming into play here as it sounds like a Yarn issue. Could you provide a reproduction or what command you're running with `turbo`?

**Comment by anthonyshew** [comment]
This is out of scope for Turborepo!
