### ISSUE TITLE
[turborepo] And turbopack problem with turbo.json and webpack HMR

### ISSUE THREAD

**Issue by 0xS4D** [vercel/turbo#3150]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

When I have the file "turbo.json" in my monorepo, the Next13 app with turbopack use webpack hmr when Im trying to use "turbopack hmr",  that make a collision and got this error:
![error](https://i.imgur.com/3NclY6W.png)

### Expected Behavior

Without turbo.json file:
![no-turbo](https://i.imgur.com/rnGbHq2.png)

With turbo.json file:
![turbo](https://i.imgur.com/FF9tjsH.png)

### To Reproduce

Create a monorepo with turborepo, create a nextjs13 app in "app" folder:
![step1](https://i.imgur.com/RPpIhmO.png)
change "next dev" to "next dev --turbo" in package.json of the app, run dev.
![step2](https://i.imgur.com/jV7Ivt3.png)

**Comment by anthonyshew** [comment]
This issue is rather old so I'm going to figure that this has been cleared up since then.
