### ISSUE TITLE
[turbopack]  Can't console.log in stdout when I use next with turbopack

### ISSUE THREAD

**Issue by amm834** [vercel/turbo#3155]
### What version of Turborepo are you using?

1.0.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Cannot console.log when i use next with turbopack

### Expected Behavior

It should work well like webpack

### To Reproduce

Cannot console.log and output is not showing in the stdout.
```tsx
import React from 'react';
import {readFile} from "fs/promises";

const getAllFiles = async () => {
    const file = await readFile('./app/hello.md')
    console.log(file) // this is not working 
    return file.toString()
}

const Home = async () => {
    const data = await getAllFiles()

    return (
        <div>
            Home page
            {data.toString()} <- working well
        </div>
    );
};

export default Home;
```

### Reproduction Repo

https://github.com/amm834/trubopack-no-stdout-issue-reproduce

**Comment by padmaia** [comment]
This one should be fixed in Next.js 13.2.0

**Comment by jvcjunior** [comment]
Not fixed yet

**Comment by ArpitaGanatra** [comment]
@padmaia is there a workaround for this? I still can't see console, or even a debugger

**Comment by ArpitaGanatra** [comment]
> Not fixed yet

can see the console in the terminal.
