### ISSUE TITLE
[WEB-962] Could not reach Cloud Firestore backend [turbopack] 

### ISSUE THREAD

**Issue by DerBasler** [vercel/turbo#3159]
### What version of Turbopack are you using?

"next": "13.1.1"

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

If I enable turbopack with next and firebase I get the following error:
@firebase/firestore: Firestore (9.15.0): Connection WebChannel transport errored
 @firebase/firestore: Firestore (9.15.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unavailable]: The operation could not be completed
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

This is not the case with webpack. 
The query is very simpel:
const mySnapshot = await getDocs(myRef);

### Expected Behavior

To request should reach firebase. 

### To Reproduce

npx create-next-app@latest
npm i firebase
(firebase backend setup)
make a query

<sub>[WEB-962](https://linear.app/vercel/issue/WEB-962/could-not-reach-cloud-firestore-backend-[turbopack])</sub>

<sub>[WEB-1140](https://linear.app/vercel/issue/WEB-1140/[web-962]-could-not-reach-cloud-firestore-backend-[turbopack])</sub>

**Comment by ForsakenHarmony** [comment]
If you're still running into this, please create a new issue with a reproduction link in the next.js repo if you're still running into this: https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&projects=&template=1.bug_report.yml
