### ISSUE TITLE
[turbopack] CSS Modules not applying styles in components imported into layout

### ISSUE THREAD

**Issue by ChaosCantrip** [vercel/turbo#3168]
### What version of Turbopack are you using?

1.6.3

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

Styles from CSS Modules are not being successfully applied to components imported into a `layout.js` file.
I am creating a CSS Module `./Header.module.css` and importing it into a component `./Header.js`, which is then imported into `./layout.js` and displayed in `<body>`.

When using turbopack, the styles do not apply unless `import styles from "./Header.module.css"` is also included in that specific `page.js`

The error occurs when any name of object, class or file is used, the above are just what I used in the reproduction

### Expected Behavior

The styles from `./Header.module.css` should be correctly applied to the objects with `className={styles.header_class}`, but they are not. An error also appears in the console, `[404] /_next/static/chunks/rsc/app_Header.module.css.map (4.75ms)`.

### To Reproduce

Create a project using Turbopack and the `/app` directory. All of the following files are then in `app/`

Create a CSS Module, `Header.module.css`, that includes some basic styles for testing.
```css
/* ./Header.module.css */

.header_class {
    background-color: red;
}
```

Create a jsx component, `<Header />` that imports and applies these styles.

```js
// ./Header.js

import styles from "./Header.module.css";

export default function Header() {
    return (
        <header className={styles.header_class}>
            <h1>This is the header</h1>
        </header>
    )
}
```

Create a layout and a page, and add the header to the top of the layout.

```js
// ./layout.js

import Header from "./Header";

export default function RootLayout({ children }) {
  return (
    <html>
      <head>
          <title>Bug Reproduction</title>
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
```

```js
// ./page.js

export default function HomePage() {
    return (
        <div>
            <p>This is the Home Page</p>
        </div>
    )
}
```

Run `next dev --turbo` and observe the red background does not apply to the header.
Run `next dev` and observe the red background appears

If you add `import styles from "./Header.module.css"` to the top of `page.js`, the header colour will apply correctly, even if `styles` is not then used in `page.js`

```js
// ./working/page.js

import styles from "../Header.module.css";

export default function WorkingPage() {
    return (
        <div>
            <p>This is the Working Page</p>
        </div>
    )
}
```

### Reproduction Repo

https://github.com/ChaosCantrip/nextjs-css-bug

**Comment by Nithin1506200** [comment]
Getting same issue here. Hence I'm not able to use this in production.

**Comment by padmaia** [comment]
Thanks for the reproduction, not seeing this issue with Next.js 13.2.4.
