### ISSUE TITLE
File names on Windows cannot contain colon character as it is a reserved character

### ISSUE THREAD

**Issue by AnderoKoplus** [vercel/turbo#317]
### What version of Turborepo are you using?

1.0.11

### Describe the Bug

ERROR @foo-bar/est:build:js:commonjs: :  open packages\client-lib.turbo\turbo-build:js:commonjs.log: The filename, directory name, or volume label syntax is incorrect.
running at     "turbo": "^1.0.11"

### Expected Behavior

turborepo uses OS specific/safe cache file name generation

### To Reproduce

use windows platform
add task which contains colons in its names like "do:something" (in my case the task was located under /packages/ folder)
it should generate a file name that is not allowed on the windows operating system

**Comment by rodrigoscna** [comment]
Any news on this?

**Comment by johnnyd710** [comment]
Still not working on turbo 1.7.0

**Comment by chris-olszewski** [comment]
This has been addressed in https://github.com/vercel/turbo/pull/6267 and https://github.com/vercel/turbo/pull/6293
