### ISSUE TITLE
[turborepo] Lint task fails to run after the build task with error "Could not find turbo.json." despite it being there

### ISSUE THREAD

**Issue by la55u** [vercel/turbo#3171]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Running the lint task with turbo fails with the following error message: 
```bash
test-monorepo:lint: 
test-monorepo:lint: > test-monorepo@1.0.0 lint /home/la/Projects/turbo-bug-demo/apps/test-frontend/.next/standalone
test-monorepo:lint: > turbo run lint
test-monorepo:lint: 
test-monorepo:lint:  ERROR  run failed: Could not find turbo.json. Follow directions at https://turbo.build/repo/docs to create one: file does not exist
test-monorepo:lint:  ELIFECYCLE  Command failed with exit code 1.
test-monorepo:lint: ERROR: command finished with error: command (/home/la/Projects/turbo-bug-demo/apps/test-frontend/.next/standalone) pnpm run lint exited (1)
shared-utils:lint:  ELIFECYCLE  Command failed.
chakra-theme:lint:  ELIFECYCLE  Command failed.

```

Note that from the error message it looks like it's trying to find the `turbo.json`file inside the `apps/test-frontend/.next/standalone` directory which is indeed not there but in the root of the monorepo. I have the `standalone` output mode enabled in the Next config because there is Docker involved in our build pipeline.

### Expected Behavior

The lint task should run fine because I have a valid `turbo.json` file in the monorepo root.

### To Reproduce

1. Clone the repoduction repo
2. Run `pnpm i -r` at the root
3. Run `pnpm lint` --> works fine
4. Run `pnpm build` --> works fine
5. Run `pnpm lint` again --> turbo exits with the error message mentioned above

### Reproduction Repo

https://github.com/la55u/turbo-bug-demo

**Comment by chris-olszewski** [comment]
So the issue seems to be that turbo is picking up the package defined in `apps/test-frontend/.next/standalone/package.json` that gets populated by `build`. The `package.json` is a copy of the root `package.json` so when it tries to run `lint` on this package it calls `turbo run lint` which fails due to the lack of a `turbo.json`.

I believe this `package.json` shouldn't be found since it's covered by `.gitignore`, I'll verify this and look for a fix. Thanks for the repro!

**Comment by chris-olszewski** [comment]
If you append `- '!**/.next/**'` to `pnpm-workspace.yaml` Turbo will stop picking up the copy in `.next/standalone` and `pnpm build && pnpm lint` will work without issue again.

**Comment by chris-olszewski** [comment]
For most projects it doesn't need to be, I'm unsure why next is copying the full `package.json` from your root. Usually the `.next/package.json` is minimal:
```
olszewski@chriss-mbp turborepo % bat docs/.next/package.json  
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: docs/.next/package.json
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ {"type": "commonjs"}
```

We do need to take into account of `.gitignore` when looking for workspace packages, but that will be tracked in #878
