### ISSUE TITLE
[turborepo] The `with-tailwind` example shows errors in VSCode: Cannot find module 'next/babel'

### ISSUE THREAD

**Issue by la55u** [vercel/turbo#3204]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Following the instructions in the `with-tailwind` example I noticed an error was being shown at some places in VSCode:

1. `packages/tailwind-config/tailwind.config.js` on the `const` keyword
2. `packages/ui/tailwind.config.js` on the `const` keyword
3. `packages/eslint-config-custom/index.js` on the `module` keyword

The same error at all places: `Parsing error: Cannot find module 'next/babel'`.
There is a similar bug report at https://github.com/vercel/turbo/issues/1600 but I experienced it with a different example.

### Expected Behavior

There shouldn't be any error in VSCode. Tailwind is quite popular and I believe it shuld work out of the box with Turborepo.

### To Reproduce

1. Follow the instructions [here](https://github.com/vercel/turbo/blob/main/examples/with-tailwind/README.md)
2. Open VSCode and navigate to `packages/tailwind-config/tailwind.config.js`
3. The first `const` is underlined and shows the error on hover

### Reproduction Repo

https://github.com/vercel/turbo/tree/main/examples/with-tailwind

**Comment by Manubi** [comment]
Same here, and I started a fresh turborepo.

**Comment by Learning-X** [comment]
Any fix on this yet?
