### ISSUE TITLE
[Turbopack] lint TP1004 fs.realpathSync(???*0*) is very dynamic

### ISSUE THREAD

**Issue by filename24** [vercel/turbo#3205]
### What version of Turbopack are you using?

1.6.3

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Windows

### Describe the Bug

When using a package which depends on temd-dir, turbopack can't compile the app.

It fails with the following output:
```ts
  \\?\C:\Users\anhge\Desktop\Developemt\nextjs-template\node_modules\temp-dir\index.js
    \\?\C:\Users\anhge\Desktop\Developemt\nextjs-template\node_modules\temp-dir\index.js:9:9  lint TP1004 fs.realpathSync(???*0*) is very dynamic
         5   const tempDirectorySymbol = Symbol.for('__RESOLVED_TEMP_DIRECTORY__');
         6
         7   if (!global[tempDirectorySymbol]) {
         8      Object.defineProperty(global, tempDirectorySymbol, {
         9 >            value: fs.realpathSync(os.tmpdir())
        10      });
        11   }
        12
        13   module.exports = global[tempDirectorySymbol];

    - *0* ???*1*()
      ⚠️  call of unknown function
    - *1* os*2*["tmpdir"]
      ⚠️  unsupported property on Node.js os module
    - *2* os: The Node.js os module: https://nodejs.org/api/os.html

```

### Expected Behavior

file building error

### To Reproduce

Checkout the repo below. It's an exceedingly minimal Next 13 project.
next dev works as intended.
next dev --turbo --show-all will produce the aforementioned error.

### Reproduction Repo

https://github.com/filename24/nextjs-template/tree/nextjs13

**Comment by ducan-ne** [comment]
I have the same issue with Prisma + Postcss

**Comment by Elijah629** [comment]
I have the same issue, its postcss that does it. But it says Turbopack cant "analyze function calls" which is most likely the problem

**Comment by abdoKa** [comment]
the same issue trying installing tailwind CSS with turbo mode.getting 3 warnings

**Comment by 18jad** [comment]
any update on this? still facing this issue with postcss and tailwind installed

**Comment by Glaser78** [comment]
same issue with the tailwind CSS aswell

**Comment by AcidOP** [comment]
It is PostCSS that causes this error when being used with Turbopack

**Comment by DavidYang2149** [comment]
same issue with tailwind CSS + pnpm

**Comment by mjth** [comment]
Removing my PostCSS config removes this error, so yes - definitely seems like a PostCSS issue

**Comment by dogfrogfog** [comment]
Hey, @ai. Any thought on this one ?

**Comment by el-buku** [comment]
bump

**Comment by Celarye** [comment]
Having the exact same issue with a clean `create-next-app` install using npm.

**Comment by kaumac** [comment]
Same here, just did created a new project, didn't change a single line of code, just ran `next dev --turbo` and I'm now getting 3 warnings all about this

**Comment by ChetSocio** [comment]
Hey guys I have observed that I only got the same error after updating create-next-app to latest version. Otherwise with provious versions, even with postcss, it was not throwing this very dynamic error. I can confirm that postcss may not be issue as i also have tried without postcss and tailwind and got same error again. So there seems to be problem with create-next-app@latest

**Comment by Geo-W** [comment]
> Hey guys I have observed that I only got the same error after updating create-next-app to latest version. Otherwise with previous versions, even with postcss, it was not throwing this very dynamic error. I can confirm that postcss may not be issue as I also have tried without postcss and tailwind and got same error again. So there seems to be problem with create-next-app@latest

which version u r using, i m using  create-next-app@13.4.13 and got this issue

**Comment by shdw-js** [comment]
well, not sure why this is happening but if you downgrade Next to the version 13.4.10 the issue disappears.

"next": "13.4.10",

**Comment by bryce0516** [comment]
> well, not sure why this is happening but if you downgrade Next to the version 13.4.10 the issue disappears.
> 
> "next": "13.4.10",

still has ths issue in "13.4.10"

**Comment by timneutkens** [comment]
Verified this no longer happens on the latest version: https://codesandbox.io/p/github/filename24/nextjs-template/csb-l4ksvh/draft/distracted-einstein?file=%2Fnext.config.js%3A15%2C1

If you're still running into problems please open a new issue with another reproduction so that we can verify it 🙏

**Comment by timneutkens** [comment]
@ChetSocio which version are you on currently? It seems this PR should have addressed the problem you're seeing: https://github.com/vercel/next.js/pull/58835

**Comment by dcodesdev** [comment]
Upgraded to `next@14.2.3` same error happens.

**Comment by timneutkens** [comment]
@dcodesdev please open a new issue with a reproduction.

**Comment by kmvan** [comment]
What's the `???*0*` ?
