### ISSUE TITLE
[turborepo] fails to parse workspaces from package.json

### ISSUE THREAD

**Issue by HerryYT** [vercel/turbo#3207]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

When running the build command, I am getting this log from turbo:
 `WARNING  Issues occurred when constructing package graph. Turbo will function, but some features may not be available:  1 error occurred:
        * json: cannot unmarshal object into Go struct field NpmPackage.packages.workspaces of type []string
`

That's probably because my workspaces entry is not made of []string but it's formed like that instead:
`
    "workspaces": {
        "packages": [
            "packages/**"
        ]
    }
`

### Expected Behavior

Turbo properly parses packages entry.

### To Reproduce

Setup a monorepo project using the same "workspaces" entry structure given in the Bug description.

### Reproduction Repo

https://github.com/JSPrismarine/JSPrismarine

**Comment by tknickman** [comment]
Hey @HerryYT! Thanks for the report. I took a quick look through how NPM parses workspaces - interestingly, it _does_ look like they allow an Array of strings at either  `workspaces.packages`, _or_ `workspaces` ([source](https://github.com/npm/map-workspaces/blob/main/lib/index.js#L29-L40)).

Currently we only support:
`workspaces: Array<string>` and not `workspaces: { packages: Array<string> }`.

We'll get that fixed up, but to get unblocked in the meantime you can swap your `package.json` workspace declaration to use the more common (and functionally equivalent):
`workspaces: Array<string>`.
