### ISSUE TITLE
[turborepo] When specify a single file inputs is used, turbo can't detect file content changes.

### ISSUE THREAD

**Issue by ZZZJX0912** [vercel/turbo#3212]
### What version of Turborepo are you using?

1.5.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When performing CI in the docker container, a single file inputs cannot be detected
Execution at vscode can meet the expected change, but not at CICD on the docker container, and always hit the cache during the CICD process even if my inputs file content changes

```json
 {
     "$schema": "https://turborepo.org/schema.json",
     "pipeline":{
           "prisma:generate":{
               "inputs": ["datamodel.prisma"],
               "outputs": [
                  "src/generated/prisma-client/**"
               ]
          },
     }
}
```

### Expected Behavior

Reexecute the command, again `prisma: generate` when inputs files content Change 

### To Reproduce

I haven't put together a reproduction yet, still kind of investigating. But hopefully someone has some tips on where to look to figure out the cause of this.

**Comment by ZZZJX0912** [comment]
This problem has bothered me for many days and this problem only appeared during the CICD process and had no problem during vscode terminal execution

**Comment by Brookke** [comment]
Seeing the same issue. Works fine locally, but in docker it doesn't have the file in the list of inputs

**Comment by anthonyshew** [comment]
This is intended behavior. Specifying an `inputs` key opts you out of Turborepo's default inputs.

However, we've added a a microsyntax in 1.12 to make it easier to add the defaults back. Check it out here: https://turbo.build/blog/turbo-1-12-0#improved-inputs-ergonomics
