### ISSUE TITLE
[turborepo]  Problem when using with App directory

### ISSUE THREAD

**Issue by robinsandborg** [vercel/turbo#3214]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

"use client"  directive does not work, as it's not placed on top of the file with the desig system example.

### Expected Behavior

Components should be compatible with next13 app directory.

### To Reproduce

Run reproduction repo and open the next-app

### Reproduction Repo

https://github.com/robinsandborg/turbo

**Comment by chris-olszewski** [comment]
Hi @robinsandborg, can you elaborate on how turborepo is contributing to this issue? Looking at the repro `next dev` fails in the same way as `pnpm turbo dev --filter=web` does

**Comment by diogonr** [comment]
I'm having a similar issue

```tsx
use client";

export const Navbar = () => {

  let isUserMenuOpened = false;
  const toggleUserMenu = () => {
    isUserMenuOpened = !isUserMenuOpened;
  };

  return (
    <button onClick={toggleUserMenu}>button</button>
  );
}
```

`pnpm dev`
```
web:dev: 
web:dev: The "use client" directive must be placed before other expressions. Move it to the top of the file to resolve this issue.
web:dev: 
web:dev:      ,-[/Users/diogoribeiro/Documents/Code/redacted/client/redacted/packages/ui/dist/index.js:155:1]
web:dev:  155 | 
web:dev:  156 | // src/Navigation/Navbar.tsx
web:dev:  157 | var import_jsx_runtime3 = require("react/jsx-runtime");
web:dev:  158 | "use client";
web:dev:      : ^^^^^^^^^^^^^
web:dev:  159 | var Navbar = () => {
web:dev:  160 |   let isUserMenuOpened = false;
web:dev:  161 |   const toggleUserMenu = () => {
web:dev:      `----```

If i remove 'use client';
I get a new error
```
web:dev: event - compiled client and server successfully in 493 ms (242 modules)
ui:dev: [0] DTS ⚡️ Build success in 1231ms
web:dev: wait  - compiling /page (client and server)...
web:dev: event - compiled client and server successfully in 280 ms (377 modules)
web:dev: Error: Event handlers cannot be passed to Client Component props.
web:dev:   <button onClick={function} type=... className=... id=... children=...>
```

**Comment by SenseiCain** [comment]
@diogonr We're having the same issue currently. What version of `node` are you using? This became an issue for us after upgrading to `13.1.4`.

**Comment by mkappelhof** [comment]
I've created a file in my design system consumer with the `use client` directive at the top and this file exports all the components from my design system i use in my client. 

Far from ideal, but works for now until it's properly fixed

**Comment by tknickman** [comment]
If you're _bundling_ a `ui` library (like in the design system example), you can add the use client directive to the entire bundle (NOTE: this is not required for internal packages without a build step). We do this via `tsup` with the following config (currently used for the changeset, kitchen-sink, and react native example):

```
import { defineConfig, Options } from "tsup";

export default defineConfig((options: Options) => ({
  banner: {
    js: "'use client'",
  },
  ...options,
}));
```

If you wanted to mix client and server components in the same package, I would setup two separate entry points
