### ISSUE TITLE
Graph caching 

### ISSUE THREAD

**Issue by torifat** [vercel/turbo#322]
### What version of Turborepo are you using?

1.0.13

### Describe the Bug

First of all, a big thanks for opening up this tool to the community. One of my colleagues and I have played with it a little bit and tried it on a moderately large repo. The repo I'm currently using is private, so I can't share it 😞. However, there is an older public mirror [here]( https://bitbucket.org/atlassian/atlaskit-mk-2/src/master/). The latest version has 529 packages in total.

_NOTE: We had to remove all circular dependencies._

I don't consider this a bug, but it felt more appropriate than other available types. I'm just sharing our findings 🙂.

Currently, it takes us around 30~35s to run any command.

```
❯ turbo run lint --scope="@atlaskit/share"
• Packages in scope: @atlaskit/share
• Running lint in 1 packages
@atlaskit/share:lint: cache hit, replaying output 732f7166cc3bda8e
[REMOVED]
@atlaskit/share:lint: Done in 7.66s.

 Tasks:    1 successful, 1 total
Cached:    1 cached, 1 total
  Time:    35.152s >>> FULL TURBO
```

I did some profiling and it seems the majority of time is being spent on generating the dependency graph.

<img width="1680" alt="Screen Shot 2021-12-16 at 9 16 42 am" src="https://user-images.githubusercontent.com/208544/146393077-5fae3980-540e-4117-a7d9-31713832ddec.png">

### Expected Behavior

I expect `turbo` to cache the dependency graph too. 

_NOTE: My assumption can be wrong here since I can't see turbo internal code 🙂._

### To Reproduce

It's a private repo, so sharing exact steps wouldn't help much. However, I hope you will find the `cpuprofile` useful 
[cpuprofile.out.zip](https://github.com/vercel/turborepo/files/7728295/cpuprofile.out.zip)

**Comment by jaredpalmer** [comment]
Both graph caching and build skipping are in the works. Stay tuned

**Comment by anthonyshew** [comment]
Figuring this has been handled after two years. Feel free to open a new issue if you're still experiencing performance issues.
