### ISSUE TITLE
Typescript autoimport suggestion not working

### ISSUE THREAD

**Issue by igor-ribeiro** [vercel/turbo#331]
### What version of Turborepo are you using?

1.0.15

### Describe the Bug

Import suggestion from Typescript are not working, unless you have the packages with an empty import (`import {} from 'ui'`)

![turborepo-ts-import](https://user-images.githubusercontent.com/5148753/146465829-6e8fd7cc-988d-4352-a2f5-52e669ba673b.gif)

### Expected Behavior

Typescript should recognize the packages from the monorepo.

### To Reproduce

1. Start a new project with `npx create-turbo@latest` or clone an example (I cloned the design system)
2. Open the index.tsx (or any file from the apps)
3. Remove the import statement of one shared component
4. Try to auto import it from IDE

**Comment by MarcARoberge** [comment]
I had this error using npm@6. upgrade my node to 16 and it worked

**Comment by igor-ribeiro** [comment]
Yeah, I'm using nvim in an environment with node 16 and it doesn't show the error, but the import is still not working.

**Comment by igor-ribeiro** [comment]
Updated the description to better explain the issue.

**Comment by igor-ribeiro** [comment]
It works if I put `../../packages/**/*.tsx` on `web/tsconfig.json` for example, but then the import is `import { Button } from "../../../packages/ui";` instead of `import { Button } from 'ui'`;

**Comment by igor-ribeiro** [comment]
Got it working... You need to add `"references": [{ "path": "../../packages/PACKAGE_NAME" }]` on `tsconfig.json` of every package that you want to use **PACKAGE_NAME**.

**Comment by fabrixiop26** [comment]
@igor-ribeiro could you show me an example of `tsconfig.json` for the package you want to use and the `tsconfig.json` for the package in which you want to import it? it's not working out of the box for me even after setting `composite: true` in the package i want to reference

**Comment by igor-ribeiro** [comment]
@fabrixiop26 I'm using the examples from here, so it's the same `tsconfig.json`.

**Comment by sghsri** [comment]
I can only get this working for actual code, not types. 
Anyone find a solution for this? 


![image](https://user-images.githubusercontent.com/13592854/150684412-d2a809da-2b9a-41c9-8747-59bebeb5b2e1.png)

![image](https://user-images.githubusercontent.com/13592854/150684428-23c107d1-9708-4d5e-a013-57a819ead03c.png)

**Comment by sghsri** [comment]
wanting to bump this and see if anyone has figured this piece out!

**Comment by anthonyshew** [comment]
Our recent example updates have fixed this!
