### ISSUE TITLE
[turborepo] `npx @turbo/codemod set-default-outputs` reports 'Invalid transform choice'

### ISSUE THREAD

**Issue by grempe** [vercel/turbo#3322]
### What version of Turborepo are you using?

1.7.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Running the new `set-default-outputs` codemod fails with `npx` and `pnpx` from the root of a turborepo.

Following instructions here:

https://turbo.build/repo/docs/reference/codemods#set-default-outputs

Output is:

```sh
❯ npx @turbo/codemod set-default-outputs
Invalid transform choice, pick one of:
- add-package-manager
- create-turbo-config
- migrate-env-var-dependencies
```

### Expected Behavior

Should run the codemod as per the instructions.

### To Reproduce

Run `npx @turbo/codemod set-default-outputs` from the root of a Turbo monorepo.

**Comment by tknickman** [comment]
Hey @grempe, can you give:
```
npx @turbo/codemod@latest set-default-outputs
```

A try?

**Comment by grempe** [comment]
Yes, that worked.
