### ISSUE TITLE
[turborepo] turbo prune exit code: 101

### ISSUE THREAD

**Issue by digoburigo** [vercel/turbo#3355]
### What version of Turborepo are you using?

1.7.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Suddenly the step in Dockerfile that envolves turborepo `RUN turbo prune --scope=web --docker`, started to output this error:
```
ERROR [builder 8/8] RUN turbo prune --scope=web --docker                                     0.3s
------
 > [builder 8/8] RUN turbo prune --scope=web --docker:
#0 0.309 thread 'main' panicked at 'Failed to execute turbo.: Os { code: 8, kind: Uncategorized, message: "Exec format error" }', crates/turborepo-lib/src/shim.rs:377:14
#0 0.309 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------
failed to solve: executor failed running [/bin/sh -c turbo prune --scope=web --docker]: exit code: 101
```

### Expected Behavior

Build normally

### To Reproduce

I don't know how to reproduce because it's random. I don't change anything in the code. The only thing I made was keeping building de Dockerfile with docker compose (I don't know if it's related). Can someone help?

**Comment by prabhjotsinghchadha** [comment]
I am getting exact same error. 
I am using 1.7.0 version of turbo
Package Manager = NPM
OS = Mac
Bug is same as you have mentioned above

**Comment by digoburigo** [comment]
I resolved this issue for me by checking if my `.dockerignore` it's in the root folder containing the right files to ignore. 
I will leave this issue open for now for more dicussion.

**Comment by prabhjotsinghchadha** [comment]
> I resolved this issue for me by checking if my `.dockerignore` it's in the root folder containing the right files to ignore. I will leave this issue open for now for more dicussion.

Can you please tell me which file you added in .dockerignore? If it's common then I will also try it on my system.

**Comment by digoburigo** [comment]
In my case I have a monorepo using pnpm workspaces (NOTE: if you use pnpm wokspaces check if all apps and packages are declared here too):
On root folder of project `.dockerignore`, with the following content
```
node_modules/
.vercel
.next
.env.local
.env.production
.env.dev
.env.*

dev.Dockerfile
prod.Dockerfile
Dockerfile
README.md
node_modules
npm-debug.log
```

**Comment by prabhjotsinghchadha** [comment]
No, It didn't work. I am also using turborepo with npm, and added the necessary files to .dockerignore.

**Comment by arugurjar** [comment]
This solution might help: https://github.com/vercel/turbo/issues/2198

**Comment by ridafkih** [comment]
@digoburigo This solved it for me, and I think the critical piece here is the exclusion of `node_modules`. 

`Exec format error` is likely originating from the dependencies being built for another architecture than is being provided. If for some reason your `node_modules` is being pulled over from your host machine and trying to be run there, it'll cause this issue.

**Comment by prabhjotsinghchadha** [comment]
> I have the same setup, with 1.7.0 and NPM still no luck

I am able to run after downgrading docker in dockerfile 
"RUN npm -g install turbo@1.6.3"

**Comment by chris-olszewski** [comment]
Closing as this is issues are probably related to copying `node_modules` into the Docker container which can result in the wrong `turbo` binary being installed for the OS/arch. See this [esbuild doc page](https://esbuild.github.io/getting-started/#simultaneous-platforms) for a good explanation of why this causes failures for those using npm or pnpm.

If you encounter this, please verify that you aren't copying `node_modules` from the host and open a new issue. If you can provide a reproduction it will be beneficial as it is very likely an issue with your specific configuration.
