### ISSUE TITLE
[turborepo] Using turbo scripts with lint-staged, .husky and ESLint

### ISSUE THREAD

**Issue by pt232** [vercel/turbo#3364]
### What version of Turborepo are you using?

1.7.0

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

I would like to use `turbo` scripts (like `turbo run lint`) in combination with [lint-staged](https://github.com/okonet/lint-staged). However, I get the following error message when linting:

```
 npm run lint:
 ERROR run failed: task `{path-to-file}/apps/web/pages/index.tsx` not found in `pipeline` in "turbo.json". Are you sure you added it?
```

index.tsx in this case is the file where I made changes for the commit. 

If I add the changed file to the turbo.json file, then it works. But I guess that's not the point. 😀 Maybe this problem is also related to lint-staged rather than turborepo. 

By the way: other npm scripts (like `npm run format`) run without errors.

Thanks for your help!

### Expected Behavior

I would have expected to be able to run simple `turbo` scripts. But maybe the whole thing is not possible at all.

### To Reproduce

Run the following commands to reproduce this issue:

1. npx create-turbo@latest

```
Where would you like to create your turborepo? ./my-turborepo
Which package manager do you want to use? npm
```

2. Open the project in VS Code
3. npx husky-init && npm install
4. npm install --save-dev lint-staged
5. Add `npx lint-staged --concurrent false` to the .husky/pre-commit hook
6. touch .lintstagedrc

```json
{
  "*.{js,ts,tsx}": ["npm run format", "npm run lint"],
  "*.json": ["npm run format"]
}
```

7. Make some changes inside a workspace
8. Create a commit
9. Get the following error:

```
✔ Preparing lint-staged...
❯ Running tasks for staged files...
  ❯ .lintstagedrc — 2 files

✖ npm run lint:
 ERROR  run failed: task `{path-to-file}/apps/web/pages/index.tsx` not found in `pipeline` in "turbo.json". Are you sure you added it?

> my-turborepo@0.0.0 lint
> turbo run lint {path-to-file}/apps/web/pages/index.tsx

Turbo error: task `{path-to-file}/apps/web/pages/index.tsx` not found in `pipeline` in "turbo.json". Are you sure you added it?
❯ *.{js,ts,tsx} — 1 file
      ✔ npm run format
      ✖ npm run lint [FAILED]
    ◼ *.json — 0 files
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...
✔ Preparing lint-staged...
❯ Running tasks for staged files...
  ❯ .lintstagedrc — 2 files
    ❯ *.{js,ts,tsx} — 1 file
      ✔ npm run format
      ✖ npm run lint [FAILED]
    ◼ *.json — 0 files
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...
husky - pre-commit hook exited with code 1 (error)
```

I have the following package.json:

```json
{
  "name": "my-turborepo",
  "version": "0.0.0",
  "private": true,
  "workspaces": [
    "apps/*",
    "packages/*"
  ],
  "scripts": {
    "build": "turbo run build",
    "dev": "turbo run dev --parallel",
    "lint": "turbo run lint",
    "format": "prettier --write \"**/*.{ts,tsx,md}\"",
    "prepare": "husky install"
  },
  "devDependencies": {
    "eslint-config-custom": "*",
    "husky": "^8.0.0",
    "lint-staged": "^13.1.0",
    "prettier": "latest",
    "turbo": "latest"
  },
  "engines": {
    "node": ">=14.0.0"
  },
  "packageManager": "npm@9.2.0"
}
```

And the following turbo.json:

```json
{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**", ".next/**"]
    },
    "lint": {
      "outputs": []
    },
    "dev": {
      "cache": false
    }
  }
}
```

**Comment by mehulkar** [comment]
I'm guessing that lint-staged is calling `npm run lint` and passes it some file arguments. Since `npm run lint` calls `turbo run lint`, this argument is getting passed directly, becoming:

```
turbo run lint {path-to-file}/apps/web/pages/index.tsx`
```

turbo interprets that last argument as a task name, which it isn't.

Try changing your `.lintstagedrc` file to:

```json
{
  "*.{js,ts,tsx}": ["npm run format", "npm run lint --"],
  "*.json": ["npm run format"]
}
```

(notice the extra `--` after `npm run lint`)

**Comment by mehulkar** [comment]
Great! Glad it worked out @pt232!

**Comment by gyhyfj** [comment]
Are you all sure it work? It does not throw error now, BUT the range is not scoped as lint-staged, it's command effect on ALL files in you moorepo! 
I just modified 3 files in my monorepo project, but the lint-staged with `prettier` cost almost 10 mins!

**Comment by gyhyfj** [comment]
And what's worse, these config and ignore files in every project of monorepo cannot effect on their own project now

**Comment by pt232** [comment]
> Are you all sure it work? It does not throw error now, BUT the range is not scoped as lint-staged, it's command effect on ALL files in you moorepo! I just modified 3 files in my monorepo project, but the lint-staged with `prettier` cost almost 10 mins!

Maybe you have the wrong scope for the lint-staged scripts. For example, you could adjust the `.lintstagedrc` file from the original post as follows:

```diff
{
   "*.{js,ts,tsx}": ["npm run format", "npm run lint"],
-  "*.json": ["npm run format"],
+  "apps/**/*.json": ["npm run format"]
}
```

As a consequence, the formatting script `npm run format` should only run for JSON file changes inside the different apps. For example, if you have a changed JSON file in the root of the project and one inside a subdirectory of the `apps` folder, then the format script only runs for the JSON file inside the `apps` folder.

**Comment by lbennett-stacki** [comment]
Can confirm this wont fix, will behave the same as calling your lint script directly from the git hook without lint-staged

**Comment by Eliot00** [comment]
Added `--` but still not work with bun 1.1.20

**Comment by Scooter1337** [comment]
My solution, which works great:

**Package.json: **
```
{
...,
"scripts": {
  ...,
  "lint-staged": "lint-staged"
  }
}
```

**.lintstagedrc: **
```
{
  "/apps/**/*.{js,ts,tsx}": ["prettier --write", "eslint --fix"],
  "/packages/**/*.{js,ts,tsx}": ["prettier --write", "eslint --fix"],
  "*.json": ["prettier --write"]
}
```

I guess it bypasses turbo, but as it only lints and formats staged files it's more than fine.

**Comment by vyshnavsdeepak** [comment]
@Scooter1337 's solution still threw me errors as I didn't have an eslint config in project root.

Found a solution here - https://nitpum.com/post/lint-staged-eslint-monorepo/

The approach involves adding a .lintstagedrc config in each package:
```
{
  "*.{js,ts,tsx}": ["prettier --write", "eslint --fix"]
}
```
With this setup, lint-staged picks up the nearest config based on the staged file, also following the ESLint config in that directory.

**Comment by lamngockhuong** [comment]
> I'm guessing that lint-staged is calling `npm run lint` and passes it some file arguments. Since `npm run lint` calls `turbo run lint`, this argument is getting passed directly, becoming:
> 
> ```
> turbo run lint {path-to-file}/apps/web/pages/index.tsx`
> ```
> 
> turbo interprets that last argument as a task name, which it isn't.
> 
> Try changing your `.lintstagedrc` file to:
> 
> ```json
> {
>   "*.{js,ts,tsx}": ["npm run format", "npm run lint --"],
>   "*.json": ["npm run format"]
> }
> ```
> 
> (notice the extra `--` after `npm run lint`)
> 
> Ultimately you're trying to produce this command: `turbo run lint -- <path>`
> 
> https://turbo.build/repo/docs/reference/command-line-reference#turbo-run-task

it worked for me

**Comment by bestickley** [comment]
If using turborepo, do you need lintstaged anymore? The [docs](https://turborepo.com/docs/crafting-your-repository/running-tasks#filtering-by-source-control-changes) explain you can run `turbo build --filter=[HEAD^1]` to run the build command "Comparing to the previous commit". I guess the tradeoff is that you lose per file operations which might not be worth it for some.
