### ISSUE TITLE
[turborepo] Turbo crashes with any command in Official Node Docker image (Alpine)

### ISSUE THREAD

**Issue by ben-xD** [vercel/turbo#3373]
### What version of Turborepo are you using?

1.7.0

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Docker (Linux) on Mac

### Describe the Bug

Turbo crashes when using any command (e.g. `turbo build`), even when a valid project and `turbo.json` exists. This doesn't seem to be a problem on Ubuntu, but only on Alpine (arm64).

I've tried all of the new versions but they have the same issue.
- `npm install --global turbo`
- `npm install --global turbo@latest`
- `npm install --global turbo@canary`

## error:

```
thread 'main' panicked at 'Failed to execute turbo.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/turborepo/src/main.rs:23:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

---

I'm running Docker on an M1 mac.

### Expected Behavior

Any command works.

### To Reproduce

- Build a container and enter container shell: run `docker run -it node:18-alpine sh`
  - to specify arm64, run `docker run --platform=linux/arm64 -it node:18-alpine sh`
- Install turbo: `npm install --global turbo`
- Run any turbo command: run `turbo build`
  - Error happens when `turbo.json` is or is-not present.

Observe error:
```
$ turbo build
thread 'main' panicked at 'Failed to execute turbo.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/turborepo/src/main.rs:23:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ben-xD** [comment]
I'll close this because it looks like it's we just need to know/remember to install `libc6-compat`

It would be good if it was clearer in the docs though (maybe it's already documented).

**Comment by tknickman** [comment]
Hey @ben-xD, thanks for the investigation - we do have this documented! 

https://turbo.build/repo/docs/getting-started/existing-monorepo#install-turbo
