### ISSUE TITLE
[turborepo] Generated prisma client is cached but not restored

### ISSUE THREAD

**Issue by TomaszG** [vercel/turbo#3393]
### What version of Turborepo are you using?

1.7.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Despite providing the correct Prisma client generated files that are cached by turbo, they're not restored on subsequent command runs. Please take a look at the reproduction repo for details. 

My turbo.json
```json
{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
    "generate": {
      "inputs": [
        "package.json",
        "src/prisma/schema.prisma"
      ],
      "outputs": [
        "../../node_modules/.pnpm/@prisma+client*/node_modules/.prisma/client/**"
      ]
    }
  }
}
```

### Expected Behavior

The cache should be fully restored.

### To Reproduce

0. Checkout the reproduction repository
1. Install dependencies with
    ```bash
    pnpm i
    ```
2. Generate Prisma Client with
    ```bash
    pnpm turbo run generate
    ```
3. Check if Prisma Client files are generated with 
    ```bash
    ls -la node_modules/.pnpm/@prisma+client*/node_modules/.prisma/client/**
    ```
4. Remove generated Prisma Client files with
    ```bash
    rm -rf node_modules/.pnpm/@prisma+client*/node_modules/.prisma/client/
    ```
5. Confirm that files were removed with 
    ```bash
    ls -la node_modules/.pnpm/@prisma+client*/node_modules/.prisma/client/**
    ```
    Should return **no matches found** error
6. Once again, generate Prisma Client with 
    ```bash
    pnpm run turbo generate
    ```
    Should restore generated client from turbo cache
7. Check if Prisma Client files were restored with 
    ```bash
    ls -la node_modules/.pnpm/@prisma+client*/node_modules/.prisma/client/**
    ```
    Files were not restored
8. Check if Prisma Client files were cached with
    ```bash
    tar --use-compress-program=unzstd -ztvf node_modules/.cache/turbo/27dc189e81124d92.tar.zst
    ```
    (hash may be different) - files are there but they were not restored

### Reproduction Repo

https://github.com/TomaszG/turborepo-prisma-cache-issue

**Comment by clodal** [comment]
This might be helpful: https://turbo.build/repo/docs/handbook/tools/prisma#7-caching-the-results-of-prisma-generate

**Comment by TomaszG** [comment]
@clodal thanks to that, I've followed that tutorial, and that's what I'm trying to achieve here. However, even though the output path for Prisma client cache is correct (as it's stored in turborepo's cache), the files are not restored when they're missing.

**Comment by fevernova90** [comment]
@TomaszG I noticed this keeps happening too. For me it's not just happening to prisma package, it's happening to random other repo. This is not consistent, you can test it when you delete the `output` folder, then running the command, the cli is showing FULL TURBO but those cached files were not restored.

**Comment by TomaszG** [comment]
I've just tried to reproduce it with turbo v1.9.8, and it seems to be fixed there.

**Comment by sepehr500** [comment]
I had to run `--no-daemon` to fix the issue
