### ISSUE TITLE
[turborepo] turbo.json `"outputMode": "errors-only"` fails

### ISSUE THREAD

**Issue by zpg6** [vercel/turbo#3417]
### What version of Turborepo are you using?

1.7.0

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

When configuring turbo.json file, have run into an inconsistency between the docs for `outputMode` and CLI availability. It seems that `"outputMode": "errors-only"` may not be an option as described in docs.

[Docs > Configuration Options > outputMode](https://turbo.build/repo/docs/reference/configuration#outputmode)

<img width="464" alt="image" src="https://user-images.githubusercontent.com/17848742/213879536-0943e1f3-6682-475d-ac55-a592f473b7c3.png">

**"errors-only" receives error:**
```
$ turbo run build
 ERROR  run failed: turbo.json: invalid task output mode: errors-only
error Command failed with exit code 1.
```

### Expected Behavior

`"outputMode": "errors-only"` should not fail and should only show output from task failures, or it should not be listed as an option in Docs.

### To Reproduce

Add `"outputMode": "errors-only"` to one or more tasks.

**Example turbo.json file:**
```json
{
    "pipeline": {
        "build": {
            "dependsOn": ["^build"],
            "outputMode": "errors-only"
        },
        "test": {
            "dependsOn": ["build"],
            "outputMode": "errors-only"
        }
    }
}
```

**Comment by NicholasLYang** [comment]
Hi Zach! Thanks for the issue. Is there any chance you could provide a reproduction repo?

One possibility is that your local turbo is a different version than your global turbo. Could you check that in your package.json, the turbo version is 1.7.0?

**Comment by laurens-mesure** [comment]
I have the same issue on turbo 1.7.0 It seems like the flag is ignored because any valid `outputMode` value results in the same log output.

**Comment by mehulkar** [comment]
A reproduction would be really good. I added a few tests that seem to indicate the feature is working: https://github.com/vercel/turbo/pull/3945. 

- For the hard error, I think @NicholasLYang is probably right that this may have something to do with a a global + local combo of `turbo` versions not working well together.

- For `outputMode` getting ignored (without the error), @laurens-mesure if you could file a separate issue with a repro that would  probably help us figure it out pretty quickly!

**Comment by anthonyshew** [comment]
Going to close this one due to inactivity and no reproduction!

**Comment by mehulkar** [comment]
I've reproduced a similar issue reported in https://github.com/vercel/turbo/issues/6677. If that reflects your reproduction, you can follow along there for a bugfix
