### ISSUE TITLE
[turborepo] `pipeline.build.inputs` globbing not working

### ISSUE THREAD

**Issue by revero-doug** [vercel/turbo#3467]
### What version of Turborepo are you using?

^1.6.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

none of the following values for `pipeline.build.inputs` work to include all files under `./src` (relative to a package in the monorepo) when running in a docker build context that does not include the `.git` directory with remote caching (via fox1t/turborepo-remote-cache); as a result, there are cache hits when there should be misses.

- `src`
- `src/**`
- `src/**/*`

caching works as expected when leaving `pipeline.build.inputs` undefined

### Expected Behavior

the cache is invalidated when any files specified by a globbing pattern in the `pipeline.build.inputs` array, change

### To Reproduce

run `pnpm turbo build` in a Dockerfile with remote caching against a container running `fox1t/turborepo-remote-cache`, with the monorepo `.git` directory excluded from the build context by adding to .dockerignore

**Comment by chris-olszewski** [comment]
Could you provide a reproduction? This sounds like a configuration which will be hard to identify without looking at how your repo is setup.

**Comment by anthonyshew** [comment]
Closing as stale with no reproduction.
