### ISSUE TITLE
[turborepo] 

### ISSUE THREAD

**Issue by The-White-Fang** [vercel/turbo#3528]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

I  create a new turbo, and added an Astro project with react using `pnpm create astro@latest -- --template framework-react`. I ran it and I was seeing following errors in console:
```
data:text;charset=u…:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

data:text;charset=u…:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

I then tried to reproduce the error without the turbo repo and everything was working fine. I copy pasted the project to turbo repo and it broke again.

### Expected Behavior

It should have been working.

### To Reproduce

Create a turbo repo using `pnpm` package manager. 
`cd` into `apps`.
Run `pnpm create astro@latest -- --template framework-react`
Run the project using `pnpm run dev --filter [astro-project]`

**Comment by chris-olszewski** [comment]
@The-White-Fang can you provide a Github repository with a reproduction. I wasn't able to reproduce following your steps.
