### ISSUE TITLE
Retrieve static assets from a sveltekit package/library

### ISSUE THREAD

**Issue by LeviticusNelson** [vercel/turbo#3559]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

You can retrieve assets from local static directory in sveltekit using: 
`<link rel="stylesheet" href="%sveltekit.assets%/assets/css/custom.css" /> `
But I want to send all of my static assets into a sveltekit package so that I can reuse custom components and also not have multiple copies of the static assets in each workspace.

### Describe the solution you'd like

Similar import like:
`<link rel="stylesheet" href="%@package_name:sveltekit.assets%/assets/css/custom.css" /> `

### Describe alternatives you've considered

Right now I have multiple copies of my assets in each workspace.

**Comment by mehulkar** [comment]
@LeviticusNelson can you clarify what this issue is about? Are you asking for a feature in Sveltekit? Or is this perhaps for turbo_pack_ ? The issue says Turborepo, so I want to make sure before proceeding.

**Comment by LeviticusNelson** [comment]
@mehulkar hi, I figured out how to import static assets from a different directory in `svelte.config.js`:  
```js
const config = {
    preprocess: [preprocess()],

    kit: {
        adapter: adapter(),
        files: {
            assets: "../../packages/ui/static",
        },
    },
};
```
I am now not sure if this would relate more to sveltekit or turbo because I would like to do something like this for future apps/packages in my monorepo:
```js
 const config = {
    preprocess: [preprocess()],

    kit: {
        adapter: adapter(),
        files: {
            assets: "ui/static",
        },
    },
};
```

**Comment by mehulkar** [comment]
I see. It seems like you are wanting to reference another directory while bundling sveltekit? I don't think this is something turborepo can help with. Your solution to use relative paths seems workable. Alternatively, you may want to see if your package manager (npm/yarn/pnpm) may have any conveniences to resolve the name `ui` to a path. 

cc @anthonyshew in case you have any other suggestions!
