### ISSUE TITLE
[turbopack] Unable to resolve server relative import

### ISSUE THREAD

**Issue by nico98gon** [vercel/turbo#3573]
### What version of Turbopack are you using?

I'm using 1.7.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

when I deployed the app using turbopack, I get back an issue because this one apparently did not support relative import yet. 

 unable to resolve server relative "/assets/img/motoProducto.jpg"
  
  | An error happened during resolving.
  | Error message: server relative imports are not implemented yet. Please try an import relative to the file you are importing from.
  | Parsed request as written in source code: server relative "/assets/img/motoProducto.jpg"
  | Path where resolving has started: [project-with-next]/components
  | Type of request: server relative import: not implemented yet
  | Import map: No import map entry

### Expected Behavior

I expected a normal dev, like pnpm that was working perfectly

### To Reproduce

`import Image from 'next/image';
import productImage from '/assets/img/motoProducto.jpg';

<Image 
      src={productImage}
      height={178}
      alt="No se pudo cargar la image"
/>`

### Reproduction Repo

https://github.com/nico98gon/comercio-san-juan-next

**Comment by Pnlvfx** [comment]
same issue

**Comment by joacub** [comment]
Same here, reported in next but no comments…

**Comment by joacub** [comment]
Recoiling all info in one thread to help speed up this.

https://github.com/vercel/next.js/issues/46358
https://github.com/vercel/next.js/issues/47919

this one probably related
https://github.com/vercel/next.js/issues/47802

**Comment by timneutkens** [comment]
Created a more minimal reproduction on the latest next@canary: https://codesandbox.io/p/github/nico98gon/comercio-san-juan-next/csb-vthk95/draft/competent-glade?file=%2Fapp%2Fpage.tsx%3A12%2C1

I'm surprised this works in webpack tbh, more like a bug in Next.js with webpack than intended behavior, we'll have a look if it makes sense to add this to Turbopack.

**Comment by ForsakenHarmony** [comment]
We probably don't want to support this: https://github.com/vercel/turbo/issues/4979#issuecomment-1551898170
