### ISSUE TITLE
[turborepo] Unable to install package using a fresh create-turbo

### ISSUE THREAD

**Issue by hunghvu** [vercel/turbo#3617]
### What version of Turborepo are you using?

create-turbo v1.7.2

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

This bug happens with both `yarn` and `npm`.

I'm trying to initialize a new monorepo using `npx create-turbo@latest`, but always face the following error.
```
D:\github>npx create-turbo@latest

>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.

? Where would you like to create your turborepo? ./my-turborepo
? Which package manager do you want to use? yarn

>>> Created a new turborepo with the following:

 - apps/web: Next.js with TypeScript
 - apps/docs: Next.js with TypeScript
 - packages/ui: Shared React component library
 - packages/eslint-config-custom: Shared configuration (ESLint)
 - packages/tsconfig: Shared TypeScript `tsconfig.json`

>>  Installing dependencies...
Aborting installation.
  yarn install has failed. // also for npm
```
The folder is created properly, but the package installation process fails. When I navigate to the monorepo and run `npm/yarn install` manually, the following errors happen.

```
// yarn
D:\github\my-turborepo>yarn install
yarn install v1.22.19
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
error An unexpected error occurred: "EISDIR: illegal operation on a directory, symlink 'D:\\github\\my-turborepo\\apps\\docs' -> 'D:\\github\\my-turborepo\\node_modules\\docs'".
info If you think this is a bug, please open a bug report with the information provided in "D:\\github\\my-turborepo\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

// npm
D:\github\my-turborepo>npm install
npm ERR! code EISDIR
npm ERR! syscall symlink
npm ERR! path D:\github\my-turborepo\apps\web
npm ERR! dest D:\github\my-turborepo\node_modules\web
npm ERR! errno -4068
npm ERR! EISDIR: illegal operation on a directory, symlink 'D:\github\my-turborepo\apps\web' -> 'D:\github\my-turborepo\node_modules\web'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\concc\AppData\Local\npm-cache\_logs\2023-02-03T05_31_10_353Z-debug-0.log
```

I also tried `pnpm`, but my system is having another issue preventing the usage of `pnpm`, as reported here: https://github.com/pnpm/pnpm/issues/6014. It may be related.

### Expected Behavior

`npx create-turbo@latest` should be successful out of the box.

### To Reproduce

Run `npx create-turbo@latest`.

**Additional information**
- `yarn` and `npm` work normally on my other projects, only `turborepo` has this issue,
- As for the errors related to a directory, I tried running `npx create-turbo@latest` on `C` drive, and it was a success. At the moment, I store all my projects in a shared drive on a dual boot (Windows 11/PopOS) system. This might give some clues.

### Reproduction Repo

N/a

**Comment by chris-olszewski** [comment]
@hunghvu can you verify that you can symlink directories on this drive? This functionality is necessary to use workspaces in npm and yarn.

**Comment by hunghvu** [comment]
@chris-olszewski Good question, and it let me learn that exFAT (which I used for dual boot) does not natively support symlink (exFAT -> exFAT), hence the error. I suppose the docs can be updated with this information so other newcomers can know. 

Or maybe, the CLI can replace `yarn/npm install has failed` with something more indicative in this scenario.

![image](https://user-images.githubusercontent.com/62678592/217464204-f8602364-806b-41f7-a995-f0e5bed8cc2f.png)

**Comment by chris-olszewski** [comment]
I'm closing this as we already call out that [workspaces are symlinked](https://turbo.build/repo/docs/handbook/workspaces#managing-workspaces) and I think it would be too fragile to depend on the error logs of yarn and npm.
