### ISSUE TITLE
[turborepo] Problems setting up storybook

### ISSUE THREAD

**Issue by StevenBendell** [vercel/turbo#3620]
### What version of Turborepo are you using?

1.7.2

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

I'm trying to setup storybook in a fresh repo following the offical guide: https://turbo.build/repo/docs/handbook/tools/storybook

When I try to run the line pnpx sb init --skip-install I get the following error:
 ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for '/typescript/4.9.5' in pnpm-lock.yaml

### Expected Behavior

Storybook is initialized successfully

### To Reproduce

I've created a minimal reproducible case here:
https://github.com/StevenBendell/turbo-repo-test

Steps:
Create a fresh repo
Create vite project workshop
Add .npmrc as per guide
Try to run command

### Reproduction Repo

https://github.com/StevenBendell/turbo-repo-test

**Comment by tknickman** [comment]
Hey @StevenBendell thanks for the report. What version of pnpm are you using? I was able to run through the example without issue on my machine (macOS with `pnpm@7.24.3`). I'm guessing this is either a pnpm issue, or _maybe_ a windows issue.

**Comment by StevenBendell** [comment]
Hi @tknickman,

I've updated my pnpm (from 7.9.3) to 7.27.0 and after deleting my node modules folder and running pnpm install again it seems to be working again

Thanks

**Comment by tknickman** [comment]
Great, glad you could get up and running!

**Comment by bdenham** [comment]
Never mind. This problem occurred because I was using node 18+. Switching to node 16 was the fix. 

I'll leave the above in case others are searching for a solution.
