### ISSUE TITLE
[turborepo] platform 'linux s390x BE' not supported

### ISSUE THREAD

**Issue by aloxlamm** [vercel/turbo#3639]
### What version of Turborepo are you using?

1.7.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Other

### Describe the Bug

turbo is not supported for plaform linux s390x BE (IBM main frame)

/turbo/node-platform.js L19:

const knownUnixlikePackages = {
"darwin arm64 LE": "[turbo-darwin-arm64](https://linear.app/vercel/issue/TURBO-darwin-arm64)",
"darwin x64 LE": "[turbo-darwin-64](https://linear.app/vercel/issue/TURBO-darwin-64)",
"linux arm64 LE": "[turbo-linux-arm64](https://linear.app/vercel/issue/TURBO-linux-arm64)",
"linux x64 LE": "[turbo-linux-64](https://linear.app/vercel/issue/TURBO-linux-64)",
};

tried to run the linux x86 binary on the platform but rust execution fails

### Expected Behavior

would be highly appreciated if you could add support for linux s390x BE

### To Reproduce

run on platform linux s390x BE:
$ npm install -g turbo

**Comment by runlevel5** [comment]
Love to see ppc64le get supported too.

**Comment by anthonyshew** [comment]
It also doesn't look like there was much interest here after over a year. Per our [Support Policy](https://turbo.build/repo/docs/support), we don't intend to support this platform so going to close this.
