### ISSUE TITLE
UI library (based on Turbo design system template) not tree shakeable in nextjs. 

### ISSUE THREAD

**Issue by williamlmao** [vercel/turbo#3667]
[Reproducible Example](https://github.com/williamlmao/chimera-tw)
* `pnpm run dev --filter=docs` to see the below build page sizes.

I noticed that every time I added new components to my ui library, the bundle sizes of the pages all grew larger. 

So I tested named vs default exports in a few pages, and here's what I found. 
```

docs:build: ├ ○ /docs/MuiTreeShakeTest1                3.38 kB         198 kB  (imported a button + slider from MUI, using default imports)
docs:build: ├ ○ /docs/MuiTreeShakeTest2 (673 ms)       5.57 kB         200 kB (imported a button + slider + switch from MUI, using named imports)
docs:build: ├ ○ /docs/MuiTreeShakeTest3 (655 ms)       3.36 kB         190 kB.  (imported a button  from MUI, using named imports)
docs:build: ├ ○ /docs/TestPopOnly                      1.09 kB         213 kB  (Imported a only Popover from my UI library using named import)
docs:build: ├ ○ /docs/TestPopWithOther                 1.57 kB         213 kB (Imported a only Popover + 3 other components from my UI library using named import)
```

You can see that in TestPopOnly and TestPopWithOther, the bundle size was the same despite different amount of components being imported. 

It looks like tree shaking was working fine with MUI, so I don't think it's a problem with nextjs. 

I have kept up the setup from the [turborepo design system](https://github.com/vercel/turbo/tree/main/examples/design-system) mostly the same. 

A ui package, with all components being exported from index.ts in /src. The only thing I really changed was updating tsup and adding the `--treeshake` flag to it, but that didn't do much. 

Any help would be appreciated!

_Originally posted by @williamlmao in https://github.com/vercel/turbo/discussions/3665_

**Comment by williamlmao** [comment]
@tknickman thank you so much for the response! I was able to get it working after looking at that example.

For anyone who runs into this in the future, I just copied the tsup config file and also updated my package json to be nearly the same, and then it worked!

**Comment by tknickman** [comment]
Awesome, glad you got it working! I made a note to update the rest of the examples that are building their UI package independently of the app as well.

**Comment by MathiasPawshake** [comment]
> Hey @williamlmao, yep you're right - because we're compiling this lib to cjs we won't be able to treeshake it - you'll need to use esm for that. We did recently update the tailwind example to support a treeshakable ui lib -
> 
> https://github.com/vercel/turbo/blob/main/examples/with-tailwind/packages/ui/tsup.config.ts#L7

Hi @tknickman, we are facing a similar issue regarding the tree shaking. You mentioned in your comment above that the lib is only compiled to `cjs` but when I look at the build command `"build": "tsup --treeshake src/index.tsx --format esm,cjs --dts --external react --minify"` I can clearly see that `esm` is also requested when building or am I missing something?
