### ISSUE TITLE
[turborepo] turbo creates a broken pnpm-lock.yaml

### ISSUE THREAD

**Issue by Marwennnne** [vercel/turbo#3672]
### What version of Turborepo are you using?

1.7.2

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Running `pnpm prune` after `pnpm i` at the root level will produce a broken lockfile.
This behavior is leading to this error  `ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY` 

### Expected Behavior

lockfile should be correct

### To Reproduce

To reproduce the bug
```
1. git clone git@github.com:Marwennnne/turbo-prune-missing-dep.git
2. cd turbo-prune-missing-dep
3. pnpm i 
4. turbo prune --scope=web --docker
5. mv out/pnpm-lock.yaml out/json/pnpm-lock.yaml
6. cd out/json && pnpm install --frozen-lockfile --strict-peer-dependencies
```
But when I delete the `node_modules` at the root level and I rerun the commands `4,5 and 6` lockfile is produced correctly meaning I should not install dependencies at the root level

### Reproduction Repo

git@github.com:Marwennnne/turbo-prune-missing-dep.git

**Comment by chris-olszewski** [comment]
Hi @Marwennnne, thanks for the report. I just tested your repro #3611 and #3656 combined fix the issue. I'll try to get a patch out ASAP with these changes. Sorry for the disruption.

**Comment by chris-olszewski** [comment]
Please upgrade to `1.7.4` and reopen if the issue persists.
