### ISSUE TITLE
[turborepo] link not allowing team selection

### ISSUE THREAD

**Issue by shawnmcknight** [vercel/turbo#3728]
### What version of Turborepo are you using?

1.7.4

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

When running `turbo link` you are presented with a list of Vercel teams.  I am no longer able to use the arrow keys to choose a team and cannot figure out a way to select a team other than the first in the list.  This appears to be a regression since I can get it to work with 1.7.0.

### Expected Behavior

Allows use of arrow keys to choose other teams.

### To Reproduce

I'm not sure if this is a windows only problem or not.  However, I'm using Windows.  The steps are simply:
* `npx turbo link`
* Answer yes to enabling remote caching
* Cannot use arrow keys to choose another team at the next prompt

**Comment by chris-olszewski** [comment]
@shawnmcknight What terminal are you using?

**Comment by shawnmcknight** [comment]
@chris-olszewski Interesting, I hadn't even thought of this.

I am using cmder (https://cmder.app/) using a `cmd` terminal.  The arrow keys are not working in that environment, but if I run `cmd` directly then the arrow keys are working properly.  If I switch back to version `1.7.0` of turbo then the keys work properly in the cmder environment.

**Comment by chris-olszewski** [comment]
Interesting, there's a known issue with the library we use to get user input and [`mintty`](https://github.com/console-rs/console/issues/35) and I wonder if `cmder` hits a similar snag. I'll see if there's a way we can code around this, but in the meantime I'll suggest using a raw `cmd` for `turbo link`. Sorry for the inconvenience.

**Comment by shawnmcknight** [comment]
@chris-olszewski No problem, that workaround is fine.  Thanks for responding so quickly!

**Comment by anthonyshew** [comment]
Closing here as a lot has changed in the past year! 😄 Please feel free to open a fresh issue if you are still seeing this problem.
