### ISSUE TITLE
Turbo error: While parsing config: unexpected end of JSON input [turborepo] 

### ISSUE THREAD

**Issue by AbuBakrBenMhenni** [vercel/turbo#3764]
### What version of Turborepo are you using?

1.7.4

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

I am encountering an issue while working on a new project in TurboRepo. Despite creating a fresh new project, I am unable to build or develop it. When I run `pnpm run build` or `pnpm run dev` it crashes immediately with `Turbo error: While parsing config: unexpected end of JSON input`

I have tried several troubleshooting steps, such as checking for updates to TurboRepo, reinstalling dependencies, and checking for compatibility issues with my system, but the problem persists.

This issue is impacting my ability to work on the project and is causing delays. I would greatly appreciate any assistance in resolving this issue so that I can proceed with my work.

![image](https://user-images.githubusercontent.com/78960201/218416221-95cc4280-ea9e-46ef-85e5-41d9cbe5525f.png)
![image](https://user-images.githubusercontent.com/78960201/218416844-b91be7b4-9e6e-4084-b50d-b59efd7fe410.png)

### Expected Behavior

It should build or run dev successfully.

### To Reproduce

![image](https://user-images.githubusercontent.com/78960201/218419297-ef2b5451-3bea-40e3-a30b-642cc796e583.png)

![image](https://user-images.githubusercontent.com/78960201/218419445-9fd6c9fa-318b-4985-9311-a59dc7d97ba1.png)

**Comment by tknickman** [comment]
Hmm, I just attempted to reproduce this but wasn't able to (on M1 Mac with `pnpm@7.27.0` and `turbo@1.7.4`)

This is possibly related to an issue with your user config file - can you check and see if you have a file at `$HOME/.config/turborepo/config.json`, and if the JSON looks valid?

If that's got issues, there's a chance this is a new bug introduced as part of the new login process (cc @NicholasLYang)

**Comment by AbuBakrBenMhenni** [comment]
> Hmm, I just attempted to reproduce this but wasn't able to (on M1 Mac with `pnpm@7.27.0` and `turbo@1.7.4`)
> 
> This is possibly related to an issue with your user config file - can you check and see if you have a file at `$HOME/.config/turborepo/config.json`, and if the JSON looks valid?
> 
> If that's got issues, there's a chance this is a new bug introduced as part of the new login process (cc @NicholasLYang)

Is it normal for the `$HOME/.config/turborepo/config.json` file to be empty?

**Comment by AbuBakrBenMhenni** [comment]
I was able to resolve the issue by deleting the file located at `$HOME/.config/turborepo/config.json`. I am not sure how the file became empty. Maybe it happened after a turbo update.

**Comment by tknickman** [comment]
Hmm interesting, we'll take a look - thanks for the report and glad you're up and running again!
