### ISSUE TITLE
[turborepo] workspaces config evaluation

### ISSUE THREAD

**Issue by stropho** [vercel/turbo#3766]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

`turbo` reads the **workspaces** config used by `yarn` but isn't able to mach the same packages as `yarn`. This issue appeared specifically with negative glob patterns.

### Expected Behavior

`turbo` should match the same workspaces as `yarn` does

### To Reproduce

Usual setup in `package.json`
```
  "workspaces": {
    "packages": [
      "packages/*"
  ]}
```

Specific setup skipping a single package 
```
  "workspaces": {
    "packages": [
      "packages/!(excluded-package)"
  ]}
```

`turbo` **does not match anything** in the `packages/` folder

**Comment by mehulkar** [comment]
This looks like a bug, thanks for the report @stropho! It looks like we support `!ignore` patterns when using [`pnpm`][1], but not with [npm][2] or [yarn][3]. For `yarn`, I can't tell from [the docs][4] _what_ exactly is supported, but the `yarn workpaces list` command does seem to exclude workspaces that are ignored.

That said, I'm not too familiar with yarn, but in yarn@3 at least, I think the config you showed is not correct. Verified with `yarn workspaces list`, and I think it should be:

```diff
{
  "workspaces": [
    "packages/*",
+    "!packages/excluded-package",
-    "packages/!(excluded-package)",
  ]
}
```

[1]: https://github.com/vercel/turbo/blob/805a5ae14f1ab67f3c3e01e758f7b53d44f9d696/cli/internal/packagemanager/pnpm.go#L64-L68
[2]: https://github.com/vercel/turbo/blob/805a5ae14f1ab67f3c3e01e758f7b53d44f9d696/cli/internal/packagemanager/npm.go#L31-L39
[3]: https://github.com/vercel/turbo/blob/805a5ae14f1ab67f3c3e01e758f7b53d44f9d696/cli/internal/packagemanager/yarn.go#L35-L55
[4]: https://yarnpkg.com/features/workspaces

**Comment by stropho** [comment]
The most relevant info I could find about yarn@1 was in the [article about workspaces and hoisting](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/). It mentions the [glob pattern with minimatch](https://github.com/isaacs/minimatch) where `packages/!(excluded-package)` would be a valid pattern - and it works.  Honestly, it doesn't explicitly  say that minimatch is used for both `nohoist` and `packages` option 🤷

**Comment by chris-olszewski** [comment]
Just tried with Yarn v1 and `packages/!(excluded-package)` is not respected. It appears the article is misguided in suggesting that it supports the entirety of minimatch glob syntax.
