### ISSUE TITLE
An example without nextjs

### ISSUE THREAD

**Issue by AngeloCore** [vercel/turbo#3781]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Can you create an example without nextjs or any other web framework?
You can create a library example, e.g. if you have a nodejs library and just want to package/bundle it.
You can also create an example of how to package a nodejs project (not web related) into a single file, just like [vercel/ncc](https://github.com/vercel/ncc).

**Comment by mehulkar** [comment]
We have [a svelte example](https://github.com/vercel/turbo/tree/main/examples/with-svelte) and are open to contributions for the other ideas! cc @anthonyshew

**Comment by tknickman** [comment]
We have several non Next.js examples:

- [Kitchen Sink](https://github.com/vercel/turbo/tree/main/examples/kitchen-sink):
	- [Remix](https://github.com/vercel/turbo/tree/main/examples/kitchen-sink/apps/blog)
	- [Express](https://github.com/vercel/turbo/tree/main/examples/kitchen-sink/apps/api)
- [Design System](https://github.com/vercel/turbo/blob/main/examples/design-system)
	- [Storybook](https://github.com/vercel/turbo/blob/main/examples/design-system/apps/docs/package.json)
- [Docker](https://github.com/vercel/turbo/tree/main/examples/with-docker)
	- [Express](https://github.com/vercel/turbo/tree/main/examples/with-docker/apps/api)
- [Create React App](https://github.com/vercel/turbo/tree/main/examples/with-create-react-app)
- [Vite](https://github.com/vercel/turbo/tree/main/examples/with-vite)
- [Rollup](https://github.com/vercel/turbo/tree/main/examples/with-rollup)
- [React Native](https://github.com/vercel/turbo/tree/main/examples/with-react-native-web)
	- [Expo](https://github.com/vercel/turbo/tree/main/examples/with-react-native-web/apps/native)


New examples contributions are always welcome!
