### ISSUE TITLE
[turborepo] An basic example `File 'tsconfig/react-library.json' not found.ts`

### ISSUE THREAD

**Issue by matamatanot** [vercel/turbo#3783]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Pulling a repository created using https://vercel.com/templates/next.js/turborepo-next-basic causes an error in VScode because tsconfig is not resolved properly.

<img width="798" alt="スクリーンショット 2023-02-14 5 51 21" src="https://user-images.githubusercontent.com/39780486/218571819-7ab8be71-0137-4e13-b0e5-5b4d6622ea50.png">
<img width="795" alt="スクリーンショット 2023-02-14 5 51 40" src="https://user-images.githubusercontent.com/39780486/218572116-4e3cf672-0157-4716-bb85-ae4beeda9f4a.png">

### Expected Behavior

tsconfig is correctly resolved.

### To Reproduce

Deploy https://vercel.com/templates/next.js/turborepo-next-basic
Pull repository
check tsconfig

### Reproduction Repo

https://vercel.com/templates/next.js/turborepo-next-basic

**Comment by tknickman** [comment]
Just want to make sure you've ran a `pnpm install` after pulling the repository?

**Comment by adam993** [comment]
> Just want to make sure you've ran a `pnpm install` after pulling the repository?

I have the same issue, on Windows. Yes, I ran the npm install.

**Comment by aleciavogel** [comment]
Take a look at the version number when you run your package manager. I ended up having to go into `packages/tsconfig/package.json` to change from `"name": "tsconfig"` to `"name": "@my-project/tsconfig"` after I realized that some other package with the same name was being installed instead of this one.

You'll need to go to your apps and any other packages relying on `tsconfig` to swap to `@my-project/tsconfig` in their devDependencies in addition to updating the tsconfig in packages like `ui` and your apps.

**Comment by ps2goat** [comment]
I had the same symptoms as this, but the problem was that the same package was listed both under `dependencies` and `devDependencies` for the failing app's `package.json`. I'm not exactly sure how that happened, but I'm sure it was my fault 😅

I was using pnpm on WSL.

**Comment by jermatic** [comment]
same problem, been working to resolve all day, no success .. so frustrating

**Comment by jermatic** [comment]
I have it working in a different project, setup everything the same, no differences, still fails ... jesus

**Comment by jermatic** [comment]
why do people use turbo repo again? all i am getting is headaches on basic stuff

**Comment by jermatic** [comment]
i downgraded TS version in my app, but it says its still using the same TS version, but works ... make it make sense
![image](https://github.com/vercel/turbo/assets/134440575/f4ace60e-9cf5-402f-8bf2-bee0f491718d)
![image](https://github.com/vercel/turbo/assets/134440575/7c212fe7-b2cd-41de-aa71-b23167f9ab8e)

**Comment by tan911** [comment]
I started created a new monorepo and I think I have the same error with this

yarn version: 4.0.2
OS: windows 10

Quite confusing if the error all about tsconfig or eslint
![image](https://github.com/vercel/turbo/assets/92535526/8530250c-8538-41a2-af3b-4c31be8936a9)
![image](https://github.com/vercel/turbo/assets/92535526/f622b1ba-3911-483a-ad9e-2bfc95ba36a7)
![image](https://github.com/vercel/turbo/assets/92535526/2a84a66d-d64b-4779-bdf5-74d45baafe52)


when running yarn lint it throws an error
![lint](https://github.com/vercel/turbo/assets/92535526/860da4c0-c821-4e41-a29f-62ed7eb89580)

**Comment by anthonyshew** [comment]
We've put in a lot of work on our examples recently! Problems like these should be resolved. If you're still have a problem, please open a fresh issue!

**Comment by zsh77** [comment]
In my case when I pulled the example using ```npm``` , there were some typos related to the ```typescript-config``` package. 

I fixed it by making changes to ```tsconfig.json``` in the root of my monorepo:

![Screenshot 1402-11-28 at 2 17 39 in the afternoon](https://github.com/vercel/turbo/assets/44067788/6b2024a4-fb35-4be8-b9c9-518361046698)


I also had to rename ```config-typescript``` directory/package  to ```typescript-config``` resulted in looking like this:

<img width="619" alt="image" src="https://github.com/vercel/turbo/assets/44067788/46907844-79f8-4876-ae9c-e9d17c5f1cb3">

**Comment by RajuGangitla** [comment]
@tan911 did you found something for that

**Comment by PoonamMehan** [comment]
After following all the appropriate advices above, just restart your text editor (mine in Vs Code)
