### ISSUE TITLE
[turborepo] Starter produces an error

### ISSUE THREAD

**Issue by thany** [vercel/turbo#3797]
### What version of Turborepo are you using?

1.7.4

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

Running `npm run lint` after installing the starter, produces an error:

```
ui:lint: > ui@0.0.0 lint
ui:lint: > TIMING=1 eslint "**/*.ts*"
ui:lint:
web:lint:
web:lint: > web@0.0.0 lint
web:lint: > next lint
web:lint:
ui:lint: 'TIMING' is not recognized as an internal or external command,
ui:lint: operable program or batch file.
ui:lint: npm ERR! Lifecycle script `lint` failed with error:
ui:lint: npm ERR! Error: command failed
ui:lint: npm ERR!   in workspace: ui@0.0.0
ui:lint: npm ERR!   at location: C:\Projects\my-turborepo\packages\ui
ui:lint: ERROR: command finished with error: command (C:\Projects\my-turborepo\packages\ui) npm run lint exited (1)
web:lint: ✔ No ESLint warnings or errors
docs:lint: ✔ No ESLint warnings or errors
command (C:\Projects\my-turborepo\packages\ui) npm run lint exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    2.606s

 ERROR  run failed: command  exited (1)
```

### Expected Behavior

No error. Don't use commands that don't exist, or install something to make it work.

### To Reproduce

1. Install the starter: https://turbo.build/repo/docs/getting-started/create-new
2. Run `npm run lint`
3. Observe the error

**Comment by thany** [comment]
Worthy of note: I'm pretty sure how to fix this, but that's beside the point. The point is that the starter should work 'out of the box', no errors. So it should still be fixed in the starter package.

**Comment by mehulkar** [comment]
We're setting `TIMING=1` quite liberally in examples and in the `create-turbo` template. Will look into why that is before removing

**Comment by thany** [comment]
Or include cross-env to make it work everywhere 😊

**Comment by mehulkar** [comment]
@thany we talked about `cross-env` yesterday, but after looking into it and seeing that it [spawns another process](https://github.com/kentcdodds/cross-env/blob/3edefc7b450fe273655664f902fd03d9712177fe/src/index.js#L13) to set the env vars, we felt it wasn't worth the performance hit. @tknickman also pointed out that we include the [pro tip of setting this env var in our docs](https://turbo.build/repo/docs/core-concepts/caching#configuring-cache-outputs).

**Comment by thany** [comment]
All good and well, and I've briefly read through it to make sure I have some sort of understanding of how turbo handles environment variables.

It seems that we are confusing *including* already-set variables and *setting* variables with a value in the first place. Turbo.json appears to only do the former, whereas cross-env is responsible for the latter. So unless you can point me (and everyone else 😉) to a way to *set an environment variable with a value* in turbo.json, or any other built-in thing without using cross-env, I'd be all ears.

Other than that, I have no idea how to set *any* environment variable in a cross-platform manner, without the use of some sort of package like cross-env. The Linux syntax certainly won't work on Windows, that's for sure, and the Windows syntax doesn't work on Linux. Kind of the point why cross-env exists in the first place.
