### ISSUE TITLE
Make build output slightly less asynchronous

### ISSUE THREAD

**Issue by thany** [vercel/turbo#3801]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

The problem that this aims to solve is this build output excerpt:

```
docs:build:
docs:build: Route (pages)                              Size     First Load JS
web:build:
web:build: Route (pages)                              Size     First Load JS
docs:build: ┌ ○ /                                      299 B          73.3 kB
docs:build: └ ○ /404                                   181 B          73.1 kB
web:build: ┌ ○ /                                      298 B          73.3 kB
web:build: └ ○ /404                                   181 B          73.1 kB
docs:build: + First Load JS shared by all              73 kB
docs:build:   ├ chunks/framework-243845dae5bb80aa.js   45.2 kB
web:build: + First Load JS shared by all              73 kB
web:build:   ├ chunks/framework-243845dae5bb80aa.js   45.2 kB
docs:build:   ├ chunks/main-9661fe22a3744d55.js        26.8 kB
docs:build:   ├ chunks/pages/_app-03f04c30f397e7c8.js  196 B
web:build:   ├ chunks/main-9661fe22a3744d55.js        26.8 kB
web:build:   ├ chunks/pages/_app-03f04c30f397e7c8.js  196 B
web:build:   └ chunks/webpack-4e7214a60fad8e88.js     712 B
docs:build:   └ chunks/webpack-4e7214a60fad8e88.js     712 B
docs:build:
```

Can you see how this might be confusing? It's interleaving two outputs together that should be kept separate.

### Describe the solution you'd like

Somehow keep "blocks" of build output together. Maybe a way to indicate that a set of output lines should be kept together, i.e. not broken apart to be interleaved in with another set of output lines.

### Describe alternatives you've considered

Building packages one-by-one would make for a easier to read output, but that's doing away part of the whole point of turborepo.

**Comment by mehulkar** [comment]
We're tracking this in https://github.com/vercel/turbo/issues/219!
