### ISSUE TITLE
[turborepo] completion

### ISSUE THREAD

**Issue by malko** [vercel/turbo#3802]
### What version of Turborepo are you using?

1.7.4
- zsh version: 5.8.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

the turbo completion zsh generates a broken completion script for zsh.
If you use it any completion attempt after typing turbo in your zsh will result in: 

_arguments:comparguments:325: doubled rest argument definition: *::pass_through_args:

### Expected Behavior

having proper completion with the generated script under zsh

### To Reproduce

generate a completion script for zsh like this:
`turbo completion zsh > /usr/share/zsh/functions/_turbo`
open an new shell and try type `turbo` then hit space bar and then tab => see the error on stdout

**Comment by malko** [comment]
By the way didn't find any info on the completion command at the online documentation, only by performing a turbo --help

**Comment by malko** [comment]
replacing all `*::` and `*:::` by `::` seems to make it work, not sure it preserve all the functionality that was initially intended though.

**Comment by chris-olszewski** [comment]
This is an upstream issue with the library we use to generate completions. I'll be following https://github.com/clap-rs/clap/pull/4612 and bumping the dependency once the PR lands

**Comment by rayzr522** [comment]
bump on this! looks like https://github.com/clap-rs/clap/pull/4612 has been merged and released, it's fixed in clap_complete v4.1.3+ -- I know this is just a small DX issue and not super urgent but would love to see a quick version bump for this!! :3

**Comment by AlexAegis** [comment]
This PR might be related, and it landed in clap 4.3.0 https://github.com/clap-rs/clap/pull/4899
