### ISSUE TITLE
[turborepo] error with turbo link

### ISSUE THREAD

**Issue by jakst** [vercel/turbo#3807]
### What version of Turborepo are you using?

1.7.4

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

When running  `turbo link`, I get this error message.
> \>\>\> Remote Caching
  Remote Caching shares your cached Turborepo task outputs and logs across
  all your team’s Vercel projects. It also can share outputs
  with other services that enable Remote Caching, like CI/CD systems.
  This results in faster build times and deployments for your team.
  For more info, see https://turbo.build/repo/docs/core-concepts/remote-caching
>
>  ? Would you like to enable Remote Caching for ~/code/my-project yes
  ERROR error: could not get team information

I already ran `turbo login` to grant the CLI access, and I have verified that there is a json token payload in `~/Library/Application\ Support/turborepo/config.json`.

### Expected Behavior

Running `turbo link` should link my project to the remote cache.

### To Reproduce

Not sure, except for running `turbo login` and `turbo link` in a project connected to vercel via git integration.

**Comment by anthonyshew** [comment]
This issue is quite old and I we've done some work around these commands so I'm going to close here. If you're still seeing a problem, please open a new issue!
