### ISSUE TITLE
Support for non-JS projects

### ISSUE THREAD

**Issue by youssef-ahamid** [vercel/turbo#3815]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Is it possible to add support for non-JS projects? 

### Describe the solution you'd like

I want to add a package.json with the appropriate scripts in any non-JS project and include it in my pipeline, cache, etc.

### Describe alternatives you've considered

I wrote a bash script so i can execute the same pipeline as a single process - lead to a lot of duplicated effort and is not pretty

**Comment by mehulkar** [comment]
@youssef-ahamid this should be possible. For example, the `cli/` workspace in _this_ repo has a `package.json` and we can execute its scripts through turbo. https://github.com/vercel/turbo/tree/main/cli. Just make sure that your package.json has a `name`, and at the root of your monorepo the workspace is included in your workspaces configuration.
