### ISSUE TITLE
[turborepo] Error using node:18-alpine Docker image: thread 'main' panicked at 'Failed to execute turbo...'

### ISSUE THREAD

**Issue by elliottsj** [vercel/turbo#3822]
### What version of Turborepo are you using?

1.7.4

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

When installing and running Turborepo in a [`node:18-alpine` Docker container](https://hub.docker.com/_/node), this error is raised upon running `./node_modules/.bin/turbo`:

```
thread 'main' panicked at 'Failed to execute turbo.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/turborepo/src/main.rs:50:10
```

### Expected Behavior

Executing `./node_modules/.bin/turbo` should not exit with this 101 error.

### To Reproduce

```
$ docker run -it --entrypoint /bin/sh node:18-alpine
/ # mkdir app
/ # cd app
/app # npm install turbo@1.7.4

added 2 packages in 3s
npm notice
npm notice New minor version of npm available! 9.3.1 -> 9.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.5.0
npm notice Run npm install -g npm@9.5.0 to update!
npm notice
/app # ./node_modules/.bin/turbo
thread 'main' panicked at 'Failed to execute turbo.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/turborepo/src/main.rs:50:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
/app # echo $?
101
```

**Comment by elliottsj** [comment]
I was able to resolve this using the `-slim` image instead. This was a useful post: https://medium.com/swlh/alpine-slim-stretch-buster-jessie-bullseye-bookworm-what-are-the-differences-in-docker-62171ed4531d

Found this helpful comment: https://github.com/vercel/turbo/blob/dd85f00f8efc6bd2c78f6b0106a0e409992d6141/examples/with-docker/apps/api/Dockerfile#L5

Closing for now, but perhaps it would be helpful for Turborepo to produce a more helpful error message if it's installed on a system where libc6-compat is missing.

**Comment by alitnk** [comment]
For future viewers: I just had this issue and adding `RUN apk add --no-cache libc6-compat` to the Dockerfile fixed it. So, no need to reach out for slim. ([reference](https://turbo.build/repo/docs/handbook/deploying-with-docker#example))
