### ISSUE TITLE
[turbopack] Node process executed without process environment variables set

### ISSUE THREAD

**Issue by 3c1u** [vercel/turbo#3876]
### What version of Turbopack are you using?

turbopack-230213.2

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

`process.env` has no shell variables when `next.config.js` is loaded inside `next-dev`.
I'm using turbopack from Next.js.

### Expected Behavior

`process.env` should have variables given from the shell.

### To Reproduce

1. Clone the repository.
2. `pnpm i && pnpm dev:turbo`
3. Open `http://localhost:3000/client-side` and you'll see the hydration error.
4. Set `kNextConfigCheckIfEnvIsDefined` to `true` in `next.config.js` and restart the server.
5. Open `http://localhost:3000` and you'll see the server crash.

These errors do not occur in the normal `next dev`.

I made a workaround for this but I'm not sure if this is safe (as `execute()` is called in many places).
https://github.com/3c1u/turbo/tree/fix-process-env-turbopack-node
With this patch, those errors will disappear.

### Reproduction Repo

https://github.com/3c1u/nextjs-env-injection

**Comment by jridgewell** [comment]
Hi @3c1u! We're aware of this, but haven't fixed it yet (tracking as WEB-517, but it's internal so you won't be able to read it). You're fix is nearly correct, but the actual fix requires a lot of plumbing of an `ProcessEnvVc` from https://github.com/vercel/turbo/blob/cda81f62564e0b57347d1f4010848be1add618f3/crates/next-core/src/page_source.rs#L225 down to the `get_renderer_pool` calls.

**Comment by 3c1u** [comment]
Thank you for the details! Looks like there are a lot of things to do 🤔

Is there any plan to fix this? I'm willing to help solving this issue!

**Comment by jridgewell** [comment]
> Is there any plan to fix this? I'm willing to help solving this issue!

Yes, we definitely want to fix, but it just hadn't been prioritized yet. I'd love it if you fixed it!

We have 2 starting points:
1. https://github.com/vercel/turbo/blob/cda81f62564e0b57347d1f4010848be1add618f3/crates/next-core/src/page_source.rs#L225
2. https://github.com/vercel/turbo/blob/cda81f62564e0b57347d1f4010848be1add618f3/crates/next-core/src/app_source.rs#L308

We'll need that `env_for_js` returned `ProcessEnvVc` as variable. We'll need to pass that variable through function calls to the `create_node_rendered_source` in both of those files. From there, we can update `create_node_rendered_source`'s returned `NodeRenderContentSource` to hold onto the `ProcessEnvVc`, and pass it to the `render_static` call. From there, pass it to `get_renderer_pool`. And finally, we can `env.await?`, and pass that to the `NodeJsPool::new`.

**Comment by ForsakenHarmony** [comment]
Hey @3c1u, didn't see you're willing to help out, fixed it myself because I needed it for another problem.

Hope you didn't start working on it so far :/

**Comment by 3c1u** [comment]
@ForsakenHarmony, thank you for fixing this issue! Luckily, I haven't worked on it yet.
@jridgewell, thanks for the explanation! (Sorry for the late response!)
