### ISSUE TITLE
Parceljs Comparison

### ISSUE THREAD

**Issue by t-botz** [vercel/turbo#3883]
### Which project is this feature idea for?

Turbopack

### Describe the feature you'd like to request

Parceljs seems to be a direct competitor to turbopack. Based on github stars, its also more popular.

I would love to see in the turbopack documentation and benchmark how it compares.

Parceljs is on its side started to [compare itself to turbopack](https://parceljs.org/blog/v2-8-0/#hmr-rebuild-performance)

### Describe the solution you'd like

Put parcel in the documentation and benchmark the same way it has been done for webpack and vite.

### Describe alternatives you've considered

-

**Comment by timneutkens** [comment]
We're currently only comparing Next.js with webpack against Next.js with Turbopack.
