### ISSUE TITLE
[turborepo] CTRL+C makes terminal freeze

### ISSUE THREAD

**Issue by b12k** [vercel/turbo#3911]
### What version of Turborepo are you using?

1.8.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

Turborepo doesnt handle `ctrl+c` properly.
When aborting a long running or `persistent: true` task using `ctrl+c` windows terminal stops responding (cmd, powershell, git-bash, cmder).

### Expected Behavior

Terminal remains interactive after `ctrl+c` process termination.

### To Reproduce

```shell
npx create-turbo@latest turbobug
# choose any package manager (pnpm in example)
cd turbobug
pnpm dev
# try terminating the process using CTRL+C
```
![shot_230222_132534](https://user-images.githubusercontent.com/10243265/220619163-9450355e-8c73-454d-8fd6-4df50498be3a.png)

**Comment by cuppachino** [comment]
Same happens for me with 1.8.2, windows, pnpm. The "workaround" is to send Y twice.

Y + enter
Y + enter

**Comment by b12k** [comment]
@cuppachino 
Unfortunately terminal is not interactive and no longer accepts any kind of input

**Comment by cuppachino** [comment]
> @cuppachino Unfortunately terminal is not interactive and no longer accepts any kind of input

Gotta go turbo 🤠🐎

**Comment by b12k** [comment]
Still present in v1.8.3

**Comment by Ahmadh26** [comment]
can confirm still occuring in 1.8.3 on windows 11 
commented more details on #3427

**Comment by arlyon** [comment]
Thanks for the report. I am going to close this in favour of #3427 so we can track it in one place! :)
