### ISSUE TITLE
[turborepo] 404 for https://turbo.build/repo/core-concepts/monorepos/filtering

### ISSUE THREAD

**Issue by githubcdr** [vercel/turbo#3922]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Website URL https://turbo.build/repo/core-concepts/monorepos/filtering is a 404

### Expected Behavior

200

### To Reproduce

Visit https://turbo.build/repo/core-concepts/monorepos/filtering

**Comment by mehulkar** [comment]
@githubcdr thanks for the report! Where did you come across the URL so we can update it to https://turbo.build/repo/docs/core-concepts/monorepos/filtering ?

**Comment by githubcdr** [comment]
https://turbo.build/repo/docs/installing on filtering

**Comment by mehulkar** [comment]
Thank you!
