### ISSUE TITLE
Global Environment Variables from Root or via a "Package"

### ISSUE THREAD

**Issue by anricoj1** [vercel/turbo#3928]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

I feel as though many users would greatly benefit from more helpful docs on ["Using environment variables"](https://turbo.build/repo/docs/handbook/environment-variables).

The only suggestion is to install `dotenv-cli` and add it infront of the script like `"dev": "dotenv -- turbo dev"`.

I'm currently working on adding `prisma` to to my monorepo for a shared db client. The turborepo docs on adding prisma are helpful but not in regards to environment variables like the `DATABASE_URL`.

### Describe the solution you'd like

I feel like more suggestions for having a shared .env config in your monorepo would be ideal. 

Regardless of how this is handled via a "package" in the monorepo or using a `.env` file from root without having to manage `dotenv-cli` especially when having multiple .env files like
- `.env.local`
- `.env.local.development`
- `.env.local.production`

This would be a great out of the box feature since people usually need some .env managment ESPECIALLY in a monorepo.

### Describe alternatives you've considered

I feel as though my [Describe the solution you'd like] section hits this point already.

I've tried using the recommended `dotenv-cli` approach from the docs and it doesn't work for my use case.

This is the approach I tried using my .env file from root with prisma and turbo:
In root **package.json**:
`"db:migrate": "dotenv -e ./env -- turbo db:migrate"`

In **packages/database/package.json**:
`"db:migrate": "prisma migrate dev --name init"`

Running `npm run db:migrate` from root gives me this error message:

`database:db:migrate: error: Environment variable not found: 
DATABASE_URL.`

I understand that this could potentially be labeled as an issue with prisma. But, the question still stands for managing environment variables throughout your turborepo

**Comment by anricoj1** [comment]
@mehulkar Correct I was hoping running `db:migrate` via the `turbo` CLI and it would make `DATABASE_URL` available where it's needed. 

I think adding more guidance in the docs on managing environment variables across your turborepo would be very helpful.

I'm using my current issue as an example for managing environment variables throughout my turbo repo. I have a `.env.local.development` file in the root of my project. I would like to be able to use it throughout all of my projects in my turborepo.

Is it better practice to:
1. Give each app their own `.env` files.
2. Create a `env` package inside the `packages/` dir.
3. Use `dotenv-cli` Infront of every `turbo` command.

It would be great if turbo could handle this out of the box or at least provide an opt in via `npx create-turbo@latest` to configure `dotenv-cli` for you.

As the template already provides you with example `eslint` `tsconfig` and `ui` packages it would be cool to see an example `env` package

**Comment by bchilcott** [comment]
+1: It's also not clear in the [with-prisma](https://github.com/vercel/turbo/tree/main/examples/with-prisma) example that the env solution there won't work on windows (unless I've done something horribly wrong).

The best alternative seems to be adding 'dotenv -e ../../.env' to each script, which feels like a bit of a hack, especially when you have a lot.

If there is a better way it doesn't seem to be documented, and if there isn't it seems like some kind of automatic solution would be a valuable improvement.

**Comment by mehulkar** [comment]
Does https://github.com/vercel/turbo/pull/4406 go far enough for you? I'd be happy to review a PR for where you think some extra material could go if you want to start one up! I'm guessing somewhere in the Monorepo Handbook is a good idea.

**Comment by bchilcott** [comment]
> Does #4406 go far enough for you?

Ah, didn't realise that had been merged at the same time I was having the problem.. It looks like the `../../.env` thing is the best option we've got atm so having that documented is good. If I think of something better I'll open a PR for it, but handling global env vars should be the monorepo tool's job ultimately, imo.

**Comment by andrevenancio** [comment]
Just wanted to share my thoughts. I think having some common environment variables to the whole monorepo is useful, however, as you know, in a monorepo with multiple applications where we can specify an app and a vercel project its more useful to have environment variables local to the application itself. I've tried to add `.env.local` to my apps/my-application and I can't get the variables to work. I could add all my environment variables to the root of the monorepo but that's not ideal. some env variables might be called the same and I dont want to be filtering which variables I'm interested.

Is there a solution I can use to avoid going down the path of

```
// .env
APPLICATION1_GRAPHQL=...
APPLICATION2_GRAPHQL=...
APPLICATION3_GRAPHQL=...
```

**Comment by chihab** [comment]
@andrevenancio could this package help?

https://github.com/chihab/dotenv-run

**Comment by xmlking** [comment]
[@dotenv-run/cli](https://github.com/chihab/dotenv-run) had nice feature needed for turbo repo:
 
Supports hierarchical cascading configuration in monorepo projects ([Nx](https://nx.dev/), [Turbo](https://turbo.build/), etc.) apps/next-app/.env > apps/.env > .env

but missing support for multiple custom .env files 

https://github.com/chihab/dotenv-run/issues/15

**Comment by andrevenancio** [comment]
I think the whole way turborepo is handling environment variables along side the vercel cli is not well though through.

So lets consider this, we have a monorepo with 2 applications `app-a` and `app-b`. On vercel we create 2 separate applications and we link them accordingly:

`apps/app-a` for `app-a` and
`apps/app-b` for `app-b`

We open vercel `app-a` application, add a few env variables and then we change to the `app-b` and add a few other variables.

Before I can run `vercel env pull` on my local machine I need to do `vercel link`. When we link we need to choose what application we're linking to. Either `app-a` or `app-b`. At this point running `vercel env pull` pulls the environment variables to a `.env.local` on the root of the monorepo and those variables are refering to `app-a` which is the app we linked. Those environment variables defined on `.env.local` can be propagated to all other `apps` and `packages` on turborepo if we add

```
"globalDotEnv": [".env.local"],
```

to the `turbo.json` file.

Now this means that if we're testing `app-a` we have our env variables, but if we are testing `app-b` we're out of luck and you will have to do `vercel link` again, pointing to `app-b`, and then do `vercel env pull` to get the env variables used on `app-b`.

I would expect maybe that doing `vercel env pull` will pull a specific .env.local to each of the apps that have been added as Projects on vercel So I would have
```
apps
  app-a
    .env.local
  app-b
    .env.local
packages
  ...
```
Instead of

```
apps
  app-a
  app-b
packages
.env.local
  ...
```

**Comment by xmlking** [comment]
> "globalDotEnv": [".env.local"],
Not sure if turbo command currently can   load above  env variables into process.env when run:

turbo run dev —filter=apps/web 

other idea is to have common .env at project root level and per-subproject .env in apps/web level.
When we rung turbo command , it should merge hierarchical .env files and make them available to process.env

**Comment by andrevenancio** [comment]
Hi @xmlking thanks for your reply.

So would you do the `vercel link` inside each of the different apps you want to pull the .env from?

Following my structure in the example above

```
cd apps/app-a && vercel link
// follow the steps to link to the app on vercel called "app-a"
```
And then do
```
cd ..
cd app-b && vercel link
// follow the steps to link to the app on vercel called "app-b"
```

And that "links" you to the 2 applications so you can run `vercel env pull` from inside each folder and get the environment variables relating to that app only?

**Comment by xmlking** [comment]
@chihab  generously added turborepo support with some additional features  I requested:  https://dotenv.run/
this is how I am using it  in `apps/console/package.json`
```json filename="package.json"  
{
	"scripts": {
		"dev": "dotenv-run -p .env,.secrets -- vite dev",
		"build": "dotenv-run -p .env,.secrets -- vite build",
		"preview": "dotenv-run -p .env,.secrets -- vite preview",
	}
}
```
in debug mode, it loads env files like this 

<img width="444" alt="image" src="https://github.com/vercel/turbo/assets/627951/b2351662-f63f-4d03-aca3-782c86afa405">

**Comment by anthonyshew** [comment]
We've updated our environment variable guidance in new documentation: https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables

**Comment by sajadmh** [comment]
The new documentation is helpful but easy to miss when searching for Vercel build error messages that don't occur in local dev.

For example:

```web:build: Error: WORKOS_REDIRECT_URI environment variable is not set
web:build:     at r (/vercel/path0/apps/web/.next/server/chunks/2071.js:20:32761)
web:build:     at 88988 (/vercel/path0/apps/web/.next/server/chunks/2071.js:20:33174)
web:build:     at t (/vercel/path0/apps/web/.next/server/webpack-runtime.js:1:128)
web:build:     at 12686 (/vercel/path0/apps/web/.next/server/chunks/2071.js:23:6987)
web:build:     at t (/vercel/path0/apps/web/.next/server/webpack-runtime.js:1:128)
web:build:     at 45211 (/vercel/path0/apps/web/.next/server/chunks/2071.js:20:30800)
web:build:     at t (/vercel/path0/apps/web/.next/server/webpack-runtime.js:1:128)
web:build:     at 72071 (/vercel/path0/apps/web/.next/server/chunks/2071.js:23:2607)
web:build:     at t (/vercel/path0/apps/web/.next/server/webpack-runtime.js:1:128)
web:build:     at 42212 (/vercel/path0/apps/web/.next/server/chunks/9550.js:17:13171)
web:build: 
web:build: > Build error occurred
web:build: Error: Failed to collect page data for /analytics
web:build:     at /vercel/path0/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_@opentelemetry+api@1.8.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.6/node_modules/next/dist/build/utils.js:1268:15
web:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
```

The environment variable is set in the Vercel project and locally in the app/package, but it wasn't clear that 'environment variable is not set' referred to the root turbo.json and needed to be added under 'globalEnv' or 'env'.

**Comment by landsman** [comment]
I am suprised as well. This is annoying.

**Comment by jjmilburn** [comment]
It seems like `globalDotEnv` would have worked perfectly fine for my use case. Now I have no idea from the docs what the equivalent substitute is, but I don't fancy putting separate .envs with the duplicate data in each repo. Any place in the docs for folks who might have previously found `globalDotEnv` a perfectly sound solution?

**Comment by xmlking** [comment]
> Am I reading this issue correctly? The way to handle shared env variables across packages and apps is to not share env variables across packages and apps?
> 
> Duplicating .env.dev files across apps and packages feels messy and prone to drifting.

  `.env` is not just secrets, it can hold some other public config like `theme`, `baseUrls`, `feature-flags` etc which we want to configure at runtime.  it would be nice to organize  monorepo level `.env` at root and `apps/web` , `apps/docs` level `.env` in its directories.  
for local development, this might easy way to split and organized large set of emveromnet variables

**Comment by xmlking** [comment]
I am surprised why **turborepo** team did not  integrated [@dotenv-run/cli](https://github.com/chihab/dotenv-run) like features natively into turbo CLI !

**Comment by MarkLee425** [comment]
Can the officials just offers us an well-structured example for that?
For example, in `/apps`, `web` (whatever frontend framework) and `server` (whatever backend framework), and some internal packages in `/packages`. Then demonstrate the environment variables sharing across apps and packages.

I believe doing this will be really helpful for developers to take as reference or getting started.

**Comment by MarkLee425** [comment]
IMO, I think having a config file or config.json for mapping the environment variables will be the most wanted solution for me, while my application needs shared environment variables but is simple. Like:
```
{
  "shared": string[],
  "app 1": string[],
   "app2": string[],
   "package 1": string[],
   ...
}
```
And use all of them from the `<root>/.env.*` will be good enough.
And for all frameworks like VITE, NEXT etc that is necessary to parse the env var with specific prefixes, add a configuration text or json (like shadcn component.json) inside packages like {type: "next"} and add the prefixes accordingly.

But I am not sure if it is doable or has any technical obstacles. Any other better recommendations?

**Comment by devhmac** [comment]
Can this thread be re-opened or point the group towards something that provides more clear guidance than the official docs linked really glazed of the actual complexity of the issue and does not provide any example intended structure? 

There are many large threads open on this exact same issue (see https://github.com/vercel/turborepo/discussions/9458) and none of the actually have a single clear recomended answer. 

@anthonyshew, you closed see this thread and the one above asking almost the exact same question, but there is still a ton of questioning going on in that thread post "answer" 

The Crux is - the docs **_unclearly_** state ["use env files in package"](https://turborepo.dev/docs/crafting-your-repository/using-environment-variables#use-env-files-in-packages) - without clarifying if this means **application** packages (`apps/`) or **all** packages (`packages/` included). And not providing clear guidance on the use of shared env values. 

Based on your answer in that thread it seems you are generally are stating [**packages =** `apps/` ](https://github.com/vercel/turborepo/discussions/9458#discussioncomment-11331608) - unless is some non-runtime/cli command needing an env like codegen. 

### The CORE question that I firmly believe remains unlear to much of the community - particularly around local development/.env file mangement. 

If I have an `application` and a `package` like below - if these two packages need the same envs for lets say base urls, 3rd party api secret tokens etc I see one of 3 real options
 
```
my-repository
├── apps
│   └── app-a
│   │   └── .env
│   │   └── package.json
│   └── app-b
│   │   └── .env
│   │   └── package.json
└── packages
│   └── shared-package ... (eg pretend shared TS business logic & 3rd party api calls)
│   │   └── .env
│   └── package-x...etc
│   │   └── .env
└── package.json
└── README.md
```
 
1. Packages have **no** envs referenced directly, and all code should essentially be written in a factory pattern which the `apps/` to construct and pass in the applications .env file. - mainly what is being proposed here https://github.com/vercel/turborepo/discussions/9458#discussioncomment-11443969
eg
```typescript
//packages/api-service/index.ts
export const createApiService = (config: EnvConfig) => {
  const apiClient = createApiClient(config)

  return {
    async getProduct(variables: ProductExampleQueryVariables) {
      const data = await apiClient.request(...)
      return data.product
    },
  }
}

export type ApiService = ReturnType<typeof createApiService>

//apps/web/clients/index.ts -- initializes factory
const EnvConfig = {
  clientKey: process.env.SOME_CLIENT_KEY,
  baseIUrl: process.env.API_BASE_URL
}

export const productService = createProductService(graphqlConfig)

```
2. every `package/` has its own .env file if it references any env value    - there are valid gripes above about this leading to drift, and frankly being a nightmare to maintain in a large project  
3. Use @kelvinsekx's approach https://github.com/vercel/turborepo/discussions/9458#discussioncomment-12368165
   - given packages generally dont have an independent runtime OUTSIDE of an application, reference env values directly in `packages/` code exactly like you would the consumeing application, **NO .env file in the `package`**. This has its own tradeoffs.
eg
```typescript // Get Base URL
//packages/api-service/index.ts
const BASE_URL = process.env.API_BASE_URL;
fetch(BASE_URL/etc,.....
// ----
//apps/website/.env
API_BASE_URL=https://<domain>
```

*4 - Bonus option I guess is repo root .envs which turbo explicitly recomends against in the docs. 

Can we just get a clear statement on this somewhere? Even if the answer is "Its the devs problem to deal with" thats a step, but I feel so much of the response to these questions appear to dodge making a recomendation or example on the actual complexity of the question at hand. 

Totally appreciate this is a novel and the topic has been belaboured, but I still see so many instances of the same question - and I have myself in an enterprise scale project we are trying to solution around. So would appreciate some clarity
