### ISSUE TITLE
Development tasks should support watch mode for re-running when "dependsOn" have changes in their "inputs"/"outputs"

### ISSUE THREAD

**Issue by NateRadebaugh** [vercel/turbo#3929]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

When creating a `dev` task in a pipeline that "dependsOn" `codegen` there is no automatic "watch mode" that will re-trigger the pipelines when the root "inputs" changes, eg a hypothetically `./codegen.config` file is manually edited.

```json
{
  "pipeline": {
    "dev": {
      "dependsOn": ["codegen"],
      "cache": false,
      "persistent": true
    },
    "codegen": {
      "inputs": ["./codegen.config"],
      "outputs": ["./codegen-outputs/**"]
    }
  }
}
```

### Describe the solution you'd like

To further improve development workflows, turbo should detect persistent nodes and apply "watch mode" to any dependencies in the related graph.

### Describe alternatives you've considered

I could write an explicit js script myself to watch for changes and re-trigger my "codegen" commands, but that is not ideal.

**Comment by mehulkar** [comment]
Thanks for the feedback! We're aware of this and are considering it!

**Comment by mehulkar** [comment]
Closing in favor of https://github.com/vercel/turbo/issues/986
