### ISSUE TITLE
[turborepo] [eslint-plugin-turbo] eslint-pugin-turbo can't read jsonc turbo.json

### ISSUE THREAD

**Issue by domdomegg** [vercel/turbo#3943]
### What version of Turborepo are you using?

v1.8.2

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

As per https://github.com/vercel/turbo/pull/3812, turbo.json can contain comments.

However, `eslint-pugin-turbo` has a rule `turbo/no-undeclared-env-vars` which attempts to find and read a `turbo.json` (to find env vars Turbo is aware of) with JSON.parse, which breaks with comments.

### Expected Behavior

`eslint-plugin-turbo` can handle turbo.json files with comments.

### To Reproduce

Follow turbo setup instructions

Add a comment to your turbo.json, e.g.

```jsonc
// this is a comment
{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
  },
}
```

Run `npx turbo lint`

**Comment by domdomegg** [comment]
Looking through the source code to try to fix this, it seems like @tknickman has already made the necessary code changes in https://github.com/vercel/turbo/pull/3846/files#diff-5e060cf84306ac1371af2dda2a506b709e04c0a4b6a11f43df6399b0fceee5cfR62

Looks like it might need a release of eslint-plugin-turbo to get this completed though.

**Comment by tknickman** [comment]
Hey @domdomegg, thanks for the repot. I'm taking a look at this, we should def support reading with jsonc in the plugin
