### ISSUE TITLE
Allow for skipping cache only if we match the most recent run

### ISSUE THREAD

**Issue by arturenault** [vercel/turbo#3948]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Currently, if there's a cache hit, a build step is totally skipped, with cached logs and artifacts being output.

This works great in most scenarios, but there are some scenarios where we want this behavior only if the cached output is from the most recent build.

For example, let's say I have a pipeline with two commands, `build` and `deploy`.

Most of the time, I do want both of the outputs of these commands to be cached. There's no point in running another build and deployment if the currently deployed code is the same as before.

But let's say I run `turbo run deploy` from a broken commit (B) today, after deploying from commit Ayesterday. If I try to run the command again from commit A, turbo just outputs the logs from when it ran on A and doesn't actually deploy.

### Describe the solution you'd like

I'd like an option in the build pipeline configuration that only uses the cache if the latest successful run on the same branch was successful.

Perhaps adding more options to the `cache` config would work, with this one being called something like `most-recent-only`. If that doesn't work, a `cache-strategy` config would work too.

### Describe alternatives you've considered

I could just disable caching on that step, but I'd be missing out on the benefits of skipping deployments 90% of the time.

We should also consider offering the ability to run arbitrary scripts to determine if something should be cached - this would enable many scenarios. But that's a big feature and this smaller one might be simpler to implement.

**Comment by nathanhammond** [comment]
I'm not sure how you have this configured, but if there are changes that have been made _and_ the `deploy` task isn't picking them up then you're omitting something that matters from the `deploy` task inputs, or you don't have the dependencies ordered correctly. (`deploy` should `dependsOn` `build`)

We do not—and will never—track caches in a time-ordered way. Caches are addressed by running a hash over the collection of inputs and designed to be reproducible across all environments, which provides no order guarantees.

If you share the image of your build and deploy steps (`--graph=out.png`) on our Discord somebody may be able to help you identify where exactly this is breaking down and how to think through a design that will accomplish your goals.

**Comment by arturenault** [comment]
I think my proposal might've been too specific and gone against turbo's design philosophy. A better question to get at what I'm looking for might be: how do you recommend handling rollbacks?

My setup is performing the way I'd like it to. The problem is that turbo makes it impossible to deploy a previous known good build because the deployment step will always be cached in that situation. Turbo will print cached logs saying the deployment completed, but my environment will still be running the newest (broken) build.

To avoid this as far as I know I'd need to either:
- Never cache my deployment step, meaning I perform unnecessary work on many deployments.
- Disable caching when deploying a rollback, meaning I lose the benefit of having a cached build.

This is an issue than any developer would face so it'd be great to get a feature that can handle this kind of situation while still getting all the benefits of turbo.

**Comment by nathanhammond** [comment]
In this case your deployment step has an uncacheable side-effect: performing the deploy. You're using cache presence to signify that the deploy is a no-op, but that's not _actually_ the signal for deploy being a no-op. Caches can be removed by doing `rm -rf node_modules/.cache` or `turbo logout` and cause a deploy you weren't necessarily expecting.

So yes: to determine if you should deploy you _must_ run the task every time. You can have a task before `deploy` that spits out a deploy key, and have the deploy task inspect that key, and the key that is currently in prod to determine if it should do anything. "Should I deploy" is a business logic decision and it's not something that can be replaced by a cache existence check.

If you wanted to use `turbo` to make the deploy key: `turbo deploy --dry=json --filter=app-name` will contain the hash of the task, which you could choose to use, but you could just as well use a GUID.
