### ISSUE TITLE
[turborepo] Filter Off Commit Range Including Unchanged Packages

### ISSUE THREAD

**Issue by joe-archie-producepay** [vercel/turbo#3965]
### What version of Turborepo are you using?

1.8.2

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Hello.

When using a commit range filter, unchanged packages are being added to the task graph. 

This appears to happen when changes in the range exist outside of a package.   

I've attempted to reproduce the issue in the Reproduction Repo linked below. 

### Expected Behavior

A commit range based filter evaluation of packages changed would match the `git diff` command output. 

https://github.com/vercel/turbo/blob/main/cli/internal/scm/git_go.go#L27-L56

### To Reproduce

1. Clone the reproduction repo. 
2. Checkout a branch off main 
3. Run turbo command with commit range filter between origin/main and current branch 
4. Verify no dependencies were added to graph 
5. Checkout test branch `test-filter-range` 
6. Run turbo command with commit range filter between origin/main and current branch 
7. Verify Root and ESconfig dependencies were added to the graph.   

```
git checkout -b test-off-main -q
turbo run build --filter=...\[origin/main...$(git branch --show-current)\]... --graph
git checkout test-filter-range
git --no-pager diff origin/main...test-filter-range --name-only
turbo run build --filter=...\[origin/main...$(git branch --show-current)\]... --graph
```
<img width="896" alt="image" src="https://user-images.githubusercontent.com/90059438/221378705-c32e6dcd-9b60-40f2-81b3-bb7729eaf6d3.png">

### Reproduction Repo

https://github.com/producepay/turboTest

<sub>[TURBO-2591](https://linear.app/vercel/issue/TURBO-2591/[turborepo]-filter-off-commit-range-including-unchanged-packages)</sub>

**Comment by morriq** [comment]
Observed something similar in our projects, 👍🏿

**Comment by mehulkar** [comment]
Update: I was able to reproduce this, even with the latest version of turbo. Didn't get a chance to look deeper yet

**Comment by mehulkar** [comment]
Additional details:

- The change between the branch and main is just one file `apps/database/readme.txt`: https://github.com/producepay/turboTest/compare/main...test-filter-range
- `eslint-config-custom` [is a root dependency][1], which is likely why it's showing up. So the real question is why `//` is showing up

[1]: https://github.com/producepay/turboTest/blob/7a1039b2c84707d0c3e2ce9a12d1edf7d08bb723/package.json#L16
