### ISSUE TITLE
Eslint rule very slow

### ISSUE THREAD

**Issue by wladiston** [vercel/turbo#3985]
### What version of Turborepo are you using?

1.8.2

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

The `turbo/no-undeclared-env-vars` rule is extremely slow on the `eslint-config-turbo@0.0.9`.

![image](https://user-images.githubusercontent.com/1843792/221658790-e70b46dc-12f3-4c7f-b629-4c3183a3a1f8.png)

### Expected Behavior

I reckon it shouldn't take that long

### To Reproduce

Just install the new version, and setup the `turbo.json` inside the project as introduced in the 1.8.2.

**Comment by tknickman** [comment]
Thanks for the report, this is definitely too slow. Will take a look.

**Comment by sneko** [comment]
Same, taking 30s instead of a few. My fault I used `latest` for this package... just fixed the version to `v0.0.8` and it's good now!

Thank you @wladiston for pointing that out :)
