### ISSUE TITLE
[turborepo] `npx @turbo/codemod update` throws an error

### ISSUE THREAD

**Issue by hymair** [vercel/turbo#4009]
### What version of Turborepo are you using?

1.8.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

after running `npx @turbo/codemod@latest update --force` :
``` 
WARNING: Git directory is not clean. Forcibly continuing...
? Where is the root of the repo to migrate? .
No codemods required to migrate from 1.8.1 to 1.8.3

Upgrading turbo from 1.8.1 to 1.8.3 (no codemods required)

Upgrading turbo with pnpm install turbo@latest --save-dev -w


Unexpected error. Please report it as a bug:
Error: Command failed: pnpm install turbo@latest --save-dev -w
    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)
    at Command.N (/Users/i/.npm/_npx/36146fcc85b26196/node_modules/@turbo/codemod/dist/cli.js:4:8282)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.parseAsync (/Users/i/.npm/_npx/36146fcc85b26196/node_modules/commander/lib/command.js:935:5) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer e2 80 89 45 52 52 5f 50 4e 50 4d 5f 48 4f 49 53 54 5f 50 41 54 54 45 52 4e 5f 44 49 46 46 e2 80 89 20 54 68 69 73 20 6d 6f 64 75 6c 65 73 20 64 69 72 ... 112 more bytes>,
    <Buffer >
  ],
  pid: 23255,
  stdout: <Buffer e2 80 89 45 52 52 5f 50 4e 50 4d 5f 48 4f 49 53 54 5f 50 41 54 54 45 52 4e 5f 44 49 46 46 e2 80 89 20 54 68 69 73 20 6d 6f 64 75 6c 65 73 20 64 69 72 ... 112 more bytes>,
  stderr: <Buffer >
}
```

### Expected Behavior

no error

### To Reproduce

Try the same command I suppose? `npx @turbo/codemod@latest update --force`

**Comment by tknickman** [comment]
Thanks for the report, will take a look. 

What error do you get from running the same command?
`pnpm install turbo@latest --save-dev -w`

We'll make some improvements on that error output as well to be a bit more clear.

**Comment by hymair** [comment]
`pnpm add -D -w turbo@latest` works fine, I used it to update turbo after I got the error from the other one.

**Comment by ludalex** [comment]
Having the exact same issue with the same setup (pnpm, Mac).

**Comment by tknickman** [comment]
Got, would you mind also sharing your pnpm version?

**Comment by hymair** [comment]
Mine is `7.28.0`

**Comment by mzavattaro** [comment]
I get this error when trying to update:
```npx @turbo/codemod@latest update --force
Need to install the following packages:
  @turbo/codemod@1.8.3
Ok to proceed? (y) y
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
? Where is the root of the repo to migrate? .
No codemods required to migrate from 1.8.2 to 1.8.3

Upgrading turbo from 1.8.2 to 1.8.3 (no codemods required)

/bin/sh: yarn: command not found
/bin/sh: pnpm: command not found
Migration failed
Unable to determine upgrade command

**Comment by dglazkov** [comment]
Getting the same error as @mzavattaro, but for a different version:

```
$ npx @turbo/codemod update
? Where is the root of the repo to migrate? .
No codemods required to migrate from 1.8.5 to 1.8.6 

Upgrading turbo from 1.8.5 to 1.8.6 (no codemods required) 

/bin/sh: yarn: command not found
/bin/sh: pnpm: command not found
Migration failed
Unable to determine upgrade command
```

**Comment by rodolfocerezo** [comment]
Same than @dglazkov 

```bash
npx @turbo/codemod update --force
? Where is the root of the repo to migrate? .
No codemods required to migrate from 1.8.2 to 1.8.8 

Upgrading turbo from 1.8.2 to 1.8.8 (no codemods required) 

Migration failed
Unable to determine upgrade command
```

**Comment by chapati23** [comment]
Same here, looks like missing an existence check for `pnpm` and `yarn` binaries?

<img width="881" alt="image" src="https://user-images.githubusercontent.com/117495/232023890-e57425ce-6c55-44bb-b6d8-f411f3abc395.png">

**Comment by mzavattaro** [comment]
The only work around I've found is to uninstall the Turbo package and reinstall it afterwards. From my experience it installs the latest update. This isn't a fix to the problem, as the same error will occur again.

You'll have to uninstall and reinstall to update to the latest version.

**Comment by tknickman** [comment]
@mzavattaro you can upgrade by installing `turbo@latest` with your package manager, that will work fine - but the benefit of using `@turbo/codemod` to upgrade is that we'll run any transforms required by the update automatically. 

I still haven't been able to repro this one - if anyone is able to create a reproduction repo and share it here I would be glad to take a deeper look (you can bootstrap a minimal example with `npx create-turbo@latest`)!

**Comment by dglazkov** [comment]
@tknickman my intuition is that this is about the state of the system, rather than a particular repo. For example, if I have yarn on pnpm installed, the codemod will just work.

(that's the workaround for me, btw: just install yarn)

**Comment by pureliumy** [comment]
Similar issue here, but the error was different.
```
? Where is the root of the repo to migrate? .
Migration failed
Unable to fetch the latest version of turbo
```

**Comment by ZeldOcarina** [comment]
> Got it, that's helpful - thank you @dglazkov! I think I have a lead on this now - I'll hopefully get a PR up today!

@tknickman I am having this issue too and I am using yarn, did you ever manage to add that PR?

**Comment by ivancuric** [comment]
Same error here:
```
Error: Command failed: pnpm install turbo@latest --save-dev -w
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at Command.I (/Users/ivan/.npm/_npx/b5f7626c653117ba/node_modules/@turbo/codemod/dist/cli.js:4:8282)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.parseAsync (/Users/ivan/.npm/_npx/b5f7626c653117ba/node_modules/commander/lib/command.js:935:5) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer e2 80 89 45 52 52 5f 50 4e 50 4d 5f 50 55 42 4c 49 43 5f 48 4f 49 53 54 5f 50 41 54 54 45 52 4e 5f 44 49 46 46 e2 80 89 20 54 68 69 73 20 6d 6f 64 75 ... 126 more bytes>,
    <Buffer >
  ],
  pid: 60073,
  stdout: <Buffer e2 80 89 45 52 52 5f 50 4e 50 4d 5f 50 55 42 4c 49 43 5f 48 4f 49 53 54 5f 50 41 54 54 45 52 4e 5f 44 49 46 46 e2 80 89 20 54 68 69 73 20 6d 6f 64 75 ... 126 more bytes>,
  stderr: <Buffer >
}
```

**Comment by denik1981** [comment]
I believe the cause of this issue is very well known and the fix shouldn't be hard to implement. 

`pnpm` does not support the `install` command as a way to **install** or **update/upgrade** a package. 
Install is aimed to work as with yarn where it only refers to the initial installation that takes no package as an argument.

Thus it is not: 

`pnpm install turbo@latest --save-dev -w`

but

`pnpm app turbo@latest --save-dev -w`

or also (I think but haven't tried)

`pnpm up turbo@latest --latest -w`

**Comment by tknickman** [comment]
PR is up to fix this! Apologies for the (longgg) delay here.

**Comment by chandlervdw** [comment]
@tknickman will your PR support `yarn` v3?
