### ISSUE TITLE
[turborepo] [Feature reguest] Add option to disable warning related to missing .git folder

### ISSUE THREAD

**Issue by manvydasu** [vercel/turbo#4023]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

I'd like to have an option to disable specific warning when running `turbo` comand - "WARNING  cannot find a .git folder. Falling back to manual file hashing (which may be slower). If you are running this build in a pruned directory, you can ignore this message. Otherwise, please initialize a git repository in the root of your monorepo".

`--output-logs` flag does not help and it looks like there is no way to disable that warning.

### Describe the solution you'd like

I'd like to have some sort of CLI param, which would prevent turbo from logging this warning. (or at least disable that warning when `--outputlogs=errors` is provided)

### Describe alternatives you've considered

- No alternatives.

**Comment by mehulkar** [comment]
the warning log is from here: 
https://github.com/vercel/turbo/blob/9d49e67725a52099c9db7bb7ae09bde222aadeee/cli/internal/run/run.go#L228

@nathanhammond thoughts on downgrading this to a debug log? If we're supporting non-git environments, maybe it's not really a warning scenario?

**Comment by nathanhammond** [comment]
Since we function correctly with or without a repository, _and_ we officially support non-repository-based applications (or applications in non-Git repositories), I agree that this should be downgraded.
