### ISSUE TITLE
[turborepo] Non-deterministic `turbo` change detection when using certain workspace configs

### ISSUE THREAD

**Issue by maschwenk** [vercel/turbo#4034]
### What version of Turborepo are you using?

1.8.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

![image](https://user-images.githubusercontent.com/1264305/222206336-21f4b6f8-a346-449b-a745-a077e2ceaabc.png)

Multiple invocations of `turbo --dry` are giving non-deterministic results. To isolate variables I've disconnected from the internet, used `--force` etc. None of that seemed to make it stable.

I spoke about this with @mehulkar and @gsoltis privately.

### Expected Behavior

If all things equal, multiple invocations of a build should give deterministic results.

### To Reproduce

Don't currently have time to create a reproduction as it's embedded in a very complex monorepo. Turbo setup is pretty vanilla.

```json
{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**", "build/**"]
    },
}
```

**Comment by maschwenk** [comment]
```yaml
  - 'apple'
  - 'apple/deployments/*'
  - 'apple/packages/**'
```
I think was the problematic setup in `pnpm-workspace.yaml`. There are `package.json`s at all these levels. I changed it to:

```yaml
  - 'apple/**/*'
```

Which seems stable but y'all do mention in docs that nested workspaces are not supported.

**Comment by gsoltis** [comment]
I'm going to close this in favor of #4178 since it turned out to be a feature that's not currently supported.

**Comment by maschwenk** [comment]
👍🏼 sounds good to me!
