### ISSUE TITLE
Tools for finding non-deterministic Turborepo caching behavior

### ISSUE THREAD

**Issue by maschwenk** [vercel/turbo#4036]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

On a very large monorepo with a lot of developers using the Turborepo cache, occasionally a poorly configured package will sneak into our monorepo. Usually this takes the form of a build process that either:

1. Makes non-transactional changes to the `dist` folder (such that if it's interrupted the dist is in an inconsistent state)
2. Writes into a gitignored location (e.g. writing a graphql schema into source so that it doesn't have to be committed but also can be referenced by source code)
3. Other fringe build processes that are not "take this Typescript `src` folder and write into the `dist` folder"

Sometimes it's super hard to understand exactly how/why this is happening. Usually we look for packages that are consistently **not** caching. But in those cases it's still hard to understand the root cause, because the **problematic package could be a dependency of the package that's failing to cache**.

We can't be the only org that has this problem.

### Describe the solution you'd like

Some tooling or tips on how to find the root cause of these cases, or examples of problematic patterns that Turborepo has identified can cause caching issues.

### Describe alternatives you've considered

We run our own Turborepo caching server, so one idea I had was to send metrics to Datadog for packages that were consistently getting cache misses. Unfortunately, because the Turborepo API only sends the hash of the package (not the name), I don't think this is possible.

**Comment by gsoltis** [comment]
I think Run Summaries will be a way to address this. You can see the kind of data that will be included in the new fields present in `--dry=json`. We'll be adding more and more in-depth information, including per-task information, that can be used to debug e.g. hits vs misses.

**Comment by mehulkar** [comment]
I've added a checlist item in #3431 to add hashes of dependencies in the run summary work I'm doing. That should make it easier to identify packages that are changing on every `turbo run`.

**Comment by anthonyshew** [comment]
We have Run Summaries implemented today that allow you to take a look at the anatomy of why your pipelines ran the way that they did, what they did, etc.

It *seems* to me that Run Summaries cover what needs to be covered to get this use case addressed so I'm going to close - but please do give me a holler, @maschwenk, if there's something more that needs to be done.
