### ISSUE TITLE
[turborepo] Artifacts are never uploaded to cache server with AWS Lambda deployment

### ISSUE THREAD

**Issue by zdarovka** [vercel/turbo#4038]
### What version of Turborepo are you using?

1.8.3

### What package manager are you using / does the bug impact?

Yarn v1, Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

The PUT endpoint for uploading artifacts is never being called when deployed to AWS lambda, when configured for Vercel servers it just stores them fine.

## My `config.json`
```
{
  "teamId": "team_FcALQN9XEVbeJ1NjTQoS9Wup",
  "apiUrl": "https://XXXXXXX.execute-api.eu-central-1.amazonaws.com",
  "token": "abcd"
}
```

Note: I have tried both `teamId` and `teamSlug` for the team identifier. It does not make any change.

## My build command 
```shell
yarn turbo run build --token="abcd"           
```

(yes, I am passing token twice to really make sure it gets there)

### 1 GET Artefact
*Request*
```json
{
    "severity": "INFO",
    "level": 30,
    "time": 1677700599229,
    "pid": 8,
    "hostname": "169.254.44.209",
    "reqId": "LuNKSAAKR5e9t5CU_gvE2A-2",
    "req": {
        "method": "GET",
        "url": "/v8/artifacts/3f04bb2017b72da6?teamId=team_FcALQN9XEVbeJ1NjTQoS9Wup",
        "hostname": "XXXXX.execute-api.eu-central-1.amazonaws.com",
        "remoteAddress": "XXXXX"
    },
    "message": "incoming request"
}

```
*Response*
```json
{
    "severity": "WARNING",
    "level": 40,
    "time": 1677700599257,
    "pid": 8,
    "hostname": "XXX",
    "reqId": "LuNKSAAKR5e9t5CU_gvE2A-2",
    "data": {
        "message": null,
        "code": "BadRequest",
        "region": null,
        "time": "2023-03-01T19:56:39.239Z",
        "requestId": "G1XS8G2FKHWSXTSZ",
        "extendedRequestId": "XCmY4Ggr4L/bmuBfzffH445xoSDEb5qa/Dxo/lvYUanFAZtHoj9lY0Wq2xK/fH2VylFyByXiHsE=",
        "statusCode": 400,
        "retryable": false,
        "retryDelay": 40.85058254148659
    },
    "isBoom": true,
    "isServer": false,
    "output": {
        "statusCode": 404,
        "payload": {
            "statusCode": 404,
            "error": "Not Found",
            "message": "Artifact not found"
        },
        "headers": {}
    },
    "stack": "Error: Artifact not found\n    at Object.handler (/var/task/index.js:100897:37)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "type": "Error",
    "message": "Artifact not found"
}
```

### POST artefact events
*Request*
```json
{
    "severity": "INFO",
    "level": 30,
    "time": 1677700599517,
    "pid": 8,
    "hostname": "XXXX",
    "reqId": "LuNKSAAKR5e9t5CU_gvE2A-3",
    "req": {
        "method": "POST",
        "url": "/v8/artifacts/events?teamId=team_FcALQN9XEVbeJ1NjTQoS9Wup",
        "hostname": "XXXX.execute-api.eu-central-1.amazonaws.com",
        "remoteAddress": "86.49.226.196"
    },
    "message": "incoming request"
}
```
*Response*
```json
{
    "severity": "INFO",
    "level": 30,
    "time": 1677700599518,
    "pid": 8,
    "hostname": "XXXX",
    "reqId": "LuNKSAAKR5e9t5CU_gvE2A-3",
    "res": {
        "statusCode": 200
    },
    "responseTime": 1.0016169999726117,
    "message": "request completed"
}
```

No other reuqest follows this sequence, and the result is artefacts are not uploaded

## Your Environment

- _os_: Mac
- turbo 1.8.3

### Expected Behavior

Artefacts should be uploaded.

### To Reproduce

Deploy the AWS Lambda server solution on you infrastructure and test the remote caching feature with the provided configs above

https://ducktors.github.io/turborepo-remote-cache/running-in-lambda.html

**Comment by spacedawwwg** [comment]
@zdarovka was there any resolution to this as we are hitting the same issue!

**Comment by zdarovka** [comment]
> @zdarovka was there any resolution to this as we are hitting the same issue!

We have completely shifted our approach away from attempting to deploy to Lambda. I believe this is essentially impractical due to the AWS Lambda request body size limit of 6 MB, which I think you will easily exceed.
