### ISSUE TITLE
Provide timings for each tasks

### ISSUE THREAD

**Issue by kevinsimper** [vercel/turbo#4064]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

We have a monorepo now with multiple apps and remote cache, so now it can be difficult to see if a optimization actually improves the speed of task.

### Describe the solution you'd like

Allow giving a CLI argument `--timing` outputing how long each task took.

### Describe alternatives you've considered

Timings could also be written to a json file which could be read by the CI if needed.

**Comment by mehulkar** [comment]
Hey @kevinsimper , I'm actively working on this. Keep an eye out for 1.9 release! I'm kind of keeping track of everything we're going to give you access to in https://github.com/vercel/turbo/pull/3431, but that PR itself is probably never getting merged (it's just my prototype work that I'm splitting off into reviewable / production worthy code)

**Comment by mehulkar** [comment]
Hey @kevinsimper this is now available in the latest canary. Try out the `--summarize` flag on any `turbo run`. Docs coming in https://github.com/vercel/turbo/pull/4467, when we have a stable release out.

**Comment by ProductOfAmerica** [comment]
> Hey [@kevinsimper](https://github.com/kevinsimper) this is now available in the latest canary. Try out the `--summarize` flag on any `turbo run`. Docs coming in [#4467](https://github.com/vercel/turborepo/pull/4467), when we have a stable release out.

@mehulkar I'm trying to do this in v2.4.4, and it's not spitting out a json file, in fact, there's not even a .turbo/runs folder at all. I've checked both the root .turbo, and package/name/.turbo, but nothing.

I guess it'd also be nice to have it just summarized after each task runs... in the console... instead of in a log file.

**Comment by mehulkar** [comment]
@ProductOfAmerica can you open a new issue please?

**Comment by ProductOfAmerica** [comment]
@mehulkar I am running --summarize on a persistent task... which may be why it isn't creating a file, is that correct?

However, this definitely makes the argument stronger to have it just print out to the console instead.

**Comment by mehulkar** [comment]
yes, afaik `--summarize` only works on tasks that end. I don't think it generates the file in SIGKILL (which is how you exit a persistent task). afaik we had thought about doing this eventually, but i'm not working on turborepo anymore, so I'm not sure if we did. A new issue will be more effective than commenting on this closed one.

**Comment by ProductOfAmerica** [comment]
For sure. Added https://github.com/vercel/turborepo/discussions/10161
