### ISSUE TITLE
[turborepo] --filter command omit some packages

### ISSUE THREAD

**Issue by loick** [vercel/turbo#4107]
### What version of Turborepo are you using?

1.8.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Hi everyone,

I have an issue that has been more and more persistent recently: when I run my "dev" command on my main app package (via filter), some packages never start. 

My config: 
```
"dev": {
      "outputs": [],
      "cache": false,
      "persistent": true
},
```

<img width="1417" alt="CleanShot 2023-03-07 at 19 24 15@2x" src="https://user-images.githubusercontent.com/4931832/223515150-51fb02cc-e43f-4405-9263-ff1ed8949f34.png">

As you can see in the previous screenshot, I'm running dev on "@slowy/front". 12 packages are indeed detected in the line "Package in scope".... However that's it. The "@slowy/front" dev command never starts. 

It thought... maybe something is blocking it within one of my dev script, but sometimes, it's the other way around: some packages are not started while the app is starting. 

It seems to only occur on the dev command, so I guess it's related to my watch mode? 

Here is the common commands I have across my packages: 
```
"build": "yarn build:esm & yarn build:cjs",
"build:esm": "tsc --module esnext --outDir dist/esm",
"build:cjs": "tsc --module commonjs --outDir dist/cjs",
"dev": "yarn build:esm --watch & yarn build:cjs --watch",
```

Also, when I stop the execution of turbo dev, I get the list of  packages supposed to be started prompted:
<img width="552" alt="CleanShot 2023-03-08 at 10 59 13@2x" src="https://user-images.githubusercontent.com/4931832/223682400-399d4d67-5613-4b8a-aa8c-db8497affab4.png">

I don't know what kind of information I could give more here. Is it known? Sometimes it seems to be working, here is a screenshot taken right after the previous command, when I tried again: 
<img width="1434" alt="CleanShot 2023-03-07 at 19 30 35@2x" src="https://user-images.githubusercontent.com/4931832/223516819-dbff7810-1dc5-496f-a921-0c12f97838cd.png">

### Expected Behavior

All of the packages & main app should be executed.

### To Reproduce

I have a main app, 12 packages. I can give access to my private repository if needed. 

I'm sorry I couldn't give you more. 

Thanks!

**Comment by loick** [comment]
If someone lands on this issue: my issue was related to the number of packages. The default maximum is `10`. So the solution would be to increase this number or to use the `--parallel` flag if you simply want to run the watcher on every package.

**Comment by nathanhammond** [comment]
You can also do this by setting `--concurrency=50` (or however many) as well.

**Comment by MarkForLoop** [comment]
@nathanhammond how do you set `--concurrency`?
