### ISSUE TITLE
Add an example for code generation

### ISSUE THREAD

**Issue by leerob** [vercel/turbo#413]
### Describe the feature you'd like to request

When building my Turborepo, I want to use a tool to scaffold a new workspace easily and generate code.

### Describe the solution you'd like

Let's lean on the best scaffolding solutions out there, like [Plop.js](https://plopjs.com/documentation/#getting-started) and friends.

### Describe alternatives you've considered

Copy-paste 😢

**Comment by yuchant** [comment]
+1 this. We need basic, recommended install methods for various common requirements to a monorepo.

I ended up putting my plop in a tool/code-generator local package.

I run it with from the root package.json like so:

```
 "scripts": {
    "plop": "yarn --cwd tools/code-generator plop"
  },
```

That has been cleanest. Turbo run + scope works too, but loses a lot of terminal output for its interactive code selection.

**Comment by tknickman** [comment]
Closing to consolidate on https://github.com/vercel/turbo/issues/4511
