### ISSUE TITLE
[turborepo] Turbo prune not handling pnpm patchedDependencies in the workspace root

### ISSUE THREAD

**Issue by shawnmcknight** [vercel/turbo#4133]
### What version of Turborepo are you using?

1.7.1, 1.7.4, 1.8.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

This was previously reported on #2788.  This [comment](https://github.com/vercel/turbo/issues/2788#issuecomment-1416398304) indicated that this problem was fixed in 1.7.1.  However, I was running 1.7.4 and experienced the problem.  I updated to 1.8.3 to see if it had actually been fixed in a later release, but the problem persisted on that release as well.  I tried downgrading to 1.7.1 to see if there had been a regression but the problem existed on that release as well.

Effectively, `turbo prune` does not appear to be handling pnpm patches at all.  After pruning, the root `package.json` that is copied into the `out` folder is left with: `"patchedDependencies": {}` when the original `package.json` had content in the object.  The `out` folder version of `pnpm-lock.yaml` does not have the `patchedDependencies` property present in it at all.  Finally, the `patches` folder, which is necessary to apply the patch, isn't present in the `out` folder after pruning.

I believe there must be something unique about my repo that is triggering this.  I tried to create a minimal reproduction from the ground up and everything worked properly.  Since I was unable to reproduce that way, I took my repo and kept removing pieces of it until I had it relatively small.  It had started with several packages in the workspace, but I was able to eliminate all but one and still reproduce the issue.  I'm not sure what is special about this repo that makes the patching fail to work properly, but hopefully providing it will assist.

### Expected Behavior

The `out` folder will have a `package.json` which retains the `patchedDependencies` property in full, the `pnpm-lock.yaml` file will retain its `patchedDependencies` property in full, and the `patches` folder will be copied in.

### To Reproduce

I have created a reproduction at https://github.com/shawnmcknight/turbo-pnpm-patch-repro.  The steps to reproduce are in the README.

### Reproduction Repo

https://github.com/shawnmcknight/turbo-pnpm-patch-repro

**Comment by arlyon** [comment]
Hi! Thanks for raising this issue. We have tests for this, which are passing, so I am interested in understanding what part of it is broken so we can expand the suite.

https://github.com/vercel/turbo/blob/main/cli/internal/packagemanager/fixtures/pnpm-patches.json

https://github.com/vercel/turbo/blob/main/cli/internal/packagemanager/pnpm_test.go

I am going to investigate the repro-repo (thanks! 😍) and try and build a failing test case for this.

**Comment by shawnmcknight** [comment]
@arlyon Thanks for the follow up.  I'm a bit confused about this statement:

> ie `turbo prune --scope test_root` will fail

In my repro, I'm not pruning to scope `test_root` but rather to scope `test` which is a package.  The `patchedDependencies` themselves live in the root `package.json` because that's how pnpm works with patches (i.e. the patch applies to _all_ packages for the workspace as a whole, not for individual packages in the workspace).

Let me know if any further clarification is needed and I'm happy to help.

**Comment by arlyon** [comment]
We have just merged a change that should address this. It should be included in the next release :)

**Comment by mareksuscak** [comment]
@arlyon this is currently affecting us as well. Using turbo@1.13.4 and pnpm@9.0.2 Our project is a pnpm workspace with a bunch of packages in it and we're patching a dependency in one of the app packages. patchedDependencies is in the root package.json and the dependency in question that is being patched is listed in `dependencies` so not a peer dependency. I see this was fixed a long time ago and was tested for pnpm v6 - makes me wonder if pnpm changed something in recent versions?
