### ISSUE TITLE
Docker dev enviroment

### ISSUE THREAD

**Issue by KristjanVall** [vercel/turbo#4138]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Hello can you provide example of how can i do development environment? Production is there but no dev.

### Describe the solution you'd like

Written documentation (or example github folder)

### Describe alternatives you've considered

Written documentation (or example github folder)

**Comment by arlyon** [comment]
Hi! Our basic example should be perfect for trying out turborepo and supports development out of the box.

```
npx create-turbo my-project --use-npm
cd my-project
turbo dev # or, if you don't have it installed globally, npm exec turbo dev
```

From there you should be able to visit localhost:3000 and start developing with instant hot reloading thanks to next.js. Let me know if this solves your issue.

**Comment by KristjanVall** [comment]
Hi!

I ment how should the Dockerfile look like? I did not manage to get hot reload ect..

Berst requires
Kristjan

**Comment by AlexandrosMelissas** [comment]
I guess it should look something like this but feel free to adjust it for your own use case. Volumes should be declared in docker-compose file (if you are using docker-compose):

```
FROM node:18-alpine as development
RUN apk add --no-cache libc6-compat
RUN apk update

RUN npm i -g pnpm turbo

WORKDIR /app

# First install the dependencies (as they change less often)
COPY .gitignore .gitignore
COPY turbo.json turbo.json
COPY --from=base /app/out/json/ .
COPY --from=base /app/out/pnpm-lock.yaml ./pnpm-lock.yaml

RUN pnpm install 

# # Build the project
COPY --from=base /app/out/full/ .

CMD ["turbo", "dev"]

```

**Comment by arlyon** [comment]
Turbo prune is not really intended for development work, but for bundling apps up for production use. What I typically do, it containerize all my local dev dependencies but run the code I am working on directly.

This is because when you build a container, it is an isolated system and will not (under normal conditions) handle any local changes _after_ the container is built.
