### ISSUE TITLE
[turborepo] Configuring globalDependencies in a non-monorepo

### ISSUE THREAD

**Issue by stefanofa** [vercel/turbo#4140]
### What version of Turborepo are you using?

1.8.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

I tried to add turborepo to an existing non-monorepo next project.
The `turbo.json` configuration is as follows:
```json
{
  "$schema": "https://turbo.build/schema.json",
  "globalDependencies": ["**/.env.*local"],
  "pipeline": {
    "build": {
      "outputs": [".next/**"]
    },
    "lint": {},
    "dev": {
      "cache": false,
      "persistent": true
    }
  }
}
```

But when I run
```bash
yarn turbo build
```
I get the following error:

> run failed: failed to collect global hash inputs: package.json: no workspaces found. Turborepo requires Yarn workspaces to be defined in the root package.json
> Turbo error: failed to collect global hash inputs: package.json: no workspaces found. Turborepo requires Yarn workspaces to be defined in the root package.json
> error Command failed with exit code 1.

If I remove
```json
"globalDependencies": ["**/.env.*local"],
```
from the configuration, seems to work instead.

I tried to do the same with the official example of [non-monorepo](https://github.com/vercel/turbo/tree/main/examples/non-monorepo) and the same error occurs.

### Expected Behavior

Being able to use turborepo in a 'non-monorepo' by having the configuration option `globalDependencies` working.

### To Reproduce

* Install [Turborepo non-monorepo starter](https://github.com/vercel/turbo/tree/main/examples/non-monorepo) :

```bash
npx degit vercel/turbo/examples/non-monorepo non-monorepo
cd non-monorepo
yarn
git init . && git add . && git commit -m "Init"
```

* Edit the file `turbo.json` by adding the option `"globalDependencies": ["**/.env.*local"]`.

* Run:
```bash
yarn turbo build
```

**Comment by arlyon** [comment]
Hi! We are working on improving the single-package workflow with turborepo. @tknickman has been working on a PR that addresses some of this and will follow up to make sure that this exact case is covered.

**Comment by mehulkar** [comment]
I added a failing test for this in #4240 and left a pointer on how to fix it. Will try to get back to it some time next week, but feel free to pick it up @stefanofa if you have an idea of how to fix!
