### ISSUE TITLE
[turborepo] unable to share a util package between both the vite, expo & fastify ?

### ISSUE THREAD

**Issue by a-eid** [vercel/turbo#4168]
### What version of Turborepo are you using?

^1.8.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

I'm trying to build a sharable util package between the client (vite & expo) and the server ( fastify ), I can't seem to be able to do so.

if main field in package.json is `dist/index.js` vite throws this error

`Uncaught SyntaxError: The requested module '/@fs/.../packages/utils/dist/index.js' does not provide an export named 'round' (at GaugeCharts.tsx:5:10)`

if I update it to `src/index.ts` fastify throws the error 

```bash
export function exclude<Entity, Key extends keyof Entity>(entity: Entity, keys: Key[]): Omit<Entity, Key> {
^^^^^^
SyntaxError: Unexpected token 'export'
```

### Expected Behavior

I expect that there is a guide on the docs that shows how to share packages between client and server. 

### To Reproduce

N/A

**Comment by nathanhammond** [comment]
One of these is expecting ESM and one is expecting CJS. This isn't a Turborepo issue; you'll need to configure both of your applications to consume the same module format.
