### ISSUE TITLE
[turborepo] prune's --docker generated "full" folder includes empty node_modules folder for each app

### ISSUE THREAD

**Issue by AlexandrosMelissas** [vercel/turbo#4179]
### What version of Turborepo are you using?

1.8.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

When i use the command `turbo prune --scope=api --docker`, "out" folder gets generated. Inside /out/full/apps/api/node_modules, there are all package folders but they are empty. 

So when i use the with-docker example for my use case and i copy /app/out/full to my current directory (which contains generated "json" folder with installed dependencies), my node_modules get ovewritten and they are empty so the rest of the build fails:

```

# Build the project
COPY --from=builder /app/out/full/  .  <------ here
RUN yarn turbo run build --filter=api...
```

### Expected Behavior

"full" folder shouldn't contain app's node_modules so that they dont override json's folder node_modules when copied.

### To Reproduce

use the following example with pnpm:
```
FROM node:alpine AS builder
RUN apk add --no-cache libc6-compat
RUN apk update
# Set working directory
WORKDIR /app
RUN yarn global add turbo
COPY . .
RUN turbo prune --scope=web --docker
 
# Add lockfile and package.json's of isolated subworkspace
FROM node:alpine AS installer
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /app
 
# First install the dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/yarn.lock ./yarn.lock
RUN yarn install
 
# Build the project
COPY --from=builder /app/out/full/ .
RUN yarn turbo run build --filter=web...
 
FROM node:alpine AS runner
WORKDIR /app
 
# Don't run production as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs
 
COPY --from=installer /app/apps/web/next.config.js .
COPY --from=installer /app/apps/web/package.json .
 
# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/public ./apps/web/public
 
CMD node apps/web/server.js
```

**Comment by AlexandrosMelissas** [comment]
I think i managed to fix it with .dockerignore file in root having this line:
`**/node_modules` instead of `node_modules`. Still, i dont think empty node_modules should be generated anyway.

**Comment by jordanebelanger** [comment]
@AlexandrosMelissas Thanks I had the same issue and this fixed it for me. I simply ran through the with docker example and converted it to pnpm before encountering this issue.

**Comment by TanMichael** [comment]
Still encounter the issue on 2023-12-05. 
If `dockerignore file in root having this line: **/node_modules instead of node_modules` is the solution, please update the example ` with-docker` of docs
