### ISSUE TITLE
[turborepo] `inputs` array glob patterns have no effect if git is not installed

### ISSUE THREAD

**Issue by orzarchi** [vercel/turbo#4185]
### What version of Turborepo are you using?

1.8.3

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Linux

### Describe the Bug

The `inputs` array is ignored if git is not installed. I've noticed this happening while running a docker build.
This results in the tasks running once, and then using the cache for all subsequent runs - even if a file matched by the glob patterns changed.

### Expected Behavior

Changing a file matched by a task's `inputs` glob pattern will cause that package to be rebuilt next time, git or no git. If git is a hard requirement, it should at least be documented.

### To Reproduce

I've created a simple reproduction repo by running `npx create-turbo@latest`, adding an `inputs` rule and creating a simple dockerfile.

1. Clone the reproduction repo
2. docker build -> `docker build -t repro .`
3. docker run -> `docker run --rm -it repro /bin/bash`
4. run `yarn turbo build` - everything is cached, `FULL TURBO` as expected
5. edit a file matched by an `input` pattern -> `echo "//" >> ./apps/web/pages/index.tsx`
6. run `yarn turbo build` - the `web` app is rebuilt as expected.
7. run `apt-get remove git`
8. repeat steps 4-6: This time the `web` app will not be rebuilt, because the change is not picked up.

### Reproduction Repo

https://github.com/orzarchi/turbo-cache-repro

**Comment by gsoltis** [comment]
I was not able to reproduce this with `turbo@1.91` (latest as of today). After removing `git`, the first build rebuilt both apps. I edited the file as indicated in step 5, then the subsequent build rebuilt the "web" app only.

I'm going to close, but if you are still observing this behavior with `turbo@1.9.1` or later I'm happy to reopen
