### ISSUE TITLE
[turborepo] Do something smart if `persistent: true` tasks will (or have) exhausted available concurrency.

### ISSUE THREAD

**Issue by nathanhammond** [vercel/turbo#4195]
### Describe the Bug

If you have more than 10 concurrent parallel tasks you can starve the rest of your graph and never process it. 

### Expected Behavior

We should do something smart here, probably a combination of both of these:

1. Warn or error in advance. After building the graph we can walk by distance from root by graph branch and identify the maximum number of persistent tasks and hard error.
2. If all execution slots are taken up by persistent tasks, grow available concurrency by one. (Only one non-persistent task is ... not great.)

***

Originally reported in #4107. Thanks, @loick!

**Comment by mehulkar** [comment]
If `--concurrency` isn't passed and if there are more than 10 persistent tasks to be executed, we could change the option to N+1?
