### ISSUE TITLE
[turborepo] The daemon can't start in a turbo monorepo in a nix-shell. [NixOS]

### ISSUE THREAD

**Issue by iivvaannxx** [vercel/turbo#4199]
### What version of Turborepo are you using?

1.8.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

I am trying to run a Nix-Shell development environment using a Flake to configure it. The environment needs turbo to build a monorepo project, but although the [Nix package](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/misc/turbo/default.nix) builds successfully, it fails to run with the daemon. It's the first time I am using Turbo, and I know that NixOS is kind of a 'special system' so I don't know if anyone could help me out. 

Whenever I run `nix develop` to use my nix-shell (source of which will be down below) it builds successfully, but as soon as you try to run `turbo run dev` with a brand new project created with `pnpx create-turbo@latest` it complains about failing to communicate with the turbod process. It also fails with `turbo daemon start`.

The error is the following: 

```
failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
        - the process identified by the pid in the file at /tmp/nix-shell.nMTLqd/turbod/66d934b64565cb24/turbod.pid is not running, and remove /tmp/nix-shell.nMTLqd/turbod/66d934b64565cb24/turbod.pid
        - check the logs at /home/ivan/.local/share/turborepo/logs/66d934b64565cb24-test.log
        - the unix domain socket at /tmp/nix-shell.nMTLqd/turbod/66d934b64565cb24/turbod.sock has been removed
        You can also run without the daemon process by passing --no-daemon
```

The TMP directory in `/tmp/nix-shell.nMTLqd/` is set in the environment variable `TMP` and `TMPDIR` but for some reason, when you start the shell, there is no file neither any folder in there. In consequence `turbod.pid` and `turbod.sock` don't get created and the daemon process can't run.

### Expected Behavior

I am aware that for some reason (which I don't know) this may not be an option in a NixOS system due to it's nature, but I would expect the daemon running without any problem. I tried it inside a Docker Ubuntu container and it works out of the box. I am also aware that Ubuntu is not NixOS, but I thought I could write an issue and get some clarification around this matter.

## To reproduce using the repo below
1. Clone the repository.
2. Run `nix develop` followed by a `pnpm install`.
3. Execute either `turbo run dev`, `pnpm run dev` or `turbo daemon start`. Any of those three should complain with the error explained above.

## To reproduce from scratch
Here's the source code for my `flake.nix`:

```
{
    description = "Development flake. Testing turborepo.";

    inputs = {

        nixpkgs.url = "github:nixos/nixpkgs/nixos-22.11";
        unstable.url = "github:nixos/nixpkgs/nixos-unstable";
        flake-utils.url = "github:numtide/flake-utils";
    };

    outputs = { self, nixpkgs, flake-utils, unstable, ... } @ args: let

        system = "x86_64-linux";

        pkgs         = import nixpkgs    { inherit system; };
        unstablepkgs = import unstable   { inherit system; };

    in rec {

        devShell.x86_64-linux = pkgs.mkShell {
            
            packages = [ 
                
                pkgs.nodejs-slim  
                pkgs.nodePackages_latest.pnpm
                
                unstablepkgs.turbo 
            ];

            shellHook = ''

                # Set it to use the turbo binary from the nix store.
                export TURBO_BINARY_PATH="${unstablepkgs.turbo}/bin/turbo"
            '';
        };
    };
}
```
1. Running `nix develop` should create a shell with pnpm, and turbo (as a global package).
2. Execute `pnpx create-turbo@latest` to create a template project.
3. Run `pnpm remove turbo` to avoid using the npm-installed version of turbo (which doesn't work on NixOS).
4. Execute either `turbo run dev`, `pnpm run dev` or `turbo daemon start`. Any of those three should complain with the error explained above.

### Reproduction Repo

https://github.com/iivvaannxx/turbo-nix-shell-test

**Comment by arlyon** [comment]
Hello! I don't think anyone on the turbo team has much experience working with NixOS (or nix in general). I am not familiar with the how packaging works (or how to get permission to update packages) however it is currently using quite an old version of turbo which I cannot get building. If there is continued interest in this please update the nix package to support 1.13+ and re-open and I will have a look at it. Closing in the mean time.
