### ISSUE TITLE
[turborepo] dependsOn running scripts on packages that aren't dependencies

### ISSUE THREAD

**Issue by trappar** [vercel/turbo#4214]
### What version of Turborepo are you using?

1.8.8

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Given the following scenario:

Monorepo
 - `SharedDependency@1.0.0`
 - `MyApp`
   - depends on: `SharedDependency@1.0.0`

Given that Both `SharedDependency` and `MyApp` both have a script called `build`, and the monorepo has a `turbo.json` containing the following:
```json
{
  "pipeline": {
    "build": {
      "dependsOn": ["^build"]
    }
  }
}
```

We would expect that running `turbo run build --filter MyApp` should execute:
* `SharedDependency` - build
* `MyApp` - build

This all works as expected. Now, if we publish `SharedDependency` and install the published version **instead of** the local version, we have the following situation:

* `MyApp` no longer depends on the local version of `SharedDependency`.
* `SharedDependency` exists both as a published package at version 1.0.0 and as a published package at the same version.

Given this situation... running `turbo run build --filter MyApp` should **only execute**:
* `MyApp` - build

Since `SharedDependency` is **not a dependency** of `MyApp` any longer.

In reality, Turbo continues to execute the `SharedDependency` build despite it no longer being an actual dependency.

### Expected Behavior

Turbo should **not** execute a build for a non-dependency (`SharedDependency` above)

### To Reproduce

I created a minimal reproduction repo in codesandbox. Since it's not feasible to publish a package just for a reproduction repo like this, I've instead recreated the scenario by creating a local `eslint` package inside the workspace which is at the same version as the current latest version. `main` depends on the real version of `eslint`, but continues to run the `build` script inside the local `eslint` package even though it shouldn't.

NOTE: The `link-workspace-packages=false` option inside of `.npmrc` is important for reproducing this issue, as setting that to false allows for installing a dependency from a repository even when that same package is available at the same version locally.

1. Visit the minimal reproduction on codesandbox
2. The results of running `turbo run build --filter main` should immediately pop up (eslint build should not run but does run)

### Reproduction Repo

https://codesandbox.io/p/sandbox/16fciy?file=%2FREADME.md

**Comment by trappar** [comment]
Still happening on `1.8.5`

**Comment by trappar** [comment]
Still happening on `1.8.6` - CodeSandbox has been updated.

**Comment by gsoltis** [comment]
I don't think we support depending on an "external" dependency with the same package name and version as one inside the monorepo. I would imagine that ambiguity could cause problems in a number of places.

As a workaround, can you try changing the version of your in-repository copy of `SharedDependency` immediately after publishing? For instance, if you publish `SharedDependency@1.0.0`, mark your in-repository version as `SharedDependency@1.0.1-snapshot` or similar? That would allow you to specify which you intend to depend on in `MyApp`'s `package.json`.
