### ISSUE TITLE
[turbopack] test toolchain eats mega disk space

### ISSUE THREAD

**Issue by cdaringe** [vercel/turbo#4258]
### What version of Turbopack are you using?

main

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I am trying to run the the turbopack test suite, but

1. on first attempt, the compiler ate all of the memory on my M1 air, killed my whole mac
2. on second attempt, the tests ate all of my remaining disk space (30GB+)

upon investigation, it seems the build/debug artifacts are enormous:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1003261/226217157-1e5b6b99-d1cd-452e-95fb-6b168d7d0d23.png">

i was following the standard instructions from `CONTRIBUTING.md`

### Expected Behavior

I expected that a somewhat new laptop with an abundance of resources to be able to build/test the project.

I suspect that this may be known behavior. I searched passed issues, but didn't see this exact topic listed. Whether or not this is a "problem" is subjective. The magnitudes of resource in play were sufficiently large that I couldn't work on the project, so I perceive it to be a problem, but I understand that this is just one man's opinion 😄 .

Let me know your thoughts!

### To Reproduce

Simply execute these steps in `CONTRIBUTING.md`: https://github.com/vercel/turbo/blob/main/CONTRIBUTING.md#testing-turbopack

### Reproduction Repo

n/a

**Comment by ForsakenHarmony** [comment]
Unfortunately, this is just rust and not something we can control
