### ISSUE TITLE
[turbopack] node-loader doesn't work with turbo loaders

### ISSUE THREAD

**Issue by joshua-lawrence** [vercel/turbo#4265]
### What version of Turbopack are you using?

1.8.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Hi, I am attempting to use the webpack loader "node-loader" to read binary node modules. Our team is unable to use Turbopack as of now because of this issue.

This is how I am adding the loader in next.config.js (equivalent examples in webpack use a regex pattern, but it appears that's not supported right now in turbopack):
  
  ```javascript
 experimental: {
    appDir: true,
    fontLoaders: [
      { loader: "@next/font/google", options: { subsets: ["latin"] } },
    ],
    turbo: {
      loaders: {
        ".node": ["node-loader"],
      },
    },
  },
```

I get an error indicating the loader isn't present:

```bash
./node_modules/.pnpm/canvas@2.11.0/node_modules/canvas/build/Release/canvas.node
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

### Expected Behavior

The following configuration in webpack works just fine:

```javascript
  webpack: (config) => {
    config.module.rules.push({
      test: /\.node/,
      use: [
        {
          loader: "node-loader",
        },
      ],
    });

    return config;
  },
  ```

### To Reproduce

Install [the canvas library](https://www.npmjs.com/package/canvas) in a Next13 project with turbopack, and configure [node-loader](https://www.npmjs.com/package/node-loader). The node binaries won't run.

**Comment by irian-codes** [comment]
Hope this gets solved someday, as of today it still doesn't work (using Next.js 14.2.3 with `--turbo` flag)
