### ISSUE TITLE
[turborepo] Unable to debug: go-turbo is expected to be invoked via turbo

### ISSUE THREAD

**Issue by MichaelToLearn** [vercel/turbo#4315]
### What version of Turborepo are you using?

1.8.5

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Issue title: Unable to start debugging after clicking "Build Basic" test button

Issue description: According to the instructions in https://github.com/vercel/turbo/blob/main/CONTRIBUTING.md, after clicking the "Build Basic" test button, debugging cannot be started and an error is thrown directly in the main.

```
Starting: /Users/sheng/go/bin/dlv dap --listen=127.0.0.1:53653 --log-dest=3 from /Users/username/Documents/code/js/github/turbo/cli/cmd/turbo
DAP server listening at: 127.0.0.1:53653
Type 'dlv help' for list of commands.
go-turbo is expected to be invoked via turbo
Process 91035 has exited with status 1
Detaching
```

### Expected Behavior

No error.

### To Reproduce

Just clone the main branch.

**Comment by chris-olszewski** [comment]
Sorry about that, our contributing docs have gotten a little out of date with the Rust migration. The go binary now expects the args to be JSON encoded.

**Comment by nathanhammond** [comment]
This isn't a bug, so we're going to close it. Go is in the process of disappearing...
