### ISSUE TITLE
[turborepo] Some packages that should be built are being skipped

### ISSUE THREAD

**Issue by jsiirila-sfx** [vercel/turbo#4320]
### What version of Turborepo are you using?

1.4.0

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Turbo is not building required monorepo packages when a mix of package versions from the registry and local monorepo packages are needed.

### Expected Behavior

All required monorepo packages will be built, even if they are required by a package installed from the package registry.

### To Reproduce

Have a monorepo with at least 3 packages (package-a, package-b, package-c) and dependencies between them that rely on different versions. 

Say that package-b has had the following package.json files for an old version (on the registry):
```
...
{
    "name": "package-b",
    "version": "1.1.0",
    "dependencies": {
        "package-c": "^1.0.0"
    }
}
```
The current version of package-b in the monorepo is `1.2.0`.

And that package-c has a current version of `1.0.1` in the monorepo.

And package-a depends on this older version of package-b (which gets installed from the registry because its version requirement isn't semver compatible with the current version in the monorepo):
```{
    "name": "package-a",
    "version": "3.0.0",
    "dependencies": {
        "package-b": "1.1.0"
    }
}
```

The expectation is that when a build is run for package-a that it will recognize the need to run the build for package-c, since the installed version of package-b from the registry depends on a version of package-c that is semver compatible with the current version in the monorepo. 
The yarn.lock file generated in this case does not list package-c since it recognizes that the valid version is in the monorepo.

Turbo doesn't run the build for package-c as expected.

**Comment by anthonyshew** [comment]
Closing as stale!
