### ISSUE TITLE
[turborepo]  turborepo using a cached task even though dependencies changed

### ISSUE THREAD

**Issue by supersabillon** [vercel/turbo#4323]
### What version of Turborepo are you using?

1.8.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Turborepo is not recognizing that a dependency has changed and instead of getting Cache miss, we get Cache hit and replaying the output. Temporary workaround we found is adding `"dependsOn": ["^build"]` to the task, even though the upstream dep does not have a `build` step.

### Expected Behavior

Turbo should recognize that a dependency changed and should create a new hash and not use cache.

### To Reproduce

Create a new repo
```sh
pnpm dlx create-turbo@latest
```

add this script to `docs` app:
```json
"type-check": "tsc --noEmit"
```

add this task to turbo.json
```json
"type-check": {
   "outputs": []
}
```

Run 
```sh
turbo type-check --filter=docs
```

Run command again, you should get FULL Turbo
Update `packages/ui/Button.tsx` and add a Typescript error.

Run command
```sh
turbo type-check --filter=docs
```

You get FULL Turbo. (It should fail here instead)

If you don't use turbo and instead run this command:

```sh
pnpm -F docs type-check
```
you see the TS error.

**Comment by chris-olszewski** [comment]
Hi @supersabillon, I believe this is an issue with the `type-check` pipeline definition. If you want to express that running `type-script` for `docs` depends on `type-script` for `docs` workspace dependencies, then the pipeline definition should include `"dependsOn": ["^type-check"]`. Please see the docs on [dependencies between workspaces](https://turbo.build/repo/docs/core-concepts/monorepos/running-tasks#in-a-different-workspace) for more information and examples.

**Comment by supersabillon** [comment]
> Hi @supersabillon, I believe this is an issue with the `type-check` pipeline definition. If you want to express that running `type-script` for `docs` depends on `type-script` for `docs` workspace dependencies, then the pipeline definition should include `"dependsOn": ["^type-check"]`. Please see the docs on [dependencies between workspaces](https://turbo.build/repo/docs/core-concepts/monorepos/running-tasks#in-a-different-workspace) for more information and examples.

 Hi @chris-olszewski, thanks for responding!

>  If you want to express that running `type-script` for `docs` depends on `type-script` for `docs` workspace dependencies

Not exactly, what I want is for my app to actually run the `type-check` script and not use a cached output. If you try the above commands, notice how `pnpm -F docs type-check` fails, but `turbo type-check --filter=docs` does not.

Also my upstream dependency might not have a `type-check` script.

Here's another example:

Add this script to docs

```json
"type-check": "tsc --noEmit"
```

Add this to turbo:
```
    "hello-world": {
      "outputs": []
    }
```

If I run `turbo hello-world --filter=docs` I keep getting Full turbo even if I make changes to the upstream dependency. 

Only workaround is to add ` "dependsOn": ["^build"],` to the `hello-world` task.

Can you please re-open this issue?

**Comment by gsoltis** [comment]
@supersabillon This is working as intended. An empty `"dependsOn"` list indicates to `turbo` that this particular task does not have any dependencies. As an example, think of a `lint` task which does not require anything from the workspace's dependencies.

For the `hello-world` example, I would recommend adding a dependency on `^hello-world` to the task. This tells `turbo` that the task has a dependency on the workspace's dependencies. It also gives you the added bonus of a hook to use should you ever want to improve your cache hit ratio by scoping what files are needed for `hello-world` in any of your dependencies by setting `inputs`.

**Comment by supersabillon** [comment]
> @supersabillon This is working as intended. An empty `"dependsOn"` list indicates to `turbo` that this particular task does not have any dependencies. As an example, think of a `lint` task which does not require anything from the workspace's dependencies.
> 
> For the `hello-world` example, I would recommend adding a dependency on `^hello-world` to the task. This tells `turbo` that the task has a dependency on the workspace's dependencies. It also gives you the added bonus of a hook to use should you ever want to improve your cache hit ratio by scoping what files are needed for `hello-world` in any of your dependencies by setting `inputs`.

thanks @gsoltis for clarifying that.

So perhaps a particular task might not have a dependency, but the output of the task could be different if a dependency changes. So then that means the task does have a dependency and should NOT be an empty array. But then what to put in the `dependsOn` array?

if we look at the simple example, adding `^hello-world` does not look right because:

1. Upstream dependencies might not have this task, so a dev in the future might look at this and think, "strange - we depend on this task to run in dependencies, but no deps have it, so I should delete this".
2. Upstream dependencies that have this task will now run. This might be the desired behavior for the team but could also not be. Maybe a dev only wants to run the task on their app and not all of the deps in the workspace. 

I think you're right, this is probably not a bug since is working as intended, but more of feature request. 

I want to tell a task, hey if any of the workspace dependencies change then you need to create a new hash (cache miss).

**Comment by gsoltis** [comment]
It's possible we could do something like this. For instance, `dependsOn: ["turbo:dependencies"]` or something. Would you want to rerun if anything about a dependency changed? A `README` file? A test file?

**Comment by nathanhammond** [comment]
In good news: this is a duplicate of #2855. We document the pattern you came up with here: https://turbo.build/repo/docs/core-concepts/monorepos/running-tasks#dependencies-outside-of-a-task

I've been holding 2855 open specifically to see how many people show up there in comments and so I can link issues to it as they come in.

Particularly, [this discussion](https://github.com/vercel/turbo/issues/2855#issuecomment-1334793695) on being able to specify the ideal outcome for these "non-task-dependencies" shows why @gsoltis commented as he did above asking about what inputs you would like to consider.

@gsoltis I believe it's reasonable to treat "just `^`" as a "please use the Turborepo defaults." This need will mostly show up in leaf-y nodes that are capable of consuming their dependencies without requiring them to run a build first. The `^topo` pattern which lets you specify the inputs of these deps already reaches "full power" for users who have strong opinions about when something should run.

**Comment by supersabillon** [comment]
@nathanhammond oh thanks for linking #2855 and for sharing that doc. I can't remember if I read that doc and did not understand it or if I completely missed it but it looks like using `^topo` would handle our use case. My one concern I have is if this is clear enough for devs not too familiar with turbo 🤔.  I'll give this a try on our end.

I think is fine to use turborepo defaults. 

Quick side note, can we update `we create an intermediary dummy topo task.` to `we create an intermediary placeholder topo task.`in an effort to use inclusive language?

**Comment by gsoltis** [comment]
Text update: #4613

**Comment by nathanhammond** [comment]
@supersabillon Those docs are probably newer than your last trip through the docs. 😜 The pattern is powerful but a bit non-obvious. Thank you for helping us improve our language. ❤️

**Comment by benmvp** [comment]
> I can't remember if I read that doc and did not understand it or if I completely missed it but it looks like using `^topo` would handle our use case. My one concern I have is if this is clear enough for devs not too familiar with turbo 🤔. I'll give this a try on our end.

I've read the docs many times and saw that section at the bottom and always would quit reading it due to my lack of understanding too. The `^topo` bits just made me feel like it wasn't solving a problem I needed. When in fact I need this for tests as well as type checking.

I'd have to really sit down to try to improve the docs so that it would explain the use case right at the beginning. But for now I'm just going to rename `topo` to `update-on-dependency-changes` for clarity in my turbo config.

Many thanks to @nathanhammond for the pointers and the Vercel team as a whole for all of your hard work! 🎉
