### ISSUE TITLE
[turbopack] next/image with remote source fails

### ISSUE THREAD

**Issue by masterkain** [vercel/turbo#4347]
### What version of Turbopack are you using?

alpha / nextjs 13

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Other

### Describe the Bug

when I switch to turbopack (using --turbo, it works with normal webpack) I get this error:

error - Error: Invalid src prop (https://art-dev.mydomain.com/000/000/002/0e2752bb7ee1.png) on `next/image`, hostname "art-dev.mydomain.com" is not configured under images in your `next.config.js`

my config:

```typescript
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    appDir: true,
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**.mydomain.com',
      },
    ],
  },
}

module.exports = nextConfig
```

### Expected Behavior

remote src works with turbopack / next 13

### To Reproduce

```
            <Image
              className="w-full"
              width={960}
              height={960}
              src="https://art-dev.mydomain.com/000/000/002/0e2752bb7ee1.png"
              alt=""
              sizes="(min-width: 1024px) 20rem, (min-width: 640px) 16rem, 12rem"
              priority
            />
```

**Comment by jridgewell** [comment]
Looking into this now. It's strange because we used to take advantage of this before we parsed the `next.config.js` and allowed _any_ external image for a while. Maybe something regressed after adding the config support.
