### ISSUE TITLE
[WEB-806] [turborepo] bug: npm issues on mac+ubuntu - failed to find package, MODULE_NOT_FOUND [turbo-linux-64] missing - commits passing CI on sunday now fails

### ISSUE THREAD

**Issue by mkarbo** [vercel/turbo#4365]
### What version of Turborepo are you using?

1.8.5

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Since yesterday, we have made no updates to our package-lock.json, package.json nor dockerfiles, but now we get an error similar to what is described on #3328

The error occurs both locally (on e.g., OSX pcs) as well as in CI (ubuntu).

```bash
#24 60.63 npm ERR! code 1
#24 60.63 npm ERR! path /app/node_modules/turbo
#24 60.63 npm ERR! command failed
#24 60.63 npm ERR! command sh -c node install.js
#24 60.63 npm ERR! [turbo] Failed to find package "turbo-linux-64" on the file system <---- ❗️This one here changes depending on system (mac vs linux)
#24 60.63 npm ERR! 
#24 60.63 npm ERR! This can happen if you use the "--no-optional" flag. The "optionalDependencies"
#24 60.63 npm ERR! package.json feature is used by turbo to install the correct binary executable
#24 60.63 npm ERR! for your current platform. This install script will now attempt to work around
#24 60.63 npm ERR! this. If that fails, you need to remove the "--no-optional" flag to use turbo.
#24 60.63 npm ERR! 
#24 60.63 npm ERR! node:internal/modules/cjs/loader:933
#24 60.63 npm ERR!   const err = new Error(message);
#24 60.63 npm ERR!               ^
#24 60.63 npm ERR! 
#24 60.63 npm ERR! Error: Cannot find module 'turbo'
#24 60.63 npm ERR! Require stack:
#24 60.63 npm ERR! - /app/node_modules/turbo/node-platform.js
#24 60.63 npm ERR! - /app/node_modules/turbo/install.js
#24 60.63 npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
#24 60.63 npm ERR!     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
#24 60.63 npm ERR!     at downloadedBinPath (/app/node_modules/turbo/node-platform.js:47:44)
#24 60.63 npm ERR!     at checkAndPreparePackage (/app/node_modules/turbo/install.js:[285](https://github.com/org/repo/{metadata}):15)
#24 60.63 npm ERR!     at Object.<anonymous> (/app/node_modules/turbo/install.js:310:1)
#24 60.63 npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:14)
#24 60.63 npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
#24 60.63 npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
#24 60.63 npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
#24 60.63 npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
#24 60.63 npm ERR!   code: 'MODULE_NOT_FOUND',
#24 60.63 npm ERR!   requireStack: [
#24 60.63 npm ERR!     '/app/node_modules/turbo/node-platform.js',
#24 60.63 npm ERR!     '/app/node_modules/turbo/install.js'
#24 60.63 npm ERR!   ]
#24 60.63 npm ERR! }
#24 60.63 
#24 60.64 npm ERR! A complete log of this run can be found in:
#24 60.64 npm ERR!     /root/.npm/_logs/2023-03-28T13_49_53_067Z-debug-0.log
#24 ERROR: process "/bin/sh -c npm ci" did not complete successfully: exit code: 1
```

I just re-ran the last passing CI (same commit hash, same lock-file, same dockerfile, cleared all our CI caches), and it now fails with the above, when it was passing yesterday.

We have tried deleting node_modules, package-lock.json and regenerating on:
- Macbook
- codespaces (ubuntu)
- windows wsl

And we keep getting issues

### Expected Behavior

Working like before :D 

### To Reproduce

Runing with `npm ci` in your with-docker instead of using yarn and:
- base image node:16.15-alpine instead of node:alpine
- turbo 1.8.5 
- npm version npm@9.6.2 instead of using yarn@1.22.17 in package.json (and replacing in dockerfiles)

The above in your example `with-docker` reproduces this on my machine (mac m2) as well

<sub>[WEB-806](https://linear.app/vercel/issue/WEB-806/[turborepo]-bug-npm-issues-on-macubuntu-failed-to-find-package-module)</sub>

**Comment by BogdanVV** [comment]
experiencing the same issue

**Comment by NicholasLYang** [comment]
Hi @mkarbo, thanks for the issue. Do you know if you're installing with the `--no-optional` flag? I just want to make sure that this path is being executed accidentally.

Also, to confirm, this error is occurring when turbo is installed locally, i.e. when you run `npm ci` and not when turbo is installed globally, i.e. when you run `npm install -g turbo`, correct?

If I had to guess, this might have something to do with our release of 1.8.6, which was released yesterday. While the local version of turbo is fixed due to the lock file, the global version of turbo may not be. Therefore, if you haven't done this already, I'd try pinning the global version of turbo by running `npm install -g turbo@1.8.5`

**Comment by matt-de-young** [comment]
My team was experiencing the same issue today; local builds (OSX) were working just fine even after running `npm ci` but some docker builds were failing using `node:18-alpine` as the base image. We resolved the issue by changing `RUN npm I -g turbo` -> `RUN npm i -g turbo@1.6.3` which is the version we currently have pinned in the lock file. 

I don't know if this is a version mismatch or a problem with [1.8.6](https://github.com/vercel/turbo/releases/tag/v1.8.6) but this resolved our problems for now.

**Comment by mkarbo** [comment]
Hi @NicholasLYang 

We never used --no-optional in these builds, no.

I did a bit of testing:

| | npm i -g turbo@1.8.5 | npm i -g turbo@1.8.6 |
|--------|--------|--------|
| package.json 1.8.5 | ✅ | ❌ |
| package.json 1.8.6 | ✅ | ❌ |

I could not get 1.8.6 working in global install in docker with node-alpine base - I think you are right in your suspicion 👍 

So thanks for the suggestions! We'll pin to 1.8.5 for now in our Dockerfile

**Comment by NicholasLYang** [comment]
Thanks for testing! I managed to reproduce the issue. I think we've found the bug and will try to get it fixed ASAP.

**Comment by tknickman** [comment]
This should be available in 1.8.7 @mkarbo, thanks again for the report!

**Comment by locona** [comment]
1.10.1  not working

**Comment by denfield-daveyonmayne** [comment]
Bump? Whys is this closed, @chris-olszewski ? The issue is still there.
