### ISSUE TITLE
[WEB-817] [turborepo] Package development with Precontruct and Next.js often crashes

### ISSUE THREAD

**Issue by AntoineKM** [vercel/turbo#4384]
### What version of Turborepo are you using?

1.8.7

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

When I launch my packages and my examples with precontruct and Next.js in development mode and at the same time, preconstruct is too slow to build the packages which makes Next.js apps crash because it does not find the "modules" which are not yet built, so in the end I find myself with only Precontruct launched

### Expected Behavior

What I would have liked is that it waits until precontruct is ready (so build) before launching my Next.js apps.

### To Reproduce

Nothing could be easier:
1. Create a monorepo with precontruct and a simple package
2. Add an app in Next.js that uses this package
3. Run it in dev mode

If this works for you, you probably have a very light package, but when you make a UI Kit or something really advanced, the initial build time of precontruct is really slow.

### Reproduction Repo

https://github.com/tonightpass/kitchen

<sub>[WEB-817](https://linear.app/vercel/issue/WEB-817/[turborepo]-package-development-with-precontruct-and-nextjs-often)</sub>

**Comment by NicholasLYang** [comment]
Hi @AntoineKM, thanks for opening an issue! If I understand correctly, you want your preconstruct task to be a dependency of your Next.js task, i.e. your preconstruct task should run to completion before your Next.js task is started. If that is the case, you can add your preconstruct task as an entry in your Next.js task's `dependsOn` array. For more information, I'd check out the [Dependencies between tasks](https://turbo.build/repo/docs/core-concepts/monorepos/running-tasks#dependencies-between-tasks) section of our documentation.

**Comment by AntoineKM** [comment]
Hey @NicholasLYang, 
That's exactly it but the problem is that dependOn doesn't support "watch", so for example if I run precontruct with "watch" my Next.js apps will never start.

**Comment by NicholasLYang** [comment]
Ah gotcha. Does the Next.js app not refresh after the modules are built?

**Comment by AntoineKM** [comment]
Sometimes it does and sometimes it doesn't because my package contains a HOC to be used in the `next.config.js` and if the package is not built before launching the Next.js app it crashes with the error message `error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error, Cannot find module, etc...."

**Comment by AntoineKM** [comment]
Yes, I had already tried that, here's what I tried:

**Current scenario**
- Step 1: `preconstruct watch` with `next dev` in `parallel`

Sometimes it works, but it's only when the watch is faster than Next.js apps to launch, and when it doesn't work, it's because preconstruct takes too long to build its watch, so Next.js crashes with `Failed to load next.config.js`.

**Pre-build scenario**
- Step 1: `precontruct build` has `dependOn`
- Step 2: `preconstruct watch` with `next dev` in `parallel`

Sometimes it works, but it's only when the watch is faster than Next.js apps to launch, and when it doesn't work, it's because preconstruct build, then preconstruct clean the build file at the watch launch, so Next.js crashes with `Failed to load next.config.js`.
Also not ideal because `precontruct build` take some time, so it degrades our developer experience.

**Current workaround**
- Step 1: `preconstruct watch` without turbo 
- Step 2: _...waiting for precontruct to be ready..._
- Step 3: `next dev` with turbo

It's clearly not as convenient as `preconstruct watch` with `next dev` in `parallel` with turbo but at least it works !


**Expected Behavior**

If there is a way to `dependOn` on a message in the console it could be a good way to launch an app after a watch starts so it could `dependOn` a watch (and here I'm not talking only for those who use preconstruct)

**Comment by AntoineKM** [comment]
So I found a workaround that works, but I'm not entirely satisfied, I would have liked something like that to be integrated directly into turbo, if you want to see how I managed to solve this problem go check this pull request: https://github.com/tonightpass/kitchen/pull/219

**Comment by gsoltis** [comment]
Closing as there is a workaround. But, @AntoineKM, you're right that Turborepo needs to provide better tools for a "watch" mode. Thanks for your example, I like the idea of being able to wait for output.
