### ISSUE TITLE
[WEB-818] [turborepo] [Regression] cache no longer working

### ISSUE THREAD

**Issue by notaphplover** [vercel/turbo#4389]
### What version of Turborepo are you using?

1.8.7

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Since version 1.8.7, `turbo` is no longer caching my tasks.

### Expected Behavior

I expect `turbo` to cache my tasks.

### To Reproduce

I made a reproduction repo. Simply follow the next steps:

1. Clone the repo.
2. Install dependencies.
3. Run the build root script.
4. Run again the build root script.

If you try again with `turbo@a.8.6`, the second time the `build` root script is called, it hits the cache

### Reproduction Repo

https://github.com/notaphplover/turbortepo-cache-issue

<sub>[WEB-818](https://linear.app/vercel/issue/WEB-818/[turborepo]-[regression]-cache-no-longer-working)</sub>

**Comment by tknickman** [comment]
Validated, fixing - thank you @notaphplover

**Comment by tknickman** [comment]
We've deprecated 1.8.7, and will be rolling out 1.8.8 shortly.

**Comment by tknickman** [comment]
1.8.8 is now available.
