### ISSUE TITLE
Blank template option when creating a turbo repo project

### ISSUE THREAD

**Issue by haneenmahd** [vercel/turbo#4407]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

There is only one template when creating a turbo repo project. It should have an option to remove the default template and use a blank one.

### Describe the solution you'd like

For some developers, who are already familiar with Turborepo they would like to use turborepo from a blank template that has no apps and packages.

### Describe alternatives you've considered

Provide steps in the docs on how to setup a blank project.

**Comment by haneenmahd** [comment]
Yes, I'm looking for a way to create a turbo repo project with no apps and packages.

**Comment by tknickman** [comment]
You can use the canary version (should land in latest soon) of `create-turbo` with templates support for this!

```
npx create-turbo@canary -e https://github.com/tknickman/turborepo-empty-starter
```
