### ISSUE TITLE
Support --filter shorthand "-f" on CLI

### ISSUE THREAD

**Issue by danawoodman** [vercel/turbo#4417]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

I'm using `--filter` all the time during development to install/build/test packages in my monorepo but I'm starting to lose my mind having to type out `--filter` all the time. 

Could I humbly request a shorthand of `-f` is added so I may retain some of my remaining sanity?

### Describe the solution you'd like

`-f` === `--filter`

### Describe alternatives you've considered

Jumping off a bridge

**Comment by NicholasLYang** [comment]
Hi @danawoodman, unfortunately making `-f` the shorthand for `--filter` would be a little confusing, as we also have the `--force` flag and we've noticed that generally `-f` corresponds to force, like in `rm` or `git`. I can certainly commiserate with the extra typing, but perhaps there's some combination of shell history or aliases that could make your life easier? Please don't jump off a bridge!

**Comment by danawoodman** [comment]
I get the argument, but `-f` doesn't exist right? So if the docs say `-f` for filter then is it unclear? 

Or what about another flag like `-t` for `filTer`

I can't imagine I'm the only one with this annoyance? 

I do use shell history but with the variety of calls that only helps so much.

**Comment by NicholasLYang** [comment]
On second thought, `-F` might be a reasonable option. I'll reopen this and discuss with the turbo team.

**Comment by danawoodman** [comment]
Yay! `-F` would be swell 🕺

**Comment by danawoodman** [comment]
Thanks @NicholasLYang !! 👏
