### ISSUE TITLE
Environemt variables not updating when updating .env file during build [turborepo] 

### ISSUE THREAD

**Issue by RohitKumarGit** [vercel/turbo#4428]
### What version of Turborepo are you using?

1.8.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

when you first clone the repo and set the value of `STRIPE_CLIENT_ID` ( or any env variable ) and then build everything works fine.

But on subsequent builds , any change of environment variable doesn't affect the cache hit , whenever you build it the values remain same since the first build

I read the documentation , It was mentioned that we need to include variable in `globalEnv` which I did but still the issue persists

### Expected Behavior

The build must account for the updated environment variables right? This issue is also there when I am deploying it on Vercel

### To Reproduce

1. Start docker daemon
2. run `git clone https://github.com/onecal-ai/onecal.git`
3. run `cd cal.com`
4. run `yarn dx` and stop after the server starts ( to set up postgres db)
5. run `yarn install`
6. change `.env.example` to `.env` present in root
7. run `yarn build`
8. run `yarn start` 

Now on bottom left you can see company credits
<img width="284" alt="image" src="https://user-images.githubusercontent.com/59276987/229328615-04ea2de2-ef12-438c-8bdc-052cd08b6a50.png">

This comes from an env variable `NEXT_PUBLIC_COMPANY_NAME` defines in `.env`

Now whenever you change this variable ( or any of the variable)  and build ( and start the server again) no effect will be there , it'll use the first-ever used environment variable no matter what!

### Reproduction Repo

git clone https://github.com/onecal-ai/onecal.git

**Comment by RohitKumarGit** [comment]
It was my mistake , sorry for posting here

**Comment by tknickman** [comment]
Glad you sorted it out!
