### ISSUE TITLE
no editor diagnostics (eslint) when using pnpm

### ISSUE THREAD

**Issue by princejoogie** [vercel/turbo#4431]
### What version of Turborepo are you using?

1.8.8

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

When creating a new turborepo app with `pnpm create turbo@latest` and choosing `pnpm`, diagnostics in the editor do not show.

Here is a screenshot of a a new turborepo app with yarn (top) and with pnpm (bottom).

![image](https://user-images.githubusercontent.com/47204120/229371924-b15b722b-1fc6-4cdd-bb2b-674148973fb6.png)

I've made only that 1 change in both apps but the one created with yarn shows diagnostics while the one using pnpm does not.

### Expected Behavior

Show diagnostics in editor

### With pnpm
  - create new turborepo app with pnpm
  - trigger an eslint error/warning
  - diagnostics doesnt show

### With yarn
  - create new turbo repo app with YARN now
  - trigger and eslint error/warning
  - diagnostics now show?

---

I used this snippet to trigger an eslint warning, under apps/docs/pages/index.tsx
```jsx
<li aria-required role="radio" aria-checked="false">test</li>
```

### Reproduction Repo

https://github.com/princejoogie/turbo-diagnostics-reproduction

**Comment by princejoogie** [comment]
related to #4348

**Comment by tknickman** [comment]
This should be fixed in https://github.com/vercel/turbo/pull/5775 (without the need to manually hoist)

You can test this now via:

```
npx create-turbo@latest -e https://github.com/vercel/turbo/tree/tomknickman/turbo-1233-fix-basic-example-lint -p examples/basic
```
