### ISSUE TITLE
[WEB-856] [turbopack] HMR of CSS is totally broken

### ISSUE THREAD

**Issue by CGQAQ** [vercel/turbo#4444]
### What version of Turbopack are you using?

next 13.2.4

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

Change css and save file, browser page didn't pick up what I just modified

### Expected Behavior

just works

### To Reproduce

```console
pnpm create next-app
√ What is your project named? ... xc
√ Would you like to use TypeScript with this project? ... Yes
√ Would you like to use ESLint with this project? ...  Yes
√ Would you like to use `src/` directory with this project? ... Yes
√ Would you like to use experimental `app/` directory with this project? ...  Yes
√ What import alias would you like configured? ... @/*

cd xc
pnpm i
```
then add `--turbo` to dev script, and run `pnpm dev`

modify `src/app/globals.css` or `src/app/page.module.css`, hit Ctrl + S and see what happens

<sub>[WEB-856](https://linear.app/vercel/issue/WEB-856/[turbopack]-hmr-of-css-is-totally-broken)</sub>

**Comment by jridgewell** [comment]
This might be fixed by https://github.com/vercel/next.js/pull/47913, which just landed.
