### ISSUE TITLE
[turborepo] eslint rule can't resolve globalEnv properly (regression)

### ISSUE THREAD

**Issue by lkostrowski** [vercel/turbo#4452]
### What version of Turborepo are you using?

1.8.8, eslint config 1.8.8

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

After migration (here https://github.com/saleor/apps/pull/353) from global config to local configs (per package) and updating eslint (eslint-config-turbo@1.8.8), eslint stopped properly detecting globalEnv array. It throws `X is not listed as a dependency in the root turbo.json or workspace () turbo.json` for every env 

### Expected Behavior

eslint-config-turbo should properly detect package envs in local turbo.jsons

### To Reproduce

1. checkout this PR/branch https://github.com/saleor/apps/pull/353 
2. pnpm install
3. pnpm lint 

### Reproduction Repo

https://github.com/saleor/apps/pull/353

**Comment by lkostrowski** [comment]
Just want to add that I have updated reproduction repo to use 1.9.0 (both turbo and eslint config). Error still occurs

**Comment by tknickman** [comment]
Hey @lkostrowski, the issue here is that workspace configs do not support any global configuration. 

The eslint config is correctly able to detect env dependencies in workspace configs when specified in a task "env",  or root "env" or "globalEnv" keys.

Check out the docs here: https://turbo.build/repo/docs/core-concepts/monorepos/configuring-workspaces#limitations

> For example, it is not possible to override globalEnv or globalDependencies. We expect that monorepo owners should control this absolutely, and if this config is not truly global, it should not be configured that way.

Going to close for now, but feel free to ping me again if you're still not able to resolve this!

**Comment by lkostrowski** [comment]
I see, thanks @tknickman . May I suggest some DX improvements here (some ideas)
- Separate json-schema for root and local config, where not available fields will be explicitly forbidden
- Turbo can parse configs and throw/warn about invalid config, also hinting that these fields are not available

Regarding `globalEnv` being forbidden, not sure about that approach. I understand this can be confused with "root", but in monorepo setup, where each app is separate deployment, I would expect these envs to be global for my app and compose down the tree. For me globalEnv is just like scoped `.env` files

Cheers

**Comment by lkostrowski** [comment]
Right! I see this error, I thought its a false positive, because it shows error on "extends" field, not in "globalDependencies" or "globalEnv"

Thanks for clarification, I will rewrite envs to build script dependencies
