### ISSUE TITLE
[turbopack] Importing anything from "mongodb" breaks turbopack

### ISSUE THREAD

**Issue by sklymoshenko** [vercel/turbo#4454]
### What version of Turbopack are you using?

1.8.8

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

I have my db sevice, where i need to change from `id: string` to `id: ObjectId`. I am using a mongodb for this and importing 
`import { ObjectId } from "mongodb"`. 
For example 

```
function getData(id: string) {
  const result = collection.findOne({ _id: new ObjectId(id) })
  return result
}
```
and then using this function to fetch data in `Page.tsx` as with `appDir: true` i dont have option to use `getServerProps`
```
import { getData } from 'services/getData`

export default async function Page() {
  const item = await getData('123')
}
```
Turbopack probably starts firing errors as is 
![Screenshot 2023-04-04 at 19 49 00](https://user-images.githubusercontent.com/38839167/229875837-8baab324-fa02-4f2f-957d-85775aedce07.png)

Its never ends, install one pacckage another issue appears. 

### Expected Behavior

Can access my db layer inside `layout.tsx` or `page.tsx` or any other server component.

### To Reproduce

1. Use steps from official next13 to create a next app. 
2. set `appDir: true` in `next.config.ts`
3. yarn add mongodb
4. yarn dev --turbo

go to any page and try to `import { ObjectId } from "mongodb"

**Comment by padmaia** [comment]
This is another case where a transitive dependency is required within a `try` block. If you dismiss the error, your app should still work, but with `v13.2.5-canary.30` you won't see it as an error anymore.
