### ISSUE TITLE
[WEB-855] [turbopack] refuse all fetch requests from middleware with node > 16.20

### ISSUE THREAD

**Issue by sklymoshenko** [vercel/turbo#4456]
### What version of Turbopack are you using?

1\.8.8

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When using turbopack with node 18 or any version that is higher than 16.20 all fetch requests with `fetch` fails on `ECONREFUSED:3000` for developmnet.

I have a route defined in `pages/api/myRoute`, and it refuses to connect to make any kind of fetch requests.

After some debugging an looking around i found that requests should go not from `localhost:3000` but from `127.0.0.1:3000`. But it doesnt make sense, bc if i have configured my `etc/hosts` -> `127.0.0.1       localhost` it should work totally fine as its working with node16.20.

Issue is that node16.20 breaks another stuff for turbopack and other packages so i would like to be able to use LTS version with node.

### Expected Behavior

Using node LTS and turbopack doesnt refuse localhost connection for fetch requests in edge runtime.

### To Reproduce

1. Create repo from steps from official docs
2. Create 1 endpont in `pages/api/endpoint`
3. In middleware try to call `fetch(/api/endpoint)`

dont forget to use try {} catch {} to catch actuall error

### Reproduction Repo

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [WEB-855](https://linear.app/vercel/issue/WEB-855/[turbopack]-refuse-all-fetch-requests-from-middleware-with-node-1620)</sub>

**Comment by jridgewell** [comment]
Hi @sklymoshenko. What URL are you using to connect to dev server in your browser? Is it `http://localhost:3000/`?

What I think is happening:
- We currently [hardcode](https://github.com/vercel/next.js/blob/9df4e0614ea6b9b82711328320f462f0348d5da7/packages/next/src/server/lib/route-resolver.ts#L129-L130) `localhost:3000` for middleware
- You're using some other port (or the auto port assigner is giving you port 3001, or something)
- The you're constructing a URL using the middleware's request url like `` `${new URL(req.url).hostname}/api/endpoint` ``

So, you're attempting to fetch from `localhost:3000` even though the real dev server is on some other port.

**Comment by sklymoshenko** [comment]
Hi, i am using a function to create a baseUrl like this
```
export const getBaseUrl = () => {
  if (process.env.NODE_ENV === 'development' || !process.env.NODE_ENV || !process.env.NEXT_PUBLIC_VERCEL_URL) {
    return 'http://localhost:3000'
  }

  // For local prod build test
  return process.env.NEXT_PUBLIC_VERCEL_URL.startsWith('localhost')
    ? `http://${process.env.NEXT_PUBLIC_VERCEL_URL}`
    : `https://${process.env.NEXT_PUBLIC_VERCEL_URL}`
}
const PREFIX = `${getBaseUrl()}/api`

export async function get(route) {
  try {
    const result = await fetch(`${PREFIX}${route}`)
    const data: ApiRouteResponseGet[T] = await result.json()
    if (data.error) {
      return { error: data.error }
    }

    return data
  } catch (err) {
    return { error: (err as Error).message }
  }
}
```

so when i am on development and my dev server runs on localhost:3000, it makes requests to `http://localhost:3000/api/route` and always fails in middleware just with turbopack. But if i am using node16.20 it doesnt fails, otherwise i need to change `localhost:3000` to `127.0.0.1:3000` to make it work

**Comment by jridgewell** [comment]
Interesting... Our rust binary `next-dev` works fine, but the wasm binary used by `next dev --turbo` fails.

**Comment by jridgewell** [comment]
https://github.com/nuxt/nuxt/issues/12358#issuecomment-1397230556

**Comment by sklymoshenko** [comment]
Oh i see, its great news that it not a problem with turbopack, bc i really like working with it. Thank you!

**Comment by jridgewell** [comment]
We'll be fixing this with https://github.com/vercel/next.js/pull/47948 by binding to an IPv6 address (which will accept both v6 and v4 requests). This is the way it works in the normal dev server, we just didn't realize the difference until this Node change happened.
