### ISSUE TITLE
[WEB-869] [WEB-869] Turbopack Route Handlers don't have ENV vars

### ISSUE THREAD

**Issue by timneutkens** [vercel/turbo#4489]
Hi,
Currently, i'm using the Next 13.2.5-canary.32 and it works well for getting the env variables in the middleware however i can't get any of them inside the route handlers.
So far, i only have the `NEXT_RUNTIME`.

*Originally posted by @anthonytison in* [*https://github.com/vercel/next.js/issues/47766#issuecomment-1498905854*](https://github.com/vercel/next.js/issues/47766#issuecomment-1498905854)

<sub>From [SyncLinear.com](https://synclinear.com) | [WEB-869](https://linear.app/vercel/issue/WEB-869/turbopack-route-handlers-dont-have-env-vars)</sub>

**Comment by anthonytison** [comment]
Thank you for having fixed this one that quickly!!!
