### ISSUE TITLE
[turborepo] Cache misses in CI/CD

### ISSUE THREAD

**Issue by siosphere** [vercel/turbo#4493]
### What version of Turborepo are you using?

1.8.8

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Linux

### Describe the Bug

When executing turbo in gitlabs, we have a multi-stage deployment. The first stage runs tests, which also builds some dependent packages using the turbo pipeline.

It produces output like:
```
...
@granite/tailwind:build: cache miss, executing 84bb54e2a5d5d356
...
```
Which is expected, since nothing has been built.

We save the node_modules/.cache dir as an artifact.

On the next stage of the build, those artifacts are downloaded, but running the build command, then re-executes the above with a cache miss, even though the reported hash is exactly the same:
```
...
@granite/tailwind:build: cache miss, executing 84bb54e2a5d5d356
...
```

Because so many dependencies are built as a result of running tests, it is seriously slowing down our deploys, since we have to build things twice.

### Expected Behavior

Using the node_modules/.cache directory in an artifact should work between ci/cd pipeline jobs to properly use the cache, and even though the hashes match, it is not executing from cache.

### To Reproduce

Create a multi-step CI/CD pipeline, and attempt to copy the cache between them, and re-run the yarn turbo commands, you will get cache misses.

**Comment by nathanhammond** [comment]
The ability to manually restore cached artifacts is tested and confirmed to work at 1.9.7: https://github.com/nathanhammond/turbo/actions/runs/5002277231

If you're still having issues the problem is likely in your configuration. You can also adopt the Vercel Remote Cache and make it my problem again if it doesn't work. 😜

**Comment by siosphere** [comment]
I did end up figuring this out. I had to change/configure the cache dir to be outside of node_modules.

When running a yarn install in a further step, the `node_modules/.next` folder was being removed.

**Comment by brynshanahan** [comment]
I'm having the same issue on Gitlab Pipelines, we are using gitlabs runner cache API but running `yarn install` is clearing turbos node_modules/.cache/turbo folder 
```
1. restores cache
2. ls node_modules/.cache/turbo/ *works*
3. yarn install
4. ls node_modules/.cache/turbo/ *fails*
```

I believe it must be happening as part of turbo's postinstall script

**Comment by brynshanahan** [comment]
Would it be possible to reopen this issue @nathanhammond

**Comment by hmnd** [comment]
@brynshanahan were you able to find a solution to this?

**Comment by brynshanahan** [comment]
Hey @hmnd I ended up passing `--cache-dir=./.turbo/.cache/turbo` everywhere I used the turbo command which avoided this issue
