### ISSUE TITLE
[TURBO-994] [turborepo] Stopped listing failed tasks when using --continue

### ISSUE THREAD

**Issue by weyert** [vercel/turbo#4504]
### What version of Turborepo are you using?

1.9.0.canary.2

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

In the past when you would run `turbo run build --continue` it will list all the failed tasks but now it only lists the following:
>  ERROR  run failed: command  exited (1)

### Expected Behavior

A clearer way to get all the failed tasks at once.

### To Reproduce

Upgrade to the latest version of `turborepo` and run `turbo run build` and notice it doesn't list all failed tasks

<sub>[WEB-895](https://linear.app/vercel/issue/WEB-895/[turborepo]-stopped-listing-failed-tasks-when-using-continue)</sub>

**Comment by mehulkar** [comment]
@weyert which version did you see the correct behavior?

**Comment by weyert** [comment]
@mehulkar Yes, I have the feeling it still worked in v1.8

But I have found an alternative approach to get a list it's not as straight forward:

```bash
SUMMARY_FILE=$(/bin/ls -t .turbo/runs/*.json | head -n1)
cat $SUMMARY_FILE | jq '[.tasks[] | select(.execution.exitCode != 0) | {"taskId": .taskId, "exitCode": .execution.exitCode }]'
```

**Comment by gsoltis** [comment]
@weyert I do suspect this is a bug, and looking closer into `--continue`, I think the intended behavior has been broken for a bit: tasks unrelated to the task that errored continue to execute, but tasks downstream of the failed task do not.

I'll see if I can get this fixed.
