### ISSUE TITLE
[WEB-903] [turbopack] Support for range of postcss config file extensions

### ISSUE THREAD

**Issue by navin-moorthy** [vercel/turbo#4513]
### What version of Turbopack are you using?

1.0.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Using `postcss.config.cjs` doens't generate the css from tailwindcss.

### Expected Behavior

Should be able to generate css defined in any of the allowed config files - https://github.com/postcss/postcss-load-config#postcssrcjs-or-postcssconfigjs

### To Reproduce

Create a `postcss.config.cjs` file in a nextjs example with tailwindcss.

In the below mentioned repo, 
- add `next dev --turbo`
- run the script to reproduce the bug

### Reproduction Repo

https://github.com/timelessco/next-react-app

<sub>[WEB-903](https://linear.app/vercel/issue/WEB-903/[turbopack]-support-for-range-of-postcss-config-file-extensions)</sub>

**Comment by padmaia** [comment]
All file extensions should work for as long as we've had postcss support: https://github.com/vercel/turbo/blob/4f6069c14b5fcb33fc5574c69fcfe3b6c0194b5c/crates/turbopack-node/src/transforms/postcss.rs#L50-L66

I just confirmed `postcss.config.cjs` worked in create-next-app. Is there anything else that might be special with your setup?

**Comment by navin-moorthy** [comment]
I can confirm that this works now ! 🎉
