### ISSUE TITLE
[turborepo] ignore glob pattern not working 

### ISSUE THREAD

**Issue by jcollum-nutrien** [vercel/turbo#4522]
### What version of Turborepo are you using?

1.8.8

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

turbo.json

```
    "test": {
      "inputs": ["!/e2e", "**/*.spec.ts"],
      "outputs": ["coverage/**"],
      "dependsOn": ["build"]
    },
```

When there are tests in `e2e/src/gql/create-customer.spec.ts` and I run `yarn test` (`"test": "turbo run test --concurrency=1",`) from the root it runs the test in the e2e folder. From that config it should be ignoring anything in that folder. 

Also tried: 

`     "inputs": ["!e2e/**", "**/*.spec.ts"],`

`      "inputs": ["!/e2e/**/*.*", "**/*.spec.ts"],` 

`      "inputs": ["!e2e", "**/*.spec.ts"],`

Also, if this feature actually exists it's **not documented**. From the issues that I read it's unclear if this has actually been implemented. 

```
✗ tree e2e # from the repo root
e2e
├── jest.config.js
├── jest.setup.ts
├── package.json
├── readme.md
├── src
│   ├── create-customer.spec.ts
│   ├── gql
│   │   └── create-customer.gql.ts
│   └── util.ts
├── test-data
│   └── customer-created-template.json
├── tsconfig.json
└── yarn.lock
```

### Expected Behavior

tests in the e2e folder are not run 

### To Reproduce

put a test in a folder called `e2e`, run the `test` script above

**Comment by jcollum-nutrien** [comment]
re: https://github.com/vercel/turbo/issues/1407#issuecomment-1450529718 says this is working

**Comment by adrienjoly** [comment]
> re: https://github.com/vercel/turbo/issues/1407#issuecomment-1450529718 says this is working

@jcollum-nutrien actually, the following comment (https://github.com/vercel/turbo/issues/1407#issuecomment-1451643852) says it's not.

**Comment by gsoltis** [comment]
@jcollum-nutrien The [inputs](https://turbo.build/repo/docs/reference/configuration#inputs) field is for determining what files to look at for caching. It will not control what your `test` script does. You will need to edit your test script to run the tests you want. If your test script does not run tests from `e2e`, it would be reasonable to exclude that directory (`!e2e/**`) from your `inputs` for the `test` task. That tells `turbo` that a change to a test in the `e2e` directory should not cause the `test` task to rerun.
