### ISSUE TITLE
--continue flag is not exiting with highest exit code

### ISSUE THREAD

**Issue by djamaile** [vercel/turbo#454]
### What version of Turborepo are you using?

4.4.4

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Running a command in multiple packages doesn't return an exit code 1 if it encounters an error. For example, running a prettier command in package A will return an error but the exit code of the turbo command will still be 0. 

```sh
yarn prettier:all --continue                                                           2216ms
yarn run v1.22.11
$ turbo run prettier:check --continue
• Packages in scope: plugin-gitlab, app, backend
• Running prettier:check in 3 packages
app:prettier:check: cache miss, executing 65e27beb04dafa0c
plugin-gitlab:prettier:check: cache miss, executing 3da4dd7e648440c0
backend:prettier:check: cache miss, executing e6932aacbc126b5b
app:prettier:check: $ prettier --check .
backend:prettier:check: $ prettier --check .
plugin-gitlab:prettier:check: $ prettier --check .
app:prettier:check: Checking formatting...
plugin-gitlab:prettier:check: Checking formatting...
backend:prettier:check: Checking formatting...
...
plugin-gitlab:prettier:check: error Command failed with exit code 1.
plugin-gitlab:prettier:check: command finished with error, but continuing...
app:prettier:check: error Command failed with exit code 1.
app:prettier:check: command finished with error, but continuing...
backend:prettier:check: error Command failed with exit code 1.
backend:prettier:check: command finished with error, but continuing...

 Tasks:    0 successful, 3 total
Cached:    0 cached, 3 total
  Time:    1.85s

✨  Done in 2.13s.
```
```sh
❯ echo $status  
0
```

### Expected Behavior

turbo command with `--continue` flag exists with 1 or higher eventually,  if it encounters an error

### To Reproduce

I guess have a prettier command setup in your repo and produce an error in package A and not one in package B.

**Comment by djamaile** [comment]
hi @jaredpalmer do you might know where the problem is? is it something I can contribute to

**Comment by GlennyDC** [comment]
Present in `turborepo` version `1.1.2` as well.

**Comment by bkiac** [comment]
Fixed for me in `1.1.5`

**Comment by hirvinen** [comment]
Present for me in 1.8.5.

**Comment by anthonyshew** [comment]
Hey, folks! Figuring this is a stale. Please open a new issue if you're still seeing this behavior.
