### ISSUE TITLE
esmExternals Support

### ISSUE THREAD

**Issue by Skyriis** [vercel/turbo#4544]
### Which project is this feature idea for?

Turbopack

### Describe the feature you'd like to request

Support for the `esmExternals` nextjs setting.

I'm using Ant.Vision which requires that feature.

### Describe the solution you'd like

Support for `esmExternals`

### Describe alternatives you've considered

Not using turbo

**Comment by sokra** [comment]
Do you need `esmExternals: false` or `esmExternals: true`?

**Comment by Skyriis** [comment]
`esmExternals: true`

**Comment by ddegooijer** [comment]
Any update?

**Comment by Skyriis** [comment]
afaik nothing happend until now

**Comment by ddegooijer** [comment]
Too bad, really want to give Turbo a go, but this is needed by our projects also.

If someone has a workaround, that would be very appreciated.
