### ISSUE TITLE
[WEB-902] [turbopack] API routes in nextjs 13.3 stopped working

### ISSUE THREAD

**Issue by masterkain** [vercel/turbo#4547]
### What version of Turborepo are you using?

not sure, whatever comes with next 13.3.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

GET http://localhost:3000/api/listings

```
error rendering: TypeError: Cannot read properties of undefined (reading 'middleware_edge')

Debug info:
- error rendering: TypeError: Cannot read properties of undefined (reading 'middleware_edge')
      [at file:///Users/kain/src/videoexplorer/frontend/node_modules/.pnpm/next@13.3.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/sandbox/sandbox.js:67:50]
      [at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]
      [at async Module.runEdgeFunction (file:///Users/kain/src/videoexplorer/frontend/.next/server/app/chunks/ssr/[next]_internal_edge.ts_4acfa5._.js:28:20)]
      [at async (file:///Users/kain/src/videoexplorer/frontend/.next/server/app/chunks/ssr/_c634e4._.js:92:5)]
      [at async endOperation (file:///Users/kain/src/videoexplorer/frontend/.next/server/app/chunks/ssr/[next]_internal_08c02e._.js:152:13)]
      [at async (file:///Users/kain/src/videoexplorer/frontend/.next/server/app/chunks/ssr/[next]_internal_08c02e._.js:100:13)]

status: exit status: 1
```

### Expected Behavior

without `--turbo` the endpoint works.

### To Reproduce

<img width="1178" alt="Screen Shot 2023-04-12 at 14 44 14" src="https://user-images.githubusercontent.com/12844/231461108-de79cb9a-cfaa-433c-8fb9-5daa2c07fbe8.png">

<sub>[WEB-902](https://linear.app/vercel/issue/WEB-902/[turbopack]-api-routes-in-nextjs-133-stopped-working)</sub>

**Comment by VaniaPopovic** [comment]
Experiencing similar but different issue TypeError: Cannot read properties of undefined (reading 'middleware_middleware') on the latest 13.1 canary 4.

Full error log:
`Debug info:
- Execution of get_from_source failed
- Execution of resolve_source_request failed
- Execution of NextRouterContentSource::get failed
- error during Next.js routing for /
- TypeError: Cannot read properties of undefined (reading 'middleware_middleware')
      [at file://C:\Users\fream\Desktop\BOBBLL\bobbll.crm.next\node_modules\.pnpm\next@13.3.1-canary.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\web\sandbox\sandbox.js:67:50]
      [at async TurbopackDevServerProxy.runMiddleware (file://C:\Users\fream\Desktop\BOBBLL\bobbll.crm.next\node_modules\.pnpm\next@13.3.1-canary.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\next-server.js:1409:24)]
      [at async TurbopackDevServerProxy.runMiddleware (file://C:\Users\fream\Desktop\BOBBLL\bobbll.crm.next\node_modules\.pnpm\next@13.3.1-canary.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:774:28)]
      [at async Object.fn (file://C:\Users\fream\Desktop\BOBBLL\bobbll.crm.next\node_modules\.pnpm\next@13.3.1-canary.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\next-server.js:1552:42)]
      [at async Router.execute (file://C:\Users\fream\Desktop\BOBBLL\bobbll.crm.next\node_modules\.pnpm\next@13.3.1-canary.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\router.js:297:32)]
      [at async resolveRoute (file://C:\Users\fream\Desktop\BOBBLL\bobbll.crm.next\node_modules\.pnpm\next@13.3.1-canary.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\route-resolver.js:171:9)]
      [at async Module.route (file://C:\Users\fream\Desktop\BOBBLL\bobbll.crm.next\.next\build\chunks\router\[next]_entry_router.ts_3d8e62._.js:44:28)]
      [at async Module.run (file://C:\Users\fream\Desktop\BOBBLL\bobbll.crm.next\.next\build\chunks\router\[turbopack-node]_ipc_evaluate.ts_d53664._.js:177:39)]`

**Comment by masterkain** [comment]
meanwhile I did some progress on the app and retried turbo, I'm using have aws sdk v3 in my route handlers and I have this:

```
error rendering: Error: Cannot find module 'os'

Debug info:
- error rendering: Error: Cannot find module 'os'
      [at file:///app/.next/server/app/edge/chunks/app_api_listings_[[...key]]_route.ts_next-edge-bootstrap.ts_fc1fbe._.js]
      [at file:///app/.next/server/app/edge/chunks/node_modules_c5accc._.js:36145:15]
      [at file:///app/.next/server/app/edge/chunks/node_modules_c5accc._.js:36148:3]
      [at [project]/node_modules/@aws-sdk/shared-ini-file-loader/dist-es/getHomeDir.js (ecmascript) (file:///app/.next/server/app/edge/chunks/node_modules_c5accc._.js:36166:3)]
      [at file:///app/.next/server/app/edge/chunks/app_api_listings_[[...key]]_route.ts_next-edge-bootstrap.ts_fc1fbe._.js:412:21]
      [at runModuleExecutionHooks (file:///app/.next/server/app/edge/chunks/app_api_listings_[[...key]]_route.ts_next-edge-bootstrap.ts_fc1fbe._.js:456:3)]
      [at instantiateModule (file:///app/.next/server/app/edge/chunks/app_api_listings_[[...key]]_route.ts_next-edge-bootstrap.ts_fc1fbe._.js:410:3)]
      [at getOrInstantiateModuleFromParent (file:///app/.next/server/app/edge/chunks/app_api_listings_[[...key]]_route.ts_next-edge-bootstrap.ts_fc1fbe._.js:498:10)]
      [at esmImport (file:///app/.next/server/app/edge/chunks/app_api_listings_[[...key]]_route.ts_next-edge-bootstrap.ts_fc1fbe._.js:181:18)]
      [at file:///app/.next/server/app/edge/chunks/node_modules_c5accc._.js:36363:175]
      [at [project]/node_modules/@aws-sdk/shared-ini-file-loader/dist-es/index.js (ecmascript) (file:///app/.next/server/app/edge/chunks/node_modules_c5accc._.js:36381:3)]

status: signal: 9 (SIGKILL)
```

https://github.com/aws/aws-sdk-js-v3/blob/1e806ba3f4a83c9e3eb0b41a3a7092da93826b8f/packages/shared-ini-file-loader/src/getHomeDir.ts#L1

not sure why

**Comment by ForsakenHarmony** [comment]
This may be fixed with https://github.com/vercel/next.js/pull/48791

it was just merged, so it's going to be in the next canary version (tonight)

**Comment by padmaia** [comment]
@masterkain can you confirm if you're still seeing this with the latest canary?

**Comment by masterkain** [comment]
@padmaia I got some other problems but I tried with a new project and routes appear to work, thanks

**Comment by padmaia** [comment]
Okay, closing this ticket out then. If you're still experiencing issues with a more complex route handler, let us know.
