### ISSUE TITLE
An option to restore `outputs` cache without merging

### ISSUE THREAD

**Issue by Leksat** [vercel/turbo#4566]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

I have found that turborepo actually merges files when restores `outputs` caches. In some cases this may lead to a buggy behavior.

For example, I have these tasks:

```json5
{
  "pipeline": {
    "build": {
      "inputs": ["src/**"],
      "outputs": ["build/**"]
    }.
    "test": {
      "dependsOn": ["build"]
    }
  }
}
```

When `build` is executed, it initiates an sqlite database:

```
build/.sqlite
```

Turborepo caches it for me.

Then I run `test` and this does some interactions with the database which change the database files:

```
build/.sqlite // changed
build/.sqlite-shm // created
build/.sqlite-wal // created
```

Then I do changes to the tests and rerun `test`. Turborepo checks caches for `build` task. It sees that `src/**` haven't changed. So it restores the outputs from the cache:

```
build/.sqlite // restored from cache
build/.sqlite-shm // left untouched
build/.sqlite-wal // left untouched
```

The result is a broken database 😢 

(This is a real-world example. I had to create an ugly workaround to make things work: https://github.com/AmazeeLabs/silverback-template/commit/cc7545f0a351e1a3daa35c75fc790ef9191c02ca)

### Describe the solution you'd like

I would like Turborepo to restore `outputs` cache without merging. So for my case above, when I run `test` for the second time, I'd like `build/.sqlite-*` files to be removed once the `build` cache is restored. Basically, I need the whole `build` directory to be replaced from the cache.

But I understand that this would be quite a big change in Turborepo behavior. So maybe it can be an option? E.g. `strictOutputs: true` or something like that.

### Describe alternatives you've considered

1. Don't create a new option. Make the no-merge behavior default.
2. Implement the no-merge behavior for directories configured without globs. So `"outputs": ["build/**"]` will still merge the directory contents, but `"outputs": ["build"]` will replace the directory.

**Comment by mehulkar** [comment]
This is a good question, I'll ask the team.

**Comment by mehulkar** [comment]
Hey @Leksat , we talked about this at the team meeting and decided not to provide this feature. One immediate issue is that it could only really work in the case where your output glob is configured to `build/**`. If instead you've specified `build/**/*.js`, we wouldn't be able to delete the entire directory (and matching the files to delete would create even more confusing behavior). 

For now, we believe this makes more sense to handle in user-land since you ultimately understand what your scripts do better than us. Thanks for filing and apologies for not being able to help more!

**Comment by Leksat** [comment]
If this comes up again, I'd vote for

> ### Describe alternatives you've considered
> 
> 1. Don't create a new option. Make the no-merge behavior default.
> 2. Implement the no-merge behavior for directories configured without globs. So `"outputs": ["build/**"]` will still merge the directory contents, but `"outputs": ["build"]` will replace the directory.

Because TIL that `"outputs": ["build"]` caches the `build` dir _without contents_ 😅

**Comment by pmelab** [comment]
I also think that, caching a directory without contents and than merging an empty directory with whatever is there, feels counter-intuitive. Adding a directory without wildcards should trigger a warning at least.

Clearing the directory before restoring it to avoid merging issues can be solved with an additional step, but it makes the turbo configuration even more complex, and in some cases its hard to grasp already. To me @Leksat 's suggestion alternative "2" feels very intuitive for both cases.
