### ISSUE TITLE
[turborepo]  npx create-turbo@latest -e with-docker invalid package manager

### ISSUE THREAD

**Issue by sarvex** [vercel/turbo#4567]
### What version of Turborepo are you using?

npx create-turbo@latest -e with-docker

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

When creating a new app with Docker through examples invalid package manager is specified. And the create-turbo command fails with error message "pnpm install has failed"

On a deeper look this is added to the package.json file. NPM might be higher version then 9.6.3 but the current latest pnpm version is 8.2.0

  "packageManager": "pnpm@9.6.3"

### Expected Behavior

  "packageManager": "pnpm@8.2.0"

### To Reproduce

pnpx create-turbo@latest -e with-docker

**Comment by tknickman** [comment]
Fixed in https://github.com/vercel/turbo/pull/4603

**Comment by enyelsequeira** [comment]
> Fixed in #4603

I don't think this is fixed I am getting this error, using the example from repo and  using `pnpm`
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/50872387/233801826-d4c87eab-4d4e-4de5-be4c-878330f9e8b3.png">

**Comment by sarvex** [comment]
@enyelsequeira your issue is different, you need to build the project before creating the container image. just run `yarn install`

**Comment by sarvex** [comment]
Verified working with `create-turbo@1.9.3`
