### ISSUE TITLE
hash changing with nothing else changing in the JSON summary

### ISSUE THREAD

**Issue by jonaslindstr** [vercel/turbo#4569]
@jonaslindstr if you have a hash changing with nothing else changing in the file, can you open a new issue with the relevant details? Thanks!

_Originally posted by @gsoltis in https://github.com/vercel/turbo/issues/4494#issuecomment-1505739820_
         
To reproduce:
1. `npx create-turbo@latest`
1. Select default target directory and `yarn`
1. `cd my-turborepo`
1. `yarn lint -F web --summarize` (cache miss)
1. `yarn lint -F web --summarize --experimental-env-mode=strict` (cache miss)
1. Compare the summary files: only `hash` is different

**Comment by gsoltis** [comment]
Ah, gotcha. The experimental env mode is incorporated into the hash, but has not made it into the summary yet. I expect that will happen in a coming revision of the feature though!

**Comment by mehulkar** [comment]
should be added in https://github.com/vercel/turbo/pull/4529, so summary file will show this info also

https://github.com/vercel/turbo/blob/37451a078645d5e518a610bd900de069ac8e0bc9/cli/internal/run/global_hash.go#L155
