### ISSUE TITLE
[turborepo] cache doesn't invalidate on change in dependent code.

### ISSUE THREAD

**Issue by shivendrasoni** [vercel/turbo#4572]
### What version of Turborepo are you using?

1.9.1

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

I am running a turbo monorepo that has a single workspace right now.  `web` 
The web is a react ssr app, built using webpack and has multiple subparts like dashboard etc.  
My turbo.json is defined as below, which specifies few tasks to build each of them. 
```json
{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
    "build": {
      "outputs": []
    },
    "build:client": {
      "inputs": ["!**/views/dashboard/**", "!**/views/supply/**", "!**/views/partners/**", "!src/**/server.js", "src/views/**/*.*"],
      "outputs": ["build/**/!(*dashboard*|*supply*|*partners*|*server*).*"],
      "dependsOn": ["^build:client"]
    },
    "build:dashboard": {
      "inputs": ["src/views/dashboard/**/*"],
      "outputs": ["build/**/*dashboard*.js"],
      "dependsOn": ["^build:dashboard"]
    },
    "build:supplier": {
      "inputs": ["src/views/supply/**"],
      "outputs" : ["build/**/*supply*.js"],
      "dependsOn": ["^build:supplier"]
    },
    "build:all": {
      "outputs": []
    }
  }
}
```
There is also a `build:all` command, which essentially runs `build:client` `build:supplier` `build:dashboard` commands. 
The inputs for each commands are clearly defined based on the entry points defined in part of the webpack config shared below
```js
const env = config.global.env
  const definePluginAdditionalVariables = {}

  if (env === 'development') {
    require('dotenv').config()
    environmentVariablesCheck(developmentRequiredEnvironmentVariables)
    developmentRequiredEnvironmentVariables.forEach(
      entry => (definePluginAdditionalVariables[`process.env.${entry}`] = JSON.stringify(process.env[entry])),
    )
  } else if (env === 'production') {
    environmentVariablesCheck(requiredEnvironmentVariables)
    requiredEnvironmentVariables.forEach(
      entry => (definePluginAdditionalVariables[`process.env.${entry}`] = JSON.stringify(process.env[entry])),
    )
  }

  const clientConfig = {}
  clientConfig.name = 'app'
  clientConfig.target = 'web'
  clientConfig.entry = {
    dashboardIndex: path.join(config.dirs.path_src, 'views', 'dashboard', 'index.js'),
    dashboardIndex: path.join(config.dirs.path_src, 'views', 'dashboard', 'index.js'),
    dashboardLeadsTemplates: path.join(config.dirs.path_src, 'views', 'dashboard', 'leads', 'templates.js'),
    dashboardInventories: path.join(config.dirs.path_src, 'views', 'dashboard', 'inventories', 'index.js')
.
.
.
  }
  clientConfig.output = {
    path: config.dirs.path_build_public,
    filename: '[name].js',
  }

  clientConfig.bail = false //Dont continue if errors
  clientConfig.devtool = false
  clientConfig.module = {
    rules: [
      {
        test: [/\.jsx?$/, /\.tsx?$/],
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: {
          presets: [
            [
              '@babel/preset-env',
              {
                modules: false,
                loose: true,
                useBuiltIns: 'usage',
                corejs: 3,
              },
            ],
            [
              '@babel/preset-react',
              {
                runtime: 'automatic',
              },
            ],
            '@babel/preset-typescript',
          ],
          cacheDirectory: config.dirs.path_build_tmp,
        },
      }]
  }


  clientConfig.resolve = {
    modules: [config.dirs.path_root, 'node_modules'],
    extensions: ['.tsx', '.ts', '.js', '.jsx', '...'],
    alias: {
      data: 'src/data',
      config: 'config',
      routes: 'src/routes',
      middlewares: 'src/middlewares',
      views: 'src/views',
      helpers: 'src/helpers',
      hooks: 'src/views/hooks',
      components: 'src/views/_components',
      layouts: 'src/views/_layouts',
      styles: 'src/views/_styles',
      javascripts: 'src/views/_javascripts',
    },
    fallback: {
      path: require.resolve('path-browserify'),
      stream: require.resolve('stream-browserify'),
      'process/browser': require.resolve('process/browser'),
    },
  }
```

When there is a change in the inputs mentioned here, the `cache invalidates` correctly. But when any of the imports change, the cache isn't invalidated.

### Expected Behavior

When I run build:dashboard once, it should build and cache the output. 
CURRENT BEHAVIOUR: 
When any of the imports in the files specified in the input directive change, it constitutes a Cache Hit. 

EXPECTED BEHAVIOUR: 
BUT when any of the imports in the files specified in the input directive change, the cache SHOULD be INVALIDATED too. (Cache miss should occur).

### To Reproduce

Run `turbo build`  in a repo. Ensure the result gets cached in `node_modules/.cache/turbo` folder. 
Make a change in any of the imports in the file specified in the inputs directive (not the actual files). 

Run `turbo build` again, the cache doesn't invalidate and result is hydrated from the cache itself.

**Comment by gsoltis** [comment]
Turborepo does not trace your code to find dependencies. You will need to specify all of the source files a particular build depends on (or omit `inputs` to depend on everything). So if `build:dashboard` can import files from your repository that are not currently specified in the `inputs` for `build:dashboard`, you will need to update the `inputs` to add them, or break them out into a separate workspace and add a package-level dependency on them.
