### ISSUE TITLE
[WEB-911] [turbopack] Multiple set-cookie folding, despite they shouldn't

### ISSUE THREAD

**Issue by stephtr** [vercel/turbo#4577]
### What version of Turbopack are you using?

The one supplied with Next 13.3.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

When setting multiple cookies via `response.headers`, they should appear as multiple `Set-Cookie` headers. With turbopack, they get merged into a single `Set-Cookie`, with the cookies separated by a comma, which doesn't work anymore in major browsers.

In the NextJS repo, there had been [a couple of variants](https://github.com/vercel/next.js/issues/40820) of [this issue](https://github.com/vercel/next.js/issues/34467). 

### Expected Behavior

Multiple `Set-Cookie` headers shouldn't be merged/folded together.

### To Reproduce

Create a NextJS app, add a code which adds two cookies and start it with `--turbo`.

```
import { NextRequest, NextResponse } from "next/server";

export default async function middleware(_request: NextRequest) {
    const resp = NextResponse.next();
    resp.headers.append("Set-Cookie", "cookie1=val1");
    resp.headers.append("Set-Cookie", "cookie2=val2");
    return resp;
}
```
(code taken from https://github.com/vercel/next.js/issues/34467)

<sub>[WEB-911](https://linear.app/vercel/issue/WEB-911/[turbopack]-multiple-set-cookie-folding-despite-they-shouldnt)</sub>

<sub>[WEB-1141](https://linear.app/vercel/issue/WEB-1141/[web-911]-[turbopack]-multiple-set-cookie-folding-despite-they)</sub>

**Comment by timneutkens** [comment]
Verified this is fixed: https://codesandbox.io/p/devbox/interesting-sound-8qyl39?file=%2Fapp%2Fpage.tsx%3A3%2C30

![CleanShot 2024-02-09 at 08 49 07@2x](https://github.com/vercel/turbo/assets/6324199/6e032614-5655-4cfd-91ed-7a280bc8ebc3)

Thanks for the report!
