### ISSUE TITLE
Better terminal output from `turbo run`

### ISSUE THREAD

**Issue by yuchant** [vercel/turbo#458]
### Describe the feature you'd like to request

I'd like to see terminal output with clean output from various scripts like `storybook-start` that uses the original clean progress bars, colors, etc.

I'd like to see output from scripts like `plop` like its interactive component picker (I am just using `yarn --cwd` for now.)

### Describe the solution you'd like

I'd like to see the output  that looks the same as if ran directly from yarn/npm. 
![image](https://user-images.githubusercontent.com/292732/147640485-32f924bc-cee9-4b4b-a459-9e0fbdb84243.png)

vs 

![Uploading image.png…]()
```
@foo/code-generator:plop: $ plop
@foo/code-generator:plop: ? [PLOP] Please choose a generator. (Use arrow keys)
@foo/code-generator:plop: ❯ component - Create a component (in ./) 
@foo/code-generator:plop:   package - Create a package (in ./packages/) info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@foo/code-generator:plop: error Command failed with signal "SIGINT".
@foo/code-generator:plop: Error: command finished with error: exit status 1
```

### Describe alternatives you've considered

`yarn --cwd package plop` is my current solution. 

Tried `--concurrency 1 --continue --scope=@foo/code-generator` as well

**Comment by mehulkar** [comment]
You can use the `--log-prefix` to remove turbo's embellishment of script logs. For the interactive picker, I think this is the same request as https://github.com/vercel/turbo/issues/1235, closing in favor of that
