### ISSUE TITLE
[turborepo] Using Turborepo, PNPM, MUI and TS causes builds to fail when using StyledComponents

### ISSUE THREAD

**Issue by Pettor** [vercel/turbo#4654]
### What version of Turborepo are you using?

1.9.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

**Background**
My project use a combination of Typescript + MUI + PNPM. I recently ported the project to use Turborepo using a simple structure with a shared UI library exporting MUI components that the main web app can use. The build however fails caused by a conflict in the shared UI library whenever they export a styled component (https://mui.com/system/styled/). Styled components is a big part of how MUI works and impossible to work without them. The issue only appear when using the project in combination with Turborepo.

**Error**
The build error when exporting a styled component looks like the following:

```node
src/index.ts(4,7): error TS2742: The inferred type of 'StyledComponent' cannot be named without a reference to '.pnpm/@mui+system@5.12.1_@emotion+react@11.10.6_@emotion+styled@11.10.6_@types+react@18.0.35_react@18.2.0/node_modules/@mui/system'. This is likely not portable. A type annotation is necessary.
```

### Expected Behavior

The inferred type should be correctly resolved and exported in a `d.ts` file in the dist folder.

### To Reproduce

Use the provided repo to reproduce the problem:

1. Either install latest PNPM (8.2.0) or preferably enable corepack in node.
2. Run `pnpm i` followed by `pnpm build`.
3. Build should fail and show `The inferred type of ...` in the `ui` package.

### Reproduction Repo

https://github.com/Pettor/bug-turborepo-pnpm-mui-ts

**Comment by tknickman** [comment]
Hey thanks for the issue! This is not an issue with Turborepo, but with pnpm workspaces. You can validate this by just running `pnpm build` within `packages/ui` (which removes `turbo` from the equation) - you will get the same error. 

It looks like this answer on SO has some options that should work:
https://stackoverflow.com/a/73861438/701449

**Comment by Pettor** [comment]
Thanks for the answer @tknickman . I have tried some of those options but can't get it to work in my context. It's a bit different, at least the type resolution path. I will investigate this a bit further 🙂
