### ISSUE TITLE
[turbopack] SyntaxError: setter functions must have one argument

### ISSUE THREAD

**Issue by jetaggart** [vercel/turbo#4661]
### What version of Turborepo are you using?

Nextjs 13.3

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

I'm testing out the new app dir in nextjs. Given a component like this, which uses react-three-fiber and threejs:

```typescript
"use client"

import { useRef, useState } from "react"
import { Canvas, useFrame } from "@react-three/fiber"
import { Mesh } from "three"

export default function Stuff({ products }: { products: any }) {
  return (
    <div>
      <Canvas>
        <ambientLight />
        <pointLight position={[10, 10, 10]} />
        <Box position={[-1.2, 0, 0]} />
        <Box position={[1.2, 0, 0]} />
      </Canvas>,
    </div>
  )
}


function Box(props: any) {
  // This reference will give us direct access to the mesh
  const mesh = useRef<Mesh>(null!)

  const [hovered, setHover] = useState(false)
  const [active, setActive] = useState(false)

  useFrame((state, delta) => (mesh.current.rotation.x += delta))
  return (
    <mesh
      {...props}
      ref={mesh}
      scale={active ? 1.5 : 1}
      onClick={(event) => setActive(!active)}
      onPointerOver={(event) => setHover(true)}
      onPointerOut={(event) => setHover(false)}>
      <boxGeometry args={[1, 1, 1]} />
      <meshStandardMaterial color={hovered ? 'hotpink' : 'orange'} />
    </mesh>
  )
}
```

The application fails to load with this error: `SyntaxError: setter functions must have one argument`. Looking at the linked source code `[node_modules_three_build_three.module_b2ff5b.js:1821:14](http://localhost:4000/_next/static/chunks/node_modules_three_build_three.module_b2ff5b.js)` I see this line in threejs:

```javascript
    set image() {
        let value = arguments.length > 0 && arguments[0] !== void 0 ? arguments[0] : null;
        this.source.data = value;
    }
```

This seems valid to me. The setter is using the `arguments` array which seems okay to me, not sure on what the standards say.

### Expected Behavior

Module to load fine

### To Reproduce

See description

**Comment by cool-little-fish** [comment]
It should a syntax error to write this kind of setter function. See [mdn doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set) , and in the bottom of the doc, it also provide the link to explain why this is a [error](https://whereswalden.com/2010/08/22/incompatible-es5-change-literal-getter-and-setter-functions-must-now-have-exactly-zero-or-one-arguments/).

**Comment by padmaia** [comment]
Babel also fails on this with the newest version and a modern target: [repl](https://babeljs.io/repl#?browsers=chrome%2048&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=FAYwNghgzlAECSBbCBzAprA3sKaAusAlsugBSywCUWwwAkHXgBaFQB0UA9gK4BOIaNgBMIeCLAC8sAG4Qw3NAG5adAL4Vgq4EA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.22.20&externalPlugins=&assumptions=%7B%7D)

But it looks like threejs [updated their code](https://github.com/search?q=repo%3Amrdoob%2Fthree.js+set+image%28%29&type=code), so I'm going to close this out.

**Comment by padmaia** [comment]
This should be fixed now ([before](https://play.swc.rs/?version=1.3.2&code=H4sIAAAAAAAAA%2BNKzkksLlbwzE1MT1Wo5ipOLVHIBLE1FMoSc0pTFWwV8kpzchQ0gXJcnJwlGZnFesX5pUXJqXopiSWJQGmwMmugZK2CAlctFwBVwaTuUAAAAA%3D%3D&config=H4sIAAAAAAAAA1WOSw7CMAxE9zlF5DVLhBB34BBRcEuq5iM7RURV706SNqXd2TPj55mFlDCwhoec85iXoIiR9j0rnFxU36wAaqtYkwkRLs0duFidGhmrtKwOjN4zNmfTrHGmS0e29jYQMp%2BDJapcP%2BKZLDY6WP%2Baqrl1jilg7cc3%2BIfasx0Mhp%2FtMtK0aug%2BB5CiHmNpA%2FpN3qK83itRLD8tYs2SKgEAAA%3D%3D) vs [after](https://play.swc.rs/?version=1.3.86&code=H4sIAAAAAAAAA%2BNKzkksLlbwzE1MT1Wo5ipOLVHIBLE1FMoSc0pTFWwV8kpzchQ0gXJcnJwlGZnFesX5pUXJqXopiSWJQGmwMmugZK2CAlctFwBVwaTuUAAAAA%3D%3D&config=H4sIAAAAAAAAA1WOSw7CMAxE9zlF5DVLhBB34BBRcEuq5iM7RURV706SNqXd2TPj55mFlDCwhoec85iXoIiR9j0rnFxU36wAaqtYkwkRLs0duFidGhmrtKwOjN4zNmfTrHGmS0e29jYQMp%2BDJapcP%2BKZLDY6WP%2Baqrl1jilg7cc3%2BIfasx0Mhp%2FtMtK0aug%2BB5CiHmNpA%2FpN3qK83itRLD8tYs2SKgEAAA%3D%3D))
