### ISSUE TITLE
[turborepo] Stack Traces from internal packages don't show TS line numbers, only JS line numbers 

### ISSUE THREAD

**Issue by Hansenq** [vercel/turbo#4674]
### What version of Turborepo are you using?

1.9.3

### What package manager are you using / does the bug impact?

npm, pnpm

### What operating system are you using?

Mac

### Describe the Bug

I currently use turborepo to share an [internal package](https://turbo.build/repo/docs/handbook/sharing-code/internal-packages) between two different apps. This internal package is bundled the same way that the [`ui` internal package](https://github.com/vercel/turbo/tree/main/examples/kitchen-sink/packages/ui) is bundled in the turborepo `kitchen-sink` example--typescript code bundled down to a CommonJS module.

When an error is hit within this internal package, the app shows a stack trace and stops. The stack trace it displays, however, shows the compiled JS file (in `dist/`) line numbers, rather than the TS file (in `src/`) line numbers. I've confirmed that the internal package is compiled with `tsc` with the `sourceMap` flag set to `true` and has generated source maps at the bottom of the `dist/*.ts` file and in `dist/*.js.map`. 

### Expected Behavior

In the error stack trace for an error encountered in an internal package, I expect the stack trace to reference the source `.ts` files. However, the stack trace currently references the compiled `.js` files. This makes debugging errors much more difficult. 

### To Reproduce

We can reproduce this issue with the example kitchen-sink repo: 

1. Clone the `kitchen-sink` example locally and run `pnpm install`
2. There's currently a bug with the example. In order to fix this example, in `package.json`, edit the `scripts.dev` value to `"turbo run dev --no-cache  --continue --concurrency 11"`
3. Open `packages/ui/src/CounterButton.tsx`. Add `throw new Error("Hello World");` on a new line on line 5, before the `return` statement.
4. Run `npm run dev`
5. Open the Remix app (likely at `localhost:3001`) in a web browser. The page should not load and the app should crash 
6. Inspect the stack trace printed out in the console. It should look something like the following. Note how the stack trace for the `ui` library points to the compiled JS file, not the source TS file. 
```
blog:dev: Remix App Server started at http://localhost:3001 (http://172.20.34.75:3001)
blog:dev: No routes matched location "/src/main.tsx"
blog:dev: GET /src/main.tsx 404 - - 145.246 ms
blog:dev: No routes matched location "/@react-refresh"
blog:dev: GET /@react-refresh 404 - - 5.613 ms
blog:dev: Error: Hello world
blog:dev:     at CounterButton (/Users/hansenq/Documents/CS/turbo/examples/kitchen-sink/packages/ui/dist/index.js:85:9)
blog:dev:     at renderWithHooks (/Users/hansenq/Documents/CS/turbo/examples/kitchen-sink/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:5724:16)
blog:dev:     at renderIndeterminateComponent (/Users/hansenq/Documents/CS/turbo/examples/kitchen-sink/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:5797:15)
blog:dev:     at renderElement (/Users/hansenq/Documents/CS/turbo/examples/kitchen-sink/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6012:7)
blog:dev:     at renderNodeDestructiveImpl (/Users/hansenq/Documents/CS/turbo/examples/kitchen-sink/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6170:11)
blog:dev:     at renderNodeDestructive (/Users/hansenq/Documents/CS/turbo/examples/kitchen-sink/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6142:14)
blog:dev:     at renderNode (/Users/hansenq/Documents/CS/turbo/examples/kitchen-sink/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6325:12)
blog:dev:     at renderChildrenArray (/Users/hansenq/Documents/CS/turbo/examples/kitchen-sink/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6277:7)
blog:dev:     at renderNodeDestructiveImpl (/Users/hansenq/Documents/CS/turbo/examples/kitchen-sink/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6207:7)
blog:dev:     at renderNodeDestructive (/Users/hansenq/Documents/CS/turbo/examples/kitchen-sink/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6142:14)
```

### Reproduction Repo

https://github.com/Hansenq/turbo-fork/tree/main/examples/kitchen-sink

**Comment by tknickman** [comment]
Hey @Hansenq - this is expected behavior, and is because the internal package is being built. The app (blog in this case) is only aware of the build _output_ (the compiled JS files) of `ui`. You might be able to get around this by configuring typescript declaration maps ([docs](https://tsup.egoist.dev/#generate-typescript-declaration-maps--d-ts-map)) in the build of `ui`, but I believe that will only work in your editor, and not in the CLI output.

**Comment by Hansenq** [comment]
Ah, appreciate the response! One quick follow-up question: is there a way then, to *not* compile the `ui` package down to CommonJS modules? That would allow the .ts files to be executed as is without compiling them down to .js. 

I'm using this strategy for simpler packages without imperative code (e.g. an internal package with our shared constants) and it's able to run the .ts without compiling it down to a CommonJS module, but this doesn't seem to work with larger packages. Any chance there's something I'm missing, and that we're able to just run the .ts without compiling it down to .js?

**Comment by anthonyshew** [comment]
We've updated our examples recently. If you're still running into problems, please open a new issue!
