### ISSUE TITLE
[turborepo] HMR lost if you import shared ui package inside _app and index files

### ISSUE THREAD

**Issue by pacxiu** [vercel/turbo#4689]
### What version of Turborepo are you using?

1.9.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

HMR is not working as expected and performs full refresh of app and it looses it's state if you modify file in package that is both imported in:
```
_app.tsx
index.tsx
```

I've started to encounter this bug in some of my shared Layouts that I had and thought maybe I have some cyclic dependencies but I could also reproduce it on sample repo. 

### Expected Behavior

It should not perform full refresh and keep it's state.

### To Reproduce

- Open Console
- Go to `Button.tsx` in `ui` package, modify eg. Button Text
- App will perform full-refresh loosing it's state
![image](https://user-images.githubusercontent.com/19193499/234195457-9d042ac2-7a5b-4f83-bcab-9fa9e81190b0.png)

### Reproduction Repo
https://github.com/clumsier/turborepo-hmr-bug

**Comment by arlyon** [comment]
Hi! Thanks for taking the time to open an issue here. I don't believe this is an issue with turborepo or turbopack since running the next in dev mode directly via yarn causes the same issue, and you have not opted-in to using turbopack. @vercel/web-tooling could anyone weigh in on this example and confirm that that is the case?

**Comment by arlyon** [comment]
Hi, @pacxiu, I think you are best off opening this repro with https://github.com/vercel/next.js, since I don't believe this is a turbo-specific issue. I am closing this for now, thanks!
