### ISSUE TITLE
Support turbo.jsonc (or turbo.json5)

### ISSUE THREAD

**Issue by cjpearson** [vercel/turbo#4710]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Turbo uses a jsonc parser (https://github.com/vercel/turbo/pull/1472) to support comments in the config file, but IDEs/editors might warn about comments not being allowed in JSON. Changing the extension will tell them that an alternative JSON syntax is being used.

### Describe the solution you'd like

If there is no `turbo.json` file, turbo will look for a `turbo.jsonc` file and use that.

### Describe alternatives you've considered

Changing IDE settings, removing comments or living with the warnings are all acceptable workarounds, but it would be nice to have this feature.

**Comment by mehulkar** [comment]
We don't support the file being called `turbo.jsonc`, but we do _parse_ the file as jsonc. So you should be able t add comments and things will work.

**Comment by mehulkar** [comment]
@cjpearson understood. We're tracking that over in https://github.com/vercel/turbo/issues/3793!
