### ISSUE TITLE
[WEB-967] [WEB-967] Issue using cookies with next/headers with Turbopack enabled

### ISSUE THREAD

**Issue by timneutkens** [vercel/turbo#4745]
### Verify canary release

* [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 16.14.2
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 13.1.6-canary.1, 13.1.5
  eslint-config-next: 13.1.5
  react: 18.2.0
  react-dom: 18.2.0
  
I've tried **Node** version 18 as well as Next both next versions listed above.
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Turbopack (--turbo)

### Link to the code that reproduces this issue

n/a

### To Reproduce

/\*
The following code will reproduce the issue in any project with turbopack enabled
\*/

import React from 'react';
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';

const Home = () => {

```
const nextCookies = cookies();
const auth = nextCookies.get('ccauth');

if (!auth) {
redirect('/login');
```

}

```
return (
    <div>page</div>
);
```

};

export default Home;

### Describe the Bug

App breaks when trying to access next/header cookie info on server component

**Unhandled Runtime Error**
1 of 1
Error: Invariant: Method expects to have **requestAsyncStorage**, none available

### Expected Behavior

Access to header/cookie info is returned

### Which browser are you using? (if relevant)

Chrome Version 109.0.5414.120 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

n/a

<sub>From [SyncLinear.com](https://synclinear.com) | [WEB-967](https://linear.app/vercel/issue/WEB-967/issue-using-cookies-with-nextheaders-with-turbopack-enabled)</sub>

**Comment by padmaia** [comment]
linear sync duplicated
