### ISSUE TITLE
[WEB-970] [turbopack] Docker ENV - webpack bundler way faster than turbopack

### ISSUE THREAD

**Issue by timneutkens** [vercel/turbo#4748]
### Verify canary release

* [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
npx --no-install next info

    Operating System:
      Platform: linux
      Arch: arm64
      Version: #1 SMP Mon Apr 24 06:47:55 UTC 2023
    Binaries:
      Node: 19.9.0
      npm: 9.6.5
      Yarn: N/A
      pnpm: 8.3.1
    Relevant packages:
      next: 13.3.2-canary.6
      eslint-config-next: 13.3.2-canary.6
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Turbopack (--turbo)

### Link to the code that reproduces this issue

no response

### To Reproduce

Run next dev --turbo in a docker environment and in host environment

### Describe the Bug

Running next dev (Webpack) in a `host machine` MacBook m1 is super slow
Running next dev --turbo (TurboPack) `in host machine` is super fast (or at least good enough) in host machine

Buuuut....

Doing the same yields the oposite, webpack is super fast and turbo pack similar or way slower than webpack, been not stable in the building times ranging from sometimes 2 seconds to 20 seconds with no reasons, webpack remains stable and builds are always ranging from 1 second to 6 seconds pretty much.

Those are Cold builds, hot builds are in webpack slower than in turbo pack which is super fast.

Problems are in cold build that turbo pack is acting erratic and shutingdown some times and not finishing the build in some circumstances.

Also already reported that turbopack has issues with https in docker so I don't know if this is related or not, or if there is any specific configuration or package that we should install in docker to gain the speed that we get in the host machine.

***just in case you may ask, I tested this isolating completely the docker volumes without sharing them with the host machine and yields exactly the same result. sharing volumes are not the cause of this (as also you can notice that webpack is faster in docker than in host machine).***

### Expected Behavior

Turbopack been faster in docker

### Which browser are you using? (if relevant)

*No response*

### How are you deploying your application? (if relevant)

*No response*

this is the image I’m using in docker
[https://github.com/nodejs/docker-node/blob/7a8d51d0e6acd67d14059140231ea52c7be8f023/19/bullseye/Dockerfile](https://github.com/nodejs/docker-node/blob/7a8d51d0e6acd67d14059140231ea52c7be8f023/19/bullseye/Dockerfile)

<sub>From [SyncLinear.com](https://synclinear.com) | [WEB-970](https://linear.app/vercel/issue/WEB-970/[turbopack]-docker-env-webpack-bundler-way-faster-than-turbopack)</sub>

**Comment by padmaia** [comment]
linear sync duplicated
