### ISSUE TITLE
[turborepo] crashes when not finding a log file on the `.turbo` folder

### ISSUE THREAD

**Issue by ovflowd** [vercel/turbo#4775]
### What version of Turborepo are you using?

1.9.3

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

Turborepo on GitHub Actions (Windows Matrix) fails due to not being able to find a log file, as seen in [this](https://github.com/nodejs/nodejs.org/actions/runs/4856776023/jobs/8661195276?pr=5340) GitHub Action.

### Expected Behavior

It should probably not crash whilst checking for an existing log file.

### To Reproduce

1. Run the Workflow Steps?

### Reproduction Repo

https://github.com/nodejs/nodejs.org/tree/major/website-redesign

<sub>[TURBO-1519](https://linear.app/vercel/issue/TURBO-1519/[turborepo]-crashes-when-not-finding-a-log-file-on-the-turbo-folder)</sub>

**Comment by ovflowd** [comment]
That's interesting, but somehow only happens if we have double colons, like `test:unit:ci` if we just use `test:unit` it works 🤯

**Comment by olaf-k** [comment]
> @gsoltis do you know if #6141 might have fixed this by any chance?

FWIW I ran into the very same issue and updating to 1.10.16 did not change a thing. I also confirm it only happens when more than one colon appears in the task name.

**Comment by grbd** [comment]
Just ran into this problem myself under windows.
running with --verbosity 10 shows the name of the log file in all cases

With a script named `panda-build`
This generates a log file of `.turbo/turbo-panda-build.log`

With a script named `panda:build`
In the console log it suggests it's using `.turbo\turbo-panda:build.log`
but the file is never generated (invalid filename for windows), the task does run without error however

with a script named `panda:build:buildinfo` (double colon)
in the console it now decides to throw an error
`.turbo\turbo-panda:build:buildinfo.log: The filename, directory name, or volume label syntax is incorrect.`

So it is failing to write a log with a single colon but not caring
but with a double colon it does care for some reason

**Comment by grbd** [comment]
Note setting `"cache": false` does fix things but then you lose the cache for the task

also since I think the log file is the cache record, I suspect where there's a single colon in place it's not caching at all
(this might also be linked to other issues under windows related to the cache)

**Comment by gsoltis** [comment]
@grbd With a single `:`, it is in fact caching, and is accidentally using a Windows feature called [Alternate Data Streams](https://owasp.org/www-community/attacks/Windows_alternate_data_stream#:~:text=Alternate%20data%20streams%20allow%20files,stream%20is%20called%20%3A%24DATA%20.). That means that the cached logs file _is_ created, as a separate stream inside the file `turbo-panda`. This is not intentional behavior, and as you have seen, is broken when there are two `:` tokens in the script name. I'll take a look at getting some escaping in place!

**Comment by grbd** [comment]
Maybe a regex to replace : with `-colon-` or something as a workaround in the log filename.

**Comment by gsoltis** [comment]
I think #6267 should fix this.

**Comment by arlyon** [comment]
Hello, we released a new version of turbo with #6267 which should fix this issue so I am going to close it. Feel free to comment if that is not the case and I will reopen.

Thanks for reporting!
