### ISSUE TITLE
Cannot use the turbo login command on a headless server

### ISSUE THREAD

**Issue by JoeyEamigh** [vercel/turbo#479]
### What version of Turborepo are you using?

1.0.24

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

When I run `turbo login` I get an error saying `exec: "xdg-open": executable file not found in $PATH`. I am on a headless system and therefore there is no way for a browser to automatically open.

### Expected Behavior

The login to provide a hyperlink to login to Vercel's Turborepo instead of crashing

### To Reproduce

Start a headless Linux server (I use Ubuntu 20.04), and run `turbo login`

bam
that should do it

**Comment by anthonyshew** [comment]
Closing as Tom has detailed how to provide credentials from CI.
