### ISSUE TITLE
[WEB-985] Wasm loading

### ISSUE THREAD

**Issue by padmaia** [vercel/turbo#4795]
Add support for loading wasm binaries in Turbopack projects

<sub>From [SyncLinear.com](https://synclinear.com) | [WEB-985](https://linear.app/vercel/issue/WEB-985/wasm-loading)</sub>

**Comment by padmaia** [comment]
Working in canary, will be published in the next release

**Comment by enricoros** [comment]
@padmaia how do we know how to use this support? I'm trying to get [tiktoken](https://github.com/dqbd/tiktoken) to run.

**Comment by timneutkens** [comment]
@enricoros could you share an example of what you're trying to use specifically? I.e. how the package is being imported. Then I can make sure we open a new issue for that particular library if it doesn't work. Thanks!

**Comment by enricoros** [comment]
@timneutkens  Thanks for the ask. Here are some details

The use case is LLM tokens count for AI applications.

The task is about importing and using the WASM-based TikToken library, which is a library that performs conversion of Text into "tokens" for various OpenAI models. This is done in the frontend (typescript, nextjs) to provide as-you-type feedback to the user.

The code (see below for the core of the code itself):
- imports dynamically the TikToken library
  - https://github.com/dqbd/tiktoken <- the WASM fast library, not the pure-JS implementation
- the TikToken library loads the WASM `import * as wasm from "./tiktoken_bg.wasm";` 
- the client will then call functions such as `get_encoding.encode(...)`, which will invoke the wasm
- the user will get to see the "tokens" with a medium-fast speed of response

```src/common/util/token-counter.ts
/**
 * Preloads the Tiktoken library if not already loaded.
 * @returns {Promise<void>} A promise that resolves when the library is loaded.
 */
export function preloadTiktokenLibrary(): Promise<void> {
  if (!preloadPromise) {
    preloadPromise = import('tiktoken')
      .then(tiktoken => {
        get_encoding = tiktoken.get_encoding;
        encoding_for_model = tiktoken.encoding_for_model;
        if (informTheUser)
          console.warn('countModelTokens: Library loaded successfully');
      })
      .catch(error => {
        console.error('countModelTokens: Failed to load Tiktoken library:', error);
        preloadPromise = null; // Allow retrying if the import fails
        throw error; // Re-throw the error to inform the caller
      });
  }
  return preloadPromise;
}
```

Thansk for your consideration.

**Comment by timneutkens** [comment]
There's an open one for pdfjs already 👍 https://github.com/vercel/next.js/issues/65406
