### ISSUE TITLE
Couldn't find "PLATFORM_NAME" variable in xcodebuild output. Please report this issue and run your project with Xcode instead.

### ISSUE THREAD

**Issue by softshipper** [vercel/turbo#481]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Running `yarn workspace calshareapp run ios` I have got the following error messages:
```
error Couldn't find "PLATFORM_NAME" variable in xcodebuild output. Please report this issue and run your project with Xcode instead.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 
```
Running without turborepo works fine. 

### Expected Behavior

Running React Native app on IOS without errors.

### To Reproduce

- Create new turbo repo.
- Create new React Native app with the following command `npx react-native init Mobile --template react-native-template-typescript` and put it into the `app`folder
- Start the command `yarn workspace Mobile run ios` on the root folder and you will see the error message.

**Comment by vcnc-hex** [comment]
Since the `react-native init` command creates a project based on a standalone application, it may not work properly in a general monorepo environment. You should use `nohoist` options inside `workspaces` field of `package.json`.

ex)
```json
  "workspaces": {
    "packages": [
      "packages/*",
      "apps/*",
    ],
    "nohoist": [
      "**/react-native",
      "**/react-native/**",
      "**/@react-native-*",
      "**/@react-native-*/**",
      "**/react-native-*",
      "**/react-native-*/**",
      "**/*react-navigation/native*",
      "**/*react-navigation/native*/**",
      "**/expo",
      "**/expo/**",
      "**/@expo",
      "**/@expo/**",
      "**/expo-*",
      "**/expo-*/**",
      "**/metro-*",
      "**/metro-*/**"
    ]
  },
```

**Comment by mehulkar** [comment]
Are you still running into this issue? It seems specific to react-native rather than turbo?

**Comment by anthonyshew** [comment]
Closing as stale.
