### ISSUE TITLE
[WEB-998] Support experimental swc plugins

### ISSUE THREAD

**Issue by padmaia** [vercel/turbo#4810]
<sub>From [SyncLinear.com](https://synclinear.com) | [WEB-998](https://linear.app/vercel/issue/WEB-998/support-experimental-swc-plugins)</sub>

**Comment by padmaia** [comment]
Working in canary, will be published in the next release

**Comment by nil1511** [comment]
Is `experimental.swcPlugins` working the same as before? and for that reason, the flag was not enabled in https://github.com/vercel/next.js/pull/50401? @kwonoj could help here.

After enabling the flag in supportedTurbopackNextConfigOptions, I tried next 13.5.1 with [swc-plugin-react-native-web](https://github.com/nissy-dev/swc-plugin-react-native-web) after building with rust nightly-2023-07-21([as explained here](https://github.com/swc-project/swc/issues/7479)), and import paths are not transformed as expected with `next dev --tubro`, works as expected without turbo.
