### ISSUE TITLE
Can you support MIT license instead of MPL?

### ISSUE THREAD

**Issue by sayjeyhi** [vercel/turbo#4811]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Since Turbo is under Vercel's name, is it possible to change the license to MIT?

### Describe the solution you'd like

MIT

### Describe alternatives you've considered

MIT

**Comment by nathanhammond** [comment]
We've selected our license intentionally and will not be changing it. If you're simply using the tool this shouldn't be a problem.
