### ISSUE TITLE
Support for Typescript Loaders

### ISSUE THREAD

**Issue by BierDav** [vercel/turbo#4814]
### Which project is this feature idea for?

Turbopack

### Describe the feature you'd like to request

There is an essential webpack loader needed `ts-loader`, because turbopack currently doesn't support typescript outputs. The problem is that we can't use this loader due to follwoing error:

```
Error evaluating Node.js code
  TypeError: Cannot read properties of undefined (reading 'hooks')
      [at initializeInstance (<project-path>\node_modules\ts-loader\dist\instances.js:237:31)]
      [at successLoader (<project-path>\node_modules\ts-loader\dist\index.js:25:40)]
      [at Object.loader (<project-path>\node_modules\ts-loader\dist\index.js:22:5)]
      [at LOADER_EXECUTION (<project-path>\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:4134)]
      [at runSyncOrAsync (<project-path>\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:4145)]
      [at iterateNormalLoaders (<project-path>\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:5782)]
      [at iterateNormalLoaders (<project-path>\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:5650)]
      [at <project-path>\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:5879]
      [at r.callback (<project-path>\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:4039)]
      [at <project-path>\node_modules\openapi-client-sdk-loader\dist\index.js:53:115]
      [at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]
```

We need a way to put typescript in the loader pipeline!

My example use case would be following configuration:

 ```javascript
 turbo: {
            loaders: {
                ".yaml": [
                    {
                        loader: 'ts-loader',
                        options: {
                            configFile: path.resolve(__dirname, '../tsconfig.json'),
                            appendTsSuffixTo: [/\.yaml$/],
                        },
                    },
                    {
                        loader: "openapi-client-sdk-loader",
                        options: {
                            compiler: 'ts',
                            templateOptions: {
                                validateRequest: true,
                                validateResponse: true,
                            },
                            skipInvalid: true,
                            style: {
                                singleQuote: true,
                                trailingComma: 'es5',
                                printWidth: 100,
                            },
                        },
                    }]
            }
        }
```

### Describe the solution you'd like

I haven't found a documentation of the turbopack loader API so I not sure if there is already a feature that does the same which would make it possible to port the library, but if not so we need some kind of support for this.

**Really the number one goal of this all is that we have type definitions. We need them, because we don't see the generated code and this is the only way the IDE is able to know which properties to expect**

### Describe alternatives you've considered

An alternative would be to support typescript as an loader output, but this is probably a lot more effort

**Comment by BierDav** [comment]
According to the webpack documenation there are properties which this loader uses that are only webpack compatible: [Webpack Documenation](https://webpack.js.org/api/loaders/#webpack-specific-properties)

So this issues doesn't make a lot of sense because it is not the intention of this project to implement/simulate this feature

**Comment by BierDav** [comment]
After more research, I have found out that there is no proper way to do have a ts-loader, because a lot of basic functionalities to provide such a loader don't exist for now. So I've edited the issue that we need support for typescript loaders in any way

**Comment by sokra** [comment]
Is `appendTsSuffixTo` the only option you need?

Turbopack already has a built-in typescript pipeline and `tsconfig` would already be handled by that.

I think what you like to do it to pass this `yaml` file through the loader first and afterwards into the existing Typescript pipeline. Is that correct?

**Comment by ForsakenHarmony** [comment]
Going to close this as there hasn't been any response

**Comment by BierDav** [comment]
Still an issue, but we don't use next anymore so it isn't relevant
