### ISSUE TITLE
[turborepo] nest js can not use hot reload with turborepo

### ISSUE THREAD

**Issue by GDdark** [vercel/turbo#4825]
### What version of Turborepo are you using?

1.9.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

nest js can use hot reload In a separate project
However, when integrated into turborepo, it does not work properly

https://docs.nestjs.com/recipes/hot-reload

### Expected Behavior

work!!

### To Reproduce

Related link：https://github.com/vercel/next.js/issues/37395

**Comment by anthonyshew** [comment]
With the new Watch Mode, you can solve this outside of Nest.js. Ongoing discussion: https://github.com/vercel/turbo/issues/8317
