### ISSUE TITLE
Failing to use prisma after following guide

### ISSUE THREAD

**Issue by bfg-coding** [vercel/turbo#4826]
### What version of Turborepo are you using?

1.9.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

After following the [guide](https://turbo.build/repo/docs/handbook/tools/prisma#4-setting-up-the-scripts) on how to add Prisma I started having the following bug show up 

```
Error: Your schema.prisma could not be found, and we detected that you are using Next.js
```

I can interact with the schema file like the article says but when I actually interact with it in my code I have this error pop up

### Expected Behavior

Be able to have my prisma setup in a package to be shared between my apps

### To Reproduce

New turborepo project and adding prisma following the [guide](https://turbo.build/repo/docs/handbook/tools/prisma#4-setting-up-the-scripts)

Try to create a new record and get the error mentioned above

**Comment by anthonyshew** [comment]
We've recently updated the examples! If you continue to have problems, please open a new issue.
