### ISSUE TITLE
Set `INIT_CWD` environment variable

### ISSUE THREAD

**Issue by schickling** [vercel/turbo#485]
### Describe the feature you'd like to request

Please set the `INIT_CWD` environment variable properly when executing a command (e.g. in a sub directory). This is a "soft standard" followed by NPM, Yarn and PNPM.

Related:

- https://yarnpkg.com/getting-started/qa#how-to-share-scripts-between-workspaces
- https://github.com/npm/cli/issues/2033
- https://github.com/pnpm/pnpm/blob/0027785595c5296231e555e0180068c79fda98e0/packages/lifecycle/src/runLifecycleHook.ts#L64

**Comment by anthonyshew** [comment]
This can be done by [installing Turborepo globally](https://turbo.build/repo/docs/installing#install-globally).
