### ISSUE TITLE
Support i18n in next.js configuration

### ISSUE THREAD

**Issue by laakal** [vercel/turbo#4859]
### Which project is this feature idea for?

Turbopack

### Describe the feature you'd like to request

Unsupported Next.js configuration option(s) (next.config.js)
  To use Turbopack, remove the following configuration options:
    - i18n.locales
    - i18n.defaultLocale

### Describe the solution you'd like

Support i18n

### Describe alternatives you've considered

N/A

**Comment by michielmetcake** [comment]
Any ideas on a solution for this issue? I'd like to try out turbo

**Comment by oliverjohns** [comment]
A large portion of nextjs apps are missing out on Turbopack because of this 😢

**Comment by eddahbihossine** [comment]
(0 , __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__.createContext) is not a function
    at [project]/node_modules/react-i18next/dist/es/context.js [app-rsc] (ecmascript) <locals> (node_modules/react-i18next/dist/es/context.js:6:39)
    at instantiateModule ($PATH)
