### ISSUE TITLE
[turborepo] Exclude noneffectual changes in scripts from global hash changes.

### ISSUE THREAD

**Issue by danfernand** [vercel/turbo#4877]
### What version of Turborepo are you using?

1.9.4-canary.7

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

when trying to ignore the main package.json in my monorepo it does not seem to allow the ignoring
```
    "build": "turbo run build --ignore='package.json' --filter='...[main]'",
```

Below is my turbo.json
```
{
  "$schema": "https://turbo.build/schema.json",
  "globalDependencies": ["**/.env.*local"],
  "globalEnv": ["PORT"],
  "pipeline": {
    "build": {
      "outputs": [
        "dist/**",
        ".next/**",
        "!.next/cache/**",
        "build/**",
        "api/**",
        "public/build/**"
      ],
      "dependsOn": ["^build"]
    },
    "test": {
      "outputs": ["coverage/**"],
      "dependsOn": []
    },
    "lint": {
      "dependsOn": []
    },
    "dev": {
      "dependsOn": [],
      "cache": false,
      "persistent": true
    },
    "clean": {
      "cache": false
    }
  }
}
```

### Expected Behavior

the expected behavior is to ignore any changes to the package.json

### To Reproduce

clone the kitchen sink example - https://vercel.com/templates/remix/turborepo-kitchensink

add the build task and the main branch and run yarn build

**Comment by nathanhammond** [comment]
A couple of notes here:

1. `--ignore` has lots of issues and we're aiming to remove it. If you want a particular outcome for ignoring include that inside of `turbo.json`.
2. You're not allowed to ignore `package.json`; we decide based upon our knowledge of the project whether or not to include that file into the hash. We elect to over-partition the hash to be safe. We know that this reduces the frequency of cache hits, but we still do piecewise inclusion of the file if you have a lockfile.

In this case we don't yet have an optimization in place that detects that the added script was not previously part of any `turbo` graph, so we simply invalidate the entire build. There's an opportunity for improvement here, but the behavior is still "correct" as is, just suboptimal.

**Comment by anthonyshew** [comment]
Going to close for a couple historical reasons:
- `--ignore` has been deprecated
- We have a newer approach around the workspace root more generally that has some overlap with what's described here.
- Granular control of which files impact global hashes can be handled using `inputs` and the new `$TURBO_DEFAULTS$` microsyntax.
