### ISSUE TITLE
Preserve terminal color output

### ISSUE THREAD

**Issue by finnatsea** [vercel/turbo#4882]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Turbo is stripping the color off of some commands. Maintaining the original color output can be extremely useful for readability and accessibility, depending on the application. Below are screenshots from a jest test run showing the difference.

### With Turborepo
<img width="827" alt="Screenshot 2023-05-09 at 3 16 48 PM" src="https://github.com/vercel/turbo/assets/43194191/cdedf5f1-7466-4507-bb09-6fe3df699c41">

### Without Turborepo
<img width="699" alt="Screenshot 2023-05-09 at 3 17 30 PM" src="https://github.com/vercel/turbo/assets/43194191/770b33d2-010b-4545-afc6-55330b128495">

### Describe the solution you'd like

Allow passing a flag to turbo to preserve colors. I think the flag should be `--preserve-color,` but I'm open to alternatives.

### Describe alternatives you've considered

It's possible that preserving the original output color should be the default for accessibility reasons, but I think providing the option is probably sufficient.

**Comment by jackmcintire** [comment]
I would also like this

**Comment by chris-olszewski** [comment]
I'm afraid to say this has been a longstanding issue and isn't a simple fix. In good news this along with richer terminal support for tools like jest made it onto the turbo team's roadmap for this quarter.

Closing in favor of #223
