### ISSUE TITLE
[turborepo] Performance tanked with latest 1.9.4

### ISSUE THREAD

**Issue by AddictArts** [vercel/turbo#4912]
### What version of Turborepo are you using?

1.9.4

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

Regardless of the daemon or `--no-daemon` it now takes seconds to launch or at least show any output. It used to spit output out within milliseconds prior to this version.

This eliminates the good thing about turbo. Within the same time I can use the CLI with `npm` to achieve the same tasks.

### Expected Behavior

Start showing output of tasks quickly

### To Reproduce

Run on windows with any decent amount of tasks and dependencies.

**Comment by nathanhammond** [comment]
Hey @AddictArts! I'm shipping a 1.9.5-canary.1 which _may_ address the issue. It's about 30 minutes from being released: https://github.com/vercel/turbo/actions/runs/4980939212

Can you give that a try and let me know?

**Comment by AddictArts** [comment]
@nathanhammond  ... Yes it did, thank you. Fantastic. This can be closed.
