### ISSUE TITLE
[turborepo] Scope and build directory not working as expected

### ISSUE THREAD

**Issue by abrisco** [vercel/turbo#4933]
### What version of Turborepo are you using?

1.9.4

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I've created a repo to demonstrate the issue. The content below is based on this repo: https://github.com/abrisco/turborepo_example

When building in a subdirectory of a repo, I'm able to run `turbo run build` and have only the packages beneath it run

```
~/Code/turborepro/packages (main ✗) turbo run build
• Packages in scope: @turborepo_example/bar, @turborepro/foo
• Running build in 2 packages
• Remote caching disabled
@turborepro/foo:build: cache bypass, force executing eee5c8aa1d0b1873
@turborepo_example/bar:build: cache bypass, force executing 98128fcb45dc629a
@turborepro/foo:build:
@turborepro/foo:build: > @turborepro/foo@1.0.0 build /Users/user/Code/turborepro/packages/foo
@turborepro/foo:build: > echo build
@turborepro/foo:build:
@turborepo_example/bar:build:
@turborepo_example/bar:build: > @turborepo_example/bar@1.0.0 build /Users/user/Code/turborepro/packages/bar
@turborepo_example/bar:build: > echo build
@turborepo_example/bar:build:
@turborepo_example/bar:build: build
@turborepro/foo:build: build

 Tasks:    2 successful, 2 total
Cached:    0 cached, 2 total
  Time:    280ms
```

However, if I try to restrict the tasks to just a specific package using [--scope](https://turbo.build/repo/docs/reference/command-line-reference#--scope) I end up seeing tasks
run from a different directory. Given that I set the scope to a specific package I would have expected only the package matching `--scope` to be run, but for some reason a reverse
dependency is triggered

```
~/Code/turborepro/packages (main ✗) turbo run build --scope='@turborepro/foo'
• Packages in scope: @turborepro/baz, @turborepro/foo
• Running build in 2 packages
• Remote caching disabled
@turborepro/foo:build: cache bypass, force executing eee5c8aa1d0b1873
@turborepro/foo:build:
@turborepro/foo:build: > @turborepro/foo@1.0.0 build /Users/user/Code/turborepro/packages/foo
@turborepro/foo:build: > echo build
@turborepro/foo:build:
@turborepro/foo:build: build
@turborepro/baz:build: cache bypass, force executing 0f9190d101cac862
@turborepro/baz:build:
@turborepro/baz:build: > @turborepro/baz@1.0.0 build /Users/user/Code/turborepro/apps/baz
@turborepro/baz:build: > echo build
@turborepro/baz:build:
@turborepro/baz:build: build

 Tasks:    2 successful, 2 total
Cached:    0 cached, 2 total
  Time:    485ms
```

This behavior occurs when using glob patterns as well. The packages in scope don't make sense since I'm in a sub directory that does not include the `@turborepro/baz` package.

```
~/Code/turborepro/packages (main ✗) turbo run build --scope='@turborepro/*'
• Packages in scope: @turborepro/baz, @turborepro/foo
• Running build in 2 packages
• Remote caching disabled
@turborepro/foo:build: cache bypass, force executing eee5c8aa1d0b1873
@turborepro/foo:build:
@turborepro/foo:build: > @turborepro/foo@1.0.0 build /Users/user/Code/turborepro/packages/foo
@turborepro/foo:build: > echo build
@turborepro/foo:build:
@turborepro/foo:build: build
@turborepro/baz:build: cache bypass, force executing 0f9190d101cac862
@turborepro/baz:build:
@turborepro/baz:build: > @turborepro/baz@1.0.0 build /Users/user/Code/turborepro/apps/baz
@turborepro/baz:build: > echo build
@turborepro/baz:build:
@turborepro/baz:build: build

 Tasks:    2 successful, 2 total
Cached:    0 cached, 2 total
  Time:    485ms
```

### Expected Behavior

When building in https://github.com/abrisco/turborepo_example I expect the results in the table below:

| directory | command | expected scope |
| --- | --- | --- |
| ./ | `turbo run build --scope='@turborepro/*` |  @turborepro/foo @turborepro/baz |
| ./ | `turbo run build --scope='@turborepro/foo` |  @turborepro/foo |
| ./packages | `turbo run build --scope='@turborepro/*` |  @turborepro/foo |
| ./packages | `turbo run build --scope='@turborepro/foo` |  @turborepro/foo |

### To Reproduce

Clone https://github.com/abrisco/turborepo_example and run the same commands described in the ticket.

### Reproduction Repo

https://github.com/abrisco/turborepo_example

**Comment by abrisco** [comment]
Related, is it possible to run a *specific* task from a specific package? My hope is to be able to run `turbo run '@turborepro/foo#build'` and have only the build task from that package be executed (with dependency tasks as an exception).

**Comment by anthonyshew** [comment]
Closing as `--scope` is deprecated: https://turbo.build/repo/docs/reference/command-line-reference/run#--scope
