### ISSUE TITLE
[turborepo] Adopt Conventional Commits for friendlier Changelog

### ISSUE THREAD

**Issue by b12k** [vercel/turbo#4939]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Every time when new version of turborepo is release I go to check release notes.
Due to lack of convention in naming commits it is hard to identify what was fixed, added etc.

### Describe the solution you'd like

Using [Conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) and [Conventional changelog](https://github.com/conventional-changelog/conventional-changelog) should enforce consistency and better readability of being changed. Using `scope` and proper commit types `feat`, `fix`, `docs`, `chore` will automatically make changelog easy to read and identify changes.  

### Describe alternatives you've considered

None

**Comment by chris-olszewski** [comment]
Thanks for the suggestion. I brought this to the team and we decided that we'll do a week long test period of using conventional commits before committing to it long term. Will update next week with a decision.

**Comment by MikelArnaiz** [comment]
@chris-olszewski 

I was wondering if you decide anything about this, but also how was it set up if I want to do it myself.
Isn't versioning handled [by other libs](https://turbo.build/repo/docs/handbook/publishing-packages/versioning-and-publishing) like changesets?

**Comment by anthonyshew** [comment]
We did some work to clean up our release notes! Check them out:
