### ISSUE TITLE
[turborepo] program not found error after upgrading to v1.9.4

### ISSUE THREAD

**Issue by XDoubleU** [vercel/turbo#4940]
### What version of Turborepo are you using?

1.9.4

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

After upgrading to v1.9.4 I get a ‘program not found’ error when trying to run a script. I managed to pinpoint this error to canary v8.

### Expected Behavior

I expect my scripts to run as in v1.9.3

### To Reproduce

In below repo after running ‘yarn install’, run ‘yarn add -W turbo@1.9.4’ and run ‘yarn test’.

### Reproduction Repo

https://github.com/XDoubleU/check-in

**Comment by kefniark** [comment]
Getting the same error, monorepo script working until 1.9.3, and doesn't work inmodern versions.
```sh
$ yarn turbo run build
$ project\node_modules\.bin\turbo run build
Error: program not found
error Command failed with exit code 1.
```

On similar archi:
* Yarn v1
* OS: windows 11 64bit

**Comment by bartyx1993** [comment]
Same issue on Win11 64bit after upgrading to 1.9.6. 
Revert to the older version doesn't work for me.

**Comment by NicholasLYang** [comment]
Hi @XDoubleU, thanks for opening an issue. Turns out this is an issue with how we detect package manager versions. We should have a fix up shortly!

**Comment by gsoltis** [comment]
@bartyx1993 @kefniark @XDoubleU 

Can you verify that `turbo@1.9.7` is working for you?

**Comment by XDoubleU** [comment]
Is working for me, thanks!

**Comment by bartyx1993** [comment]
Is working for me, thanks!

**Comment by trandachuy2002** [comment]
Turborepo failed to start.

Turborepo detected that you are running:
windows ia32

**Comment by hollandz** [comment]
> Turborepo failed to start.
> 
> Turborepo detected that you are running: windows ia32

Did you resolve this issue? I just ran into the same error.
