### ISSUE TITLE
Invalid 'main' field problem

### ISSUE THREAD

**Issue by paradise** [vercel/turbo#4954]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

npm, Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

Hi, I have a problem with my turbo project. I have `express` application under `apps` folder and several packages under `packages` folder. I'm using the Typescript.

Problem arises when I'm trying to run the project in the Docker container. 

For example, I have `db` package, in package.json of this package I have these lines: 
```
  "main": "./index.ts",
  "source": "./index.ts",
  "types": "./index.ts",
```

During the development everythig is fine, but if I build my project with Dockerfile and run it, I receive an error 

```
/app/packages/db/index.ts:1
export {
^^^^^^

SyntaxError: Unexpected token 'export'
```

This is because `main` property in package.json is `index.ts` (I have compiled version under /dist folder, but it is not used, because of this property).

So, to make it work, I assume, that I need to change `main` property to `/dist/index.js` (so that node runtime can handle it), but if I do so, I cannot run my project in development mode. Now error is 
```
backend:dev: DeprecationWarning: Invalid 'main' field in '<full path here>\db\package.json' of './dist/index.js'. Please either fix that or report it to the module author
backend:dev:     at tryPackage (node:internal/modules/cjs/loader:447:15)
backend:dev:     at Module._findPath (node:internal/modules/cjs/loader:678:18)
backend:dev:     at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
...
```

I have tried project from turbo examples, but got the same error.

### Expected Behavior

It should work both in development mode and in production mode. 

### To Reproduce

To reproduce, you can get [with-docker example](https://github.com/vercel/turbo/tree/main/examples/with-docker) and run `npm run dev`

### Reproduction Repo

https://github.com/vercel/turbo/tree/main/examples/with-docker

**Comment by paradise** [comment]
I made temporary fix, by adding small node script, which rewrites `package.json` before run:

```
const { readFileSync, writeFileSync } = require("fs");

var args = process.argv.slice(2);
const path = args[0];

const packageJson = readFileSync(path, "utf8");
const obj = JSON.parse(packageJson);

obj["main"] = "./dist/index.js";
obj["module"] = "./dist/index.mjs";
obj["types"] = "./dist/index.d.ts";

writeFileSync(path, JSON.stringify(obj), "utf8");
```

In  my Docker file I added two lines:
```
COPY rewriteConfig.js rewriteConfig.js
RUN node ./rewriteConfig.js /app/packages/db/package.json
```

**Comment by paradise** [comment]
Hi, thanks for the answer! But your example does not work out of the box now, maybe it should be fixed, to avoid the same issues in the future.

**Comment by teaglebuilt** [comment]
for me this is happening without docker as well

**Comment by teaglebuilt** [comment]
> for me this is happening without docker as well

the apps and packages folder end up in the `dist` folder of the application under `apps`

**Comment by anthonyshew** [comment]
The original issue sounds like a userland issue.

On examples, we've updated them recently. Please open an issue if you have any problems with them!
