### ISSUE TITLE
[turbopack] Error resolving server relative import: not implemented yet

### ISSUE THREAD

**Issue by panieldark** [vercel/turbo#4979]
### What version of Turborepo are you using?

Next: 13.4.2

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

<img width="958" alt="Screenshot 2023-05-16 at 10 16 06 AM" src="https://github.com/vercel/turbo/assets/21699995/262cf1aa-d103-4ec8-b519-19dd2822b075">

### Expected Behavior

Relative imports to work

### To Reproduce

Import an asset using relative import (`/public/` prefix shouldn't be necessary according to Next docs, but that's a different issue)

**Comment by NicholasLYang** [comment]
Hi @panieldark, this appears to be a turbopack issue. I'll relabel it accordingly

**Comment by panieldark** [comment]
Got it, thanks!

**Comment by jridgewell** [comment]
Hi @panieldark! Importing from `/public/…` directly isn't supported:

```js
import foo from "/public/foo.png"
```

Instead, you'll need to use the actual path to the thing you're trying to import, eg `"../public/foo.png"` (or the appropriate number of `../`s). Alternatively, you can configure TypeScript's `compilerOptions.paths` to alias an import of `"public/foo.png"` (notice that there's no leading `/`).

When we discussed this with the Next.js team, they expressed that this was an unintentional "feature" and isn't actually supposed to work by default. Instead, they recommend doing one of the above suggestions. The benefit of this is that if follows the conventions in the larger ecosystem, which is quickly adopting TS's `paths`, `package.json`'s `imports` field, and import maps in general.

**Comment by panieldark** [comment]
Good to know! Although, it seems a bit unexpected--Next.js use without turbopack allows for base imports (it's also in their docs, although I'm not in front of a computer at the moment). Since it's available in one, would love if it was consistent across the other!![image](https://github.com/vercel/turbo/assets/21699995/ae88b347-68ed-44ed-8f78-7352dc18ea33)

**Comment by jridgewell** [comment]
The Static Assets page is specifically referencing the `src` property of an `<img />` (or `<NextImage />` component), or a `background: url("…")` inside of a CSS file. In both cases, this doesn't mean to actually import the file into the JS module graph, but to point the asset when it is served from a server.

When using the `import foo from "/public/…"` import syntax, you're telling the bundler that this asset is actually part of the JS module graph, and it has to be turned into a JS object that can be manipulated.

I've added this feedback to our internal issue tracker as WEB-363

**Comment by RedBeardEth** [comment]
I have a similar issue using the @ardatan/sync-fetch  + graphql-tools/url-loader packages if you have any suggestions on how to fix. 

`error - [resolve]
  node_modules/@ardatan/sync-fetch
    Error resolving server relative import: not implemented yet
    unable to resolve server relative "/ROOT/node_modules/@ardatan/sync-fetch/worker.js"

  node_modules/@ardatan/sync-fetch/index.js
    node_modules/@ardatan/sync-fetch/index.js:41:10  Error resolving commonjs request
        37 |   }
        38 | }
        39 | 
        40 | function sendMessage (message) {
           |           v-----------------------------------------------------------
        41 +   return exec(process.execPath, [path.join(__dirname, 'worker.js')], {
        42 +     windowsHide: true,
        43 +     maxBuffer: Infinity,
        44 +     input: JSON.stringify(message),
        45 +     shell: false
        46 +   }).toString()
           +-----^
        47 | }
        48 | 
        49 | function extractContentType (input) {
        50 |   const request = new _fetch.Request(...input)
    
    unable to resolve server relative "/ROOT/node_modules/@ardatan/sync-fetch/worker.js" or dynamic

  node_modules/@graphql-mesh/utils/esm/defaultImportFn.js
    node_modules/@graphql-mesh/utils/esm/defaultImportFn.js:3:24  Error resolving EcmaScript Modules request
         1 | import { path as pathModule } from '@graphql-mesh/cross-helpers';
         2 | async function defaultImportFn(path) {
           |                         v-----------------------------
         3 +     let module = await import(/* @vite-ignore */ path)
         4 +         .catch(e => {
           +-
         5 |         if (e.code === 'ERR_REQUIRE_ESM') {
         6 |             // eslint-disable-next-line no-new-func
         7 |             return new Function(`return import(${JSON.stringify(path)})`)();
         8 |         }
    
    unable to resolve dynamic

  node_modules/@graphql-tools/url-loader/esm/index.js
    node_modules/@graphql-tools/url-loader/esm/index.js:11:37  Error resolving EcmaScript Modules request
         7 | import { defaultSyncFetch } from './defaultSyncFetch.js';
         8 | import { buildGraphQLWSExecutor } from '@graphql-tools/executor-graphql-ws';
         9 | import { buildHTTPExecutor, isLiveQueryOperationDefinitionNode, } from '@graphql-tools/executor-http';
        10 | import { buildWSLegacyExecutor } from '@graphql-tools/executor-legacy-ws';
           +                                      v---------------------v
        11 + const asyncImport = (moduleName) => import(`${moduleName}`);
           +                                      ^---------------------^
        12 | const syncImport = (moduleName) => require(`${moduleName}`);
        13 | export var SubscriptionProtocol;
        14 | (function (SubscriptionProtocol) {
        15 |     SubscriptionProtocol["WS"] = "WS";
    
    unable to resolve dynamic

    node_modules/@graphql-tools/url-loader/esm/index.js:12:36  Error resolving commonjs request
         8 | import { buildGraphQLWSExecutor } from '@graphql-tools/executor-graphql-ws';
         9 | import { buildHTTPExecutor, isLiveQueryOperationDefinitionNode, } from '@graphql-tools/executor-http';
        10 | import { buildWSLegacyExecutor } from '@graphql-tools/executor-legacy-ws';
        11 | const asyncImport = (moduleName) => import(`${moduleName}`);
           +                                     v----------------------v
        12 + const syncImport = (moduleName) => require(`${moduleName}`);
           +                                     ^----------------------^
        13 | export var SubscriptionProtocol;
        14 | (function (SubscriptionProtocol) {
        15 |     SubscriptionProtocol["WS"] = "WS";
        16 |     /**
    
    unable to resolve dynamic

  node_modules/node-gyp-build/node-gyp-build.js
    node_modules/node-gyp-build/node-gyp-build.js:22:10  Error resolving commonjs request
        18 | 
        19 | module.exports = load
        20 | 
        21 | function load (dir) {
           |           v-------------------------------
        22 +   return runtimeRequire(load.resolve(dir))
        23 + }
           +-
        24 | 
        25 | load.resolve = load.path = function (dir) {
        26 |   dir = path.resolve(dir || '.')
        27 | 
    
    unable to resolve dynamic`

**Comment by Riicksouzaa** [comment]
<details>

<summary>Try this tsconfig</summary>

```json
{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": [
    "**/*.cjs",
    "**/*.js",
    "**/*.json",
    "**/*.jsx",
    "**/*.mjs",
    "**/*.mts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts",
    "next-env.d.ts",
    "build/types/**/*.ts"
  ],
  "exclude": ["node_modules", "dist", "build", ".next"]
}

```

</details>
