### ISSUE TITLE
[turborepo] early exit when trying to use rollup's watch mode

### ISSUE THREAD

**Issue by NullVoxPopuli** [vercel/turbo#4983]
### What version of Turborepo are you using?

1.9.6

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

rollup's watch mode is killed by turbo, or not waited for?, hard to tell.

### Expected Behavior

`turbo` does not early exit, and rollup continues building / watching for changes.

### To Reproduce

Also written here: https://github.com/NullVoxPopuli/limber/pull/926

1. `git clone git@github.com:NullVoxPopuli/limber.git`
2. `cd limber`
3. `git checkout how-to-get-turbo-rollup-watching`
4. `pnpm i --ignore-scripts`
5. observe that in `packages/ember-repl/addon/package.json` the `start` script is `rollup --config --watch`
6. try to start watch mode via turbo: `pnpm turbo start --filter ember-repl`
7. observe that turbo exited, when it should have not-exited due to rollup being in watch mode
8. `cd packages/ember-repl/addon`
9. `pnpm start`
10. observe that the `start` script in this package is a long-running watch mode that doesn't exit unless `Ctrl+C` is pressed (or some other kill/stop process signal is sent to the process)

### Reproduction Repo

https://github.com/NullVoxPopuli/limber/pull/926

**Comment by nathanhammond** [comment]
Hey @NullVoxPopuli! As a first pass I looked at the `turbo.json` and your command (filtered) and it seems not likely to be the case, but: is it possible that you have another task in the execution which is exiting non-zero? Unless you specify `--continue` `turbo` will bail at the exact moment any task exits non-zero.

Dropping this as a "just in case" bit of feedback, will take a more-detailed pass later.

**Comment by NullVoxPopuli** [comment]
Hello! Thanks for looking in to this!

> it possible that you have another task in the execution which is exiting non-zero? 

I don't think so -- in the reproduction, there are no other tasks?

**Comment by mehulkar** [comment]
I can reproduce this in a much simpler example too: https://github.com/mehulkar/turbo-issue-4983. Need to look into how the rollup executable works. I tried passing `--no-stdin` to rollup just in case I'd get lucky with that explanation, but that didn't work.

**Comment by mehulkar** [comment]
Ok , this seems somewhat related to https://github.com/rollup/rollup/pull/5004 and related issues pointed there. I tried rollup@3.20 in the example and it seems to work. I've updated the readme in the instructions to show how it working with the older version.
