### ISSUE TITLE
[turborepo] Support for Go

### ISSUE THREAD

**Issue by muuvmuuv** [vercel/turbo#5004]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

We would like to move our go gin server into our frontend monorepo. We allready use turbo for Astro with Svelte. 

### Describe the solution you'd like

A go adapter to run, build, install deps, lint, test and format go code.

### Describe alternatives you've considered

Plugin system to add it ourself?

**Comment by NicholasLYang** [comment]
Hi @muuvmuuv, unfortunately this is not on our roadmap currently. However, as a work around, you can add a package.json to the relevant Go projects and add scripts that do the relevant actions:

```
{
  "name": "go-server",
  "scripts": {
    "build": "go build ./cmd/foobar"
  }
}
```

In fact, this is exactly how we use Turborepo ourselves, by having a [cli/package.json](https://github.com/vercel/turbo/blob/main/cli/package.json) that calls the relevant make commands.

**Comment by muuvmuuv** [comment]
Oh ok, thought since its written in go/rust it would be something for the future. 

Yes, we already use the package.json. Just thought having all in a cli included would have a more mono feeling.

**Comment by khabubuphathu** [comment]
In my mono repo I have a `package.json` with the following build script
```
{
  "scripts": {
    "build": "turbo run build"
  }
}
```

In my go project I have the following build script
```
{
  "scripts": {
    "build": "cross-env GOARCH=amd64 GOOS=linux go build -ldflags \"-X 'github.com/test/synks/daemon/internal.Version=$npm_package_version'\" -o ./daemon-amd64 ./cmd/daemon/main.go"
  }
}
```

When I run `npm run build` in the root of my monorepo I get the follwing error
`build cache is required, but could not be located: GOCACHE is not defined and %LocalAppData% is not defined`

But if I run the same command in the directory of my go project I don't get and error

**Comment by jrab** [comment]
> In my mono repo I have a `package.json` with the following build script
> 
> ```
> {
>   "scripts": {
>     "build": "turbo run build"
>   }
> }
> ```
> 
> In my go project I have the following build script
> 
> ```
> {
>   "scripts": {
>     "build": "cross-env GOARCH=amd64 GOOS=linux go build -ldflags \"-X 'github.com/test/synks/daemon/internal.Version=$npm_package_version'\" -o ./daemon-amd64 ./cmd/daemon/main.go"
>   }
> }
> ```
> 
> When I run `npm run build` in the root of my monorepo I get the follwing error `build cache is required, but could not be located: GOCACHE is not defined and %LocalAppData% is not defined`
> 
> But if I run the same command in the directory of my go project I don't get and error

my hunch is that there is a scoping issue and your environment variables are not being read or its using incorrect go configurations -- maybe find a way to ensure all of that is being passed into the subprocess?
