### ISSUE TITLE
[turborepo] turbo gen workspace error

### ISSUE THREAD

**Issue by liamfend** [vercel/turbo#5015]
### What version of Turborepo are you using?

1.9.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

**I created a project with**
`pnpm dlx create-turbo@latest`

**Now I am adding a package using**  
`pnpm dlx turbo gen workspace --name @mytest/icons`
 **and I get an error:**

pnpm dlx turbo gen workspace --name @mytest/icons  
ERROR Unexpected parameter '--name' was found. 
  Note: To use '--name' as a value, use '--name'. 
Usage: turbo --skip-infer <--cache-dir <CACHE_DIR>|-cache-workers <CACHE_WORKERS>|-concurrency <CONCURRENCY>|-continue|-dry-run [<DRY_ RUN>]|--single-package|-- --filter <FILTER>|--force|--global-deps <GLOBAL_DEPS>|--graph [<GRAPH>]|--experimental-env-mode [<ENV_MODE>]| --ignore <IGNORE>|--include-dependencies|-- no-cache|--no-daemon|--no-deps|--output-logs <OUTPUT_LOGS>|--only|--parallel|--pkg- inference-root <PKG_INFERENCE_ROOT>|--profile <PROFILE>|--remote-only|--. --scope <SCOPE>|-since <SINCE>|-summarize [<SUMMARIZE>]|--log-preix <LOG_PREFIX>|TASKS|PASS_THROUGH_ARGS|--experimental-space-id < EXPERIMENTAL_SPACE_ID>>. 
 
If I use the
`pnpm dlx turbo gen workspace `
I get the following error
 ERROR Failed to run: Error preparing the engine: The following task could not be found in the project: gen, workspace
ERROR turbo: Error preparing engine: The following task could not be found in the project: gen, workspace

### Expected Behavior

create a pkg successful

### To Reproduce

no need.

**Comment by tknickman** [comment]
This API shifted a bit ahead of release and `gen` is only available in 1.9.7 and newer! (this will be officially released in 1.10.0).

Try `pnpm dlx turbo@latest gen workspace --name @mytest/icons`

Also, make sure the version of `turbo` in your repo is also 1.9.7 or newer.
