### ISSUE TITLE
[turborepo] sometimes not generate dist directory or There is no d.ts file under dist

### ISSUE THREAD

**Issue by vaynevayne** [vercel/turbo#5045]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

pnpm run clean 
pnpm run dev 

Then open vscode, one with dist but no corresponding d.ts file, and the other package without a dist directory at all

<img width="1476" alt="image" src="https://github.com/vercel/turbo/assets/124666577/c28eef2c-6322-44be-ae6b-8dece14024d8">

### Expected Behavior

There are dist directories and d.ts files

https://github.com/vaynevayne/soul

### To Reproduce

pnpm run clean 
pnpm run dev 

### Reproduction Repo

https://github.com/vaynevayne/soul

**Comment by vaynevayne** [comment]
> @vaynevayne did you solve this? I'm running into the same problem

@MindaugasMateika  The reason is that you must resolve all the ts errors or the ts file will not be generated

**Comment by alexandrucancescu** [comment]
@vaynevayne I dont have any ts error for that package and it still does not generate a dist folder. it then moves to building a package that depends on this dist.
