### ISSUE TITLE
[turbopack] Dynamic routing throws error when using an encoded path with spaces in it.

### ISSUE THREAD

**Issue by bjk95** [vercel/turbo#5051]
### What version of Next.js are you using Turbopack in?

13.4

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When using the following dynamic route the subsequent error is thrown. This occurs when the components are encoded using encodeURIComponent and does not occur when I switch back to webpack.

error during Next.js routing for /console/corpus/Mo9kXKe2j62P/Cambodia & Thailand Trip.md

Caused by:
- router evaluation failed: no message received from javascript stream

Debug info:
- Execution of get_from_source failed
- Execution of resolve_source_request failed
- Execution of NextRouterContentSource::get failed
- error during Next.js routing for /console/corpus/Mo9kXKe2j62P/Cambodia & Thailand Trip.md
- router evaluation failed: no message received from javascript stream

### Expected Behavior

Parse the encoded URL

### To Reproduce

Try go to a URL with spaces in it (when encoded, %20).

**Comment by Dave-lab12** [comment]
I am having the same issue 

Using encodeURIComponent on [Turbopack](https://turbo.build/pack) throws error 
## Reproduction Repo 
https://codesandbox.io/p/sandbox/youthful-curran-9zp6ch

**Comment by ForsakenHarmony** [comment]
The original issue is no longer applicable (should work fine now)
