### ISSUE TITLE
[turborepo] Verbose logging not verbose enough to determine if remote caching works

### ISSUE THREAD

**Issue by weyert** [vercel/turbo#5074]
### What version of Turborepo are you using?

1.9.8

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I am having issues were the remote caching functionality doesn't work. If I try to build an application twice in Docker or Gitlab CI it always says it can not find a cache miss. Even when I build locally it doesn't appear to upload the cache. 

Currently, it's hard to debug whether it trying to upload the cache entries to api or not. Even when you use `--verbosity=6` it doesn't show anything. 

### Expected Behavior

I would expect that when I increase the verbosity log level it will get chatty enough to also see any in- or outgoing http requests e.g. to the remote cache api

### To Reproduce

Hard to reproduce

**Comment by chris-olszewski** [comment]
This was addressed with the port to Rust. In Go we were discarding all cache related errors and we now print this as warnings.
