### ISSUE TITLE
rich glob pattern (e.g. support of `!`, `()`, etc)

### ISSUE THREAD

**Issue by jjangga0214** [vercel/turbo#5093]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

It seems it does not support widely-used styles of glob pattern, like `!` and `()`, which can be used like the below snippet just for example.

```json
{
  "inputs": ["(src,test)/**/*.(js,jsx,ts,tsx)", "!test/foo.js"]
}
```

Is there a special reason?
Thanks.

### Describe the solution you'd like

Add support would be great.

### Describe alternatives you've considered

None.

**Comment by mehulkar** [comment]
`!` should work already, are you having trouble with it? We have a passing test for it as well: https://github.com/vercel/turbo/blob/main/turborepo-tests/integration/tests/excluded_inputs.t

**Comment by anthonyshew** [comment]
According to what we've specified in the documentation, this is supported today: https://turbo.build/repo/docs/reference/configuration#glob-specification-for-paths

If you have any troubles with it, please do open a bug report.
