### ISSUE TITLE
[turbopack] Not working with Mobx-state-tree

### ISSUE THREAD

**Issue by miltonlaufer** [vercel/turbo#5110]
### What version of Next.js are you using Turbopack in?

13.4.4

### What package manager are you using / does the bug impact?

npm, Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

On project that use mobx-state-tree, when I run 
`next dev --turbo`

it gets to this message:
```console
>>> TURBOPACK (beta)

Thank you for trying Next.js v13 with Turbopack! As a reminder,
Turbopack is currently in beta and not yet ready for production.
We appreciate your ongoing support as we work to make it ready
for everyone.

Learn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack
Please direct feedback to: https://nextjs.link/turbopack-feedback

ready - started server on [::]:3000, url: http://localhost:3000
```

But the server is not responding and no error message appears. 
The same projects work perfectly using `next dev`

### Expected Behavior

To work the same way as it works with `ǹext dev` (but faster! :) )

### To Reproduce

For example, clone this repo: https://github.com/ecklf/react-hooks-mobx-state-tree.git and upgrade all the relevant packages (all these steps are already done in the repo referenced below): 

```console
git clone https://github.com/ecklf/react-hooks-mobx-state-tree.git
cd mobx-state-tree
#Lets upgrade all the packages
yarn upgrade next@latest react@latest react-dom@latest eslint-config-next@latest  yarn upgrade mobx@latest mobx-react-lite@latest mobx-state-tree@latest
```

You'll need to edit `next.config.js` too:

```javascript
module.exports = {
 // Comment these lines
//  future: {
//    webpack5: true,
//  },
};
```

Then, if you run `yarn dev` everything works great. 

But if you run `next dev --turbo` the behaviour es the same as described above. 

### Reproduction Repo

https://github.com/miltonlaufer/nextjs-turb-mst-problem

**Comment by cannc4** [comment]
any updates on this?

**Comment by miltonlaufer** [comment]
Hi! Does anyone know if there was any work on this? It's been a while and I'm a bit surprised Next.js is not interested in being compatible with one of the most used state managers out there.

**Comment by ForsakenHarmony** [comment]
@miltonlaufer there's a good chance this was fixed in the meantime, a lot has changed including the approach to turbopack

I'm going to close this for now, if you're still running into problems feel free to open a new issue in the next.js repo (that's where we're tracking turbopack issues now as it's only used in next.js so far)

**Comment by miltonlaufer** [comment]
@ForsakenHarmony Thanks for your reply. Just tested it again, all libraries with their latest versions, and unfortunately it didn't work. 
I'll follow your advise and open an issue there.
