### ISSUE TITLE
[Turborepo] Add supporting to pnpm-lock.yaml v.6.1

### ISSUE THREAD

**Issue by Dwlad90** [vercel/turbo#5117]
### What version of Turborepo are you using?

1.9.9

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Turbo prune not support to pnpm-lock.yaml v6.1.

When run the next command:
`turbo prune --docker --scope=<workspace>`

turbo throw exception:
`Turbo error: Failed to encode pruned lockfile: Unable to generate pnpm-lock.yaml with lockfileVersion: 6.1. Supported lockfile versions are [5.3 5.4 6.0]`

### Expected Behavior

Prune workspace successfully

### To Reproduce

1. Install pnpm@8.6.0
2. run `pnpm install`
3. run `turbo prune --docker --scope=<workspace>`

**Comment by weyert** [comment]
Yeah, some settings are getting stored in the `pnpm` file now. I think it's safe to ignore them

**Comment by ChiuMungZitAlexander** [comment]
I think it is working now.

**Comment by edouardr** [comment]
> I think it is working now.

nothing is mentioned in the changelog of [v.1.10.0](https://github.com/vercel/turbo/releases/tag/v1.10.0).
I have also tested for the sake of it, and it is still an issue.

**Comment by piyushchauhan2011** [comment]
still an issue, just tried with v1.10.1
```
#0 0.484  ERROR  Failed to encode pruned lockfile: Unable to generate pnpm-lock.yaml with lockfileVersion: 6.1. Supported lockfile versions are [5.3 5.4 6.0]
#0 0.484 Turbo error: Failed to encode pruned lockfile: Unable to generate pnpm-lock.yaml with lockfileVersion: 6.1. Supported lockfile versions are [5.3 5.4 6.0]
```

**Comment by rayepps** [comment]
Can confirm that manually changing the version `6.1` to `6.0` in the lockfile will get it to work. We know we're playing with fire doing this but for our use case we don't have any better choices. In CI/CD we use this `sed` just before pruning.

```
sed -i -e "s/lockfileVersion: '6.1'/lockfileVersion: '6.0'/g" pnpm-lock.yaml
```

*cred to @manas-vessel

**Comment by piyushchauhan2011** [comment]
Until the upgrade comes, for now we just use pnpm version 7.32.5 which has lockfile 6.0 support. I think pnpm 7.3.0 generates 5.4 version. I would recommend to stick to old version until this upgrade comes for turborepo

**Comment by tuahear** [comment]
This is already resolved by #5195

**Comment by Dwlad90** [comment]
Confirm, with turbo@1.10.3 work perfect

**Comment by weyert** [comment]
Please note about this potential numbering change:
https://github.com/pnpm/pnpm/issues/6648
