### ISSUE TITLE
Add documentation for `--out-dir` flag for `turbo prune`

### ISSUE THREAD

**Issue by maschwenk** [vercel/turbo#5132]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Previously we used [pnpm-isolate-workspace](https://www.npmjs.com/package/pnpm-isolate-workspace) for similar functionality. The one nice thing about that is we could install it in the project/app and all the output could be relative to that project. Why does this matter? Because it means you can prune multiple apps in parallel. This allows you to build/deploy apps in parallel on a given machine.

Note this is something I'm happy to implement myself. Just want to get signoff that this is a feature that would be accepted before I open the PR

### Describe the solution you'd like

A flag to override the location and/or name of the folder that `prune` uses. 

### Describe alternatives you've considered

🤷🏼 

<sub>[TURBO-1138](https://linear.app/vercel/issue/TURBO-1138/allow-turbo-prune-output-location-to-be-overidden)</sub>

**Comment by mehulkar** [comment]
Are you maybe looking for the `--out-dir` flag? 
https://github.com/vercel/turbo/blob/b0b69a1f8ca65349d3c057de79f92531f3bdf540/crates/turborepo-lib/src/cli.rs#L314

Looks like it isn't documented though: https://turbo.build/repo/docs/reference/command-line-reference#turbo-prune---scopetarget. 

If that's what you're looking for let me know and we'll add it into the docs

**Comment by maschwenk** [comment]
😂 indeed. Was looking in docs but didn't see. Excellent.
