### ISSUE TITLE
[turborepo] The results provided by turbo-ignore do not meet expectations

### ISSUE THREAD

**Issue by qigemingzizenmezhemekunnan** [vercel/turbo#5136]
### What version of Turborepo are you using?

1.10.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When I use npx turbo-ignore -- fallback=HEAD~10 or npx turbo-ignore -- fallback=[SHA], I find it always prompts me ⏭ Ignoring the change（ Unless I make relevant modifications in HEAD ^, turbo ignore doesn't seem to care about my specified commit, it only compares with HEAD ^

for example I modified packages/A and submitted a commit. Assuming the SHA of this commit is 001, when I run `npx turbo ignore packages/A -- fallback=001` its judgment is normal and it will prompt me to `Proceeding with deployment`; Then I modified packages/B, packages/c, or unrelated files and submitted multiple commits. At this point, I ran npx turbo ignore packages/A again -- fallback=001, and it prompted me    `⏭ Ignoring the change`

### Expected Behavior

When there are related modifications to the commit I specify, it should prompt me to `✓ Processing with deployment`

### To Reproduce

1. Modify a file in package/A and submit commit [001]
2. Execute Command `npx turbo ignore packages/A -- fallback=001`  (It's normal at this point, prompt me `✓ Processing with deployment`
3. Modify a file in package/B and submit commit [002]
4. Modify a file in package/C and submit commit [003]
5.  Execute Command `npx turbo ignore packages/A -- fallback=001` （It's abnormal at this point, prompt me  `⏭ Ignoring the change`

**Comment by tknickman** [comment]
Hey @qigemingzizenmezhemekunnan thanks for the report. Unless you're deploying on Vercel, `turbo-ignore` will _always_ compare with `HEAD^`. The fallback arg is only used when:

1. Deploying on Vercel
2. The previously deployed commit SHA can't be found

That being said, this is something we can support, and we do have another issue for it here: https://github.com/vercel/turbo/issues/5080

I'm going to close this one to consolidate, thanks!
