### ISSUE TITLE
[turbopack] hmr doesn't work in wsl2

### ISSUE THREAD

**Issue by will-chc** [vercel/turbo#5137]
### What version of Next.js are you using Turbopack in?

latest

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

hmr doesn't work in wsl2。
it need restart the project。
 

### Expected Behavior

modify code，hmr doesn't work in wsl2

### To Reproduce

npm run dev in wsl2

**Comment by ForsakenHarmony** [comment]
Closing for now, if this is still a problem in the latest next.js canary feel free to open a new issue in the next.js repo
