### ISSUE TITLE
Support the use case of not using mergebase for --since

### ISSUE THREAD

**Issue by SamChou19815** [vercel/turbo#514]
### Describe the feature you'd like to request

I am trying to integrate turborepo in my GitHub actions workflow.

I want to avoid checking out the entire history, so I tried to only check out two commits: the base commit and the merge commit of the pull request. Then I want to use `--since=[base-commit]` to only rebuild what has been affected by the request.

However, this will result in a fatal error due to these lines:

https://github.com/vercel/turborepo/blob/23cb6c1bb1360d33a7b63b9222922b5a94d30d9f/cli/internal/scm/git.go#L74-L84

Example of failed run: https://github.com/SamChou19815/infra/pull/25

When using three dots, git will try to find the mergebase between the two commits, which usually does not exist when you only checkout two isolated commits. I would like to support the use case so I don't have to checkout the entire history just for an incremental build from turborepo.

### Describe the solution you'd like

An option that runs `git diff --name-only fromCommit..HEAD` under the hood would be great.

### Describe alternatives you've considered

Use build cache instead?

**Comment by attila** [comment]
A potential workaround is to fetch enough history so that diffing via a merge-base becomes possible. It looks like https://github.com/rmacklin/fetch-through-merge-base is attempting to achieve exactly that.

It still is considered a kludge in my opinion, and support for an option to use `..`-style diffs would be desirable.

**Comment by jaredpalmer** [comment]
So tl;dr add a `--base` flag for the `<fromCommit>`?

**Comment by jaredpalmer** [comment]
Can you suggest how you'd like to specify `...` vs. `..` via command line flags?

**Comment by SamChou19815** [comment]
Maybe there can be a flag like `--no-mergebase` or a separate flag like `--diff=[commit]` that signals we only care about the diff between two commits.

**Comment by graup** [comment]
+1 on the issue. I had opened a discussion but seems is the same. https://github.com/vercel/turborepo/discussions/805

If we cannot fix it, at the very least we could improve the error message and documentation.

**Comment by anthonyshew** [comment]
`--since` is deprecated so will close this as out of date!
