### ISSUE TITLE
Update SASS docs and examples

### ISSUE THREAD

**Issue by jridgewell** [vercel/turbo#5143]
Is there any plans for updating the documentation and examples? Thanks

_Originally posted by @GarryOne in https://github.com/vercel/next.js/issues/49882#issuecomment-1569830165_
            

<sub>[WEB-1142](https://linear.app/vercel/issue/WEB-1142/update-sass-docs-and-examples)</sub>

**Comment by GarryOne** [comment]
![image](https://github.com/vercel/turbo/assets/6481499/249fbbe4-a96e-4de1-a6c7-b166e1ea85db)

**Comment by GarryOne** [comment]
> ![image](https://user-images.githubusercontent.com/6481499/245107887-249fbbe4-a96e-4de1-a6c7-b166e1ea85db.png)

Fixed with:
https://github.com/vercel/next.js/pull/51259

**Comment by anthonyshew** [comment]
This appears to be stale but please re-open if needed!
