### ISSUE TITLE
[turborepo] Eslint plugin should also look for env vars accessed from import.meta.env

### ISSUE THREAD

**Issue by petercpwong** [vercel/turbo#5163]
### What version of Turborepo are you using?

1.10.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Currently, the eslint plugin only looks for env vars accessed from `process.env`. However, some frontend frameworks such as vite expose env vars using `import.meta.env` (https://vitejs.dev/guide/env-and-mode.html), so the eslint plugin is unable to catch env vars that are used in vite projects but not declared inside `turbo.json`.

### Expected Behavior

Eslint plugin should be able to catch undeclared env vars accessed from `import.meta.env`

### To Reproduce

Pretty self explanatory

**Comment by ThinhLe183** [comment]
any update ?

**Comment by jamesbvaughan** [comment]
Are there any major blockers to this work? If not, I'd be happy to take a crack at it.

**Comment by tknickman** [comment]
Thanks for tackling this! Closing the issue.
