### ISSUE TITLE
[turbopack] turbopack seems to rely on baseUrl (in tsconfig.json) for static assets

### ISSUE THREAD

**Issue by Taarek** [vercel/turbo#5183]
### What version of Next.js are you using Turbopack in?

13.4.4

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

When I tried using turbopack with my project, that works fine without turbopack. I ran into this error:
![image](https://github.com/vercel/turbo/assets/13603398/c2984582-672b-40d9-875f-67e38298316e)

After reading some of the issues on this repo, I tried setting `baseUrl` in my `tsconfig.json` to `./` (`"baseUrl": "./"`).
Doing that made everything work as expected.

I'll have to admit, I am not entirely sure how `baseUrl` is meant to work, or how it's supposed to be respected.

### Expected Behavior

Static Assets loading without having to rely on `baseUrl` like how it works without turbopack.

### To Reproduce

- Have a nested file and try importing a static asset by doing `import name from 'public/image.jpg'` while using turbopack
- You'll be prompted with an error that says it was unable to resolve module  "public" with subpath blah blah
- Try adding `"baseUrl": "./"` to tsconfig.json, and refreshed. Suddenly it all works.

**By nested files, I mean like frontend/components/File.tsx**

**Comment by ForsakenHarmony** [comment]
If you're still running into this, please open a new issue in the next.js repo
