### ISSUE TITLE
[turborepo] `waiting to cache` takes more than 1minute

### ISSUE THREAD

**Issue by imranbarbhuiya** [vercel/turbo#5187]
### What version of Turborepo are you using?

1.10.1

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Windows

### Describe the Bug

From last 6month, `waiting to cache` takes more than 1min. After running the `turbo` command, it shows 

```sh
o WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
        - the process identified by the pid in the file at /tmp/turbod/f70758a87e404a08/turbod.pid is not running, and remove /tmp/turbod/f70758a87e404a08/turbod.pid
        - check the logs at /root/.local/share/turborepo/logs/f70758a87e404a08-Sofi-Site.log
        - the unix domain socket at /tmp/turbod/f70758a87e404a08/turbod.sock has been removed
        You can also run without the daemon process by passing --no-daemon  
```

after opening the log file, it shows 
```log
2023-06-02T22:34:28.754+0530 [ERROR] turbod: error watching /root/Sofi-Site: failed adding watch to /root/Sofi-Site/apps/website/.next/cache/images/AKH46QpebUE1etcFkHeYwdHVFmT6A5BKuPKzWAurElo=: no space left on device
```

and the `turbod.pid` file doesn't exists

### Expected Behavior

it shouldn't take that long

### To Reproduce

I can't really provide a repro as it works fine in my local machine but the above logs might help u identify the bug

<sub>[TURBO-1173](https://linear.app/vercel/issue/TURBO-1173/[turborepo]-waiting-to-cache-takes-more-than-1minute)</sub>

**Comment by gsoltis** [comment]
@imranbarbhuiya is it possible that you are out of space on a disk somewhere? The daemon error should be unrelated, but if you are in fact out of disk space, that might be part of the problem.

Also, I'm confused, are you on Windows? The paths in the error look like they are from a unix-like system.

Additional thing to check:
 - the size on disk of `node_modules/.cache/turbo`. It's possible there are some large artifacts there. It's also possible that the outputs you are producing are large

**Comment by imranbarbhuiya** [comment]
Sorry I selected my local os. Yeah os is ubuntu. Also, we don't have any storage issues. 
![image](https://github.com/vercel/turbo/assets/74945038/9bb9dd68-51bd-43f5-813b-5982d1328e84)
seems like `.next` folder is too huge. Ig it's causing the issue. I'll try deleting and recreating it

**Comment by gsoltis** [comment]
@imranbarbhuiya The latest version of `turbo` (`1.10.3`) includes a `turbo daemon clean` command to get into a good state. Can you give that a try?

**Comment by imranbarbhuiya** [comment]
No, it shows `Done` but after I run again, it gives

```sh
 WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed.
        To quickly resolve the issue, try running:
        - $ turbo daemon clean

        To debug further - please ensure the following:
        - the process identified by the pid in the file at /tmp/turbod/f70758a87e404a08/turbod.pid is not running, and remove /tmp/turbod/f70758a87e404a08/turbod.pid
        - check the logs at /root/.local/share/turborepo/logs/f70758a87e404a08-Sofi-Site.log
        - the unix domain socket at /tmp/turbod/f70758a87e404a08/turbod.sock has been removed

        You can also run without the daemon process by passing --no-daemon
```

opening the log file shows

```sh
2023-06-10T01:52:21.712+0530 [ERROR] turbod: error watching /root/Sofi-Site: failed adding watch to /root/Sofi-Site/apps/gems/.turbo: no space left on device
2023-06-10T01:52:22.712+0530 [ERROR] turbod: error watching /root/Sofi-Site: failed adding watch to /root/Sofi-Site/apps/gems/.turbo: no space left on device
2023-06-10T01:52:23.712+0530 [ERROR] turbod: error watching /root/Sofi-Site: failed adding watch to /root/Sofi-Site/apps/gems/.turbo: no space left on device
2023-06-10T01:53:13.853+0530 [ERROR] turbod: error watching /root/Sofi-Site: failed adding watch to /root/Sofi-Site/apps/gems: no space left on device
2023-06-10T01:53:14.853+0530 [ERROR] turbod: error watching /root/Sofi-Site: failed adding watch to /root/Sofi-Site/apps/gems: no space left on device
2023-06-10T01:53:15.854+0530 [ERROR] turbod: error watching /root/Sofi-Site: failed adding watch to /root/Sofi-Site/apps/gems: no space left on device
```

**Comment by niedzielski** [comment]
I upgraded to Debian v12 with Node v20 recently and I believe I'm seeing a similar issue that I don't think was present on Debian v11 with Node v16:

```
web-worker:build: Failed to check if we can skip restoring outputs for web-worker#build: rpc error: code = Unknown desc = failed adding watch to /home/user/.local/share/turborepo/cookies/2931d19fe7121f69/91.cookie: no space left on device. Proceeding to check cache
web-worker:build: Failed to mark outputs as cached for web-worker#build: rpc error: code = Unknown desc = failed adding watch to /home/user/.local/share/turborepo/cookies/2931d19fe7121f69/92.cookie: no space left on device
web-worker:build: cache hit, suppressing output 4575b2ab92642d80
```

/home/user/.local/share/turborepo/cookies/2931d19fe7121f69/ exists and has a number of files in it but 92.cookie does not exist. The general error format is similar for other packages. Plenty of space on disk.

When I try to dump the node_modules cache, I get:

```
$ npx turbo daemon clean
2023-06-13T13:56:03.177-0600 [ERROR] turbod: error watching /home/user/work/src: failed adding watch to /home/user/work/src/blah/vendor/google.golang.org/grpc/balancer: no space left on device
```

When I manually hose out node_modules/.cache:

```
$ rm -rf node_modules/.cache/
$ npx turbo run build --output-logs=new-only --force
...
some-package:build: Failed to mark outputs as cached for some-package#build: rpc error: code = Unknown desc = timed out waiting for cookie
...
$ npx turbo run build --output-logs=new-only # everything times out waiting for cookie but build is successful and daemon cleaning still fails
```

When I manually dump the node_modules and .local cache I get:

```
$ rm -rf /home/user/.local/share/turborepo node_modules/.cache/
$ npx turbo run build --output-logs=new-only # everything times out waiting for cookie
```

My Debian upgrade was a from-scratch fresh install. I did copy files over but I did not knowingly inherit prior NPM or .local state.

Node.js v20.3.0
NPM v9.6.7
turbo v1.6.3
yarn v3.2.3

**Comment by gsoltis** [comment]
@arlyon can you help track down what's going on with the daemon?

**Comment by arlyon** [comment]
Hi, as an update I am working on understanding the issue here and will hopefully get a fix very soon. Cheers.

**Comment by NicholasLYang** [comment]
Hi @niedzielski, could you try running with a newer version of turbo? A lot has changed since 1.6.3

**Comment by sammyfilly** [comment]
Okay thank for the tip

**Comment by niedzielski** [comment]
@NicholasLYang, thanks for the follow-up! I tried but I'm going to have to debug later. I think I'm hitting #3050 on Turbo v1.10.7:

```
$ yarn build
 ERROR  run failed: error preparing engine: Could not find "___ROOT___#build" in root turbo.json
Turbo error: error preparing engine: Could not find "___ROOT___#build" in root turbo.json
```

**Comment by arlyon** [comment]
I am going to close this due to age. We are now on 1.12 which replaces the entire go code with rust, so if this can be repro'd on that version please write a comment and we can re-open.

Thanks!
