### ISSUE TITLE
[turbopack] cache problems with video demo explained

### ISSUE THREAD

**Issue by mieaw** [vercel/turbo#5197]
### What version of Turborepo are you using?

beta

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

look at the video:  https://www.youtube.com/watch?v=rMEkQ3dRvxI
and gh repo: https://github.com/uptimizer-prolife/turborepo-nextjs-cache-problems-ref-001

### Expected Behavior

look at the video:  https://www.youtube.com/watch?v=rMEkQ3dRvxI
and gh repo: https://github.com/uptimizer-prolife/turborepo-nextjs-cache-problems-ref-001

### To Reproduce

look at the video:  https://www.youtube.com/watch?v=rMEkQ3dRvxI
and gh repo: https://github.com/uptimizer-prolife/turborepo-nextjs-cache-problems-ref-001

**Comment by timneutkens** [comment]
This does not look related to Turbopack. Have a look at this post on how caching is applied in Next.js: https://github.com/vercel/next.js/discussions/54075
