### ISSUE TITLE
[turborepo] Better error reporting in postinstall script

### ISSUE THREAD

**Issue by jgoz** [vercel/turbo#5205]
### What version of Turborepo are you using?

1.10.1

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Upgrading from 1.9.3 to 1.10.1 was causing our CI to fail even though it worked fine locally. We were seeing a very cryptic message originating from the `postinstall` script:

```
npm ERR! code 1
npm ERR! path /opt/actions-runner/_work/***/***/node_modules/turbo
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! node:internal/errors:857
npm ERR!   const err = new Error(message);
npm ERR!               ^
npm ERR! 
npm ERR! Error: Command failed: /opt/actions-runner/_work/***/***/node_modules/turbo/bin/turbo --version --skip-infer
npm ERR!     at checkExecSyncError (node:child_process:861:11)
npm ERR!     at Object.execFileSync (node:child_process:896:15)
npm ERR!     at validateBinaryVersion (/opt/actions-runner/_work/***/***/node_modules/turbo/install.js:28:6)
npm ERR!     at /opt/actions-runner/_work/***/***/node_modules/turbo/install.js:317:7 {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [
npm ERR!     null,
npm ERR!     Buffer(143) [Uint8Array] [
npm ERR!        69,  82,  82,  79,  82,  32,  97,  32, 118,  97, 108, 117,
npm ERR!       101,  32, 105, 115,  32, 114, 101, 113, 117, 105, 114, 101,
npm ERR!       100,  32, 102, 111, 114,  32,  39,  45,  45, 102, 111, 114,
npm ERR!        99, 101,  32,  91,  60,  70,  79,  82,  67,  69,  62,  93,
npm ERR!        39,  32,  98, 117, 116,  32, 110, 111, 110, 101,  32, 119,
npm ERR!        97, 115,  32, 115, 117, 112, 112, 108, 105, 101, 100,  10,
npm ERR!        32,  32,  91, 112, 111, 115, 115, 105,  98, 108, 101,  32,
npm ERR!       118,  97, 108, 117, 101, 115,  58,  32, 116, 114, 117, 101,
npm ERR!        44,  32, 102,  97,
npm ERR!       ... 43 more items
npm ERR!     ],
npm ERR!     Buffer(0) [Uint8Array] []
npm ERR!   ],
npm ERR!   pid: 8966,
npm ERR!   stdout: Buffer(143) [Uint8Array] [
npm ERR!      69,  82,  82,  79,  82,  32,  97,  32, 118,  97, 108, 117,
npm ERR!     101,  32, 105, 115,  32, 114, 101, 113, 117, 105, 114, 101,
npm ERR!     100,  32, 102, 111, 114,  32,  39,  45,  45, 102, 111, 114,
npm ERR!      99, 101,  32,  91,  60,  70,  79,  82,  67,  69,  62,  93,
npm ERR!      39,  32,  98, 117, 116,  32, 110, 111, 110, 101,  32, 119,
npm ERR!      97, 115,  32, 115, 117, 112, 112, 108, 105, 101, 100,  10,
npm ERR!      32,  32,  91, 112, 111, 115, 115, 105,  98, 108, 101,  32,
npm ERR!     118,  97, 108, 117, 101, 115,  58,  32, 116, 114, 117, 101,
npm ERR!      44,  32, 102,  97,
npm ERR!     ... 43 more items
npm ERR!   ],
npm ERR!   stderr: Buffer(0) [Uint8Array] []
npm ERR! }
```

I scratched my head for longer than I'd like to admit, but then I fed the buffer output back into Node, converted to UTF-8, and it produced this message:

```
"ERROR a value is required for '--force [<FORCE>]' but none was supplied\n" +
  '  [possible values: true, fa'
```

It turns out my project was defining the `TURBO_FORCE` environment variable without a value in certain CI runs. Essentially, it was an optional property that did not have a default value. As of 1.9.4(?), turborepo stopped inferring a default value for this variable and started requiring it to be passed explicitly as `true` or `false`, which caused our build to start failing.

It was an easy fix, but determining the root cause was pretty difficult.

### Expected Behavior

Error messages from `postinstall` scripts are printed in a more user friendly way.

### To Reproduce

- Add `turbo@1.10.1` as a dependency to an npm project
- Delete node_modules
- Run `TURBO_FORCE='' npm i`

**Comment by mehulkar** [comment]
Hey there, Thanks for the report!  I was able to reproduce this with 1.10.1, but after testing future versions, I see the bug was fixed in 1.10.13. After reviewing [the diff](https://github.com/vercel/turbo/compare/v1.10.12...v1.10.13), my guess is that it was fixed in #5695. Please upgrade and let us know if you're still seeing issues
