### ISSUE TITLE
[turborepo] `turbo gen` is unable to find generators

### ISSUE THREAD

**Issue by suneettipirneni** [vercel/turbo#5249]
### What version of Turborepo are you using?

1.10.2

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

Whenever I run `turbo gen` I receive the following output:

```
>>> Modify "@discordjs/discord.js" using custom generators

>>> No generators found.

? Would you like to add a config with a sample custom generator to @discordjs/discord.js? Yes
? Should the generator config be created with TS or JS? TypeScript

>>> Generator config successfully created!
>>> Loading generator config...

>>> Error loading generator
```

Turbo can't seem to load the newly created generator, and when this command is run again it reports there are no generators found despite the `example` generator already being saved in `turbo/generators` from the previous command.

```
$ turbo gen

>>> Modify "@discordjs/discord.js" using custom generators

>>> No generators found.
```

### Expected Behavior

`turbo gen` should be able to load and find generators in the directory where they were created.

### To Reproduce

1. Clone the repo: `git clone https://github.com/discordjs/discord.js.git && cd discord.js`
2. Checkout the branch with the latest turbo installation: `git checkout turbo-gen-error`
3. Install deps with `yarn`
4. Run `turbo gen` to generate the example generator.

### Reproduction Repo

https://github.com/discordjs/discord.js/tree/turbo-gen-error

**Comment by tknickman** [comment]
Hey @suneettipirneni, thanks for the report / reproduction. I'll take a look!

**Comment by tknickman** [comment]
Fixed in https://github.com/vercel/turbo/pull/5263. 

The issue had to do with our automatic TS support. Your root tsconfig includes:

```
"moduleResolution": "bundler",
```

Which was breaking our ability to load the TS config. 

This PR fixes that by setting some overrides for our specific loader. Also, it stops burying this error so it would have been more obvious what was going on!

**Comment by tknickman** [comment]
Should be released as a canary today or monday!

**Comment by suneettipirneni** [comment]
Awesome, thanks for fixing this.

**Comment by suneettipirneni** [comment]
@tknickman Unfortunately this seems to still give the same errors on the latest canary with this fix, I've ran this `-vvv` and it doesn't seem to show the cause for the generator failing to load either:

```
$ yarn turbo gen -vvv
                                                                                                                                                                                                                                                                                                                                             
2023-06-12T20:27:15.683-0400 [DEBUG] turborepo_lib::shim: Global turbo version: 1.10.4-canary.0
2023-06-12T20:27:16.639-0400 [DEBUG] turborepo_lib::shim: Local turbo path: /Users/user/discord.js/node_modules/turbo-darwin-64/bin/turbo
2023-06-12T20:27:16.639-0400 [DEBUG] turborepo_lib::shim: Local turbo version: 1.10.4-canary.0
2023-06-12T20:27:16.639-0400 [DEBUG] turborepo_lib::shim: Repository Root: /Users/user/discord.js
2023-06-12T20:27:16.640-0400 [DEBUG] turborepo_lib::shim: Running local turbo binary in /Users/user/discord.js/node_modules/turbo-darwin-64/bin/turbo

2023-06-12T20:27:16.640-0400 [DEBUG] turborepo_lib::shim: supports_skip_infer_and_single_package true

>>> Modify "@discordjs/discord.js" using custom generators

>>> No generators found.

? Would you like to add a config with a sample custom generator to @discordjs/discord.js? Yes
? Should the generator config be created with TS or JS? TypeScript

>>> Generator config successfully created!
>>> Loading generator config...

>>> Error loading generator
```

**Comment by tknickman** [comment]
@suneettipirneni try:

`yarn turbo gen --tag canary`

**Comment by suneettipirneni** [comment]
Ah, that did the trick. Thanks again.

**Comment by tknickman** [comment]
No prob! Once latest is out you can go back to just `turbo gen` 😄
