### ISSUE TITLE
[turborepo] eslint-plugin-turbo: `process.env` is monitored but `import.meta.env` is not

### ISSUE THREAD

**Issue by PhilippMolitor** [vercel/turbo#5257]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When using `eslint-config-turbo` with the recommended ruleset, `process.env` is monitored correctly. My frontend package uses Vite, and therefore my env variables live in `import.meta.env` instead.

See: [https://vitejs.dev/guide/env-and-mode.html#env-variables-and-modes](https://vitejs.dev/guide/env-and-mode.html#env-variables-and-modes)
Astro uses this convention as well: [https://docs.astro.build/en/guides/environment-variables/](https://docs.astro.build/en/guides/environment-variables/)

### Expected Behavior

This plugin should also support this convention. It works exactly like `process.env`.

### To Reproduce

-

**Comment by tknickman** [comment]
Thank you, it's on the list! We have an existing issue for this [here](https://github.com/vercel/turbo/issues/5163), so I'm going to close this one to consolidate.
