### ISSUE TITLE
[turborepo] Documentation suggests "*" as package version when "workspace:*" is correct

### ISSUE THREAD

**Issue by hamza1311** [vercel/turbo#5261]
### What version of Turborepo are you using?

N/A - docs issue

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Linux

### Describe the Bug

When `"*"` is used as dependency version in package.json, yarn prefers to load it from the package registry instead of from the workspace. The solution is to use `"workspace:*"`, as described in [their documentation](https://yarnpkg.com/features/workspaces).

Turborepo documentation for monorepo uses `"*"`. This can lead to problems when yarn believes the package published to registry is newer than the local one. We ran into this issue where `x.y.5` > `x.y.6-foo.1`, causing builds to fail, with cryptic and unhelpful error messages.

Note that [pnpm also suggests using `"workspace:*"`](https://pnpm.io/workspaces#publishing-workspace-packages)

### Expected Behavior

Documentation should suggest using  `"workspace:*"` and/or link back to package manager's docs.

### To Reproduce

N/A -- docs issue

**Comment by arlyon** [comment]
I think this is a good change. If you are up for updating the docs with this, feel free to tag me here and I will make sure to get it merged :)

Alex
