### ISSUE TITLE
[turbopack]   lint TP1004 fs.readFileSync(???*0*, {"encoding": "utf8"}) is very dynamic

### ISSUE THREAD

**Issue by MrOxMasTer** [vercel/turbo#5265]
### What version of Next.js are you using Turbopack in?

13.4.5canary9

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Windows

### Describe the Bug

![image](https://github.com/vercel/turbo/assets/59291123/e42c8adf-d8b3-4c84-9f1c-22e5d9942cd0)
![image](https://github.com/vercel/turbo/assets/59291123/7ea7481c-cb1f-4aef-adb2-dbb097734d1c)
![image](https://github.com/vercel/turbo/assets/59291123/1aa53e6d-d830-4b67-9132-3e4bdd28ab7c)

I found a solution to the problem using node Js on github, but an error pops up when using it

### Expected Behavior

So that no warning pops up

### To Reproduce

"eslint": "^8.42.0",
"eslint-config-next": "13.4.4"
"postcss": "^8.4.24",

**Comment by timneutkens** [comment]
Tailwind works correctly now.
