### ISSUE TITLE
[turborepo] Windows CLI doesn't show color highlight properly

### ISSUE THREAD

**Issue by dzcpy** [vercel/turbo#5268]
### What version of Turborepo are you using?

1.10.3

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

When using it under Windows default CMD, it doesn't show any highlighted color. How ever, color highlighting with other JS packages work fine.
![image](https://github.com/vercel/turbo/assets/203980/42d06c97-9120-4b79-a53e-355f6f6fc592)
It works fine with Git Bash:
![image](https://github.com/vercel/turbo/assets/203980/bcecd422-c6ef-470d-bb40-95d7387e6368)
But not Git bash in VSCode, which is weird

### Expected Behavior

Highlight color correctly.

### To Reproduce

Run any comnands with Windows 10 CMD

**Comment by mehulkar** [comment]
Hey @dzcpy , we weren't able to reproduce this on Win10, OS build 19045.3570 even using `turbo@1.10.3`

It does seem to be a known thing that not all Windows CMD.exe doesn't support color escape sequences across the board, but considering that reported this from Win 10, it may be a setting on your end. 

Can you check out https://learn.microsoft.com/en-us/windows/console/setconsolemode and try some things? Some things that jump out are `ENABLE_VIRTUAL_TERMINAL_PROCESSING` and `ENABLE_PROCESSED_OUTPUT`. 

You can also try using the `--no-color` if that helps get you some output that is easier to read.
