### ISSUE TITLE
Introduce two more directories for configs and tools - leave packages for real package

### ISSUE THREAD

**Issue by un33k** [vercel/turbo#5299]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Adding configs & tools directory to turbo default repo.

Please refer to the attached image.

- The package directory to remain clean for the packages responsible for the core product.
- Any configuration related artifacts is moved into a configs directory
- Any tools for building the project, or its maintenance is put into a tools directory

This is to keep the apps and package directory clean and single purpose.

![turbo](https://github.com/vercel/turbo/assets/407537/b0af5bcc-4dad-47ad-be74-1d95e42c099d)

### Describe the solution you'd like

The recommendation is for turbo repo to adapt the above  directory reorg, if possible.

### Describe alternatives you've considered

Coming from NX, turbo is a fresh and clean start.  The alternative is leave things as they are now. 

The tools/utils/src/loc.ts file uses `loc` command and injects the Line of Code into the REEADME.md. With the current structure, such scripts have to be put in the root directory, or in packages.  A dedicated `tools` directory is much cleaner. 

Same thing for  the `configs` directory.

**Comment by anthonyshew** [comment]
We're happy with the way the examples are structured now. Thanks for the suggestion!
