### ISSUE TITLE
[turborepo] could you update svelte eslint config ?

### ISSUE THREAD

**Issue by AxeloLabs** [vercel/turbo#5304]
### What version of Turborepo are you using?

1.0.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

please, you are using an obsolete svelte eslint plugin
  plugins: ['svelte3', '@typescript-eslint'],

svelte3 is not recomended anymore
https://github.com/sveltejs/eslint-plugin-svelte
https://github.com/sveltejs/eslint-plugin-svelte3

could you update the correct config for svelte please ?
tks

### Expected Behavior

-

### To Reproduce

-

### Reproduction Repo

-

**Comment by tknickman** [comment]
For sure, we'll knock this out shortly. If you have the time a PR would also happily be accepted!

**Comment by anthonyshew** [comment]
We've updated our examples recently. If things still don't look right, would love a PR (or new issue).
