### ISSUE TITLE
[turborepo] turbo gen workspace --copy [url] doesn't work

### ISSUE THREAD

**Issue by sofshant** [vercel/turbo#5308]
### What version of Turborepo are you using?

1.10.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

running `turbo gen workspace --copy [url]` seems to ignore the url and run the command prompting what local package turbo should copy instead of the url.

```
turbo gen workspace --copy https://github.com/vercel/turbo/tree/main/examples/with-prisma/packages/database

>>> Copy an existing workspace from boilerplate

? What type of workspace should be added? package
? What is the name of the package? db
? Which workspace should "db" start from?   ui```

### Expected Behavior

Copy the setup in https://github.com/vercel/turbo/tree/main/examples/with-prisma/packages/database

### To Reproduce

turbo gen workspace --copy https://github.com/vercel/turbo/tree/main/examples/with-prisma/packages/database

### Reproduction Repo

_No response_

**Comment by tknickman** [comment]
Hey @sofshant, is this still reproducible? I just checked on this (apologies for the delay) and I'm unable to reproduce on 	`turbo@1.10.12`. Happy to take a look!

**Comment by tknickman** [comment]
Going to close for now, but please open a new issue if this is still reproducible and we'll be happy to take a look!
