### ISSUE TITLE
Followed tutorial and it broke on Yarn Turbo Run Build with "invalid character" error

### ISSUE THREAD

**Issue by WillPwn4Food** [vercel/turbo#533]
### What version of Turborepo are you using?

1.0.24

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

Following steps as per guide here: https://turborepo.org/docs/getting-started
I have an existing NextJS app that I'm trying to add Turbo to.
I'm in the repo and I follow steps:

- yarn add turbo -W --dev
- add this to my package.json:
```
  "turbo": {
    "baseBranch": "origin/main",
    "pipeline": {
      "build": {
        "dependsOn": ["^build"],
        "outputs": [".next/**"]
      },
      "test": {
        "dependsOn": ["^build"],
        "outputs": []
      },
      "lint": {
        "outputs": []
      },
      "dev": {
        "cache": false
      }
    }
  }
```

**Add this to .gitignore**
```
# turbo
 .turbo
  build/**
  dist/**
 .next/**
```

I run: **yarn turbo run build**

I get this weird error:
```
> yarn turbo run build
yarn run v1.22.5
$ D:\GitHub\myrepo\node_modules\.bin\turbo run build
←[91m←[1;31;7m ERROR ←[0m←[31m parsing .git\hooks\applypatch-msg.sample: invalid character '#' looking for beginning of value←[0m←[0m
node:child_process:729
    throw err;
    ^

Error: Command failed: D:\GitHub\myrepo\node_modules\turbo-windows-64\turbo.exe run build
    at checkExecSyncError (node:child_process:707:11)
    at Object.execFileSync (node:child_process:726:15)
    at Object.<anonymous> (D:\GitHub\myrepo\node_modules\turbo\bin\turbo:5:26)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 3260,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
```

### Expected Behavior

I expected it to just do a build and cache like in the video I watched I guess?

### To Reproduce

I literally just installed this in an existing Github repo.

**Comment by markjm** [comment]
This error is due to the `workspaces` field being unset in your root package.json
https://classic.yarnpkg.com/lang/en/docs/workspaces/

The error message is certainly messed up, but im not sure if the right course of action is to (1) immediately error out if the workspaces field (or backend equivalent) is unset, or (2) handle that as a real case - such that you are essentially caching the whole repo as one

**Comment by WillPwn4Food** [comment]
Perhaps I'm confused or missing something after further research. 
I have a repo, it is just one thing, I guess that's not a monorepo (as I assume a monorepo can have a set of 1 to many, but requires extra tooling even just to handle the 1). 
I literally just want to use Turbo to build faster on Vercel for my production app (assuming it works that way). 
I tried following the migration steps and I guess I ignored the workspaces because I don't use them or know what they are. The wording makes it seem optional:
`If you are moving from another tool to Yarn workspaces, be sure to also specify all workspaces in your package.json.`
"well I'm not moving from another tool..."
So I guess I can't just follow the instructions to migrate, I have to figure out how to make a new repo with yarn workspaces, figure out how to migrate my single repo into it, so now it's got some extra structure (I literally don't care about adding any other repos or using the monorepo advantages), and then figure out how to apply this to a new Github repo and reapply my production deploys on Vercel to use this new repo with the project subfolder, is this correct?

And does this even work with preview builds or only on the main branch?

I feel like there is a big knowledge gap or tutorial missing for this use case, especially since the Vercel acquisition. Maybe I am too naive to what a Monorepo is, I had just assumed it was more like folders in folder and you check in the root. I imagine others may hit the same confusion I do, so you may want to add some extra preamble or call outs in your tutorial.

I've never needed to know more because I haven't used them or needed them yet at this point, but I guess the big point of Turbo is the Monorepo magic and the caching is extra sugar, where as I only care about that sugar and don't see an easy path to it and my hosting provider acquired it and teased it.

So that would probably explain the weird errors I'm getting, but I would love a few answers to some of the question's I asked to know if I should bother trying to keep figuring this out or just abandon. I'd also say maybe just add some more doc stuff or blog posts or tutorials if you think my use case is going to be big, especially if Vercel tells all their users about it.

I started doing the base tutorial to start from scratch and I got all these extra folders and config files I don't care about or understand and I don't use typescript, so I'm not sure if your tutorials are a little overblown or under-explained, is there a super base level version you can make? Intrigued, but frustrated. It seems like it's making things more complex, unless you have a great love, intimacy and deep knowledge of config and package files, which I guess if you want to do a monorepo you would have to have.

**Comment by mehulkar** [comment]
Hello, this is a very late response, but if you're still running into this, can you please provide a reproduction repo?
