### ISSUE TITLE
[turborepo] ETXTBSY with Docker on node 20.3.0 (upstream bug)

### ISSUE THREAD

**Issue by andreialecu** [vercel/turbo#5335]
### What version of Turborepo are you using?

1.10.3

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

Going to leave this here for others in case they run into it. It appears our docker builds started failing recently.

It could be an upstream issue with Node.

Rolling back to node 20.2.0 works.

Aka, instead of `FROM node:alpine AS builder` using `FROM node:20.2.0-alpine AS builder` works.

```
#13 [builder 5/7] RUN yarn global add turbo
#13 sha256:3bc7ac6f39a70e2fe26f94cc70e4b64dec5eb57f4d4bc7c2077b3700807945f1
#13 0.367 yarn global v1.22.19
#13 0.409 [1/4] Resolving packages...
#13 0.698 [2/4] Fetching packages...
#13 2.550 [3/4] Linking dependencies...
#13 2.601 [4/4] Building fresh packages...
#13 2.668 error /usr/local/share/.config/yarn/global/node_modules/turbo: Command failed.
#13 2.668 Exit code: 1
#13 2.668 Command: node install.js
#13 2.668 Arguments: 
#13 2.668 Directory: /usr/local/share/.config/yarn/global/node_modules/turbo
#13 2.668 Output:
#13 2.668 node:internal/errors:496
#13 2.668     ErrorCaptureStackTrace(err);
#13 2.668     ^
#13 2.668 
#13 2.668 <ref *1> Error: spawnSync node ETXTBSY
#13 2.668     at Object.spawnSync (node:internal/child_process:1117:20)
#13 2.668     at spawnSync (node:child_process:871:24)
#13 2.668     at Object.execFileSync (node:child_process:914:15)
#13 2.668     at validateBinaryVersion (/usr/local/share/.config/yarn/global/node_modules/turbo/install.js:28:6)
#13 2.668     at /usr/local/share/.config/yarn/global/node_modules/turbo/install.js:314:7 {
#13 2.668   errno: -26,
#13 2.668   code: 'ETXTBSY',
#13 2.668   syscall: 'spawnSync node',
#13 2.668   path: 'node',
#13 2.668   spawnargs: [
#13 2.668     '/usr/local/share/.config/yarn/global/node_modules/turbo/bin/turbo',
#13 2.668     '--version',
#13 2.668     '--skip-infer'
#13 2.668   ],
#13 2.668   error: [Circular *1],
#13 2.668   status: null,
#13 2.668   signal: null,
#13 2.668   output: null,
#13 2.668   pid: 0,
#13 2.668   stdout: null,
#13 2.668   stderr: null
#13 2.668 }
#13 2.668 
#13 2.668 Node.js v20.3.0
#13 2.668 info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
#13 ERROR: executor failed running [/bin/sh -c yarn global add turbo]: exit code: 1
```

### Expected Behavior

No error.

### To Reproduce

Dockerfile with:

```
FROM node:20.3.0-alpine AS builder
RUN apk add --no-cache libc6-compat
RUN apk update
# Set working directory
WORKDIR /app
RUN yarn global add turbo
```

**Comment by andreialecu** [comment]
Upstream bug: https://github.com/nodejs/node/issues/48444

**Comment by arlyon** [comment]
Thanks for the report. Am I correct in saying this is a wider nodejs issue rather than a turbo-specific problem?

**Comment by andreialecu** [comment]
Indeed it's a nodejs issue, so you can close it (either now or when it's fixed upstream) - I opened it here because Turbo specifically documents Docker usage, and I ran into this issue just here for now. I thought others would appreciate quickly finding a workaround.

I don't think it's actionable from Turbo's side.

**Comment by arlyon** [comment]
The report is useful for others and for documentations sake so thanks for taking the time. I will close this now.

**Comment by ShaharAdskAcc** [comment]
I got the same problem on my ci/cd pipeline - but it wasn't relevant to docker. 
I leave it here because Google directed me to this thread.

I had the following error:
```
Turborepo did not find the correct binary for your platform.

We will attempt to install it now.

Installation has succeeded.

/mnt/data/jenkins/workspace/***/node_modules/turbo/bin/turbo:273

  throw e;

  ^

<ref *1> Error: spawnSync /mnt/data/jenkins/workspace/***/node_modules/turbo/node_modules/turbo-linux-64/bin/turbo ETXTBSY
```

My problem, I had two parallel tasks that run `turbo run lint` and `turbo run test`,
They basically raced on installing the correct binary, and locking the file.. the other tried to override the file,
The way that I solved it, was to run the following command before I ran in parallel the rest of the `turbo` commands

```
    sh """
    npx turbo --help
    """
```
