### ISSUE TITLE
[turborepo] [regression] turbo crashes when a task traps signals

### ISSUE THREAD

**Issue by notaphplover** [vercel/turbo#5337]
### What version of Turborepo are you using?

1.10.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Turborepo panics when a task traps signals. On previous versions `turbo` does not crash. Versions prior to `1.10.2` do not crash. This bug was probably introduced in `1.10.2`.

### Expected Behavior

I expect turborepo not to panic.

### To Reproduce

1. Clone the reproduction repo.
2. Go to the root directory of the project.
3. Install dependencies: `pnpm i`.
4. Run `pnpm run foo:turbo:trap`

The following output should appear:

```
thread 'main' panicked at 'handler set: MultipleHandlers', crates/turborepo-lib/src/child.rs:26:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'handler set: MultipleHandlers', crates/turborepo-lib/src/child.rs:26:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Reproduction Repo

https://github.com/notaphplover/turborepo-trap-issue

**Comment by arlyon** [comment]
I have a fix for this in this PR, thanks for the report :)
