### ISSUE TITLE
[turborepo]: ERROR Unable to find Go binary

### ISSUE THREAD

**Issue by MathiasWP** [vercel/turbo#5381]
### What version of Turborepo are you using?

1.10.6

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug
```bash
ERROR Unable to find Go binary. Please report this issue at https://github.com/vercel/turbo/issues and include your package manager and version along with the following information:
--
11:57:02.260 | os=linux
11:57:02.260 | arch=x86_64
11:57:02.260 | turbo-version=1.10.6
11:57:02.260 | turbo-bin=/vercel/path0/node_modules/turbo/bin/turbo
11:57:02.260 | go-turbo-bin=/vercel/path0/node_modules/turbo/bin/go-turbo
11:57:02.260 |  
11:57:02.260 | Error: Failed to execute turbo (Unable to locate Go binary).
11:57:02.274 | Error: Command "cd ../.. && npm run build:init" exited with 1
11:57:02.785 | BUILD_UTILS_SPAWN_1: Command "cd ../.. && npm run build:init" exited with 1
```

### Expected Behavior

Should find Go binary

### To Reproduce

Build step in Vercel

**Comment by onehassan** [comment]
I'm facing the same issue on my local machine.

I've installed Go using Homebrew.

Turborepo version: 1.10.6
package manager: pnpm
operating system: macOS Ventura 13.2.1



```
os=macos
arch=x86_64
turbo-version=1.10.6
turbo-bin=/Users/hassan/Library/pnpm/global/5/.pnpm/turbo@1.10.6/node_modules/turbo/bin/turbo
go-turbo-bin=/Users/hassan/Library/pnpm/global/5/.pnpm/turbo@1.10.6/node_modules/turbo/bin/go-turbo     
```

**Comment by arlyon** [comment]
Let's start with repro-ing the local case first and then try to work backwards. @onehassan what command do you use to run turbo? How did you install it?

**Comment by fish4j** [comment]
Same here. rolling back to 1.10.5 works for me.

**Comment by onehassan** [comment]
> I'm facing the same issue on my local machine.
> 
> I've installed Go using Homebrew.
> 
> Turborepo version: 1.10.6 package manager: pnpm operating system: macOS Ventura 13.2.1
> 
> ```
> os=macos
> arch=x86_64
> turbo-version=1.10.6
> turbo-bin=/Users/hassan/Library/pnpm/global/5/.pnpm/turbo@1.10.6/node_modules/turbo/bin/turbo
> go-turbo-bin=/Users/hassan/Library/pnpm/global/5/.pnpm/turbo@1.10.6/node_modules/turbo/bin/go-turbo     
> ```

Update:

For my case apparently the issue was with my `pnpm` installation. I suppose It was an `x86` version and I'm on an m1 Mac.

Here's what I did to fix this

1. Delete pnpm: `rm -rf /Users/[username]/Library/pnpm`
2. Install it again: `curl -fsSL https://get.pnpm.io/install.sh | sh -`

**Comment by JasonMetal** [comment]
I use the taobao
just like it
`pnpm config set registry https://registry.npm.taobao.org`

then ,it is ok
tips:  pnpm -v 8.6.5

**Comment by matt-unosquare** [comment]
same issues
```
os=macos
arch=x86_64
turbo-version=1.10.6
turbo-bin=/Users/matt.koehler/_projects/playground/node_modules/.pnpm/turbo-darwin-64@1.10.6/node_modules/turbo-darwin-64/bin/turbo
go-turbo-bin=/Users/matt.koehler/_projects/playground/node_modules/.pnpm/turbo-darwin-64@1.10.6/node_modules/turbo-darwin-64/bin/go-turbo
```

**Comment by Stanzilla** [comment]
in GitHub actions as wel
```
		os=linux
        arch=x86_64
        turbo-version=1.[10](https://github.com/diablobuilds/diablobuilds.com/actions/runs/5432160803/jobs/9879026191#step:5:11).7
        turbo-bin=/home/runner/work/diablobuilds.com/diablobuilds.com/node_modules/turbo/bin/turbo
        go-turbo-bin=/home/runner/work/diablobuilds.com/diablobuilds.com/node_modules/turbo/bin/go-turbo
        
```

**Comment by freshfritz** [comment]
Very annoying. Happened to us for the first time when this issue was created (Github Actions).

It doesn't show up for a while and then suddenly for no reason. So far it has helped to wait a bit and start new rebuilds.

**Comment by afroguy16** [comment]
Downgrading to `turbo 1.9.7` fixed this for me

**Comment by nathanhammond** [comment]
Hey everybody, can any of you confirm if simply changing the version to a different version, and then changing it back to 1.10.6 addresses the issue? One possible hypothesis is `node_modules` cache installation weirdness.

Tomorrow I'll review the diff .5=>.6 to see if there are possible contributing changes.

**Comment by Stanzilla** [comment]
> Hey everybody, can any of you confirm if simply changing the version to a different version, and then changing it back to 1.10.6 addresses the issue? One possible hypothesis is `node_modules` cache installation weirdness.
> 
> Tomorrow I'll review the diff .5=>.6 to see if there are possible contributing changes.

that's been my observation so far, yes

**Comment by nathanhammond** [comment]
I am unable to reproduce this issue. Since I am unable to reproduce, without further information we will be unable to make progress on this issue. See below the information needed.

***

Codebase details from my inspection:

Here is where the error is triggered:
https://github.com/vercel/turbo/blob/b4fe7e9b225e80f36c82513b18db6e0ded582a36/crates/turborepo/src/main.rs#L24-L42

On Mac and Linux the entire code path up to that error exclusively uses Rust stdlib functions (with a detour through `dunce`):
https://gitlab.com/kornelski/dunce/-/blob/e409d1c6f015ad4c06cf2597a5e7dc66dc670e8e/src/lib.rs#L64-67

The relevant code has not changed since `v1.7.1`:
https://github.com/vercel/turbo/blame/b4fe7e9b225e80f36c82513b18db6e0ded582a36/crates/turborepo/src/main.rs#L24-L42

Our installation behavior has not changed since `v1.8.4`:
https://github.com/vercel/turbo/commit/3cd82426819bf84ad587fd8fbab282e253370daa

***

I see nothing which implies that this issue is caused by any recent Turborepo changes. I hypothesize that the issue is with cache restoration on individual boxes in combination with upgrades and possibly mixed-usage of package managers.

Can the next person who encounters this error provide me with:
- An `ls -la` of the `turbo-bin` and `go-turbo-bin` path.
- What version you upgraded from, if recent.
- Confirmation via `cat` that the contents of `turbo-bin` and `go-turbo-bin` are binary.
- Output of `file` called on the `turbo-bin` and `go-turbo-bin` path.
- And, _last_, whether or not it is reproducible after `rm -rf node_modules`.

**Comment by rvuyyuru2** [comment]
--
65 | > turbo build
66 |  
67 | ERROR Unable to find Go binary. Please report this issue at https://github.com/vercel/turbo/issues and include your package manager and version along with the following information:
68 | os=linux
69 | arch=x86_64
70 | turbo-version=1.10.7
71 | turbo-bin=/codebuild/output/src1893885850/src/node_modules/turbo/bin/turbo
72 | go-turbo-bin=/codebuild/output/src1893885850/src/node_modules/turbo/bin/go-turbo
73 |  
74 | Error: Failed to execute turbo (Unable to locate Go binary).
75 |  
76 | [Container] 2023/07/17 09:07:52 Command did not exit successfully npm run build exit status 1
77 | [Container] 2023/07/17 09:07:52 Phase complete: BUILD State: FAILED
78 | [Container] 2023/07/17 09:07:52 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm run build. Reason: exit status 1

in aws code build

**Comment by dennisMeeQ** [comment]
This happened to me as well after upgrading from `v1.9.1` => `v1.10.11`. Worked locally but broke on CI (GH actions with npm). Upgrading to `v1.10.12` (which had coincidentally just come out) solved the issue.

```
Error: Failed to execute turbo (Unable to locate Go binary).
ERROR Unable to find Go binary. Please report this issue at https://github.com/vercel/turbo/issues and include your package manager and version along with the following information:
        os=linux
        arch=x86_64
        turbo-version=1.10.11
        turbo-bin=/home/runner/work/interact/interact/node_modules/turbo/bin/downloaded-turbo-linux-64-turbo
        go-turbo-bin=/home/runner/work/interact/interact/node_modules/turbo/bin/go-turbo
```

**Comment by rvuyyuru2** [comment]
@dennisMeeQ  issue solved ci pipeline ?

**Comment by BaptisteMalou** [comment]
I had the same issue on CI (GitHub action with npm):
```
ERROR Unable to find Go binary. Please report this issue at https://github.com/vercel/turbo/issues and include your package manager and version along with the following information:
        os=linux
        arch=x86_64
        turbo-version=1.10.12
        turbo-bin=/home/runner/work/malou-app/malou-app/node_modules/turbo/bin/downloaded-turbo-linux-64-turbo
        go-turbo-bin=/home/runner/work/malou-app/malou-app/node_modules/turbo/bin/go-turbo
 ```
 
 It first happened quite randomly since I didn't change anything related to turbo. 
The fix was to downgrade turbo version to `1.10.10`.

**Comment by Arylo** [comment]
Same here for github actions.
```
Error: Failed to execute turbo (Unable to locate Go binary).
ERROR Unable to find Go binary. Please report this issue at https://github.com/vercel/turbo/issues and include your package manager and version along with the following information:
        os=linux
        arch=x86_64
        turbo-version=1.10.9
        turbo-bin=/home/runner/work/js-sh/js-sh/node_modules/turbo/bin/downloaded-turbo-linux-64-turbo
        go-turbo-bin=/home/runner/work/js-sh/js-sh/node_modules/turbo/bin/go-turbo
```

Downgrading to `turbo@1.9.7` or upgrading to `turbo@1.10.10` works for me

**Comment by mkah91** [comment]
For this was a cross-platform related issue. It worked for me again after installing the right turbo version (depending on your platform):

```
npm install -D --arch=x64 --platform=linux turbo
npm install -D --arch=arm64 --platform=darwin turbo
```

**Comment by nathanhammond** [comment]
Hey y'all! I'm going to lock this issue. If anybody encounters this issue moving forward please make sure you're on 1.10.13 or newer. If you _just_ upgraded from a version less than 1.10.13 then you're likely dealing with a poisoned cache.

If you simply want things to start working again, this _will_ work:
- new global install e.g. `npm install -g turbo@latest`
- make sure `package.json` in the monorepo root for `turbo` is set to ^1.10.13. `npm install --save-dev turbo@^1.10.13`
- remove the lockfile. `rm package-lock.json`
- remove node_modules `rm -rf node_modules`
- reinstall `npm install`

After doing this you shouldn't encounter the issue again.
