### ISSUE TITLE
[turborepo] turbo 1.10.x not work with pnpm workspace exclude feature

### ISSUE THREAD

**Issue by suhaotian** [vercel/turbo#5391]
### What version of Turborepo are you using?

1.10.6

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

After update `turbo` to 1.10.6, the command with turbo (e.g `pnpm lint`) not work anymore:

```bash
> @acme/monorepo@ lint /Users/suhaotian/Projects/expo-monorepo-example
> turbo lint

• Running lint
• Remote caching disabled
root task lint (turbo lint) looks like it invokes turbo and might cause a loop

No tasks were executed as part of this run.

 Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
  Time:    68ms 
```

But if I use `turbo@1.9.9` or If I delete these lines `- '!**/dist**'` and `'!**/.next**'` in the `pnpm-workspace.yaml`, it will work:
```yaml
packages:
  - 'apps/*'
  - 'packages/**'

  # exclude dist projects
  - '!**/dist**'
  # exclude .next projects
  - '!**/.next**'

```

### Expected Behavior

Should work after bump turbo version

### To Reproduce

```bash
pnpm install
pnpm lint
# or
pnpm build
```

### Reproduction Repo

https://github.com/suhaotian/expo-monorepo-example/tree/bump-deps

**Comment by zxlisrich** [comment]
I have same problem

**Comment by gabriellet** [comment]
I have this problem on a Mac using yarn with versions `1.10.3` and `1.10.6`. I don't see the issue on `1.10.4` though.

**Comment by gsoltis** [comment]
@suhaotian @zxlisrich @gabriellet 

Here's what's going on: we've started tightening some of our glob validation, and 
 1. the exclusion globs are not technically valid (up for debate, different libraries have different rules)
 2. we're not doing a great job reporting what the actual error is (we should be telling you which glob had the problem)
 
So, short term fix: for `!**/dist**`, decide if you mean `!**/dist*/**` or `!**/dist/**` (probably this one), and update your glob accordingly, and then do the same for `!**/.next**`.

We'll work on, at minimum, getting a better error message in place. I'm not sure if we need to relax the strictness of our globbing, as there are two possible interpretations of this particular pattern. The more accepting option, `!**/dist*/**`, is (I'm assuming) probably not what you want to specify in this case.

**Comment by suhaotian** [comment]
Thank you so much. This is really helpful! @gsoltis

**Comment by lorensr** [comment]
This is similar to https://github.com/vercel/turbo/issues/5331 and https://github.com/vercel/turbo/discussions/5290

I stopped the error by pinning `1.10.4` in this project:

[turbo.json](https://github.com/temporalio/samples-typescript/blob/bb3ecaa3cdb1d8eb2b1d24828ac78b4f1275988c/food-delivery/turbo.json)

It also stopped this error: 

```
Package tasks (<package>#<task>) are not allowed in single-package repositories: found worker#build
```

I'm not sure why, because I have multiple packages and need certain packages to be built before the `worker` package or I get a build error like `Cannot find module 'common/lib/temporal-connection'`.

**Comment by suhaotian** [comment]
@lorlorloren already solved this issue follow the steps by @gsoltis 

and also you can check the already fixed the reproduce repo commit: https://github.com/byCedric/expo-monorepo-example/commit/b56ea3db5354a21a32c9636972f8bf7734ab66c6
