### ISSUE TITLE
[turborepo] eslint-plugin-turbo: `dotEnv` support differs between workspace setting and root setting

### ISSUE THREAD

**Issue by konomae** [vercel/turbo#5393]
### What version of Turborepo are you using?

1.10.6

### What package manager are you using / does the bug impact?

npm / pnpm

### What operating system are you using?

Mac

### Describe the Bug

Sample repository:
https://github.com/konomae/turbo-lint-repro-202306

In the [main](https://github.com/konomae/turbo-lint-repro-202306/tree/main) branch, dotEnv is specified in the root configuration, but an error occurs.

```bash
npm exec eslint .

/Users/user/turbo-lint-repro/apps/myapp/index.js
  1:13  error  HELLO is not listed as a dependency in the root turbo.json or workspace (apps/myapp) turbo.json  turbo/no-undeclared-env-vars

✖ 1 problem (1 error, 0 warnings)
```

In the [use-workspace-config](https://github.com/konomae/turbo-lint-repro-202306/compare/use-workspace-config) branch, dotEnv is specified in the workspace configuration, no errors occur.

```bash
npm exec eslint .
# no errors
```

### Expected Behavior

Behavior should be consistent.
Perhaps the latter (no errors) is preferable.

### To Reproduce

Sample repository:
https://github.com/konomae/turbo-lint-repro-202306

<sub>[TURBO-2629](https://linear.app/vercel/issue/TURBO-2629/[turborepo]-eslint-plugin-turbo-dotenv-support-differs-between)</sub>

**Comment by vlapo** [comment]
Have the same problem. It looks like the documentation is not valid or it is a bug. In case we have one `turbo.json` file in the root of the project it will resolve `dotEnv` config relative to root of project instead of the workspace root (e.g. `/apps/web/`) 

<img width="860" alt="image" src="https://github.com/vercel/turbo/assets/2484063/8b5ad126-3e4d-43eb-988b-17187086c2a7">

**Comment by vlapo** [comment]
@nathanhammond  is this behaviour intended

**Comment by mehulkar** [comment]
I was able to reproduce this on latest canary `eslint-config-turbo@1.12.5-canary.2` also

**Comment by anthonyshew** [comment]
`dotEnv` has been removed so this issue is no longer relevant. However, to explain, environment variables need to be enumerated in [the `env` key](https://turbo.build/repo/docs/reference/configuration#env) to be accounted for in hashing.

**Comment by konomae** [comment]
> https://turbo.build/repo/docs/reference/configuration#env
> Turborepo automatically includes environment variables prefixed by common frameworks through Framework Inference. For example, if your package is a Next.js project, you do not need to specify any environment variables that start with NEXT_PUBLIC_.

I want `eslint-plugin-turbo` to know about that.
I think that would eliminate the need to include the NEXT_PUBLIC_ prefix to turbo.json for the eslint plugin.

But this is a different issue and I may file another issue later.
