### ISSUE TITLE
[turborepo] error performing lockfile operation: Unable to find resolved version for xxx@link:packages/xxx

### ISSUE THREAD

**Issue by tjx666** [vercel/turbo#5407]
### What version of Turborepo are you using?

1.10.6

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I use pnpm.overrides to lock one dependency:

```json
{
    "pnpm": {
        "overrides": {
            "follow-redirects": "workspace:*"
        }
    }
}
```

Then whenever run turbo, will notify:

```node
 WARNING  Issues occurred when constructing package graph. Turbo will function, but some features may not be available:  1 error occurred:
        * error performing lockfile operation: Unable to find resolved version for follow-redirects@link:packages/follow-redirects in apps/web
```

![image](https://github.com/vercel/turbo/assets/41773861/7c638c32-0669-4da1-84c7-81302c66fcbf)

### Expected Behavior

no warning

### To Reproduce

1. git clone git@github.com:tjx666/turbo-issue.git
2. pnpm install
3. pnpm run build

### Reproduction Repo

https://github.com/tjx666/turbo-issue

**Comment by chris-olszewski** [comment]
Thanks for the issue, we our current support for pnpm overrides is very limited and I'm guessing that the `workspace` protocol is tripping us up. I should have time to take a look tomorrow.

**Comment by leonard-henriquez** [comment]
I have a similar error:
<img width="1213" alt="CleanShot 2023-07-16 at 01 21 59@2x" src="https://github.com/vercel/turbo/assets/30215564/06594c64-021f-4d6a-88b0-8be3ac12bf62">

@chris-olszewski do you know any workaround?

**Comment by anthonyshew** [comment]
Closing due to staleness.
