### ISSUE TITLE
[turbopack] Stuck in infinite GET request loop when using Next-Auth middleware.

### ISSUE THREAD

**Issue by TheToughest** [vercel/turbo#5408]
### What version of Turborepo are you using?

--turbo

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Problem
Using NextAuth in nextjs and writing a simple middleware file (as shown in my [stackoverflow issue](https://stackoverflow.com/questions/76565934/nextjs-13-stuck-in-infinite-get-request-loop-when-using-next-auth-middleware-f)), causes the app to be stuck in an infinite status 200 get request loop. I suggest it is a turbopack issue, whenever I remove --turbo from my package.json the middleware works as expected and route protection with nextjs's middleware works.

### Middleware.ts
```ts
export { default } from 'next-auth/middleware'

export const config = {
    matcher: "/settings"
}
```

### Link to stackoverflow question
[Link](https://stackoverflow.com/questions/76565934/nextjs-13-stuck-in-infinite-get-request-loop-when-using-next-auth-middleware-f)

### Image
![afbeelding](https://github.com/vercel/turbo/assets/45489013/18a8b4a5-9e14-4054-a975-6fe4ca185987)

### Expected Behavior

No GET loop is happening after loggin in and accessing a protected route.

### To Reproduce

 - Create a simple next.js application and enable turbopack and implement [next-auth](https://next-auth.js.org/).
 - In my case I am using prisma for a connection to a local MySQL database and a credentialsprovider.
 - Add a middleware.ts in the root folder of the project with the basic middleware as shown above.
 - Access a protected route, while logged in and check the network tab in the dev tools of your browser.
 - Enjoy the frozen site and GET loop as shown in the picture above.

**Comment by arlyon** [comment]
Thanks for the report, I have reassigned it to the turbopack team.

**Comment by s3f5** [comment]
Having the same issue, with a simple redirect middleware.

**Comment by dogukanoksuz** [comment]
Looks like middlewares not working well with Turbopack. I also have this problem with my authenticated app.

**Comment by AlonMiz** [comment]
> > Having the same issue, with a simple redirect middleware.
> 
> Just disable turbopack until the issue is resolved or try and move to another authentication service like clerk.

i experience the issue here, while using clerk

**Comment by digitaltopo** [comment]
Is there another ticket tracking this issue somewhere? Experiencing this exact issue as well.

**Comment by omgismartinez** [comment]
I am using Clerk Auth and I have an `infinite loop`, inside the middleware I have the condition if I am already in the path with `req.nextUrl.pathname` but I still get the error.

````typescript
if (!user.privateMetadata.role && req.nextUrl.pathname !== '/started') {
    const started = new URL('/started', req.url)
    return NextResponse.redirect(started)
}

**Comment by timneutkens** [comment]
The issue with Clerk has been fixed some time ago. Can you try again?

**Comment by AlonMiz** [comment]
Works for me🙏👏

**Comment by timneutkens** [comment]
Thanks for checking!

**Comment by timneutkens** [comment]
Asked @balazsorban44 to check the next-auth case as well and that one works too 🙌
