### ISSUE TITLE
Depend on all packages when using "^task" in root

### ISSUE THREAD

**Issue by dipunm** [vercel/turbo#5409]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

The root project will typically not depend on its packages, however if you want to run a script after a specific task has been executed on all packages, I can't see a way to do this.

Imagine a root package.json file with:
```json
"scripts": {
    "verify": "turbo lint test build report-coverage",
    "report-coverage": "node scripts/coverage.js"
}
```

The verify script works fine, "report-coverage" depends on all "test" tasks to be complete but does not rely on all "build" tasks to be complete.

I can't figure out how I can make report-coverage depend on all "test" tasks, instead it runs in parallel.

My turbo.json file:
```
{
    "$schema": "https://turbo.build/schema.json",
    "pipeline": {
        "build": {
            "dependsOn": ["^build"],
            "outputs": [ "dist/**" ]
        },
        "lint": {},
        "test": {
            "outputs": ["coverage/**"]
        },
        "//#report-coverage": {
            "dependsOn": ["^test"]
        }
    }
}
```

### Describe the solution you'd like

Unless there is already a use case for defining `^task` for root project tasks, I think we should implicitly treat all packages as a dependency of the root project.

### Describe alternatives you've considered

Alternative I have considered is being able to reference all packages using the following syntax: `*#test`

**Comment by unematiii** [comment]
I have the same problem, apparently specifying st like
```
 "//#report-coverage": {
       "dependsOn": ["^test"]
 },
```
in root `turbo.json` has no effect.

**Comment by mehulkar** [comment]
Couple things to think about:

- Running a task after some set of tasks has completed. We can loosely call it a "finalization" task, and it's a general purpose tool we could design around
- "Root" depending on all packages. I'm not sure `^` is appropriate for this, because we really do want that to mean a topological dependency through `package.json` `dependencies`. 

That said, I'll bring this up at the next team meeting

**Comment by mehulkar** [comment]
On second thought, this actually looks identical to #4145, closing out.
