### ISSUE TITLE
[turborepo] Automatic Workspace Scoping feature is no longer working on 1.10.5 and up

### ISSUE THREAD

**Issue by nvie** [vercel/turbo#5429]
### What version of Turborepo are you using?

1.10.6

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

The Automatic Workspace Scoping feature as it was [introduced in 1.8](https://turbo.build/blog/turbo-1-8-0#automatic-workspace-scoping) is no longer working on 1.10.5 and up. Downgrading back to 1.10.4 makes it work again.

### Expected Behavior

When I'm inside a workspace directory and I run `turbo build`, I expect to only run the build for that workspace, but this no longer is happening. Instead, all the builds are being run (as if run from the top-level of the repo).
Explicitly passing `--filter` _does_ still work, but it's no longer being auto-detected anymore.

### To Reproduce

```
$ npm i turbo@1.10.6   # or 1.10.5
$ cd /path/to/workspace
$ turbo build
```

It should only run the builds for that workspace.
Instead, it runs _all_ the builds.

### Reproduction Repo

https://github.com/liveblocks/liveblocks

**Comment by gsoltis** [comment]
@nvie confirmed, thanks for the report and repro!

We'll get a fix out asap
