### ISSUE TITLE
[turborepo] The `^` char in `dependsOn` does not work when using `alias package name`

### ISSUE THREAD

**Issue by dileedotdev** [vercel/turbo#5441]
### What version of Turborepo are you using?

1.10.7

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

The `^` char in `dependsOn` does not work when using `alias package name`

My config
```json
    "build": {
      "dependsOn": ["^build"],
      "outputs": [".next/**", "!.next/cache/**", "dist/**"]
    },
```

My app dependency

```json
    "dependencies": {
       "ui": "workspace:@resolvex/ui@^",
    }
```

When I run `build` both the app and package run concurrently

But if I not using an alias it work correctly

### Expected Behavior

App wait util package done for `build`

### To Reproduce

Install dependency by using an alias

**Comment by dcop** [comment]
Same issue, but on MacOS

**Comment by gsoltis** [comment]
I was able to confirm that this is a bug.
