### ISSUE TITLE
`pnpm dlx create-turbo@latest` doesn't work behind proxy

### ISSUE THREAD

**Issue by itayperry** [vercel/turbo#5446]
### What version of Turborepo are you using?

1.10.7

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Hi, I'm trying to create a new turborepo folder based on the basic example you have in the docs.
I run the command `pnpm dlx create-turbo@latest` and it gets stuck forever at `Downloading files...`.

I have the proxy address configured in my `.bashrc` and `.npmrc` (environment variables: `http_proxy`, `https_proxy`).

Older versions of `create-turbo` do not have this issue, for example 1.8.8 works.

I am using Ubuntu WSL2.

![image](https://github.com/vercel/turbo/assets/37377389/37b37cf0-c264-4220-8656-1d50741cd749)

### Expected Behavior

`create-turbo` should use the configured proxy from environment variables.

### To Reproduce

Bash example:
```bash
export http_proxy=http://<server>:<port>
export https_proxy=http://<server>:<port>
pnpm dlx create-turbo@latest
```

**Comment by jcteague** [comment]
getting similar issue with `npx create-turbo@latest`
```Where would you like to create your turborepo? .
? Which package manager do you want to use? npm

Downloading files. This might take a moment.


>>> Unexpected error. Please report it as a bug:
Ov [Error]: Client network socket disconnected before secure TLS connection was established
    at Xo (/Users/uut301/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:150:268)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.lh (/Users/uut301/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:218:615)
    at async Command.parseAsync (/Users/uut301/.npm/_npx/e8c68b66aeb1424f/node_modules/commander/lib/command.js:935:5)```

I went down to v1.9.9 and still had the error.

**Comment by gsoltis** [comment]
Thanks for the report, we can take a look at adding support for proxies
