### ISSUE TITLE
[turborepo] Regression -  ERROR  run failed: error hashing package files: git error: 'git status' in REPO/packages/tsconfig had a parse error path error: Path packages/tsconfig is not parent of .editorconfig

### ISSUE THREAD

**Issue by ivancuric** [vercel/turbo#5447]
### What version of Turborepo are you using?

1.10.7

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Husky push hook runs a lint-staged task. I am getting the following error only when ran via turbo:

```
[turborepo] Regression -  ERROR  run failed: error hashing package files: git error: 'git status' in REPO/packages/tsconfig had a parse error path error: Path packages/tsconfig is not parent of .editorconfig
```

Reverting to 1.10.6 fixes this issue.

### Expected Behavior

This shouldn't happen.

### To Reproduce

Wasn't able to reproduce in a new repo, can't share current one.

**Comment by hta218** [comment]
Same here: 

```bash
ERROR  run failed: error hashing package files: git error: 'git status' in <MY_REPO> had a parse error path error: Path <SUB_MODULE_PATH> is not parent of package-lock.json
```

**Comment by luke-concannon** [comment]
same...

```
Turbo error: error hashing package files: git error: 'git status' in /Users/lumirari/dev/wematter/packages/eslint-config-custom exited with code 129 stderr: error: unknown option `no-renames'
usage: git status [<options>] [--] <pathspec>...
```

**Comment by sammyfilly** [comment]
How do you get the parent json file

**Comment by luke-concannon** [comment]
@sammyfilly can you ask your question in a different / more descriptive way? Do you mean the root package.json? What do you mean by 'how do you get...'?

**Comment by chris-olszewski** [comment]
Hi all, sorry for this issue and thanks for identifying the change as something in `1.10.7`. Could someone who can reproduce the `ERROR  run failed: error hashing package files: git error: 'git status'` give me the following information:
 - Output of `git ls-tree -r HEAD`
 - Directory that you're executing turbo in
 - Globs that you're using to find workspaces (either in `package.json` or `pnpm-workspace.yaml` depending on package manager)

Thanks in advance as this will help me a lot.

**Comment by chris-olszewski** [comment]
@luke-concannon Can you try updating your git version?

**Comment by luke-concannon** [comment]
updating git version did the trick. Thanks @chris-olszewski

**Comment by franzwilhelm** [comment]
@chris-olszewski if a specific git version is required, it might be a good idea to include that as part of the error message + mention it in the docs. It's hard to see the connection between git and turbo, so the debug process might be hard. In fact, you might stop allowing to run turbo commands if a git version too low is found

**Comment by mortalYoung** [comment]
Same here. 
It's better to mention it in the docs about the connection between git and turbo. Or list the version of git that turbo@1.10.7 is competible with

**Comment by hta218** [comment]
Upgraded `git` to `v2.41.0` but the problem still remains.
![image](https://github.com/vercel/turbo/assets/24975260/35088f98-d306-4e9a-95d4-bd0bd71d8648)
Does anyone have any idea how to handle this error? 🙄

**Comment by franzwilhelm** [comment]
@hta218 https://github.com/vercel/turbo/issues/5447#issuecomment-1621908600

**Comment by chris-olszewski** [comment]
I don't believe git version is the cause of most of these issues only errors that complain about `--no-renames` not being a valid git flag. 

I once again am asking for people who encounter this issue to include some additional information that will help me figure out what's going on: https://github.com/vercel/turbo/issues/5447#issuecomment-1622682573

@Vintotan 
If you only use `turbo` globally (`turbo` isn't listed in your project's `package.json`) then `npm install -g turbo@1.10.6` will do the trick.

**Comment by gsoltis** [comment]
@hta218 I wonder if this is a git submodule issue. Do you have  a submodule included in what you're hashing?

@ivancuric same question, are you using a git submodule?

**Comment by ivancuric** [comment]
Nope, no submodules.

**Comment by gsoltis** [comment]
@ivancuric We're having some trouble reproducing this. Can you provide your `git` version (`git --version`) and the output of `git status --untracked-files --no-renames -z -- .` run from the directory of the package that's causing an error, right after the error occurs? I think it's `<REPO>/packages/tsconfig`. Note that this output will include some null bytes and be on a single line, which is expected.

Also, just want to confirm, when you run `lint-staged`, what is the `turbo` command that ends up being invoked? Is it a root task (`//#some-command` in `turbo.json`) or is it running a command in every workspace (`turbo some-command`) ?

**Comment by gsoltis** [comment]
Also, if you can try `turbo@1.10.8-canary.0`, we added some more verbose logging to the `git status` call to try to determine what is going on.

**Comment by JosephMing** [comment]
<img width="833" alt="image" src="https://github.com/vercel/turbo/assets/31059354/dcc6da9a-c769-43ac-8dc9-a3a60544932c">

**Comment by hta218** [comment]
@gsoltis Yes, I have a git submodule inside my turbo repo

**Comment by gsoltis** [comment]
Hey all, we've released `turbo@1.10.8-canary.1` which implements a fallback for when git-based hashing fails for any reason. Can you all give it a try and verify that it's working for you? In my own tests it successfully handles things like git submodules

**Comment by isometriq** [comment]
I'm just beginning to learn with `turbo@1.10.7` and I'm using submodules. The hasgThe canary
```
Turbo error: error hashing package files: git error on /Users/iso/Dev/domain/.turbo/turbo-build.log: could not find '/Users/iso/Dev/domain/.turbo/turbo-build.log' to open: No such file or directory; class=Os (2); code=NotFound (-3)
```
The canary version allowed the build to start (although i have other errors in my build to fix, not related to the discussed issue).

**Comment by towry** [comment]
I have a monorepo that has a subfold is a standalone git repo but ignored in the monorepo(do not want use git submodules because have to commit it everytime).

This error happens when the ignored git subfolder is changed and have to commit the ignored git subfolder.
