### ISSUE TITLE
[turbopack] res.end and res.write not working with Turbopack

### ISSUE THREAD

**Issue by ashishkankal** [vercel/turbo#5451]
### What version of Turborepo are you using?

13.4.8

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

I am trying to use the write and end function from res. Its throwing the error `Error: write is not implemented`

Below is the code.
```
// pages/index.tsx

import { GetServerSidePropsContext } from "next";

const ExamplePage = () => {
  return (
    <div>
      <h1>Test Page </h1>
    </div>
  );
};

export const getServerSideProps = (ctx: GetServerSidePropsContext) => {
  ctx.res.setHeader("Content-Type", "application/xml");
  ctx.res.write(
    "<breakfast_menu><food><name>Belgian Waffles</name><price>$5.95</price><description>Two of our famous Belgian Waffles with plenty of real maple syrup</description><calories>650</calories></food></breakfast_menu>"
  );
  ctx.res.end();
  return { props: {} };
};
export default ExamplePage;
```

### Expected Behavior

It should load the xml response similarly when we run the project using webpack.

### To Reproduce

1. Clone the Repository
2. Run the command `npm run turbo`
3. Throws the error (screenshot attached)

<img width="963" alt="image" src="https://github.com/vercel/turbo/assets/7954909/e6d4088b-c0f5-4429-ac0c-0f1fee5bdcc3">

### Reproduction Repo

https://github.com/ashishkankal/turbo-repo-example

**Comment by timneutkens** [comment]
This works now, thanks for the report!

Codesandbox: https://codesandbox.io/p/github/ashishkankal/turbo-repo-example/csb-r2y7sh/draft/zealous-swartz?file=%2Fpages%2Findex.tsx
