### ISSUE TITLE
[turborepo] Undetected task failures

### ISSUE THREAD

**Issue by robaca** [vercel/turbo#5454]
### What version of Turborepo are you using?

1.10.7

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Linux

### Describe the Bug

We are seeing in our pipelines, that some tasks are not correctly handled as failed. 

Looking at the summary JSON, they are shown with cache miss, exit code 0 and startTime == endTime, but looking at the task output log referenced by the summary, it definitely took some time and finally failed. 

Followup tasks are also shown as executed with zero duration, but with empty logs. 

One such task summary looks like this:
```json
    {
     "taskId": "@some/service#test:interface",
      "task": "test:interface",
      "package": "@some/service",
      "hash": "b37ffa867c3d6928",
      "inputs": {
        ...
      },
      "hashOfExternalDependencies": "6d49749eed1fb17b",
      "cache": {
        "local": false,
        "remote": false,
        "status": "MISS",
        "timeSaved": 0
      },
      "command": "../../../scripts/pipeline/test-interface.sh",
      "cliArguments": [],
      "outputs": [
        "acceptance/build/reports/**",
        "acceptance/build/test-results/**"
      ],
      "excludedOutputs": null,
      "logFile": "packages/some/service/.turbo/turbo-test:interface.log",
      "directory": "packages/some/service",
      "dependencies": [
        ...
      ],
      "dependents": [
        ...
      ],
      "resolvedTaskDefinition": {
        "outputs": [
          "acceptance/build/reports/**",
          "acceptance/build/test-results/**"
        ],
        "cache": true,
        "dependsOn": [
          ...
        ],
        "inputs": [],
        "outputMode": "new-only",
        "persistent": false,
        "env": [
          "SKIP_TESTS"
        ],
        "passThroughEnv": null,
        "dotEnv": null
      },
      "expandedOutputs": [],
      "framework": "",
      "envMode": "loose",
      "environmentVariables": {
        "specified": {
          "env": [
            "SKIP_TESTS"
          ],
          "passThroughEnv": null
        },
        "configured": [
          "SKIP_TESTS=fcbcf165908dd18a9e49f7ff27810176db8e9f63b4352213741664245224f8aa"
        ],
        "inferred": [],
        "passthrough": null
      },
      "dotEnv": null,
      "execution": {
        "startTime": 1688461653699,
        "endTime": 1688461653699,
        "exitCode": 0
      }
    }
```

### Expected Behavior

The tasks are shown with correct startTime and endTime and proper exit code.
Followup tasks are skipped and are not in the summary or marked as skipped (like `skipped: true`).

### To Reproduce

Don't know how to reproduce in a separate repo - it happens reproducible in our customer project only for specific tasks.

**Comment by robaca** [comment]
In another run, we now just have two `deploy:dev` tasks of different services, failing with the same error, one reported as failed and one with 0sec exit code 0.

**Comment by robaca** [comment]
This behavior makes sense to me, if these 0ms tasks are unfinished tasks because of other failures in the pipeline. But how can I detect that reliably from the summary data?

**Comment by NicholasLYang** [comment]
Hi @robaca, thanks for the issue. We'll look into this. Full disclosure, we're in the process of moving this code from Go to Rust and hopefully that should provide a more...robust handling of empty values. Currently we set values to 0/`nil` in Go, whereas in Rust we can use enums to explicitly note that the task did not complete successfully.

**Comment by anthonyshew** [comment]
Summaries are now in Rust! I'll mark this as stale since, as @NicholasLYang mentioned, this probably existed as a Go problem.

If you're still running into this, please create a new issue with a reproduction.
