### ISSUE TITLE
[turbopack] error <Link />

### ISSUE THREAD

**Issue by daniellx42** [vercel/turbo#5460]
### What version of Turborepo are you using?

1.10.7

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

error when using the @modal/(..cards)[id]/pages.tsx folder, when using the `<Link />` of /next/link instead of opening @modal it sends the user to the @modal page

### Expected Behavior

as expected and when you click on @modal it opens as a popup taking the id of the parameter

### To Reproduce

`<Link href={`/cards/${posts.post.id}`} >...</Link>`

pnpm next dev ✔️ --> opens a popup

pnpm next dev --turbo 🗙 --> send to another page

**Comment by chris-olszewski** [comment]
This looks like an issue with turbopack and not repo. Can you include what version of `next` you're using?

**Comment by daniellx42** [comment]
Sorry, I selected turborepo instead of turbopack but I already corrected the nomenclature. The version I'm using is "next": "13.4.8"

**Comment by ForsakenHarmony** [comment]
Please open a new issue with a complete reproduction in the next.js repo if this is still an issue.
