### ISSUE TITLE
[turborepo] - `turbo gen workspace` >>> r.flatMap is not a function

### ISSUE THREAD

**Issue by solomon-bush** [vercel/turbo#5471]
### What version of Turborepo are you using?

1.10.7

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Command
```sh
~/Workspaces/LogHarvestor/log-harvestor ❯ turbo gen workspace              
```

### Error
```sh
>>> Unexpected error. Please report it as a bug:
r.flatMap is not a function
```

### Expected Behavior

Trying to follow this guide -> https://turbo.build/repo/docs/core-concepts/monorepos/code-generation

### To Reproduce

run `turbo gen workspace` from root of a turbo repo

ENV information:
```
OS: Apple M1 Pro - macOS: 13.4.1 (22F82)
NPM: 9.8.0
NODE: 20.4.0
TURBO: 1.10.7
```

**Comment by chris-olszewski** [comment]
Hi @solomon-bush, can you include the value of your `workspaces` field in your root `package.json`?

**Comment by tknickman** [comment]
Available now in `turbo@canary`. 

To test with `gen`, you'll need to also pass one additional arg - `npx turbo@canary gen --tag canary`
