### ISSUE TITLE
When I use edge runtime with Turbopack it showing a error

### ISSUE THREAD

**Issue by shakibdshy** [vercel/turbo#5480]
### What version of Next.js are you using Turbopack in?

13.4.4, 

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

![image](https://github.com/vercel/turbo/assets/15661765/7dbeb1bc-c6cb-455a-9dc6-d189dc958d74)

### Expected Behavior

I am actually using Turbopack example with this command and it's a fresh installation 

`npx create-next-app --example with-turbopack`

### To Reproduce

![image](https://github.com/vercel/turbo/assets/15661765/e49a6c5d-f970-4696-afae-5d7329de1c59)

**Comment by timneutkens** [comment]
This has been fixed!
