### ISSUE TITLE
[turborepo] Path aliases in packages/ui workspace

### ISSUE THREAD

**Issue by aytacyaydem** [vercel/turbo#5501]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

I am trying to setup Turborepo with two namespaces one of them is packages and another is apps. I have two Nextjs project in apps and I have components, config files in packages workspace. I am trying to setup path aliases in packages workspace and I am facing an issue. Here my codes:

File: packages/ui/modules/programApplicationStatus.js
```
const PROGRAM_APPLICATION_STATUS = Object.freeze({
  APPLIED: { value: "APPLIED", label: "Applied", color: "blue.500" },
  ACCEPTED: { value: "ACCEPTED", label: "Accepted", color: "green.500" },
  REJECTED: { value: "REJECTED", label: "Rejected", color: "red.500" },
  ENROLLED: { value: "ENROLLED", label: "Enrolled", color: "purple.500" },
  WAITING_ROOM: {
    value: "WAITING_ROOM",
    label: "Waiting Room",
    color: "orange.400",
  },
});

export default PROGRAM_APPLICATION_STATUS;
```

File: packages/ui/tsconfig.json:
```
{
  "extends": "tsconfig/react-library.json",
  "include": ["."],
  "exclude": ["dist", "build", "node_modules"],
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@components/*": ["./components/*"],
      "@constants/*": ["./constants/*"],
      "@context/*": ["./context/*"],
      "@fragments/*": ["./fragments/*"],
      "@hooks/*": ["./hooks/*"],
      "@hocs/*": ["./hocs/*"],
      "@layouts/*": ["./layouts/*"],
      "@modules/*": ["./modules/*"],
      "@mutations/*": ["./mutations/*"],
      "@queries/*": ["./queries/*"],
      "@specialContents/*": ["./specialContents/*"],
      "@utils/*": ["./utils/*"]
    }
  }
}
```

File: apps/docs/pages/index.js
```
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import HomePageCard from "ui/components/HomepageCard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <HomePageCard />
        <div>asdasd</div>
      </main>
    </>
  );
}
```

**ERROR:**
../../packages/ui/components/HomepageCard/index.js:2:0
Module not found: Can't resolve '@modules/programApplicationStatus'
  1 | import { Badge, Card, Flex, Text, Link } from "@chakra-ui/react";
> 2 | import PROGRAM_APPLICATION_STATUS from "@modules/programApplicationStatus";
  3 | import dayjs from "dayjs";
  4 | import React from "react";
  5 | import RemainingDayBadge from "../RemainingDayBadge";

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./pages/index.js

How Can I fix it?

### Expected Behavior

 import PROGRAM_APPLICATION_STATUS from "@modules/programApplicationStatus"
 
 ıt should work correctly

### To Reproduce

-

**Comment by gsoltis** [comment]
I don't think this is a Turborepo-specific issue, but it is a typescript-in-monorepos issue. I suspect you need to set your path aliases properly for your nextjs application. Some samples and discussion can be found [here](https://github.com/vercel/turbo/discussions/620#discussioncomment-2135849)
