### ISSUE TITLE
[turborepo] Error running turbo with modified submodule files

### ISSUE THREAD

**Issue by mattoni** [vercel/turbo#5521]
### What version of Turborepo are you using?

1.10.7

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Linux & Mac

### Describe the Bug

Getting an error whenever a git submodule file is edited, and then trying to run turbo. If any submodule file is different from origin and a turbo command is executed, I get the following error:

```
ERROR  run failed: error hashing package files: git error on /home/alex/Dev/-/cycle/cycle-web-monorepo/public/paths/dns/tasks.yml: could not find '/home/alex/Dev/-/cycle/cycle-web-monorepo/public/paths/dns/tasks.yml' to open: No such file or directory; class=Os (2); code=NotFound (-3)
```
The submodule is located in `/home/alex/Dev/-/cycle/cycle-web-monorepo/openapi/public-spec/public/paths/dns/tasks.yml` where both `openapi` and `public spec` are git submodules (3 levels deep). This was working perfectly fine in 1.10.6, so something changed recently to cause this issue. It seems like it's now searching the top directory for a very nested path for hashing purposes, instead of in the nested path it should be. Quite possible this is related to the other issue I reported in #5485. This is a pretty crucial bug for my company, since it prevents turborepo from working correctly.

### Expected Behavior

Turbo would work correctly without error like it does in 1.10.6

### To Reproduce

I believe this will happen with any modified submodule file and doing `turbo run`. If it is unable to easily be triaged, let me know and I'll put together a reproducible example.

**Comment by louisgv** [comment]
Seeing the same issue with a 1-level deep nested submodule, using `pnpm@8.6.5` and `turbo@1.10.7`

**Comment by gsoltis** [comment]
I think this should be fixed in `turbo@1.10.8-canary.1`. Can you verify? @louisgv @mattoni

**Comment by towry** [comment]
`turbo@1.10.8-canary.2` works for me.

**Comment by anthonyshew** [comment]
Looks like this was fixed according to feedback above.
