### ISSUE TITLE
[turborepo] `packageExtensions` reorder causes checksum error

### ISSUE THREAD

**Issue by gerbyzation** [vercel/turbo#5526]
### What version of Turborepo are you using?

1.10.7

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

If turbo rewrites the root `package.json` as part of the prune operation it doesn't respect the order of the `packageExtensions`, which causes a checksum failure when installing with a frozen lockfile.

We have a monorepo with `packageExtensions` set in the root `package.json`:
```
		"packageExtensions": {
			"@reach/skip-nav": {
				"peerDependencies": {
					"@types/react": "*"
				}
			},
			"@reach/polymorphic": {
				"peerDependencies": {
					"@types/react": "*"
				}
			}
		},
```

Note the (non-alphabetical) order. The `pnpm-lock.yaml` file has the following checksum calculated: `packageExtensionsChecksum: de7edee8e04c1ce0d1c3be75d9979308`

When using `turbo prune` the new root `package.json` file it generates writes these in alphabetical order:
```
    "packageExtensions": {
      "@reach/polymorphic": {
        "peerDependencies": {
          "@types/react": "*"
        }
      },
      "@reach/skip-nav": {
        "peerDependencies": {
          "@types/react": "*"
        }
      }
    },
```

The checksum in the newly generated `pnpm-lock.yaml` has remained the same, so when now running `pnpm install --frozen-lockfile` on the pruned output the following error will show:

```
 ERR_PNPM_LOCKFILE_CONFIG_MISMATCH  Cannot proceed with the frozen installation. The current "packageExtensionsChecksum" configuration doesn't match the value found in the lockfile
```

### Expected Behavior

Either generates a correct checksum for the changes made, or leaves the `packageExtensions` order as-is.

### To Reproduce

A repro is available at https://github.com/gerbyzation/pnpm-package-extension-checksum-error-repro

```
pnpm exec turbo prune --scope lib-a
cd out
pnpm install --frozen-lockfile
```

### Reproduction Repo

https://github.com/gerbyzation/pnpm-package-extension-checksum-error-repro

**Comment by chris-olszewski** [comment]
Thanks for the repro. Once #5531 lands we'll have a better path forward to handle this. 

In the meantime, could you reorder the `packageExtensions` field to be alphabetical and regenerate `pnpm-lock.yaml` before attempting to prune? I realize this isn't ideal, but it should unblock you.

**Comment by gerbyzation** [comment]
Yes we're already been doing that in the meantime. Thanks for looking into this!

**Comment by gerbyzation** [comment]
Following the issue you filed with  PNPM they've made some changes and going forward will calculate the checksum order-independent: https://github.com/pnpm/pnpm/pull/6839. 

Unless we're concerned about this issue for older versions of PNPM this can probably be closed?

**Comment by chris-olszewski** [comment]
Once a `pnpm` release with https://github.com/pnpm/pnpm/pull/6839 is released the issue should be resolved. Will keep the issue open until I can suggest a specific version as a fix.

**Comment by chris-olszewski** [comment]
For anyone who encounters this issue, upgrading to `pnpm@8.6.10` will mitigate it as `packageExtensionsChecksum` will no longer depend on the ordering of `packageExtensions`
