### ISSUE TITLE
[turbopack] Cannot read properties of undefined (reading 'parse')

### ISSUE THREAD

**Issue by sepcnt** [vercel/turbo#5545]
### What version of Next.js are you using Turbopack in?

13.4.2

### What package manager are you using / does the bug impact?

npm, pnpm

### What operating system are you using?

Windows

### Describe the Bug

Turbopack conflicts with `recharts` , which works fine with webpack. (npm also not works)

Call Stack
<unknown>
/turbopack/[project]/node_modules/.pnpm/reduce-css-calc@2.1.8/node_modules/reduce-css-calc/dist/index.js (39:30)
walk
/turbopack/[project]/node_modules/.pnpm/postcss-value-parser@3.3.1/node_modules/postcss-value-parser/lib/walk.js (19:7)
push.[project]/node_modules/.pnpm/postcss-value-parser@3.3.1/node_modules/postcss-value-parser/lib/index.js (ecmascript).ValueParser.walk
/turbopack/[project]/node_modules/.pnpm/postcss-value-parser@3.3.1/node_modules/postcss-value-parser/lib/index.js (18:3)
push.[project]/node_modules/.pnpm/reduce-css-calc@2.1.8/node_modules/reduce-css-calc/dist/index.js (ecmascript).exports.default
/turbopack/[project]/node_modules/.pnpm/reduce-css-calc@2.1.8/node_modules/reduce-css-calc/dist/index.js (29:51)
Text
/turbopack/[project]/node_modules/.pnpm/recharts@2.7.2_prop-types@15.8.1_react-dom@18.2.0_react@18.2.0/node_modules/recharts/es6/component/Text.js (208:17)
renderWithHooks
/turbopack/[project]/node_modules/.pnpm/next@13.4.10_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (10697:18)
mountIndeterminateComponent
/turbopack/[project]/node_modules/.pnpm/next@13.4.10_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (15735:13)
beginWork$1
/turbopack/[project]/node_modules/.pnpm/next@13.4.10_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (17310:16)
beginWork
/turbopack/[project]/node_modules/.pnpm/next@13.4.10_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (25689:14)
performUnitOfWork
/turbopack/[project]/node_modules/.pnpm/next@13.4.10_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (24540:12)
workLoopSync
/turbopack/[project]/node_modules/.pnpm/next@13.4.10_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (24256:5)
renderRootSync
/turbopack/[project]/node_modules/.pnpm/next@13.4.10_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (24211:7)
recoverFromConcurrentError
/turbopack/[project]/node_modules/.pnpm/next@13.4.10_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23446:20)
performConcurrentWorkOnRoot
/turbopack/[project]/node_modules/.pnpm/next@13.4.10_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23352:22)
workLoop
/turbopack/[project]/node_modules/.pnpm/next@13.4.10_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js (261:34)
flushWork
/turbopack/[project]/node_modules/.pnpm/next@13.4.10_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js (230:14)
MessagePort.performWorkUntilDeadline
/turbopack/[project]/node_modules/.pnpm/next@13.4.10_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js (537:21)

### Expected Behavior

Successfully render the chart.

### To Reproduce

Create a client component with:
```json
{
    "next": "^13.4.2",
    "recharts": "^2.7.2"
}
```
Start dev env with:
```bash
npx next dev --turbo
```

**Comment by m-radmacher** [comment]
I'm using next 13.4.10 and recharts 2.7.2 with the same result.

**Comment by michaelhays** [comment]
Same issue with [Tremor](https://github.com/tremorlabs/tremor) (which itself uses recharts).

**Comment by michaelhays** [comment]
This is not erroring for me anymore with Next.js 14.0.4-canary.28
