### ISSUE TITLE
[turborepo] dockerfile with Next.js looking for yarn instead of NPM

### ISSUE THREAD

**Issue by thedaviddias** [vercel/turbo#5549]
### What version of Turborepo are you using?

1.10.8

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

I have spent some time trying to move a nextjs project to a monorepo. My main problem lays with my Dockerfile.

I have looked into the [example provided by the documentation](https://turbo.build/repo/docs/handbook/deploying-with-docker) and this [created a basic example of a monorepo](https://github.com/thedaviddias/turbo-docker-npm-issue/blob/main/Dockerfile) to reproduce the issue.

For an unknown reason, the `next build` is looking for a `yarn.lock` file even I use NPM and have a `package-lock.json`.

This is the error message I'm getting 👇
```
#19 0.473 web:build: > next build
#19 0.473 web:build: 
#19 0.899 web:build: Attention: Next.js now collects completely anonymous telemetry regarding usage.
#19 0.899 web:build: This information is used to shape Next.js' roadmap and prioritize features.
#19 0.899 web:build: You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#19 0.900 web:build: https://nextjs.org/telemetry
#19 0.900 web:build: 
#19 0.952 web:build: - info Creating an optimized production build...
#19 6.635 web:build: - info Compiled successfully
#19 6.636 web:build: - info Linting and checking validity of types...
#19 6.700 web:build: It looks like you're trying to use TypeScript but do not have the required package(s) installed.
#19 6.700 web:build: Installing dependencies
#19 6.700 web:build: 
#19 6.700 web:build: If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).
#19 6.700 web:build: 
#19 6.849 web:build: - error ESLint must be installed in order to run during builds: yarn add --dev eslint
#19 11.87 web:build: 
#19 11.87 web:build: Installing devDependencies (yarn):
#19 11.87 web:build: - @types/react
#19 11.87 web:build: 
#19 11.97 web:build: yarn add v1.22.17
#19 11.99 web:build: info No lockfile found.
#19 12.00 web:build: warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```

I have tried:
- Different versions of turbo, same issue
- In my github repo example, it uses the latest version of Next, but my other project uses `12.13.1`

### Expected Behavior

I should be able to use `npm` and have all my packages installed properly.

### To Reproduce

At the root of my Apple M1, I have been running `docker build -t webapp-test . --no-cache --progress=plain` to test the build of my docker container.

### Reproduction Repo

https://github.com/thedaviddias/turbo-docker-npm-issue

**Comment by thedaviddias** [comment]
After so many trials and going through many issues, it seems, for a reason I still don't understand I have to add `npx` in front of `RUN npx turbo run build --filter=web...`

Which seems odd as `turbo` is installed globally with `npm install -g turbo`.

I then also faced another issue identical to #2683, which I was able to solve adding:
```
experimental: {
  outputFileTracingRoot: path.join(__dirname, "../../"),
},
```

If using Next.js in a version prior to 13.x.x, `'/app/apps/web/server.js` is not found.

**Comment by dragidavid** [comment]
would you mind sharing your dockerfile? It still can't find the `server.js` even after adding the snippet to next.config

**Comment by thedaviddias** [comment]
I am going to close this issue as I solved my problem but if anyone has an explanation on why I had to add `npx`, I'm curious.

**Comment by shariqh** [comment]
I just went through the same thing for three hours before discovering this... would like to understand the nuance as well
