### ISSUE TITLE
[turborepo] Failed to load plugin 'turbo' declared in 'apps/backend/.eslintrc.js » eslint-config-custom » eslint-config-turbo': Cannot find module 'eslint-plugin-turbo'

### ISSUE THREAD

**Issue by divyansh7924** [vercel/turbo#5571]
### What version of Turborepo are you using?

1.109

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

This works fine while trying to run pnpm run lint but fails in VS Code only
Creating a new monorepo with setting up nestjs popups the error in VSCode below:  
Error: Failed to load plugin 'turbo' declared in 'apps/backend/.eslintrc.js » eslint-config-custom » eslint-config-turbo':  
 Cannot find module 'eslint-plugin-turbo'. 
Require stack: 
- /Users/divyanshgupta/Projects/monorepo/apps/backend/__placeholder__.js
Referenced from: /Users/divyanshgupta/Projects/monorepo/node_modules/.pnpm/eslint-config-turbo@1.9.3_eslint@8.45.0/node_modules/eslint-config-turbo/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1010:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)

  
packages/eslint-config-custom/index.js
`module.exports = {
  extends: ["turbo"],
  "rules": {
    // Automatically flag env vars missing from turbo.json
    "turbo/no-undeclared-env-vars": "off"
  }
};
`
  
packages/eslint-config-custom/package.json
`{
  "name": "eslint-config-custom",
  "version": "0.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "eslint-config-prettier": "^8.3.0",
    "eslint-config-turbo": "^1.9.3"
  },
  "publishConfig": {
    "access": "public"
  }
}
`

./.eslintrc.js
`module.exports = {
  root: true,
  // This tells ESLint to load the config from the package `eslint-config-custom`
  extends: ["custom"],
  settings: {
    next: {
      rootDir: ["apps/*/"],
    },
  },
};
`

/apps/backend/.eslintrc.js
`module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: 'tsconfig.json',
    tsconfigRootDir: __dirname,
    sourceType: 'module',
  },
  plugins: ['@typescript-eslint/eslint-plugin'],
  root: true,
  extends: [
    'custom',
    'plugin:@typescript-eslint/recommended',
    'plugin:prettier/recommended',
  ],
  env: {
    node: true,
    jest: true,
  },
  ignorePatterns: ['.eslintrc.js'],
  rules: {
    '@typescript-eslint/interface-name-prefix': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/ban-ts-comment': 'off',
  },
};
`

### Expected Behavior

eslint should properly work in vscode 

### To Reproduce

setup a new turborepo with nestjs with above config

**Comment by chris-olszewski** [comment]
Hi @divyansh7924, can you provide a reproduction repository? Can you include what command VSCode is running that produces the error as well?

**Comment by divyansh7924** [comment]
<img width="1440" alt="Screenshot 2023-07-20 at 9 52 41 PM" src="https://github.com/vercel/turbo/assets/36097299/42d255ac-ce52-4029-9f3c-2c56e66c115b">


Hey @chris-olszewski 
It seems to be the official eslint extension on vscode that seems to be doing this. Attached the screenshot for reference.
The repository is private actually, let me create a sample repo tomorrow to help you reproduce the error if that helps.

**Comment by divyansh7924** [comment]
@chris-olszewski 
Here's the example repository 
https://github.com/divyansh7924/turbo-nest-monorepo-example

Node version: v18.14.0

**Comment by WinmezzZ** [comment]
Same problem here, any update?

**Comment by rmosias2** [comment]
Any ideas on how to get around this?

**Comment by chris-olszewski** [comment]
I'm still unable to reproduce this. If you encounter this please make sure you're using `2.4.2` of the ESLint extension and include any part of your `settings.json` that set any eslint settings. If possible a full log of the ESLint error with `"eslint.debug": true` in your `settings.json` would be extremely helpful.

**Comment by divyansh7924** [comment]
Hey @chris-olszewski 
I am using the latest version of eslint extension 2.4.2.

Here's the full log after turning on eslint.debug
https://gist.github.com/divyansh7924/9e96dc2aca62bd33f76ba47597bcb07e

**Comment by divyansh7924** [comment]
Hi @chris-olszewski 
Any ideas to resolve this, or any workaround possible
thanks!

**Comment by WinmezzZ** [comment]
> Hi @chris-olszewski Any ideas to resolve this, or any workaround possible thanks!

Install any needed plugins into root of project work for me, but it wa alittle stupid

**Comment by plrs9816** [comment]
I also have the same issue. Strangely, 'next lint' detects fine but only vscode behaves strange.

**Comment by noxify** [comment]
had the same problem.

Based on https://github.com/microsoft/vscode-eslint/issues/1373, I had to add the following to my `.npmrc`:

```
public-hoist-pattern[]=*eslint-plugin-*
public-hoist-pattern[]=@typescript-eslint/eslint-plugin
```

After running `pnpm i` and restarting the VSC eslint server, it seems the linting is working again.

**Comment by anthonyshew** [comment]
Check out [the examples directory(https://github.com/vercel/turbo/tree/main/examples) for examples of valid ESLint setups.

**Comment by yusufumac** [comment]
We encountered this issue and removing the `public-hoist-pattern[]=*prisma*` from the .npmrc has solved the issue

**Comment by kthorri** [comment]
I had the same issue, there was an invalid turbo.json file in one of my packages, fixing that fixed the load plugin error

**Comment by 0x80** [comment]
For me it also appears when I add turbo.json files to my workspace directories, with something like this:

```
{
  "extends": ["//"],
  "globalDependencies": [".env.dev", ".env.prd", "tsconfig.json"]
}
```

Adding this to some of my packages, also seems to make linting fail on other package that do not have a turbo file.

I solved it by declaring the global dependencies at the root with `**/` prefix

**Comment by stevemu** [comment]
I resolved the problem by upgrading "eslint-config-turbo" in package.json in "eslint-config" package to the newest version.

**Comment by strlrd-29** [comment]
@stevemu thank you, this happened to me after upgrading `turbo` package without the `eslint-config-turbo`.

**Comment by Harit007x** [comment]
@stevemu thanks a bunch , it worked for me

**Comment by bitttttten** [comment]
I also had to update `eslint-plugin-turbo`. I used the codegen, but we are using a monorepo and the codegen upgrade didn't catch the `eslint-plugin-turbo` inside our `packages/eslint-config`.
