### ISSUE TITLE
[turborepo] Possible bug in "Using environment variables" documentation

### ISSUE THREAD

**Issue by jkjustjoshing** [vercel/turbo#5586]
### What version of Turborepo are you using?

1.10.7

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

In [this section of the docs](https://turbo.build/repo/docs/handbook/environment-variables#with-workspace-scripts) it says that this is an acceptable way to include `.env` variables in a script:

```diff
{
  "scripts": {
+.   "dev": "dotenv -e ../../.env start-server"
  }
  "devDependencies": {
+    "dotenv-cli": "latest"
  },
}
```

However, what happens if you define a variable in that `.env` folder that you want Turborepo to depend on? Imagine this turbo.json pipeline entry:

```json
"build": {
    ...
    "env": ["DOMAIN"]
}
```
Imagine the `build` script runs an 11ty static build that includes the `DOMAIN` variable in the HTML output. With the above method of including `.env`, If I set `DOMAIN=example.com`, run `turbo run build`, then change that to `DOMAIN=stage.example.com` in `.env`, Turborepo will not see that changed environment variable the next time `turbo run build` runs, and it will use the cached previous run of that command.

I believe including that example in your documentation encourages a method of environment variable loading that is incompatible with Turborepo. 

### Expected Behavior

One of the following:
* Put a warning banner explaining what can go wrong with the documentation
* Provide a way for the `turbo` package to automatically load a `.env` file and use that to determine which cache to use

### To Reproduce

https://turbo.build/repo/docs/handbook/environment-variables#with-workspace-scripts

**Comment by nathanhammond** [comment]
> Last updated on April 4, 2023

Oops. We missed this page when we did our _massive_ environment variable overhaul in May.

This is the most-up-to-date documentation about how to use Environment Variables: https://turbo.build/repo/docs/core-concepts/caching/environment-variable-inputs

I'm going to rewrite this page, but in the mean time I'm hoping that our existing documentation can unblock you. You should indeed be adding the file to `dotEnv` or `globalDotEnv` (depending upon where you are in the repo structure).
