### ISSUE TITLE
[turborepo] 

### ISSUE THREAD

**Issue by Nightvision53** [vercel/turbo#5587]
### What version of Turborepo are you using?

1.10.9

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Other

### Describe the Bug

The command `pnpm dlx create-turbo@latest` has `"packageManager": "pnpm@7.15.0"` in its package json that has this [issue](https://github.com/pnpm/pnpm/issues/6424#issuecomment-1646205675) that pnpm is not able to fetch packages from npm registry.

### Expected Behavior

Pnpm installs packages without having problems.

### To Reproduce

Use [offical guide](https://turbo.build/repo/docs/getting-started/create-new) to create a repo with pnpm and use Node 20 with it

**Comment by domdomegg** [comment]
Also see: https://github.com/vercel/next.js/issues/52943
