### ISSUE TITLE
[turborepo]  create-turbo@latest uses an old version of pnpm which can fatal pnpm install

### ISSUE THREAD

**Issue by kyldvs** [vercel/turbo#5592]
### What version of Turborepo are you using?

create-turbo@latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Performing a fresh setup with `pnpm dlx create-turbo@latest` fails on my computer.

The error occurs when installing dependencies with `pnpm`:

```
Installing packages. This might take a couple of minutes.

>>> Installing dependencies...
>>> pnpm install --fix-lockfile has failed.
```

The `pnpm install --fix-lockfile` command fails like this:

```
pnpm install --fix-lockfile
Scope: all 6 workspace projects
 WARN  GET https://registry.npmjs.org/turbo error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@types/node/-/node-17.0.45.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@types/react/-/react-18.2.5.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.

...
```

The issue appears to be resolved in `pnpm`: https://github.com/pnpm/pnpm/issues/6424

However the `create-turbo` script seems to force `pnpm` to `7.15.0` in `package.json` by adding:

```
"packageManager": "pnpm@7.15.0",
```

When I manually update this to `"packageManager": "pnpm@8.3.1",` I can rerun `pnpm install --fix-lockfile` just fine.

### Expected Behavior

`pnpm dlx create-turbo@latest` completes in an empty repo (after selecting `pnpm`).

### To Reproduce

While using node v20 (specifically v20.3.1 for me)

`pnpm dlx create-turbo@latest`

**Comment by Nightvision53** [comment]
It's a duplicate issue from [#5587](https://github.com/vercel/turbo/issues/5587)

**Comment by kyldvs** [comment]
Should be fixed by https://github.com/vercel/turbo/pull/5609
