### ISSUE TITLE
[turborepo] prune error 'new-only'

### ISSUE THREAD

**Issue by nmackey** [vercel/turbo#5598]
### What version of Turborepo are you using?

1.10.10

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Error during turbo prune

`ERROR json error while pruning: unknown variant `new-only`, expected one of `full`, `none`, `hash`, `new`, `error` at line 7 column 30`

### Expected Behavior

Prune completes successfully as with previous versions of turbo

### To Reproduce

I'm assuming it is related to my use `"outputMode": "new-only"` as part of your build command in `turbo.json`

**Comment by tkstang** [comment]
Same issue here

**Comment by jazmon** [comment]
Same thing happening to us too, pinning the version to `1.9.3` is our workaround for now
