### ISSUE TITLE
[turborepo] prune error "/pnpm-workspace.yaml" not found

### ISSUE THREAD

**Issue by beefancohen** [vercel/turbo#5599]
### What version of Turborepo are you using?

1.10.10

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

`turbo prune --scope=tono-app --docker` fails with "/out/pnpm-workspace.yaml" not found.  This is running on github actions machines

### Expected Behavior

`pnpm-workspace.yaml` file is in the right location

### To Reproduce

```
FROM node:16-alpine AS provisioner
RUN apk add --no-cache libc6-compat
RUN apk update

# Intall turbo
RUN npm i -g turbo;

# Set working directory
WORKDIR /usr/src/app
COPY . .
RUN turbo prune --scope=tono-app --docker
 
# Add lockfile and package.json's of isolated subworkspace
FROM node:16-alpine AS builder
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /usr/src/app


# Install pnpm
RUN npm i -g pnpm;

# To skip scripts that should not run in CI environment
ENV GITHUB_ACTIONS=true
 
# First install the dependencies (as they change less often)
COPY .gitignore .gitignore
COPY .npmrc .npmrc
COPY --from=provisioner /usr/src/app/out/json/ .
COPY --from=provisioner /usr/src/app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml
```

**Comment by Brookke** [comment]
Had the same problem, applied a short term fix of locking the version to `1.10.9`

```
# Intall turbo
RUN npm i -g turbo@1.10.9
```

**Comment by valeriomarzulli** [comment]
same problem here!
pnpm-worskpace.yaml is no longer available in out/ folder.

It works on windows, but it fails on docker container using node:18-alpine
(as workaround i'm pointing to /out/json/pnpm-workspace.yaml)

**Comment by beefancohen** [comment]
thank you @chris-olszewski!  either way works, appreciate the fast follow up
