### ISSUE TITLE
[turborepo] command not found: raw

### ISSUE THREAD

**Issue by NickHackford** [vercel/turbo#5630]
### What version of Turborepo are you using?

1.9.9

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

When running the command `yarn turbo gen` it not longer runs as expected and instead gives me the following output

```
npx: installed 1 in 1.142s
command not found: raw
```

This command was working fine for me throughout the week and I only noticed this behavior late yesterday. I asked a coworker to verify and they experienced the same issue. This error still occurred when testing different against versions of turbo as well as reverting to earlier states of the repo.

### Expected Behavior

My plop config is found and ran

### To Reproduce

Cd into a project with turbo and run `yarn turbo gen`

**Comment by NickHackford** [comment]
Was doing lots of testing with different node versions and it started working again at some point. Now I can no longer get the error to happen.

**Comment by gimdongwon** [comment]
I met this error. plz help me from this error
![스크린샷 2024-01-19 16 33 24](https://github.com/vercel/turbo/assets/37524650/762c4843-513f-4e85-9c4a-c5a0caf3e7a9)
