### ISSUE TITLE
[turborepo] Remote cache not triggered using ENV vars

### ISSUE THREAD

**Issue by dcantu96** [vercel/turbo#5631]
### What version of Turborepo are you using?

1.10.12

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac Intel

### Describe the Bug

I think the `turbo run` command is not detecting the `.env` keys and not running remote cache.
<img width="424" alt="Screenshot 2023-07-28 at 12 40 36" src="https://github.com/vercel/turbo/assets/32658690/c8e2e1b4-a42b-4a7a-affc-8187de5d3ec7">
<img width="522" alt="Screenshot 2023-07-28 at 12 40 00" src="https://github.com/vercel/turbo/assets/32658690/d8c5d4e7-eb8a-4af5-8511-74296469f61a">

**Update**: It seems like env vars are not being detected on my Mac Intel based, but they are in my Mac M1. I also tested in windows and it doesn't detect the env on windows

If I type the values in the script it does work
<img width="551" alt="Screenshot 2023-07-28 at 12 41 28" src="https://github.com/vercel/turbo/assets/32658690/e1e158c6-dbcb-4339-9843-d9add8a72ea3">

### Expected Behavior

I expect the `TURBO_TOKEN` `TURBO_TEAM` and `TURBO_API` env variables to be detected and run with remote cache enabled

### To Reproduce

1. In any monorepo create an env file and add your keys for `TURBO_TOKEN` `TURBO_TEAM` and `TURBO_API`
2. add a `turbo run build` in your root package.json
3. remote cache should be disabled

**Comment by dcantu96** [comment]
It seems like env vars are not being detected on my Mac Intel based, but they are in my Mac M1. I also tested in windows and it doesn't detect the env on windows

**Comment by NicholasLYang** [comment]
Hi @dcantu96, thanks for the issue. Just to clarify, what are you using to load the `.env` file before running `turbo`?

**Comment by dcantu96** [comment]
Hi @NicholasLYang I'm not using anything to load the `.env` why? Should I be using something like **dotenv** ?

**Comment by dcantu96** [comment]
I tried using dotenv on windows and it worked 😅 I feel dumb for not trying that. I think that's should also fix my Intel based mac... it would be nice for it to work on any environment but I would understand if it's out of your reach.

**Comment by dcantu96** [comment]
So, using dotenv works 100% of the time, not using dotenv gives very inconsistent results, sometimes it works sometimes, it doesnt. I tested using M1, M2, and Intel based Macs

**Comment by arlyon** [comment]
Some people (myself included) use shell plugins (https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/dotenv) to have the terminal session automatically load the .env file, rather than have the program do it. Typically it happens when navigating into a folder with a .env. Could this be why it 'works' on some machines but not others?

**Comment by dcantu96** [comment]
Got it, I do have that plug-in on my m2 terminal, that's why it worked. I think it would be nice to automatically support this like nextjs.

**Comment by NicholasLYang** [comment]
We're actively exploring automatic `.env` loading as an option! For now I'm going to close this issue since the problem seems to be resolved.
