### ISSUE TITLE
[turborepo] `@turbo/codemod update` throws error when `turbo` is not installed globally

### ISSUE THREAD

**Issue by steveluscher** [vercel/turbo#5642]
### What version of Turborepo are you using?

1.10.12

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

One of the recommended options for installing Turborepo when you work with other developers is to pin it to a version, [per repository](https://turbo.build/repo/docs/installing#install-per-repository).

If you do this and you do _not_ install it globally, then `pnpx @turbo/codemod update` throws the following error:

```shell
/bin/sh: 1: turbo: not found
```

### Expected Behavior

It should use the workspace version of `turbo`.

### To Reproduce

1. Don't install `turbo` globally
2. `pnpm add turbo --save-dev --ignore-workspace-root-check`
3. `pnpx @turbo/codemod update`

**Comment by NicholasLYang** [comment]
Hi @steveluscher. Thanks for the issue. I'm not able to reproduce this. What version of pnpm are you using? And can you provide all of the output from `@turbo/codemod update`?

**Comment by steveluscher** [comment]
Oh, weird.

pnpm 8.6.10

```shell
~/src/solana-web3.js$ pnpx @turbo/codemod update
.../share/pnpm/store/v3/tmp/dlx-455403   |  WARN  deprecated cross-spawn-async@2.2.5
.../share/pnpm/store/v3/tmp/dlx-455403   | +121 ++++++++++++
.../share/pnpm/store/v3/tmp/dlx-455403   | Progress: resolved 121, reused 121, downloaded 0, added 121, done
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
? Where is the root of the repo to migrate? .
/bin/sh: 1: turbo: not found
Migration completed
Nothing to do, current version (1.10.12) is the same as the requested version (1.10.12)
```

**Comment by tknickman** [comment]
Released
