### ISSUE TITLE
[turborepo] Unable to find Go binary - `go-turbo-bin` is missing

### ISSUE THREAD

**Issue by saraC15** [vercel/turbo#5650]
### What version of Turborepo are you using?

1.10.12

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Upgrading from 1.10.7 to 1.10.12 running `git clean -Xdfq && npm i && turbo run compile --cache-dir=.turbo -- --force` I get the following error:

```
> compile
> turbo run compile --cache-dir=.turbo --force

ERROR Unable to find Go binary. Please report this issue at https://github.com/vercel/turbo/issues and include your package manager and version along with the following information:
        os=macos
        arch=x86_64
        turbo-version=1.10.12
        turbo-bin=<path to my project>/node_modules/turbo/bin/downloaded-turbo-darwin-64-turbo
        go-turbo-bin=<path to my project>/node_modules/turbo/bin/go-turbo
```

I checked the files referenced for `turbo-bin` and `go-turbo-bin`. The former is a huge binary file, later (`go-turbo-bin`) does not exist.

I use npm v9.8.1. Removing `node_modules` does not help.

### Expected Behavior

The `go-turbo-bin` file should be there. It should be possible to compile the project.

### To Reproduce

See bug description.

**Comment by cassiecascade** [comment]
I'm running into this in GitHub actions as well. It runs fine locally on my project.

turbo: `v1.10.12`
node: `v20.5.0`
npm: `9.8.0`

```stdout
npm run lint:check
  shell: /usr/bin/bash -e {0}
  

> lint:check
> turbo lint:check

ERROR Unable to find Go binary. Please report this issue at https://github.com/vercel/turbo/issues and include your package manager and version along with the following information:
        os=linux
        arch=x86_64
        turbo-version=1.10.12
        turbo-bin=/home/runner/work/monorepo/monorepo/node_modules/turbo/bin/downloaded-turbo-linux-64-turbo
        go-turbo-bin=/home/runner/work/monorepo/monorepo/node_modules/turbo/bin/go-turbo
        
Error: Failed to execute turbo (Unable to locate Go binary).
Error: Process completed with exit code 1.
```

**Comment by cassiecascade** [comment]
@saraC15 I downgraded and version locked to `1.10.11` and it's going through now, as a temporary fix.

**Comment by NicholasLYang** [comment]
Hi @saraC15, @cassiecascade, thanks for the issue. When you run `npm install`, do you see the following message?

> [turbo] Failed to find package "turbo-darwin-arm64" on the file system

> This can happen if you use the "--no-optional" flag. The "optionalDependencies"
package.json feature is used by turbo to install the correct binary executable
for your current platform. This install script will now attempt to work around
this. If that fails, you need to remove the "--no-optional" flag to use turbo.

It appears that for some reason `npm` is not installing the correct package, so our install script is falling back to manually downloading the package. This should work, but it is less reliable than having `npm` install the package.

**Comment by cassiecascade** [comment]
I went back through the failed action runs and tried this again locally and that message didn't appear in either (or one like it for linux). It seems to happen only on `1.10.12` still and only when using it in the docker build pipeline we have setup; using `node:20-alpine`. We also don't use the `--no-optional` flag. I -can- run everything fine on my Mac, but when I try to build the container either locally or on a remote host (GitHub or fly) it fails.

I don't know if any of that is helpful in debugging, if this is even something that's fixable (it may be a transient issue?) but I hope it is! Optional dependencies for architecture is awesome but I have experience with it being finicky at times so I understand. Thanks for responding~

**Comment by saraC15** [comment]
Thanks Cassidy! 1.10.11 works for me as well :)

Hi Nicholas, I don't get that error message. (If it's to any help - I have gotten it for a previous version but it was fixed by fixing my `package-lock.json`. Was not using the no-optional flag).

For me it fails on my local machine, but succeeds in the pipeline running Ubuntu and node 16, npm 8.19.4.

Let me know if there is anything else you need :)

**Comment by samtgarson** [comment]
FWIW (not sure if further instances are helpful) I received this issue on Vercel after upgrading from 1.10.11 to 1.10.12 and it goes away after locking back at 1.10.11.

```
ERROR Unable to find Go binary. Please report this issue at https://github.com/vercel/turbo/issues and include your package manager and version along with the following information:
--
os=linux
arch=x86_64
turbo-version=1.10.12
turbo-bin=/vercel/path0/node_modules/turbo/bin/downloaded-turbo-linux-64-turbo
go-turbo-bin=/vercel/path0/node_modules/turbo/bin/go-turbo
 
Error: Failed to execute turbo (Unable to locate Go binary).
Error: Command "NODE_ENV=production turbo run build" exited with 1
```

Did not seem to get this error locally (macbook pro) oddly.

**Comment by chris-olszewski** [comment]
If anyone encountering this issue could include their `package-lock.json` that could be helpful.

**Comment by chris-olszewski** [comment]
For anyone encountering this issue it most likely stems from a bad `package-lock.json` that is missing the `optionalDependencies`. 

To properly generate a new lockfile:
 - `rm -rf node_modules && rm package-lock.json`
 - bump the version of turbo in `package.json`
 - `npm install`

If the new `package-lock.json` is generated with an existing `node_modules` then `npm` will create a lockfile that only contains the `optionalDependencies` that are present in `node_modules`. This means that if you create a lockfile on a Mac and then try to use it on a Linux machine the Linux package won't be present and won't get installed.

**Comment by wrs** [comment]
FYI, I just got this error on a completely fresh `create-turbo` dir.

```
$ pnpm dlx create-turbo@latest
../Library/pnpm/store/v3/tmp/dlx-78065   | +116 ++++++++++++
../Library/pnpm/store/v3/tmp/dlx-78065   | Progress: resolved 116, reused 0, downloaded 116, added 116, done

>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.

? Where would you like to create your turborepo? mono
? Which package manager do you want to use? pnpm

Downloading files. This might take a moment.

>>> Created a new Turborepo with the following:

apps
 - apps/docs
 - apps/web
packages
 - packages/eslint-config-custom
 - packages/tsconfig
 - packages/ui

Installing packages. This might take a couple of minutes.

>>> Success! Created a new Turborepo at "mono".
Inside that directory, you can run several commands:

  pnpm run build
     Build all apps and packages

  pnpm run dev
     Develop all apps and packages

  pnpm run lint
     Lint all apps and packages

Turborepo will cache locally by default. For an additional
speed boost, enable Remote Caching with Vercel by
entering the following command:

  pnpm dlx turbo login

We suggest that you begin by typing:

  cd mono
  pnpm dlx turbo login

$ cd mono
$ pnpm run build

> mono@ build /Users/waltersmith/src/mono
> turbo run build

ERROR Unable to find Go binary. Please report this issue at https://github.com/vercel/turbo/issues and include your package manager and version along with the following information:
        os=macos
        arch=aarch64
        turbo-version=1.10.12
        turbo-bin=/Users/waltersmith/src/mono/node_modules/.pnpm/turbo@1.10.12/node_modules/turbo/bin/downloaded-turbo-darwin-arm64-turbo
        go-turbo-bin=/Users/waltersmith/src/mono/node_modules/.pnpm/turbo@1.10.12/node_modules/turbo/bin/go-turbo

Error: Failed to execute turbo (Unable to locate Go binary).
 ELIFECYCLE  Command failed with exit code 1.
$ ls /Users/waltersmith/src/mono/node_modules/.pnpm/turbo@1.10.12/node_modules/turbo/bin/
downloaded-turbo-darwin-arm64-turbo* npm-install/                         turbo*

**Comment by wrs** [comment]
```
$ pnpm exec turbo --verbosity 9 run build
2023-08-08T19:13:33.006-0700 [DEBUG] turborepo_lib::shim: Global turbo version: 1.10.12
2023-08-08T19:13:33.007-0700 [DEBUG] turborepo_lib::shim: No local turbo binary found at: /Users/waltersmith/src/mono/node_modules/turbo-darwin-arm64/bin/turbo
2023-08-08T19:13:33.007-0700 [DEBUG] turborepo_lib::shim: No local turbo binary found at: /Users/waltersmith/src/mono/node_modules/turbo/node_modules/turbo-darwin-arm64/bin/turbo
2023-08-08T19:13:33.007-0700 [DEBUG] turborepo_lib::shim: No local turbo binary found at: /Users/waltersmith/src/mono/node_modules/.pnpm/turbo@1.10.12/node_modules/turbo-darwin-arm64/bin/turbo
...
$ ls node_modules/turbo-darwin-arm64/bin
ls: node_modules/turbo-darwin-arm64/bin: No such file or directory
$ ls node_modules/turbo/node_modules/turbo-darwin-arm64/bin
ls: node_modules/turbo/node_modules/turbo-darwin-arm64/bin: No such file or directory
$ ls node_modules/.pnpm/turbo@1.10.12/node_modules/turbo-darwin-arm64/bin
$
```

I tried going back to 1.10.1 and upgrading one minor version at a time. It started acting weird around 1.10.5. I get an install error, then if I `pnpm prune` and try again, it succeeds. It wasn't always able to actually run `turbo`, getting the "unable to locate Go binary" error again, but for no apparent reason it then started working all the way up to 1.10.10.

```
$ pnpm install -w turbo@1.10.5
Packages: +2 -2
++--
Progress: resolved 448, reused 435, downloaded 0, added 0, done
node_modules/.pnpm/turbo@1.10.5/node_modules/turbo: Running postinstall script, failed in 568ms
.../turbo@1.10.5/node_modules/turbo postinstall$ node install.js
│ [turbo] Failed to find package "turbo-darwin-arm64" on the file system
│ This can happen if you use the "--no-optional" flag. The "optionalDependencies"
│ package.json feature is used by turbo to install the correct binary executable
│ for your current platform. This install script will now attempt to work around
│ this. If that fails, you need to remove the "--no-optional" flag to use turbo.
│ [turbo] Trying to install package "turbo-darwin-arm64" using npm
│ [turbo] Failed to install package "turbo-darwin-arm64" using npm: EEXIST: file already exists, mkdir '/Users/waltersmith/src/mono/node_mo…
│ [turbo] Trying to download "https://registry.npmjs.org/turbo-darwin-arm64/-/turbo-darwin-arm64-1.10.5.tgz"
│ [turbo] Failed to download "https://registry.npmjs.org/turbo-darwin-arm64/-/turbo-darwin-arm64-1.10.5.tgz": Could not find "package/bin/t…
│ /Users/waltersmith/src/mono/node_modules/.pnpm/turbo@1.10.5/node_modules/turbo/install.js:302
│         throw new Error(`Failed to install package "${pkg}"`);
│               ^
│ Error: Failed to install package "turbo-darwin-arm64"
│     at checkAndPreparePackage (/Users/waltersmith/src/mono/node_modules/.pnpm/turbo@1.10.5/node_modules/turbo/install.js:302:15)
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
│ Node.js v20.3.1
└─ Failed in 568ms at /Users/waltersmith/src/mono/node_modules/.pnpm/turbo@1.10.5/node_modules/turbo
 ELIFECYCLE  Command failed with exit code 1.
~/s/mono (main|✚2) [1]$ pnpm prune
Lockfile is up to date, resolution step is skipped
Already up to date

devDependencies:
+ turbo 1.10.4
~/s/mono (main|✚2) $ pnpm install -w turbo@1.10.5
Packages: +2 -2
++--
Progress: resolved 448, reused 435, downloaded 0, added 2, done
node_modules/.pnpm/turbo@1.10.5/node_modules/turbo: Running postinstall script, done in 185ms

devDependencies:
- turbo 1.10.4
+ turbo 1.10.5 (1.10.12 is available)

Done in 1.9s
~/s/mono (main|✚2) $ pnpm exec turbo run build
[works]
```

I got this interesting message when I tried to go back to 1.10.12:

```
$ pnpm exec turbo run build
/Users/waltersmith/src/mono/node_modules/.pnpm/turbo@1.10.12/node_modules/turbo/bin/turbo:13
    throw e;
    ^

Error:
You installed turbo for another platform than the one you're currently using.
This won't work because turbo is written with native code and needs to
install a platform-specific binary executable.

Specifically the "turbo-darwin-arm64" package is present but this platform
needs the "turbo-darwin-arm64" package instead. ...
```

**Comment by nathanhammond** [comment]
@wrs the issue you're reporting is a different issue, related to an arm/x86 thing. Can you open a new issue?

**Comment by wrs** [comment]
Sure thing! I opened #5692 and deleted my comments above.
