### ISSUE TITLE
[turborepo] Cannot find module 'ui' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by ThugDenGamer** [vercel/turbo#5651]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Windows

### Describe the Bug

The title and this images explain my problem. I created a turborepo project from [there](https://github.com/vercel/turbo/tree/main/examples/with-react-native-web) and I just ran the web section. I didn't change anything and got this error. After that I tried to restart my Typescript server, change my Typescript version to my workspace's typescript version, edit my tsconfig and not resolved.
I checked my global yarn version (3.6.1) and my workspace's yarn version (1.22.19). I thought this version incompatibility might have caused this. I fix the version from package.json and used yarn install but nothing changed.
![image](https://github.com/vercel/turbo/assets/58256550/68c8df6b-83d0-45e0-9620-c5d7d2f12069)
![image](https://github.com/vercel/turbo/assets/58256550/56bdfe05-3a09-4483-ace5-0b0360956a31)
![image](https://github.com/vercel/turbo/assets/58256550/8c9952fa-d58c-4bde-8b38-750770cc8eb5)

### Expected Behavior

I expected the seamless workspace with `npx create-turbo -e with-react-native-web`.

### To Reproduce

Create a monorepo with `npx create-turbo -e with-react-native-web`

**Comment by NicholasLYang** [comment]
Hi @ThugDenGamer, thanks for the issue. If you haven't tried already, I'd build the `ui` package and see if it resolves the issue. The `ui/package.json` has the following line:

```
"types": "./dist/index.d.ts",
```

This is what the TypeScript compiler uses to find your type definitions. However, if `ui` is not built, the `dist` folder will not exist, and therefore TypeScript will not be able to resolve the package. This is why `ui#build` is a dependency of `web#build` in the Turborepo task graph.

**Comment by mervinyan** [comment]
I encountered the same problem even the ui is built. I noticed that the `index.d.mts` file in the `dist` folder so I updated the `types` line to following:
`"types": "./dist/index.d.mts"`
then the problem is gone

**Comment by magnusriga** [comment]
I got this same problem, now that the shared ui package no longer is built. How do we tell typescript that the apps have the dependencies installed, so TypeScript does not throw an error when importing next/image etc inside a package/ui component?

**Comment by dileepbc3141** [comment]
added build dependecy of in turbo.json solved this type error

 ```
"lint": {
      "dependsOn": ["^lint"]
    },
```

**Comment by oussama-sb3** [comment]
I got this same problem, added  "types": "./index.ts" to the package.json and in my case handled hoisting in my .npmrc file cause im working with pnpm and the problem got solved.
