### ISSUE TITLE
[turborepo] getting eror while installing 

### ISSUE THREAD

**Issue by srikanth-rakuten** [vercel/turbo#5656]
### What version of Turborepo are you using?

1.10

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

>>> Unexpected error. Please report it as a bug:
Bv [Error]: self-signed certificate in certificate chain

### Expected Behavior

it should install right

### To Reproduce

<img width="541" alt="Screenshot 2023-08-02 at 3 00 11 PM" src="https://github.com/vercel/turbo/assets/111979111/ab6899b9-ee50-47d9-bc23-811008fdaf1b">

**Comment by NicholasLYang** [comment]
Hi @srikanth-rakuten, thanks for the issue. This appears to be an issue with certificate signing in yarn. [This issue](https://github.com/yarnpkg/yarn/issues/980) might provide some potential solutions.

**Comment by srikanth-rakuten** [comment]
No i tried both npm set strict-ssl false  and yarn config set strict-ssl false --global but non worked

**Comment by NicholasLYang** [comment]
Hmm. I'm not able to reproduce this. This does appear to be an issue with your package manager, and not turborepo specifically. Have you tried re-installing the package manager? What version are you using?

**Comment by mehulkar** [comment]
Hey @srikanth-rakuten this is almost guaranteed not an issue with turborepo as we simply run `npm install` (or `yarn`) to install packages. You can get around this by passing a flag to skip the installation `npx create-turbo --skip-install` and then installing packages yourself with your own toolchain. My guess is that you aren't able to install packages from npm's registry even outside turborepo. 

Feel free to jump into our [Discord](https://turbo.build/discord) `#help` channel if you still need help and someone might be able to help you, but as of now this does not look like a Turborepo issue.
