### ISSUE TITLE
[turbopack] could not unmarshal lockfile: : yaml: unmarshal errors:

### ISSUE THREAD

**Issue by vaynevayne** [vercel/turbo#5701]
### What version of Next.js are you using Turbopack in?

13.4.12

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

deploy to vercel 
  https://vercel.com/vaynevayne/get-ui-docs/3L7LRVZPrqAyvcHxa6owjuachFW4

### Expected Behavior

no error no warning

### To Reproduce

https://github.com/vaynevayne/get-ui/tree/main/docs

in readme.md, click quick deploy

### Reproduction Repo

https://github.com/vaynevayne/get-ui/tree/main/docs

**Comment by padmaia** [comment]
@vaynevayne Turbopack is not supported for production builds in Next.js yet, so this seems to be labeled wrong. Did you mean to file an issue for Turborepo?

**Comment by nathanhammond** [comment]
Hello @vaynevayne! The issue that you're encountering is because the project you're working in is using an old version of Turborepo: 1.6.3. If you were to update that to `latest` (1.10.14) it will work just fine.

Thank you for the report!
