### ISSUE TITLE
[turborepo] passing arguments to running tasks leads to redundant warnings (yarn)

### ISSUE THREAD

**Issue by voronin-ivan** [vercel/turbo#5702]
### What version of Turborepo are you using?

1.10.12

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When using `turbo run` arguments for tasks are passed with redundant `--` which leads to the warning `scripts don't require "--" for options to be forwarded` -> bloated logs -> increased cache size.

The issue is reproducible only with yarn, npm and pnpm work as expected without this warning.

### Expected Behavior

Don't pass redundant `--` for running tasks to avoid useless warning.

### To Reproduce

To reproduce you can use the [official yarn example](https://github.com/vercel/turbo/tree/main/examples/with-yarn). Change lint script in package.json to `"lint": "turbo lint -- --quiet"` to pass an argument and run `yarn lint`. As a result, you'll see the following warning in logs and cache:
```
ui:lint: warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
```

**Comment by gsoltis** [comment]
I was able to confirm. I'll see if I can get that updated.
