### ISSUE TITLE
[turborepo] Imported components from "@headlessui/react" are undefined

### ISSUE THREAD

**Issue by ihor-romanchuk** [vercel/turbo#5744]
### What version of Turborepo are you using?

1.10.12

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

Components imported from "@headlessui/react" are `undefined`.

### Expected Behavior

The component should be imported without problems

### To Reproduce

I've created an app using this template `npx create-turbo -e with-create-react-app`.
I've installed `"@headlessui/react": "^1.7.16"` in /packages/ui fodler.
I've used a component from "@headlessui/react" library in on of the components:
```
import { Menu } from "@headlessui/react";

console.log("Menu", Menu);

export const Link = () => {
  return (
    <Menu>
        <Menu.Button>Button</Menu.Button>
      </Menu>
  );
};
```

When I use `Link` component in the React app, I get the following error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'Button')
    at Link (Link.tsx:23:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
``` 

Console.log outputs: "Menu undefined"

P.S. something similar was mentioned there: https://stackoverflow.com/questions/73153159/components-importing-headlessui-throwing-errors-when-built-and-then-used-in-anot 

### Reproduction Repo

https://github.com/ihor-romanchuk/turbo-create-react-app-headless-ui-undefined

**Comment by tknickman** [comment]
Hey @ihor-romanchuk, thanks for the report! While this isn't an issue Turborepo exactly, it's a weird side effect of 1. workspaces, and 2. how headless-ui is bundled. You can fix this with the following setup:

1. Install `@headlessui/react` in the web, _not_ the package.
2. List `@headlessui/react` as a peerDependency of the `ui` package (and/or a devDep to ensure it's installed for local dev).
3. Mark it as external in the [build](https://github.com/ihor-romanchuk/turbo-create-react-app-headless-ui-undefined/blob/main/packages/ui/package.json#L10)
	4. 	`"build": "tsup src/index.tsx --format cjs --dts --external react, @headlessui/react",`

This should now work when importing your Menu component from your local `ui` package into an app.
