### ISSUE TITLE
[turborepo] UI package is using older react version

### ISSUE THREAD

**Issue by anmol242** [vercel/turbo#5756]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

When installing turbo with latest code it is adding ` "react": "^17.0.2",` as a dependency in `ui` package while `web` and `docs` are using ` "react": "^18.2.0",`. So, I had to manually change the react version in `ui` package.

### Expected Behavior

`UI` package should use same version similar to docs and web aps

### To Reproduce

Run `npx create-turbo@latest` in your local and you will see ui package is using `"react": "^17.0.2",`

**Comment by tknickman** [comment]
Fixed in https://github.com/vercel/turbo/pull/5757. Thanks @anmol242!
