### ISSUE TITLE
[turborepo] Issues Peer dependencies in packages/ui

### ISSUE THREAD

**Issue by bhaveek424** [vercel/turbo#5758]
### What version of Turborepo are you using?

1.9.7

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Issues with peer dependencies found
**packages/ui
└─┬ react-dom 18.2.0
  └── ✕ unmet peer react@^18.2.0: found 17.0.2**

This causes problem to work with latest UI libraries **MUI** in the ui folder. 
![Screenshot from 2023-08-19 20-32-13](https://github.com/vercel/turbo/assets/61945842/e698c367-05a5-4354-952f-e532870d8931)

### Expected Behavior

The react should be updated to latest version.

### To Reproduce

In the ui folder, install MUI or any other UI library:
```
pnpm add @mui/material @emotion/react @emotion/styled
```

**Comment by anmol242** [comment]
Hey @bhaveek424 I believe this is the same issue which was mentioned by me few hours ago:
https://github.com/vercel/turbo/issues/5756

**Comment by bhaveek424** [comment]
Hey @anmol242, I see. Earlier your issue didn't had any title so I must have missed it. But yeah I'll close this issue now.
