### ISSUE TITLE
[turborepo] Error installing Material-UI due to React version conflict in 'basic' boilerplate

### ISSUE THREAD

**Issue by lalwanijatin** [vercel/turbo#5761]
### What version of Turborepo are you using?

1.10.12

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

When attempting to install the Material-UI package (@mui/material) in the 'basic' boilerplate, users may encounter a dependency conflict related to React versions. The error message indicates that there is a conflict between the React version specified in the UI package and the React version used by other modules in the monorepo.

### Expected Behavior

I expected to be able to install the Material-UI package without encountering any dependency conflicts.

### To Reproduce

1. Clone the 'basic' boilerplate locally.
2. Navigate to the UI package directory.
3. Run the following command to attempt to install Material-UI: **npm install @mui/material**
4. Observe the error related to the React version conflict.

**Comment by anmol242** [comment]
This is a duplicate issue raised already 2 days ago:
https://github.com/vercel/turbo/issues/5756

**Comment by tknickman** [comment]
Fixed in https://github.com/vercel/turbo/pull/5757, thanks!
