### ISSUE TITLE
[turborepo] Prune is no longer copying package.json to `full` directory

### ISSUE THREAD

**Issue by Xiot** [vercel/turbo#5768]
### What version of Turborepo are you using?

1.10.10

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

Running `turbo prune --scope=X --docker` properly pairs down the list of packages, however the root `package.json` doesn't seem to be copied into the `full` folder.

This causes `yarn` to think that there are 0 packages and it generates an empty lock file.

According to the docs, there should be a `package.json` in the `full` directory.  
https://turbo.build/repo/docs/reference/command-line-reference/prune#--docker

### Expected Behavior

Copy the `package.json` into the `full` directory as well as the `json` directory

### To Reproduce

```
turbo prune --scope=motion-dashboard --docker --out-dir ~/tmp/prune-test
```

`root` directory
![CleanShot 2023-08-21 at 13 39 20](https://github.com/vercel/turbo/assets/1887318/0dbf64a1-7998-4149-ba71-82d7c9537b2f)

`json` directory
![CleanShot 2023-08-21 at 13 40 01](https://github.com/vercel/turbo/assets/1887318/45a9210a-23ff-43bb-a841-0effd10f82db)

`full` directory
![CleanShot 2023-08-21 at 13 38 31](https://github.com/vercel/turbo/assets/1887318/05e4998e-ae4e-42fd-8bdd-3ecce24a900f)

#### With 1.10.9

`root` directory
![CleanShot 2023-08-21 at 13 42 55](https://github.com/vercel/turbo/assets/1887318/38bfc901-d7ea-4aa1-8fa8-f81220b57ab5)

`json` directory
![CleanShot 2023-08-21 at 13 43 16](https://github.com/vercel/turbo/assets/1887318/614d404d-ea7c-4d52-afb7-23c08a3828f3)

`full` directory
![CleanShot 2023-08-21 at 13 43 37](https://github.com/vercel/turbo/assets/1887318/1cffc264-607d-4950-b047-39feaecc56ff)

**Comment by Xiot** [comment]
Nice.

Currently I also need to copy over the `.yarnrc` file as well in order for the `yarn install` to work properly with the options that I have set up.

It looks like `.npmrc` is copied, but not the `.yarnrc`
https://github.com/vercel/turbo/pull/5531/files#diff-e61927c5381f3d8584b69c7437092722217c73789ef148ec0495faefbe59358aR49

I also just noticed that in either versions the `.yarn/releases` or `.yarn/plugins` were copied over either.

**Comment by chris-olszewski** [comment]
I'd be open to look into if we could copy over `.yarnrc` without making it a breaking change, but I'm pretty hesitant to start copying over more parts of `.yarn`. 

I don't *think* that there's platform dependent code in `.yarn/releases` or `.yarn/plugins`, but if there is then just copying it as part of prune could lead to undesired behavior in the Docker container. I think having `RUN yarn set version` and `RUN yarn plugin import` in the `Dockerfile` would probably be less error-prone.

**Comment by Xiot** [comment]
That sounds good. And I'll look at explicitly calling `set version` and `plugin import` in my scripts. 

I just need the `.yarnrc` for the linker config. 

I'm fine copying the files over manually for my setup though. 
Just wanted to raise it here since it was sort of related to my original issue.
