### ISSUE TITLE
[turborepo] Document behavior for how a failing task interacts with the cache

### ISSUE THREAD

**Issue by closesimple-wl** [vercel/turbo#5780]
### What version of Turborepo are you using?

1.10.12

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

The documentation needs to spell out how a failing task is not cached.  Not to mention, there's no API to force caching a failed result.

This might be implied, but it's definitely not clear nor explicit, and we shouldn't have to do mental gymnastics to figure out the reasoning behind the software's behavior.

### Expected Behavior

A clear explanation in the docs.  Only a few sentences is needed, really.

### To Reproduce

Run a task whose `scripts` definition is `exit 1`.

**Comment by tknickman** [comment]
Closed via https://github.com/vercel/turbo/pull/5782

**Comment by closesimple-wl** [comment]
That's better, but it still doesn't explain the reasoning.
