### ISSUE TITLE
[turborepo] outdated eslint doc (eslint-config-custom package)

### ISSUE THREAD

**Issue by boompikachu** [vercel/turbo#5797]
### What version of Turborepo are you using?

1.10.13

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

The documentation in https://turbo.build/repo/docs/handbook/linting/eslint is outdated. In the newly created monorepo, there are no longer an `index.js` file in `packages/eslint-config-custom` but a `library.js`, `next.js`, and `react-internal.js` instead. The website doesn't mentioned anything about these files.

Also, the extended eslint are different; old = `"custom"` new = `"custom/next"` which is different from this section: https://turbo.build/repo/docs/getting-started/create-new#understanding-eslint-config-custom

### Expected Behavior

The doc should reflect the monorepo config

### To Reproduce

<img width="874" alt="image" src="https://github.com/vercel/turbo/assets/37561295/879f89f0-dbf2-4411-9e6c-6f305a08edf0">
<img width="285" alt="image" src="https://github.com/vercel/turbo/assets/37561295/cc3e79ed-5225-4393-8c3f-9058aed56930">

====================

<img width="715" alt="image" src="https://github.com/vercel/turbo/assets/37561295/1bac4f92-47dd-4914-94ec-4370a39b32c7">
<img width="182" alt="image" src="https://github.com/vercel/turbo/assets/37561295/b43ac5b7-f52e-4c1e-8169-9cbf698ea32d">

**Comment by tknickman** [comment]
Thanks @boompikachu, we're in the middle of re-working these to be more consistent / correct. The code is landing first and the docs will follow shortly!

**Comment by boompikachu** [comment]
> Thanks @boompikachu, we're in the middle of re-working these to be more consistent / correct. The code is landing first and the docs will follow shortly!

Thank you for an amazing monorepo

By the way, when changing from using `index.ts` (1.10.12) to `next.js` (1.10.13) file, will old users know the changes? I'm curious since if I were to init my turborepo now, will I miss out on some of the new features in the future?

**Comment by TatianaRG** [comment]
Hi, is there any updated docs/ examples how to use the newly created files ( next.is, library.js etc..) Thanks

**Comment by matrixersp** [comment]
what are the use cases of library.js?
