### ISSUE TITLE
[turborepo] Turborepo starter - eslint error when using process

### ISSUE THREAD

**Issue by JohnGemstone** [vercel/turbo#5802]
### What version of Turborepo are you using?

1.10.13

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Linting error when building with a process.env definition:
`Error: 'process' is not defined.  no-undef`

My first time using Turborepo, pretty sure I could edit the ESlint config myself, but assume this isn't intentional or I'm missing something?

Looking at the docs it seems like `process.env` is the correct way to use environment variables:
https://turbo.build/pack/docs/features/environment-variables#processenv

### Expected Behavior

No linting error

### To Reproduce

1. Run `npx create-turbo@latest`
2. Inside the `web` folder create `.env.local` variables
3. Add env variable to`turbo.json` build pipeline
4. Inject into `page.tsx` to test:
```js
import { Button, Header } from "ui";

const foo = process.env.NEXT_PUBLIC_TEST ?? "no env";

export default function Page(): JSX.Element {
  return (
    <>
      <Header text="Web" />
      <p>{foo}</p>
      <Button />
    </>
  );
}
```
5. Deploy or run `turbo build`
6. Observe linting error:

```
web:build: ./app/page.tsx
--
21:04:41.887 | web:build: 3:13  Error: 'process' is not defined.  no-undef
```

### Reproduction Repo

https://github.com/JohnGemstone/turborepo-linterror/

**Comment by tknickman** [comment]
Fixed in https://github.com/vercel/turbo/pull/5805

**Comment by JohnGemstone** [comment]
Thanks for the quick turnaround!
