### ISSUE TITLE
[turborepo] [husky] Husky does not work in turborepo

### ISSUE THREAD

**Issue by trixobird** [vercel/turbo#5804]
### What version of Turborepo are you using?

1.10.12

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I am adding husky and once I commit there is this error:

```
trixobird@MacBook-Pro husky-turborepo % git commit -m"Add husky"

> husky-turborepo@ lint /Users/trixobird/w/testing/node/husky-turborepo
> turbo run lint

Turborepo did not find the correct binary for your platform.
We will attempt to install it now.
Installation has failed.

***

Turborepo failed to start.

Turborepo detected that you are running:
darwin 64

***

We were not able to find the binary at:
turbo-darwin-64/bin/turbo

We looked for it at:
/Users/trixobird/w/testing/node/husky-turborepo/node_modules/.pnpm/turbo@1.10.13/node_modules/turbo/bin/node_modules
/Users/trixobird/w/testing/node/husky-turborepo/node_modules/.pnpm/turbo@1.10.13/node_modules/turbo/node_modules
/Users/trixobird/w/testing/node/husky-turborepo/node_modules/.pnpm/turbo@1.10.13/node_modules
/Users/trixobird/w/testing/node/husky-turborepo/node_modules/.pnpm/node_modules
/Users/trixobird/w/testing/node/husky-turborepo/node_modules
/Users/trixobird/w/testing/node/node_modules
/Users/trixobird/w/testing/node_modules
/Users/trixobird/w/node_modules
/Users/trixobird/node_modules
/Users/node_modules
/node_modules
/Users/trixobird/w/testing/node/husky-turborepo/node_modules/.pnpm/turbo@1.10.13/node_modules/turbo/bin/node_modules
/Users/trixobird/w/testing/node/husky-turborepo/node_modules/.pnpm/turbo@1.10.13/node_modules/turbo/node_modules
/Users/trixobird/w/testing/node/husky-turborepo/node_modules/.pnpm/turbo@1.10.13/node_modules
/Users/trixobird/w/testing/node/husky-turborepo/node_modules/.pnpm/node_modules
/Users/trixobird/Library/pnpm/global/5/.pnpm/pnpm@8.6.12/node_modules/pnpm/bin/node_modules
/Users/trixobird/Library/pnpm/global/5/.pnpm/pnpm@8.6.12/node_modules/pnpm/node_modules
/Users/trixobird/Library/pnpm/global/5/.pnpm/pnpm@8.6.12/node_modules
/Users/trixobird/Library/pnpm/global/5/.pnpm/node_modules
/Users/trixobird/.node_modules
/Users/trixobird/.node_libraries
/usr/local/lib/node

***

Turborepo checked to see if binaries for another platform are installed.
This typically indicates an error in sharing of pre-resolved node_modules across platforms.
One common reason for this is copying files to Docker.

We found these unnecessary binaries:
turbo-darwin-arm64/bin/turbo

***

If you believe this is an error, please include this message in your report.
 ELIFECYCLE  Command failed with exit code 1.
husky - pre-commit hook exited with code 1 (error)
trixobird@MacBook-Pro husky-turborepo % 
```

### Expected Behavior

I am expecting to have the pre commit checks ran and the commit

### To Reproduce

pnpm dlx create-turbo@latest
pnpm dlx husky-init && pnpm install
commit

**Comment by arlyon** [comment]
Hi! Thanks for the report! I just checked and have managed to repro on my Mac. I am going to dig in to this. We distribute binaries with our packages and it seems like something in that system has broken on this case. I'll update here with progress.

Cheers

Alex

**Comment by nathanhammond** [comment]
@trixobird Hey! Are you running an Apple ARM processor or an Intel processor? This is a bit interesting:

```
Turborepo detected that you are running:
darwin 64

***

We were not able to find the binary at:
turbo-darwin-64/bin/turbo

***

We found these unnecessary binaries:
turbo-darwin-arm64/bin/turbo
```

**Comment by nathanhammond** [comment]
I also need the contents of `.husky pre-commit` since it appears to have been changed. The default generated version of this is:

```sh
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm test
```

But from your output it appears to be calling `lint`, so I need to know what you modified the file to be:
```
> husky-turborepo@ lint /Users/trixobird/w/testing/node/husky-turborepo
> turbo run lint
```

**Comment by nathanhammond** [comment]
So, given that things are in a weird state (based upon the error message contents), I hypothesize that you have mixed package manager usage in your project or that you have a lot of latent packages sitting around in global namespace. I'm entirely unable to reproduce the failure, and I've tried to reproduce:

1. Exactly as shipped.
```
pnpm dlx create-turbo@latest
pnpm dlx husky-init
pnpm install
git commit -m "Fails because the pre-commit hook defaults to npm test"
```

2. Local Installation.
```sh
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
```

3. Global installation.
```
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

turbo lint
```

4. After upgrading.
```
pnpm dlx @turbo/codemod update 
```

***

Given that I'm unable to reproduce (and believe me, I tried!) I'm going to have to assume that the behavior you're seeing is a problem unique to your setup. If you can provide me a _lot_ more detail about things like what is in your cache, which _exact_ executable is running (`which turbo`), `turbo --skip-infer --version`, `node -p "process.arch"`, I _might_ be able to figure out how you got here.

**Comment by nathanhammond** [comment]
```sh
pnpm dlx create-turbo@latest issue-5804 pnpm
cd issue-5804
pnpm dlx husky-init
pnpm install
sed -i "" "s/npm test/pnpm lint/g" ".husky/pre-commit"
git add --all
git commit -m "Test it works."
```

**Comment by nathanhammond** [comment]
If that fails with copy/paste then the only inputs that can possibly be impacting you are:
- pnpm version
- node version
- pnpm cache

Only one thing stands out: it's attempting to load -64 on your -arm64 device. Did you install node 64 instead of node arm64?

Can you also remove your global pnpm cache and try again?

`pnpm store path`

Then rm it.

**Comment by nathanhammond** [comment]
Also, if you're copy/pasting that test script exactly the directory lookups should not contain `turbo@1.10.13` at all. This indicates to me that your local module cache is poisoned or you have some sort of global pnpm config.

(Or there's an additional step you're doing that I'm not.)

**Comment by trixobird** [comment]
I removed pnpn and node and reinstall it, and everything is working now. Thank you :)
