### ISSUE TITLE
[turborepo] Parsing error: Cannot find module 'next/babel'

### ISSUE THREAD

**Issue by ImBIOS** [vercel/turbo#5817]
### What version of Turborepo are you using?

1.10.13

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

## Description

ESLint error: `Parsing error: Cannot find module 'next/babel'`

## Environment

```

  System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M2
    Memory: 44.83 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/Library/Caches/fnm_multishells/45503_1693117081546/bin/node
    npm: 9.6.7 - ~/Library/Caches/fnm_multishells/45503_1693117081546/bin/npm
    pnpm: 8.6.12 - ~/Library/pnpm/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    eslint: ^8.47.0 => 8.47.0 
    prettier: ^3.0.2 => 3.0.2 
    tsconfig: workspace:* => 0.0.0 
    turbo: latest => 1.10.13 


```

### Expected Behavior

ESLint should work properly without babel resolution error

### To Reproduce

1. Run `pnpm create turbo` and use pnpm.
1. Open `apps/web/next.config.js`, wait a second and the module has a red underline error.

### Reproduction Repo

pnpm create turbo

### Additional Info

Related with:
- #3204
- #3489

**Comment by ImBIOS** [comment]
Related with #3204 #3489

**Comment by tknickman** [comment]
Thanks for the report! This is a vscode issue, you can fix it by adding:

```
{
  "eslint.workingDirectories": [{ "mode": "auto" }]
}
```

to your `.vscode/settings.json`.

I wanted to avoid shipping an IDE specific config with our examples, but it's a common enough issue that we should likely add it in.
