### ISSUE TITLE
[turborepo] Daemon always errors, always hangs

### ISSUE THREAD

**Issue by jakubmazanec** [vercel/turbo#5829]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

I must run turborepo with `--no-daemon`, otherwise I get this error, every time:

```
 WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed.
        To quickly resolve the issue, try running:
        - $ turbo daemon clean

        To debug further - please ensure the following:
        - the process identified by the pid in the file at AppData\Local\Temp\turbod\0a120ac93a2231ff\turbod.pid is not running, and remove AppData\Local\Temp\turbod\0a120ac93a2231ff\turbod.pid
        - check the logs at AppData\Roaming\turborepo\data\logs\0a120ac93a2231ff-toolbox.log
        - the unix domain socket at AppData\Local\Temp\turbod\0a120ac93a2231ff\turbod.sock has been removed

        You can also run without the daemon process by passing --no-daemon
```

Also, I cannot delete node_modules, because some Turborepo processes hang around.

### Expected Behavior

No hanging processes, no warning messages, no need for `--no-daemon` option.

### To Reproduce

Use Turborepo on Windows, I guess 🤷‍♂️

**Comment by chris-olszewski** [comment]
Just to double check, running turbo with `--daemon` fixes the error message not `--no-daemon`? Also, does running `turbo daemon clean` help in any way?

**Comment by jakubmazanec** [comment]
`--daemon` doesn't seem to exist: `ERROR unexpected argument '--daemon' found`. `turbo daemon clean` cleans the stale PID file, what I'm not sure it will help with future instances of this problem. I don't want to use `--no-daemon` everywhere, and I don't want daemon blocking deleting node_modules. Daemon should be opt-in, instead of opt-out.

**Comment by chris-olszewski** [comment]
Closing in favor of #3455 as I believe that issue captures all of the issue you're encountering
