### ISSUE TITLE
Support ARM32 (Raspberry Pi)

### ISSUE THREAD

**Issue by topaxi** [vercel/turbo#5836]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

I'd like to use and run turbo repository on a Raspberry Pi.

Currently I get the following error:
```
***

Turborepo failed to start.

Turborepo detected that you are running:
linux arm

Turborepo supports your platform, but does not support your processor architecture.
```

### Describe the solution you'd like

Running `turbo` on a Raspberry Pi should "just work".

### Describe alternatives you've considered

Using some other monorepo tool, maybe Nx works (haven't tried)?

**Comment by chris-olszewski** [comment]
We do support `arm64`, but it appears you're running the 32 bit version since your arch is `arm` and not `arm64`. I don't think we have any plans/capacity at the moment to support 32 bit.

**Comment by topaxi** [comment]
Good point, I wasn't aware that I installed the 32bit version, as I guess it doesn't matter much on a Raspberry :joy: 

I'll try to reinstall with a 64bit version and see whether that helps.

That would be good enough for me and we can close this issue then :+1:

**Comment by TahaKotwal12** [comment]
i have 64 based system then also it is showing Turborepo failed to start.

Turborepo detected that you are running:
windows ia32

Turborepo supports your platform, but does not support your processor architecture.
