### ISSUE TITLE
[turbopack] The socket.io not working with turbo + next@latest

### ISSUE THREAD

**Issue by avinashcodelabs** [vercel/turbo#5837]
### What version of Next.js are you using Turbopack in?

canary

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

- Created the nextjs project with npx create-next-app@latest app_name
- Added socket.io & socket.io-client package and wrote socket code in server and client.
- Changed the package.json to use ---turbo command
"dev": "next dev --turbo"
- Now, if run the app with "npm run dev", socket is not working throwing 404 polling error in chrome console and network tab.
- If i remove "--turbo", from dev script, everthing works fine.

GitHub repo - https://github.com/avinashcodelabs/nextjs-turbo-socketio-reproduce-issue.git
Codesanbox link - https://codesandbox.io/p/github/avinashcodelabs/nextjs-turbo-socketio-reproduce-issue/main?workspaceId=f5e62c11-e518-4676-ae49-f9fdcb9090e2 

Terminal output:
ready - started server on [::]:3000, url: http://localhost:3000
[404] /api/socket_io (3189ms)
[404] /api/socket_io (3765ms)
[404] /api/socket_io (3905ms)
error - [resolve] ... [1 paths] are hidden, run with --show-all to show them
warning -
  [parse]
    ... [2 paths] are hidden, run with --show-all to show them
  [resolve]
    ... [3 paths] are hidden, run with --show-all to show them
event - 13 requests (GET /, ...), and side effects of 7 requests (GET /, ...) 9559ms
event - 10 requests (GET /_next/static/chunks/_env_b53fce.js.map, ...), and side effects of 9 requests (GET /_next/static/chunks/_env_b53fce.js.map, ...) 325ms
event - side effects of 4 requests (GET /_next/static/chunks/node_modules_@swc_helpers_esm__interop_require_wildcard_dff17b.js, ...), and 7 requests (GET /_next/static/chunks/node_modules_next_2d9381._.js.map, ...) 132ms
event - side effects of 26 requests (GET /_next/static/chunks/[next]_dev_2185c6._.js, ...), and 25 requests (GET /turbopack-hmr, ...) 1537ms
[404] /api/socket_io (53ms)
[404] /api/socket_io (49ms)
event - side effects of 15 requests (GET /_next/static/chunks/app_page_b53fce.js, ...), and 17 requests (GET /api/socket_io, ...) 722ms
event - 13 requests (GET /api/socket, ...), and side effects of 13 requests (GET /_next/static/chunks/app_page_5771e1.js, ...) 380ms
Socket is initializing
warning - [parse] ... [1 paths] are hidden, run with --show-all to show them
[404] /api/socket_io (54ms)
[404] /api/socket_io (60ms)
event - 4 requests (GET /api/socket_io, ...) 1365ms
[404] /api/socket_io (21ms)
[404] /api/socket_io (23ms)
event - 4 requests (GET /api/socket_io, ...) 34ms
[404] /api/socket_io (23ms)
event - 2 requests (GET /api/socket_io, ...) 32ms
[404] /api/socket_io (22ms)
[404] /api/socket_io (27ms)
[404] /api/socket_io (44ms)
event - 6 requests (GET /api/socket_io, ...) 65ms

### Expected Behavior

Socket connection should work with in latest Next.js app with "dev": "next dev --turbo" script in package.json

### To Reproduce

```
git clone https://github.com/avinashcodelabs/nextjs-turbo-socketio-reproduce-issue.git
cd nextjs-turbo-socketio-reproduce-issue
npm i
npm run dev
```

Note: I have  **"dev": "next dev --turbo"** in package.json file
Now, go to http://localhost:3000/ and open chrome's Console or Network tab. here we will see the socket connections are failing.
Screenshot attched.

![next-turbo-socketio-issue](https://github.com/vercel/turbo/assets/18024455/f9cf24bb-6c40-4a64-b189-edb419669770)

![codesanbox-repro](https://github.com/vercel/turbo/assets/18024455/a23b6011-9d0b-4e49-9914-b78cc3cafc6a)

### Reproduction Repo

https://github.com/avinashcodelabs/nextjs-turbo-socketio-reproduce-issue

**Comment by R-Kazmi** [comment]
Somehow socket.io-client version 3.1.2 works and every other version gives this error.

**Comment by timneutkens** [comment]
Verified this has been fixed 💯 

Here's the sandbox with the latest canary: https://codesandbox.io/p/github/avinashcodelabs/nextjs-turbo-socketio-reproduce-issue/csb-dy6z6n/draft/silly-volhard?file=%2Fapp%2Fpage.tsx%3A16%2C8

Network tab: 
![CleanShot 2024-02-09 at 08 41 13@2x](https://github.com/vercel/turbo/assets/6324199/d3b9323b-3509-4cfa-ac1c-d7e47ec9e302)

**Comment by KUSHAL-RAJ-PAREEK** [comment]
it's not working for me

**Comment by timneutkens** [comment]
You can open a new issue with a complete reproduction 🙂
