### ISSUE TITLE
[turborepo] `turbo prune` does not preserve symlinks

### ISSUE THREAD

**Issue by cngJo** [vercel/turbo#5842]
### What version of Turborepo are you using?

1.10.13

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When using symlinks in an app and prune this app, the symlink gets converted to a directory. 

**Backstory** 

My use-case where I found this is, that we distribute our font-stack and font files in a separate package `packages/design`. 
Using this approach, we ran into issues with `scss` not resolving the font files doe to them being loaded from a relative path in `packages/design` which does not exist in `apps/web`. This is solved by a symlink, until I have a better solution, but that's not a topic for here, I just wanted to share some insights to why this symlink is used.

### Expected Behavior

Symlinks should be preserved during `turbo prune`, both inside the same package and between packages, and not get converted to plain directories.

> See **Backstory** to explain why we use/need a symlink in the first place

### To Reproduce

Basically create _any_ symlink in an app, `turbo prune` and check the symlink.

```bash
# 1. create new monorepo
pnpm dlx create-turbo@latest

# 2. create directory test in apps/web with an empty file
cd apps/web
mkdir test
touch test/test.txt

# 3. create a symlink `directory` pointing to the created directory
ls -n test directory

# 4. Verify we can access the file "through" the symlink"
file directory/test.txt 
# OUTPUT: directory/test.txt: empty
# CONCLUSION: symlink works

# 5. go back and prune apps/web 
cd ../..
turbo prune --scope=web

# 6. check the symlink in the pruned output
cd out/apps/web
file directory/text.txt  
# OUTPUT: directory/test.txt: cannot open `directory/test.txt' (No such file or directory)
# CONCLUSION: symlink does not work
```

When we take a look at `directory` in the pruned app, we see that is "just" a directory and not a symlink anymore.

```text
drwxr-xr-x   2 johannes  staff    64 Aug 31 06:10 directory/
```

### Reproduction Repo

https://github.com/cngJo/turbo-symlink-reproduction

**Comment by nathanhammond** [comment]
Hey @cngJo! When running `prune` the intent is to grab just the packages that are necessary and nothing else. In your description of your use case you're talking about a symlink whose target is _outside_ of `apps/web` inside of `packages/design`.

We don't know _anything_ about the symlink target, including whether or not it will be reconstituted in the extracted location by a different tool. Given that, we really only have one option: capture the symlink precisely as defined.

The correct approach in your scenario is to include the package that contains the symlink target as part of the `prune` targets.

The existing behavior _may_ be demonstrating a bug (@chris-olszewski), but if so it is a bug which only appears in a misconfigured state.

I'm closing this issue; @chris-olszewski may be interested in coming back to change the behavior for when it encounters issues.

**Comment by cngJo** [comment]
Hey @nathanhammond

Thanks for your response!

I get the point about why the symlink is not properly resolved. 
Even tho in my example, `app/web` has a dependency on `packages/design`, since we `@import` stylesheets from that package. So the symlink in the other package would work with the same relative path ;)
The issue why we need the symlink in the first place lies in a path resolution issue in `sass`.

I've worked around this with a simple `cp -R` after pruning `apps/web` and that works for me. Not the cleanest solution, but that's already the case with needing that symlink :D 

When you come back to this issue and / or decide that you want to handle this as a bug, feel free to ping me when needed ;)

**Comment by nathanhammond** [comment]
Does `turbo prune --scope=web --scope=design` not work?

**Comment by nathanhammond** [comment]
Back at a computer:

- If you've got it marked as a dependency the correct path for that font is this: `path.join(path.base(require.resolve('design/package.json')), 'path', 'to', 'font.woff')`.
- You _probably_ still need to prune with both scopes enumerated.

**Comment by nathanhammond** [comment]
@cngJo I'm wrong, and I can reproduce your issue! Thank you for your persistence.

```
pnpm dlx create-turbo@latest prune-test pnpm
cd prune-test/apps/web/app
ln -s ../../../packages/ui/turbo
ln -s ../../../packages/ui/button.tsx
ls -la turbo button.tsx
# button.tsx -> ../../../packages/ui/button.tsx
# turbo -> ../../../packages/ui/turbo
cd ../../..
pnpm turbo prune --scope=web
tree out
```

Output:
```
out
├── apps
│   └── web
│       ├── README.md
│       ├── app
│       │   ├── button.tsx -> ../../../packages/ui/button.tsx
│       │   ├── layout.tsx
│       │   ├── page.tsx
│       │   └── turbo
```

That "turbo" directory is indeed not maintaining the symlink.

**Comment by nathanhammond** [comment]
@gsoltis @chris-olszewski this ends up being:

https://github.com/vercel/turbo/blame/492d2daacc9ae5b0230fe086e0c62e7bc2d54ae7/crates/turborepo-fs/src/lib.rs#L46-L49

Additional notes over at: https://github.com/vercel/turbo/pull/4719

**Comment by nathanhammond** [comment]
If you look at the commit _before_ #4719 landed we can more-easily see that `RecursiveCopy` is exclusively used by `prune`. 2db09b7d40419bad5d32c251e15ce02767361865

The behavior of `RecursiveCopy` was written prior to `cache-to-tar` which removed all other consumers of this functionality. That is a legacy of trying to do `cp -ar` manually in Go without advance plans.

<img width="382" alt="Screenshot 2023-09-05 at 9 57 22 AM" src="https://github.com/vercel/turbo/assets/20542/c195e759-22a9-4e3a-b0b3-a25c4b74fd39">

> I've reproduced these quirks so that we can fix them on purpose rather than bury them in the porting effort. @gsoltis 

It's time.

**Comment by khuezy** [comment]
Hi, I'm not sure if this is related to symlinks, but when I run `turbo prune web --docker`, the `out/full/apps/web/node_modules/ui` is empty. To reproduce, use https://github.com/vercel/turbo/tree/main/examples/with-docker and switch to `pnpm` and add `pnpm-workspace.yaml`:
```
packages:
  - "packages/*"
  - "apps/*"
```
