### ISSUE TITLE
[turborepo/docs]: "Publishing Packages" CJS-only advice is outdated

### ISSUE THREAD

**Issue by llllvvuu** [vercel/turbo#5843]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

> In this guide, we'll be using a bundler to bundle a package to [CommonJS](https://en.wikipedia.org/wiki/CommonJS), the most commonly used format used on npm.

It's true that CJS is the most common overall, but modern packages tend to be dual-packaged, and TypeScript users tend to write `import`, which means they will choose the ESM export if it is available, and get the gains of doing so.

The only change that would need to be made to the instructions:
```diff
-    "build": "tsup src/index.ts --format cjs --dts"
+    "build": "tsup src/index.ts --format cjs,esm --dts"

  "main": "./dist/index.js",
+ "module": "./dist/index.mjs",
  "types": "./dist/index.d.ts"
```

### Describe the solution you'd like

It's of course a matter of opinion, but IMO ESM is the future and is superior for users. I personally even prefer a more extreme approach of [shipping ESM-only like sindre](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), but dual-package seems to be the more common/moderate / non-breaking approach so I suggest that.

### Describe alternatives you've considered

Alternative: leaving as-is. The upside of packaging only a single format is that there is no [dual-package hazard](https://nodejs.org/api/packages.html#dual-package-hazard).

I wanted to get an opinion before submitting a PR.

**Comment by tknickman** [comment]
I'm in favor of this. Would even love if we could recommend straight `esm`, but that would probably cause _more_ issues for us to sort out - so I think the hybrid is the best approach, thanks for the suggestion!
