### ISSUE TITLE
[turborepo] Cannot create starter app with create-turbo-app and throw 503 error

### ISSUE THREAD

**Issue by amm834** [vercel/turbo#5868]
### What version of Turborepo are you using?

1.0.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

```
➜  workspace pnpm dlx create-turbo@latest
../Library/pnpm/store/v3/tmp/dlx-4492    | +116 ++++++++++++
../Library/pnpm/store/v3/tmp/dlx-4492    | Progress: resolved 116, reused 116, downloaded 0, added 116, done

>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.

? Where would you like to create your turborepo? next-fdd
? Which package manager do you want to use? pnpm

Downloading files. This might take a moment.


>>> Unexpected error. Please report it as a bug:
av [Error]: Response code 503 (Service Unavailable)
    at Uo (/Users/admin/Library/pnpm/store/v3/tmp/dlx-4492/node_modules/.pnpm/create-turbo@1.10.13/node_modules/create-turbo/dist/cli.js:45:268)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.Nc (/Users/admin/Library/pnpm/store/v3/tmp/dlx-4492/node_modules/.pnpm/create-turbo@1.10.13/node_modules/create-turbo/dist/cli.js:218:615)
    at async Command.parseAsync (/Users/admin/Library/pnpm/store/v3/tmp/dlx-4492/node_modules/.pnpm/commander@10.0.1/node_modules/commander/lib/command.js:935:5)

```

### Expected Behavior

It should create a starter app.

### To Reproduce

```
pnpm dlx create-turbo@latest
```

### Reproduction Repo

Cannot provide cause it have not been created to use it.

**Comment by bryanjhickey** [comment]
Some issue with me.

```bash
pnpm dlx create-turbo@latest


.../Library/pnpm/store/v3/tmp/dlx-90617  | +116 ++++++++++++
.../Library/pnpm/store/v3/tmp/dlx-90617  | Progress: resolved 116, reused 116, downloaded 0, added 116, done

>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.

? Where would you like to create your turborepo? ./my-turborepo
? Which package manager do you want to use? pnpm

Downloading files. This might take a moment.


>>> Unexpected error. Please report it as a bug:
av [Error]: Response code 503 (Service Unavailable)
    at Uo (/Users/bjh/Library/pnpm/store/v3/tmp/dlx-90617/node_modules/.pnpm/create-turbo@1.10.13/node_modules/create-turbo/dist/cli.js:45:268)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.Nc (/Users/bjh/Library/pnpm/store/v3/tmp/dlx-90617/node_modules/.pnpm/create-turbo@1.10.13/node_modules/create-turbo/dist/cli.js:218:615)
    at async Command.parseAsync (/Users/bjh/Library/pnpm/store/v3/tmp/dlx-90617/node_modules/.pnpm/commander@10.0.1/node_modules/commander/lib/command.js:935:5)
```

**Comment by nathanhammond** [comment]
Hey y'all, the first thing that does is attempt to download from GitHub. You're seeing an error caused by this:

https://www.githubstatus.com/incidents/c8zjb9351hlc

We need to improve our error handling in this scenario to communicate what is happening, but it was a short term exceptional state.

**Comment by todorone** [comment]
@nathanhammond @tknickman 

have the same 503 issue, but now with post-script. nothing helps 😢

**Comment by amm834** [comment]
> @nathanhammond @tknickman
> 
> have the same 503 issue, but now with post-script. nothing helps 😢
> 
> ```
> node_modules/.pnpm/turbo@0.8.5/node_modules/turbo: Running postinstall script, failed in 4s
> .../.pnpm/turbo@0.8.5/node_modules/turbo postinstall$ node install.js
> │ /Users/.../node_modules/.pnpm/turbo@0.8.5/node_modules/turbo/install.js:291
> │         throw e
> │         ^
> │ HTTPError: Response code 503 (Service Unavailable)
> │     at Request.<anonymous> (/Users/fediru/dev/tvpil/node_modules/.pnpm/got@11.8.6/node_modules/got…
> │     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
> │   code: 'ERR_NON_2XX_3XX_RESPONSE',
> │   timings: {
> │     start: 1698762901485,
> │     socket: 1698762901485,
> │     lookup: 1698762901487,
> │     connect: 1698762901494,
> │     secureConnect: 1698762901502,
> │     upload: 1698762901502,
> │     response: 1698762901745,
> │     end: 1698762901746,
> │     error: undefined,
> │     abort: undefined,
> │     phases: {
> │       wait: 0,
> │       dns: 2,
> │       tcp: 7,
> │       tls: 8,
> │       request: 0,
> │       firstByte: 243,
> │       download: 1,
> │       total: 261
> │     }
> │   }
> │ }
> │ Node.js v18.17.1
> └─ Failed in 4s at /Users/.../node_modules/.pnpm/turbo@0.8.5/node_modules/turbo
>  ELIFECYCLE  Command failed with exit code 1.
> ```

It's npm API issue
