### ISSUE TITLE
[turborepo] unable to parse yaml: mapping values are not allowed in this context at line 24 column 15

### ISSUE THREAD

**Issue by paulwongx** [vercel/turbo#5902]
### What version of Turborepo are you using?

1.10.12

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When running turbo build, I keep getting this error. It's not clear to me which yaml file it's referrring to... can someone help me clarify?

```cli
Running "turbo run build"
--
00:39:14.085 | WARNING  Issues occurred when constructing package graph. Turbo will function, but some features may not be available:  1 error occurred:
00:39:14.085 | * unable to parse yaml: mapping values are not allowed in this context at line 24 column 15
```

If referring to the yarn.lock file, the content at line 24 is below, but it's unclear how I'm supposed to resolve this.
```cli
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

// ....

"@ampproject/remapping@^2.2.0":
  version "2.2.1"
  resolved "https://registry.yarnpkg.com/@ampproject/remapping/-/remapping-2.2.1.tgz#99e8e11851128...."
  integrity sha512-lFM.....
  dependencies: // <<<<<<<<<<<<<<<<<<<<<<<< This is line 24
    "@jridgewell/gen-mapping" "^0.3.0"
    "@jridgewell/trace-mapping" "^0.3.9"
```

I'm raising this as an issue due to [this similar issue](https://github.com/vercel/turbo/issues/394).

I create my project using `npx create-turbo@latest`

### Expected Behavior

1. Should not have malformed yaml
2. Should clarify which yaml file has the error

### To Reproduce

```cli
Running "turbo run build"
--
00:39:14.085 | WARNING  Issues occurred when constructing package graph. Turbo will function, but some features may not be available:  1 error occurred:
00:39:14.085 | * unable to parse yaml: mapping values are not allowed in this context at line 24 column 15
```

**Comment by chris-olszewski** [comment]
Do you have a `packageManager` set in your `package.json`? If not, can you set it to the version of `yarn` that you expect?

**Comment by chris-olszewski** [comment]
If I had to guess, I believe that this would be fixed by https://github.com/vercel/turbo/pull/5986

**Comment by chris-olszewski** [comment]
If anyone encounters this please try upgrading to `turbo@1.10.15-canary.0` and reopen if the problem persists.
