### ISSUE TITLE
[turbopack] Crash build on importing sqlite3 

### ISSUE THREAD

**Issue by lr0pb** [vercel/turbo#5913]
### What version of Next.js are you using Turbopack in?

13.4.19

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

Importing and using [`sqlite3`](https://www.npmjs.com/package/sqlite3) library in server component using turbopack results in an error
Using `next dev` without `--turbo` importing everything right
![image](https://github.com/vercel/turbo/assets/53260102/470d452a-a9ea-4d8f-b57b-ec60b4f7d71c)

### Expected Behavior

Import `sqlite3` in server components work

### To Reproduce

Run `npm i sqlite`

Add server component `app/page.tsx`
```tsx
import sqlite3 from 'sqlite3';

export default function Page() {
  console.log(sqlite3.READONLY);
  return <div></div>;
}
```

Run `next dev --turbo`

**Comment by timneutkens** [comment]
This works now 💯

Added a test case here: https://github.com/vercel/next.js/pull/61845
