### ISSUE TITLE
[turborepo] Unable to find Go binary

### ISSUE THREAD

**Issue by cupid-dev** [vercel/turbo#5920]
### What version of Turborepo are you using?

1.10.13

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

New Turbo user with a fresh download on an M2 Mac. I'm following the ["Creating a new monorepo"](https://turbo.build/repo/docs/getting-started/create-new) getting started guide and hit this error whenever I try to run a `turbo` command, like `turbo lint` or `turbo build`. The same issue has been [raised](https://github.com/vercel/turbo/issues/5381) before.

```
git:(main) cd apps/docs
➜  docs git:(main) turbo build
ERROR Unable to find Go binary. Please report this issue at https://github.com/vercel/turbo/issues and include your package manager and version along with the following information:
        os=macos
        arch=x86_64
        turbo-version=1.10.13
        turbo-bin=/Users/Wyatt/Dropbox/Cupid3/node_modules/.pnpm/turbo-darwin-64@1.10.13/node_modules/turbo-darwin-64/bin/turbo
        go-turbo-bin=/Users/Wyatt/Dropbox/Cupid3/node_modules/.pnpm/turbo-darwin-64@1.10.13/node_modules/turbo-darwin-64/bin/go-turbo
```  

@nathanhammond you [asked](https://github.com/vercel/turbo/issues/5381#issuecomment-1630392090) for this info on the last issue:

```
cupid3 git:(main) ls -la ./node_modules/turbo/bin
total 24
drwxr-xr-x  3 Me  staff     96 Sep  9 18:08 .
drwxr-xr-x  7 Me  staff    224 Sep  9 18:08 ..
-rwxr-xr-x  3 Me  staff  10722 Sep  9 18:07 turbo
``` 

I don't see go-turbo.

### Expected Behavior

The turbo commands to work

### To Reproduce

I followed the getting started guide.

**Comment by cupid-dev** [comment]
I've discovered that I can successfully run the turbo commands indirectly, by calling the package.json scripts: e.g., `pnpm run start`

**Comment by nathanhammond** [comment]
I'm still going to need a lot more information before I'm able to identify what's going on.

It looks like you are running global turbo.

`which turbo`
ls -la of that dir

I suspect you have an old, global insulation somehow.

I want to try debugging before I ask you to just run 

npm install -g turbo@latest

**Comment by nathanhammond** [comment]
In general: tell me everything you can find out about what versions are on your box, and where they are coming from.

I would be looking in global, and local. Look at the package.json in each of those turbo directories.

**Comment by nathanhammond** [comment]
Put another way: in 1.10.13 we changed the way install happens such that there's no way that I know possible to split go-turbo. That is an artifact of an older install process that we no longer use.

Part of the problem may be that we ship lockfiles in our examples still use an older version. /cc @tknickman

**Comment by nathanhammond** [comment]
Almost certain to work: new global install, make sure package.json in the monorepo is 1.10.13, remove the lockfile, remove node_modules, reinstall.

**Comment by davidortner-ipex** [comment]
The problem with re-installing is that it won't work on a different architecture from what it was installed on.

Adding the binary packages manually as dependencies solves it:

```
"devDependencies": {
         "turbo-darwin-64": "^1.12.4",
        "turbo-darwin-arm64": "^1.12.4",
        "turbo-linux-64": "^1.12.4",
        "turbo-linux-arm64": "^1.12.4",
        "turbo-windows-64": "^1.12.4",
        "turbo-windows-arm64": "^1.12.4"
}
```
