### ISSUE TITLE
[turborepo] Issue in kitchen sink code

### ISSUE THREAD

**Issue by Akash-pugazh** [vercel/turbo#5928]
### What version of Turborepo are you using?

1.10.13

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

After creating a project using Kitchen Sink, On initial code at Admin/src/app/index.tsx
It reports that ui module is not properly found

### Expected Behavior

It should not produce error, It should import the components from ui module and components should be used in pages

### Create Project

`npx create-turbo -e kitchen-sink`

**Once Done open in Code and navigate to the apps/admin/src/app/index.tsx**

**Comment by tknickman** [comment]
This can be fixed by building the ui package, or running `turbo lint` (turbo will ensure ui is build first)
