### ISSUE TITLE
Make it easier to deploy a self-hosted cache

### ISSUE THREAD

**Issue by fredsensibill** [vercel/turbo#5944]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

I would like to be able to more easily deploy a self-hosted cache for my team. Given our security requirements we are not able to use Vercel, so the next best thing would be to deploy it in our own cloud provider.

### Describe the solution you'd like

I would like a Docker image that can be deployed wherever. 

### Describe alternatives you've considered

A command like `turbo cache serve` or something, to setup the cache server in the specified host/port.

I honestly have not considered writing my own cache server as the documentation suggests. Seems a bit much.

<sub>[TURBO-1389](https://linear.app/vercel/issue/TURBO-1389/make-it-easier-to-deploy-a-self-hosted-cache)</sub>

**Comment by weyert** [comment]
Plenty of open-source solutions available for the cache server. Have similar concerns so wrote my own

**Comment by arlyon** [comment]
Hey, thanks for opening this. We should have a list of 3rd party cache servers in our docs somewhere for others with similar constraints. I will mention this today and get a timeline.

**Comment by anthonyshew** [comment]
As mentioned, there are open-source solutions a search away! Will close.
