### ISSUE TITLE
Support Console Ninja extension on Visual Studio Code

### ISSUE THREAD

**Issue by SirFrey** [vercel/turbo#5977]
### Which project is this feature idea for?

Turbopack

### Describe the feature you'd like to request

Support for Console Ninja.

### Describe the solution you'd like

A kind of API or something similar that allows console ninja to track the `console.log` there's in the code.

### Describe alternatives you've considered

I haven't think in other thing yet.

**Comment by kwonoj** [comment]
I have raised upstream issues and discussed bit about what technical challenges need to be resolved. It is something we may consider to adapt, but there's no immediate plan. 

Refer https://github.com/wallabyjs/console-ninja/issues/136 for the details.

**Comment by ArtemGovorov** [comment]
We are keen on adding Turbopack support in Console Ninja. Perhaps Turbopack can expose a setting that exposes a hook to its fs reads, or makes it read files from disk via node fs API? The loaders API already exposes certain bits of it in a way (ie. passes/receives source code to/from loader node process). 

As @kwonoj pointed out, there are also internal assets that Turbopack handles, but it looks like we don't need them to make Console Ninja work, a simple fs hook may be enough.
