### ISSUE TITLE
[turborepo] npx create-turbo throws error -  Unable to download template from Github (Mac M1)

### ISSUE THREAD

**Issue by nujumo** [vercel/turbo#5984]
### What version of Turborepo are you using?

1.10.14 (but was facing the same issue previously with 1.10.13)

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

When running npx create-turbo I get the following error...
![image](https://github.com/vercel/turbo/assets/14853975/c98de194-e836-473f-8e44-fc61a535bb7f)

### Expected Behavior

That npx create-turbo would generate a turborepo in the ./my-turborepo folder

### To Reproduce

Node version: 18.17.1
NPM version: 9.6.7
Mac M1

1. Ran npm install -g turbo
2. In a new folder ran npx create-turbo, and confirmed proceed to install package create-turbo@1.10.14.
3. Set the folder name
4. Choose the npm workspaces option
5. 'Downloading files' starts
6. After several minutes the following error appears ...`>>> Unable to download template from Github
>>> The server aborted pending request`

![image](https://github.com/vercel/turbo/assets/14853975/44b02310-eb6a-4ef8-9866-0baad357f051)

**Comment by nathanhammond** [comment]
Heya @nujumo! This issue isn't a Turborepo issue. Turborepo is failing to download from GitHub. You can see that GitHub was experiencing issues when you filed this issue: https://www.githubstatus.com/incidents/zjchv3zvfg50

**Comment by nujumo** [comment]
@nathanhammond, I have been having the same/similar issue for a couple of weeks now (since I got a new work machine), i.e. with version 1.10.13 and with 1.10.14. 

However, npx create-turbo does appear to be working as expected this morning
