### ISSUE TITLE
[turborepo] 

### ISSUE THREAD

**Issue by DJanocha** [vercel/turbo#5989]
### What version of Turborepo are you using?

1.10.13

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When trying to run scripts using the turbo cli, for example `turbo run typecheck`, turbo cli doesn't run the 'typecheck' script among the apps/packages that have that script defined. Instead of that I get the following error:
```
 ERROR  run failed: error preparing engine: Could not find the following tasks in project: typecheck
Turbo error: error preparing engine: Could not find the following tasks in project: typecheck
```

What confuses me is that I can run the `turbo build` and `turbo dev` scripts.
Examples of scripts I cannot run the following scripts: `turbo db:generate`, `turbo db:push`, `turbo typecheck`.

It doesn't metter if I run `turbo run ${script}` or `turbo ${script}` scripts.

It may be the cause of my config, but I could find the issue with it.

Info about my hardware and OS:
- mac mini (2023),
- ram: 32GB,
- macOs: 13.3.1 (a) (22E772610a)

pnpm version: 8.6.12,

### Expected Behavior

I would like the turbo cli to run the 'typecheck' scripts among all of the apps/packages that specified that script. In my case the following package.json files have that script defined:
- apps/api/package.json,
- apps/web/package.json,
- packages/db/package.json,
- packages/shared/package.json,

### To Reproduce

1. clone my repo: `git clone https://github.com/DJanocha/fullstack-template.git . `
2. install dependencies: `pnpm i`,
3. generate prisma client: `pnpm db:generate`
4. running script that is not working but should work like `turbo run typecheck` or `turbo db:generate`

As you can see in the codebase of my repo, I try to avoid the turbo cli eg. in main package.json in "db:generate" script because of the problem I am facing.

### Reproduction Repo

https://github.com/DJanocha/fullstack-template.git

**Comment by nathanhammond** [comment]
Your `turbo.json` does not define any of those scripts so we don't execute them. You would need to add them here:
https://github.com/DJanocha/fullstack-template/blob/cf83b408e17738b046af1937f09f32b03f2dcb53/turbo.json#L6-L22

**Comment by nathanhammond** [comment]
(Coming soon: better error messages that would have told you that `turbo.json` doesn't include that script.)
