### ISSUE TITLE
[turborepo] fails to hash the project without a clear reason

### ISSUE THREAD

**Issue by wladiston** [vercel/turbo#6046]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I started to see this issue after updating the turbo to the latest version

```bash
➜ npx turbo run build
 ERROR  run failed: error hashing package files: io error: No such file or directory (os error 2)
Turbo error: error hashing package files: io error: No such file or directory (os error 2)
```

It seems like this issue was introduced on `1.10.7`. Did some testing and `1.10.6` works fine.
It would be awesome to have a clear error message though.

### Expected Behavior

turbo run works :)

### To Reproduce

1. clone the repo
2. `pnpm install`
3. `cd apps/server`
4. `npx turbo run build`

### Reproduction Repo

https://github.com/bamotf/bamotf

<sub>[TURBO-1399](https://linear.app/vercel/issue/TURBO-1399/[turborepo]-fails-to-hash-the-project-without-a-clear-reason)</sub>

**Comment by nathanhammond** [comment]
I can reproduce, investigating.

**Comment by nathanhammond** [comment]
Investigating to see if caused by #5401.

**Comment by nathanhammond** [comment]
So, the cause of the problem is that your project includes a broken symlink:
https://github.com/bamotf/bamotf/blob/main/apps/server/.env

The "correct" outcome here is a bit ambiguous, give me a bit to figure out what I think.

**Comment by wladiston** [comment]
Good catch!
