### ISSUE TITLE
[turborepo] --filter not working inside docker container

### ISSUE THREAD

**Issue by ArshanKhanifar** [vercel/turbo#6078]
### What version of Turborepo are you using?

1.10.12

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

My monorepo has 3 apps, I wanna only run 2 of them, they're located at apps/box-api and apps/box-scenarios. 
Running this in local setup works just fine:
```
    "start:playwright": "turbo run --filter={\"./apps/box-api\",\"./apps/box-scenarios\"} start ",
```

Running the same thing in my dockerfile filters everything out & runs 0 tasks.

Here's my dockerfile:

```
FROM arshankhanifar/box-run-build

COPY . .

RUN pnpm i

RUN pnpm run build:ci

ENTRYPOINT pnpm run start:playwright
```

build:ci also runs on my host computer, all it does is it sets some env vars before building so it shouldn't really be related to this issue. 

My Mac's info:
![image](https://github.com/vercel/turbo/assets/10492324/0e0d4596-f5b4-44b2-b29c-e73e657055ed)

My docker image's info:
```
uname-a
Linux 7e649e54b344 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
pnpm version
8.8.0
node version
v18.17.1
turbo version

> box-monorepo@ get:turbo-version /home/box-monorepo
> turbo --version

1.10.12
```

### Expected Behavior

should filter for those two apps and run

### To Reproduce

my repo is private for my company, but I'm happy to make a sample repo. 

<sub>[TURBO-1395](https://linear.app/vercel/issue/TURBO-1395/[turborepo]-filter-not-working-inside-docker-container)</sub>

**Comment by chris-olszewski** [comment]
A few things:
 - If you just want exact workspaces, passing the name of the workspace can be used: e.g. `turbo run --filter=box-api --filter=box-scenarios start` (assuming those are the names of the packages)
 - `{}` are only necessary when combining directory filters with other filters, I believe you want to use `turbo run --filter='./apps/box-api' --filter='./apps/box-scenarios' start` if you want to stick with directory matching.
 - Can you confirm that `turbo run --filter="{\"./apps/box-api\",\"./apps/box-scenarios\"}" start` runs the two tasks when you run that command from your terminal? I'm unable to get this structure of filter to match any tasks.

**Comment by chris-olszewski** [comment]
Closing this as I'm pretty sure the other filters I provided above would fix the issue. Feel free to reopen if you do need the bracket syntax along with a repro if possible.
