### ISSUE TITLE
[turborepo] I can't add "use client" to my component

### ISSUE THREAD

**Issue by ara6i** [vercel/turbo#6093]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

dist/dropdown/dropdown.mjs (1:0) Module level directives cause errors when bundled, "use client" in "dist/dropdown/dropdown.mjs" was ignored.

its ignoring use client in my component i have already build next js with turbo repo and in ui package i need to use "use client"

it should be add in chunk manually please help !

### Expected Behavior

use client should work fine

### To Reproduce

"use client";

import React, { useState } from "react";
import { DropdownProps } from "./types";

export const Dropdown: React.FC<DropdownProps> = (props) => {
  const [isOpen, setIsOpen] = useState(false);

  const handleDropdownClick = () => {
    setIsOpen(!isOpen);
  };

  return (
    <div className="relative inline-block text-left">
      <button
        type="button"
        className="inline-flex justify-center w-full rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none"
        id="dropdown-menu-button"
        onClick={handleDropdownClick}
      >
        Click
      </button>

      {isOpen && (
        <div className="origin-top-right absolute right-0 mt-2 w-52 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5">
          <div
            className="py-1"
            role="menu"
            aria-orientation="vertical"
            aria-labelledby="dropdown-menu-button"
          >
            <a
              href="#"
              className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"
              role="menuitem"
            >
              Item 1
            </a>
            <a
              href="#"
              className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"
              role="menuitem"
            >
              Item 2
            </a>
          </div>
        </div>
      )}
    </div>
  );
};

<sub>[TURBO-1419](https://linear.app/vercel/issue/TURBO-1419/[turborepo]-i-cant-add-use-client-to-my-component)</sub>

**Comment by ara6i** [comment]
i'm using Ubuntu as my OS

**Comment by ara6i** [comment]
> Can you please provide a full reproduction repository? This sounds like an issue with configuration and without seeing the full codebase it's hard to offer assistance.
i'm using tuborepo + tailwind boilerplate  

i have setup tsup config to see if its work , now it is using "use client" but it does not come at the first line of code 
![tsup](https://github.com/vercel/turbo/assets/88967049/6849961b-4371-4f28-ba2b-251adfa2d44c)
![Screenshot from 2023-10-04 20-28-21](https://github.com/vercel/turbo/assets/88967049/c0ff12ac-f38b-4cf0-9740-98a55d504558)
![Screenshot from 2023-10-04 20-27-34](https://github.com/vercel/turbo/assets/88967049/bb8eacdb-1fde-46cd-bf04-e7a4f49485d0)

**Comment by ara6i** [comment]
i'm using turbo repo + tailwind boilerplate that the document mentioned 
https://turbo.build/repo/docs/getting-started/from-example

**Comment by ara6i** [comment]
also the chunk file 
![Screenshot from 2023-10-04 20-35-25](https://github.com/vercel/turbo/assets/88967049/0e7df124-bce6-45e7-b52c-2dd7f758e72f)

**Comment by chris-olszewski** [comment]
I believe you're hitting [esbuild's limitation with cjs code splitting](https://esbuild.github.io/api/#splitting). If you remove `splitting: true`, then I believe you will have your banner appear in the proper spot.

If you want an example of someone using a similar setup with turbo, I'd check out [react-wrap-balancer](https://github.com/shuding/react-wrap-balancer/blob/main/tsup.config.ts)
