### ISSUE TITLE
[turborepo] NextJS with "use client" components causing error

### ISSUE THREAD

**Issue by william-fargues** [vercel/turbo#6094]
### What version of Turborepo are you using?

1.10.14

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

Let's take a classic scenario in which you're exporting components from an `index.ts` file from let's say a `ui` package.
You are exporting both server and client components.

Now let's omit on purpose the "use client" directive on our client component and that's it (we do not even import it anywhere in the app).

Even though we don't use it we'll have this error: 
> You're importing a component that needs useState. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.

### Expected Behavior

Because the component is not imported anywhere in the app, we should not see any error.

### To Reproduce

1. Clone the basic repo: [https://github.com/vercel/turbo/tree/main/examples/basic](https://github.com/vercel/turbo/tree/main/examples/basic)
2. Create a button component (omitting the `"use client"` in the `ui` package):
``` typescript
import type { ReactElement} from 'react';
import { useState } from 'react';

export function Button(): ReactElement {
  const [count, setCount] = useState(0);

  return <button onClick={() => { setCount((prev) => prev + 1); }} type="button">Click {count}</button>;
}
```
3. export the button component in the `index.ts` file:
``` typescript
export * from "./card";
export * from "./button";
```
4. That's it, start the  dev mode and you'll see the error.

**Comment by chris-olszewski** [comment]
This isn't an issue with `turbo`, but a misuse of server/client components. Even if you take `turbo` out of the equation completely and opt out of workspaces you can reproduce the error by exporting an unmarked client component from a module that isn't marked with `"use client"`:
```
[0 olszewski@chriss-mbp] /tmp/use_client/apps/web $ cat app/ui/button.tsx
import type { ReactElement} from 'react';
import { useState } from 'react';

export function Button(): ReactElement {
  const [count, setCount] = useState(0);

  return <button onClick={() => { setCount((prev) => prev + 1); }} type="button">Click {count}</button>;
}
[0 olszewski@chriss-mbp] /tmp/use_client/apps/web $ cat app/ui/index.tsx 
// component exports
export { Card } from "./card";
export { Button } from "./button";
[0 olszewski@chriss-mbp] /tmp/use_client/apps/web $ head app/page.tsx 
import Image from "next/image";
import { Card } from "./ui";
import styles from "./page.module.css";

function Gradient({
  conic,
  className,
  small,
}: {
  small?: boolean;
[0 olszewski@chriss-mbp] /tmp/use_client/apps/web $ yarn build
yarn run v1.22.19
$ next build
Failed to compile.

./app/ui/button.tsx
ReactServerComponentsError:

You're importing a component that needs useState. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

   ╭─[/private/tmp/use_client/apps/web/app/ui/button.tsx:1:1]
 1 │ import type { ReactElement} from 'react';
 2 │ import { useState } from 'react';
   ·          ────────
 3 │ 
 4 │ export function Button(): ReactElement {
 5 │   const [count, setCount] = useState(0);
   ╰────

Maybe one of these should be marked as a client entry with "use client":
  ./app/ui/button.tsx
  ./app/ui/index.tsx
  ./app/page.tsx


> Build failed because of webpack errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Is there a reason why you are avoiding marking your component with `"use client"` even though it is a client component? If it's a third party component, you could [follow these docs](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#using-third-party-packages-and-providers) to correctly mark it as such.

**Comment by dwilt** [comment]
@dnguyenfs I ran into this too. I bet you're using the default turbrepo setup when you create a new repo and you're using the pattern that was setup in the `ui` folder. What is a bit misleading here IMO, unless I'm doing something wrong, is that because the `ui/index` folder is exporting _all_ of the components that you have in the `ui` package, if _any_ of them use `useState` (or any other client-component specific logic), you'll get this error since the way the default turbo is setup, _all_ of the components get imported into the application from `ui`. 

I'm a bit confuse on what the best way to import from the `ui` package should be if we aren't supposed to do barreling (an `index` file which exports everything).

**Comment by dwilt** [comment]
@dnguyenfs figured out a better solution: `export` the components you want instead of using  the `index.ts` file: https://turbo.build/repo/docs/getting-started/create-new#understanding-imports-and-exports

this will prevent them from all being imported where you might not be intending to. Plus it makes tree shaking possible.

**Comment by manavm1990** [comment]
> @dnguyenfs figured out a better solution: `export` the components you want instead of using the `index.ts` file: https://turbo.build/repo/docs/getting-started/create-new#understanding-imports-and-exports
> 
> this will prevent them from all being imported where you might not be intending to. Plus it makes tree shaking possible.

I just wasn't sure why this way (which adds more work when one has already created an `index.ts` - thanks to ChatGPT for helping rework this!) matters. Why can't Next just import things as needed and within the appropriate client-server realms regardless of `"exports"` or an `index.ts`?
