### ISSUE TITLE
keep cache when the `verison` field changed in package.json

### ISSUE THREAD

**Issue by chnliquan** [vercel/turbo#6131]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

By default, Turborepo will not cache when the package.json changed, lets say i have 100 sub-repos in one monorepo, the 100 sub-repos shared same version, it will change the version field and turborepo will run task 100 times when update the version every time even if my codebase(src) has not changed

### Describe the solution you'd like

Allow users to customize which field changes will not affect cache hits

### Describe alternatives you've considered

Allow users to customize which field changes will not affect cache hits

**Comment by chris-olszewski** [comment]
Closing in favor of #6131 since no longer using all of `package.json` in a task's inputs would need to be opt-in.
