### ISSUE TITLE
Group task logs in CI

### ISSUE THREAD

**Issue by weyert** [vercel/turbo#6188]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

I would like to be able to visually group logs in CI so its easier to keep track of logs or to expand/collapse

### Describe the solution you'd like

I would like to have support for some special logging instructions that are supported in CI solutions, the most popular ones are:

Gitlab:
Requirement: None

start: `section_start:${Math.floor(Date.now() / 1000)}:${taskName}\\r\\e[0K${taskName}\r\n`
end: `section_end:${Math.floor(Date.now() / 1000)}:${taskName}\\r\\e[0K`

Teamcity:
start: `##teamcity[blockOpened name='${taskName}']
`
end: `##teamcity[blockClosed name='${taskName}']`

Github Actions:
Requirement: None

start: `::group::${taskName}\r\n`
end: `::endgroup::\r\n`

Travis:
start: `travis_fold:start:${taskName}\r\n`,
end: `travis_fold:end:${taskName}\r\n`,

Azure:
start: `##[group]${taskName}\r\n`,
end: `##[endgroup]\r\n`,

### Describe alternatives you've considered

None

<sub>[TURBO-1517](https://linear.app/vercel/issue/TURBO-1517/group-task-logs-in-ci)</sub>

**Comment by mehulkar** [comment]
Thanks for the request, I'll take it to the team to discuss priority!

**Comment by weyert** [comment]
@mehulkar Yeah, you appear to already do it for GitHub Actions so why not for the other popular CIs

**Comment by mehulkar** [comment]
It would make sense to me to add support for these https://github.com/vercel/turbo/blob/main/cli/internal/ci/vendors.go (and maybe remove some from the list). But since we don't actively use these CI vendors, we'll probably be running blind with the syntax (e.g. if it changes)

**Comment by mehulkar** [comment]
We talked about this and want to add support. Happy take contributions if anyone is interested to PR, but it's in our backlog

**Comment by cymruu** [comment]
I'm interested in tackling this task. Upon reviewing the code, I've found out that the code responsible for generating groups in the GitHub Actions output, is currently implemented in Go codebase. However, there's no corresponding implementation in the Rust codebase. 
Should this feature be implement this feature in Go, Rust, or in both languages?

**Comment by weyert** [comment]
@cymruu Thanks that would be great :)

**Comment by mehulkar** [comment]
@cymruu I would start only with Rust. From what I understand the port is very nearly done

**Comment by mstuercke** [comment]
@gajus 
> Does anyone know how to disable this?

Do one of the following:
- set the environment variable: `TURBO_LOG_ORDER=stream` ([Turbo docs](https://turbo.build/repo/docs/reference/system-variables))
- add the option `--log-order=stream` to the command ([Turbo docs](https://turbo.build/repo/docs/reference/command-line-reference/run#--log-order))
