### ISSUE TITLE
Add Example Turborepo project with Vue3 or Nuxt

### ISSUE THREAD

**Issue by hasan75** [vercel/turbo#6216]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Hello,
I have explored the turbo repo documentation and examples and I have found that the documentation is based on NextJs and I couldn't find any example with NuxtJs or Vue3.

### Describe the solution you'd like

It would be great if any example with Nuxt Js or Vue 3 can be added.
Documentation with Vue or Nuxt Js would be a great enhancement in the Turbo Doc.

### Describe alternatives you've considered

I have tried to run a repo with NuxtJs but couldn't finish it. 
Thanks.

**Comment by mehulkar** [comment]
Hi there, thanks for the request. We're open to contributions but can't reasonably maintain an example for every framework out there. I'll take this to the team and see if there we can invest time in this! cc @anthonyshew

**Comment by Neosoulink** [comment]
Hi @mehulkar, I like the idea

Is there a team working on this issue? I'll be glad to contribute on this one

**Comment by anthonyshew** [comment]
Happy to have a Nuxt example!

@Neosoulink, if you'd like to make a PR for this and request my review, we can work on it. Just let me know so I'm not duplicating your work.

Otherwise, I'll hop on it in the coming weeks while I work on freshening up our other examples.

**Comment by Neosoulink** [comment]
Hi @anthonyshew, yes sure. I can start working on it and create a PR ASAP, (of course, I'll request your review)

**Comment by Neosoulink** [comment]
**UPDATE**:
Hey @anthonyshew, when you are available, I'll be glad to work with you on this example addition!
