### ISSUE TITLE
[turborepo] Turbo error: unable to find any locator for array-source@0

### ISSUE THREAD

**Issue by MaxwellLevenson** [vercel/turbo#6243]
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

Running `yarn turbo prune --scope foo` triggers an error:
```
➜  turbo_repro git:(main) yarn turbo prune --scope foo
Generating pruned monorepo for foo in /Users/maxlevenson/turbo_repro/out
 - Added foo
Turbo error: unable to find any locator for array-source@0
```

### Expected Behavior

The prune command completes without error.

### To Reproduce

Clone this minimal reproducible example https://github.com/MaxwellLevenson/turbo-prune-err-repro and run `yarn turbo prune --scope foo` from the repo root.

### Reproduction Repo

https://github.com/MaxwellLevenson/turbo-prune-err-repro

**Comment by chris-olszewski** [comment]
Closing this in favor of #6232, but I am extremely thankful for the reproduction. It makes my life a lot easier
