### ISSUE TITLE
[turborepo] turbo run build fails on Vercel because a <KEY> is not listed as a dependency in turbo.json (but .env is)

### ISSUE THREAD

**Issue by ilyagru** [vercel/turbo#6271]
### What version of Turborepo are you using?

1.10.15

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When using the eslint plugin and declaring the env dependencies like below, Vercel deployment fails because of the error:

`:build: ...  Error: ..._KEY is not listed as a dependency in turbo.json  turbo/no-undeclared-env-vars`.

From what I can see is that when using `"globalDotEnv": [".env"]` locally, it succeeds because the `.env` file is there, so it can detect all environment variables defined in the file. But on Vercel there is no such a file, all variables are provided directly one by one. Vercel doesn't use `.env` files under the hood?

What would be a good solution to this? Having added `"globalDotEnv": [".env"]` compoaring to listing variables one by one is great because it eliminates the need to keep it in sync manually and because there is the single source of truth.

Probably related link - https://turbo.build/repo/docs/core-concepts/caching/environment-variable-inputs#invisible-environment-variables

Using `eslint-config-turbo` along wth `turbo.json` file:
```json
{
  "$schema": "https://turbo.build/schema.json",
  "globalDotEnv": [".env"],
  "globalEnv": ["NODE_ENV", "ANALYZE"],
  "globalDependencies": [".env", "**/.env.*local", "**/*.tsconfig.json"],
  "pipeline": {
    "dev": {
      "cache": false,
      "persistent": true,
      "dotEnv": [
        ".env.development.local",
        ".env.local",
        ".env.development",
        ".env"
      ]
    },
    "build": {
      "dependsOn": ["^build"],
      "outputs": [".next/**", "public/**", "!.next/cache/**", "cdk.out/**"],
      "dotEnv": [
        ".env.production.local",
        ".env.local",
        ".env.production",
        ".env"
      ]
    },
    "start": {
      "dependsOn": ["^build"],
      "outputs": [".next/**", "!.next/cache/**"],
      "persistent": true
    },
    "test": {
      "dotEnv": [".env.test.local", ".env.test", ".env"]
    },
    "lint": {},
    "format": {},
    "typecheck": {}
  }
}

```

### Expected Behavior

No error if all the environment variables are correctly added in the projects's settings on Vercel.

### To Reproduce

1. Init turborepo with the config above.
2. Configure eslint with eslint-config-turbo.
3. Add .env file with some example variables.
4. Use variables in `apps/web/`
5. Deploy `apps/web` to Vercel.

**Comment by gsoltis** [comment]
This is working as intended. Your application depends on environment variables, which are supplied locally via `.env`, but there is no `.env` file when deploying on Vercel. So you'll need to list the variables that your application depends on in `env`.

**Comment by ilyagru** [comment]
I see, thank you for the answer @gsoltis. Something to note, that with this implementation, if a Next.js project is deployed to Vercel, the "globalDotEnv" option is useless/confusing because it works locally but doesn't on Vercel, and in any case it is necessary to list the variables in the "env".

**Comment by JKarlavige** [comment]
> I see, thank you for the answer @gsoltis. Something to note, that with this implementation, if a Next.js project is deployed to Vercel, the "globalDotEnv" option is useless/confusing because it works locally but doesn't on Vercel, and in any case it is necessary to list the variables in the "env".

Running into this now as well while converting our repo to a Turborepo. Is there any documentation or production examples of how the env variables should be configured? The [docs page](https://turbo.build/repo/docs/handbook/environment-variables) only notes how to configure `.env` files, but not seeing anything specific for having to setup individual env variables.

**Comment by gsoltis** [comment]
I agree it's not an ideal setup. For an explanation behind the complexity, consider the two scenarios:
 1. Local development. `turbo` executes a task, which in turn loads env vars from a `.env` file which is not checked in to `git`. `turbo` doesn't see the env vars, unless it also loads that same file, and it needs to be told explicitly about that file, since it is not tracked via source control.
 2. Vercel or other production setup. The environment already has the environment variables loaded, but there is no indication of which environment variables are relevant to `turbo`, because there is no `.env` file present. `turbo` cannot just grab every environment variable, as some are machine-specific, and others change on every invocation (e.g. `BUILD_ID` or similar)

This setup results in there being two ways to tell `turbo` about environment variables that matter: 
 1. Check a particular `.env` file
 2. Look for an explicit set of env vars already set (via [env](https://turbo.build/repo/docs/reference/configuration#env) in `turbo.json`)

**Comment by JKarlavige** [comment]
That makes sense, thanks @gsoltis. I also found [this section](https://turbo.build/repo/docs/core-concepts/caching/environment-variable-inputs) in the docs which also helped me understand how this works.

I went ahead and created a separate `turbo.json` in a specific app and added the `env` property within that config.
