### ISSUE TITLE
[turborepo] build and start fails

### ISSUE THREAD

**Issue by SantoshKumarRavi** [vercel/turbo#6272]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

Error I got  in terminal: 

```
server:db:generate: Failed to mark outputs as cached for server#db:generate: rpc error: code = Unavail
able desc = failed to write cookie file The system cannot find the path specified. (os error 3)
```

i dont know if it is specific to windows.
i given all permission to turbo folder.

still turbo build throwing this error and 
shows successfull also.

when i tried turbo run start, it is exiting.

may i know what is the reason ?

### Expected Behavior

need to start app without exiting 

### To Reproduce

i have no idea how to reproduce.
i am using windows 10,
node -v 18.16.0
npm -v 9.5.1

my question is same as this  stack-overflow Question
https://stackoverflow.com/questions/73620820/turborepo-starts-webserver-and-then-immediately-successfully-exists

<sub>[TURBO-1550](https://linear.app/vercel/issue/TURBO-1550/[turborepo]-build-and-start-fails)</sub>

**Comment by gsoltis** [comment]
Thanks for the report, I'll take a look and see if I can figure out what's up.

**Comment by arlyon** [comment]
Hi @SantoshKumarRavi are you able to update turbo, run the example again, and report what issue you get?

**Comment by vinicius507** [comment]
The same issue started happening to me after updating from 1.11.3 to 1.12.1 while using Vite

**Comment by xmlking** [comment]
process exits without errors
<img width="845" alt="image" src="https://github.com/vercel/turbo/assets/627951/8d4e42bf-2fc7-458b-b623-96fb674e6ceb">

**Comment by vinicius507** [comment]
> The same issue started happening to me after updating from 1.11.3 to 1.12.1 while using Vite

Upgrading to 1.12.2 fixed the issue (don't forget `persistent: true`)

**Comment by arlyon** [comment]
Yes, persistent: true is important for these types of commands. Dev servers will sometimes report a successful exit code when quitting which, unless marked as persistent, will cause turbo to cache it. Not what you want! 1.12.2 had a change that should help here, if I get another confirmation that that resolves it I will close this issue.
