### ISSUE TITLE
Not able to run the turbo project with any of the package managers

### ISSUE THREAD

**Issue by sudo-shihab** [vercel/turbo#632]
### What version of Turborepo are you using?

@latest

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn ..

### What operating system are you using?

Windows 

### USER :

* Platform : 'Windows 11',
* Version :  '10.0.22000' ,
* Processor : 'AMD',
* OS Architecture    : 'x64'
* OS type : 'Windows NT',
#### current versions of my package managers 
* npm - 6.14.8
* yarn - 1.22.17
* pnpm - 6.28.0

### ISSUE :
Tried running  `npx create-turbo@latest` with `npm` , `pnpm` and `yarn`

*  With `Yarn`  the scaffolding itself is aborted in the middle ( tried even updating yarn, no luck )
*  With `NPM` the scaffolding is successful ( node_modules are installed)  but I am not able to run the project with `npm run dev` or with `npm run build`  (aborts the process with an error within the terminal )
* with `PNPM` the scaffolding seems to show success but I observed that  node packages are not installed by default , however tried to install the packages manually but no luck and hence `pnpm run dev` and `build` fails here too

### Running project post the scaffolding phase using * NPM *   [ `npm run dev` or `npm run build` is resulting in same error shown below ]
![turbo-npm-err](https://user-images.githubusercontent.com/58358409/151551816-717ac767-164e-454d-ae99-03a12b3d77f8.png)

#### Error 1 :  Dependency installation phase is skipped within the turbo generator CLI , refer the image below .

![turbo-pnpm-err1](https://user-images.githubusercontent.com/58358409/151552787-6458e06f-ed0d-4fda-8866-86157bcae2f6.png)

#### Error 2 :   'node_modules` folder is absent by default and I am not able to manually install the packages also ,  now forget about running dev server :/
![turb-pnpn-err2](https://user-images.githubusercontent.com/58358409/151553074-4dc403e2-f8d2-40c0-97c9-a713486a9b50.png)

#### Dependency Installation process aborts within the scaffolding phase itself  
![turbo-yarn-err](https://user-images.githubusercontent.com/58358409/151554781-646d4edf-35e6-4660-8e68-99b32c91e026.png)

### Expected Behavior

*  `npx create-turbo@latest` cmd should produce same scaffolding structure across all the package manager `pnpm` , `yarn` , `npm` , but seems like the project structure is broken and inconsistent.
*  after running `npx create-turbo@latest`  with any of the package manager, one should be able to successfully run the `npm scripts ` using the respective package manager preferred in the project.

## Please refer to the 'Describe the Bug` section , I have uploaded each scenario with the screenshots .

* run `npx create-turbo@latest <project-name>` within the terminal using PNPM or NPM or YARN
* If you  scaffolding using `NPM` , pckg deps installation is shown success and we can see `node_modules` folder
     *  cd to project-name
     *  try running `npm run dev` or `npm run build`
     *  npm script is  aborted with some error
     
* If you are scaffolding  using `PMPM` , scaffolding status is shown success but we cannot see `node_modules` folder inside the project.
     * cd to project-name
     *  try to run `npm run dev` or `npm run build`
     *  npm script is aborted saying ` did you mean pnpm install`
     *  try to install it manually using `pnpm install` , but hard luck

* If you are scaffolding  using `YARN` , 
     *  Process aborts within the scaffolding phase itself  [ please refer tot he images uploaded in the `describe the bug` section.]

**Comment by jaredpalmer** [comment]
thanks for the writeup investigating on my windows machine

**Comment by anthonyshew** [comment]
This looks stale! If you're still seeing this problem, please open a new issue.
