### ISSUE TITLE
[turborepo] Docs pages not found

### ISSUE THREAD

**Issue by danger-ahead** [vercel/turbo#6323]
### What version of Turborepo are you using?

NA

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Linux

### Describe the Bug

https://turbo.build/pack/docs/comparisons/vite
https://turbo.build/pack/docs/comparisons/webpack

these two pages in docs are non existent.

### Expected Behavior

The pages should be there or the routing should be fixed.

### To Reproduce

NA

**Comment by tknickman** [comment]
This has been fixed. Thanks for the report!

Check out this PR for more details / reasoning: https://github.com/vercel/turbo/pull/6268
