### ISSUE TITLE
[turborepo] Cannot access ENV variable from React Vite

### ISSUE THREAD

**Issue by ThinhLe183** [vercel/turbo#6345]
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

I created an env variable with the prefix `VITE_` and set it up as the document instruction.
My backend app could access these env var via **process.env** but my frontend app didn't show any variable that I defined.

### Expected Behavior

The env variable with VITE_ prefix can be accessed via import.meta.env

### To Reproduce

1. Create React app with Vite
2. Structure it with turborepo
3. Create a global .env file
4. Create an env variable with VITE_ prefix
5.  Access that variable via import.meta.env

**Comment by mehulkar** [comment]
This does not seem related to turborepo, rather it seems that your app needs to [use `.env` files](https://vitejs.dev/guide/env-and-mode.html#env-files). If you could provide a repo and show how you think this is related to Turborepo, we may be able to figure out whether this is a bug or not. 

Closing down, but we can re-open if it becomes clear that it's a turborepo issue.

**Comment by Roman-Maksimov** [comment]
Vite looks for the .env files in the projects _rootDir_. Specifically in the turborepo architecture the vite projects usually stored under the _apps/\<project\>_ folder. If you keep the _.env_ filed in the repository root, you have to specify an **envDir** path in the _vite.config.js_

```javascript
// apps/<project>/vite.config.js

export default defineConfig({
  ...
  envDir: '../../',
});
```

Alternatively you can place you .env files right under the _apps/\<project\>/folder_.

Also don't forget to setup the turbo config https://turborepo.com/docs/crafting-your-repository/using-environment-variables properly.
