### ISSUE TITLE
[turborepo] - Error preparing engine: Could not find the following tasks in project

### ISSUE THREAD

**Issue by magicspon** [vercel/turbo#6358]
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Hello,

I'm seeing the follow error when running `turbo run link` task via lint-staged

```
✖ turbo run lint:
 ERROR  run failed: error preparing engine: Could not find the following tasks in project: _path_to_repo_/.lintstagedrc.js, _path_to_repo/apps/cms/src/globals/Seo.ts, _path_to_repo/apps/cms/src/seed.ts, _path_to_repo/apps/cms/src/singles/About.ts, _path_to_repo/apps/cms/src/singles/Home.ts, _path_to_repo/apps/web/src/app/page.tsx, _path_to_repo/packages/config/eslint/react-internal.js, _path_to_repo/packages/ui/index.tsx
```

yarn run lint - works as expected
turbo run lint - works as expected

ref: https://github.com/vercel/turbo/issues/3918

### Expected Behavior

Shoud work when running via lint-staged

### To Reproduce

Clone this repo
Change any js/ts file
`git add .`
`git commit -m "refactor: test` // or `npx lint-stage` 

### Reproduction Repo

https://github.com/magicspon/next-payloadcms-mono

**Comment by axelhamil** [comment]
Try directly with a tool command like:
```js
module.exports = {
	'*.{js,ts,tsx}': 'eslint --fix',
}
```

And I use this tsconfig.json at the project root:
```json
{
  "extends": "./packages/tsconfig/base.json",
  "include": ["."],
  "exclude": ["dist", "build", "node_modules"]
}
```

**Comment by mehulkar** [comment]
This is most likely an issue with how lint-staged executes its script. I cloned your repo and updated `.lintstagedrc.js` to:

```diff
module.exports = {
	'*.{js,ts,tsx,css}': 'yarn run format',
-	'*.{js,ts,tsx}': 'turbo run lint',
+	'*.{js,ts,tsx}': 'turbo run lint --',
}
```

This got me a litle further, but I still get a lint failure, I'm not sure if that's still part of this configuration or something else

**Comment by magicspon** [comment]
@mehulkar that's one issue down... now i'm getting:

```
throw new Error("> Couldn't find any `pages` or `app` directory. Please create one under the project root");
```

argh!

**Comment by mehulkar** [comment]
Yeah I got the same error, I'm not sure. I think this will require some understanding of what lint-staged does and how it executes its command. Since `turbo run lint` works fine, I'm inclined to believe this is not a turbo issue. Maybe hop into [Discord](https://turbo.build/discord) with this?

**Comment by mehulkar** [comment]
I'm going to close this down as it appears to be unrelated to turbo. Please let me know if I'm mistaken!

**Comment by mehulkar** [comment]
@ngrcode I didn't find a solution, but I think you will need to dig into how `lint-staged` to find the right configuration
