### ISSUE TITLE
[turborepo] mdx files don't cause rebuild

### ISSUE THREAD

**Issue by versecafe** [vercel/turbo#6365]
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

## MDX Files Not Triggering Rebuild
mdx files are flagged as differences but then do not trigger a rebuild, this causes systems like Nextra + NextJS to never build new pages or update content as the entire system is _meta.json and file.mdx

<img width="1445" alt="image" src="https://github.com/vercel/turbo/assets/147033096/91428998-7ee3-407c-8649-0ef1d1471a3b">

Solving this requires running without cache, or when using vercel forcing a redeploy and selecting not to reuse prior build cache which then prevents imported workspace packages from being cached forcing them to be rebuilt.

<img width="1445" alt="image" src="https://github.com/vercel/turbo/assets/147033096/e6c59aa9-3952-439e-853b-81241d582b7c">

### Expected Behavior

Modifying MDX files should trigger package/app rebuild or a flag option in turbo.json in the project or pacakge should allow for an optional flag to cause this behaviour in a format such as
```
{
     rebuild : {ts,tsx,md,mdx}
}
```

### To Reproduce

1. Create a turborepo & copy in a Nextra template
```
turbo gen workspace --copy https://github.com/shuding/nextra-docs-template
turbo build
cd ./apps/nextra-docs-template
pnpm start
```
2. view it, then modify one of the mdx files such as index, run turbo build, and view it again and it will
not have updated even if when using pnpm dev you can see the new version.

**Comment by tknickman** [comment]
Hey @versecafe, thanks for the report. I took a look at this one and was unable to reproduce, are you adding the nextra docs template to an existing turborepo monorepo? If so, could you share your `turbo.json`?

**Comment by anthonyshew** [comment]
Hey, @versecafe, this is a problem in Nextra that I've experienced, too. It has its own internal webpack cache that I think doesn't invalidate correctly. I've had this problem locally, on Vercel, with Turborepo, and without Turborepo.
