### ISSUE TITLE
[turborepo] `Error: cannot find binary path` when running `turbo build` (with the `with-react-native-web` starter)

### ISSUE THREAD

**Issue by MAXOUXAX** [vercel/turbo#6392]
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

After installing Turbo globally and trying to build a starter template using the `npm run build` / `turbo build` command, this error message shows up:
```
Error: cannot find binary path
```

### Expected Behavior

I expected the command to work as intended after installing Turbo from the official docs using the `npm install turbo --global` command.

### To Reproduce

1. Deploy a project using `https://vercel.com/templates/next.js/turborepo-react-native`
2. Run `npm i`, you should get an error because npm is unable to resolve the dependency tree (the starter is broken, but there's other issues dedicated to that problem)
3. Update versions of dependencies in all the package.json files
4. Run `npm i`, it should install as expected
5. Run `npm run build`, it should run `turbo build` and run into the issue
6. Try installing Turbo globally using `npm install turbo --global` and run `turbo build`, should get the same error

**Comment by arlyon** [comment]
Hello, apologies for the delay I wanted to give this issue some proper attention. First is the example not working. For some reason our versions have drifted but I am opening a PR to address this. The second one is the issue of the missing binary, which will also be triggered by global turbo. May I ask what version of turbo you have in your lockfile?

**Comment by mehulkar** [comment]
Closing this out in favor of https://github.com/vercel/turbo/issues/6015, since react-native-web example seems generally broken
