### ISSUE TITLE
[turborepo] Update to 1.10.16 fails

### ISSUE THREAD

**Issue by teddis** [vercel/turbo#6407]
### What version of Turborepo are you using?

1.10.13

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

The recommended update command `npx @turbo/codemod update` is failing. 

```
> npx @turbo/codemod update
? Where is the root of the repo to migrate? .
No codemods required to migrate from 1.10.13 to 1.10.16 

Upgrading turbo from 1.10.13 to 1.10.16 (no codemods required) 

Migration failed
Unable to determine upgrade command
```

### Expected Behavior

Update works.

### To Reproduce

Repeat update command.

**Comment by chris-olszewski** [comment]
A few pieces of information that can help me debug/get a reproduction:
 - If you have `turbo` installed globally what the output of `turbo bin` is when run from where you're performing the migration
 - Output of `yarnpkg --version` from migration directory
 - Relevant sections of `package.json`: `workspaces` field and how `turbo` is declared as a dependency in either `dependencies`/`devDependencies`
