### ISSUE TITLE
[turborepo] Turborepo react-native starter doesn't work out of the box

### ISSUE THREAD

**Issue by dgrcode** [vercel/turbo#6412]
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

It's using expo SDK 45, which is already deprecated (based on [this](https://docs.expo.dev/workflow/upgrading-expo-sdk-walkthrough/)). In fact SDK 46 is deprecated as well

### Expected Behavior

Following the instructions [here](https://vercel.com/templates/next.js/turborepo-react-native) and running the project with Expo Go should give me a working app

### To Reproduce

Run `npx create-turbo@latest -e with-react-native-web`
Try to run it with Expo Go. You'll get a message saying only SDK 47, 48 and 49 are supported.

**Comment by mehulkar** [comment]
#6015

**Comment by dgrcode** [comment]
woops sorry, I missed that one
