### ISSUE TITLE
[turborepo] not possible to pass `--args` containing space to `turbo gen`

### ISSUE THREAD

**Issue by karfau** [vercel/turbo#6430]
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Running `pnpm turbo gen generator --args 'containing spaces'` uses `containing` as the input for the first propmt and `spaces` as the input for the second promt, instead of passing `containing spaces` to the first one.

The position is not relevant, I'm not able to pass a value containing spaces to a single prompt input.
I also tried double quotes, wrapping single quotes by double quote, wrapping double quotes by single quotes, some escaped quotes, but nothing worked.

### Expected Behavior

Pass all parts of the argument that are wrapped by quotes to the propmt at that position.

### To Reproduce

1.  `pnpm turbo gen`
2. confirm to add an example Javascript generator
3. `pnpm turbo gen example --args test .md "contains spaces"`
4. grep 'contains spaces' test.md (fails, only "contains" is in the title)

or 

3. `pnpm turbo gen example --args 'file name' .md title`
> `>>> The "type" prompt did not recognize "name" as a valid list value (ERROR: invalid choice)`

**Comment by tknickman** [comment]
Thanks for the report @karfau, will take a look.
