### ISSUE TITLE
[turborepo] Next.js package using CSS modules makes TypeScript angry

### ISSUE THREAD

**Issue by heloineto** [vercel/turbo#6435]
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

Following the template provided by the docs, I'm building a package that can only be used with Next.js. Even though using CSS modules in that package works (thanks to Next.js transpiling), TypeScript still gets angry about it.

```js
// next.config.js
module.exports = {
  transpilePackages: [
    'my-ui-package',
  ],
};
```

In the `my-ui-package`:

```ts
// my-component.tsx
import classes from './my-component.module.css';

export function MyComponent() {
  // ...
}
```

TypeScript throws the following error:

```
Cannot find module './my-component.module.css' or its corresponding type declarations.ts(2307)
```

### Expected Behavior

Current behaviour: Using CSS Modules in a Next.js package does not work out of the box.
Expected behaviour: Using CSS Modules in a Next.js package works of the box.

### To Reproduce

1. Create a new project from the Next.js template in the [documentation](https://turbo.build/repo/docs/getting-started/from-example)
2. Use CSS modules inside inside the `ui` package (default package from the template)
3. Note that, despite the code working, TypeScipt throws an error

### Reproduction Repo

https://github.com/heloineto/turborepo-nextjs-css-modules-bug

**Comment by chris-olszewski** [comment]
This seems to be an issue with the Typescript config more than `turbo` itself, unless I'm misunderstanding.

Can you provide how you're running your type checking in your repro? I'm seeing a differing warning from running `pnpm build` in `apps/web`:
```
./app/page.tsx:129:17
Type error: Type '{ children: string; className: string; href: string; key: string; title: string; }' is not assignable to type 'IntrinsicAttributes & { title: string; children: ReactNode; href: string; }'.
  Property 'className' does not exist on type 'IntrinsicAttributes & { title: string; children: ReactNode; href: string; }'.

  127 |       <div className={styles.grid}>
  128 |         {LINKS.map(({ title, href, description }) => (
> 129 |           <Card className={styles.card} href={href} key={title} title={title}>
      |                 ^
  130 |             {description}
  131 |           </Card>
  132 |         ))}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by heloineto** [comment]
@chris-olszewski Oh, this is an unrelated error as a result of me changing the props of the Card component. I'm sorry for that, it's fixed now.

But note that the original error does not happen on `pnpm build` because the `ui` package has no build script.

As of my understanding, the package is imported as is, and then build on the Next.js project importing it. The error is in TypeScript not understanding that. There's also an ESlint error related to the fact that "classes" has an any type.

**Comment by heloineto** [comment]
I would guess this could be fixed by changing the example project to either:

1. Adding a build step to the package that handles CSS modules and other concerns (this would be great because the package could be used outside Next.js)
2. Configuring TypeScript so that it understands that it is in a "Next.js context" and CSS modules are fine.

But I have no idea on how to do either.

**Comment by waellaataoui** [comment]
Any updates here? I'm having the same issue with SASS modules

**Comment by MalekBouba** [comment]
Up!
same issue with SCSS modules.

**Comment by chris-olszewski** [comment]
Closing as I believe this is a configuration issue that's outside of `turbo`'s scope. I found https://github.com/vercel/next.js/issues/9690 which seems to provide a solution to using CSS modules with TS.

Feel free to reopen if I misunderstood and this is something directly related to use of `turbo` when running the tasks.

**Comment by ajrussellaudio** [comment]
@chris-olszewski I think this should be reopened.

It may be a config issue, but it's a config issue with the _default_ turbo settings when running `npx create-turbo@latest` and trying to import a CSS module in `packages/ui/src/button.tsx`. [Minimal repro here](https://github.com/ajrussellaudio/turbo-css-modules-min-repro)

The [Turborepo docs](https://turbo.build/pack/docs/features/css) state:

> Turbopack handles CSS Modules out-of-the-box. Any file with a .module.css extension will be considered a CSS module, and you can import it into a JavaScript or TypeScript file...

But that isn't true, and that I think is the issue here.

**Comment by ahkhanjani** [comment]
> @chris-olszewski I think this should be reopened.
> 
> It may be a config issue, but it's a config issue with the _default_ turbo settings when running `npx create-turbo@latest` and trying to import a CSS module in `packages/ui/src/button.tsx`. [Minimal repro here](https://github.com/ajrussellaudio/turbo-css-modules-min-repro) with the same error as OP described at the top of this thread.
> 
> The [Turborepo docs](https://turbo.build/pack/docs/features/css#css-modules) state:
> 
> > Turbopack handles CSS Modules out-of-the-box. Any file with a .module.css extension will be considered a CSS module, and you can import it into a JavaScript or TypeScript file...
> 
> But that isn't true, and that I think is the issue here.

I agree with this. I'm having trouble importing a CSS module in a package, not a Next.js app.

**Comment by morkro** [comment]
I am experiencing the same issue. I simply did `npx create-turbo@latest` with all default settings and getting this error.

```
Cannot find module './button.module.css' or its corresponding type declarations.ts(2307)
```

**Comment by najwer23** [comment]
same

**Comment by mfaux** [comment]
The [typescript-plugin-css-modules](https://www.npmjs.com/package/typescript-plugin-css-modules) package fixed this issue for me.

**Comment by najwer23** [comment]
i decided to move on and i did my own monorepo with storybook and vite as I only focus on React components. 
we support css modules is a big lie

I hate lying
