### ISSUE TITLE
EMFILE: too many open files when runing dev mode

### ISSUE THREAD

**Issue by ezeamin** [vercel/turbo#6458]
Hi. I'm building a monorepo project using TurboRepo. I have 13 packages and 2 apps, so not so many files, in comparison to other gigantic monorepos. This error started happening when I created the 2nd app, crashing at the moment it wants to start. 

The error is shown at the 2nd app folder ("backoffice-psae"), when trying to import a package ("ui") that imports another package ("hooks") that imports a library ("react-hook-form"). The whole error: 

```shell 
Error: EMFILE: too many open files, open 'C:\Users\Amin\Documents\Codigo\PJ\sistemas-judiciales-monorepo\apps\backoffice-psae\node_modules\ui\node_modules\hooks\node_modules\react-hook-form\dist\utils\isWeb.d.ts'
```

@weyert commented on this 3 weeks ago in [#986](https://github.com/vercel/turbo/issues/986#issuecomment-1780206735_):

> I have tried `turbowatch` but it appears to watch the whole monorepo which I don't think right? I would expect it to watch any input that `turbo` itself considers? E.g. why would it need to watch `node_modules` directories?
>
> I keep getting the error `Error: EMFILE: too many open files, watch` when running it based on the example given by @mattieb 
>
> I have to admit my monorepo is pretty big; based on the `tree` 60.000 files or via `git ls-files` 15.000

Needless to say, my project is by a big difference smaller, listing 156 files with `git ls-files`. In reality, counting node_modules, there are 47.549 files, still smaller than @weyert 's, however a lot in comparison to his 15.000 tracked files...

The only way I've found to workaround this issue is deleting the 2nd app folder. Not even runing dev mode with --filter and only the 1st app. Of course, not a solution. It throws away the whole point of creating a monorepo.

Call stack:
```shell 
✓ Compiled /page in 4.3s
web:dev:  ⨯ ModuleBuildError: Error evaluating Node.js code
web:dev: Error: EMFILE: too many open files, open 'C:\Users\Amin\Documents\Codigo\PJ\sistemas-judiciales-monorepo\apps\backoffice-psae\node_modules\ui\node_modules\hooks\node_modules\react-hook-form\dist\utils\isWeb.d.ts'
web:dev:     at processIssues (C:\Users\Amin\Documents\Codigo\PJ\sistemas-judiciales-monorepo\node_modules\.pnpm\next@14.0.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-utils\setup-dev-bundler.js:256:23)
web:dev:     at Object.ensurePage (C:\Users\Amin\Documents\Codigo\PJ\sistemas-judiciales-monorepo\node_modules\.pnpm\next@14.0.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-utils\setup-dev-bundler.js:1095:33)
web:dev:     at async DevBundlerService.ensurePage (C:\Users\Amin\Documents\Codigo\PJ\sistemas-judiciales-monorepo\node_modules\.pnpm\next@14.0.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\dev-bundler-service.js:18:20)
web:dev:     at async DevServer.ensurePage (C:\Users\Amin\Documents\Codigo\PJ\sistemas-judiciales-monorepo\node_modules\.pnpm\next@14.0.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:518:9)
web:dev:     at async Object.ensure (C:\Users\Amin\Documents\Codigo\PJ\sistemas-judiciales-monorepo\node_modules\.pnpm\next@14.0.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:164:17)
web:dev:     at async DevRouteMatcherManager.matchAll (C:\Users\Amin\Documents\Codigo\PJ\sistemas-judiciales-monorepo\node_modules\.pnpm\next@14.0.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\future\route-matcher-managers\dev-route-matcher-manager.js:94:13)
web:dev:     at async DevRouteMatcherManager.match (C:\Users\Amin\Documents\Codigo\PJ\sistemas-judiciales-monorepo\node_modules\.pnpm\next@14.0.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\future\route-matcher-managers\default-route-matcher-manager.js:155:26)
web:dev:     at async NextNodeServer.handleCatchallRenderRequest (C:\Users\Amin\Documents\Codigo\PJ\sistemas-judiciales-monorepo\node_modules\.pnpm\next@14.0.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\next-server.js:222:31)
web:dev:     at async DevServer.handleRequestImpl (C:\Users\Amin\Documents\Codigo\PJ\sistemas-judiciales-monorepo\node_modules\.pnpm\next@14.0.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:751:17)
web:dev:  ✓ Compiled /_error in 369ms
web:dev:  ✓ Compiled /favicon.ico/route in 86ms
``` 

### Some relevant info:

Dev command: `env-cmd -f ./.env.development turbo run dev --concurrency 18`

Dev config at `turbo.json`: 
```javascript
"dev": {
      "cache": true,
      "persistent": true,
      "dotEnv": [".env.development"]
    },
``` 

Env:
Windows 11
Node 21.0.0
pnpm 8.9.2
Apps runing with Next.js 14.0.1

I'll be glad to help if any more information is needed. Thanks!

**Comment by ezeamin** [comment]
I updated Node to 21.2.0, but still got the error. 

I removed the `persistent` config at `turbo.json`, and the `--concurrency` 18 from the dev script, but still got the error.

I tried running only 1 app, directly moving my cmd to that folder and runing `pnpm dev` there, and removing from it any connection it may have to the other app (for example, a multizones config that goes in the `next.config.js` file). Still got the error (which is weird, because it isn't running the other app!)

My PC has 16GB of RAM and a 12th Gen Intel i3 processor, so performance shouldn't be a problem.

**Comment by chris-olszewski** [comment]
Can you try running with `--no-daemon` and see if you still get the same error?

**Comment by Yremma** [comment]
> Can you try running with `--no-daemon` and see if you still get the same error?

Hi! I´m on the same team, with the same issue. I tried this and I´m still getting the error

![SS01](https://github.com/vercel/turbo/assets/21195993/f311fab7-3011-4cb0-b738-2b8bb3ceabc3)
![SS02](https://github.com/vercel/turbo/assets/21195993/6584be8f-960a-4f2c-89b9-63dd19a9ed03)

**Comment by ezeamin** [comment]
Hi @chris-olszewski, thanks for your quick reply. Running `dev` directly at `backoffice-psae` gave the same error. The `dev` command here, as well as in `web` but with other port, is `next dev --port 3001 --turbo`. The `turbo` flag was added some days ago at trying to solve this issue, so without it the problem remains.

The first time I had this problem was when creating this new app folder and trying to run it. As I reached nowhere, I checkouted to other branch to keep working on other stuff from `packages` folder. The error was still there, and it stayed until I realized that `.next` and `.turbo` folders, inside `apps/backoffice-psae` remained in the branch I was now working. This was because git didn't track them - normal behaviour. I removed those and everything went on as normal, but with only 1 app. So I've now tried many times to remove and recreate those folders, both from web and from backoffice-psae, and still nothing was usefull. Even in this last step you suggested.

**Comment by chris-olszewski** [comment]
If the issue is there without using `turbo`, then this is an underlying issue with how many files are open when running the dev server. If this issue is also there without the `--turbo` flag it also isn't a Turbopack related issue.

> until I realized that `.next` and `.turbo` folders

`.next` is probably the culprit here. `.turbo` should just have task logs for the workspace.

I'd suggest looking for an existing issue in [vercel/next.js](https://github.com/vercel/next.js) or opening one there would probably be a better place to look for help.
