### ISSUE TITLE
Add a flag to run only the dependencies of a task, but not the task itself

### ISSUE THREAD

**Issue by ari-becker** [vercel/turbo#6460]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Add a flag to `turbo run` to run only the dependencies of a task, but not the task itself.

Use-case: some GitHub Actions expect to run a task by themselves. For example, Chromatic's action: https://www.chromatic.com/docs/github-actions/ will both build a Storybook and deploy it to Chromatic. Our Storybook has various dependencies, such as `build:css`, which must be executed before this task. It would be nice if we could use Turborepo to only run the dependencies of the `build-storybook` task, not the `build-storybook` task itself, since Chromatic's action will run that. In this way, if we add additional dependencies to `build-storybook` in the future in our Turborepo pipeline, CI will continue to just work. Otherwise, if we executed `turbo run build-storybook` before running the Chromatic action, CI would spend time building `Storybook` twice: once by Turbo, and once by the Chromatic action.

Essentially, this should be the opposite of `turbo run --only`. Instead of running only the task and none of its dependencies, it runs the dependencies but not the task.

### Describe the solution you'd like

`turbo run build:storybook --dependencies-only`

### Describe alternatives you've considered

Manually running each dependency before running the GitHub Action, e.g. `turbo run build:css --filter {./packages/foo}...`

**Comment by anthonyshew** [comment]
Does this section (and/or the one below) describe what you're looking for?
https://turbo.build/repo/docs/core-concepts/monorepos/filtering#include-dependents-of-matched-workspaces

Specifically, it sounds like you're wanting:
```
# Build 'my-app's dependencies, but not 'my-app' itself
turbo run build --filter=my-app^...
```

**Comment by ari-becker** [comment]
@anthonyshew the way I understood `--filter=foo^...` is, for the following packages:

`packages/foo/package.json`:
```json
{
  "scripts": {
    "build:css": "...",
    "build:storybook": "..."
  },
  "dependencies": {
    "bar": "workspace:*"
  }
}
```

`packages/bar/package.json`:
```json

{
  "scripts": {
    "build:css": "..."
  }
}
```

and `turbo.json`:

```json
{
  "pipelines": {
    "build:storybook": {
      "dependsOn": ["^build:css", "build:css"]
    }
  }
```

then `turbo run build:storybook --filter=foo^...` will run `bar#build:css` only, because the filter is on the package itself, so it would exclude any of the task's dependencies within the same package. What I'm looking for (`turbo run build:storybook --filter=./packages/foo --dependencies-only`) would run both `bar#build:css` and `foo#build:css`, i.e. including dependencies within the same package.

**Comment by anthonyshew** [comment]
Ah, I see now.

What I'd recommend you do here would be more like:
```json
   // Pseudo-coding the pipelines, adjustments may be needed
    "build:storybook": {
      "dependsOn": ["build:storybook:deps"]
    },
    "build:storybook:deps": {
      "dependsOn": ["^build:css", "build:css"]
    },
    "build:css": {}
 ```
This way, you can run `turbo build:storybook:deps` without that final build step of Storybook (but still have a pipeline to run for the full thing, `turbo build:storybook`).
