### ISSUE TITLE
Extend turbo prune to include full-without-the-target-workspace

### ISSUE THREAD

**Issue by gajus** [vercel/turbo#6480]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

I would like `turbo prune --scope=@contra/app-contra-api --docker` to output an additional directory which includes all files but the files of the target scope.

For context, the purpose of this is to be able to cache dependencies separately from the target workspace.

Consider this Dockerfile:

```Dockerfile
FROM node:21.1-bullseye-slim AS base

RUN \
  npm install --global pnpm@8.9.0 turbo@1.10.15 @roarr/cli@5.12.4

FROM base AS pruner

WORKDIR /srv

COPY . .

RUN turbo prune --scope=@contra/app-contra-api --docker

FROM base AS builder

WORKDIR /srv

COPY --from=pruner /srv/out/json .

RUN pnpm install --frozen-lockfile

COPY --from=pruner /srv/out/full .

SHELL ["/bin/bash", "-c"]

RUN --mount=type=secret,id=env,uid=1987 \
  set -o allexport && \
  source /run/secrets/env && \
  set +o allexport && \
  pnpm turbo run build --filter=@contra/app-contra-api && \
  find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +

# The rest is irrelevant for this example ...
```

With this Dockerfile, every time that `@contra/app-contra-api` workspace is updated _OR_ its dependencies are updated, we have to re-run build the main workspace and its dependencies. However, if there was an additional output `./out/full-without-target-scope-workspace`, then we could do this:

```Dockerfile
FROM node:21.1-bullseye-slim AS base

RUN \
  npm install --global pnpm@8.9.0 turbo@1.10.15 @roarr/cli@5.12.4

FROM base AS pruner

WORKDIR /srv

COPY . .

RUN turbo prune --scope=@contra/app-contra-api --docker

# Simulating the desired behavior
RUN \
  cp -r ./out/full ./out/full-without-target-scope-workspace && \
  rm -rf ./out/full-without-target-scope-workspace/apps/contra-api

FROM base AS builder

SHELL ["/bin/bash", "-c"]

WORKDIR /srv

COPY --from=pruner /srv/out/json .

RUN pnpm install --frozen-lockfile

COPY --from=pruner /srv/out/full-without-target-scope-workspace .

RUN --mount=type=secret,id=env,uid=1987 \
  set -o allexport && \
  source /run/secrets/env && \
  set +o allexport && \
  pnpm turbo run build --filter=@contra/app-contra-api^...

COPY --from=pruner /srv/out/full/apps/contra-api ./apps/contra-api

RUN --mount=type=secret,id=env,uid=1987 \
  set -o allexport && \
  source /run/secrets/env && \
  set +o allexport && \
  pnpm turbo run build --filter=@contra/app-contra-api --only

# The rest is irrelevant for this example ...
```

> **Note** `--only` does not work as expected here https://github.com/vercel/turbo/issues/2939

This why I can rely on Docker cache to cache the dependencies.

Obviously, as shown here, I can workaround this with:

```Dockerfile
# Simulating the desired behavior
RUN \
  cp -r ./out/full ./out/full-without-target-scope-workspace && \
  rm -rf ./out/full-without-target-scope-workspace/apps/contra-api
```

but it feels like a pattern that would be nice to support.

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

**Comment by chris-olszewski** [comment]
I'm not inclined to add this feature into `turbo` as it seems fairly awkward to explain and as you mention there's a very easy work around.

Out of curosity what's the time difference between the two docker files you provided when you make a change to just `@contra/app-contra-api`?
