### ISSUE TITLE
Allow to configure --env-mode strict in turbo.json

### ISSUE THREAD

**Issue by gajus** [vercel/turbo#6481]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Not clear why this is not already an option, as the desired effect is to have consistent behavior across all envs.

### Describe the solution you'd like

Adding `envMode` setting to `turbo.json`

### Describe alternatives you've considered

Passing explicit `--env-mode` to every turbo command.

**Comment by gajus** [comment]
so I am reading this right, I can just declare `globalPassThroughEnv: []` and that will make `envMode` strict by default?

That's great, but not clear why the indirectness of setting.

**Comment by chris-olszewski** [comment]
> so I am reading this right, I can just declare globalPassThroughEnv: [] and that will make envMode strict by default?

Yup, that's correct.

> That's great, but not clear why the indirectness of setting.

Hi @gajus, I discussed this with the team and we came to the conclusion that the current state, while indirect, is more desirable than adding a configuration option that can conflict with others. We don't want to require users to set `envMode: "strict"` if they already have `passThroughEnv` or `globalPassThroughEnv` set. We also don't want to allow for `globalPassThroughEnv: ["MY_VAR"]` and `envMode: loose`.

I'll close this as not-planned, but I'll keep this open to see if there's additional interest in this or if there's a use case we're not considering that comes up.

**Comment by gajus** [comment]
I think my bigger problem is that the default is loose instead of strict. It is very counter intuitive that I need to set `globalPassThroughEnv: []` to enable strict mode. We realized this after several months falsely assuming that we are using strict. It is a pretty major headache at the moment. I wish the default was strict and then you can provide whatever setting/convention to enable loose mode.

**Comment by NatoBoram** [comment]
Let's just reopen it since it's a different issue

* https://github.com/vercel/turbo/discussions/8611
