### ISSUE TITLE
[turborepo] kitchen-sink example project does not work well with VS Code

### ISSUE THREAD

**Issue by tsopeh** [vercel/turbo#6484]
### What version of Turborepo are you using?

latest (1.10.16)

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Every Typescript file opened in VS Code has the following error at its top:

`Parsing error: Cannot read file '/users/tsopeh/...../delme/tsconfig.json'.`

### Expected Behavior

Since this is an example project, I expected that tooling "just works". Or at least some additional instructions on how to fix this.

PS: Webstorm IDE works without issues.

### To Reproduce

I followed the [instructions](https://github.com/vercel/turbo/tree/main/examples/kitchen-sink#using-this-example), and created an example project named `delme`. After that, I've ran the `npm run dev` command and everything has compiled and ran successfully. When I opened the project in VS Code, every typescript file had the following error at its top:

`Parsing error: Cannot read file '/users/tsopeh/...../delme/tsconfig.json'.`

![image](https://github.com/vercel/turbo/assets/37545996/71d0bff6-fbd1-4128-8d57-44ae6d9abede)

**Using**
- VS Code (latest, version 1.84.2)
- Turborepo (latest, version 1.10.16)
- Node v20.8.0
- MacOS 14.1

**Comment by anthonyshew** [comment]
We're aware of this! Mt current project is to breathe new life into our examples, perhaps with some re-architecting along the way.

Stay tuned!

**Comment by better-salmon** [comment]
Hey @tsopeh! I found a workaround. Create or find `.vscode/settings.json` and add the following:

```json
{
    "eslint.workingDirectories": [{ "pattern": "apps/*/" }, { "pattern": "packages/*/" }]
}
```

**Comment by mehulkar** [comment]
@anthonyshew i know you've put some major effort into these, can you comment/close this one when you get a chance?

**Comment by anthonyshew** [comment]
Yep! 🥳

**Comment by stevegreco** [comment]
How do we resolve this issue?  I am still seeing this when creating a new turbo repo project. @anthonyshew

**Comment by lukeocodes** [comment]
I pop this in my `.vscode/settings.json` file

```json
{
  "eslint.workingDirectories": [
    {
      "pattern": "apps/*/"
    },
    {
      "pattern": "packages/*/"
    }
  ]
}
```
