### ISSUE TITLE
[turborepo] Creating multiple ui packages, broke tailwind stylization

### ISSUE THREAD

**Issue by GuilhermeFCO** [vercel/turbo#6493]
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Hi, i created a project with turborepo with-tailwind, worked. 
But in the moment i copy ui package and create other package changing package.json, import in apps web and docs, the component Card from ui package broken stylization. 
If try add new styles with tailwind in Card component don't work, but add styles in apps web and docs, work correctly.
So, what a create new other packages like ui to use?

### Expected Behavior

When a create new package like ui, the stylization dont broken and accept components from other packages.

### To Reproduce

Create a turborepo with-tailwind
Copy ui package, paste in packages, change name in package.json.
Put in dependencie of apps packages.

pnpm install
pnpm run dev

And the Card component dont work more.

I tested 5 times, and all times, broked.

**Comment by chris-olszewski** [comment]
Can you provide a reproduction repo? It will greatly help to understand what's happening.

**Comment by GuilhermeFCO** [comment]
Hi

https://github.com/GuilhermeFCO/turborepo-error-ui

I up my example with tailwind stylization broked.

**Comment by GuilhermeFCO** [comment]
![image](https://github.com/vercel/turbo/assets/53825689/25bb8c2b-49f8-417c-bc94-86988ae21776)

In apps web and docs, the Card component dont have styles.

**Comment by 7iomka** [comment]
`content` field need to be defined explicitly in apps tailwind.config file
Did you tried this approach?

**Comment by tknickman** [comment]
@GuilhermeFCO you need to import the styles from the package into your app. 

Here: https://github.com/GuilhermeFCO/turborepo-error-ui/blob/main/apps/web/src/app/layout.tsx#L2

Should be:

```
import "@ui/react/styles.css";
```

Also make sure your package has been built so that export can resolve. 
```

**Comment by GuilhermeFCO** [comment]
Work, thanks!
