### ISSUE TITLE
[turborepo] yarn - cannot find pnpapi

### ISSUE THREAD

**Issue by newbish** [vercel/turbo#6495]
### What version of Turborepo are you using?

1.10.12

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When creating a repo with `yarn dlx create-turbo@latest` the process fails referencing a missing pnpapi module.

```
>>  Installing dependencies...
>>> Unexpected error. Please report it as a bug:
Error: Command failed with exit code 1: yarn install
error An unexpected error occurred: "/Users/kkikta/src/new_project/node_modules/core-js-pure: Cannot find module 'pnpapi'
Require stack:
- /Users/kkikta/.cache/node/corepack/yarn/1.22.19/lib/cli.js
- /Users/kkikta/.cache/node/corepack/yarn/1.22.19/bin/yarn.js
Require stack:
- /Users/kkikta/.cache/node/corepack/yarn/1.22.19/lib/cli.js
- /Users/kkikta/.cache/node/corepack/yarn/1.22.19/bin/yarn.js".
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info If you think this is a bug, please open a bug report with the information provided in "/Users/kkikta/src/new_project/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    at nA (/Users/kkikta/.yarn/berry/cache/create-turbo-npm-1.10.16-df45cd266b-8.zip/node_modules/create-turbo/dist/cli.js:6:57)
    at /Users/kkikta/.yarn/berry/cache/create-turbo-npm-1.10.16-df45cd266b-8.zip/node_modules/create-turbo/dist/cli.js:6:10493
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Po (/Users/kkikta/.yarn/berry/cache/create-turbo-npm-1.10.16-df45cd266b-8.zip/node_modules/create-turbo/dist/cli.js:191:2084)
    at async Command.Xc (/Users/kkikta/.yarn/berry/cache/create-turbo-npm-1.10.16-df45cd266b-8.zip/node_modules/create-turbo/dist/cli.js:218:2075)
    at async Command.parseAsync (/Users/kkikta/.yarn/berry/cache/commander-npm-10.0.1-f17613b72b-8.zip/node_modules/commander/lib/command.js:935:5) {
  shortMessage: 'Command failed with exit code 1: yarn install',
  command: 'yarn install',
  escapedCommand: 'yarn install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'yarn install v1.22.19\n' +
    'info No lockfile found.\n' +
    '[1/4] Resolving packages...\n' +
    '[2/4] Fetching packages...\n' +
    '[3/4] Linking dependencies...\n' +
    '[4/4] Building fresh packages...\n' +
    'info If you think this is a bug, please open a bug report with the information provided in "/Users/kkikta/src/new_project/yarn-error.log".\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.',
  stderr: `error An unexpected error occurred: "/Users/kkikta/src/new_project/node_modules/core-js-pure: Cannot find module 'pnpapi'\n` +
    'Require stack:\n' +
    '- /Users/kkikta/.cache/node/corepack/yarn/1.22.19/lib/cli.js\n' +
    '- /Users/kkikta/.cache/node/corepack/yarn/1.22.19/bin/yarn.js\n' +
    'Require stack:\n' +
    '- /Users/kkikta/.cache/node/corepack/yarn/1.22.19/lib/cli.js\n' +
    '- /Users/kkikta/.cache/node/corepack/yarn/1.22.19/bin/yarn.js".',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

### Expected Behavior

Expected the repo creation to succeed

### To Reproduce

> yarn dlx create-turbo@latest

**Comment by chris-olszewski** [comment]
Can you verify that your yarn installation is correct?
Maybe try `yarn dlx create-turbo@latest turbo-example -m yarn --skip-install && cd turbo-example && yarn set version classic && yarn install` to see if explicitly setting the yarn version helps.

**Comment by chiefdeals** [comment]
same issue

`>   Installing dependencies...
>>> Unexpected error. Please report it as a bug:
Error: Command failed with exit code 1: yarn install
warning "@repo/eslint-config > eslint-config-prettier@9.1.0" has unmet peer dependency "eslint@>=7.0.0".
warning "@repo/eslint-config > eslint-config-turbo@1.11.3" has unmet peer dependency "eslint@>6.6.0".
warning "@repo/eslint-config > @typescript-eslint/parser@6.19.1" has unmet peer dependency "eslint@^7.0.0 || ^8.0.0".
warning "@repo/eslint-config > @typescript-eslint/eslint-plugin@6.19.1" has unmet peer dependency "eslint@^7.0.0 || ^8.0.0".
warning "@repo/eslint-config > eslint-config-turbo > eslint-plugin-turbo@1.11.3" has unmet peer dependency "eslint@>6.6.0".
warning "@repo/eslint-config > @typescript-eslint/eslint-plugin > @typescript-eslint/type-utils@6.19.1" has unmet peer dependency "eslint@^7.0.0 || ^8.0.0".
warning "@repo/eslint-config > @typescript-eslint/eslint-plugin > @typescript-eslint/utils@6.19.1" has unmet peer dependency "eslint@^7.0.0 || ^8.0.0".
warning "@repo/eslint-config > @typescript-eslint/eslint-plugin > @typescript-eslint/utils > @eslint-community/eslint-utils@4.4.0" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || >=8.0.0".
warning "@repo/eslint-config > @vercel/style-guide > @babel/eslint-parser@7.23.3" has unmet peer dependency "eslint@^7.5.0 || ^8.0.0".
warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-eslint-comments@3.2.0" has unmet peer dependency "eslint@>=4.19.1".
warning "@repo/eslint-config > @vercel/style-guide > eslint-import-resolver-typescript@3.6.1" has unmet peer dependency "eslint@*".
warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-import@2.29.1" has unmet peer dependency "eslint@^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8".
warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-jsx-a11y@6.8.0" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7 || ^8".
warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-react@7.33.2" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7 || ^8".
warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-jest@27.6.3" has unmet peer dependency "eslint@^7.0.0 || ^8.0.0".
warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-jest > @typescript-eslint/utils@5.62.0" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || ^8.0.0".
warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-unicorn@48.0.1" has unmet peer dependency "eslint@>=8.44.0".
warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-testing-library@6.2.0" has unmet peer dependency "eslint@^7.5.0 || ^8.0.0".
warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-react-hooks@4.6.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0".
warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-playwright@0.16.0" has unmet peer dependency "eslint@>=7".
error Error: /Users/evan/Desktop/turborepo/node_modules/core-js-pure: Cannot find module 'pnpapi'
Require stack:
- /Users/evan/.cache/node/corepack/yarn/1.22.21/lib/cli.js
- /Users/evan/.cache/node/corepack/yarn/1.22.21/bin/yarn.js
Require stack:
- /Users/evan/.cache/node/corepack/yarn/1.22.21/lib/cli.js
- /Users/evan/.cache/node/corepack/yarn/1.22.21/bin/yarn.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at require$$0.Module._resolveFilename (/private/var/folders/gb/jh6dj96j48l31lb1096f25bm0000gn/T/xfs-e0fcb7d1/dlx-47541/.pnp.cjs:10075:54)
    at require.resolve (/Users/evan/.cache/node/corepack/yarn/1.22.21/lib/v8-compile-cache.js:162:23)
    at /Users/evan/.cache/node/corepack/yarn/1.22.21/lib/cli.js:34246:76
    at Generator.next (<anonymous>)
    at step (/Users/evan/.cache/node/corepack/yarn/1.22.21/lib/cli.js:310:30)
    at /Users/evan/.cache/node/corepack/yarn/1.22.21/lib/cli.js:321:13
yarn install v1.22.21
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    at ML (/Users/evan/.yarn/berry/cache/create-turbo-npm-1.11.3-84c158a615-8.zip/node_modules/create-turbo/dist/cli.js:12:57)
    at /Users/evan/.yarn/berry/cache/create-turbo-npm-1.11.3-84c158a615-8.zip/node_modules/create-turbo/dist/cli.js:12:8077
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fc (/Users/evan/.yarn/berry/cache/create-turbo-npm-1.11.3-84c158a615-8.zip/node_modules/create-turbo/dist/cli.js:60:2093)
    at async Command.Lm (/Users/evan/.yarn/berry/cache/create-turbo-npm-1.11.3-84c158a615-8.zip/node_modules/create-turbo/dist/cli.js:87:2075)
    at async Command.parseAsync (/Users/evan/.yarn/berry/cache/commander-npm-10.0.1-f17613b72b-8.zip/node_modules/commander/lib/command.js:935:5) {
  shortMessage: 'Command failed with exit code 1: yarn install',
  command: 'yarn install',
  escapedCommand: 'yarn install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'yarn install v1.22.21\n' +
    'info No lockfile found.\n' +
    '[1/5] Validating package.json...\n' +
    '[2/5] Resolving packages...\n' +
    '[3/5] Fetching packages...\n' +
    '[4/5] Linking dependencies...\n' +
    '[5/5] Building fresh packages...\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.',
  stderr: 'warning "@repo/eslint-config > eslint-config-prettier@9.1.0" has unmet peer dependency "eslint@>=7.0.0".\n' +
    'warning "@repo/eslint-config > eslint-config-turbo@1.11.3" has unmet peer dependency "eslint@>6.6.0".\n' +
    'warning "@repo/eslint-config > @typescript-eslint/parser@6.19.1" has unmet peer dependency "eslint@^7.0.0 || ^8.0.0".\n' +
    'warning "@repo/eslint-config > @typescript-eslint/eslint-plugin@6.19.1" has unmet peer dependency "eslint@^7.0.0 || ^8.0.0".\n' +
    'warning "@repo/eslint-config > eslint-config-turbo > eslint-plugin-turbo@1.11.3" has unmet peer dependency "eslint@>6.6.0".\n' +
    'warning "@repo/eslint-config > @typescript-eslint/eslint-plugin > @typescript-eslint/type-utils@6.19.1" has unmet peer dependency "eslint@^7.0.0 || ^8.0.0".\n' +
    'warning "@repo/eslint-config > @typescript-eslint/eslint-plugin > @typescript-eslint/utils@6.19.1" has unmet peer dependency "eslint@^7.0.0 || ^8.0.0".\n' +
    'warning "@repo/eslint-config > @typescript-eslint/eslint-plugin > @typescript-eslint/utils > @eslint-community/eslint-utils@4.4.0" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || >=8.0.0".\n' +
    'warning "@repo/eslint-config > @vercel/style-guide > @babel/eslint-parser@7.23.3" has unmet peer dependency "eslint@^7.5.0 || ^8.0.0".\n' +
    'warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-eslint-comments@3.2.0" has unmet peer dependency "eslint@>=4.19.1".\n' +
    'warning "@repo/eslint-config > @vercel/style-guide > eslint-import-resolver-typescript@3.6.1" has unmet peer dependency "eslint@*".\n' +
    'warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-import@2.29.1" has unmet peer dependency "eslint@^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8".\n' +
    'warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-jsx-a11y@6.8.0" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7 || ^8".\n' +
    'warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-react@7.33.2" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7 || ^8".\n' +
    'warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-jest@27.6.3" has unmet peer dependency "eslint@^7.0.0 || ^8.0.0".\n' +
    'warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-jest > @typescript-eslint/utils@5.62.0" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || ^8.0.0".\n' +
    'warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-unicorn@48.0.1" has unmet peer dependency "eslint@>=8.44.0".\n' +
    'warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-testing-library@6.2.0" has unmet peer dependency "eslint@^7.5.0 || ^8.0.0".\n' +
    'warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-react-hooks@4.6.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0".\n' +
    'warning "@repo/eslint-config > @vercel/style-guide > eslint-plugin-playwright@0.16.0" has unmet peer dependency "eslint@>=7".\n' +
    "error Error: /Users/evan/Desktop/turborepo/node_modules/core-js-pure: Cannot find module 'pnpapi'\n" +
    'Require stack:\n' +
    '- /Users/evan/.cache/node/corepack/yarn/1.22.21/lib/cli.js\n' +
    '- /Users/evan/.cache/node/corepack/yarn/1.22.21/bin/yarn.js\n' +
    'Require stack:\n' +
    '- /Users/evan/.cache/node/corepack/yarn/1.22.21/lib/cli.js\n' +
    '- /Users/evan/.cache/node/corepack/yarn/1.22.21/bin/yarn.js\n' +
    '    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)\n' +
    '    at require$$0.Module._resolveFilename (/private/var/folders/gb/jh6dj96j48l31lb1096f25bm0000gn/T/xfs-e0fcb7d1/dlx-47541/.pnp.cjs:10075:54)\n' +
    '    at require.resolve (/Users/evan/.cache/node/corepack/yarn/1.22.21/lib/v8-compile-cache.js:162:23)\n' +
    '    at /Users/evan/.cache/node/corepack/yarn/1.22.21/lib/cli.js:34246:76\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at step (/Users/evan/.cache/node/corepack/yarn/1.22.21/lib/cli.js:310:30)\n' +
    '    at /Users/evan/.cache/node/corepack/yarn/1.22.21/lib/cli.js:321:13',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}`

**Comment by chiefdeals** [comment]
> Can you verify that your yarn installation is correct? I ask because [`pnpapi` is a builtin](https://yarnpkg.com/advanced/pnpapi#requirepnpapi) so being unable to load it points at larger problems.
> 
> Maybe try `yarn dlx create-turbo@latest turbo-example -m yarn --skip-install && cd turbo-example && yarn set version classic && yarn install` to see if explicitly setting the yarn version helps.

Had same issue, this enabled me to run without errors

**Comment by chris-olszewski** [comment]
Closing this as I believe this is an issue with the `yarn` installation on the machine and not `turbo` itself.
