### ISSUE TITLE
[turbopack] SASS nesting classes is not working

### ISSUE THREAD

**Issue by waellaataoui** [vercel/turbo#6501]
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Using nested classes in a .scss file doesn't have any effect at all.
But nesting  HTML elements works 
![image](https://github.com/vercel/turbo/assets/43973620/993d9fa8-a804-4387-a9db-4ddf3018b5c2)

### Expected Behavior

Using nested classes selectors should take effect

### To Reproduce

Create any project using turbopack and try adding styles using a nested selector. You won't be able to see your styles being added

**Comment by timneutkens** [comment]
Verified this works correctly now.

Here's a sandbox: https://codesandbox.io/p/devbox/vigilant-cdn-dmm53w?file=%2Fapp%2Fpage.tsx

Thanks for the report!
