### ISSUE TITLE
[turborepo] npx create-turbo@latest output result is not compatible with Nextjs 14

### ISSUE THREAD

**Issue by larryhopecode** [vercel/turbo#6507]
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

After generated scaffold directory structure, go into root workspace. 
$ pnpm update
$ pnpm dev (no error message)
$ pnpm build then the error shows up.
> turbo-demo@ build /mnt/nvme/code/playground/turbo-demo
> turbo run build

• Packages in scope: docs, eslint-config-custom, tsconfig, ui, web
• Running build in 5 packages
• Remote caching disabled
web:build: cache miss, executing 41fefabc01e8d8d7
docs:build: cache miss, executing d730b9f1e2a0cb14
web:build:
web:build: > web@1.0.0 build /mnt/nvme/code/playground/turbo-demo/apps/web
web:build: > next build
web:build:
docs:build:
docs:build: > docs@1.0.0 build /mnt/nvme/code/playground/turbo-demo/apps/docs
docs:build: > next build
docs:build:
docs:build:    Creating an optimized production build ...
web:build:    ▲ Next.js 14.0.3
web:build:
web:build:    Creating an optimized production build ...
web:build:  ✓ Compiled successfully
web:build:    Linting and checking validity of types ...
docs:build:  ✓ Compiled successfully
docs:build:    Linting and checking validity of types ...
web:build: Failed to compile.
web:build:
web:build: ../../packages/ui/card.tsx:24:10
web:build: Type error: Type 'import("/mnt/nvme/code/playground/turbo-demo/node_modules/.pnpm/@types+react@18.2.5/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
web:build:   Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
web:build:     Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.
web:build:
web:build:   22 |         {title} <span>-&gt;</span>
web:build:   23 |       </h2>
web:build: > 24 |       <p>{children}</p>
web:build:      |          ^
web:build:   25 |     </a>
web:build:   26 |   );
web:build:   27 | }
web:build:  ELIFECYCLE  Command failed with exit code 1.
web:build: ERROR: command finished with error: command (/mnt/nvme/code/playground/turbo-demo/apps/web) pnpm run build exited (1)
web#build: command (/mnt/nvme/code/playground/turbo-demo/apps/web) pnpm run build exited (1)

 Tasks:    0 successful, 2 total
Cached:    0 cached, 2 total
  Time:    3.84s
Failed:    web#build

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.

### Expected Behavior

should be correctly built

### To Reproduce

$ pnpm update
$ pnpm dev (no error message)
$ pnpm build then the error shows up.

**Comment by larryhopecode** [comment]
one missing steps for reproducing the bug (upgrade to next js 14.0.3)
cd apps/web/
pnpm add next

**Comment by chris-olszewski** [comment]
Closing in favor of #6529
