### ISSUE TITLE
I got this bug when I use `yarn lint`:

### ISSUE THREAD

**Issue by anthonyshew** [vercel/turbo#6511]
I got this bug when I use `yarn lint`:

root task lint (turbo run lint) looks like it invokes turbo and might cause a loop

- turborepo: "latest"
- netxjs: "latest"

_Originally posted by @tienlx97 in https://github.com/vercel/turbo/discussions/5290_

**Comment by chris-olszewski** [comment]
For those that want this addressed. Providing a reproduction would be amazing, but if that's not possible the value of the script in `package.json` that `turbo` is complaining about would be very helpful e.g. `"lint": "eslint ."`.

**Comment by Talljoe** [comment]
I don't have a complete repro, but I hit this issue when I mis-typed the name of `pnpm-workspace.yaml`.  I tried it just now and removing the workspace file caused that error. This may not be the same cause that others are seeing, though.

**Comment by anthonyshew** [comment]
Closing due to age and inactivity. If you're seeing a problem that sounds like this one, please open a fresh issue with a reproduction!
