### ISSUE TITLE
Make changelogs more readable

### ISSUE THREAD

**Issue by anthonyshew** [vercel/turbo#6526]
### Discussed in https://github.com/vercel/turbo/discussions/6436

<div type='discussions-op-text'>

<sup>Originally posted by **jakeleventhal** November 13, 2023</sup>
The changelog is pretty hard to read/understand when every single commit message is just mashed together. It would be really nice if the changes were at least organized by type and ranked in some sort of relevance, or at least highlight the big things that people should actually care about at the top.</div>

<sub>[TURBO-1727](https://linear.app/vercel/issue/TURBO-1727/make-changelogs-more-readable)</sub>

**Comment by tknickman** [comment]
Release notes will be organized based on https://github.com/vercel/turbo/blob/main/.github/turborepo-release.yml.

**Comment by jakeleventhal** [comment]
@tknickman this problem exists for all other vercel packages. Hopefully this can be adopted for the entire org
