### ISSUE TITLE
Upgrade examples `next` version to 14

### ISSUE THREAD

**Issue by Neosoulink** [vercel/turbo#6529]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Upgrade the `next` version to 14 for all examples integrated with NexJS

**Comment by anthonyshew** [comment]
I'm on these! Will handle this one today since we've got somebody looking at it.

**Comment by Neosoulink** [comment]
Awesome @anthonyshew, thanks 🙌
