### ISSUE TITLE
[turborepo] root turbo.json not used & has to duplicate conf so that it is applied

### ISSUE THREAD

**Issue by MarArMar** [vercel/turbo#6560]
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

I have this in my turborepo root 
```json
{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
    "build": {
      "cache": false,
      "dependsOn": ["^build"],
      "outputs": []
    }
  }
}
```

If I build a project on vercel, the build show these logs
```
Deployment completed
Uploading build cache [XXX.XX MB]...
Build cache uploaded: Y.YYs
```

If I add this turbo.json in the folder that is built,
```json 
{
  "$schema": "https://turbo.build/schema.json",
  "extends": ["//"],
  "pipeline": {
    "build": {
      "cache": false,
      "dependsOn": ["^build"],
      "outputs": [".svelte-kit/**"]
    }
  }
}
```
Then it correctly does not cache the build

Why is the root config not applied ?

### Expected Behavior

Should apply root config

### To Reproduce

Make Sveltekit default project & use configs as specified to build a project on vercel

**Comment by tknickman** [comment]
Hey @MarArMar. A few things here:

1. Workspace configs always override the root config ([docs](https://turbo.build/repo/docs/core-concepts/monorepos/configuring-workspaces#how-it-works)).
2. The log line that you're posting from Vercel is for the [Vercel build cache](https://vercel.com/docs/deployments/troubleshoot-a-build#what-is-cached), _not_ the turbo cache. The Vercel Build cache caches `node_modules` to make installs faster. And the turbo cache build outputs to make builds faster. Disabling the turbo cache (by setting `"cache": false` _does not_ disable the Vercel build cache)

With `"cache": false`,  in your config, you should see a log line with:
`cache bypass, force executing` 

for your `build` task.

**Comment by MarArMar** [comment]
hmmm

so 1st time the node_modules were cached by Vercel, not Turbo ?

And 2nd time they were not uploaded because Vercel already had them in cache ?

Ok was surprized I thought it was the turbo override that had the effect

Indeed might not be turbo at all then

**Comment by MarArMar** [comment]
Is my workspace config any relevant then ? Except for the "output" everything is the same, so it is probably useless right ?

**Comment by MarArMar** [comment]
Ok thanks. Closing the issur then. Manyt thnaks for your help
