### ISSUE TITLE
Add [vercel only <workspace>] commit message check to turbo-ignore

### ISSUE THREAD

**Issue by m1heng** [vercel/turbo#6578]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

`turbo-ignore` enables commit message checks for forcefully deploying a specific workspace. However, in situations where we use a specific branch like `release/<workspace>` to manage the production release of a particular workspace, it would be beneficial to have a commit message check that allows deployment of only that workspace, even if there are changes in other workspaces.

### Describe the solution you'd like

Add [vercel only <workspace>] commit message check.
Only specified workspace will be deployed, others would be ignored.

### Describe alternatives you've considered

Null

**Comment by tknickman** [comment]
Thanks for the contribution! This is a niche case I think, but it's simple enough to support. I left some feedback on the PR.
