### ISSUE TITLE
Log file creation fails for npm scripts names containing `:` & Turbo panics with `#`

### ISSUE THREAD

**Issue by b12k** [vercel/turbo#660]
### What version of Turborepo are you using?

1.1.2

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

`./package.json`
```json
{
  "scripts": {
    "build:docker": "turbo run build:docker --parallel"
  }
}
```

`./turbo.json`
```json
{
  "pipeline": {
    "build:docker": {
      "outputs": []
    }
  }
}
```

`./apps/my-app/api/package.json`
```json
{
  "scripts": {
    "build:docker": "cd ../../../ && docker build . -f infrastructure/docker/Dockerfile -t my-app-api:latest"
  }
}
```

`folder structure`
```bash
monorepo/
  package.json
  infrastructure/
    docker/
      Dockerfile
  apps/
    my-app/
      api/
        package.json
```

When re-running `yarn build:docker` getting `cache miss`.

Renaming npm scripts from `build:docker` to `build-docker` solved an issue.

![изображение](https://user-images.githubusercontent.com/10243265/152022645-9b4da565-b1f6-4d72-892f-99bad947e8f9.png)

[Thread in Discussions](https://github.com/vercel/turborepo/discussions/659)

### Expected Behavior

Turbo should support any npm script naming convention.

Consider replacing "non friendly" characters in npm script name with a defined placeholder char:
(underscore or dual-underscore for example)
- `build:docker` => `build__docker`
- `build#docker` => `build__docker`

Or use npm script name hash for log files name.

BTW `#` in script name makes Turbo panic 
<details>
  <summary>Terminal screenshot</summary>
  
![изображение](https://user-images.githubusercontent.com/10243265/152024600-ee65e2e6-d8c6-4c39-b44f-29612fef79bd.png)

</details>

### To Reproduce

- Name your package.json scripts using `:` or `#` characters. 
- Expect
  - for `:`: miss formed log file
  - for `#`: panic

**Comment by weyert** [comment]
Yes, ; and # are invalid characters for a file name in Windows
