### ISSUE TITLE
[turborepo] Root workspace:* dependencies don't bust the cache

### ISSUE THREAD

**Issue by closesimple-wl** [vercel/turbo#6614]
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

We're storing our "tsconfig.json" in a "packages" project, similar to how the Reproduction Repo does it: https://github.com/vercel/turbo/issues/5808

We want to move our dependency on this "tsconfig.json" project up to the root Workspace's "package.json" to eliminate some duplication in each project in the monorepo.  They're basically all TypeScript projects, after all.

Problem is Turborepo ignores the root "package.json" dependencies when determining whether a project, via its dependencies, has changed.

### Expected Behavior

Turborepo should bust the cache (and therefore perform the build task) when a root local dependency changes, just like it does when a non-root local dependency changes.

At the very least, the documentation should explain why it doesn't.  Anti-mental-gymnastics, please.

### To Reproduce

Follow the Reproduction Repo creation: https://github.com/vercel/turbo/issues/5808

Remove the `@repo/blah` dependencies from each project, and add those dependencies to the root "package.json".  Change "base.json" in the tsconfig project.  Notice the cache isn't busted.  FULL TURBO even when there's a change.

<sub>[TURBO-1837](https://linear.app/vercel/issue/TURBO-1837/[turborepo]-root-workspace-dependencies-dont-bust-the-cache)</sub>

**Comment by NicholasLYang** [comment]
Hi @closesimple-wl, thanks for the issue. If I'm not mistaken, Turbo is working as intended here. If you remove the dependencies from each workspace, then the workspaces' tasks will not depend on the dependencies. We don't treat root dependencies as global, so if they change, they won't affect the other workspaces. 

That said, I do see where you're coming from. It makes sense that root dependencies should be global. I'll raise this with the team and we can consider a flag for this behavior.

**Comment by NicholasLYang** [comment]
Done in #6622  :D

**Comment by closesimple-wl** [comment]
Thank you @NicholasLYang .  I like how it describes the "what", but it's missing the always-crucial "why".  What's the reasoning?

**Comment by mehulkar** [comment]
We talked through this again at the team meeting today, and we've gotten consensus on a couple things:

- We mostly agree that using a root dependency to affect all your workspaces is not the best setup
- But if you do, we agree that internal dependencies _should_ cause a global cache miss.

We will add the hash of files from internal dependencies to the global hash when they are in the root package.json. Note a couple things:

- `inputs` configurations will still be respected (including [Workspace Configurations](https://turbo.build/repo/docs/core-concepts/monorepos/configuring-workspaces)), so turbo won't blindly take _every_ file in these internal packages
- We will not consider this a breaking change (even though this _likely_ will cause unexpected cache misses for people who are used to the current behavior)

Thanks for filing and for helping shape this conversation!
