### ISSUE TITLE
Ability to create a repo with create-turbo from an example

### ISSUE THREAD

**Issue by bring-shrubbery** [vercel/turbo#664]
### Describe the feature you'd like to request

When running `create-turbo` at the moment, you always get the same placeholder setup (next.js, docs, tsconfig, config, ui packages). Having a `--example` flag that you can use to provide an example from the `examples` folder of this repo would be very nice. Maybe similar to how `create-next-app` does it?

### Describe the solution you'd like

I would like to run this command to create a design system turborepo:

```bash
npx create-turbo@latest --example design-system
```

### Describe alternatives you've considered

Alternatively, an "Examples" section could be added to the docs, which could automatically render the README files from examples in this repo. This would be a useful and simpler solution, compared to changing the create-turbo CLI.

**Comment by DefinitelyMaybe** [comment]
perhaps a specific example could be chosen within the cli instead of as a flag? either way this would be helpful.

**Comment by bring-shrubbery** [comment]
@DefinitelyMaybe absolutely, I was just suggesting the same way as next.js has when creating repo from an example.

**Comment by tknickman** [comment]
Took a little bit, but this finally landed! It's available now in canary, and we would love any feedback:

`npx create-turbo@canary -e {example}`

**Comment by bring-shrubbery** [comment]
@tknickman Nice! I will definitely try this out in a near future.
