### ISSUE TITLE
[turborepo] code generator not working.

### ISSUE THREAD

**Issue by mayank1513** [vercel/turbo#6656]
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

Turborepo generators used to work well in my repo. However, after recent updates, it doesn't work.

When I run `yarn turbo gen` it throws following error.
```
>>> Unexpected error. Please report it as a bug:
error TS6053: File 'tsconfig/base.json' not found.
```

Repo - https://github.com/react18-tools/react18-themes

### Expected Behavior

Turborepo generators should generate the expected files without throwing meaningless errors.

### To Reproduce

```
git clone https://github.com/react18-tools/react18-themes.git
cd react18-themes
pnpm i
pnpm turbo gen
```
Throws error.

### Reproduction Repo

https://github.com/react18-tools/react18-themes

**Comment by flextremedev** [comment]
I'm having the same issue. Please note that your repo under Reproduction Repo is not accessible (Page not found).

**Comment by mayank1513** [comment]
> I'm having the same issue. Please note that your repo under Reproduction Repo is not accessible (Page not found).

Hi, thanks for the observation. I have updated it - https://github.com/react18-tools/react18-themes

**Comment by tknickman** [comment]
Taking a look!

**Comment by mayank1513** [comment]
Thanks for the diagnosis.
