### ISSUE TITLE
turborepo: Discovering symbol references and renaming doesn't work in VS Code

### ISSUE THREAD

**Issue by tsopeh** [vercel/turbo#6673]
### What version of Turborepo are you using?

latest, 1.10

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Cannot discover all references for some symbol in VS Code (`Context menu -> Find All References` or `Option+Shift+F12`). Cannot confidently rename (F2) the same symbol and expect that all its references will be renamed as well.

### Expected Behavior

All references of the symbol should be listed when searching for them. Renaming a symbol should rename all of its references.

### To Reproduce

I followed the [official guide](https://turbo.build/repo/docs/getting-started/create-new).

Steps

1. `npx create-turbo@latest`
2. Open the new repo in VS Code
3. Open the `packages/ui/src/card.tsx`
4. Search for all references of the `Card` component (`Context menu -> Find All References` or `Option+Shift+F12`). Doesn't find them all.

If you now navigate to `apps/web/app/page.tsx`, then jump back to the card component and search again for its references, now there'll be an entry for `apps/web/app/page.tsx`, but still not for `apps/docs/app/page.tsx` (because we didn't navigate to that one yet). If you were to now rename the `Card` component to the `CoolCard`, only the `apps/web/app/page.tsx`'s reference would get renamed, thus breaking the `apps/docs/app/page.tsx`.

These steps can be repeated by reloading VS Code: `Cmd+Shift+P -> "Developer: Reload Window"`

I've tried these steps for `npm`, `pnpm` and `yarn v1`.
Node: v21.1.0
OS: MacOS 14.1.1
VS Code: 1.84.2 (latest)

### Reproduction Repo

No need, doesn't work out of the box

**Comment by anthonyshew** [comment]
This is a limitation brought on by the way VSCode and `tsserver` work. Poking around in the TypeScript repo yields many issues on this subject. Here's one that links out to a great many other related issues: https://github.com/microsoft/vscode/issues/80087

It looks like this is a conscious performance trade-off made by the TypeScript team from what I'm seeing. Unfortunately, there's nothing we can do about this here in Turborepo it looks like. 

If there's a technique that can make this work that you can point me to, that'd be great! I wasn't able to find a solution. Would be happy to take a PR for review, as well!

**Comment by mickdewald** [comment]
That's a shame it does not work. 
Is there any news regarding this issue?
It helps a lot to see all the references for a component in the whole project

**Comment by anthonyshew** [comment]
This is not a Turborepo issue as noted in my comment above. You'll want to check in on with the TypeScript repo to see if anything has been done.
