### ISSUE TITLE
Keep executing tasks that are running even if one fails

### ISSUE THREAD

**Issue by MonstraG** [vercel/turbo#6689]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Assume I have a project where I build several apps: `storefront`, `admin`, `docs`:

Here is how they build (time wise):
```
storefront: [ | | | | | | | ] ✓
admin:      [ | | | | | | | | | ] ✓
docs:       [ | | | | ] ✓

3 jobs succeeded, 3 jobs cached.
```
docs manages to build first, storefront second and admin last.

When everything is working perfectly all jobs pass and cache, so if I run `turbo` again, it'll just print ">>> FULL TURBO" in 0.1 seconds:
```
storefront: [] ✓
admin:      [] ✓
docs:       [] ✓

3 jobs succeeded, 3 taken from cache
```

I then write some code in `storefront` but make a mistake:
```
storefront: [ | | | | | | x
admin:      [ | | | | | | ~
docs:       [ | | | | ] ✓

1 jobs succeeded, 1 job cached.
```
docs sucessfully builds, storefront fails, and admin build gets abandoned.

If I try to fix it and fail, the same thing will happen, except docs is already cached:
```
storefront: [ | | | | | | x
admin:      [ | | | | | | ~
docs:       [] ✓ cached

1 jobs succeeded, 1 taken from cache.
```

If admin was allowed to be continued, it would succeed:
```
storefront: [ | | | | | | x
admin:      [ | | | | | | | | | ] ✓
docs:       [] ✓ cached

2 jobs succeeded, 1 taken from cache.
```
And on the following runs, only storefront would be attempted to be run:

```
storefront: [ | | | | | | x
admin:      [] ✓ cached
docs:       [] ✓ cached

2 jobs succeeded, 2 taken from cache.
```

In my project I have not 3, but 6 applications, and usually only one fails, but my CPU has to start rebuilding most of them (because fail happens before anything succeeds)

I feel like a lot of CPU cycles can be saved, if already running builds would be allowed to continue, so that they woundn't need to be run again.

### Describe the solution you'd like

With a flag or by default, allow already running jobs to continue, if one of the jobs fails, but do not start other jobs.

### Describe alternatives you've considered

N/A

**Comment by NicholasLYang** [comment]
Hi, thanks for the issue. If I'm understanding your request correctly, you can do this with the `--continue` flag, which lets tasks continue execution even if one fails.

**Comment by mehulkar** [comment]
@NicholasLYang is correct, `--continue` is intended for this use case. Going to close this down, but let us know if there's a misunderstanding!
