### ISSUE TITLE
Add ability to do group-expanded to log-order for better CI readability in Github Actions

### ISSUE THREAD

**Issue by runspired** [vercel/turbo#6709]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

see title

### Describe the solution you'd like

see title

### Describe alternatives you've considered

choosing chaos with --log-order=stream

<sub>[TURBO-1857](https://linear.app/vercel/issue/TURBO-1857/add-ability-to-do-group-expanded-to-log-order-for-better-ci)</sub>

**Comment by anthonyshew** [comment]
Could you provide more details? How is this different from `--log-order=grouped`?

**Comment by runspired** [comment]
@anthonyshew log order grouped collapses all groups, makes it impossible to find which groups have failures in them.

An alternative here is to make `--log-order=grouped` expand any groups that have failures in them

**Comment by tknickman** [comment]
@runspired groups with failures are listed at the end of the run, but agreed - runs with failures should be expanded by default!

**Comment by maschwenk** [comment]
I guess in terms of feasibility:

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines unclear if the expandability state is actually controllable?

I wonder if an alternative would be to pin failures to the bottom or something? Or restate them in a summary like Jest does? I know y'all have the `--summary` but obviously that's not super human readable.

**Comment by mehulkar** [comment]
Since we're buffering the output until the task is done, we can just omit the group start/end markers for NZE tasks
