### ISSUE TITLE
Tailwind CSS not working

### ISSUE THREAD

**Issue by mayank1513** [vercel/turbo#6717]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/react18-tools/nextjs-themes/tree/tailwind/examples/tailwind

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

1.11.0

### Describe the Bug

I was just trying to add a tailwind example for one of my packages. I have followed the official docs. However, it seems that I am making some silly mistake here. It doesn't seem to apply tailwind styles.

Here's the code - https://github.com/react18-tools/nextjs-themes/tree/tailwind/examples/tailwind

No errors are thrown but the styles are not applied either.

### Expected Behavior

Tailwind styles such as underline should be applied.

### To Reproduce

```
git clone -b tailwind https://github.com/react18-tools/nextjs-themes.git
cd nextjs-themes
pnpm i
yarn dev --filter tailwind
```

**Comment by anthonyshew** [comment]
This doesn't look to be a Turborepo bug. Two ways I've determined this:

- If I use `npx create-next-app` to create another Next.js + Tailwind app in your examples folder, it works correctly.
- If I run the `dev` script in `examples/tailwind` directly (`cd examples/tailwind && pnpm dev`, not `turbo dev`), there are still no styles. Running the script directly means Turborepo wasn't involved in any way.

There is likely to be some small misconfiguration in the application. I couldn't tell what it was at a glance, unfortunately, but I trust you'll be able to find it!

---
As an aside, when I was looking at your repo, it looks like you're git ignoring your lockfile. You **definitely** want to commit your lockfile. Quick explanation from AI: https://sdk.vercel.ai/s/MvppSyx
