### ISSUE TITLE
proposal: Turbofile

### ISSUE THREAD

**Issue by kislball** [vercel/turbo#673]
### Describe the feature you'd like to request

Introduce Turbofile - a file, which will be backed by some scripting language(e.g. Lua or Tengo) which will allow for:
* Less boilerplate and more reusability
* Much more flexible
* Easily add new programming languages without modifing Turborepo itself. 
* Less NPM dependent

Possible drawbacks are:
* Increased difficulty
* Slower initial startup time, can be solved by caching configuration

### Describe the solution you'd like

I will briefly describe general concept for Turbofile, [Tengo](https://github.com/d5/tengo) will be used here since its implementation is in pure Go and requires not a lot overhead.

#### Basics
Simple root Turbofile:
```go
config(
  packages("./lib", "./apps"),
  scripts("build", "test")
)
```

Simple file for Go package:
```go
config(
  gomod(),
  script(
    "build",
    sh("go build ./cmd/turbo/main.go"),
    outputs("./build/turbo.exe")
  )
)
```

Same goes for node:
```go
config(
  npm(),
  npmScript("build", outputs("./dist")),
  npmScript("test", dependsOn("build"))
)
```

#### Under the hood

```go
config(
  name("github.com/vercel/turborepo"),
  dependency("github.com/vercel/turborepo-dependency") // only means for topological order, dependencies are still managed by golang
)
// in case of node
config(
  name("test-project"),
  dependency("github.com/vercel/turborepo")
)
```

It would also allow for easy nesting of repositories:
```go
config(
  name("test-project"),
  dependency("github.com/vercel/turborepo"),
  projects("./directory")
)
```

#### Custom "hooks"
Tengo has a pretty decent standard library which includes fs.
```go
// npm.tengo
os := import("os")
json := import("json")
turbo := import("turbo")

export func () {
  j := os.read_file("./package.json")
  if is_error(j) {
    turbo.error("Cannot find package.json")
    return
  }
  package := json.decode(string(j))
  deps := []

  for dep, _ in package.dependencies {
    if turbo.has_package(dep) { // here we don't add some arbitrary packages from npm registry, only add those which are controlled by turbo
      deps = deps + dependency(dep)
    }
  }  

  return [name(package.name), deps]
}
```

```go
npm := import("./npm")

config( // config should flat all arrays 
  npm()
)
```
#### Legacy
```go
config(legacyTurbo("./turbo.json"))
// or from package.json
config(legacyPackage("./package.json"))
```

### Describe alternatives you've considered

It is possible to generate JSON files arbitrarily, however it will likely result in quite unpredictable behaviour and is limited,

**Comment by connorjs** [comment]
Or JS-based config? `turbo.config.js`

**Comment by gunnartorfis** [comment]
It would allow for documenting the config file, +1 from me regardless of the language that would be used.

**Comment by GNRSN** [comment]
> It would allow for documenting the config file, +1 from me regardless of the language that would be used.

@gunnartorfis You can already document the config file, it's inferred as jsonc by default. 
You can configure your editor to treat it as such manually if it doesn't happen automatically

**Comment by anthonyshew** [comment]
This doesn't seem like something we'll pursue. If folks want to create scripts for generating things, they can do so in a variety of ways in the ecosystem today and schedule those generation tasks through `turbo`.
