### ISSUE TITLE
Wrong dependent task gets run when using pnpm relative path reference (eg. `workspace:../path/to/dep`)

### ISSUE THREAD

**Issue by steveluscher** [vercel/turbo#6744]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/steveluscher/pnpm-alias-pathspec-repro.git

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

1.11.1-canary.0

### Describe the Bug

Imagine that you:

1. Alias a package to a relative path (eg. `"luigi": "workspace:../waluigi"`)
2. Another package in your workspace has the same name as the alias (`luigi`)

…then you run some turborepo task.

```shell
pnpm i
cd packages/app/
pnpm turbo hello
```

Turborepo will run the task in the wrong workspace package; the `hello` script from `luigi/package.json` runs.

### Expected Behavior

Since the dependency `luigi` is aliased to `workspace:../waluigi`, I would expect the `hello` script from `waluigi/package.json` to run.

### To Reproduce

Follow the README in https://github.com/steveluscher/pnpm-alias-pathspec-repro.git.

### Additional context

> [!NOTE]
> If you change the dependency in `app/package.json` from `"luigi": "workspace:../waluigi"` to `"luigi": "workspace:waluigi@*"` it works as expected.

<sub>[TURBO-1899](https://linear.app/vercel/issue/TURBO-1899/wrong-dependent-task-gets-run-when-using-pnpm-relative-path-reference)</sub>

**Comment by steveluscher** [comment]
Possibly related `TODO`:

https://github.com/vercel/turbo/blob/4be6e0e7b2170c1b1f822db5a6a6750873a0f4be/crates/turborepo-repository/src/package_graph/builder.rs#L624-L626

**Comment by chris-olszewski** [comment]
I know this isn't a fix for the underlying issue, but could you use the other `pnpm` [alias strategy](https://pnpm.io/workspaces#referencing-workspace-packages-through-aliases) to unblock yourself?
e.g. in `packages/app/package.json` change the dependency to be `"luigi": "workspace:waluigi@*"`

**Comment by steveluscher** [comment]
I mentioned that alternate strategy in a note in the original issue text, yeah. That strategy won't work for me for reasons that I shouldn't get into here. I just want to make sure that Vercel is aware of the bug in Turbo.

**Comment by chris-olszewski** [comment]
Ah, my bad for not reading the issue closely enough. Thanks for opening the issue and the repro.
