### ISSUE TITLE
Task with "cache" false turns off dependent task cache restore

### ISSUE THREAD

**Issue by closesimple-wl** [vercel/turbo#6749]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

no

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

1.11.1-canary.0

### Describe the Bug

We have a "deploy" task that depends on a "build" task.  Deployment is a side effect, so we specify `cache` `false` on the "deploy" task.

Running the "deploy" task first runs the "build" task, which restores an empty directory instead of what was previously built and cached.

Unrelated, but bonus points if you answer this question: https://github.com/vercel/turbo/discussions/6035

### Expected Behavior

The previously built version should be restored from cache.  Instead we get an empty directory restored.

```json
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist"]
    },
    "test": {},
    "deploy": {
      "dependsOn": ["build"],
      "cache": false
    }
  }
 ```

### To Reproduce

1. Build a workspace, which caches the output.
2. Delete the output directory.
3. Run the "deploy" task.

The "build" will have a cache hit, but the output directory will be empty instead of full of the build artifacts.

**Comment by mehulkar** [comment]
Your outputs configuration should likely be `"outputs": ["dist/**"]` if you intend to capture all of the contents of the dist directory. Closing this out, but if you find that doesn't work, I can re-open!

**Comment by closesimple-wl** [comment]
No, the "build" task is the thing restoring the directory.  The "deploy" task shouldn't be restoring anything; it takes what "build" built and pushes it somewhere.

**Comment by closesimple-wl** [comment]
@mehulkar sorry I just realized my stripped down example doesn't reflect what we actually have.  We do have `directory/**` glob pattern, and this is still happening.

**Comment by closesimple-wl** [comment]
In the meantime, removing `cache` `false` appears to avoid the issue.  Problem is we want `cache` `false`. :)

**Comment by closesimple-wl** [comment]
Scratch that.  It was that we're missing the `/**` glob pattern on the directory.  Same behavior without `cache` `false` too.  My mistake, thank you.
