### ISSUE TITLE
"File Inputs": Add extraInput & exclude

### ISSUE THREAD

**Issue by websaid** [vercel/turbo#6814]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

I want to be able to include and exclude easier to the [Workspace Files](https://turbo.build/repo/docs/core-concepts/caching/file-inputs#workspace-files).

I want turbo to include one file, which is being ignored in the .gitignore. I think there should be an easy way to include it and have it next to the default behaviour. 

Also an easy exclude should be possible, in order to be able to have a file/directory in the repo but not relevant to turbo.

### Describe the solution you'd like

This is the `.gitignore`
```.gitignore
/types/
```

 `turbo.json`
```json
{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
    "build": {
      "extraInput": ["epiTypes/**"],
      "exclude": ["e2e/**"]
    },
  }
}
```

### Describe alternatives you've considered

Tried to define every input I need by using the `inputs` option inside the   `turbo.json`

**Comment by chris-olszewski** [comment]
This was discussed with the team today and this is a feature that we think would be beneficial.

We're doing some planning next week and will update with more info about timeline/expected API then.
