### ISSUE TITLE
'@repo/eslint-config@*' is not in npm registry

### ISSUE THREAD

**Issue by lifeofsoumya** [vercel/turbo#6815]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

npm install --prefix=apps/web

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

1.1.7

### Describe the Bug

I was trying to install any random package in my turborepo's web directory. The default devDepencies contain : ` "@repo/eslint-config": "*",` Which couldn't be fetched from the npm registry and showed this error.

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@repo%2feslint-config - Not found        
npm ERR! 404
npm ERR! 404  '@repo/eslint-config@*' is not in this registry.
```

### Expected Behavior

While installing anything in the web workspace it was suppose to install all the existing dependencies and the package itself only if it was present in the npm registry.

### To Reproduce

<img width="630" alt="image" src="https://github.com/vercel/turbo/assets/62131036/76c629a4-d7e2-4b25-90d1-7570ac527fa9">
`npm --prefix=apps/web install socket.io-client ` 
This reproduces the error.

**Comment by anthonyshew** [comment]
This won't be a Turborepo issue. 😄

I can do see the same error message, however! Looking through the documentation for the npm CLI, I don't see anything for a `--prefix` flag. 🤔 Possible that it's out of date (or could you point me to it if I just haven't found it)?

Either way, I think the command you might be wanting is `npm install socket.io-client -w web`.

**Comment by denu5** [comment]
@lifeofsoumya where did you deploy to? 

This flag was suddenly in my build settings on vercel: {project}/settings/general and I had failing builds with: Running "install" command: `npm install --prefix=../..`...

1. added my imported packages to transpilePackages: https://stackoverflow.com/a/77686714
2. did some clicks in the ui and removed the prefilled command in the npm field: `npm install --prefix=../..`...

**Comment by anthony-urbina** [comment]
i was using `--workspace=web` and it's shorthand `-w web` and getting the same error. realized that it's because the workspace name in my `package.json` for my `web` folder was `frontend` instead of `web`

**Comment by hamidrezaramzani** [comment]
I got the same `@repo/eslint-config 404 error` when making a Vite project in my monorepo. The problem was the package name — using `ui` caused the error. I changed it to `shared-ui` and it worked.

**Comment by EddyPBR** [comment]
The error when creating the Vite React project with the name web occurs because web is a reserved name or conflicts with NPM packages on some platforms. So just change the root dir name.
