### ISSUE TITLE
Cannot find module @repo/ui error with SvelteKit2

### ISSUE THREAD

**Issue by git-no** [vercel/turbo#6853]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

turbo 1.11.2

### What package manager are you using / does the bug impact?

pnpm in VSC

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

turbo 1.11.2

### Describe the Bug

With SvelteKit Version 2 building the repo throws an error at line

`import { MyCounterButton } from '@repo/ui';`

with message 

`Cannot find module '@repo/ui' or its corresponding type declarations.ts(2307)`

when build is started by 
`pnpm --filter docs build`.

Also VSC show the error at '@repo/ui'.

`turbo build`works`.

The reason could be the new setting by SvelteKit in tsconfig.json of `"moduleResolution": "bundler"` and in package.json of package ui the required new entry:
```json
  "exports": {
    ".": {
      "svelte": "./index.ts"
    }
  },
```
### Expected Behavior

Build without error. 

### To Reproduce

1. Update the Turbo SvekteKit repo to SvelteKit2
2. Build

**Comment by anthonyshew** [comment]
The example is using SvelteKit 1 so I would expect that upgrading a major version of the framework could produce errors out of the box.

It would be great if we got the example upgraded to the current version, though! Happy to take a PR!

**Comment by mcmxcdev** [comment]
I am encountering the same issue with SvelteKit v2, will try to find out the root issue.

**Comment by mcmxcdev** [comment]
@git-no If I am not mistaken I have nailed down the problem.

For now you will need to stick to this (outdated) code in you package.json: 
```
"svelte": "index.ts",
```

If you switch from that logic to:

```
  "exports": {
    ".": {
      "svelte": "./index.ts"
    }
  }
```

The module can't be resolved correctly and throws the TS error.

**Comment by git-no** [comment]
I could probably fix it in my dev repo. Did an update of all modules to ESM.
Repo build with PNPM was successful.

If you want @anthonyshew I would create a PR with my lessons learned.

@mcmxcdev FYI

**Comment by anthonyshew** [comment]
I do think the work I'm about to push in #6920 is going to fix this. Once I have those in, would love for you both to take another look.

**Comment by shinokada** [comment]
For me, I needed to add the following to `apps/web/package.json`:

```
"dependencies": {
		"@repo/ui": "workspace:*"
	},
```
