### ISSUE TITLE
turbo fails to prune workspace app with pnpm pkgmgr

### ISSUE THREAD

**Issue by amitdhiman000** [vercel/turbo#6858]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/amitdhiman000/pnpm-workspace-apps

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

1.11.3-canary.1

### Describe the Bug

Unable to prune the workspace package [@kt/test-app](https://github.com/amitdhiman000/pnpm-workspace-apps/tree/main/services/test-app) for deployment.

```
Turbo error: fs error while pruning: failed to copy file from 
/home/user/pnpm-workspace-apps/packages/math-utils/node_modules/typescript
to
/home/user/pnpm-workspace-apps/out/packages/math-utils/node_modules/typescript
```

### Expected Behavior

1.) turbo prune should work without any errors 
2.) It should copy all the required dependencies along with it.
3.) It should provide a way to resolve symlinks on target machine, something like rushjs [deploy](https://rushjs.io/pages/maintainer/deploying/#handling-links).

### To Reproduce

```
git clone git@github.com:amitdhiman000/pnpm-workspace-apps.git
cd pnpm-workspace-apps
pnpm install
turbo build
turbo prune --scope @kt/test-app
```

**Comment by chris-olszewski** [comment]
I haven't been able to reproduce the error you were seeing. Can you give me the output of `ls -lh /home/user/pnpm-workspace-apps/packages/math-utils/node_modules/typescript`?

**Comment by amitdhiman000** [comment]
@chris-olszewski 
```
ls -lh packages/math-utils/node_modules/typescript
lrwxrwxrwx 1 user user 68 Dec 27 12:05 packages/math-utils/node_modules/typescript -> ../../../node_modules/.pnpm/typescript@5.3.3/node_modules/typescript
```

```
ls -lh node_modules/.pnpm/typescript@5.3.3/node_modules/typescript
total 92K
drwxrwxr-x 1 user user    0 Dec 27 12:05 bin
drwxrwxr-x 1 user user  28K Dec 27 12:05 lib
-rw-rw-r-- 4 user user 9.0K Dec 24 11:13 LICENSE.txt
-rw-rw-r-- 2 user user 3.5K Dec 27 09:02 package.json
-rw-rw-r-- 2 user user 2.8K Dec 27 09:02 README.md
-rw-rw-r-- 2 user user 2.6K Dec 27 09:02 SECURITY.md
-rw-rw-r-- 2 user user  37K Dec 27 09:02 ThirdPartyNoticeText.txt
```

**Comment by chris-olszewski** [comment]
I think #6983 will fix the error you're encountering then.

**Comment by chris-olszewski** [comment]
Closing as I believe this is fixed. Please re-open if the latest canary still has the same issue.
