### ISSUE TITLE
Unable to create a new turbo repo

### ISSUE THREAD

**Issue by Siddharth-2382** [vercel/turbo#6861]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

npx create-turbo@latest

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

1.11.2

### Describe the Bug

**Device and node specifications:**

MacBook Air M1
Node version: v21.5.0
NPM version: 10.2.4

## About the issue
I am trying to start a new turborepo hence I ran the command:

    npx create-turbo@latest

After that it asks where to create and which workspace to use. Everything goes fine until here. 

**The issues that I'm facing are:**
1. It gets stuck at : `Downloading files. This might take a moment.`
<img width="1437" alt="Screenshot 2023-12-29 at 10 29 32 AM" src="https://github.com/vercel/turbo/assets/94699055/e737bab7-e1a9-4385-8810-56faa137f603">

2. When I go inside the repo and take a look at `package.json`, irrespective of what workspace I've selected it shows `pnpm` as package manager.

<img width="819" alt="Screenshot 2023-12-29 at 10 37 08 AM" src="https://github.com/vercel/turbo/assets/94699055/9544e37b-b3da-43d4-af2e-25dc0cc7c73f">

### Expected Behavior

Running `npx create-turbo@latest` should go smoothly and create a new turbo repo with the proper workspace that was selected.

### To Reproduce

Run:

    npx create-turbo@latest

**Comment by anthonyshew** [comment]
I just ran `npx create-turbo@latest` now to make sure that it behaves as expected and had success. 🤔 

I'm wondering if maybe your npm cache got into a bad state somehow. Would you be able to clear your `npx` cache to see if the problem persists? According to [this StackOverflow answer](https://stackoverflow.com/a/66019858/12092649), it looks like you'll use `rm -rf ~/.npm/_npx` for a Unix-based machine or delete `%LocalAppData%/npm-cache/_npx` on Windows.

If that doesn't work, could you clear all of your npm cache with `npm cache clean --force`? This is a little more heavy-handed so definitely try the previous strategy first.

**Comment by anthonyshew** [comment]
I also just noticed that you're using an odd numbered Node.js version. You likely want to switch to an even-numbered version since [odd versions of Node.js are unstable, development releases for the core team to work with and not meant for general use](https://nodejs.org/en/about/previous-releases).

**Comment by Siddharth-2382** [comment]
Okay, so I just tried all the possible solutions you've mentioned but the issue still persists. There is no change in results from before. Is there anything else that I can do?

**Comment by anthonyshew** [comment]
Now looking into the code for `create-turbo`, it looks like we apply a transform to convert to your package manager of choice [here](https://github.com/vercel/turbo/blob/370e78ef6f3d5826798ec2fee659a8cef79f1ca1/packages/create-turbo/src/commands/create/index.ts#L129). Note that that is _after_ you're done downloading the files so the `packageManager` field will only change after the download is complete.

I'm noticing that you've mentioned downloading files appears to be stuck for you. Is it possible that they're still being downloaded such that you need to wait longer? Depending on network speeds, it could take awhile to fetch all the source code onto your machine.

**Comment by Siddharth-2382** [comment]
okay that seems to be taking care about the transformation but I've waited for more 1hr. Whilst on other device it ran within 4-5 mins.

**Comment by anthonyshew** [comment]
Glad you got it sorted! Enjoy!
