### ISSUE TITLE
ESlint not warning about any React mistakes on Next.js

### ISSUE THREAD

**Issue by BrianUribe6** [vercel/turbo#6864]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

The issue occurs on the default template, see reproduction steps

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

1.11.3-canary.1

### Describe the Bug

I've created an empty  project using `npx create-turbo@latest`. After working on it for a while I noticed I was not getting any of the typical react ESlint warnings (useEffect exhaustive-deps, and such). To double check the issues are not specific to my project, I created a new monorepo using `npx create-turbo@latest` again which confirmed that issue is present on the template itself.

The following code contains multiple errors that should trigger warnings (as the default eslint config on Next.js does).

```jsx
import { useEffect, useState } from "react";

function TestESLintShouldWarn(props: { something: number }) {
  const conditionalHook = true;
  useEffect(() => {
    console.log(props.something);
  }, []);

  if (conditionalHook) {
    const [thisShouldWarn, setThisShouldWarn] = useState();
  }
}

export default TestESLintShouldWarn;

```

### Expected Behavior

ESlint react-hooks should trigger on the following snippet of code for a Next.js application:

```tsx
import { useEffect, useState } from "react";

function TestESLintShouldWarn(props: { something: number }) {
  const conditionalHook = true;
  useEffect(() => {
    console.log(props.something);
    // Expect react-hooks/exhaustive-deps WARNING
  }, []);

  if (conditionalHook) {
    // Expect eslintreact-hooks/rules-of-hooks ERROR
    const [thisShouldWarn, setThisShouldWarn] = useState();
  }
}
```

### To Reproduce

1. Create a new monorepo with `npx create-turbo@latest`
2. Create a new file under `apps/web/app`, let's call it  **Test.tsx**.
3. Paste the following snippet (same as above):
```tsx 
import { useEffect, useState } from "react";

function TestESLintShouldWarn(props: { something: number }) {
  const conditionalHook = true;
  useEffect(() => {
    console.log(props.something);
    // Expect react-hooks/exhaustive-deps WARNING
  }, []);

  if (conditionalHook) {
    // Expect eslintreact-hooks/rules-of-hooks ERROR
    const [thisShouldWarn, setThisShouldWarn] = useState();
  }
}```


### Additional context

The error occurs on 1.11.3-canary.1, and also on 1.11.2.

**Comment by BrianUribe6** [comment]
Solved this issue by directly adding `Next.js ESLint configuration, instead of the default Vercel style guidelines provided by the default template.

```diff
- extends: [
-    "eslint:recommended",
-    "prettier",
-    require.resolve("@vercel/style-guide/eslint/next"),
-    "eslint-config-turbo",
  ],
+ extends: ["next", "eslint:recommended", "prettier", "eslint-config-turbo"],
```

**Comment by boompikachu** [comment]
Should we still open this issue? It seems that adding `"next"` eslint is a workaround rather than fixing the problem. Or maybe should we open the issue in https://github.com/vercel/style-guide instead?
