### ISSUE TITLE
Documentation for Prisma/Turbo Integration

### ISSUE THREAD

**Issue by jin-current** [vercel/turbo#6874]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

N/A

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

turbo@1.11.2

### Describe the Bug

Example here: https://turbo.build/repo/docs/handbook/tools/prisma
uses `prisma db push` for migrating DB but the recommended prisma command for migration is `prisma migrate deploy`

https://www.prisma.io/docs/orm/prisma-client/deployment/deploy-database-changes-with-prisma-migrate

There should be a call-out in this documentation on when to use `prisma db push` here (maybe dev only) and noting that `prisma migrate deploy` is the right command for promoting changes to production. 

### Expected Behavior

There should be a call-out in this documentation on when to use `prisma db push` here (maybe dev only) and noting that `prisma migrate deploy` is the right command for promoting changes to production. 

### To Reproduce

Documentation only - no bug.
https://turbo.build/repo/docs/handbook/tools/prisma

<sub>[TURBO-2132](https://linear.app/vercel/issue/TURBO-2132/documentation-for-prismaturbo-integration)</sub>

**Comment by anthonyshew** [comment]
Hey, Jin! `prisma migrate deploy` and `prisma db push` are both options for going to production with Prisma, depending on where your database lives. I've added a small paragraph at the bottom of our documentation to point folks to the right place to sort out this part of their application architecture (namely, the docs for their database).
