### ISSUE TITLE
Can't use shared vite.config.ts in monorepo

### ISSUE THREAD

**Issue by Rusinas** [vercel/turbo#6931]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/Rusinas/vite-shared-config-bug

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

1.11.3

### Describe the Bug

I have a monorepo, where I've got a bunch of Vue apps and I want to share vite.config.ts across all of them. The problem is that I am getting tons of errors and I can't figure it out.

When I try to export shared config and use it, I get the following error:
```
failed to load config from C:\Users\andre\Desktop\Code\Stuff\vite-shared-config\apps\vue-project\vite.config.ts
error when starting dev server:
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for C:\Users\andre\Desktop\Code\Stuff\vite-shared-config\packages\vite-config\src\index.ts
```

Interestingly enough that if I change the import statement from `import { ViteConfigBase } from 'vite-config'` to `import { ViteConfigBase } from '../../packages/vite-config/src/vite.config.base'`, everything will work just fine. But that's only for dev. If I want to build it inside of a Docker container, it will fail. 

Changing the file extension to `.js` is not helping too.  

I don't know if the problem is with Vite or Turborepo, but I am kinda desperate right now and will appreciate any help.

### Expected Behavior

Shared config from the package is working fine. 

### To Reproduce

`cd apps/vue-project`
`npm i`
`npm run dev`
?????
ERROR!

**Comment by chris-olszewski** [comment]
The reproduction repo you linked to doesn't use Turborepo at all and unless the `dev` script in `apps/vue-project/package.json` invokes turbo, then your reproduction steps also don't invoke `turbo`. The error message you provided doesn't look like it's produced by `turbo` either.

Closing as I believe this is an issue with your Vite setup. Feel free to reopen with a reproduction where the failure only happens when `turbo` is used.

**Comment by ampcpmgp** [comment]
I ran into the same problem.
It is discussed here.

https://github.com/vitejs/vite/issues/5370
