### ISSUE TITLE
feat: Refresh on env changes

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [vercel/turbo#6932]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

In my only next.js app next refreshed when I changed my env files. Now since I switched to a monorepo my apps and packages get not refreshed on an env change.

### Describe the solution you'd like

Refresh my app like next did on an env change.

### Describe alternatives you've considered

I have to build my own tool to do that which would be not a nice experience. This should come out-of-the box

**Comment by chris-olszewski** [comment]
Can you clarify what you mean by "refresh"? As in automatically rerun when inputs (such as a .env file changes)? Would #986 address your need?

**Comment by chris-olszewski** [comment]
Closing as a believe this this is a duplicate ask of #986
