### ISSUE TITLE
feat: Throw GH Action error if Playwright fails

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [vercel/turbo#7014]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

As being able to see in this run of the GH Action the tests were failing and the GH Action was passing, but I want that the Action is failing if the tests are not passing.
https://github.com/The-Creative-Programming-Group/Weather-App/actions/runs/7532866046/job/20504296786

### Describe the solution you'd like

I want to see that if my playwright test(s) are failing that my GH Action throws an error.

### Describe alternatives you've considered

-

**Comment by anthonyshew** [comment]
Turborepo should be forwarding the exit signal of the task. If it isn't, that'll be a bug.

Are you able to run this task directly to see if it exits errorfully outside of `turbo`?

**Comment by FleetAdmiralJakob** [comment]
Ok, I created an error on Turborepo: https://github.com/vercel/turbo/issues/7014

**Comment by chris-olszewski** [comment]
I believe the tests did pass and playwright exited with a 0 exit code. The [6 tests that produced errors](https://github.com/The-Creative-Programming-Group/Weather-App/actions/runs/7532866046/job/20504296786#step:7:362) got marked as "flakey" which I'm guessing that means that they failed initially, but succeeded on a [retry](https://playwright.dev/docs/test-retries#retries).

**Comment by chris-olszewski** [comment]
Closing as [this run](https://github.com/The-Creative-Programming-Group/Weather-App/actions/runs/7513745407/job/20455839197#step:7:580) displays that `turbo` properly handles non-zero exit codes when they are present resulting in a failing GH Action.
