### ISSUE TITLE
Publish Turbo generators and use as npm packages?

### ISSUE THREAD

**Issue by mehulkar** [vercel/turbo#7020]
### Discussed in https://github.com/vercel/turbo/discussions/6848

<div type='discussions-op-text'>

<sup>Originally posted by **phuctm97** December 22, 2023</sup>
I want to publish Turbo generators so that me, my team members, as well as others can use the published Turbo generators by just installing an npm package. Is it possible?</div>

**Comment by tknickman** [comment]
Hey @phuctm97, you definitely can do this. 

Here's an example I quickly created - https://github.com/tknickman/composable-generators.

This package stores the generators: https://github.com/tknickman/composable-generators/tree/main/packages/generators

And they're loaded here: https://github.com/tknickman/composable-generators/blob/main/packages/ui/turbo/generators/config.ts#L4

Also, these are just javascript, so you can compose them anyway you like. For example your package could just export functions that match the `PlopTypes.PlopGeneratorConfig` definition, and then you could import those from your shared package and pass them directly to `setGenerator`:

```
import { myGeneratorFunc } from "@repo/shared-generators"

plop.setGenerator(
    "generator-name",
   myGeneratorFunc
  );
```

This works via `load` ([docs](https://github.com/plopjs/plop/blob/main/plop-load.md)) if you're curious about the internals.
