### ISSUE TITLE
hang on MacOS Node16

### ISSUE THREAD

**Issue by unional** [vercel/turbo#7057]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/repobuddy/repobuddy/pull/152
https://github.com/repobuddy/repobuddy/actions/runs/7603548091

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

1.11.4-canary.1

### Describe the Bug

When running the CI on `macos-latest` with NodeJS 16, it hangs when the script completes:

```sh
  Test Suites: 39 passed, 39 total
  Tests:       2 todo, 45 passed, 47 total
  Snapshots:   0 total
  Time:        29.598 s
  Ran all test suites.
// ... hangs ...
```

This also happens at work in some private repos occasionally (it sometimes go through).

But it seems to occur every time in this CI.

### Expected Behavior

Script ends properly.

### To Reproduce

Seems to be specific to macos and Node16.

Here is my turbo.json:

```json
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": [
        "^build"
      ],
      "inputs": [
        "src/**",
        "ts/**",
        "package.json",
        "tsconfig.*"
      ],
      "outputs": [
        "cjs/**",
        "esm/**",
        "tslib/**",
        "*.tsbuildinfo"
      ]
    },
    "build:doc": {
      "dependsOn": [
        "^build"
      ]
    },
    "clean": {
      "cache": false
    },
    "coverage": {
      "dependsOn": [
        "@repobuddy/jest#build",
        "build"
      ],
      "inputs": [
        "src/**",
        "ts/**",
        "package.json",
        "tsconfig.*"
      ],
      "outputs": [
        "coverage/**"
      ]
    },
    "depcheck": {
      "dependsOn": [
        "build"
      ]
    },
    "dev": {
      "cache": false
    },
    "lint": {
      "dependsOn": [
        "^build"
      ],
      "inputs": [
        "src/**",
        "ts/**",
        "package.json"
      ]
    },
    "size": {
      "dependsOn": [
        "build"
      ]
    },
    "test": {
      "dependsOn": [
        "@repobuddy/jest#build",
        "build"
      ],
      "inputs": [
        "src/**",
        "ts/**",
        "package.json",
        "tsconfig.*"
      ]
    },
    "test:list": {
      "dependsOn": [
        "build"
      ],
      "inputs": [
        "src/**",
        "ts/**",
        "package.json"
      ]
    }
  }
}
```

### Additional context

https://github.com/repobuddy/repobuddy/actions/runs/7603468790/job/20705243674

Raw Logs:
https://pipelinesghubeus10.actions.githubusercontent.com/qoBhiCmYCrBG87ARc31AlGNdWTiuZARDXdgMr9hyyjJ9wtK7tJ/_apis/pipelines/1/runs/1017/signedlogcontent/8?urlExpires=2024-01-21T20%3A29%3A27.4976374Z&urlSigningMethod=HMACV1&urlSignature=f1T%2F%2B%2FayOIiZgktv714K52G%2FxUPVw2wcqSs8RtWnEqc%3D

**Comment by NicholasLYang** [comment]
Hi, thanks for the issue. I can't seem to reproduce on my local machine, because I get a task failure around coverage (` Module @swc/jest in the transform option was not found.` is the error if you have any ideas). In the meanwhile, can you run the turbo command with verbose flags applied? I.e. add `-vvv` to the turbo command or prefix the command with `TURBO_LOG_VERBOSITY=3`

**Comment by unional** [comment]
Hi, for `@swc/jest`, it seems like some setting issue. I have added it as a dev deps so that should go away now.

Note that I also can't repro it locally.
But I do experience it from time to time on other private projects on macos and Node16.
This happens to other team members working on those private projects too.

A sad note (or a happy note) is that the latest CI is passing now. So can't repro it atm.

**Comment by unional** [comment]
Trying to enable the Mac + Node16 CI again on latest code to see if this can be repro:

https://github.com/repobuddy/repobuddy/pull/157

**Comment by mehulkar** [comment]
[We support](https://turbo.build/repo/docs/support#nodejs-compatibility) the active and maintenance versions of Node (currently 20 and 18, respectively). If this issue does not reproduce in Node 18, we are unlikely to be able to dedicate any effort to fixing this problem. We may be able to consider a PR, but that is unlikely as well and may take time. I would suggest that you either pin to an older version of turbo or update to a later version of Node.

**Comment by unional** [comment]
It also happen on Node 20
https://github.com/repobuddy/repobuddy/actions/runs/8490047264/job/23260750272

Also encountered it locally on Macbook.

**Comment by unional** [comment]
It is happening to both Node 18 and Node 20
