### ISSUE TITLE
Examples: Prettier not working

### ISSUE THREAD

**Issue by magnusriga** [vercel/turbo#7059]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

Any turborepo example

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

Na

### Describe the Bug

Prettier does not seem to work out of the box.

Do we need to add a prettier entry to package.json, or some other prettier config file, to make it work? If so, do we need to hoist the @vercel/style-guide package up to the root node_modules?

### Expected Behavior

Expected prettier to work out of the box.

### To Reproduce

Deploy any of the turborepo examples.

**Comment by anthonyshew** [comment]
Happy to take a PR!

**Comment by magnusriga** [comment]
I don't have as much experience with PRs, but I'll see what I can do :)

Before I do that, do you know why we do not need to install the plugins that @vercel/style-guide uses under the hood, in our own end user app? E.g. @vercel/style-guide/ESLint/react extends plugin:eslint-plugin-react.

I expected to have to install them in our end user app, or at the very least to hoist them to root, since pnpm default settings is to only allow end user app to access its own direct dependencies, and in ESLint plugis are resolved from the end user app and not from the derived ESLint config where the plugin us loaded.

PS: The only plugins I had to install in the end user app were eslint-plugin-next as well as plugins I added myself (like eslint-plugin-storybook and eslint-plugin-mdx). Which is odd, almost as if the plugins vercel style-guide uses under the hood somehow breaks out of ESLint's plugin resolution algo.

I should understand that first, before making any hoisting suggestions :)

**Comment by anthonyshew** [comment]
I just tested and Prettier is as expected for me.

**Comment by anthonyshew** [comment]
I'm going to mark the dependency resolution question (and my answer here 😄) as off-topic but, to give an answer:

1. When you install a direct dependency, you also install its own listed dependencies.
2. When you install one of your monorepo's packages into another, it can still find its dependencies in the places it is installed so it can work correctly.

**Comment by magnusriga** [comment]
> I'm going to mark the dependency resolution question (and my answer here 😄) as off-topic but, to give an answer:
> 
> 1. When you install a direct dependency, you also install its own listed dependencies.
> 2. When you install one of your monorepo's packages into another, it can still find its dependencies in the places it is installed so it can work correctly.

Thanks, and sorry to ask, but could you be a bit more specific, listing the actual resolution steps?

Folder structure of virtual store:

`node_modules/.pnpm/<name>@<version>/node_modules/<name>`

`package/eslint-config`'s own direct dependencies are installed `package/eslint-config/node_modules`, which symlinks to the virtual store folder listed above.

ESLint plugin resolution for the `web` package is done from `apps/web/.eslintrc.js` and NOT from the config file where the `plugin: eslint-plugin-react` appears (which is in the virtual store). That is a special rule ESLint has about plugin resolution.

From the `apps/web` package, we can access these modules:

1) Its own direct dependencies in: `apps/web/node_modules/<name>`, which in fact resides in the virtual store (`node_modules/.pnpm/<name>@<version>/node_modules/<name>`)

2) Packages directly inside `node_modules` higher in the folder structure, which in our case is the root node_modules.

As noted, ESLint resolves plugins from the derived config, i.e. from the `apps/web` package, and not from the virtual store. Thus, it only searches in (1) and (2).

Do you agree?

**Comment by magnusriga** [comment]
@anthonyshew Following up here. You say Prettier is working on your end, but looking at the basic turbo example I do not see any prettier config pointing to the vercel style-guide prettier package. I.e. there is no `prettier` field in any package.json, and no `prettierrc` config file.

Where exactly did you specify the prettier config, so it uses `@vercel/style-guide/prettier`?

**Comment by magnusriga** [comment]
@anthonyshew I found the reason it works without manually hoisting those packages. There was nothing wrong with my understanding of module resolution or ESLint plugin resolution (thankfully, I thought I was going crazy).

The answer was that[ pnpm's default setting for `public-hoist-pattern` is](https://pnpm.io/npmrc#public-hoist-pattern):

`public-hoist-pattern[]=['*eslint*', '*prettier*']`

**As such, it is crucial that, in the examples, you do not overwrite this setting. You do it the storybook, for instance:**

`public-hoist-pattern[]=*storybook*`

It should be:

`public-hoist-pattern[]=['*eslint*', '*prettier*', '*storybook*']`

Otherwise you will ruin parts of the `@vercel/style-guide` package.

**Comment by magnusriga** [comment]
@anthonyshew Just a note that might be helpful to you in the examples and docs:

I found out that `@vercel/style-guide` uses a community package that changes the behavior of how ESLint resolves plugins, so that it no longer resolves them from the derived package, but instead from the config where the plugin is actually mentioned.

The Vercel team clarified it here: https://github.com/vercel/style-guide/issues/86#issuecomment-1924675205

The package: https://www.npmjs.com/package/@rushstack/eslint-patch

You can use that in your examples, if you want to apply other ESLint plugins without forcing consumers to install them in every package.json in the monorepo.

**Comment by blarson-hearst** [comment]
@magnusriga Sorry, I'm having a little difficulty following along here. What did you end up doing?
