### ISSUE TITLE
FreeBSD support (arm64/x64)

### ISSUE THREAD

**Issue by rskaarup** [vercel/turbo#7083]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Native libraries for FreeBSD. This was dropped in 2022 - but very much missed. 

Last released version was 1.4.7:
[https://www.npmjs.com/package/turbo-freebsd-arm64?activeTab=readme](https://www.npmjs.com/package/turbo-freebsd-arm64)

### Describe the solution you'd like

For native libraries to be available, so FreeBSD can be added as supported platform.

FreeBSD is highly used by at least one of your major benefactors: Netflix

### Describe alternatives you've considered

Staying on version 1.4.7 (last released native library) - but that is not a way forward.

**Comment by mehulkar** [comment]
As of now, we only support Debian-based distributions: https://turbo.build/repo/docs/support, but will take this into consideration. This may be easier when we drop the `--go-fallback` flag and are building _just_ the Rust binary.

**Comment by mehulkar** [comment]
One more thing: Rust itself puts [FreeBSD in Tier 2 with Host Tools tier](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2-with-host-tools) support, which means that it is "guaranteed to build", but the level of support is a lower. I will bring this up in our next team meeting, next week!

**Comment by wesleytodd** [comment]
Hey @rskaarup, if you work at Netflix and are opening this on behalf of work you are doing here can you reach out to me internally? My team is leading up the work on this and if FreeBSD support is important for us then I would like to know that. But to clarify, right now this is not something that our users have actively asked for internally.

**Comment by mehulkar** [comment]
We spoke about this internally at our core team meeting. At the moment, we are leaning towards not officially supporting FreeBSD and asking that you compile from source. If we can determine that this is a large problem for Netflix (or a significant number of other users who upvote this issue), we can reconsider.

**I will leave this issue open for a week or so to hear back on either end.**

In the meantime, if you try to compiling from source and run into any issues, feel free to open another issue or go to Discord/StackOverflow for help. Thanks!

**Comment by rskaarup** [comment]
Thanks for your time! I don't work at Netflix - just an example of a FreeBSD institution. 

Not sure how to compile and install the binary myself - would be happy to do so.
The generic turborepo installs fine with npm on FreeBSD - but it still needs the platform specific binary. If you can provide a guide to how users could compile (and install) that binary, it could expand your user base to multiple platforms. 

I guess Windows and MacOS support is primarily for code-writing purposes. That leaves only debian-based linux distros for production deployment. I know percentage-wise you are decently covered, but in my opinion alternatives should exist. 

Here is a bunch of vote-ups for FreeBSD support 👍👍👍👍👍👍👍👍👍

**Comment by mehulkar** [comment]
> Not sure how to compile and install the binary myself - would be happy to do so.

We probably need to make the instructions more clear, but the starting point is `cd cli && make` and then following the errors. We have a section in the Contributing doc: https://github.com/vercel/turbo/blob/main/CONTRIBUTING.md#building-turborepo, but I am not sure how good it is.

**Comment by mehulkar** [comment]
Thanks for the feedback and all the upvotes @rskaarup 😆 . I've added a note on how we handle unsupported platforms here: https://github.com/vercel/turbo/pull/7276. If you run into trouble compiling, feel free to open a Discussion or try your luck on Discord, but at this time we're not planning to wrap up an npm binary for FreeBSD.
