### ISSUE TITLE
Total Minutes Saved component is a distraction

### ISSUE THREAD

**Issue by aholland** [vercel/turbo#7107]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://turbo.build/repo/docs/handbook/sharing-code/internal-packages

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

months

### Describe the Bug

Sorry to hijack the bug report system but I did click the "Give feedback" link to get here.

I'm working my way through your docs and on each page, ie every time I click, I use developer tools to delete this component off the page, because it's too 'loud'. I get the idea of advertising minutes saved but perhaps months or even years of compute would make for a less frenetic *and* more interpretable figure? I note that your current claim is to have saved about two and a half decades.

<img width="237" alt="image" src="https://github.com/vercel/turbo/assets/1101312/8a655fa1-a111-4c6c-ad7a-dc04cf3e68a2">

### Expected Behavior

asdf

### To Reproduce

Visit the website https://turbo.build/repo/docs/handbook/sharing-code/internal-packages

### Additional context
Workaround: install page manipulator extension and apply the below code as javascript, to the URL https://turbo.build/repo/docs recursively.

```
var element = document.querySelector("#__next > div > div.nx-mx-auto.nx-flex.nx-max-w-\\[90rem\\] > nav > div > div > a.group.mt-4.rounded-lg.border.border-transparent.overflow-hidden.bg-origin-border.bg-gradient-to-r.from-red-500.to-blue-500.dark\\:text-\\[\\#9ca3af\\].text-\\[\\#6b7280\\] > div");
if (element) {
    element.style.display = 'none';
}
```

**Comment by anthonyshew** [comment]
What a coincidence. I just had this same thought the other day.
