### ISSUE TITLE
Packages brake when using Turborepo with different dependency versions

### ISSUE THREAD

**Issue by magnusriga** [vercel/turbo#7134]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/magnusriga/turbo-tailwind

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

turbo 1.11.3

### Describe the Bug

If the monorepo has two apps, e.g. `docs` and `web`, and they use different versions of key packages (like `nextjs`), various external packages break.

Below is an example with storybooks. I have also experienced the issue with other tools/external npm packages. I believe they might somehow grab the wrong version of nextjs (or whichever package it needs that the two apps have differing versions of).

### Expected Behavior

Expected storybooks to work for package `foo`, regardless of which `nextjs` version the unrelated app `bar` uses.

### To Reproduce

Here is a minimal repo: https://github.com/magnusriga/turbo-tailwind

To reproduce the bug:

1. Run `pnpm i` in the root folder
2. Run `pnpm storybook` from the `apps/foo` folder

As seen, `pathname` from the external package is `null` (go to the console in dev tools and see the printout).

To fix the issue, just change the `next` dependency in `bar`'s package.json from `^13.5.6` to `latest`. Now do the first two steps above again (running `pnpm i` again is crucial), and voila it works.

The bizarre thing here is that changing the package version for a package that does not have anything to do with storybooks here, will break it. So, the issue has to be with package structure in pnpm and turborepo.

**Comment by magnusriga** [comment]
I saw this from [your docs](https://turbo.build/repo/docs/handbook/troubleshooting#handling-mismatched-package-versions):

> Mis-matched dependencies in different repositories can mean that code runs unexpectedly. React, for instance, will error if there is more than one version installed.

Does that mean all packages should have the same versions of all common dependencies, at all time?

If so, that becomes near impossible to manage, because we use GitHub Actions (dependabot) to update dependencies, which I do not think takes care of all packages at the same time (not 100% sure there).

**Comment by anthonyshew** [comment]
Turborepo doesn't have a hand in package management today so doesn't play a role here. These are package managers' concerns.

We do want to play a role in helping to manage dependency version in the future but, today, you likely want to refer to the documentation of the package manager that you are using.

**Comment by magnusriga** [comment]
@anthonyshew Understood, I will check in with Zoltan over at pnpm.

**Comment by magnusriga** [comment]
In case helpful to others, I ended up solving it with this package: https://www.npmjs.com/package/syncpack

It works well.
