### ISSUE TITLE
Document --profile flag

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turbo#717]
### Describe the feature you'd like to request

`--profile` is missing from CLI reference. It exports a profile.json that can folks evaluate `turbo` execution in Chrome or Edge DevTools or chrome://tracing tabs

### Describe the solution you'd like

- Add to CLI reference
- Add dedicated page in features

### Describe alternatives you've considered

n/A

**Comment by mehulkar** [comment]
Is `--cpuprofile` the same as the `--profile` mentioned here? https://turborepo.org/docs/reference/command-line-reference#--cpuprofile

**Comment by seanlaff** [comment]
No, the `--cpuprofile` outputs a heatmap of cpu utilization for use in something like speedscope. The `--profile` command produces output that you can drop in `chrome://tracing`.

The former lets you see where cpu time is being spent (including all of turbo's internal go code), whereas the later shows the actual timeline of execution (order of stages, which are parallel, the duration of each, etc) of your project's turborepo stages.

Your average user would definitely be more interested in `--profile`, so I think it deserves some docs.
