### ISSUE TITLE
Support task colors on Windows

### ISSUE THREAD

**Issue by chris-olszewski** [vercel/turbo#7176]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

`npx create-turbo@canary color-test pnpm && cd color-test && turbo build`

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

`1.12.0`

### Describe the Bug

Currently that only output colors if hooked up to a TTY won't output colors on Windows.

### Expected Behavior

Tools such as `next` should output colors when invoked via `turbo` on Windows

### To Reproduce

`npx create-turbo@canary color-test pnpm && cd color-test && turbo build`

**Comment by Bejasc** [comment]
Experiencing this as an issue.

Colours work fine on my Windows 10 and Windows 11 environment, when running `npm x` or `pnpm x` directly for the individual apps.

It's only when I run `pnpm x` at the root level (which in turn runs `turbo` that I lose all colours on my Windows 10 environment. 

To reiterate; Colours work fine in the same environment, when the process is **not** run through `turbo`.

---

Also of note; this also impacts *any* colours output the the console. I use `colorette` in my logger implementation, which works in all environments when run directly with `npm` or `pnpm` - but colour is shown only as the ANSI codes when it is run through `turbo`

**Comment by chris-olszewski** [comment]
@Bejasc Which console are you running your programs in? Also, can you verify that you have the same issue with the latest canary?

**Comment by Bejasc** [comment]
@chris-olszewski I am using powershell inside the vscode terminal, running Windows 10. 

I have followed the exact reproduction steps from your original report, and can confirm that colours are **working correctly**, targeting turbo `1.12.3-canary.0`.

Updating my existing project to use the same version of turbo (previously this was `1.11.3`) - the issue also appears to be resolved.

I did notice that, while using `1.11.3` - _some_ output was colored, before it was dropped. entirely. 
![image](https://github.com/vercel/turbo/assets/12091874/2dc3b3f8-8aba-4203-892b-e4e25fb01a3e)



`1.12.3-canary.0` appears to have a solution?

**Comment by chris-olszewski** [comment]
That's very interesting output, I wonder if one of the underlying tools is messing with Windows VT100 processing.

I'll mention that this is still an issue for Windows as some tools will only output colors if they are hooked up to a pseudoterminal and I'm still working on interfacing with ConPTY.

**Comment by anthonyshew** [comment]
Huge, LFG. @chris-olszewski
