### ISSUE TITLE
Vite dev server closing unexpectedly

### ISSUE THREAD

**Issue by mauricewegner** [vercel/turbo#7181]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

npx create-turbo@latest -e with-vite

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

1.12.0

### Describe the Bug

When running `turbo run dev` the Vite dev server starts up correctly but instantly finishes the task and closes itself unexpectedly.

### Expected Behavior

The Vite dev server should keep running until closed manually.

### To Reproduce

1. Clone the vite example: `npx create-turbo@latest -e with-vite`
2. Run `pnpm dev` (`turbo run dev` with the selected pkg manager)

**Comment by recallwei** [comment]
+1

**Comment by wernher-mercury** [comment]
+1

**Comment by GGBeng1** [comment]
+1

**Comment by erich2s** [comment]
+1

**Comment by gudleik** [comment]
Version 1.12.1 fixed it almost, but having same issue when using --filter, like `turbo run dev --filter xyz`

**Comment by gudleik** [comment]
ah, sorry for not reading the release log.. I just noticed the PR was merged and a new version was out. 

At least version 1.12.2 works as a charm ❤️

**Comment by kamil-maslowski** [comment]
I'm on 1.12.2 here and it still happens...

**Comment by taschetto** [comment]
> I'm on 1.12.2 here and it still happens...

Same

**Comment by kamil-maslowski** [comment]
@chris-olszewski can we please get any help on this? 1.12.2 still has the issue, and as you can see I'm not the only one...

**Comment by gudleik** [comment]
Did you add `persistent: true` to the task in turbo.json?
