### ISSUE TITLE
Add Vercel deploy button to examples

### ISSUE THREAD

**Issue by lfades** [vercel/turbo#719]
### Describe the feature you'd like to request

Vercel's [Deploy Button](https://vercel.com/docs/deploy-button) can used to quickly setup a monorepo examples on production. Using the configuration in the documentation page it should get back the expected deploy button URL, however there are some additional settings that can be added as query params and are not documented yet: `root-directory`, `build-command`, `dev-command` and `install-command`, which match their equivalent settings in Vercel's dashboard:

![image](https://user-images.githubusercontent.com/4278345/153500867-7c95667f-e267-41d1-ba13-92e5fc00cb0c.png)

### Describe the solution you'd like

Deploying a monorepo to be as easy as clicking a button.

### Describe alternatives you've considered

NA

**Comment by mehulkar** [comment]
This is done now https://turbo.build/repo/docs/getting-started/from-example
