### ISSUE TITLE
Error after upgrading to 1.12.2

### ISSUE THREAD

**Issue by semmywong** [vercel/turbo#7202]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

none

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

turbo 1.12.2

### Describe the Bug

The error after upgrading turbo to 1.12.2, which worked fine before with 1.11.3

```

(base) PS D:\WorkStudio\web\mine\fulfillment-fe> pnpm build

> fulfillment-fe@0.0.1 build D:\WorkStudio\web\mine\fulfillment-fe
> turbo run build

Turborepo did not find the correct binary for your platform.
We will attempt to install it now.
Installation has failed.

***

Turborepo failed to start.

Turborepo detected that you are running:
windows 64

***

We were not able to find the binary at:
turbo-windows-64/bin/turbo.exe

We looked for it at:
D:\WorkStudio\web\mine\fulfillment-fe\node_modules\.pnpm\turbo@1.12.2\node_modules\turbo\bin\node_modules
D:\WorkStudio\web\mine\fulfillment-fe\node_modules\.pnpm\turbo@1.12.2\node_modules\turbo\node_modules
D:\WorkStudio\web\mine\fulfillment-fe\node_modules\.pnpm\turbo@1.12.2\node_modules
D:\WorkStudio\web\mine\fulfillment-fe\node_modules\.pnpm\node_modules
D:\WorkStudio\web\mine\fulfillment-fe\node_modules
D:\WorkStudio\web\mine\node_modules
D:\WorkStudio\web\node_modules
D:\WorkStudio\node_modules
D:\node_modules
D:\WorkStudio\web\mine\fulfillment-fe\node_modules\.pnpm\turbo@1.12.2\node_modules\turbo\bin\node_modules
D:\WorkStudio\web\mine\fulfillment-fe\node_modules\.pnpm\turbo@1.12.2\node_modules\turbo\node_modules
D:\WorkStudio\web\mine\fulfillment-fe\node_modules\.pnpm\turbo@1.12.2\node_modules
D:\WorkStudio\web\mine\fulfillment-fe\node_modules\.pnpm\node_modules
C:\Users\Administrator\.node_modules
C:\Users\Administrator\.node_libraries
C:\Program Files\nodejs\lib\node

***

We did not find any binaries on this system.
This can happen if you run installation with the --no-optional flag.

***

If you believe this is an error, please include this message in your report.
 ELIFECYCLE  Command failed with exit code 1.
(base) PS D:\WorkStudio\web\mine\fulfillment-fe>
```

### Expected Behavior

Expect to compile worded fine

### To Reproduce

See bug description

**Comment by Vvaraz** [comment]
The identical issue.

**Comment by gsoltis** [comment]
I've verified that both the latest canary, `1.11.4-canary.4` and latest patch, `1.12.2` of `turbo-windows-64` contain the correct binary. Can you verify that you have a version of `turbo-windows-64` that matches the version of `turbo` in your `node_modules`? 

Can you verify that you are installing with optional dependencies? i.e. not passing `--omit optional` or equivalent when installing?

**Comment by Vvaraz** [comment]
There are certain issues present on my machine. According to the turbo.js code, when it is unable to detect the binary, it will execute
`function installUsingNPM(){}` 
and install it in the directory represented by
 `const turboPath = path.dirname(require.resolve('turbo/package'))`.
  However, on my machine, running the command `npm install --loglevel=error --prefer-offline --no-audit --progress=false` in this directory does not have any effect.
It seems that the binary listed under `optionalDependencies` in the `package.json` file have not been installed.

I have now modified the code in such a manner that it is functioning properly.

```javascript
- function installUsingNPM() {
+ function installUsingNPM(platform,resolvedArch) {
   const turboPath = path.dirname(require.resolve('turbo/package'));

   const env = { ...process.env, npm_config_global: undefined };
 
   child_process.execSync(
-    `npm install --loglevel=error --prefer-offline --no-audit --progress=false`,
+    `npm install turbo-${platform}-${resolvedArch} -D --loglevel=error --prefer-offline --no-audit --progress=false`,
     { cwd: turboPath, stdio: "pipe", env }
   );
 }
```

**Comment by semmywong** [comment]
> I've verified that both the latest canary, `1.11.4-canary.4` and latest patch, `1.12.2` of `turbo-windows-64` contain the correct binary. Can you verify that you have a version of `turbo-windows-64` that matches the version of `turbo` in your `node_modules`?
> 
> Can you verify that you are installing with optional dependencies? i.e. not passing `--omit optional` or equivalent when installing?

I cannot find `turbo-windows-64` in global `node_modules`

**Comment by semmywong** [comment]
Upgrade to 1.12.3 is working
