### ISSUE TITLE
Deleted a workspace but Turborepo still trying to read its package.json

### ISSUE THREAD

**Issue by anthonyshew** [vercel/turbo#7245]
### Discussed in https://github.com/vercel/turbo/discussions/7186

<div type='discussions-op-text'>

<sup>Originally posted by **danielhep** January 30, 2024</sup>
I deleted a workspace from my pnpm Turborepo project, but now whenever I run any `turbo run` command I get the following error:
` ERROR  run failed: unable to parse workspace package.json: unable to read package.json: failed to open file '/Users/danielhep/git/otp-frontend/packages/leg-chip/package.json'`

I searched my entire project for references to the `leg-chip` workspace but nothing comes up. I don't know where it's coming from!</div>

**Comment by elamandeep** [comment]
I created a project using Turborepo yesterday. Within the packages directory, I initially created a component package inside package workspace. However, after renaming the folder from "component" to "core," I've been encountering an error. I even made necessity changes in my other packages. Still I'm getting same error. I even again created fresh project but after running turbo dev command. I'm getting same error

Here's my repo link https://github.com/elamandeep/ivy

```  
ivy@ dev /home/elamandeep/Desktop/Projects/ivy
    turbo dev

    ERROR  run failed: unable to parse workspace package.json: unable to read ?>package.json: failed to open file /home/elamandeep/Desktop/Projects/ivy/packages/components/package.json
     ELIFECYCLE  Command failed with exit code 1.
```

**Comment by tkore** [comment]
Having the same exact issue with latest turborepo version.

**Comment by tkore** [comment]
As per the discussion in https://github.com/vercel/turbo/discussions/7186, using version 1.12.2 does solve the issue

**Comment by danielhep** [comment]
Quote from my post in the discussion: 
I was finally able to fix this. I found some documentation that I can't find again that mentioned not putting internal monorepo dependencies inside the package.json at the top level of the repo. I checked and sure enough, at some point I had added some internal dependencies there. Removing them and rerunning pnpm install fixed the issue for me. I am not sure what the linkage is between this mistake on my part and the issue I was encountering- some kind of caching thing?

Given how obscure this bug was and difficult to track down, I think there should be some checks in turborepo that warn people who put internal dependencies at the top level. @anthonyshew

**Comment by msdit** [comment]
I solved my problem by run
```
pnpm install
```

**Comment by luizfelmach** [comment]
Same issue here. turbo version: 1.12.2

**Comment by luizfelmach** [comment]
Updates. I solved this by deleting the /tmp/turbod folder

I figured this could be a cache, so I looked in all the folders on my pc that had something to do with the turbo.

**Comment by anthonyshew** [comment]
@danielhep We're thinking that this is actually a deeper issue with our daemon. We're looking into this.

**Comment by sinbad-io** [comment]
I have the same issue.

**Comment by jannikwienecke** [comment]
same issue!

**Comment by edersonmberti** [comment]
I have the same issue.

**Comment by Fred-O-Nyarko** [comment]
I have the same issue. I'm on Apple M2 and Sonoma 14.2.1.
All I did was restart my machine and issue got resolved.

**Comment by mehulkar** [comment]
Try `turbo daemon restart` to see if that fixes things, that would help narrow down whether it's a daemon issue or not

**Comment by requiel20** [comment]
@mehulkar 

turbo daemon restart
Turbo error: unable to connect: unable to make handshake: bad grpc status code: Unknown error

**Comment by requiel20** [comment]
I managed to fix the issue by running `turbo daemon clean` 🎉

**Comment by sinbad-io** [comment]
> I have the same issue. I'm on Apple M2 and Sonoma 14.2.1.
> All I did was restart my machine and issue got resolved.

This did the job for me as well.

**Comment by axeen** [comment]
Was having the same issue

@mehulkar 
> turbo daemon restart

Tried this. Hadn't installed `turbo` globally so had to do that first. Then got 
```
Turbo error: unable to connect: daemon is not running
```
but now it works 🤷

**Comment by chris-olszewski** [comment]
As of `1.12.3` this should no longer be an issue due to https://github.com/vercel/turbo/pull/7290
Please reopen if you encounter this with 1.12.3 or newer

**Comment by mixn** [comment]
Neither `turbo daemon restart`, nor `turbo daemon clean` worked for me, but rebooting my machine did. Thanks, all!

**Comment by michael-land** [comment]
@chris-olszewski This happened again in turbo 2.0 with `turbo watch` command. solved by `turbo daemon restart`

**Comment by franher** [comment]
> turbo daemon clean

It worked for me; I did `npx turbo daemon clean` to avoid installing `turbo` globally.

**Comment by seaders** [comment]
This situation (or something very like it) has just happened to me.

The solution for me was to jump into the package-lock.json file and delete the reference that was there to my deleted dependency which was a workspace in a monorepo.  Turbo didn't see it any more, it wasn't there in my npm cache, but there was still a reference to `apps/web2` in package-lock.json.  Deleting it from there got rid of this issue for me.
