### ISSUE TITLE
Wait for output path to exist before running the script

### ISSUE THREAD

**Issue by egoist** [vercel/turbo#725]
### Describe the feature you'd like to request

I use Turbo to run dev scripts:

```bash
turbo run dev --parallel --no-cache --scope=package-a --include-dependencies
```

The problem is package A might depend on the output files of package B:

-  with `--parallel` it ignores all that, so A's dev script will fail for the first time
- without `--parallel` only the `dev` script of A's dependencies get executed.

Relevant `turbo.json`:

```json
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": ["^build"]
    },
    "test": {
      "dependsOn": ["build"]
    },
    "dev": {
      "dependsOn": ["^dev"],
      "cache": false
    },
    "lint": {}
  }
}
```

### Describe the solution you'd like

Maybe the `output` option should be taken into account when running the script.

### Describe alternatives you've considered

Writing some custom script to execute the dev script for now

**Comment by gsoltis** [comment]
I'm interested in possible solutions to this. Just watching the outputs seems like it could still have problems with partially complete compilations or file copies. I wonder if there are other signals we could use to know when a compilation pass has completed?

**Comment by Ghirigoro** [comment]
Any chance of getting an API for generating/handling custom events to drive the execution of pipelines? Given the number of scenarios/tools Turborepo would be used with, I doubt there's any proxy that can reliably represent the end of watch events. I can imagine that API being a total bear 🐻 to write, but I'd imagine it would make Turborepo a lot more flexible.

**Comment by daividh** [comment]
I think it's related to [460](https://github.com/vercel/turborepo/issues/460).

**Comment by mehulkar** [comment]
Closing in favor of an issue that has more conversation already https://github.com/vercel/turbo/issues/986
