### ISSUE TITLE
support stable Rust toolchains

### ISSUE THREAD

**Issue by ognevny** [vercel/turbo#7252]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

add support for stable rust toolchains

### Describe the solution you'd like

don't use unstable or anything that is related to nightly Rust

### Describe alternatives you've considered

if one wants to build turbo with stable Rust there is no alternatives

**Comment by NicholasLYang** [comment]
Hi @ognevny, could you provide a reason for why you'd like to build turbo on stable? To be frank, both turborepo and turbopack make heavy use of nightly features, so this is likely not feasible in the near future.

**Comment by ognevny** [comment]
> Hi @ognevny, could you provide a reason for why you'd like to build turbo on stable? To be frank, both turborepo and turbopack make heavy use of nightly features, so this is likely not feasible in the near future.

I want to provide it in [msys2](https://msys2.org/) distribution. we don't provide nightly Rust toolchain

**Comment by chris-olszewski** [comment]
We appreciate the interest of packaging `turbo` for msys2 distribution, but removing our usage of nightly would be a large undertaking that we won't be prioritizing.

**Comment by ognevny** [comment]
ok, I fully understand your opinion. hoping the things will get stable soon

**Comment by jirutka** [comment]
I’d like to ask the same, for the Alpine Linux package.
