### ISSUE TITLE
noEmit or isInvalidated option / interop with vercel's Ignore Build Step feature

### ISSUE THREAD

**Issue by qdozaq** [vercel/turbo#732]
### Describe the feature you'd like to request

Essentially want to be able to run turbo and have it tell me if anything has been invalidated, but not actually build anything.
Similar to how typescripts `tsc --noEmit` validates types without actually building them.

I think that feature by itself would be useful, but more specifically for vercel's [ignore build step](https://vercel.com/support/articles/how-do-i-use-the-ignored-build-step-field-on-vercel) feature this would be ***extremely useful***

### Describe the solution you'd like

So if I wanted to fill out the `Ignore Build Step` field in a vercel build I'd like to be able to do something like this:

```bash
turbo --scope="my-app" --include-dependencies --noEmit --quite
```

where `--noEmit` says don't build anything just tell me if anything is invalidated
and `--quite` removes any output and exits with a 0 if there are invalidated packages

(these could of course be wrapped up together into their own flag as well)

The end result being only starting a build pipeline if the targeted package has changed or any of its upstream dependencies have changed.

### Describe alternatives you've considered

I _could_ get around this currently by adding a npm script like this to each package.json:
```json
{
  "cached": ":"
}
``` 
and then this to my turbo config
```json
{
      "cached": {
        "dependsOn": [
          "^cached"
        ]
      },
}
```

and then parse the output of `turbo run cached --scope="my-app" --include-dependencies` to determine if I should exit with 0 or not, but that all seems like a cumbersome way to do this.

**Comment by mehulkar** [comment]
There's a [`--dry`](https://turbo.build/repo/docs/reference/command-line-reference/run#--dry----dry-run) and `--dry=json` flag now that does this!
