### ISSUE TITLE
Turborepo 1.12.x stopped passing command input to Vite dev server

### ISSUE THREAD

**Issue by jacobcarpenter** [vercel/turbo#7332]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/vercel/turbo/tree/main/examples/with-vite

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

turbo@1.12.3-canary.0

### Describe the Bug

Vite's dev server is interactive. It accepts commands to perform operations like **open the browser** (`o`) and **restart the server** (`r`).

Turborepo 1.11.3 passes terminal input along to a dev server that was started through `turbo dev`.

Turborepo 1.12.3 however no longer seems to pass the terminal input along to the dev server instance. The keyboard input is echoed to the terminal, but does not seem to be passed along to the persistent task. This is a unfortunate disruption to a convenient workflow.

### Expected Behavior

After starting the vite dev server via turbo, pressing `o`, then `Enter` opens the browser.

### To Reproduce

Install the vite example and run `yarn dev`; once the servers start, hit `o` and press Enter. Notice that nothing happens.

Next run
```
yarn add turbo@1.11.3 -W
```
... or whatever the appropriate command to downgrade the workspace root dependency in your preferred package manager is.

Then repeat the `yarn dev` followed by `o` and Enter. Notice that the browser opens to the dev server.

**Comment by chris-olszewski** [comment]
Turbo `1.11` unintentionally spawned all tasks with inherited `stdin`. This was fixed in 1.12 and now that `turbo` is spawning tasks hooked up to a psuedoterminals we cannot spawn tasks that inherit `turbo`'s `stdin`.

Proper support for interactive tasks is coming with 1.13.

**Comment by Shay-repos** [comment]
Bump

**Comment by chris-olszewski** [comment]
With 1.13 this is now fixed with the new UI: https://turbo.build/blog/turbo-1-13-0#new-terminal-ui
