### ISSUE TITLE
[VS Code Extension] Hints shouldn't be problems

### ISSUE THREAD

**Issue by alan-nf** [vercel/turbo#7394]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

n/a

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

n/a

### Describe the Bug

The VS Code extension (published 2024-01-25, 22:07:10) shows helpful tooltips as problems:

<img width="638" alt="image" src="https://github.com/vercel/turbo/assets/100322190/2fd83728-d007-4c32-8045-25ced4a19953">

I get the desire to show tooltips but surfacing them as problems clutters the UI and makes me always have active problems I can't resolve in the problems pane:

<img width="703" alt="image" src="https://github.com/vercel/turbo/assets/100322190/e458f24a-6b33-42a4-9832-df5b2652c1ea">

### Expected Behavior

The more semantic place to stick these is in inlay hints, which are bits of helpful text that can be rendered in the editor without declaring them as problems. [This is the API](registerInlayHintsProvider). [This is the feature documentation](https://code.visualstudio.com/docs/typescript/typescript-editing#_inlay-hints). Here's what it looks like:

![image](https://github.com/vercel/turbo/assets/100322190/10ee1e9a-a25f-4936-b511-74c54638e9c7)

Hot take: if inlay hints aren't good enough, this feature should probably just be removed from the extension. Cluttering up the Problems pane, with even helpful information, isn't worth it.

### To Reproduce

1. Install VSCode turborepo extension: https://marketplace.visualstudio.com/items?itemName=Vercel.turbo-vsc
2. Open turbo.json
3. Make sure the `build` task depends on `^build`. You should see the `^build` text get a problem from the extension.

**Comment by arlyon** [comment]
Thanks for the detailed report. Point taken, the 'perma-clutter' in the problems view is unnecesarry. I actually didn't know that the informational diagnostics would be displayed as a 'problem' in VSCode. Seems a little contradictory.

I have added a PR that addresses this, and adds a few more goodies in the process. Thanks for taking the time to report!

**Comment by alan-nf** [comment]
The HINT looks great. No issues in my problem pane and you are right that it's less noisy than inlays.

Thank you!
