### ISSUE TITLE
[VS Code Extension] `turbo.path` setting not used to run turborepo

### ISSUE THREAD

**Issue by alan-nf** [vercel/turbo#7395]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

n/a

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

n/a

### Describe the Bug

The VS Code extension (published 2024-01-25, 22:07:10) let's you run pipelines directly from turbo.json:

<img width="193" alt="image" src="https://github.com/vercel/turbo/assets/100322190/0c21b324-3a82-47dc-8d26-5b6fcd065463">

This results in the command `turbo run graphql:introspect` being run, regardless of what the `"turbo.path"` setting is configured to. Since I don't have a global `turbo` command, this fails for me:

<img width="221" alt="image" src="https://github.com/vercel/turbo/assets/100322190/1b70a7bf-db13-4e76-8d24-604e859b64ae">

### Expected Behavior

I would expect the "Run graphql:introspect" button to run the turbo I have in `turbo.path`. So, if I have this config setting in .vscode/settings.json:

`"turbo.path": "./node_modules/.bin/turbo"`

I would expect the button to run:

`./node_modules/.bin/turbo run graphql:introspect`

### To Reproduce

1. Install VSCode turborepo extension: https://marketplace.visualstudio.com/items?itemName=Vercel.turbo-vsc
2. Create a .vscode/settings.json and set it to:
```json
{
  "turbo.path": "./node_modules/.bin/turbo"
}
```
4. Open your turbo.json
5. Click the "Run ..." button above any task:
<img width="193" alt="image" src="https://github.com/vercel/turbo/assets/100322190/36e52866-0920-4e95-b07a-217425a39f12">

**Comment by arlyon** [comment]
Nice catch. PR up now!

**Comment by alan-nf** [comment]
Fix confirmed, ty!
