### ISSUE TITLE
[VS Code Extension] Extension can't load anymore

### ISSUE THREAD

**Issue by alan-nf** [vercel/turbo#7413]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

n/a

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

n/a

### Describe the Bug

Thank you so much for fixing my bug reports, and so quickly. (and for the extension in the first place)

Unfortunately, it looks like the v1.1.0 update may have broken something for me. Here's what I'm seeing:

<img width="480" alt="image" src="https://github.com/vercel/turbo/assets/100322190/18ce195e-a8b5-438c-9e08-3eff6ffd99b8">

Output:

> [Error - 8:22:36 PM] Turborepo Language Server client: couldn't create connection to server.
> Launching server using command /Users/anorbauer/.vscode/extensions/vercel.turbo-vsc-1.1.0/out/turborepo-lsp-darwin-arm64 failed. Error: spawn /Users/anorbauer/.vscode/extensions/vercel.turbo-vsc-1.1.0/out/turborepo-lsp-darwin-arm64 EACCES

### Expected Behavior

Extension loads successfully 

### To Reproduce

I'm not really sure what I'm doing to reproduce this. I'm on the latest VS Code (not insiders), macOS, and I have turbo@1.12.3 installed as a local npm package. Let me know how I can help to try and reproduce if you can't.

**Comment by alan-nf** [comment]
Things I've tried to fix:

* Restart VS Code
* Reinstall extension
* Kill turbo process manually, reload VS Code window

Things I've noticed:

* Despite the error, a `turbo` process _is_ starting

**Comment by chaseholdren** [comment]
`chmod ug+x ~/.vscode-server/extensions/vercel.turbo-vsc-1.1.0/out/turbo*`

this fixed it for me

**Comment by arlyon** [comment]
Hm, seems like the binaries have bad permissions, I will audit and push a new release.

**Comment by arlyon** [comment]
Released 1.1.1 to resolve this, thanks for the report!

**Comment by alan-nf** [comment]
That did the trick, thank you so much!

**Comment by supernaut** [comment]
Still an error for me with version 1.1.1 on Mac. `turborepo-lsp-darwin-arm64` is running (seven processes if that's relevant) but still get the errors. The files in `~/.vscode/extensions/vercel.turbo-vsc-1.1.1/out` seem to have the right permissions.

```
[Info  - 13:59:36] root uri: /var/folders/_d/wx7mv5697qs0qm7kg3p6m1t00000gn/T/turbod/c8c8b14cb52a1902/turbod.sock
[Error - 13:59:43] failed to connect to daemon: timeout while watching directory: deadline has elapsed
[Error - 13:59:43] Server initialization failed.
  Message: Internal error
  Code: -32603 
[Error - 13:59:43] Turborepo Language Server client: couldn't create connection to server.
  Message: Internal error
  Code: -32603 
```

**Comment by BlueBazze** [comment]
Im getting same errors as supernaut
```
[Info  - 11:44:42 AM] root uri: /tmp/turbod/bf1fb3149d6ade5f/turbod.sock
[Error - 11:44:49 AM] Server initialization failed.
  Message: Internal error
  Code: -32603 
[Error - 11:44:49 AM] Turborepo Language Server client: couldn't create connection to server.
  Message: Internal error
  Code: -32603 
[Error - 11:44:49 AM] failed to connect to daemon: timeout while watching directory: deadline has elapsed
```

A few pop ups show up.
`Server Initialization failed.`
`Internal error`
`{"code":127,"killed":false,"signal":null,"cmd":"/home/{user}/.volta/bin/turbo\n daemon start"}` (i've replaced my computer username with "{user}")

OS: Ubuntu 23.10
The commands works fine when i manually run them in the terminal. Did try to `chmod ug+x` the extension binaries as mentioned in one of the other comments, but it did not change anything.

Did wonder what the `\n` in the message is doing. Because if it is being included in the command being run, then the command would obviously fail. But it might also just be used to display the popup message.
![image](https://github.com/vercel/turbo/assets/11636062/f4f26362-ce72-413e-bfb3-353acf744fba)

**Comment by TylerNRobertson** [comment]
This issue is still present, probably should re-open this one

**Comment by arlyon** [comment]
Thanks for raising I'll re-open and take a look next week :)

**Comment by arlyon** [comment]
Ok, so these are technically two separate issues. The first issue was a genuine problem with the LSP, the second is an issue with the turborepo daemon. I am going to close this again in favour of https://github.com/vercel/turbo/issues/4608 (and fix that issue :) )
