### ISSUE TITLE
[VS Code Extension] Remove global `turbo` requirement

### ISSUE THREAD

**Issue by alan-nf** [vercel/turbo#7425]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Feature Request: make the extension just gracefully, and silently, be quiet if it can't talk to the turbo server.

Explanation:

I work in an environment where npm/node are never installed globally and are driven by project installations. I cannot install `turbo` globally through npm, as I don't have a global npm installation.

In my turborepo-powered monorepo I added this to my `.vscode/settings.json` workspace settings to make it so that the extension works fine:

```json
{
  "turbo.path": "./node_modules/.bin/turbo"
}
```

And this works great! Except when I load up a repository that either doesn't have turbo or doesn't have this setting:

<img width="572" alt="image" src="https://github.com/vercel/turbo/assets/100322190/04b73ef5-7a68-4879-964a-ee690c111986">

### Describe the solution you'd like

I would love it if the extension just gracefully, and silently, was quiet if it can't talk to the turbo server.

Bonus points: you can have some kind of error/warning if I open a turbo.json file and the extension is off/not functioning.

### Describe alternatives you've considered

I'm trying out the extension and dealing with the annoyance of dismissing the errors when I open my non-turborepo projects. It's not killing me yet!

**Comment by arlyon** [comment]
Thanks for the patience while we sort out the various edge cases :) Assuming global turbo simplifies the logic but I do see there are probably cases (shared machines, or your scenario) where that is infeasible. I'll see if I can brainstorm some solution.

**Comment by weyert** [comment]
Yeah, having the same issue even when I globally install the turbo package. Maybe it's related to my use of `asdf` to manage Node.js

**Comment by arlyon** [comment]
Heyo, new version with some better detection logic is being reviewed as we speak :)
