### ISSUE TITLE
Docs: Extend Kitchen Sink example with dependencies like Mongodb

### ISSUE THREAD

**Issue by leetmachine** [vercel/turbo#7517]
### What is the improvement or update you wish to see?

The Kitchen Sink example shows a package `logger` being used in a server context but the example does not expand to a use case that has a package with its own dependencies. I've attempted to add Mongodb to the logger package, and with no success, receive an error like:
```○ Compiling / ...
storefront:dev:  ⚠ ../../node_modules/.pnpm/mongodb@6.3.0/node_modules/mongodb/lib/deps.js
storefront:dev: Module not found: Can't resolve 'aws4' in '/Users/redacted/Desktop/redacted/node_modules/.pnpm/mongodb@6.3.0/node_modules/mongodb/lib'
```
I believe its related to missing of optional mongodb dependencies. 

This error goes away when you add monogdb directly as a dependency to the nextjs `apps/storefront` so I suspect theres some config with `tsup`, `turbo`, `nextjs` that is missing. 

I think an example of this config would be really helpful, and fits perfectly into the existing "Kitchen Sink" example.

I've created an [example repo](https://github.com/leetmachine/mongo-issue) showcasing the exact problem with the node_modules, I'd be happy to open the PR into your docs if we can figure out the example.

### Is there any context that might help us understand?

I extended the Kitchen Sink example to add "mongodb" client to the packages/logger. I chose to enhance logger package because it was already configured and makes the example easy. 

`web/storefront/page.tsx` is importing the new "dbConnect" function, which introduces an error `Module not found: Can't resolve 'aws4`. The error goes away if you add "mongodb" as a depedency to `apps/storefront`. 

example repo:  https://github.com/leetmachine/mongo-issue
requires adding your own mongodb uri to [logger/src/dbConnect.ts](https://github.com/leetmachine/mongo-issue/blob/5f84d4eb654e1a5c5c7cf0c718cd691275dc228b/packages/logger/src/dbConnect.ts#L3)
the `dbConnect` implementation is from the [with-mongodb ](https://github.com/vercel/next.js/blob/canary/examples/with-mongodb/lib/mongodb.ts) nextjs example

If someone can help guide my example, I'm happy to open a PR against the Kitchen Sink example to extend it with the concept.

**Comment by anthonyshew** [comment]
We appreciate the suggestion! However, we're happy with the surface area of our examples right now.

In this particular case, this is an issue with dependency resolution, as you've noted, which is something out side of Turborepo's current scope. We try to help out where we can, but providing an example of every permutation of possible dependency resolution errors is something that we can't dedicate time to.

For what it's worth, I pulled down your repo and installed `aws4` into the `logger` package alongside `mongodb` and it appears to be working. Sounds like you were on the right track about optional dependencies!
