### ISSUE TITLE
Turbo throws error "turbo_json_parse_error"

### ISSUE THREAD

**Issue by cameroncf** [vercel/turbo#7522]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/cameroncf/turbo-json-validation-issue/blob/main/turbo.json

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

1.12.5-canary.0

### Describe the Bug

I've just updated from 1.11.3 to 1.12.4 and am running into an error parsing the turbo.json file.  I'm using Projen to maintain my turbo.json file and it drops a comment into the file so it can be tracked by Projen and re-generated reliably. 

We've been using Projen to manage this file for a couple of years at least without any issue. This seems to be new somewhere after v1.11.3. I suspect some additional "helpful" JSON validation was added to turbo recently.

Screenshot of Github Actions error:
<img width="745" alt="Screenshot 2024-02-26 at 4 13 28 PM" src="https://github.com/vercel/turbo/assets/789760/a010df9b-fd30-4830-9158-83da818186d2">

Screenshot of the relevant portion of offending file:
<img width="745" alt="Screenshot 2024-02-26 at 4 11 52 PM" src="https://github.com/vercel/turbo/assets/789760/f0870498-95ef-498b-9b68-196e51e3f310">

### Expected Behavior

I expect Turbo to run without error.

### To Reproduce

Repo [here](https://github.com/cameroncf/turbo-json-validation-issue/blob/main/turbo.json). Run `pnpm turbo build` to reproduce.

### Additional context

Reverting to 1.11.3 works. Potential solutions:

- CLI / env switch to ignore validation step.
- Vercel adds "//" to schema.
- I create / use my own schema.

**Comment by cameroncf** [comment]
I'm not much of a Rust dev but did manage to track back to recent changes around this error code and it looks like @NicholasLYang may be touching the code recently. Not trying to build any expectations on immediate attention - just giving you the heads up in case the relevant code for this is living in your head right now.

**Comment by chris-olszewski** [comment]
`turbo.json` supports line comments starting with `//`. Can you configure `projen` to put the comment in a line with just `//` instead of a key in the JSON object?

**Comment by cameroncf** [comment]
@chris-olszewski that did the trick. It's probably still worth looking at since it's a breaking change in behavior but that did fix my immediate problem.

Here's the Projen code as breadcrumbs for anyone else:
```
new JsonFile(this, "turbo.json", {
  allowComments: true, // this line fixed the problem
  obj: () => {
    return {
      $schema: "https://turborepo.org/schema.json",
      pipeline: {}
    };
  },
});
```

**Comment by NicholasLYang** [comment]
Yeah, sorry about that. Having no validation in our turbo.json was frankly an oversight if not a bug. We added the validation to prevent common mistakes like mistyping fields. We even caught issues in our own examples after adding it. Apologies for the breaking change, having extra fields was never a documented Turborepo feature, so we felt comfortable adding validation.

**Comment by nivekithan** [comment]
This error will get triggered, if you are using `leading ./` in the `pnpm-workspaces.yaml`. To fix it, you will have to remove `./` from the `pnpm-workspaces.yaml` 

https://github.com/vercel/turborepo/issues/10944
