### ISSUE TITLE
"panic: runtime error: slice bounds out of range" with --concurrency 1

### ISSUE THREAD

**Issue by VanTanev** [vercel/turbo#758]
### What version of Turborepo are you using?

1.1.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Running the example repo, this command fails:
```
$ turbo run lint --concurrency 1
panic: runtime error: slice bounds out of range [14:13]

goroutine 1 [running]:
github.com/vercel/turborepo/cli/internal/run.parseRunArgs({0xc00013a020, 0x3, 0x3}, {0xc000024034, 0x27})
	github.com/vercel/turborepo/cli/internal/run/run.go:833 +0x1e05
github.com/vercel/turborepo/cli/internal/run.(*RunCommand).Run(0xc00000c180, {0xc00013a020, 0x0, 0x0})
	github.com/vercel/turborepo/cli/internal/run/run.go:122 +0x25c
github.com/mitchellh/cli.(*CLI).Run(0xc00016ba40)
	github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
main.main.func9(0x8df223, {0x0, 0x38}, {0xc00013a010, 0x7f5b55bc65b8, 0x4}, {0x0, 0xc00013a820}, {0x0, 0x0}, ...)
	github.com/vercel/turborepo/cli/cmd/turbo/main.go:173 +0x445
main.main()
	github.com/vercel/turborepo/cli/cmd/turbo/main.go:178 +0xc25

```

### Expected Behavior

No panic.

### To Reproduce

1. Checkout https://github.com/vercel/turborepo/tree/a3c066bf0c59ba2faa133e3420f23487ae7065d9/examples/basic
2. run `yarn install`
3. run `yarn turbo run lint --concurrency 1`

**Comment by jaredpalmer** [comment]
Sorry about that. The correct option syntax of turbo is exactly —flag=thing (spaces are not allowed, which is causing the panic).

See https://turborepo.org/docs/reference/command-line-reference#option-syntax

Made a new issue #759 for improved and more flexible flag parsing

**Comment by VanTanev** [comment]
Thanks for responding so quickly.
In general, inflexible options syntax would be OK. The panic is however very unexpected.

**Comment by jaredpalmer** [comment]
Agreed I think this particular flag should check and throw a usage error here

**Comment by iamnafets** [comment]
Got the same issue, explanation was super helpful. A simple message would be even better. Thank you!

**Comment by mehulkar** [comment]
Spaces should work now, for what it's worth, thank you for filing!

**Comment by VanTanev** [comment]
Love to see it!
