### ISSUE TITLE
Turbo creates cookie files in the root of the mono repo

### ISSUE THREAD

**Issue by weyert** [vercel/turbo#7671]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

n/a

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

turbo 1.12.5

### Describe the Bug

Oddly enough a bunch of `.cookie` files are created in the root of the project. 

![CleanShot 2024-03-08 at 01 14 15@2x](https://github.com/vercel/turbo/assets/7049/c958e93b-3d70-450c-ac2d-fa39e0ff855e)

### Expected Behavior

In the past it would create the cookie files in a directory `.turbo/cookies` but doesn't appear to happen

### To Reproduce

Not sure

**Comment by weyert** [comment]
Maybe this PR is fixing this problem: https://github.com/vercel/turbo/pull/7664

**Comment by Zertsov** [comment]
Hey @weyert, I agree, I think that PR might fix this issue, so once it's merged we'll come back to this to verify / double check with ya!

**Comment by chris-olszewski** [comment]
Closing as #7664 has now been released in [`1.13.0-canary.0`](https://github.com/vercel/turbo/releases/tag/v1.13.0-canary.0)

**Comment by jordanebelanger** [comment]
Happening on 1.13.3 as well

**Comment by Code42Cate** [comment]
Also happening on 1.13.4-canary.1

**Comment by dcposch** [comment]
@chris-olszewski please reopen:

```
$ npx turbo lint
[...]

$ git status
[...]
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        29.cookie

$ jq .version node_modules/turbo/package.json 
"1.13.3"
```

**Comment by wittwerch** [comment]
Still happening on 1.13.4. 
@chris-olszewski could you please re-open the issue?
