### ISSUE TITLE
turbo doesn't run on system without node.

### ISSUE THREAD

**Issue by lofsigma** [vercel/turbo#7688]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

system dependent

### What package manager are you using / does the bug impact?

bun

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

can't tell

### Describe the Bug

On a system with just bun installed, no node. 
```sh
$ turbo 
env: node: No such file or directory
```

### Expected Behavior

```sh
Usage: turbo [OPTIONS] [COMMAND]
...
```

### To Reproduce

install through bun 

### Additional context

apologies if this is a bun issue, feel free to close if it is.
I submitted an issue there too.
https://github.com/oven-sh/bun/issues/9334

**Comment by weyert** [comment]
Yeah, think it's this: https://github.com/vercel/turbo/blob/main/packages/turbo/bin/turbo#L1

**Comment by NicholasLYang** [comment]
We can definitely look into this once we've refactored our release process. For now, it's actually quite feasible to build `turbo` from source. You'll need to clone the repository, install Rust, a protobuf toolchain (protoc), and a capnproto toolchain (capnp), but after that it should be (hopefully) smooth sailing. If you run `cargo install --path crates/turborepo` from the root, you should end up with a global turbo that doesn't use `node`. Let me know if you run into any issues!
