### ISSUE TITLE
pnpm install runs postinstall in every project

### ISSUE THREAD

**Issue by alexmilde** [vercel/turbo#7734]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/alexmilde/turbo-pnpm-postinstall-issue/tree/main/my-turborepo

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

1.12.3

### Describe the Bug

Running pnpm inside an app folder will trigger the postinstall script of a different app.

This causes side effects with mono repo deployment on vercel.

```alex@Alexanders-MBP my-turborepo % cd apps/docs
alex@Alexanders-MBP docs % pnpm install
Scope: all 6 workspace projects
. postinstall$ node -e "console.log('postinstall docs')"
│ postinstall docs
└─ Done in 68ms
../web postinstall$ node -e "console.log('postinstall web')"
│ postinstall web
└─ Done in 63ms
```

Even using a filter wont work here:

```
alex@Alexanders-MBP docs % pnpm --filter "docs" install
../web postinstall$ node -e "console.log('postinstall web')"
│ postinstall web
└─ Done in 70ms
. postinstall$ node -e "console.log('postinstall docs')"
│ postinstall docs
└─ Done in 66ms
```

### Expected Behavior

postinstall should only be triggered for the current project

### To Reproduce

checkout my repo and run 
`cd apps/docs && pnpm install`

**Comment by anthonyshew** [comment]
Could you say what Turborepo's role is here?

**Comment by alexmilde** [comment]
your're right. my bad. its a pnpm issue. i will close this and file one at pnpm.

**Comment by anthonyshew** [comment]
Thank you!
