### ISSUE TITLE
Docs: Code block does not work for tabs on the documentation.

### ISSUE THREAD

**Issue by abranhe** [vercel/turbo#7738]
### What is the improvement or update you wish to see?

I was exploring the documentation website for Turbo repo and noticed that the installation instruction had a bash command on the front.

```
bash pnpm install turbo --global
``` 

### Screenshot
![turbo-screenshot](https://github.com/vercel/turbo/assets/21347264/09d18607-ebc4-4f69-a902-4c342f29b7dc)

I'm like what are they doing there, I even ran it but realized that it was wrong.

### Is there any context that might help us understand?

I clicked on edit this page and realized that when a code block is inside a Tab it renders it as an inline code, adding the language of the extended syntax in front of the code.

```jsx
<Tab>
    ```bash
    yarn global add turbo
    ```
</Tab>
```

You can see the example here:
https://github.com/vercel/turbo/blob/main/docs/pages/repo/docs/installing.mdx#L28C3-L32C9

Or all of them:

https://github.com/search?q=repo%3Avercel%2Fturbo%20%3CTab%3E%20%20%20%20%20%60%60%60bash&type=code


### Does the docs page already exist? Please link to it.

https://turbo.build/repo/docs/installing

**Comment by anthonyshew** [comment]
We've released a new iteration of the docs where this is now solved.
