### ISSUE TITLE
`turbo` fails if there is no lockfile

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turbo#777]
### What version of Turborepo are you using?

all

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v1, Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

If we cannot detect a package manager backend either via `packageManager` key in `package.json` or through lockfile inference, `turbo` throws an error. This is problematic for folks using `turbo` with other languages like Rust or Go where they may not require even installing node_modules

### Expected Behavior

If `turbo` doesn't find a packageManager we should likely fallback to `npm` for now.

### To Reproduce

Run `turbo` without a lockfile or `packageManager` key

### Suggested Solution

If a lockfile does not exist at the root,  we should alter hashing behavior and still allow task running. Thus, we need to conditionally change conditionally hash lockfile as. a global dependency in npm and pnpm, and in the case of yarn, change how we conditionally resolve external dependencies.

**Comment by thasmo** [comment]
Currently this error also occurs (for me) if `packageManager` **is** defined in `package.json` (but the package manager specific lockfile does not exist).

**Comment by OscarVantagePOS** [comment]
I'm also having this issue even with the `packageManager` field set, just like @thasmo. turbo@1.7.0

**Comment by arlyon** [comment]
On turbo 1.12 turbo will just emit a warning instead of failing.

```
glob-example on  main [!] via  v21.6.2
❯ rm pnpm-lock.yaml

glob-example on  main [✘!] via  v21.6.2
❯ pnpm build

> glob-example@ build /Users/arlyon/Programming/glob-example
> turbo build

 WARNING  Issues occurred when constructing package graph. Turbo will function, but some features may not be available: could not resolve workspaces: io error: No such file or directory (os error 2)
• Packages in scope: @repo/eslint-config, @repo/typescript-config, @repo/ui, docs, web
• Running build in 5 packages
• Remote caching disabled
web:build: cache miss, executing 3965897bf3332cee
docs:build: cache miss, executing 34458b17d801c86b
# rest of build...
```
