### ISSUE TITLE
Turbo throws telemetry warning as being an std error

### ISSUE THREAD

**Issue by pfrincu-plenty** [vercel/turbo#7777]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

turbo run build

### What package manager are you using / does the bug impact?

Yarn v2/v3/v4 (node_modules linker only)

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

1.12.4

### Describe the Bug

The warning regarding the turbo telemetry is send as an errorSTD:                                                                                                                                                     14:47:12
Attention:
Turborepo now collects completely anonymous telemetry regarding usage.
This information is used to shape the Turborepo roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://turbo.build/repo/docs/telemetry

### Expected Behavior

The warning should not be send as an errorSTD

### To Reproduce

When running: turbo run build

**Comment by tknickman** [comment]
Hey, thanks for the report! This is intentional, and done to keep stdout clean for commands that output JSON that may need to be cleanly parsed.
