### ISSUE TITLE
Cache miss when output not git ignored

### ISSUE THREAD

**Issue by EWhite613** [vercel/turbo#7784]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/EWhite613/turbo-issue-cache/tree/main

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

1.13.0-canary.1

### Describe the Bug

`turbo` does not take into account outputted files when using cache on dependency builds. So if i have an outputted file and I also don't have the output in my `.gitignore` it will cause it to miss the cache.

Seems like canary fixed an issue where the output was not considered for the current command (ie doing `turbo run build` use to gets this in non canary) But when I run a command that depends on output of another file (ie `turbo run typecheck`) it will see the outputted file of `build` as changed.

So can see first run cache things. And on second run you would expect everything to be cached, but due to the outputted files also being seen as inputs it will re execute (and have it's dependents re-execute). Third run all cached (assuming you don't delete outputted files)

### Expected Behavior

Would expect the outputted files to be taken into consideration from previous call of the current command (seems fixed in canary), and commands that depend on that one

### To Reproduce

https://github.com/EWhite613/turbo-issue-cache/blob/main/README.md

## Workaround-ish
Specify `inputs`.

But I notice if I do this, I would have to do this for all my commands. Since say I have the following
```
{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
    "test": {
      "dependsOn": ["^compile"],
      "outputs": ["artifacts/logs/test/xml/test-reports/xunit_results.xml"]
    },
    "lint": {
      "dependsOn": ["^compile", "^lint"]
    },
    "compile": {
      "dependsOn": ["^prepublishOnly"],
      "inputs": ["src/**"],
      "outputs": ["**/*.d.ts"]
    }
  }
}
```
I now need to let my test command be specific with it's inputs as well cause it will also see `compile`'s output as a change.

Also when trying to target only things that have changed the output will mark a lot more as changed than expected. Ie `turbo run test --filter="...[<target-branch>...HEAD]"` will start noticing the output and adding more packages into scope as they are seen as changed.

**Comment by EWhite613** [comment]
Perhaps my main issue is that the filter `--filter="...[<target-branch>...HEAD]"` takes into account local changes. If it didn't I would be fine. 

I could raise a separate issue for this if that makes sense

**Comment by gsoltis** [comment]
If your outputs are not gitignored, and they produce files in the package that generated them, then I think `turbo` is doing the right thing by considering them changed. You could try editing your `inputs` to only capture the files that you actually need to run your task. 

If there is a bug where specifying both ends of the git comparison (`--filter=[<some sha>...<other sha>]` is not just doing that range of changes, please open a new issue.

**Comment by EWhite613** [comment]
Fair enough. Raised https://github.com/vercel/turbo/issues/7818 for the filter issue
