### ISSUE TITLE
Screenshots in VS Code Marketplace listing for Turborepo LSP are broken links

### ISSUE THREAD

**Issue by steveluscher** [vercel/turbo#7825]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

N/A

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

N/A

### Describe the Bug

https://marketplace.visualstudio.com/items?itemName=Vercel.turbo-vsc

<img width="742" alt="image" src="https://github.com/vercel/turbo/assets/13243/ef9bdcc1-3bf9-4c6b-9e8c-a8518d2e59fe">

### Expected Behavior

Images.

### To Reproduce

Look.

**Comment by weyert** [comment]
Yeah, also would be nice to release a new version that includes the search-for-turbo logic that potentially makes it work with project-level `turbo`

**Comment by arlyon** [comment]
New version being reviewed as we speak!
