### ISSUE TITLE
Bug running NodeJS API on Windows and WSL

### ISSUE THREAD

**Issue by gtoro98** [vercel/turbo#7845]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/gtoro98/turbo_issue

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

1.13.1-canary.2

### Describe the Bug

NodeJS Fastify server fails to run locally from turborepo on windows systems

### Expected Behavior

Server to start

### To Reproduce

run npm run dev on issue repo

### Additional context

Version 1.12 works fine, this issue only appears to happen on Windows, no problem on M chip macs. Tested with WSL with Ubuntu distro and issue also happens

**Comment by chris-olszewski** [comment]
Can you include how it is failing? The repro you provided seems to be working fine on my Windows machine:
![image-6](https://github.com/vercel/turbo/assets/4131117/a37ebac8-d3a8-4434-957b-eb4123a2e1dc)


Information such as which console you are running from and Windows build version could also help.

**Comment by gtoro98** [comment]
> Can you include how it is failing? The repro you provided seems to be working fine on my Windows machine: ![image-6](https://private-user-images.githubusercontent.com/4131117/318138582-a37ebac8-d3a8-4434-957b-eb4123a2e1dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzIzMjQsIm5iZiI6MTcxMTk3MjAyNCwicGF0aCI6Ii80MTMxMTE3LzMxODEzODU4Mi1hMzdlYmFjOC1kM2E4LTQ0MzQtOTU3Yi1lYjQxMjNhMmUxZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMTE0NzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjRlODgzYjlhYTQzZDNkZjQzNDYyNjIwYjMzMmQ5YjhiMmQxMjI1YWJhNmNjMWE3MzY2YzQzMzA3OTMzOTc0MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5ezvV8aWGxVj9fRVZ48EHDDbmV_p4-r4miuP2zUU5q0)
> 
> Information such as which console you are running from and Windows build version could also help.

It looks like it is running but none of the commands are excecuting and the server isn't running

**Comment by tknickman** [comment]
@gtoro98 could you also provide the console you're using as well as your windows build version?

Thanks!

**Comment by gtoro98** [comment]
@tknickman OS Build 22631.3296 but have reproduced in various others on windows powershell, command prompt and terminal

**Comment by gtoro98** [comment]
@chris-olszewski running 'npm run dev' from within the apps/api directory results in succesful starting of the server

**Comment by chris-olszewski** [comment]
Closing in favor of #7834 as I believe this is an bad interaction with `turbo` and `tsx` on Windows.
