### ISSUE TITLE
Regression with 1.13.1 when filtering between two branches

### ISSUE THREAD

**Issue by kevinpastor** [vercel/turbo#7921]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/kevinpastor/turbo-branch-filter-issue

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

Turborepo v1.13.3-canary.0

### Describe the Bug

When using a filter to check a specific range of commits (e.g. `turbo run build --filter=[develop...master]`), no tasks are executed.

### Expected Behavior

Packages that are different between the two branches should have their tasks executed.

### To Reproduce

1. Clone [the repository](https://github.com/kevinpastor/turbo-branch-filter-issue).
2. Run `pnpm install`.
3. Run `pnpm exec turbo run build --filter=[develop...master]`.

On that repository, `packages/first` has a slight difference in the `develop` branch compared to the `master` branch (i.e. a `.gitignore` file is present on the `develop` branch).

### Additional context

Running the same steps to reproduce with `turbo@1.13.1-canary.2` works as expected. `turbo@1.13.1-canary.3` seems to have introduced the regression.

**Comment by anthonyshew** [comment]
Can you try `turbo run build --filter=[master...develop]`?

We recently fixed a bug so that comparisons are the same as Git. It looks like you may have been depending on it.

**Comment by kevinpastor** [comment]
Changing the order works on the repro repository. I'll try the change on our actual repository and get back to you.

**Comment by anthonyshew** [comment]
I've also confirmed that this is the case with another user seeing the same behavior.

We fixed a bug in #7838 so that Turborepo uses the same comparison ordering as Git: [`<from>...<to>`](https://turbo.build/repo/docs/core-concepts/monorepos/filtering#check-a-range-of-commits).

**Comment by kevinpastor** [comment]
This change did fix the issue in our repository. Thank you!
