### ISSUE TITLE
"turbo run dev" gets stuck at a random stage

### ISSUE THREAD

**Issue by AlexisCharp** [vercel/turbo#7924]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/AlexisCharp/turborepo-issue-showcase

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

turbo@1.13.3-canary.0

### Describe the Bug

When running yarn dev at the root level of the repo, the turbo package should watch all packages in parallel. However, it appears that it forgets to launch some of the packages' dev scripts.

On the example, you'll probably think it's related to postcss watcher as it's likely to be a css package missing. But, I'm working on a bigger codebase currently and it randomly concerns storybook, css, a react lib, a next app. It's really something linked to turbo itself because the solution I found to fix this was to downgrade to turbo 1.12...

### Expected Behavior

I should have all packages listed in the console.
(If you run the example, you'll notice some of them are missing)

### To Reproduce

Simply run `yarn dev` at the root level

**Comment by tknickman** [comment]
This is happening because turbo will schedule `10` tasks to run concurrently by default. For your `dev` tasks, you can override this with the concurrency flag:

`--concurrency 20`

**Comment by AlexisCharp** [comment]
Hello Thomas,
Thanks for your quick answer. There is still something I can't figure out, I have the --parallel flag passed to my dev command. On the concurrency documentation, it says : "This option is ignored if the --parallel flag is also passed". Is the documentation not up to date then?

**Comment by mistic100** [comment]
@tknickman I had the exact same problem, only 10 tasks started even though the `--parallel` flag is set. Can you enlight us on this behaviour and/or fix the documentation ?
Thanks
