### ISSUE TITLE
Turbo not working on windows

### ISSUE THREAD

**Issue by mann1996** [vercel/turbo#7957]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/jaspreet-singh-96/test-repo

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

1.13.3-canary.0

### Describe the Bug

I am getting this error when running any turbo command in windows. For example ```turbo dev --parallel``` or ```turbo build```.

![image](https://github.com/vercel/turbo/assets/26829578/4faa7427-5ccb-4313-bfd0-df051d6cd85b)

It works fine on macos and linux. Works fine whe running individual packages using pnpm filter.

### Expected Behavior

Should start all packages in dev mode.

### To Reproduce

run ```turbo dev --parallel``` in root directory. 

### Additional context

I have tested this with both latest stable release and canary release. Below is output with verbosity level 2
![image](https://github.com/vercel/turbo/assets/26829578/30eac821-9ae9-4109-ac82-0ce436baee38)

**Comment by chris-olszewski** [comment]
I pretty sure [this line](https://github.com/rustls/rustls-native-certs/blob/0ebeee01ed61ebeacd5ebb98e7f5694b0ee70a08/src/windows.rs#L19) is producing the error, which is odd as I believe Root is a [predefined cert store location](https://learn.microsoft.com/en-us/windows/win32/seccrypto/system-store-locations).

I'm not sure if this is the best way to go about finding the default cert store, but it worked on my machine. Could you verify that the following commands work in Powershell and that the directories exist?
```
cd Cert:\
cd .\\LocalMachine\
cd .\Root\
ls
```

**Comment by mann1996** [comment]
Sorry for delay. Yes, these commands work in Powershell below is the output for last cmd
![image](https://github.com/vercel/turbo/assets/26829578/25851db3-7a99-4439-ab8c-a17b8a123314)

**Comment by chris-olszewski** [comment]
I just noticed you're running the command from the `H:` drive. Could you try running a `turbo` command from the `C:` drive? Is there anything special to the `H:` drive that could be relevant?

**Comment by mann1996** [comment]
H drive is where I keep all my projects. Its an external drive that I use between my desktop and laptop

**Comment by mann1996** [comment]
I tried running it from C drive and got same issue.

**Comment by chris-olszewski** [comment]
I'm at a loss as to why the upstream dependency would be failing to load the cert store. Do you have any issues/special configuration for setting up TLS connections with other programs?

One thing I'm curious about is if you get the same error with 1.12?

**Comment by mann1996** [comment]
I don't know what was wrong. I did a clean install of windows and its working now.

**Comment by wanghaisheng** [comment]
@chris-olszewski  file is there and what i want to do is clone and run https://github.com/withastro/astro
