### ISSUE TITLE
Docs: OpenAPI spec incorrectly mentions teamId instead of slug

### ISSUE THREAD

**Issue by AdiRishi** [vercel/turbo#7980]
### What is the improvement or update you wish to see?

The OpenAPI spec for Turbo found here - https://turbo.build/api/remote-cache-spec mentions the use of `teamId` as a query parameter in most of it's routes.
![Screenshot 2024-04-16 at 11 59 23 AM](https://github.com/vercel/turbo/assets/8351234/ac3634a2-5a33-4ee2-8981-1a64eb265010)

I was updating my own [custom remote cache](https://github.com/AdiRishi/turborepo-remote-cache-cloudflare) server to comply with the API spec, however the actual requests made by the turbo client do not match what is specified in the OpenAPI spec for `teamId`.

### Is there any context that might help us understand?

I'm running turbo version `1.13.2`
The environment variables given to turbo are
```
TURBO_TEAM=team_my_team_name
TURBO_API=http://localhost:8787
TURBO_TOKEN=SECRET
TURBO_REMOTE_CACHE_SIGNATURE_KEY=SECRET
```

The docs mention the use of `teamId` query parameter, however, in actuality, the turbo client uses the `slug` parameter.

We can see this behavior through the warnings generated
```
 WARNING  failed to contact remote cache: Error making HTTP request: HTTP status client error (400 Bad Request) for url (http://localhost:8787/v8/artifacts/99469f3053174e08?slug=team_my_team_name)
```
This clearly slows that the `turbo` client uses `slug` instead of `teamId`. I have verified this by observing API calls to my production hosted instance as well.

**Comment by chris-olszewski** [comment]
Apologies for the confusion, both `teamId` and `slug` are valid query params for specifying which team you are using. If you connect your repository though something like `turbo link`, then a team id will be saved and `teamId` will be used when accessing the remote cache. `TURBO_TEAM` uses the `slug` query parameter instead since it isn't a team id.

Looking into fixing this in the upstream OpenAPI spec.

**Comment by AdiRishi** [comment]
Hey @chris-olszewski , thanks for confirming this 😄 
Looking forward to having this updated in the OpenAPI spec.

I had another question, I know this is off topic to the current issue, so happy to open a new one if you want.
I'm wondering if you could help explain what the `POST /v8/artifacts` route is supposed to do.
The docs say it has this input
```json
{
  "hashes": [
    "string"
  ]
}
```
and gives this as an example for output
```js
{
  "additionalProp1": {
    "size": 0,
    "taskDurationMs": 0,
    "tag": "string"
  },
  // ...
}
```

The output example is super unclear, I'm really not sure what data I'm meant to be returning here. What are the `additionalProp` keys? Is this saying that I have to echo the metadata even to the server via the `/v8/artifacts/events` endpoint?
Keen to get some clarity 🙏 . This is the last unimplemented endpoint I have left for my custom server.

**Comment by chris-olszewski** [comment]
I just double checked and we currently don't make use of that endpoint so you will be fine not implementing it.

I will update the OpenAPI spec to omit that endpoint.

**Comment by chris-olszewski** [comment]
OpenAPI spec has been updated to mention `slug` and `teamId`. Still working on fully removing the `POST /v8/artifacts` since it's unused.

**Comment by AdiRishi** [comment]
Thanks Chris.
I'm happy to close out this issue, or keep it open your other changes are synced, whatever you'd like
