### ISSUE TITLE
Docs: When the API references will be added?

### ISSUE THREAD

**Issue by sudoaugustin** [vercel/turbo#8010]
### What is the improvement or update you wish to see?

Hi, when the turbopack will be ready to use as a standalone bundler outside nextjs? I have project that use esbuild to bundle, but since esbuild don't support HMR, I'm thinking to move to turbopack.  Thanks!

### Is there any context that might help us understand?

-

**Comment by anthonyshew** [comment]
Today, the focus for Turbopack is on being an excellent bundler for the Next.js Compiler.

We're getting close to a stable release for the development server and are beginning to put thought into Next.js builds.

Once those things are done, we will take a step back and look at the needs of users and the larger ecosystem to see what next steps will be.
