### ISSUE TITLE
 ERROR  Cannot invoke 'uname` to get architecture type: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }

### ISSUE THREAD

**Issue by ParasRai2** [vercel/turbo#8012]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/ParasRai2/articles-nextjs.git

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

turbo@1.13.2

### Describe the Bug

I am building the mono repo apps on cPanel.
While building with `npx turbo run build --parallel`
its throwing error with the message 
` ERROR  Cannot invoke 'uname' to get architecture type: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
Oops! Turbo has crashed.`

### Expected Behavior

Build the apps on the monorepo

### To Reproduce

Run command 
`npx turbo run build --parallel`

### Additional context

<img width="1226" alt="image" src="https://github.com/vercel/turbo/assets/30003380/e5cc59b8-7dbe-4e20-b662-3f742dcf7c9a">

**Comment by ParasRai2** [comment]
```
name = "turbo"
operating_system = "Linux [unknown bitness]"
crate_version = "1.13.2"
explanation = """
file '/github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs' at line 170
"""
cause = "The global thread pool has not been initialized.: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: \"Res$
method = "Panic"
backtrace = """

   0:   0x72ad97 - <unresolved>
   1:   0x5cfba5 - <unresolved>
   2:   0x5cd723 - <unresolved>
   3:  0x12ac8ab - <unresolved>
   4:  0x1067cc8 - <unresolved>
   5:  0x1062910 - <unresolved>
   6:  0x10632fd - <unresolved>
   7:  0x10630a2 - <unresolved>
   8:  0x10601ed - <unresolved>
  9:  0x105f555 - <unresolved>
 10:  0x1019df5 - <unresolved>
  11:   0xc536a2 - <unresolved>
  12:   0xccfaa5 - <unresolved>
  13:  0x116a35d - <unresolved>
  14:   0xe143b0 - <unresolved>
  15:   0xe9424d - <unresolved>
  16:   0xe8f370 - <unresolved>
  17:   0xaf21e2 - <unresolved>
  18:   0xaf1933 - <unresolved>
  19:   0xaf1633 - <unresolved>"""
```

@chris-olszewski  here is the content of the report file

**Comment by chris-olszewski** [comment]
Can you run `uname -a` and provide the result? It's odd that we're unable to determine the bitness of your system.

**Comment by ParasRai2** [comment]
@chris-olszewski 
I got this
Linux s2912.fra1.stableserver.net 4.18.0-513.11.1.lve.el8.x86_64 #1 SMP Thu Jan 18 16:21:02 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

I am using nodejs application on cPanel

**Comment by chris-olszewski** [comment]
It appears to be happening when the library we use for parallel processing is setting up the thread pool, but is unable to query the underlying OS for information. I'm unsure if this is a bad install of the OS or the OS itself doesn't surface this capability to user code. 

You could try to reinstall the OS/reprovision the box. I'm afraid we can't dedicate resources to figuring out what exactly is going wrong with your setup.
