### ISSUE TITLE
Feature Request: Turbopack Plugins

### ISSUE THREAD

**Issue by bestickley** [vercel/turbo#8062]
### What is the improvement or update you wish to see?

I want to be able to use [Pigment CSS](https://github.com/mui/pigment-css) with MUI v6 in my Next.js app with Turbopack. Pigment CSS requires use of plugins into build system, which means I have to downgrade from turbopack to webpack which hurts DX. Based on the docs [here](https://turbo.build/pack/docs/migrating-from-webpack#will-we-be-able-to-use-webpack-plugins), I know the turbopack team is working on this (thank you!), but can any timeline/updates be shared?

### Is there any context that might help us understand?

https://github.com/mui/pigment-css/issues/6

### Does the docs page already exist? Please link to it.

https://turbo.build/pack/docs/migrating-from-webpack#will-we-be-able-to-use-webpack-plugins

**Comment by kwonoj** [comment]
As doc noted it is not easy to support webpack plugins out of the box. There will be some extendable point for the turbopack and team internally discusses it but cannot promise exact time & how at this moment.

**Comment by NoriSte** [comment]
Hey team, any update on this?
(and thank you for everything you do, we really appreciate it 😍)

**Comment by theoephraim** [comment]
Now that we are officially [100% turbo](https://areweturboyet.com/), and I suspect we'll see more users moving over, the question of plugins is very important. I have built tooling that works by injecting webpack plugins, and I'd like to understand how (and when) this may be possible using turbopack.

**Comment by theoephraim** [comment]
Why this is closed? Is there no future for any kind of plugin system in turbopack?

**Comment by yoannmoinet** [comment]
Can we re-open this please?

**Comment by deryasdeepseeartbounty** [comment]
> Can we re-open this please?
Sure!
