### ISSUE TITLE
Docs: `dependsOn` is easy to use incorrectly and have tasks run out of order

### ISSUE THREAD

**Issue by alex-page** [vercel/turbo#8066]
### What is the improvement or update you wish to see?

It would be great to add an example for when to use `^build, build` and the tradeoffs of this approach. [This is a pattern we have noticed across many repositories](https://github.com/search?type=code&q=path%3Aturbo.json+%2F%22%5C%5Ebuild%22%2C+%22build%22%2F) `turbo.json` files. 

### Is there any context that might help us understand?

My current project set up:
- `"turbo": "^1.13.2"`
- `"packageManager": "pnpm@9.0.5`

On a project I am working on we recently started using `"test": { "dependsOn": ["^build"]}`. It wasn't clear why the scripts were running out of order.

We noticed `pnpm build` would be running at the same time as `pnpm test` and some workspaces were waiting for other workspaces to complete building correctly but packages that depended on themselves to complete `build` did not wait and would run `test` at the same time.

Later we realised if added `^build, build` it would run in order.

`turbo.json`
```diff
- "test": { "dependsOn": ["^build"]},
+ "test": { "dependsOn": ["^build", "build"]},
```

### Does the docs page already exist? Please link to it.

https://turbo.build/repo/docs/reference/configuration#dependson

**Comment by anthonyshew** [comment]
I might be misunderstanding but the doc you've linked fairly succinctly describes your use case. Can you explain why it's confusing?

There's also a longer explanation with examples here: https://turbo.build/repo/docs/core-concepts/monorepos/task-dependencies#from-the-same-workspace

**Comment by alex-page** [comment]
We found the task dependency documentation but it would have been nice to have a reference to those details from the `dependsOn` configuration page.

The `dependsOn` example on the configuration page doesn't have any examples with both `"^build", "build"` and explain why this pattern would be helpful.

**Comment by anthonyshew** [comment]
We've released a new iteration of the docs, including some reworking around dependencies. Take a look: https://turbo.build/repo/docs/crafting-your-repository/configuring-tasks
