### ISSUE TITLE
Examples: `with-nestjs` example implementation

### ISSUE THREAD

**Issue by Neosoulink** [vercel/turbo#8131]
### What is the improvement or update you wish to see?

It would be great to have a `with-nestjs` example integrated

### Is there any context that might help us understand?

Starting a NestJs project managed within turbo-repo is just great and I recommend it!

However, the `turbo` repo doesn't include an official example to start a NestJS Turbo-repo project.

**Comment by Neosoulink** [comment]
If it's possible, I'm volunteering to contribute to this one

**Comment by anthonyshew** [comment]
No one on our team has experience with Ne**s**t.js so we'd appreciate a contribution for this!

**Comment by Cirilord** [comment]
@Neosoulink what the config you use in launch.json for debug purpose?

**Comment by Neosoulink** [comment]
Hey @Cirilord,
I did not integrate a `launch.json` for this example

> https://github.com/vercel/turbo/pull/8162

**Comment by Cirilord** [comment]
Do you have any idea what it would look like?

**Comment by Neosoulink** [comment]
@Cirilord,
I'm not sure about the context... Could you share more details or needed behavior?

**Comment by Cirilord** [comment]
Sure, i'm trying to create a configuration inside launch file to debug my nextjs application

**Comment by Neosoulink** [comment]
@Cirilord okay...
Note that you're free to configure your debugger as you prefer and it's beyond this issue's scope.

But, as an example, if you want to set a configuration that launches both apps in development mode (`/api` and `web`), you can use `TurboRepo` as follows:

```json
{
  "version": "0.0.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch apps in dev mode (using turbo repo)",
      "runtimeExecutable": "pnpm",
      "runtimeArgs": ["run-script", "dev"],
        "env": {
          "NODE_ENV": "development"
      },
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
  ]
}
```

This configuration will execute the script at the `root` of your project and will launch your apps/packages in the development mode.

**Comment by Cirilord** [comment]
Thanks @Neosoulink! It worked very well

**Comment by fzzv** [comment]
@Neosoulink Hi 👋, sorry to bother you and thank you for your work on this project!

I have a question about the `with-nestjs` example.  
I cloned the repository directly, and I'm wondering how to properly import `@repo/api/index` inside `apps/api`.

For example, when I add the following line in `app.module.ts`:

```ts
import { links } from '@repo/api/index';
```

the console shows an error saying that the module cannot be found (or similar import error).

Could you please advise how to correctly reference @repo/api/index within apps/api?
Am I missing a specific configuration for TypeScript paths or the Turborepo setup?

Thank you very much for your time and help! 🙏

<img width="1209" height="289" alt="Image" src="https://github.com/user-attachments/assets/67d9fcf6-19ac-4eee-bd8b-fb73f76349bc" />

**Comment by Neosoulink** [comment]
Hey @fzzv, have you correctly specified the package in your `package.json`?

Something like:

```ts
  "my-package: "workspace:*"
```

> Note: you can still check out how it's done in the example or browse the [official documentation](https://turborepo.com/docs/crafting-your-repository/managing-dependencies).

Let me know if you solved it 🐞

**Comment by fzzv** [comment]
@Neosoulink Hi, thank you very much for your reply!

I’ve correctly specified the package.  
To make it easier to reproduce, I created a minimal repo — I only added the following line in `apps/api/src/app.module.ts`:

```ts
import { links } from '@repo/api/index';
```

After running `pnpm run dev`, the console shows an error.

Here’s the Codesandbox URL for reference:
https://codesandbox.io/p/github/fzzv/my-turborepo/main?import=true

Thank you again for taking the time to look into this! 🙏

**Comment by Neosoulink** [comment]
Hey @fzzv,
You were right, the example had a tiny issue with the `@repo/api` package typing.

I'm creating an issue + PR for it in a few minutes; meanwhile, you can use the following as a reference:

https://github.com/Neosoulink/basic-turborepo-nestjs

Here's the demo:
https://codesandbox.io/p/github/fzzv/my-turborepo/csb-wn82nh/draft/inspiring-snow?file=%2Fapps%2Fapi%2Fpackage.json&import=true

> You should have something like this
<img width="1442" height="973" alt="Image" src="https://github.com/user-attachments/assets/8f4c6c78-b05a-45e9-b287-2931f92180f1" />

**Comment by fzzv** [comment]
Thanks! @Neosoulink 

I’d like to ask a quick question:  
In `packages/api`, is it only possible to import other modules using **relative paths** (like `../../...`), and not with **path aliases** (like `links/...`)?

**Comment by Neosoulink** [comment]
> Thanks! [@Neosoulink](https://github.com/Neosoulink)
> 
> I’d like to ask a quick question: In `packages/api`, is it only possible to import other modules using **relative paths** (like `../../...`), and not with **path aliases** (like `links/...`)?

This is not directly linked to the example, but TypeScript.

TypeScript offers a mechanism to create path aliases:

```json
  {
      "compilerOptions": {
        "baseUrl": ".",
        "paths": {
          "@components/*": ["./src/components/*"],
          "@utils/*": ["./src/utils/*"],
          "@api/*": ["./src/api/*"]
        }
      }
    }
```

> If you think something is missing, you can create a [discussion](https://github.com/vercel/turborepo/discussions).
