### ISSUE TITLE
Resolve Alias not working same as webpack

### ISSUE THREAD

**Issue by pksorensen** [vercel/turbo#8146]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

not public

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

the one that comes with nextjs 14.2.3

### Describe the Bug

In webpack we define alias for webpack

```
 config.resolve.alias['@eavfw/utils'] = path.resolve(__dirname, '../../node_modules/@eavfw/utils');
```

the module is there, and i suspect this being related to that the package is linked in with npm (basically a symlink)

![image](https://github.com/vercel/turbo/assets/2718591/bdb0dd92-7c7d-4bd3-b861-886f6ea41e25)

but building causes nextjs app with turbo not to resolve it.

![image](https://github.com/vercel/turbo/assets/2718591/5471c049-5c89-4601-b842-5d091c8fd321)

### Expected Behavior

We expect it to load packages even if linked with npm like webpack is doing :)

### To Reproduce

use npm link and try alias to the module

**Comment by ForsakenHarmony** [comment]
Please open an issue on the next.js repo
https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&projects=&template=1.bug_report.yml
