### ISSUE TITLE
If dependsOn is missed and a workspace dependency changes, there s no cache miss

### ISSUE THREAD

**Issue by lukpsaxo** [vercel/turbo#8160]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### What package manager are you using / does the bug impact?

Yarn v2/v3/v4 (node_modules linker only)

### What operating system are you using?

Windows

### Describe the Bug

For lint and sometimes typescript, you want packages to compile in parallel because even though module a depends on b - it does not depend on the linting in module b to be done before the linting in module a.

So I recreated a test case:
1. ran npx create-turbo@latest
2. deleted dependsOn: from the lint task

Now the tasks run in parallel.

But if I change the eslint config package - I get a cache hit - instead of a cache miss :/ so removing dependsOn seems to make the task not depend on any of its dependencies?

I found a work-around. If I add a dummy task that isn't in any packages, then depend on that, now I get parallel execution and when the lint config is changed, it triggers a cache miss.

**Comment by anthonyshew** [comment]
The behaviors you're describing are all expected.

The "dummy task" workaround we have documented here, as well: https://turbo.build/repo/docs/core-concepts/monorepos/task-dependencies#dependencies-outside-of-a-task

**Comment by lukpsaxo** [comment]
Thanks, sorry I missed that - I had skipped the docs straight to how to setup eslint / typescript and the examples pointed from those pages aren't setup like this.
