### ISSUE TITLE
`turbo-ignore` do not work on a single repo

### ISSUE THREAD

**Issue by devjiwonchoi** [vercel/turbo#8172]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/devjiwonchoi/repro-turbo-ignore-single-app

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

turbo 1.13.4-canary.4

### Describe the Bug

Context: Using `turbo` on a single Next.js app (non-monorepo)

`turbo build --dry json` returns the `packages` as undefined, so it throws an error as below:

![Screenshot 2024-05-18 at 1 42 38 AM](https://github.com/vercel/turbo/assets/120007119/a4e5d9ad-61c2-4ef0-b49e-dde6495fabc4)

### Expected Behavior

In `tuborepo`, we need to add logic to include a single repo to `packages` value as well.

### To Reproduce

Run the following commands:

```sh
pnpm i
pnpm turbo build
npx turbo-ignore
```

Confirm that the `packages` value is missing

```sh
pnpm turbo build --dry=json
```

### Additional context

x-ref: #8171

**Comment by tknickman** [comment]
Hey @devjiwonchoi thanks for the report. This shouldn't straight up fail, so we can fix that. However using `turbo-ignore` with a single package repo is not necessary, since turbo only has package level granularity it will never ignore.

**Comment by devjiwonchoi** [comment]
@tknickman Thank you for the fix!

I came across from this [video by Anthony](https://www.youtube.com/watch?v=fu1O6wAFfrM) where it introduces to use `turbo-ignore` to possibly skip everything on CI before even installing deps, as well as from [the docs](https://turbo.build/repo/docs/core-concepts/monorepos/skipping-tasks#using-turbo-ignore-on-vercel).

As I'm benefitting so much from `turbo build` and the remote cache on my Next.js app, I'd love to benefit even more with `turbo-ignore` where I can `turbo build` locally, remote cached, and not even installing deps on Vercel and save money for Vercel and time for myself.

I think it's feasible.. or maybe I misunderstood the feature?

**Comment by tknickman** [comment]
That's awesome you're benefiting from `turbo build`! 

`turbo-ignore` helps when deploying in CI (it works best on Vercel!) to determine if your changes are relevant to the app you're deploying. It does this by determining if your package, or any of your packages dependencies have changed. When you're working with a single package application - a deployment will only be queued when it has changes, thus running turbo-ignore won't matter as it will always determine that the project should build.

**Comment by devjiwonchoi** [comment]
Ah, understood. Thank you for your kind explanation!!

**Comment by tknickman** [comment]
No problem - thanks again for the report of the issue!
