### ISSUE TITLE
Docs: importing internal packages to node-js application

### ISSUE THREAD

**Issue by asutosh-147** [vercel/turbo#8175]
### What is the improvement or update you wish to see?

in docs it is mentioned that we can import the internal packages into apps(vite app or nextjs app) and the method works but when i try to import the same typescript package inside my apps/server folder which contains node-js it doesn't suggest the path and shows import error " cannot find module or types ". this error disappears when i update the import path pointing direct to the file but remains if i use the path mentioned in imported package's package.json........... So can anyone please help me with it ?

### Is there any context that might help us understand?

please update the issue in docs as well

### Does the docs page already exist? Please link to it.

[link to the doc page](https://turbo.build/repo/docs/handbook/sharing-code/internal-packages)

**Comment by anthonyshew** [comment]
We have updated the documentation around creating Internal Packages here: https://turbo.build/repo/docs/crafting-your-repository/creating-an-internal-package
