### ISSUE TITLE
$TURBO_DEFAULT$ doesn't work as default anymore in 1.13.3

### ISSUE THREAD

**Issue by ChurroC** [vercel/turbo#8203]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://codesandbox.io/p/github/ChurroC/next-server-theme/main?import=true

### What package manager are you using / does the bug impact?

npm, Yarn v1, bun

### What operating system are you using?

WSL but also tested on code sandbox

### Which canary version will you have in your reproduction?

Tried on 1.13.4-canary.5 and on stable 1.13.3

### Describe the Bug

When adding `$TURBO_DEFAULT$` to inputs, turbo doesn't recognize it and instead caches no matter the change. Cache revalidation worked perfectly without `$TURBO_DEFAULT$`. But the second I used it as an input it served the cached run no matter what.

### Expected Behavior

$TURBO_DEFAULT$ should work the same as the default inputs and even more important should invalidate the cache when files change.

### To Reproduce

You can use the repo and first do yarn install.
Then do yarn run build --filter web. This will run build step of web package. It'll work find with no input section.
If you add "inputs": ["$TURBO_DEFAULT$" to build you end up having no cache invalidation.

### Additional context

Video of me testing on the code sandbox **https://drive.google.com/file/d/1g9YsqGOQMxoyC8y0myBaiaegbwm5EOYX/view**
![turbo json - next-server-theme - CodeSandbox (1)](https://github.com/vercel/turbo/assets/66274903/4752db43-b5b1-46b2-b43b-5318e3c7b7e7)

Also tested on 1.13.0 and everything started working

**Comment by NicholasLYang** [comment]
Hey @ChurroC, thanks for the issue. Could you try running with `--no-daemon`? It's possible that the daemon's implementation of file hashing is incorrect.

**Comment by rozsival** [comment]
In case this is going to be investigated / fixed later on, I confirm in our project the combination of `$TURBO_DEFULT$` and daemon was the problem too. Switching to `--no-daemon` mode solved the problem.
