### ISSUE TITLE
Unable to opt-out of ui view

### ISSUE THREAD

**Issue by weyert** [vercel/turbo#8278]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

n/a

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.0-canary.2

### Describe the Bug

It's unable to opt-out of running the tasks in UI mode. If you run `pnpm exec turbo run build --filter=@company/secret-mgmt...` it will always shows the UI-mode. 

Occasionally, you might not want to use this UI mode, e.g. when you just trying to build some packages in a shell script.

### Expected Behavior

I would be able to opt-out of UI mode, e.g. via `--no-experimental-ui`-mode or when passing `CI=true pnpm exec turbo run dev`

### To Reproduce

None available

### Additional context

I have a script builds the developer environment and need to build some packages (e.g.s secret management) before I can run some followup code. Now it shows the UI instead of just outputting the logs when running `pnpm exec turbo run build --filter=@company/secret-mgmt...`

**Comment by anthonyshew** [comment]
There will be a configuration for it in `turbo.json`. You can also use `--log-order` to opt out.

**Comment by weyert** [comment]
@anthonyshew I can't seem to get this work with both `--log-order=stream` or `--log-order=grouped` in turbo@2.0.1

**Comment by michael-land** [comment]
The configuration {"ui": "stream"} works, but `--log-order=stream`does not seem to work.

**Comment by weyert** [comment]
Neither for `run`
