### ISSUE TITLE
turborepo tui doesn't print run summary

### ISSUE THREAD

**Issue by chris-olszewski** [vercel/turbo#8290]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

`npx create-turbo@canary test npm && npm build`

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v1, Yarn v2/v3/v4 (node_modules linker only)

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.0-canary.3

### Describe the Bug

Run summary doesn't print when TUI is used

### Expected Behavior

Run summary displaying number of tasks ran/cached should be displayed.

### To Reproduce

Use TUI

**Comment by clintonwoo** [comment]
I'm seeing this issue too on Linux with turborepo 2.0.4.canary1 and pnpm 9.1.4. It runs all the tasks with TUI then before printing run summary it just exits with an error code. It works no problem with stream mode though.
