### ISSUE TITLE
Docs: schema needs to be updated for 2.0

### ISSUE THREAD

**Issue by deggertsen** [vercel/turbo#8297]
### What is the improvement or update you wish to see?

With the recent update to 2.0 the referenced schema is out of date and still uses "pipeline" instead of "tasks". Please update the schema. Ideally there would be a separately published schema for 2.0.

### Is there any context that might help us understand?

https://turbo.build/schema.json still refers to "pipeline" instead of "tasks".

### Does the docs page already exist? Please link to it.

https://turbo.build/schema.json

**Comment by anthonyshew** [comment]
Updated now! Thank you!

**Comment by psirenny** [comment]
Is there a way to target a specific JSON schema version? Our CI broke when the schema was updated to v2.0 because the repo was still on turbo@1.0. (There's a JSON schema validation step).

**Comment by anthonyshew** [comment]
@psirenny Yes, documented here: https://turbo.build/repo/docs/getting-started/editor-integration#older-versions
