### ISSUE TITLE
Scaffolding tool needs update: “pipeline” field should be “tasks” in turbo.json

### ISSUE THREAD

**Issue by PixelHabits** [vercel/turbo#8301]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/PixelHabits/turborepo-2.0-issue

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.0-canary.4

### Describe the Bug

After scaffolding a new template application using pnpm dlx create-turbo@latest, running the turbo dev command results in the following error:

```
× found `pipeline` field instead of `tasks`
    ╭─[turbo.json:3:1]
  3 │       "globalDependencies": ["**/.env.*local"],
  4 │ ╭─▶   "pipeline": {
  5 │ │       "build": {
  6 │ │         "dependsOn": ["^build"],
  7 │ │         "outputs": [".next/**", "!.next/cache/**"]
  8 │ │       },
  9 │ │       "lint": {
 10 │ │         "dependsOn": ["^lint"]
 11 │ │       },
 12 │ │       "dev": {
 13 │ │         "cache": false,
 14 │ │         "persistent": true
 15 │ │       }
 16 │ ├─▶   }
    · ╰──── rename `pipeline` field to `tasks`
 17 │     }
    ╰────
  help: changed in 2.0: `pipeline` has been renamed to `tasks`
  ```

### Expected Behavior

The turbo dev command should run without errors after scaffolding a new template application.

### To Reproduce

Scaffold a new template application using:
```
pnpm dlx create-turbo@latest
```

### Additional context

The issue can be fixed by changing the pipeline field in turbo.json to tasks as suggested by the command line output. The scaffolding tool should be updated to reflect this change.

**Comment by PixelHabits** [comment]
I also verified the issue is still present on v.2.0.1

**Comment by anthonyshew** [comment]
We're working on this here: https://github.com/vercel/turbo/pull/8284

Sorry for not having them ready to go right away! We had to wait for the npm publish to get the examples fixed up.

**Comment by anthonyshew** [comment]
Should be good now! Sorry again for the wait.
