### ISSUE TITLE
Docs: update default cache-dir path value

### ISSUE THREAD

**Issue by robert-westenberger** [vercel/turbo#8302]
### What is the improvement or update you wish to see?

With the update to 2.x.y, the default cache-dir value is ./.turbo/cache , not ./node_modules/.turbo/cache. 

### Is there any context that might help us understand?

The value in the documentation doesn't match the true default cache dir location

### Does the docs page already exist? Please link to it.

https://turbo.build/repo/docs/reference/run#--cache-dir-path

**Comment by anthonyshew** [comment]
Must have missed a few on my find-and-replace. Updated, thank you!
