### ISSUE TITLE
`@turbo/codemod migrate` will downgrade Yarn from version 4 to 1.x.

### ISSUE THREAD

**Issue by Thiry1** [vercel/turbo#8308]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/Thiry1/turborepo-bug-repro

### What package manager are you using / does the bug impact?

Yarn v2/v3/v4 (node_modules linker only)

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.0-canary.4 and 2.0.1

### Describe the Bug

`@turbo/codemod migrate` will downgrade Yarn from version 4.x to 1.x.

### Expected Behavior

packageManager field will not be changed.

### To Reproduce

1. clone reporoduction repo
2. run `npx @turbo/codemod migrate`

**Comment by Thiry1** [comment]
I guess the root cause is that `yarnpkg --version` is being executed in the tmp directory instead of the repository directory.
https://github.com/vercel/turbo/blob/67b2a855dbb28b0bcc4d16513f7a89b95c9c3906/packages/turbo-utils/src/managers.ts#L11

**Comment by Xhale1** [comment]
pnpm is also downgraded from 9 to 8

**Comment by karl-run** [comment]
Fixes the downgrade issue, but it still tries to run

```
yarn add turbo@latest --dev -W
```

at the end, which is not a valid yarn 2-4 command.

```
$ yarn add turbo@latest --dev -W                                  1 ↵  ✹main 
Unknown Syntax Error: Command not found; did you mean one of:

  0. yarn add [--json] [-F,--fixed] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
  1. yarn add [--json] [-F,--fixed] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...

While running add turbo@latest --dev -W
```

**Comment by anthonyshew** [comment]
Made a fresh issue for that since it's a different concern!
