### ISSUE TITLE
Docs: Watch Mode docs feedback

### ISSUE THREAD

**Issue by wujekbogdan** [vercel/turbo#8317]
### What is the improvement or update you wish to see?

The docs say

> When your script has a built-in watcher, you likely don't need to use turbo watch. Instead, use your script's built-in watcher and mark the task as long-running using ["persistent": true](https://turbo.build/repo/docs/reference/configuration#persistent).

It might be misleading. 

### Is there any context that might help us understand?

This isn't accurate. The watch mode that bundlers (e.g., tsup, esbuild, rollup) come with is only able to watch for changes made to files they're bundling. This is a major issue and the reason why Turbo needed the watch mode that was introduced recently (thank you devs!). I would either remove this from the documentation or add some clarification.

### Does the docs page already exist? Please link to it.

https://turbo.build/repo/docs/reference/watch#using-turbo-watch-with-persistent-tasks

**Comment by NicholasLYang** [comment]
Currently persistent tasks are not reloaded. That is something that people have asked for in #8164, so we're definitely looking into it! If you don't mind me asking, what's your specific use case for reloading persistent tasks?

We encourage people to keep using the built in watchers for existing tools because often times tool specific watchers have special logic for that tool, for instance `vite dev` or `next dev` are optimized for hot reloading, while `vite build` and `next build` are not. If a user were to use `turbo watch` with `vite build`, it would provide a much worse user experience than just using `vite dev` directly. This is also why we didn't include reloading persistent tasks, since often persistent tasks have an initial startup time, so reloading them on every change would be a pretty bad user experience. However, people clearly want this feature, so we're looking into it!

**Comment by michael-land** [comment]
When working with NestJS in a monorepo setup, I want the server to reboot whenever I edit the packages. For example, I need to reload app-1 and app-2 when package-1 changes. As @wujekbogdan mentioned, the watch mode that bundlers come with can only monitor changes made to files within that specific project.

My current workaround is to have a separate compile script and a separate persistent watch script with Nodemon. Additionally, I have separate compile and dev tasks set up. When package code changes, Turbo detects it and triggers the "compile" task for package-1, app-1 and app-2. This updates the app-1 and app-2 dist directory, causing Nodemon to reboot the persistent script. Hopefully, this can be simplified in future versions.


```json
apps/app1/package.json
{
    "script": {
        "compile": "nest build -b swc",
        "dev": "nodemon dist/main.js --watch dist --delay 1",
    }
}

pacakges/package1/package.json
{
    "script": {
        "compile": "tsc",
    }
}

turbo.json
{
    "compile": {
      "dependsOn": ["^compile"],
      "inputs": ["src/**", "tsconfig.json"],
      "outputs": ["dist/**"]
    },
    "dev": {
      "dependsOn": ["^dev"]
    }
}
```

```
pnpm exec turbo watch dev compile
```

**Comment by NicholasLYang** [comment]
Gotcha. Yeah that seems to be a common setup. We'll hopefully get that fixed ASAP

**Comment by anthonyshew** [comment]
@michael-land It sounds to me like we already have the behavior you're looking for but the documentation isn't strong enough to help you put the pieces together.

Listing out the requirements I think you're describing as I'm understanding them. Let me know if I'm wrong so I can adjust:
- You don't want to use Nest.js' hot-reloading - but you still want it to be dependency-aware and reboot.
- You don't want packages to handle their own hot-reloading - but you still want them to be dependency-aware and rebuild.

Will this work for what you need?

```json
// turbo.json
{
   "build" {
       "dependsOn": ["^build"],
       "inputs": ["src/**", "tsconfig.json"],
       "outputs": ["dist/**"],
   }
}
```
Note that I'm not marking any tasks as persistent here. We're going to solely rely on `turbo watch` to keep processes awake and aware.

```json
// apps/app-1/package.json and apps/app-2/package.json

{
  "scripts": {
    "build": "nest build -b swc",
  }
}
```

```json
// packages/package1/package.json

{
  "scripts": {
    "build": "tsc"
}
```

When I use `turbo watch build` and make an edit in `package1`, it will rebuild. When that task is done, the `app-1` will rebuild and reboot.

Does that sound right?

(For context, when writing the documentation for this, I realized `turbo watch` such a powerful feature that enables so many different patterns that I didn't know what would be confusing to write down and what would be helpful. I chose to keep it simple in the hopes that folks would provide feedback about what they would find more helpful - and here we are.) 😄

**Comment by michael-land** [comment]
Hi Anthony,

Thanks for getting back to me.

You suggested the configuration nest build -b swc only works if I want to build and rebuild when dependencies change. During development, I also want to run a development server, e.g., nest start --watch.

In my case, I have separate build and compile commands. I use compile for development and build for production. The build command does extra things like code generation and deleting the dist directory before building, while compile only builds the code.

If you'd like, I can provide a sample setup for reproduction.

**Comment by anthonyshew** [comment]
In that case, I believe you would do:

```
// turbo.json
{
   "build" {
       "dependsOn": ["^build"],
       "inputs": ["src/**", "tsconfig.json"],
       "outputs": ["dist/**"],
   },
   "dev" {
       "dependsOn": ["^dev"],
       "inputs": ["src/**", "tsconfig.json"],
       "outputs": ["dist/**"],
   },
   "app1#dev": {
     "dependsOn": [],
     "persistent": true
     // + whatever other configuration you need
   }
}
```

Note: In a real repo, I would likely use a [Package Configuration](https://turbo.build/repo/docs/reference/package-configurations) instead of the `<package>#<task>` syntax, but using that syntax here for clarity. Both ways work according to your needs.

```
// apps/app-1/package.json and apps/app-2/package.json
{
  "scripts": {
    "build": "nest build -b swc",
    "dev": "nest start --watch"
  }
}
```
```
// packages/package1/package.json
{
  "scripts": {
    "build": "tsc",
    "dev": "tsc"
}
```

A couple of things worthy of note here:
- The `dev` tasks in this configuration are all using `turbo watch`, since they're not marked as persistent. They will re-run in full with dependency-awareness from your Task Graph (same as if you did `turbo run`).
- The `"persistent": true` for `app1` opts that task out of `turbo watch`, allowing the Nest.js dev server to do it's own hot-reloading. It's solely responsible for seeing the changes in its dependent packages.

Tell me if I got it this time. 😄

**Comment by michael-land** [comment]
![CleanShot 2024-06-05 at 13 59 22](https://github.com/vercel/turbo/assets/33362998/94f924ae-3390-4aa4-800d-d1f1aa46d709)

> Tell me if I got it this time. 😄

I guess not 🫢. I created a simple repo for reproduction: https://github.com/michael-land/turborepo2-watch

In the video, I expect the app's console.log to reprint with the new value whenever I save.

**Comment by anthonyshew** [comment]
This appears to be an issue with the Nest.js hot-reloading server not tracing its modules correctly. I made a PR to your reproduction that shows this: https://github.com/michael-land/turborepo2-watch/pull/1

What I'm noticing:
- Run `turbo watch dev`
- Open browser to localhost:3000
- Change the string in the package
- The string will change in your browser - but the Nest.js server won't "hot reload" instantly. However, if you open the `./apps/backend/src/main.ts` and hit save in your browser, you'll see a fresh log in the Nest.js task with the new value.

For me, that indicates that the Nest.js hot reloader isn't quite handling what it is meant to, but I admittedly don't know if the Nest.js hot reloader is supposed to handle this case.

For the sake of thoroughness, I tried [the first strategy I proposed](https://github.com/vercel/turbo/issues/8317#issuecomment-2150416285) and changed the `dev` script in `backend` to `"nest build -b swc && nest start` and things are working as I would expect them to.

Overall, it looks like `turbo watch` is working as intended here (although we do still need to improve the documentation).

**Comment by michael-land** [comment]
I tried your PR, and Next.js example is working fine (it might also watch node_modules for hot reloads). However, I can't get `nest build -b swc && nest start` to work. I'll wait to see if others have the same issue. I appreciate your help. Thanks!

**Comment by anthonyshew** [comment]
Apologies, I left out that you'll want to remove the `app1#dev` configuration. Pushed [another commit to show a diff](https://github.com/michael-land/turborepo2-watch/pull/1/commits/290221547d8599e06bb82313ef74e37b57844bb9). Once you do that, it will _kinda-hot-reload_ when you hit save on a file in the Nest.js app.

**Comment by michael-land** [comment]
it works now 🥳

**Comment by anthonyshew** [comment]
Love to hear it. Thinking about what docs updates I need to make to make this more clear.

**Comment by wujekbogdan** [comment]
> Currently persistent tasks are not reloaded. 

Does it mean that if I set up Turbo the way I described [here](https://github.com/vercel/turbo/discussions/8318) then I'm all set?

``` sh
turbo watch dev --filter=@my-namespace/my-app
```

Where the dev task for the app being watched is defined as:

``` json
{
  "dev": "tsup --watch --onSuccess 'node dist/index.js'"
}
```

The `build` task for all the packages is defined as:

``` json
{
  "build": "tsup"
}
```

And the turbo config is defined as

``` json
{
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**"]
    },
    "dev": {
      "persistent": true,
      "dependsOn": ["^build"],
      "cache": false
    },
  },
}
```

Based on what you say, it seems that this setup is correct - `@my-namespace/my-app` dependencies will restart on change, while the `dev` task will not (as intended) because it's persistent - it will use the` tsup` watcher.

Or am I wrong? Maybe I need to explicitly include the `build` task even though it's a dependency of `dev`?

``` sh
turbo watch build dev --filter=@my-namespace/my-app
```

**Comment by ScottAwesome** [comment]
> Gotcha. Yeah that seems to be a common setup. We'll get that fixed ASAP

This sounds counter to whats written in the docs [here](https://turbo.build/repo/docs/reference/watch#using-turbo-watch-with-persistent-tasks)

To Quote:

>When your script has a built-in watcher, you likely don't need to use turbo watch. Instead, use your script's built-in watcher and mark the task as long-running using "persistent": true

**Comment by weyert** [comment]
If I understand it correctly, you enforce the rebuild of the project itself, which will trigger the restart?

I still think something like `nx watch` would be useful too:
https://nx.dev/nx-api/nx/documents/watch

**Comment by anthonyshew** [comment]
@wujekbogdan That sounds to me like it would work. Do you not get the behavior you're looking for?

**Comment by wujekbogdan** [comment]
@anthonyshew 

Yes, it works, but it would be good to clarify the following things in the docs:

- How does the watch mode affect persistent tasks? For example, when a persistent `dev` task depends on `^build`, Turbo will only restart the dependent `^build` tasks, keeping the persistent task running.
- How does the `--filter` work together with the watch mode? It would be good to clarify that dependencies are still watched when a package is specified with the `--filter` flag. One might think that `--filter` causes only the filtered package to be watched.
- Remove this line from the docs: _"When your script has a built-in watcher, you likely don't need to use turbo watch."_ It's very misleading. You still need Turbo's watch mode to watch the dependencies of the package that's being built with a bundler ([example](https://github.com/vercel/turbo/issues/8317#issuecomment-2152005399)). The bundler's built-in watcher will only watch a specific package - it won't watch its dependencies.

**Comment by hackwaly** [comment]
Watch mode re-run my persistent task without kill previous job.  I'd like it do not re-run persistent tasks. Or allows `turbo run xx watch yy` to do both watch tasks and run tasks in one command.

**Comment by up209d** [comment]
`nest start` on every change is a nuke restarting nestjs app, that defeats the quick restart purpose of `nest start --watch` (it is way quicker), but it seems like the only way (a hack, a workaround). I blame nestjs not turborepo, they have little to none configuration with their watch mode.

**Comment by kelchm** [comment]
I've done a bit of a deep dive on this over the last 24 hours and wanted to share my findings in case they help anyone else. 

Basically -- the problem I observed really just comes down to the fact that the `nest start --watch` is relying on tsc watch to do the heavy lifting. This means that:
-  In cases where the code change in the shared package  _doesn't_ result in changes to any `*.d.ts` files, the nest application _will not be reloaded_.
- If you do make a change in the shared package that *does* result in a change to a `*.d.ts` file, the reloading of the nest application magically _just works_.

As an experiment, I patched in a simple change to `@nestjs/cli` locally to simply inject the `--watch` flag to the node process created by `spawnChildProcess` in [start.action.ts](https://github.com/nestjs/nest-cli/blob/10.4.9/actions/start.action.ts#L179). This works as expected, with node itself taking over to restart the server when a change occurs in `node_modules`.

I'm not sure at this point if I'm going to stick with this approach, but in general I prefer this to the alternative of needing to have entirely separate tasks for compilation and the server itself -- that approach ends up being pretty overwhelming when you have more than one server running at the same time.

**Comment by kelchm** [comment]
After giving this some further thought, I've discovered a simple workaround that requires zero modifications to the NestJS CLI. 

The `@nestjs/cli` already has built-in support for passing arbitrary arguments to the spawned Node.js process via the `--` separator. This means we can leverage Node.js's native `--watch` flag (available in Node.js 18.11+) to automatically restart the application when **any** dependency changes, including internal workspace packages that TypeScript's watch mode wouldn't normally detect.

**Usage:**
```bash
nest start --watch -- --watch
```

**What this does:**
- The first `--watch` enables NestJS CLI's TypeScript watch mode (compiles your app on source changes)
- The second `--watch` (after `--`) is passed directly to the Node.js process, enabling Node's native file watcher

**Why this solves the problem:**

When using pnpm workspaces with Turbo (or similar tools), internal package rebuilds update files in `node_modules`, but TypeScript's watch mode only detects changes to `.d.ts` files. Node's `--watch` flag, however, detects **all** file changes in imported modules—including pure implementation changes (`.js` files)—and automatically restarts the process.

While the double `--watch` may look a bit odd at first glance, it's a clean solution that works today without any patches or custom tooling.

**Comment by kelchm-pfizer** [comment]
After further investigation, I discovered a simple workaround that leverages the existing nestjs cli's `--exec` flag to enable Node.js's native watch mode without making any modifications to the NestJS CLI.

**Usage:**

```bash
nest start --watch --exec "node --watch"
```

**How it works:**

- The first `--watch` enables NestJS CLI's TypeScript watch mode (compiles / runs the app on source changes)
- `--exec "node --watch"` tells the NestJS CLI to spawn Node.js with the `--watch` flag, enabling Node's native file watcher (which detects all file changes in imported modules)

**Comment by jdnichollsc** [comment]
> After further investigation, I discovered a simple workaround that leverages the existing nestjs cli's `--exec` flag to enable Node.js's native watch mode without making any modifications to the NestJS CLI.
> 
> **Usage:**
> 
> nest start --watch --exec "node --watch"
> **How it works:**
> 
> * The first `--watch` enables NestJS CLI's TypeScript watch mode (compiles / runs the app on source changes)
> * `--exec "node --watch"` tells the NestJS CLI to spawn Node.js with the `--watch` flag, enabling Node's native file watcher (which detects all file changes in imported modules)

Thanks for sharing Mat! <3
