### ISSUE TITLE
Turbo 2.0 - Envs from GitHub Actions are not loaded

### ISSUE THREAD

**Issue by timheerwagen** [vercel/turbo#8320]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/timheerwagen/turborepo-env-bug

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

turbo@2.0.0-canary.4

### Describe the Bug

Envs from local .env files are loaded correctly.

Envs in GitHub Actions are not loaded:
```
env:
  FRONTEND_URL: ${{ vars.FRONTEND_URL }}
```

### Expected Behavior

Envs are loaded and shown inside `next.config.mjs` via `console.log`

### To Reproduce

Run GitHub Actions and turbo task inside. `npx turbo run build  --filter=frontend`

### Additional context

It works on ^1.13.4.

**Comment by weyert** [comment]
Does it work w hen you pass `--env-mode=loose`? 
I think you need to add `FRONTEND_URL` to `globalPassThroughEnv` in `turbo.json`

**Comment by kode15333** [comment]
I experienced the same, and I need to add globalDependences to turbo.json ([link](https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables))

**Comment by timheerwagen** [comment]
@kode15333 That works, thank you very much. I must have overlooked it.

**Comment by yamatsum** [comment]
@weyert 
Even for environment variables that do not start with `NEXT_PUBLIC_*` , I'm able to retrieve environment variables set in [Vercel](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#environment-variables-on-vercel). Why?
I haven't set anything inside turbo.json

**Comment by flayks** [comment]
It took me quite a while to figure out that Turbo was stripping all the env variables, it would be good to have a warning when starting the project or building!

Although I can understand it would extended and allow more configuration and safety, it is very confusing.
