### ISSUE TITLE
Docs: old path indexed by google, missing redirect?

### ISSUE THREAD

**Issue by moklick** [vercel/turbo#8322]
### What is the improvement or update you wish to see?

When I google something like "turbo publishing packages", it shows me links to https://turbo.build/repo/docs/guides/publishing-packages . That path was renamed to https://turbo.build/repo/docs/guides/publishing-libraries but it seems that there is no redirect, so it shows a 404.

### Is there any context that might help us understand?

no

### Does the docs page already exist? Please link to it.

https://turbo.build/repo/docs/guides/publishing-libraries

**Comment by anthonyshew** [comment]
This has been corrected. Thank you for reporting. 🙌
