### ISSUE TITLE
New TUI breaks some command-line scripts

### ISSUE THREAD

**Issue by isaacharrisholt** [vercel/turbo#8323]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/isaacharrisholt/turborepo-precommit-bug

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

turbo 2.0.0-canary.4

### Describe the Bug

When running under certain conditions, like under `pre-commit`, Turbo 2.0+ will run into an internal error. This appears to be when trying to start the TUI, as piping output to `/dev/null` fixes the issue (but is definitely _not_ ideal). Adding `CI=1` doesn't seem to fix anything.

### Expected Behavior

Ideally, Turbo should either detect that it cannot use the TUI and use the old method of streaming logs, or better, there should be a CLI flag that forces Turbo to use the old log style (no TUI).

### To Reproduce

Install `pre-commit` using `pip`, `pipx` etc. (any valid Python installation method) in the example repo. Run `pre-commit run --all-files` to run the commit hooks.

Essentially, any use of `turbo run` under `pre-commit` now fails since 2.0.

**Comment by RohanJnr** [comment]
is there anyway to avoid the TUI using command line options that can be passed to the turbo command ? the pre-commit is stuck forever
![image](https://github.com/vercel/turbo/assets/37217450/a9a97b6d-d29a-4638-bf20-ae9872886187)

**Comment by chris-olszewski** [comment]
The env flag to disable the TUI is `TURBO_UI=0`.

Looking into how `pre-commit` is starting `turbo` hooked up to a TTY in such a way that we crash.

**Comment by isaacharrisholt** [comment]
> The env flag to disable the TUI is TURBO_UI=0.

Nice, thanks! Is this documented anywhere? I assume we might also need to use it in CI?

**Comment by chris-olszewski** [comment]
> Nice, thanks! Is this documented anywhere? 

It looks like this didn't get a spot. I'll quick add that as well as make sure `CI=1` also disables the TUI.

> I assume we might also need to use it in CI?

For the most part this shouldn't be necessary as most CI environments do not set up a TTY when running jobs. If your CI provider does setup a TTY (such as [CircleCI](https://discuss.circleci.com/t/reprise-allow-for-using-circle-ci-tooling-without-a-tty/23309)), then you'll need to also add this to your CI setup.

#8333 should fix the underlying crash

**Comment by isaacharrisholt** [comment]
Amazing, thanks for picking this up so quickly! Turbo 2.0 looks great, and I love the TUI for local work

**Comment by chris-olszewski** [comment]
@isaacharrisholt @RohanJnr 

Could you try out `2.0.2-canary.0` and see if this fixes your issue? If not, please reopen the issue.

**Comment by isaacharrisholt** [comment]
Seems to work, thanks!

**Comment by Raphael-08** [comment]
umm i think i have the same issue with a script when the script needs some user input like n/y
unable to enter into the tui using enter
only arrow keys work but enter and ctrl+z won't work
