### ISSUE TITLE
Docs: Docker Docs Global Turbo Install Breaks on Major Version Update

### ISSUE THREAD

**Issue by MerfAvenger** [vercel/turbo#8328]
### What is the improvement or update you wish to see?

The docker documentation needs to reflect the fact that the global turbo install will not always be backwards compatible i.e. the following causes a breaking issue for people using turbo v1:

```docker
RUN yarn global add turbo
```

This needs to update to illustrate how to lock the turbo install to a specific major version. Otherwise some other strategy should be devised that does cause this unpredictable behaviour.

### Is there any context that might help us understand?

We have referred to the Turbo documentation for dockerfile setup available from: https://turbo.build/repo/docs/guides/tools/docker 

Specifically, we use the following, based on the `yarn` command from the docs: 
```docker
RUN pnpm add -g turbo
```

Turbo released 2.0 and this removed the following configuration options (instead of deprecating them). This resulted in the following for us since we used the `outputMode` configuration option and global now installed v2 automatically:
```
0.504 Error: turbo_json_parse_error
0.504
0.504   x Found an unknown key `outputMode`.
0.504     ,-[29:1]
0.504  29 |             "outputs": ["**/*.{js,jsx,ts,tsx,json,md}"],
0.504  30 |             "outputMode": "new-only"
0.504     :             ^^^^^^^^^^^^
0.504  31 |         },
0.504     `----
```

### Does the docs page already exist? Please link to it.

https://turbo.build/repo/docs/guides/tools/docker

**Comment by anthonyshew** [comment]
Curious, do you have `turbo` installed into your repository?

**Comment by MerfAvenger** [comment]
We have Turbo installed in the repository at `^1.10.12`.

**Comment by omawhite** [comment]
I just ran into this same issue, today, did the same thing as @MerfAvenger. Either updating the docs to pin a specific version, and/or coming up for a way for the dockerfile to just use the workspace version of turbo would be nice.

**Comment by anthonyshew** [comment]
Just fixed this here: https://turbo-site.vercel.sh/repo/docs/guides/tools/docker#example

Thanks for bringing it up. Appreciate it!
