### ISSUE TITLE
Docs: `pnpm` install of eslint not correct on the website

### ISSUE THREAD

**Issue by gabewillen** [vercel/turbo#8378]
### What is the improvement or update you wish to see?

First I just want to thank everyone at Vercel for the tools you make. You all make the web / js / ts development significantly better and it's appreciated.

The documentation for the eslint install for `pnpm` is `pnpm install jest --save-dev --recursive --filter=ui --filter=docs --filter=web` which is incorrect.

### Is there any context that might help us understand?

<img width="842" alt="Screenshot 2024-06-07 at 9 36 58 AM" src="https://github.com/vercel/turbo/assets/91307534/4daa3d6b-9a50-4219-9b2c-5576bf8f7c31">
<img width="861" alt="Screenshot 2024-06-07 at 9 36 49 AM" src="https://github.com/vercel/turbo/assets/91307534/7b37c542-5fa1-4736-bcbe-30d110c36788">

### Does the docs page already exist? Please link to it.

https://turbo.build/repo/docs/guides/tools/eslint

**Comment by anthonyshew** [comment]
Can you say how it's incorrect? In what way?

**Comment by gabewillen** [comment]
> Can you say how it's incorrect? In what way?
> 
> Happy to fix, just not sure why it's wrong because it works well when I try it.

It suggests installing `jest` instead of just installing `eslint` was this by design? It seems like an unnecessary added dependency. In my case we are using `vitest` why do I have to install `jest` also?

**Comment by anthonyshew** [comment]
🤦 I was completely looking past that at the flag combination. Fixing now.

**Comment by gabewillen** [comment]
> 🤦 I was completely looking past that, focusing on the flag combination. You're totally right. Fixing now.

Okay good 😅 I was starting to second guess myself. I believe `yarn` says jest as well.

**Comment by gabewillen** [comment]
This is definitely a 13 pointer though you'll probably have to take the rest of the day off after fixing and testing this one...😉

**Comment by anthonyshew** [comment]
T-Shirt Size: Hulk in Green Mode

**Comment by anthonyshew** [comment]
Fixed now. Thank you for reporting.
