### ISSUE TITLE
`create-turbo` not able to find tasks on Windows

### ISSUE THREAD

**Issue by Ipriyankrajai** [vercel/turbo#8389]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

npx create-turbo@latest && pnpm dev

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

2.0.3-canary.0

### Describe the Bug

When I Create new turbo repo with npx create-turbo@latest and select package manager as pnpm and run pnpm dev it throws an error.

![image](https://github.com/vercel/turbo/assets/32142351/18e13ec8-b8a4-4652-8af0-4bbc4958c4bd)

### Expected Behavior

It should start an development server

### To Reproduce

Run the following commands
1. npx create-turbo@latest
2. cd to project directory
3. pnpm dev

**Comment by anthonyshew** [comment]
I can't reproduce this on macOS and I'd be quite surprised to learn that there's a platform difference here.

Can I ask what other debugging you've done?
- Does running `pnpm install` again help possibly?
- I see the directory is named `turbo-1`. Does that mean you're using Turborepo at version 1? (Could be just a placeholder but want to make sure.)

**Comment by Ipriyankrajai** [comment]
Hello @anthonyshew,

1) Yes i tried running `pnpm install` but it doesn't help.
2) I'm using turbo version 2.0.1. `turbo-1` is just project name

**Comment by Ipriyankrajai** [comment]
Hello @anthonyshew,
Looks like `turbo@2.0.4` has fixed this issue.
