### ISSUE TITLE
Turbo crash on Windows Server 2016 Data Center

### ISSUE THREAD

**Issue by dungjk** [vercel/turbo#8391]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/vercel/turbo/tree/main/examples/basic

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

turbo@2.0.3-canary.0

### Describe the Bug

Environment:
Windows Server 2016 Data Center.

I've created very minimal app using command.
```sh
$ npx create-turbo@canary -e basic
$ yarn build
```

Turbo is crash with following log:
```toml
name = "turbo"
operating_system = "Windows 10.0.14393 (Windows Server 2016 Datacenter) [64-bit]"
crate_version = "2.0.3-canary.0"
explanation = '''
file 'crates\turborepo-lib\src\process\mod.rs' at line 122
'''
cause = "not poisoned: PoisonError { .. }"
method = "Panic"
backtrace = """

   0: 0x7ff6e82c66e3 - <unresolved>
   1: 0x7ff6e82e9327 - <unresolved>
   2: 0x7ff6e83cba86 - <unresolved>
   3: 0x7ff6e7e5b5cc - <unresolved>
   4: 0x7ff6e7e3b092 - <unresolved>
   5: 0x7ff6e7e4d70c - <unresolved>
   6: 0x7ff6e7e55247 - <unresolved>
   7: 0x7ff6e7e03ced - <unresolved>
   8: 0x7ff96a7084d4 - <unresolved>
   9: 0x7ff96a9b1791 - <unresolved>"""
```

### Expected Behavior

Turbo should run build task without issue.

### To Reproduce

Environment:
Windows Server 2016 Data Center.

I've created very minimal app using command.
```sh
$ npx create-turbo@canary -e basic
$ yarn build
```

### Additional context

I install `turbo@1.13.4.`
Edit `turbo.json`, change `tasks` to `pipeline` then run `yarn build`.
Everything run well without any issue.

**Comment by anthonyshew** [comment]
This looks similar to #8349 and #8326. Does setting [the `TURBO_UI=0` environment variable](https://turbo.build/repo/docs/reference/system-environment-variables) help?

**Comment by dungjk** [comment]
Thankyou @anthonyshew 
I've set env TURBO_UI=0 for CI pipeline and it run well now.
You saved my day.
