### ISSUE TITLE
eslint-plugin-turbo

### ISSUE THREAD

**Issue by andrevenancio** [vercel/turbo#8404]
### What is the improvement or update you wish to see?

The documentation of the plugin states that `"turbo"` needs to be added. In reality all your examples use the full package name. e.g.: https://github.com/vercel/turbo/blob/main/examples/kitchen-sink/packages/config-eslint/index.js

### Is there any context that might help us understand?

I've upgraded to turbo 2.0 and I'm having some errors like

```
ESLint: 8.57.0

TypeError: Failed to load plugin 'turbo' declared in '.eslintrc.json » @intangible/eslint-config » eslint-config-turbo': Cannot convert undefined or null to object
    ```

**Comment by anthonyshew** [comment]
Betrayed by my own find and replace! Thanks for reporting.
