### ISSUE TITLE
Terminal UI has multiple issues and downsides

### ISSUE THREAD

**Issue by MickL** [vercel/turbo#8419]
### What package manager are you using / does the bug impact?

`bun` but also occurs using `npm`

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.3

### Describe the Bug

I wrote [a lot of feedback](https://github.com/vercel/turbo/discussions/7802#discussioncomment-9638656) to the new Terminal UI because it has tons of bugs and problems but I dont know if it has been read because you just released Turbo v2 with a not functional Terminal UI:

**Crucial issues that make the UI unusable:**

1 - I cant scroll the logs of a tasks. Instead it scrolling scrolls the list of tasks in the left sidebar.

This is especially crucial if a task doesnt have the presistent: true option because atm one needs to go into a task with enter to be able to scroll in it. This is very cumberstone to me, I would assume navigating tasks with the arrow keys is fine while I would be able to scroll a task immediately without then need to jump into it. Additionally this also means all tasks that dont have `persistent: true` option can never be scrolled.

Suggested solution:
* Dont scroll the sidebar with the mousewheel / trackpad
* Scroll activated tasks without the need to "enter" it first

2 - Scrolling is not possible with a Trackpad at least on macOS: I can scroll up once but then I cant scroll down anymore, the frame jumps up to the very top multiple times per second.

This occurs at least in Webstorm. I tested in iTerm and there trackpad scrolling seems to work.

**Must haves (imho)**

3 - There are a lot of characters printed in the terminal for no reason when scrolling?

<img width="965" alt="Bildschirmfoto 2024-06-11 um 11 35 27" src="https://github.com/vercel/turbo/assets/5103210/1c7ecbc3-fccd-4b55-8ef2-64af4ded8faa">

This occurs at least in Webstorm. I tested in iTerm and there I dont see them.

4 - Lines are not clickable, colors are not emitted.

Here you can see that when I run "bun lint" normally I can click the line of code and it jumps into it (using Webstorm). Also the warning is yellow and an error would be red:
<img width="783" alt="Bildschirmfoto 2024-06-11 um 11 29 15" src="https://github.com/vercel/turbo/assets/5103210/be1c9902-2466-43c3-bfd4-450aea7193da">

But if I run the same with Turbo (same with `ui: "stream")` I cant click the line and the color is lost aswell:
<img width="966" alt="Bildschirmfoto 2024-06-11 um 11 29 34" src="https://github.com/vercel/turbo/assets/5103210/10c68e50-58e2-40cd-8aae-1ffe0b462627">

**Feature requests**

5 - When starting just one task (e.g. with --filter="...") there should be no left sidebar. Actually in this case the whole terminal UI can be deactivated

Otherwise when starting just one task and there is a left sidebar, the task should be interactive immediately. It is very scary to do something like drizzle:push and then it asks "Do you really want to push changes? > Yes, No " and I need to press enter to get into the task

**Comment by anthonyshew** [comment]
In the spirit of keeping feedback actionable, I'll close and lock this one. If you'd like to open an issue with a clear focus on one bug (or many, each with their own focus), we're happy to get those addressed. Do be mindful of existing issues when doing so, adding thumb-up reactions to the ones you care about so we can gauge interest.

We absolutely listened to feedback working up to this release and appreciate yours as well! We're not perfect, bugs happen, and I can understand if a new feature is not to your tolerance level. Everyone is different and there are a lot of folks enjoying the new UI today. We're going to keep making it better.

We're also happy to take PRs if you'd like to help!
