### ISSUE TITLE
turbo 2.0 build --env-mode=loose

### ISSUE THREAD

**Issue by andrevenancio** [vercel/turbo#8424]
### Link to code that reproduces this issue

no

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

turbo@2.0.3

### Describe the Bug

When I run `npm run build` locally I have no issue as all my different apps have individual `.env` files on them and they exist at build time.

When I deploy the build fails. It seems that for some reason builds dont inherit environment variables by default. I'm not really sure what use case that serves, and I assume most apps that require env variables will need those to be provided in order to produce a build... Regardless, I investigate and apparently I can use --env-mode=loose which in theory makes ALL environment variables available.

My build still fail. I was pretty excited about using turbo 2.0, but I've been blocked 2 days straight with things that were not happening before.

### Expected Behavior

I would expect that builds read the env variables set on my project dashboard.

### To Reproduce

have an app that requires env variables

**Comment by NicholasLYang** [comment]
Hi @andrevenancio, thanks for the issue. We're definitely working through some kinks in our environment variable setup. Could you try adding the environment variables to the [`globalEnv` or `env` keys](https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables#adding-environment-variables-to-task-hashes)? That might be a potential solution. Alternatively, could you send the Vercel build error message? You can send it to nicholas.yang@vercel.com if you don't wish to make it public.

**Comment by andrevenancio** [comment]
adding variables to globalEnv means that I need to add variables for appA, appB, appC appD etc. I have a lot of apps (mostly prototypes) and in them a lot of env variables. is this meant to be on the turbo.json in the root?

**Comment by NicholasLYang** [comment]
In the case where environment variables are specific to a task, you can add them to the `env` key in the task entry in `turbo.json`. We don't currently have a way to configure environment variables at the package level unfortunately

**Comment by andrevenancio** [comment]
Not for the package, but for the apps. I think packages that require environment variables are poorly designed. They should be set by each app

```
const { client } from '@repo/some-package';
const foo = client(process.env.SOMETHING);
foo.someMethod();
```

I have multiple apps and packages. Lets assume this
```
apps
  /app-1
   /app-2
   /app-3
packages
  /config-eslint
  /ui
turbo.json
```

What you are saying is that I need to add ALL environment variables for app-1, app-2 and app-3 on that turbo.json on the root?
Wouldn't it be better to had individual turbo.json on each of the apps? But my question is: Why do we need to complicate this? Why did `strict` was preferred over `loose` as the default? already have individual `.env` files on each of the apps. I already added the environment variables on my project on vercel.com, why do I need to repeat myself and be explicit and include all the environment variables necessary to each app? Is it normal for users to create too many environment variables that are not in use and require this explicit mention on turbo.json?
The same work a developer has to explicitly mention which env variables are in use on the project is the same amount of work they have to go to vercel and remove any unused environment variables.
I do not understand the requirement of having to tell turbo which environment variables will be available on the deployment environment....

This gives overhead and its confusing. I'm seriously consider reverting to turborepo 1x and ignore this decision.

**Comment by anthonyshew** [comment]
You can individually create `env` keys for each package using [Package Configurations](https://turbo.build/repo/docs/reference/package-configurations), as you're suggesting, and it's the technique I tend to prefer, personally. I like the explicitness of what specifically goes where.

While I do agree there is overhead associated with having to explicitly mark variables in the `env` key, this is significantly different than _initializing the presence_ of the variable to the system's environment (e.g. adding an environment variable to your CI provider).

It's important to understand that Turborepo has no understanding of _which environment variables are important to the task_ without you telling it which ones matter. It might come as a surprise that there are many, many environment variables on your machine right now that you may or may not be aware of. From Turborepo's perspective, there's no way of knowing which of those variables matter to your caching behavior - until you say so. For example, changing your system's `PATH` likely shouldn't result in a cache miss so, by default, it doesn't.

This change to Strict Mode is important as it helps you to [not ship your preview environments to production](https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables). While it might be mildly annoying to have that list exist explicitly, it's vitally important to creating the right behavior for the repository, and it has much better tradeoffs than implicitly missing cache on all possible environment variables.

That said, we're continuing to think about how we can make environment variables a better experience in Turborepo, with the change to Strict Mode being an important Step 1. We're going to keep iterating here.

**Comment by andrevenancio** [comment]
Hey Anthony. apologies for nagging, but I find this explanation hard to argue against and it gives me the context that I didn't have by looking at migration of the PR that the migration refers too. So thanks for taking the time.

Let me steal another minute of your time just to leave here a solution for ME and others.

So you're saying that in the case of monorepo's where the developers choose to have "project" (I say project to link to vercel) and not "app" to link to the monorepo, but they are effectively the same and its probably a good idea to merge semantics in the future. Its confusing to say `project` when I want to refer to something on my vercel dashboard and `app` when I want to specify a folder living on my monorepo - but I digress.

So in the case where we have individual environment variables on each app, you are saying I need to add a new turbo.json to my app which extends from my root one and in there I have some overrides.
So in my particular example:

I have 3 apps `app-1`, `app-2` and `app-3`. Each app with their own environment variables.

my code would look like:
```
apps
  /app-1
      ...
      package.json
      turbo.json <-- new file
   /app-2
      ...
      package.json
      turbo.json <-- new file
   /app-3
    ...
    package.json
      turbo.json <-- new file
packages
  /config-eslint
  /ui
turbo.json
```

and that turbo.json on `apps/app-1/turbo.json` would look something like this:

```
{
  "extends": ["//"],
  "tasks": {
    "build": {
      "env": ["GOOGLE_ANALYTICS", "MY_ENV_VARIABLE1", "MY_ENV_VARIABLE2", "MY_ENV_VARIABLE3"]
    },
    "special-task": {} // New task specific to this package
  }
}
```
where `MY_ENV_VARIABLE1`, `MY_ENV_VARIABLE2` and `MY_ENV_VARIABLE3` is exclusive to the `apps/app-1`.

In the case where env variables have a common name but might have a different value per app/project can those variables be injected on the root turbo.json?

So `GOOGLE_ANALYTICS` would be on my root turbo.json and the other 3 would be on my app specific turbo file. OR, because I'm overriding the `build` task any `build` task on the root gets discarded?

Apologies if I'm being confusing. Hope It was clear :)

**Comment by anthonyshew** [comment]
Let me start from scratch re-explaining what you have, so I can make sure I don't assume things in what you wrote. Trying to avoid "Curse of Knowledge"-ing myself into a bad explanation. 😄 

Package Configurations let you set a custom configuration for each package, extending from the root `turbo.json`. The Package Configuration extends from the root `turbo.json`, inheriting everything from there. There's one non-obvious behavior worth being aware of: Adding a key to a task in a Package Configuration **overwrites** the key from the root `turbo.json`, rather than *merging*.

For the case of handling the `env` key for your build task, I'll give the following example (building off of your example):

```
// ./turbo.json
{
  "tasks": {
    "build": {
      "env": ["GOOGLE_ANALYTICS", "VAR_1"]
    }
  }
}
```
```
// ./apps/app-1/turbo.json
{
  "extends": ["//"],
  "tasks": {
    "build": {
      "env": ["GOOGLE_ANALYTICS", "VAR_4"]
    }
  }
}
```

The directory structure you've written above is correct. Let's now list out which variable is available in which tasks in Strict Mode:
- `VAR_1` is available in **every build task except the `build` task of `app-1`**.
- `GOOGLE_ANALYTICS` is available in **all tasks** because we repeated it in the Package Configuration.
- `VAR_4` is **only available in the `build` task of `app-1`**. It won't be available anywhere else.

Hopefully that's enough to go on. Let me know if that still leaves anything out.

**Comment by andrevenancio** [comment]
That's my understanding. Thanks for putting things so clearly.
