### ISSUE TITLE
Docs: Changeset action node job name differs from version

### ISSUE THREAD

**Issue by DaveVED** [vercel/turbo#8425]
### What is the improvement or update you wish to see?

In the [changeset](https://github.com/vercel/turbo/blob/main/examples/with-changesets/.github/workflows/release.yml), the Node action job name states ` - name: Setup Node.js 18.x` but uses `          node-version: 20.x`. I have to change this for ever new repository I create using `npx create-turbo@latest -e with-changesets`.

### Is there any context that might help us understand?

Example [here](https://github.com/vercel/turbo/blob/main/examples/with-changesets/.github/workflows/release.yml) should be updated to be consistent. 

### Does the docs page already exist? Please link to it.

https://github.com/vercel/turbo/blob/main/examples/with-changesets/.github/workflows/release.yml

**Comment by anthonyshew** [comment]
Thanks, fixed! Probably faster to make the PR last time and get the credit for the keen find next time. 😄
