### ISSUE TITLE
Docs: Missing Prettier package in examples

### ISSUE THREAD

**Issue by Stanzilla** [vercel/turbo#8444]
### What is the improvement or update you wish to see?

with-tailwind and other examples list Prettier but don't have a Prettier config package

### Is there any context that might help us understand?

See https://github.com/vercel/turbo/tree/main/examples/with-tailwind

it says `[Prettier](https://prettier.io/) for code formatting` at the bottom but there is no Prettier config package included.

I think it would be a great addition if such an example package was added since many people use Prettier in monorepos!

### Does the docs page already exist? Please link to it.

https://github.com/vercel/turbo/tree/main/examples/with-tailwind

**Comment by anthonyshew** [comment]
You don't have to have a Prettier configuration file for Prettier to do its work. It will use its default rules without one.

Just for fun, I checked with the robots!: https://sdk.vercel.ai/s/mcvXHQ26wSf1

**Comment by Stanzilla** [comment]
> sdk.vercel.ai/s/mcvXHQ26wSf1

While true, many people still have a config file to adjust the settings and enable plugins, like the popular tailwind class sorting one, Would be handy to have an example for it regardless.
