### ISSUE TITLE
dotenv-cli doesnt work after upgrading to 2.0.3

### ISSUE THREAD

**Issue by Angusross111** [vercel/turbo#8454]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/Angusross111/turborepo-test

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

turbo@2.0.3

### Describe the Bug

I have a global `.env` file that has shared environment variables. I use dotenv-cli to read in the env file before running any turbo commands:
```
"build": "dotenv -e .env -- turbo build",
```
This previously worked in version `1.13.3`, but after upgrading to `2.0.3`  with `bunx @turbo/codemod@latest update` none of my apps get the environmental variables.
see attached reproduction repo with commit to see it failing
https://github.com/Angusross111/turborepo-test/commit/2923c52c076985c383a049fa924fd614489db355

With this diff it works as expected.
```
diff --git a/package.json b/package.json
index 145a5d3..a4c7f25 100644
--- a/package.json
+++ b/package.json
@@ -9,7 +9,7 @@
   },
   "devDependencies": {
     "prettier": "^3.2.5",
-    "turbo": "latest",
+    "turbo": "1.13.3",
     "typescript": "^5.4.5",
     "dotenv-cli": "^7.4.2"
   },
diff --git a/turbo.json b/turbo.json
index 3bb895c..93bbcf7 100644
--- a/turbo.json
+++ b/turbo.json
@@ -1,7 +1,7 @@
 {
   "$schema": "https://turbo.build/schema.json",
   "globalDependencies": [".env"],
-  "tasks": {
+  "pipeline": {
     "build": {
       "dependsOn": ["^build"],
       "inputs": ["$TURBO_DEFAULT$", ".env", ".env.*"],
```

### Expected Behavior

Using dotenv-cli I should be able to read in and set Env Variables for all tasks and downstream frameworks

### To Reproduce

install and run
```
bun run build
```
https://github.com/Angusross111/turborepo-test

Have also tried npm with the same result

**Comment by orjan** [comment]
You’ll probably need to specify the variables that you would like to pass through?

https://turbo.build/repo/docs/reference/configuration#env

**Comment by orjan** [comment]
References: https://github.com/vercel/turbo/issues/8424

**Comment by NicholasLYang** [comment]
Hi, yes, with turbo 2.0, we now have the strict environment variable mode enabled by default. This mode requires you to specify your environment variables, either in `env` or `passThroughEnv`, for them to be made available to a task. If you wish to go back to the previous behavior, you can pass `--env-mode=loose` as a flag

**Comment by Angusross111** [comment]
Should this also affect deploying on Vercel? As my builds are also failing on vercel.

**Comment by Angusross111** [comment]
After a bit more reading I can see that it does
>Frameworks like Next.js inline build-time environment variables (e.g. NEXT_PUBLIC_XXX) in bundled outputs as strings. Turborepo will automatically try to infer these based on the framework, but if your build inlines other environment variables or they otherwise affect the build output, you must declare them in your Turborepo configuration.

https://vercel.com/docs/monorepos/turborepo#deploy-turborepo-to-vercel
