### ISSUE TITLE
A persistent task cannot depend on it

### ISSUE THREAD

**Issue by TheKnarf** [vercel/turbo#8484]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

N/A

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.3

### Describe the Bug

```
$ pnpm turbo watch --filter bff dev
x invalid task configuration

Error: "dialogporten-types-generated#dev" is a persistent task, "bff#dev" cannot depend on it
[turbo.ison: 12:11]
   "dependsOn": [
     "^dev"
       persistent task
  ],
  ```

### Expected Behavior

If one persistent task depends on another persistent task then I would expect it to startup both and simply run them in parallel. Maybe there could even be config called something like "delay" to ensure that it gives each task a bit of startup-time before starting the next one.

The documentation says the following:

> Because a long-running process won't exit, tasks that would depend on it would never run. Once you've labeled the task as persistent, turbo will throw an error if other tasks depend on it.
> 
> This option is most useful for development servers or other "watch" tasks.

But I don't see how this is useful. If I have two package in a pnpm monorepo, `package-b` have added `package-a` as a dependency using `workspace:*`, and both packages have a "dev" task that watches for changes and rebuilds, then I would like to be able to run both at the same time.

Now obviously I could run both at the same time without `turborepo`. For example using [`mprocs`](https://github.com/pvolok/mprocs) I could simply run something like:

```bash
pnpm mprocs 'pnpm --filter package-a dev' 'pnpm --filter package-b dev'
```

But part of the point of `turborepo` is that it uses the dependency graph so that I don't have to craft that kind of `mprocs` command myself.

I think long-running process should be able to depend on other long-running process.

### To Reproduce

If my description isn't clear enough I could try and make an example

**Comment by anthonyshew** [comment]
This is expected behavior as documented. You can't depend on a long-running task because it won't exit.

Some options for what you may be trying to achieve:
- `turbo watch` allows a task to be dependency-aware. Note that this comes with the caveat that two long-running tasks still won't be able to depend on each other.
- Remove the `dependsOn` relationship between the tasks so that they can run in parallel, as you've mentioned is the behavior you're looking for. You might also add a "sleep 5 && your-command" to delay the startup invocation of the script that needs to wait.

Ultimately, there's no way for Turborepo to associate the runtime behavior of your tasks against each other. That would be a brand new construct that would need a champion, an RFC, and community backing so we know people want it. If you're interested in writing that idea down for the community, you can open a Discussion with the Idea label so we can all chat about it more.

**Comment by TheKnarf** [comment]
> Ultimately, there's no way for Turborepo to associate the runtime behavior of your tasks against each other

There is no reason for why it would need to. If `task b` depends on `task a` and **both** are persistent then just run both of them in parallell at the same time, how is that not the logical way to do it?

Nevertheless I've created [a discussion for it](https://github.com/vercel/turbo/discussions/8487) if thats the correct forum to discuss this.

**Comment by TheKnarf** [comment]
> Can you explain how that's different from what I've described here? What you're describing is the default behavior.

I'll try my best to explain since it seems that we have a bit of a miss-communication.

The point of turborepo is to build up a dependency graph automatically for a monorepo context. If I have a task called `build` with some dependencies and a package called `package-b` that depends on other packages in my monorepo, then when I run a command like `pnpm turbo --filter package-b build` its `turborepo`'s job to figure out which other packages `package-b` depends on and run their build task as well. It does this "automatically" meaning that won't have to manually build up a list of dependencies like I might need to do if I instead was using a `Makefile`. Hopefully we agree that thats the point of `turborepo`, its a smarter alternative to `Makefiles` with some built inn caching options.

With the introduction of "persistent tasks" I would like for `turborepo` to still do its job building up a dependency graph and running all of the task that depends on each other. This however `turborepo` can't currently do, which you claim is by design. That means that `turborepo` servs zero purposes over a `Makefile`, even worse, I'm no forced to create a `Makefile` just for "persistent tasks" where I manually group tasks together that are supposed to run together across the monorepo.

Mind you I was already doing this manually before the introduction of "persistent tasks" to `turborepo`, but I had hoped now that `turborepo` got "persistent tasks" that I would no longer have to do this kind of double bookkeeping where `turborepo` can build a dependency graph only for "non-persistent tasks" but I myself still have to maintain this on the side. 

When I first heard that `turborepo` was getting built inn support for "persistent tasks" I imagined that it would work as following:


|Should _column_ be able to depend on _row_|Persistent task|Normal task|
|--|--|--|
|Persisten task| *Yes*, run both in parallell | No, the persistent task will never finish before the normal task gets to run
|Normal task| Yes, run the normal task first and then the persisten task | Yes, run the normal task first before the other normal task

That way instead of having a `Makefile` where I manually keep a list of "persistent tasks" that need to run together I could simply use `turborepo` as I do for "non-presistent tasks"

**Comment by anthonyshew** [comment]
Tasks that run in parallel are, by definition, not depending on each other. If you want to run them in parallel, you would remove the `dependsOn` relationship.

**Comment by TheKnarf** [comment]
> Tasks that run in parallel are, by definition, not depending on each other. If you want to run them in parallel, you would remove the dependsOn relationship.

I don't agree with you. For example a Frontend app would depend on the api from the Backend app, therefor in a dev setting (persistent task) they would both need to run at the same time.

**Comment by TheKnarf** [comment]
> That's a description of the runtime behavior, rather than the task graphing behavior.

Persistent tasks **are** runtime behavior.

It is my opinion that dependsOn for persistent tasks should work the same way that `depends_on` work in a Docker Compose file.

**Comment by mangobestfruit** [comment]
@TheKnarf I think you can do what you're looking for with the filtering syntax https://turbo.build/repo/docs/reference/run#microsyntaxes-for-filtering

In your example you'd do something like ```turbo run dev --filter=package-b...``` to also run dev on all the dependencies of package-b

**Comment by LinnJS** [comment]
Okay so I landed here for the same reasons as @TheKnarf. I understand the idea if its persistent it will never exit and cant run other task. Okay no problem makes sense its like when you try to chain two watch commands with a bash &&. Like `pnpm run dev && pnpm run generate:watch`. The second one will never be hit.

But the part I am having trouble with is how to configure turbo repo to run a parallel task for both of these task above the are in the same app and I need them to run in parallel but I am not sure how.

Like for example if I wanted all of the below task to run when a dev runs `pnpm turbo dev` how would I make the task always run `pnpm turbo watch generate:watch` and `pnpm turbo watch test:watch` all in the same task?

@anthonyshew I see you mention this workflow is possible but I am having a hard time figuring out how to set this up.

This was my initial reaction for how to solve this problem but it does not work

```
"dev:watch": {
  "parallel": ["generate:watch", "test:watch", "dev"]
}
```

**Comment by anthonyshew** [comment]
@LinnJS, that sounds like `turbo watch generate:watch test:watch`?

**Comment by loganzartman** [comment]
At first I didn't realize, but @mangobestfruit is correct and this works at least for my use-case:

I have a package `web-app`, and some dependencies `lib-a` and `lib-b`. All of these have persistent `dev` tasks that watch and rebuild their outputs. To run the `web-app` dev server, I simply write a package.json script:

```
turbo run dev --filter web-app...
```

The `...` syntax, when placed after `web-app`, says to include its dependencies ([reference](https://turbo.build/repo/docs/reference/run#microsyntaxes-for-filtering)). This means that turbo will start `web-app#dev`, `lib-a#dev`, and `lib-b#dev` in parallel, which is exactly what I want.

It would be interesting if this could be expressed in turbo.json, so that simply running `turbo run dev -F web-app` would do the same, and I think this is what other posters want. For example, if I run `turbo run build -F web-app` where `build` uses `dependsOn: ["^build"]` in turbo.json, it has this behavior (builds dependencies first). Could there be a similar option that would express parallel (and not dependent) builds?

**Comment by chris-dura** [comment]
For other folks landing on this old issue...

>  It would be interesting if this could be expressed in turbo.json, so that simply running turbo run dev -F web-app would do the same, and I think this is what other posters want.
> ...
> Could there be a similar option that would express parallel (and not dependent) builds?

I believe the `with` configuration in `turbo.json` could be a way accomplish this without the need to use the `...` filtering in the actual command.

- https://turborepo.com/docs/reference/configuration#with
