### ISSUE TITLE
v2: Nuxt/Nitro cant pick up environment anymore

### ISSUE THREAD

**Issue by MickL** [vercel/turbo#8503]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### What package manager are you using / does the bug impact?

bun

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.4-canary.4

### Describe the Bug

This is a bit hard to explain and to reproduce but maybe you already have an idea why this could be the case:

Nitro (the server that runs Nuxt) [automatically detects](https://nitro.unjs.io/deploy#zero-config-providers) what provider it is getting deployed to while `nuxt build` is running. It then adds a preset variable which affects how Nitro is built and bundled. Some presets might be `node-server` (default), `bun`, `cloudflare_pages` or `vercel`.

However since Turbo 2.0 this always results in `node-server`.

I even tried to set environment variable manually in Cloudflare `NITRO_PRESET=cloudflare_pages` but STILL it is using `node-server` for some reason.

Downgrading to `1.13.4` and it works again.

Could it be the case that Turbo is removing the environment variable `NITRO_PRESET` for some reason?

**Comment by anthonyshew** [comment]
[Strict Mode](https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables#strict-mode) is now the default so this is expected behavior.

**Comment by MickL** [comment]
I just read this in the documentation. This also means that with v2 of Turbo ALL deployments of Nuxt will fail that are not with the preset `node_server`. E.g. ALL deployments that are on Vercel right now will fail with Turbo v2.

I opened https://github.com/vercel/turbo/issues/8504 to fix this.
