### ISSUE TITLE
Add env wildcards for framework Nitro NITRO_*

### ISSUE THREAD

**Issue by MickL** [vercel/turbo#8504]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

-

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.4-canary.4

### Describe the Bug

[Nitro](https://nitro.unjs.io) is the server framework that [Nuxt](https://nuxt.com) is using. It is part of every Nuxt application but is also an awesome API framework on its own that deploys everywhere (e.g. on Vercel Functions and Vercel Edge Functions).

When using Nitro separate all env variables start with `NITRO_*`. This wildcard should be added to the [Framework Inference](https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables#framework-inference).

This will also fix deployments of Nuxt that deploy to any given preset that is not `node-server` (e.g. `vercel`), see https://github.com/vercel/turbo/issues/8503

### Expected Behavior

-

### To Reproduce

-

**Comment by anthonyshew** [comment]
Works for me! Code is here for you, future me, or anyone else that wants to make this PR: https://github.com/vercel/turbo/blob/131cb0813b2bcee10715609f9f838988719aec47/crates/turborepo-lib/src/framework.rs#L36

**Comment by MickL** [comment]
I will do a PR, also to update the docs.

btw I wonder why is says `NUXT_ENV_*`, it should be `NUXT_*`

**Comment by anthonyshew** [comment]
Is it meant to be `NUXT_*`? I think I'm the only one on the team who has ever used Nuxt and it was a hello-world. 😄 If you want to add that to the PR and provide the documentation that shows that it's supposed to be `NUXT_*`, that would be great!

**Comment by MickL** [comment]
It is `NUXT_*` for server variables and `NUXT_PUBLIC_` for frontend variables. Docs: https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables

Until now nobody noticed but with v2 all env variables are removed so it will start to break. Also I wonder if Nuxt/Nitro detects some providers by environment variables. If yes than this environments are not [zero config](https://nitro.unjs.io/deploy#zero-config-providers) anymore when using Turbo.

**Comment by anthonyshew** [comment]
Happy to support popular frameworks! Just a simple mistake on our part. We don't claim to be perfect.
