### ISSUE TITLE
[VSCode Extension] Version Mismatch

### ISSUE THREAD

**Issue by litewarp** [vercel/turbo#8507]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

N/A

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.04

### Describe the Bug

When I start the VSCode extension, it reports that there is an version mismatch. It looks like the client bundled with the extension has not been updated.

[Relevant discord thread](https://discord.com/channels/818588653005176832/1248835862502838293)

```
[Info  - 8:05:35 PM] root uri: /var/folders/k2/bx96vkx13_g9hgmlc0pgj3600000gn/T/turbod/559b7a291e18e741/turbod.sock
[Error - 8:05:35 PM] Server initialization failed.
  Message: Internal error
  Code: -32603 
[Error - 8:05:35 PM] Turborepo Language Server client: couldn't create connection to server.
  Message: Internal error
  Code: -32603 
[Error - 8:05:35 PM] failed to connect to daemon: unable to make handshake: version mismatch: Some("version mismatch. Client 1.11.0 Server 2.0.0")
```

### Expected Behavior

The VSCode extension should launch the client should connect to the daemon from the turbo 2.04 install.

### To Reproduce

Install turbo > 2.0 and the latest VSCode extension (1.12) and try to start the extension.

**Comment by anthonyshew** [comment]
Hey, thanks for this! A new 2.0 version has been released now.
