### ISSUE TITLE
Turbo saving caches in incorrect location

### ISSUE THREAD

**Issue by HaveSpacesuit** [vercel/turbo#8553]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

​

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

2.0.5-canary.0

### Describe the Bug

Turbo is saving caches in the source code folder instead of on the machine cache location. Turbo used to save cached output (e.g., {6AF0698E-D558-4F6E-9B3C-3716689AF493}.2.ver0x0000000000000021.db) under **C:/Windows/ProgramData/Microsoft/Windows/Caches**. After updating from v1 to v2, it saves in the source code location, e.g., **D:/MyRepo/website/%SystemDrive%/ProgramData/Microsoft/Windows/Caches**. It seems the `%SystemDrive%` variable isn't being escaped in some script.

### Expected Behavior

I do not want cached files in my source code.

### To Reproduce

Install Turbo v2 and run a script with cached output. The files will appear in a location including the literal `%SystemDrive%` in the path.

**Comment by chris-olszewski** [comment]
Can either of you provide a reproduction? Can you also include a Windows build number? I'm unable to reproduce on my Windows machine.

**Comment by IvGaLa** [comment]
> Can either of you provide a reproduction? Can you also include a Windows build number? I'm unable to reproduce on my Windows machine.

Of course, here I provide you with some more information:

**OS:** 
_Windows 10 Pro Edition
Version 22H2
OS Build 19045.4529
Windows Feature Experience Pack 1000.19058.1000.0_


**VSCode:**
_Version: 1.90.2 (user setup)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045_


**npm:**
_v10.8.1_


**turbo:**
_reactjs@1.0.0 S:\Development\ReactJS
└── turbo@2.0.4_

**Comment by chris-olszewski** [comment]
I should have asked this before, but can you try running with `--env-mode=loose` and see if the cache saves to the correct place?

**Comment by IvGaLa** [comment]
> I should have asked this before, but can you try running with `--env-mode=loose` and see if the cache saves to the correct place?

If I run my application with "--env-mode=loose" then it does NOT create the directory "%SystemDrive%\ProgramData\Microsoft\Windows\Caches" inside my project folder.

**Comment by HaveSpacesuit** [comment]
> I should have asked this before, but can you try running with `--env-mode=loose` and see if the cache saves to the correct place?

Same - this is an okay workaround for now.

**Comment by chris-olszewski** [comment]
Could either of you provide a repro app? I want to test https://github.com/vercel/turbo/pull/8615 and make sure that `SystemRoot` is the only env var that needs to be passed through.

An alternative would be if you added `SystemRoot` (or `SYSTEMROOT` if you use CMD prompt) to your [global pass through](https://turbo.build/repo/docs/reference/configuration#globalpassthroughenv) and see if running with `--env-mode=strict` produces the cache folder.

**Comment by HaveSpacesuit** [comment]
> Could either of you provide a repro app? I want to test #8615 and make sure that `SystemRoot` is the only env var that needs to be passed through.
> 
> An alternative would be if you added `SystemRoot` (or `SYSTEMROOT` if you use CMD prompt) to your [global pass through](https://turbo.build/repo/docs/reference/configuration#globalpassthroughenv) and see if running with `--env-mode=strict` produces the cache folder.

I'm afraid I wouldn't know how to go about creating a repro app.

I did add `"globalPassThroughEnv": ["SystemRoot"],` (and also tried with `SYSTEMROOT`) to my turbo.json and ran `turbo start --env-mode=strict`. This did not solve the issue. It still put the cache folder in the wrong location.

However, I tried I also tried `SystemDrive`, and the cache was not written to the source code location!

**Comment by chris-olszewski** [comment]
> I'm afraid I wouldn't know how to go about creating a repro app.

This would probably be just trimming down your project to whatever NPM dependency is saving to `C:/Windows/ProgramData/Microsoft/Windows/Caches`. I could then see what environment variables the package uses to save the cache and add them to the list.


> However, I tried I also tried SystemDrive, and the cache was not written to the source code location!

This is super helpful! Thank you

**Comment by HaveSpacesuit** [comment]
Can confirm that updating to ^2.0.7 fixes this issue for me. Thank you!
