### ISSUE TITLE
Turbo doesn't detect dependencies with PNPM >= 9.0.0

### ISSUE THREAD

**Issue by NikolaRHristov** [vercel/turbo#8572]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

pnpm install ; pnpm run prepublishOnly

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

2.0.5-canary.2

### Describe the Bug

When using `pnpm` >= 9.0.0 the dependencies of a package are not detected.

Example (works correctly):

```json
{
	"packageManager": "pnpm@8.15.8",
}
```

![image](https://github.com/vercel/turbo/assets/90222871/10169010-f7d4-453d-9ec6-e95eb185768d)

`@playform/compress` is dependent on both `@playform/build` and `@playform/pipe`.

When running with:

```json
{
	// or anything above 9.0.0
	"packageManager": "pnpm@9.0.0",
}
```

![image](https://github.com/vercel/turbo/assets/90222871/89c7e1cc-21ca-45c6-89b4-277c2eefa402)

### Expected Behavior

Detect all sub-dependencies correctly.

### To Reproduce

Run `turbo` with `pnpm` >= 9.0.0

**Comment by NikolaRHristov** [comment]
Working `pnpm` `8.15.8`

```sh
digraph {
        compound = "true"
        newrank = "true"
        subgraph "root" {
                "[root] @playform/build#prepublishOnly" -> "[root] ___ROOT___"
                "[root] @playform/compress#prepublishOnly" -> "[root] @playform/build#prepublishOnly"
                "[root] @playform/compress#prepublishOnly" -> "[root] @playform/pipe#prepublishOnly"
                "[root] @playform/pipe#prepublishOnly" -> "[root] @playform/build#prepublishOnly"
        }
}
```

Undetected `pnpm` `9.0.0`

```sh
digraph {
        compound = "true"
        newrank = "true"
        subgraph "root" {
                "[root] @playform/compress#prepublishOnly" -> "[root] ___ROOT___"
        }
}
```

**Comment by NikolaRHristov** [comment]
Could be a duplicate of https://github.com/vercel/turbo/issues/8168

**Comment by tknickman** [comment]
Yep, going to consolidate over there. Thanks @NikolaRHristov.
