### ISSUE TITLE
Turbo produces an `undefined` folder

### ISSUE THREAD

**Issue by NikolaRHristov** [vercel/turbo#8573]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

turbo run prepublishOnly

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

2.0.5-canary.2

### Describe the Bug

When running `turbo run prepublishOnly` inside a package a folder is produced containing:

![image](https://github.com/vercel/turbo/assets/90222871/b4db991f-646d-4dbe-9b85-15494059984a)

```sh
cat DzCzBDeveloperzBApplicationzBPlayFormzBNPMzBBuild.MAP
```

```json
{"D:\\Developer\\node_modules\\typescript\\lib\\typescript.js":["b374e05d441f3afb568ce53e5859d9efa3b300f1",0,2408008]}
```

The `.BLOB` file is unreadable.

This is `typescript` version `5.5.2`

### Expected Behavior

To not have this folder produced.

### To Reproduce

Run `turbo run prepublishOnly` inside https://github.com/PlayForm/Compress or https://github.com/PlayForm/Build

**Comment by chris-olszewski** [comment]
Can you provide a full reproduction with you attempting to use `turbo` with those listed repositories? Neither of them have `packageManager` listed which is required for `turbo@2`.

Could you also try `turbo run prepublishOnly --env-mode=loose` and see if that also produces the same output?

**Comment by NikolaRHristov** [comment]
To the first, they're ran in https://github.com/NikolaRHristov/DeveloperYarn

To the second I'll try again later today with env loose.

**Comment by NikolaRHristov** [comment]
`turbo run prepublishOnly --filter=@playform/build --env-mode=loose` did fix it.
