### ISSUE TITLE
Docs: formatting errors inside `code` blocks in configuring turbo.json page

### ISSUE THREAD

**Issue by kettei-sproutty** [vercel/turbo#8582]
### What is the improvement or update you wish to see?

Hello,
trying to copy a code block from [Configuring turbo.json](https://turbo.build/repo/docs/reference/configuration) almost always require to edit the copied text, for example:

- Almost all code blocks contains `trailing commas` on last values
- Some commas are missing

Example:
```json
{
  "$schema": "https://turbo.build/schema.json" // missing comma
  "tasks": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**", ".next/**", "!.next/cache/**"], // trailing
    },
    "test": {
      "outputs": ["coverage/**"],
      "dependsOn": ["build"],  // trailing
    },
    "dev": {
      "cache": false,
      "persistent": true,  // trailing
    },  // trailing
  },  // trailing
}
```

If it is an issue and not expected and this is not duplicate (I checked but i didn't find anything specific) I would like to take care of this.

Let me know :)

### Is there any context that might help us understand?

I think docs `code` blocks should use a more standard approach (json commas instead of jsonc).

### Does the docs page already exist? Please link to it.

https://turbo.build/repo/docs/reference/configuration#tasks

**Comment by tknickman** [comment]
Hey @kettei-sproutty, PRs to improve this would be greatly appreciated! 🙏🏼
