### ISSUE TITLE
No context detected when the context is defined in an app and the library that use it is in a package

### ISSUE THREAD

**Issue by osvaldo-cv** [vercel/turbo#8635]
I have a `/hooks` package where I use React Query. I have the React Query Providers in the apps, but They are not working. Please check the error here:

![Screenshot 2024-06-20 at 7 58 17 PM](https://github.com/vercel/turbo/assets/20977158/c08a7b6f-0c16-453d-8110-db835a976939)

The React Query Providers are defined as expected in the root of the projects. I have a nextjs app where I import a function from a package that uses react query.

What is the right way to make this working?

I have the same problem with all the libraries requiring context wrapping.

**Comment by osvald0** [comment]
Any comment?

**Comment by ForsakenHarmony** [comment]
Please open an issue on the next.js repo
https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&projects=&template=1.bug_report.yml
