### ISSUE TITLE
New UI is not working (version 2.0.6)

### ISSUE THREAD

**Issue by satelllte** [vercel/turbo#8636]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

npx create-turbo@latest

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.6

### Describe the Bug

New UI doesn't work with the upgrade to latest (v2.0.6)

### Expected Behavior

New UI works

### To Reproduce

Create new repo with `npx create-turbo@latest`, run it and see the new UI isn't there

---

<img width="646" alt="turbo_2 0 6" src="https://github.com/vercel/turbo/assets/20585619/363a0b86-9e59-490e-ae44-ed2945975d84">

### Additional context

Same for `2.0.6-canary.0`

**Comment by anthonyshew** [comment]
We are temporarily disabling it as the default while we work on #8372. 

To turn it back on, use the `ui` configuration in `turbo.json`: https://turbo.build/repo/docs/reference/configuration#ui
