### ISSUE TITLE
Turbo prune with multiple scopes

### ISSUE THREAD

**Issue by baptisteArno** [vercel/turbo#864]
### Describe the feature you'd like to request

I'd like to be able to use multiple scopes with the `prune` CLI command.

### Describe the solution you'd like

`turbo prune --scope=app1 --scope=app2`

We can already do this with the run command.

### Describe alternatives you've considered

-

**Comment by CJEnright** [comment]
I'm looking into this in https://github.com/vercel/turbo/discussions/2503

My use case is that we build all of our server side apps into a single image for simplicity. At run time we choose what app runs via environment variables.

**Comment by CJEnright** [comment]
Closed by #2551

Once that gets released you should be able to specify multiple scopes:
```
turbo prune --scope=app1 --scope=app2
```
