### ISSUE TITLE
v2 doesn't allow omitting scope when filtering by package (i.e., when using `--filter`)

### ISSUE THREAD

**Issue by migueloller** [vercel/turbo#8652]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/migueloller/turborepo-package-scope-repro

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.6

### Describe the Bug

Before Turborepo v2, the `--filter` flag supported omitting the package scope, similar to pnpm's [filter](https://pnpm.io/filtering#--filter-package_name). But now in v2, the scope must be specified.

### Expected Behavior

I expect to be able to run `pnpm turbo -F app-a build` and for it to succeed. Instead, I must run `pnpm turbo -F @scope/app-a build`.

### To Reproduce

Clone the provided repro repo and run `pnpm turbo -F app-a build`.

This will result in the following error:

```bash
  × No package found with name 'app-a' in workspace
```

### Additional context

I tested by reproduction in `1.13.4` and the issue wasn't present. To do this, run `pnpm upgrade turbo@1 -w` and then rerun the repro steps.

**Comment by anthonyshew** [comment]
Hey, Miguel! This was included in the correctness breaking changes (third from the bottom): https://turbo.build/blog/turbo-2-0#correctness

I answered more of the "why" here: https://github.com/vercel/turbo/discussions/8524#discussioncomment-9811128

**Comment by migueloller** [comment]
I appreciate the prompt response! Thanks @anthonyshew
