### ISSUE TITLE
npx create-turbo@latest installs beta/release candidate version of the dependencies

### ISSUE THREAD

**Issue by Aloneduckling** [vercel/turbo#8680]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/Aloneduckling/turborepo-issue

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

2.0.6-canary.0

### Describe the Bug

`npx create-turbo@latest` installs beta/release candidate version of dependencies. Below is the package.json for `apps/docs` next app

![image](https://github.com/vercel/turbo/assets/54030684/f47b2a27-9ada-4fef-a699-0015cb7815fd)

### Expected Behavior

The version of the installed dependencies should be stable and not the beta/RC ones. 

### To Reproduce

1. `npx create-turbo@latest`
2. Check the dependencies installed in `apps/docs`

**Comment by anthonyshew** [comment]
Thanks for the issue! This is intended since these Next.js dependencies will be stable in the coming weeks.

If you prefer, you can downgrade them. 👍
