### ISSUE TITLE
Issue with Path Aliases and ESLint in Turborepo with TypeScript

### ISSUE THREAD

**Issue by wojtekKrol** [vercel/turbo#8711]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/paxcode-it/zodify-forms/tree/dev

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.6

### Describe the Bug

I'm experiencing an issue with path aliases in a Turborepo monorepo setup when using TypeScript. The issue is with ESLint and my IDE not resolving the path aliases correctly, even though the code itself compiles and runs without any problems. This issue affects my development experience as it causes false positives in my IDE and ESLint errors.

### **Root Directory Setup**

I have a root `tsconfig.json` with the following configuration:

```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "skipLibCheck": true,
    "target": "es2022",
    "allowJs": true,
    "resolveJsonModule": true,
    "moduleDetection": "force",
    "isolatedModules": true,
    "verbatimModuleSyntax": false,
    "module": "ESNext",
    "strict": true,
    "noImplicitOverride": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "declaration": true,
    "incremental": false
  },
  "lib": ["es2022", "dom"]
}
```

### **Package Directory Setup**

In the root directory, I have a structure as follows:
```
packages/
  └── PACKAGE/
      ├── src/
      │   └── **/*.ts
      └── tsconfig.json
```

The `tsconfig.json` inside each package looks like this:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["jest.config.ts", "src/**/*.ts", "__tests__/**/*.ts"],
  "exclude": ["node_modules", "lib", "coverage"]
}
```

### **The Issue**

When I import modules using the path alias in my package, such as:

```typescript
import { FieldValueToOptions, MappedFieldOptions } from '@/types/UtilityTypes';
```

ESLint and my IDE show the following error:

```
ESLint: Unable to resolve path to module '@/types/UtilityTypes'.(import/no-unresolved)
```

However, the code works correctly, and I can navigate to the module definition using my IDE (cmd+click).

### **Potential Workaround**

I haven't found a reliable workaround yet. Any suggestions or fixes would be greatly appreciated.

Thank you for looking into this issue!

### Expected Behavior

ESLint and the IDE should resolve the path alias correctly and not show any errors.

### **Actual Behavior**

ESLint and the IDE show an error indicating that the module cannot be resolved, even though the code compiles and runs correctly.

### To Reproduce

1. git clone the repo
2. pnpm install
3. git reset --soft HEAD~1 
4. git add .
5. git commit -m '' 
6. lint-staged will run and throw error about alias paths

### Additional context

- This issue only affects the linter/IDE and not the actual code execution.
- A second package with the same structure and configuration does not affect the issue.

**Comment by wojtekKrol** [comment]
Resolved with this comment: https://github.com/import-js/eslint-plugin-import/issues/2301#issuecomment-974473228

**Comment by dimitropoulos** [comment]
great timing! we had just cloned this and were _just_ looking at this and were about to suggest this fix!

**Comment by wojtekKrol** [comment]
Thank you for such a fast response! :)
