### ISSUE TITLE
Error message on package.json : specify which repo workspace

### ISSUE THREAD

**Issue by MarArMar** [vercel/turbo#8744]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

no

### What package manager are you using / does the bug impact?

npm & bun

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

1.31.4

### Describe the Bug

```sh
turbo run dev --filter=svelteproject
  × unable to parse workspace package.json: unable to parse package.json: trailing comma at line 20 column 3
  ├─▶ unable to parse package.json: trailing comma at line 20 column 3
  ╰─▶ trailing comma at line 20 column 3

error: "turbo" exited with code 1
```

Turbo should specify which package.json it is talking about instead of leaving the user guessing

This was in one of the workspace dependency and I had to search each one to find it

### Expected Behavior

unable to parse workspace "WorkspaceName" package.json

### To Reproduce

```sh
turbo run dev
```

With a package.json with an extra comma at the end of a list for example :
```
{
  "name": "@repo/styles",
  "version": "1.0.0",
  "license": "UNLICENSED",
  "files": [
    "styles.css",
  ]
}
```

**Comment by NicholasLYang** [comment]
Hi @MarArMar, thanks for the issue, this is great feedback. I'm adding a more clear error message in #8753. I'll let you know when it's out.

**Comment by NicholasLYang** [comment]
Done! It should be out in the next patch. We probably won't be back porting it to 1.0 though, so I'd recommend upgrading to Turbo 2.0
