### ISSUE TITLE
Getting `ERR_UNSUPPORTED_ESM_URL_SCHEME` error when trying to build with turbo repo on Windows (GH actions)

### ISSUE THREAD

**Issue by bracesproul** [vercel/turbo#8798]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/langchain-ai/langgraphjs/pull/271/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR77-R114

### What package manager are you using / does the bug impact?

Yarn v2/v3/v4 (node_modules linker only)

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

2.0.7-canary.1

### Describe the Bug

When running our unit tests in CI, turbo repo fails to build the project in windows enviroments running node version `18.x` and `20.x`. Turbo repo has no issues building in a macos environment. The exact error is as follows:
```bash
@langchain/langgraph:build
cache miss, executing 3d314cffd1d1c[19](https://github.com/langchain-ai/langgraphjs/actions/runs/10014949280/job/27685592355?pr=271#step:7:20)1
• Packages in scope: @langchain/langgraph
• Running build:internal in 1 packages
• Remote caching disabled
@langchain/langgraph:build:internal: cache miss, executing 741cb7b8ad633719
@langchain/langgraph:build:internal: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
@langchain/langgraph:build:internal:     at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:239:11)
@langchain/langgraph:build:internal:     at defaultLoad (node:internal/modules/esm/load:130:3)
@langchain/langgraph:build:internal:     at ModuleLoader.load (node:internal/modules/esm/loader:396:13)
@langchain/langgraph:build:internal:     at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:278:56)
@langchain/langgraph:build:internal:     at new ModuleJob (node:internal/modules/esm/module_job:67:26)
@langchain/langgraph:build:internal:     at #createModuleJob (node:internal/modules/esm/loader:290:17)
@langchain/langgraph:build:internal:     at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:247:34)
@langchain/langgraph:build:internal:     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:[22](https://github.com/langchain-ai/langgraphjs/actions/runs/10014949280/job/27685592355?pr=271#step:7:23)8:17)
@langchain/langgraph:build:internal:     at async ModuleLoader.import (node:internal/modules/esm/loader:315:[23](https://github.com/langchain-ai/langgraphjs/actions/runs/10014949280/job/27685592355?pr=271#step:7:24)) {
@langchain/langgraph:build:internal:   code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
Error: @langchain/langgraph#build: command (D:\a\langgraphjs\langgraphjs\langgraph) C:\Users\RUNNER~1\AppData\Local\Temp\xfs-d08a57cc\yarn.cmd run build exited (1)
@langchain/langgraph:build:internal: }
@langchain/langgraph:build:internal: ERROR: command finished with error: command (D:\a\langgraphjs\langgraphjs\langgraph) C:\Windows\temp\xfs-165a7ab4\yarn.cmd run build:internal exited (1)
@langchain/langgraph#build:internal: command (D:\a\langgraphjs\langgraphjs\langgraph) C:\Windows\temp\xfs-165a7ab4\yarn.cmd run build:internal exited (1)
 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    3.334s 
Failed:    @langchain/langgraph#build:internal
 ERROR  run failed: command  exited (1)
Error:  command finished with error: command (D:\a\langgraphjs\langgraphjs\langgraph) C:\Users\RUNNER~1\AppData\Local\Temp\xfs-d08a57cc\yarn.cmd run build exited (1)
 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    5.373s 
Failed:    @langchain/langgraph#build
 ERROR  run failed: command  exited (1)
Error: Process completed with exit code 1.
```

It appears to be something related to how Github actions manages paths when running in windows.

### Expected Behavior

The project successfully builds

### To Reproduce

Fork the `https://github.com/langchain-ai/langgraphjs` repo, checkout the `brace/upgrade-build` branch, push to your own repository and run the CI github action file. Or, view the failures [here](https://github.com/langchain-ai/langgraphjs/actions/runs/10014949280?pr=271).

**Comment by chris-olszewski** [comment]
Can you confirm that running `yarn run build` in the directory of `@langchain/langgraph` on Windows works successfully? If that works can you try adding `--env-mode=loose` to your `turbo` command?

**Comment by bracesproul** [comment]
Both failed with the same errors. See
- [yarn run build:internal in the directory of @langchain/langgraph commit](https://github.com/langchain-ai/langgraphjs/pull/271/commits/5737596ff17b33ddb9e6f6aee8ae1a67ca35035c)
- [--env-mode=loose to your turbo command commit](https://github.com/langchain-ai/langgraphjs/pull/271/commits/ac630091312f4d5a257c4441374eff3b08383fc1)

**Comment by bracesproul** [comment]
Both failed with the same errors. See
- [yarn run build:internal in the directory of @langchain/langgraph commit](https://github.com/langchain-ai/langgraphjs/pull/271/commits/5737596ff17b33ddb9e6f6aee8ae1a67ca35035c)
- [--env-mode=loose to your turbo command commit](https://github.com/langchain-ai/langgraphjs/pull/271/commits/ac630091312f4d5a257c4441374eff3b08383fc1)

@chris-olszewski

**Comment by chris-olszewski** [comment]
If this happens without `turbo` being invoked, then this doesn't seem like a `turbo` issue, but instead something with the underlying tool.

Closing as there isn't any action we can take, but if something comes to light where this does seem to be an issue with `turbo` invoking the underlying script, then please reopen.
