### ISSUE TITLE
TMP and TEMP env variables are not passed through

### ISSUE THREAD

**Issue by cahilfoley** [vercel/turbo#8802]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/cahilfoley/turborepo-temp-bug

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.9 (because canary is currently at 2.0.7)

### Describe the Bug

The TMP and TEMP environment variables are not available in child NPM scripts being run by `turbo run` or `turbo watch`

### Expected Behavior

The TMP and TEMP environment variables should be available in app and package code.

### To Reproduce

Try to access the TMP or TEMP environment variables in any app or package script run through turbo in `turbo@^2`. In the reproduction simply run `turbo run example` and compare the outputs to your local `TMP` and `TEMP` env variables. This also breaks the node `os.tmpdir()` function.

**Comment by chris-olszewski** [comment]
Thanks for the PR!
