### ISSUE TITLE
Docs: Improve UX - Prevent empty folders from opening and closing

### ISSUE THREAD

**Issue by guesung** [vercel/turbo#8817]
### What is the improvement or update you wish to see?

In the "Transit Nodes" section of the documentation, clicking an empty folder (e.g., 'core' package) causes it to open and immediately close.

Suggestion: Disable the open/close action for empty folders.

Rationale:
- Reduces user confusion
- Provides more intuitive behavior
- Improves focus on document content

I wanted to fix this directly but couldn't find the repository. Hence, I'm raising this issue for consideration.

### Is there any context that might help us understand?

https://github.com/user-attachments/assets/b339a6d2-a29b-4c7d-8b5e-1ad9bd6ebc7c

### Does the docs page already exist? Please link to it.

https://turbo.build/repo/docs/core-concepts/package-and-task-graph#task-graph

**Comment by anthonyshew** [comment]
Looks like I saw #8859 first! Fix is rolling out. Thank you!
