### ISSUE TITLE
Unable to Import External Dependencies in Internal Package Components

### ISSUE THREAD

**Issue by severindemchuk** [vercel/turbo#8829]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/severindemchuk/turborepo-swiper-example

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

turbo@2.0.10-canary.0

### Describe the Bug

I'm encountering an issue in my turborepo setup where I'm unable to import external dependencies inside internal package components. Below are the steps I've taken and the error message I'm receiving:

1. Created a component within one of my internal packages.
2. Installed `swiper` as an external dependency.
3. Attempted to use `swiper` in my component.

I've also tried this with another dependency `react-modern-drawer` which produces the same issue.

```
The current file is a CommonJS module whose imports will produce 
 calls; however, the referenced file is an ECMAScript module and cannot be imported with 
 . Consider writing a dynamic 
 call instead.
   

To convert this file to an ECMAScript module, add the field `"type": "module"` to /Users/**/Documents/Repositories/turborepo-v2/packages/ui/package.json .
``` 
<img width="1736" alt="image" src="https://github.com/user-attachments/assets/843256da-2eca-4e97-9b14-41c13f2c05cd">

When I try to build i get following error:
```
│    Collecting page data  ..TypeError: (0 , p.createContext) is not a function
│     at 3527 (/Users/severin.demchuk/Documents/Repositories/turborepo-v2/apps/web/.next/server/app/page.js:1:85752)
│     at t (/Users/severin.demchuk/Documents/Repositories/turborepo-v2/apps/web/.next/server/webpack-runtime.js:1:127)
│     at 8019 (/Users/severin.demchuk/Documents/Repositories/turborepo-v2/apps/web/.next/server/app/page.js:1:773)
│     at t (/Users/severin.demchuk/Documents/Repositories/turborepo-v2/apps/web/.next/server/webpack-runtime.js:1:127)
│     at r (/Users/severin.demchuk/Documents/Repositories/turborepo-v2/apps/web/.next/server/app/page.js:6:35796)
│     at /Users/severin.demchuk/Documents/Repositories/turborepo-v2/apps/web/.next/server/app/page.js:6:35827
│     at t.X (/Users/severin.demchuk/Documents/Repositories/turborepo-v2/apps/web/.next/server/webpack-runtime.js:1:1191)
│     at /Users/severin.demchuk/Documents/Repositories/turborepo-v2/apps/web/.next/server/app/page.js:6:35809
│     at Object.<anonymous> (/Users/severin.demchuk/Documents/Repositories/turborepo-v2/apps/web/.next/server/app/page.js:6:35854)
│     at Module._compile (node:internal/modules/cjs/loader:1256:14)
``` 

Adding  `"type": "module"` to the `package.json` as suggested by the error doesn't resolve the issue. 

**Package.json**
```javascript
{
  "name": "@repo/ui",
  "version": "0.0.0",
  "private": true,
  "exports": {
    "./button": "./src/button.tsx",
    "./card": "./src/card.tsx",
    "./code": "./src/code.tsx",
    "./slider": "./src/slider.tsx"
  },
  "scripts": {
    "lint": "eslint . --max-warnings 0",
    "generate:component": "turbo gen react-component"
  },
  "devDependencies": {
    "@repo/eslint-config": "*",
    "@repo/typescript-config": "*",
    "@turbo/gen": "^1.12.4",
    "@types/eslint": "^8.56.5",
    "@types/node": "^20.11.24",
    "@types/react": "^18.2.61",
    "@types/react-dom": "^18.2.19",
    "eslint": "^8.57.0",
    "typescript": "^5.3.3"
  },
  "dependencies": {
    "react": "^18.2.0",
    "swiper": "^11.1.7"
  }
}

``` 

Everything else is the boilerplate code from `npx create-turbo@latest`.

**How i managed to make it work**
When i change tsconfig the of the ui package through the react-library.json to `"module": "ESNext"` and `"moduleResolution": "Bundler"` it appears to work and i don't receive the error anymore. But still I'm unsure if this is the correct way to go about this. 

### Expected Behavior

I would expect to be able to import any external dependency the same way it would be on a NextJs or React App. 

### To Reproduce

1. Create a new Turborepo Project `npx create-turbo@latest`
2. Install a external dependency `npm i swiper` to a internal package e.g `packages/ui`
3. Create a new component or use an existing one and import the external dependecy

**Comment by chris-olszewski** [comment]
Just clarifying: Is the ask here for the example to be updated?

**Comment by chris-olszewski** [comment]
This sounds like a bundler issue with your specific use of the external dependency. If you think this is a `turbo` issue can you verify that the command you are running succeeds without the use of `turbo`? e.g. If `web#build` fails then run `cd apps/web && npm run build`.

I tried to follow your reproduction steps, but wasn't able to hit the errors you reported. If you do think this is a `turbo` issue, then providing a reproduction repository helps a great deal.

**Comment by severindemchuk** [comment]
Hi @chris-olszewski 

You can use this repository for reproduction: [https://github.com/severindemchuk/turborepo-swiper-example
](https://github.com/severindemchuk/turborepo-swiper-example)

The Repo doesn't include any changes to the typescript config like i described in the issue. I managed to find out that i made an issue myself and that I needed to add `'use client'` statement to my newly added component. The build now runs successfully. ✅  

But the issue isn't really resolved regarding the module Resolution of external dependencies. When i run `tsx tsc --noEmit` in the `packages/ui` directory i still get following errors: 

```
npx tsc --noEmit      
src/slider.tsx:3:37 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("swiper/react")' call instead.
  To convert this file to an ECMAScript module, add the field `"type": "module"` to '/Users/severindemchuk/Documents/Repositories/turborepo-swiper-example/packages/ui/package.json'.

3 import { Swiper, SwiperSlide } from 'swiper/react';
                                      ~~~~~~~~~~~~~~


Found 1 error in src/slider.tsx:3
``` 

Now adding ```"module": "ESNext", "moduleResolution": "Bundler"``` to the `packages/ui/tsconfig.json` and again running `tsx tsc --noEmit` i don't get any errors. 

The question here is two-fold:

1. If I want to use external dependencies in `packages/ui` (e.g., swiper or others), is it correct to change the tsconfig by adding `"module": "ESNext", "moduleResolution": "Bundler"` to the `tsconfig.json`? Or is there another way to do this? TypeScript configs are not necessarily my strong suit, so I just want to make sure I use it as intended. It seems a pretty common use case to use some external dependencies in the UI package, which made me think I might be using this in a way it was not intended. This leads to the second question:
2.  If this is the right way to configure the tsconfig, would it make sense to adjust the generated example so that it works out of the box without having to change the tsconfig (as you mentioned in your first comment)?

Your help is greatly appreciated!

**Comment by anthonyshew** [comment]
We aren't the experts on TypeScript configuration. You may find better help in a TypeScript community. But it does look like you've found your way to your solution!

If you would like to update the example, feel free to do so!
