### ISSUE TITLE
Unable to read config: failed to parse turbo json

### ISSUE THREAD

**Issue by SeyTo** [vercel/turbo#8834]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/SeyTo/jsonparseturbo.git

### What package manager are you using / does the bug impact?

Yarn v1, Yarn v2/v3/v4 (node_modules linker only)

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

v1.22.22

### Describe the Bug

Running `npx turbo prune filter=web` keeps producing
```
× Unable to read config: failed to parse turbo json
  ╰─▶ failed to parse turbo json
```
even on a vanilla created project. I had to eventually revert to older version to avoid this issue.
The files structure is 
```
drwxrwxr-x   7 rj rj   4096 Jul 25 06:46 ./
drwxrwxr-x   apps/  -> web, api
drwxr-xr-x  .git/
-rw-r--r--    .gitignore
drwxr-xr-x  node_modules/
-rw-r--r--  .npmrc
-rw-r--r--  package.json
drwxrwxr-x  packages/
-rw-r--r--  README.md
drwxr-xr-x 19:09 .turbo/
-rw-r--r--  turbo.json
-rw-r--r--  yarn.lock
```
and `turbo.json` is 
```json
{
  "$schema": "https://turbo.build/schema.json",
  "ui": "tui",
  "globalDotEnv": [
    ".env"
  ],
  "tasks": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["$TURBO_DEFAULT$", ".env*"],
      "outputs": [".next/**", "!.next/cache/**"]
    },
    "lint": {
      "dependsOn": ["^lint"]
    },
    "dev": {
      "cache": false,
      "persistent": true
    }
  }
}
```

### Expected Behavior

`turbo prune` to prune without issue.

### To Reproduce

Run `turbo prune web`

### Additional context

Issue only occuring on versions above `2.0.1`.

**Comment by SeyTo** [comment]
This issue is only occuring in my machine. Will open again with solution if I find one.

**Comment by chris-olszewski** [comment]
This sounds like you might be using incorrect versions of `turbo` for the `turbo.json`. 

Can you add calls of: `npx turbo --version` or `turbo --version` (depending on how you're invoking `turbo`) right before the failing command and verify you're using the version of `turbo` that you expect?

**Comment by SeyTo** [comment]
`npx turbo --version` is `1.11.3` and `turbo --version` is `2.0.9`. For docker using the `latest` will give that error but not when using `1.11.3`. But when I run it locally on my machine while updating the version to `2.0.9` there seems to be no issue. Anyway, I can't seem to triage this issue and no one else seems to be having this issue. I will close it in few days.

**Comment by chris-olszewski** [comment]
You could try setting [`TURBO_DOWNLOAD_LOCAL_ENABLED=1`](https://turbo.build/repo/docs/reference/system-environment-variables) which will inspect your lockfile and use the version of `turbo` specified there.

Could you provide a reproduction of the vanilla project you're running into issues with and the commands you're running?
