### ISSUE TITLE
Docs: Directory animation bug when content inside the folder is empty

### ISSUE THREAD

**Issue by extramix** [vercel/turbo#8859]
### What is the improvement or update you wish to see?

When attempting to toggle an empty folder, it momentarily tries to expand without any content and then quickly reverts to its previous state. (please refer to the video reference below)

https://github.com/user-attachments/assets/aaa34c19-d9db-48d9-be91-452ab47befc6

### Is there any context that might help us understand?

1) Go to Creating an Internal Package page
2) In the [1) Create an empty directory](https://turbo.build/repo/docs/crafting-your-repository/creating-an-internal-package#create-an-empty-directory) section, try toggling `math` folder a few times.

## Observations
- This issue does not occur when toggling other inactive empty folders such as `app`
- The bug specifically occurs when the folder is both empty and active (highlighted in green.)

### Does the docs page already exist? Please link to it.

https://turbo.build/repo/docs/crafting-your-repository/creating-an-internal-package

**Comment by anthonyshew** [comment]
I've reported this upstream! https://github.com/fuma-nama/fumadocs/issues/646

**Comment by extramix** [comment]
Thank you so much, Anthony!

**Comment by anthonyshew** [comment]
Deploying fix now! Thanks for letting us know. 👍
