### ISSUE TITLE
`filter` does not seem to work on Linux.

### ISSUE THREAD

**Issue by long-woo** [vercel/turbo#8876]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

-

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

2.0.9

### Describe the Bug

The local machine is Mac, CI/CD uses Linux. The same command has different `--filter=@scope/*[HEAD^1]` results:

### Mac

<img width="847" alt="image" src="https://github.com/user-attachments/assets/8204b865-40bc-40ea-968c-14d7f4c4dda2">

### Linux

<img width="1139" alt="image" src="https://github.com/user-attachments/assets/4a123dbe-69a6-4b5a-bfcb-ce55189ae45e">
``

### Expected Behavior

The results are consistent with Mac.

### To Reproduce

The most recent git record is invalid.

**Comment by chris-olszewski** [comment]
Can you try adding enclosing quotes around your filters e.g. `--filter="@scope/*[HEAD^1]"`? Many shells expand `*` as a wild card and this happens before `turbo` receives the command line arguments.

If this doesn't work could you:
 - Provide the raw text of the command you're running. It's hard to tell exactly what the command is from your screenshots
 - What shell is being used in each environment

**Comment by long-woo** [comment]
Thank you for your reply. I roughly know the cause of the problem. It is estimated that the `pnpm-lock.yaml` file has changed due to the execution of `pnpm i` on the deployment server.
