### ISSUE TITLE
Turborepo on Vercel template is failing to be deployed

### ISSUE THREAD

**Issue by Saad1379** [vercel/turbo#8898]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://vercel.com/templates/next.js/monorepo-turborepo

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

15.0.0-canary.95

### Describe the Bug

While deploying I ran into error during build process
``Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.``

![image](https://github.com/user-attachments/assets/bb7b1dad-90a6-48e3-a440-ddc98d362a6f)

### Expected Behavior

Successfully create a turborepo monorepo adn deploy it on vercel

### To Reproduce

1. Go to https://vercel.com/templates/next.js/monorepo-turborepo
2. Click on "Deploy"
3. Wait for the build process to finish

**Comment by anthonyshew** [comment]
I'll fix the template! This is happening because the Root Directory is missing. You can fix this in your Project Settings by setting the Root Directory to `apps/docs` or `apps/web`
