### ISSUE TITLE
2.0.10+ doesn't keep the dev command open

### ISSUE THREAD

**Issue by hrishikesh-k** [vercel/turbo#8915]
### Verify canary release

- [x] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/hrishikesh-k/blog

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

[2.0.12-canary.0](https://github.com/vercel/turbo/releases/tag/v2.0.12-canary.0)

### Describe the Bug

Running `npm run dev` starts my dev server but also immediately shuts it down. Here's the output from the terminal:

```
npm run dev

> dev
> turbo run @hrishikeshk/site#dev --no-cache

turbo 2.0.10

• Packages in scope: //, @hrishikeshk/adapter, @hrishikeshk/cache, @hrishikeshk/site, @hrishikeshk/utils
• Running @hrishikeshk/site#dev in 5 packages
• Remote caching disabled
@hrishikeshk/utils:build: cache miss, executing a1971776d99e9ef9
@hrishikeshk/utils:build:
@hrishikeshk/utils:build: 
@hrishikeshk/utils:build: > @hrishikeshk/utils@0.0.1 build
@hrishikeshk/utils:build: > tsc
@hrishikeshk/utils:build:

@hrishikeshk/adapter:build: cache miss, executing b1d849e4ddb8df85
@hrishikeshk/adapter:build:
@hrishikeshk/adapter:build: 
@hrishikeshk/adapter:build: > @hrishikeshk/adapter@0.0.1 build
@hrishikeshk/adapter:build: > tsc
@hrishikeshk/adapter:build:

@hrishikeshk/site:dev: cache miss, executing 9a82d2de968055b7
@hrishikeshk/site:dev:
@hrishikeshk/site:dev: 
@hrishikeshk/site:dev: > @hrishikeshk/site@0.0.1 dev
@hrishikeshk/site:dev: > vite dev
@hrishikeshk/site:dev:

@hrishikeshk/site:dev:   VITE v5.3.5  ready in 1273 ms
@hrishikeshk/site:dev:
@hrishikeshk/site:dev:   ➜  Local:   http://localhost:5173/
@hrishikeshk/site:dev:   ➜  Network: use --host to expose
@hrishikeshk/site:dev:   ➜  press h + enter to show help


 Tasks:    3 successful, 3 total
Cached:    0 cached, 3 total
  Time:    5.192s
```

### Expected Behavior

The dev server should remain on.

### To Reproduce

Run `npm i` (after changing the `turbo` version to anything after `2.0.9` in the root `package.json`) and `npm run dev` in the reproduction repo.

### Additional context

Worked fine till 2.0.9. Broke in 2.0.10 and still broken in 2.0.11.

**Comment by chris-olszewski** [comment]
Your [`dev` task](https://github.com/hrishikesh-k/blog/blob/main/turbo.json#L52) needs to be declared as [persistent](https://turbo.build/repo/docs/reference/configuration#persistent).

Please reopen if this doesn't resolve your issue.

**Comment by chaikovskyiVlad** [comment]
This issue is still present in version 2.4.4
I'm using Mac on M1
Node: `22.14.0`
Pnpm: `9.15.9`
My `turbo.json` file 

{
  "$schema": "https://turborepo.org/schema.json",
  "globalDependencies": ["**/.env.*local"],
  "tasks": {
    "@purple/hooks#build": {
      "dependsOn": ["@purple/permissions#build"]
    },
    "@purple/hooks#dev": {
      "dependsOn": ["@purple/permissions#build"]
    },
    "@purple/ui#dev": {
      "dependsOn": ["@purple/eslint-config#build", "@purple/icons#build", "@purple/permissions#build", "@purple/hooks#build"]
    },
    "@purple/sense#dev": {
      "dependsOn": ["@purple/eslint-config#build", "@purple/icons#build", "@purple/permissions#build", "@purple/vite-configs#build", "@purple/hooks#build", "@purple/ui#build"]
    },
    "@purple/admin#dev": {
      "dependsOn": ["@purple/eslint-config#build", "@purple/icons#build", "@purple/permissions#build", "@purple/vite-configs#build", "@purple/hooks#build", "@purple/ui#build"]
    },
    "@purple/providers#dev": {
      "dependsOn": ["@purple/eslint-config#build", "@purple/icons#build", "@purple/permissions#build", "@purple/vite-configs#build", "@purple/hooks#build", "@purple/ui#build"]
    },
    "build": {
      "env": ["SENTRY_AUTH_TOKEN"],
      "dependsOn": ["^build"],
      "outputs": ["dist/**"]
    },
    "dev": {
    "dependsOn": ["^build"],
    "env": [
      ".env.development.local",
      ".env.development",
      ".env.local",
      ".env"
    ],
    "cache": false,
    "persistent": true
  },
    "test": {},
    "clean": {
      "dependsOn": ["^clean"],
      "cache": false
    },
    "lint:code": {},
    "lint:styles": {},
    "lint:fix": {},
    "lint": {},
    "check-types": {}
  }
}
