### ISSUE TITLE
Downgrade issue - bun/yarn

### ISSUE THREAD

**Issue by shuther** [vercel/turbo#8935]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

see below

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.11

### Describe the Bug

I am using bun as a package manager, package.json contains:
`  "packageManager": "bun@v1.1.10"`

The build process is reporting an error (see below) - the regex is fine so there is another issue somewhere between bun and turbo.
```
invalid_package_manager_field

  × could not parse the packageManager field in package.json, expected to match regular expression (?P<manager>bun|npm|pnpm|yarn)@(?
  │ P<version>\d+\.\d+\.\d+(-.+)?)
    ╭─[/Users/shuther/Documents/devP/web-main1/package.json:38:1]
 38 │   ],
 39 │   "packageManager": "bun@v1.1.10"
    ·                     ──────┬──────
    ·                           ╰── invalid `packageManager` field

```

So I tried to downgrade the migration using:
px @turbo/codemod migrate --to 2.0.9

but I am getting:
```
? Where is the root of the repo to migrate? .
No codemods required to migrate from 2.0.11 to 2.0.9 

Upgrading turbo from 2.0.11 to 2.0.9 (no codemods required) 

Upgrading turbo with yarn add turbo@2.0.9 --dev -W 

Migration failed
Unable to upgrade turbo: Error: Command failed: yarn add turbo@2.0.9 --dev -W
error This project's package.json defines "packageManager": "yarn@bun@v1.1.10". However the current global version of Yarn is 1.22.22.

Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
```

The yarn downgrade is a known issue.
The package manager is not picked up properly.
Migration fails.

### Expected Behavior

downgrade should work.

### To Reproduce

Source of the project was: https://github.com/saasfly/saasfly
then:
`npx @turbo/codemod migrate`

**Comment by anthonyshew** [comment]
This is an unfortunate yarn bug, from deep in the archives: https://github.com/yarnpkg/yarn/issues/9015
