### ISSUE TITLE
svg with fragment not support

### ISSUE THREAD

**Issue by hhniao** [vercel/turbo#8950]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://codesandbox.io/p/devbox/new-night-8nwzdf

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

dont know

### Describe the Bug

Module not found: Can't resolve './fonts/slick.svg#slick'
![image](https://github.com/user-attachments/assets/375e366a-8d55-4dd1-bcc2-c4a06d0db236)

### Expected Behavior

currect load svg

### To Reproduce

https://codesandbox.io/p/devbox/new-night-8nwzdf
the docs label

### Additional context
update package.json then is work
```
	"scripts": {
		-- "dev": "next dev --turbo",
		++ "dev": "next dev",
	}
```
or update node_modules/slick-carousel/slick/slick-theme.css 
```
-- url('./fonts/slick.svg#slick')
++ url('./fonts/slick.svg') 
```
so it is mean turbo not support *.svg#fragment?
_No response_

**Comment by Netail** [comment]
Related to https://github.com/vercel/next.js, not turbo

**Comment by hhniao** [comment]
> Related to https://github.com/vercel/next.js, not turbo
@Netail 
hi, 
update package.json then is work
```
	"scripts": {
		--   "dev": "next dev --turbo",
		++ "dev": "next dev",
	}
```
or update node_modules/slick-carousel/slick/slick-theme.css 
```
--   url('./fonts/slick.svg#slick')
++ url('./fonts/slick.svg') 
```
so it is mean turbo not support *.svg#fragment?

**Comment by Netail** [comment]
> > Related to https://github.com/vercel/next.js, not turbo
> @Netail 
> hi, 
> update package.json then is work
> ```
> 	"scripts": {
> 		-- "dev": "next dev --turbo",
> 		++ "dev": "next dev",
> 	}
> ```
> or update node_modules/slick-carousel/slick/slick-theme.css 
> ```
> -- url('./fonts/slick.svg#slick')
> ++ url('./fonts/slick.svg') 
> ```
> so it is mean turbo not support *.svg#fragment?
> 
> can you forward to nextjs? if is nextjs problem?

I mean, Turbopack has moved to the next.js repo. This repository is only turborepo now

**Comment by hhniao** [comment]
@Netail 
hi,
https://github.com/vercel/next.js
report bug to this repo?
ok, i got it.
