### ISSUE TITLE
Development not running in interactive mode

### ISSUE THREAD

**Issue by osvald0** [vercel/turbo#8951]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/osvald0/turborepo-rn-web-issue

### What package manager are you using / does the bug impact?

Yarn v2/v3/v4 (node_modules linker only)

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

turbo@npm:2.0.12-canary.3

### Describe the Bug

I can't run the turbo project in interactive mode. So, it's impossible to run the app in the simulators.  I can reproduce the issue with the with-react-native-web example.

### Expected Behavior

I should be able to enter interactive mode by pressing the enter key. Then, I should be able to run iOS by pressing the "I" key, for example.

### To Reproduce

1- Download the example project.
2- Install packages.
3- Run "yarn run dev".

**Comment by chris-olszewski** [comment]
If I add [`"ui": "tui`](https://turbo.build/repo/docs/reference/configuration#ui) to the `turbo.json` in your reproduction, then I'm able to interact with task:


https://github.com/user-attachments/assets/bf6730c5-dc49-4397-bcbb-1cdb96b97e18

What terminal are you using? If you could add `-vv 2> /tmp/turbo_logs.txt` to your `dev` script, attempt to interact with the task, and then include that file here, that would help me debug.

**Comment by osvald0** [comment]
Thanks @chris-olszewski. I missed the  `ui` property.
