### ISSUE TITLE
create-turbo not working

### ISSUE THREAD

**Issue by langley-enduir** [vercel/turbo#8968]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

N/A

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

(empty)

### Describe the Bug

npx create-turbo is not working. Running `npx create-turbo` using the latest and canary versions prompts with "Where would you like to create your Turborepo?" then fails while downloading with error ">>> no "package.json" found at"

### Expected Behavior

`npx create-turbo@latest -e with-vite -m npm` needs to create a new local repo using the "with-vite" template.

### To Reproduce

Run `npx create-turbo@latest`.

### Additional context

This was working earlier today, and suddenly stopped working, 

https://github.com/user-attachments/assets/6a135a56-6efe-472e-82bc-4e2bf5427aca

**Comment by nikita-rudenko** [comment]
Same issue occurs to me.

**System:** Mac OS.
**Package manager:** both npm and pnpm.

I tried:
- `turbo daemon restart`
- `turbo daemon clean`
- clearing npx cache
- moving away all other repos that use Turborepo next to my dir
